### ISSUE TITLE
Create vcpkg port

### ISSUE THREAD

**Issue by sdcb** [Microsoft/cppwinrt#1]
Install from vcpkg would be very convenience.
https://github.com/Microsoft/vcpkg

**Comment by sgreenlay** [comment]
Added a cppwinrt port over in the vcpkg repo: https://github.com/Microsoft/vcpkg/pull/154

**Comment by kennykerr** [comment]
Yes, we would like to offer both vcpkg and nuget support. Thanks for the feedback!

**Comment by BrentRe** [comment]
Just to clarify, we are currently not committing to providing vcpkg or nuget support. I personally prefer to dedicate resources to adding more features to C++/WinRT, e.g. authoring WinRT classes, XAML support, and so on.

However, this is a great area where the community can help out - as I see 'sgreelay' has already done for vcpkg. Thank you! There is one small bug in the vcpkg request. I've left a comment there.

**Comment by BrentRe** [comment]
vcpkg support for cppwinrt now available in the Microsoft/vcpkg repo.
