### ISSUE TITLE
feature requested: add helper function to get hresult message

### ISSUE THREAD

**Issue by seven-mile** [microsoft/cppwinrt#1007]
Until now we can't fetch error message string from `winrt::hresult` directly, but generally `winrt::hresult_error` contains message data. So we can indeed use a workaround:

```cpp
winrt::hresult hr;
try {
    winrt::throw_hresult(hr);
} catch (const winrt::hresult_error &e) {
    display(e.Message());
}
```

That's because, as far as I known, cpp/winrt already have ability to fetch error message from calling some raw COM interfaces. But it's weird to use exception to do this thing. cpp/winrt can easily provide a helper function for it. What do you think?

**Comment by sylveon** [comment]
You can manually call `FormatMessage` to get the error message for an HRESULT. Also, no need to throw the exception: `winrt::hresult_error(hr).message()`

**Comment by seven-mile** [comment]
Thank you! I somehow didn't notice this constructor. This works well.
