### ISSUE TITLE
Proper placement of IAsyncAction in .h file & .cpp file

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#101]
I have this in the .h header
       static IAsyncAction ReadDataBase();
and this in the source .cpp
      IAsyncAction  DataBase::ReadDataBase() {
...
}

The compiler doesn't like it but I'm at a loss on how to correct it.

**Comment by bigdimboom** [comment]
Need a quick tutorial about : 1. how to quickly setup c++/WinRT UWP app in visual studio 2. how to do file management and compilation rules for .h and .cpp files in C++/WinRT 2. how to find the documentation for C++/WinRT APIs. and C++/WInRT programming model.

**Comment by JackDetrick** [comment]
Poor error message - cause: missing code in the body
