### ISSUE TITLE
test_vector_concurrency iterator invalidation case fails occasionally

### ISSUE THREAD

**Issue by dfields-msft** [microsoft/cppwinrt#1012]
The `test_vector_concurrency` test typically passes, but may occasionally encounter the [following failure](https://microsoft.visualstudio.com/Dart/_build/results?buildId=38770724&view=logs&j=9d906afe-3eb5-5d79-316d-86f3f3fa360c&s=d654deb9-056d-50a2-1717-90c08683d50a&t=9e4318d3-5f72-5045-a68e-f107ae8db597&l=6408):
```
-------------------------------------------------------------------------------
multi_threaded_vector
-------------------------------------------------------------------------------
D:\a\1\s\test\test\multi_threaded_vector.cpp(455)
...............................................................................

D:\a\1\s\test\test\multi_threaded_vector.cpp(419): FAILED:
  CHECK( conditional_unbox<T>(t) == 1 )
with expansion:
  42 == 1

===============================================================================
test cases:   80 |   79 passed | 1 failed
assertions: 2864 | 2863 passed | 1 failed
===============================================================================
```

It's not immediately clear whether this is a problem with the product code, or the test code. This failure may have been masked for a while due to the fact that until #1011, test failures would be silently ignored and not fail the build pipeline.

@kennykerr FYI

**Comment by kennykerr** [comment]
@dunhor does that test look familiar?

**Comment by kennykerr** [comment]
I'm guessing this is a test bug but I'll leave it unless it starts making more noise.
