### ISSUE TITLE
convertible_observable_vector::IndexOf slows debugging because it uses exceptions in a non-exceptional case

### ISSUE THREAD

**Issue by mcooley** [microsoft/cppwinrt#1013]
We have a scenario where some code in XAML repeatedly calls IObservableVector::IndexOf, where `value` is a different type than the container items. That causes hresult_no_interface to be thrown and caught internally within cppwinrt many times [in this code](https://github.com/microsoft/cppwinrt/blob/05737b0ce1e129f07f784bb9eb461ea6a3cf7bd7/strings/base_collections_vector.h#L107).

All of these exceptions cause ~1s pauses in the debugger and make it difficult for the developer to be productive if they have first-chance exceptions turned on.

It appears that since #695 was merged, IInspectable.try_as is equivalent (?) to unbox_value and could be used in the implementation of IndexOf to avoid this. (Is that true, or did I miss some nuance there?)

**Comment by kennykerr** [comment]
@oldnewthing

**Comment by kennykerr** [comment]
Something like this should avoid the exception:

```C++
bool IndexOf(Windows::Foundation::IInspectable const& value, uint32_t& index) const
{
    auto unbox = value.try_as<T>();

    if (unbox)
    {
        return IndexOf(unbox.value(), index);
    }
    else
    {
        return false;
    }
}
```

**Comment by mcooley** [comment]
I played around with this a bit more and ran into two nuances:
1) The `auto`-returning version of ` try_as<T>`  can return `std::optional<T>`  or a reference type for `T`. One has .value(), the other doesn't. The only uniform way to get a `T` out in both cases is to use the `bool`-returning version of `try_as<T>`.
2) `value` can be null, and that's a case where `try_as` returns false but we need to search the collection anyway.

So the result ends up a little uglier, maybe something like this...

```
if constexpr(std::is_convertible_v<std::nullptr_t, T>)
{
    if (!value)
    {
        return IndexOf(T{nullptr}, index);
    }
}

T unboxedValue;
if (value.try_as(unboxedValue))
{
    return IndexOf(unboxedValue, index);
}
else
{
    index = 0;
    return false;
}
```

**Comment by kennykerr** [comment]
Of course, the following should cover both cases:

```C++
bool IndexOf(Windows::Foundation::IInspectable const& value, uint32_t& index) const
{
    if constexpr (is_com_interface_v<T>)
    {
        return IndexOf(value.try_as<T>(), index);
    }
    else
    {
        if (auto box = value.try_as<T>())
        {
            return IndexOf(box.value(), index);
        }
        else
        {
            return false;
        }
    }
}
```

**Comment by kennykerr** [comment]
It's a little more complicated but here's a fix with some tests to cover the different scenarios: #1017

**Comment by kennykerr** [comment]
2.0.210913.7 has now been published with this fix.
