### ISSUE TITLE
what are winrt::composing and winrt::composable ?

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#1016]
I don't understand `winrt::composing` and `winrt::composable`?,  where can i find any documents?

i need to resolve a problem:
`idl` define:
```
interface IOnly
{
    ...
}

unsealed runtimeclass Only : IOnly
{
     Only(Object inner);
}

```
namespace winrt
{
      class HotKey : public winrt::implements<HotKey, composing, Only, IClosable>
      {
      }
}

if i did not authorize a runtime class `HotKey `, how can i compose `Only`  runtime class?

**Comment by kennykerr** [comment]
@DefaultRyan

**Comment by kennykerr** [comment]
I would highly recommend letting C++/WinRT implement this for you (rather than using `implement` directly) via the `-component` flag. It knows where these markers go - I don't recall as its a rather complicated dance.

**Comment by DefaultRyan** [comment]
I'm a bit late to the party, but the short of it is that a WinRT type that can be instantiatable as a base class across the ABI boundary, is referred to as _composable_ in WinRT parlance. One part of implementing this scheme uses [COM Aggregation](https://docs.microsoft.com/en-us/windows/win32/com/aggregation), which requires lighting up some extra logic in both the base (inner) class and the derived (outer) class.

`winrt::composable` is generated by cppwinrt to mark that a type can function as a composable base class, and `winrt::composing` is generated by cppwinrt to mark that a type is subclassing a composable bass class. Both of these light up the extra COM aggregation logic needed for this scenario, and you should avoid using them manually.
