### ISSUE TITLE
Request for Tutorial: Visual Studio settings, .h  and .cpp rules, file create, read and write 

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#102]
Need a quick tutorial about : 1. how to quickly setup c++/WinRT UWP app in visual studio 2. how to do file management and compilation rules for .h and .cpp files in C++/WinRT 2. how to find the documentation for C++/WinRT APIs. and C++/WInRT programming model.

**Comment by bigdimboom** [comment]
https://kennykerr.ca/2016/10/24/cppwinrt-getting-started/
