### ISSUE TITLE
Error trying to build a project with WinUI 2.7

### ISSUE THREAD

**Issue by MattBDev** [microsoft/cppwinrt#1020]
I have been trying to add WinUI 2.7 using XAML Islands to my Win32 application. I followed the steps from the Microsoft Docs website and I also took a look at TranslucentTB since they are using it successfully. During the project build I am getting the error:
`C:\Users\MattB\source\repos\notepad-plus-plus\PowerEditor\MyUWPApp\Generated Files\winrt\base.h(2544,39): error C2039: 'Release': is not a member of 'winrt::MyUWPApp::XamlMetaDataProvider'`
The error occurs in base.h of winrt. Specifically this section of code:
``` 
        WINRT_IMPL_NOINLINE void unconditional_release_ref() noexcept
        {
            std::exchange(m_ptr, {})->Release();
        }
```
[In the gist at this link](https://gist.github.com/MattBDev/7ce905dc579b68716b6b7117b13e561f) I have included the error and some relevant files.
It doesn't seem to matter which Minimum Platform version or Target version I am using but I have it set at a minimum of 10.0.18362.0 and a target of 10.0.22000.0.

**Comment by Link1J** [comment]
`winrt::MyUWPApp::XamlMetaDataProvider` is the C++/WinRT projection type, so it doesn't need to be wrapped in a `winrt::com_ptr`. 

Here's the version of `App_baseWithProvider`, based on the one from the Windows Terminal.
```cpp
template<typename D, typename... I>
struct App_baseWithProvider : public App_base<D, ::winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider>
{
    using IXamlType = ::winrt::Windows::UI::Xaml::Markup::IXamlType;

    IXamlType GetXamlType(::winrt::Windows::UI::Xaml::Interop::TypeName const& type)
    {
        return _appProvider.GetXamlType(type);
    }

    IXamlType GetXamlType(::winrt::hstring const& fullName)
    {
        return _appProvider.GetXamlType(fullName);
    }

    ::winrt::com_array<::winrt::Windows::UI::Xaml::Markup::XmlnsDefinition> GetXmlnsDefinitions()
    {
        return _appProvider.GetXmlnsDefinitions();
    }

private:
    bool _contentLoaded{ false };
    winrt::<App Namespace Here>::XamlMetaDataProvider _appProvider;
};
```

**Comment by sylveon** [comment]
The documentation [still suggests](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp#add-code-to-the-uwp-app-project) to use the com_ptr based one, and it does compile fine in my project, SDK 22000, because that ends up picking the implementation type (which can and should be used with com_ptr) due to namespace scoping rules. This is probably an issue somewhere else, it seems that the implementation type isn't being picked up by the compiler (missing include or broken include order?)

**Comment by kennykerr** [comment]
This looks like Xaml code gen. If so, please follow up with the Xaml team here:

https://github.com/microsoft/microsoft-ui-xaml
