### ISSUE TITLE
[Question]How can I initialize the base class without default constructor?

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#1024]
`idl`
```
[default_interface]
unsealed runtimeclass ActionControl : Microsoft.UI.Xaml.Controls.ContentControl
{
	ActionControl(String key);
}

[default_interface]
runtimeclass Xaml_StartProcess : ActionControl
{
	Xaml_StartProcess(String key);
}
```

`projection class`

```
struct Xaml_StartProcess : Xaml_StartProcessT<Xaml_StartProcess>
{
	Xaml_StartProcess(hstring const & key) : implements_type(key){}
};
```
i try to add implements_type, but
compile error: `illegal member initialization: 'implements_type' is not a base or member`

**Comment by sylveon** [comment]
Check out [this](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#deriving-from-a-type-that-has-a-non-default-constructor)

**Comment by shelllet** [comment]
> Check out [this](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#deriving-from-a-type-that-has-a-non-default-constructor)

thx!
