### ISSUE TITLE
[Qustion] Unable to initialize the base class of projected type.

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#1027]
```
namespace Velkhana
{
  [default_interface]
  unsealed runtimeclass Only{
    Only(Object inner);
    ....
  }
}
```
**local class:**
```
class Only2 : public winrt::implements<Only2, Velkhana::Only>
{
	Only2() : implements_type(box_value(true)) {

	}
};
```
why can't i init base class in this case?

![image](https://user-images.githubusercontent.com/16729017/134896723-23bea986-5fcd-4f55-ab3b-e83b57718292.png)

and another qustion:

i analyzed the source code, but don't find `winrt::implements` constructor, how ` local class` initializes the grandparent class by `implements_type` ?
Is there any trick here?

**Comment by kennykerr** [comment]
For general questions you're better off using https://stackoverflow.com/ - this issues page is just for cppwinrt bugs. 

@DefaultRyan may be able to help though - he's more familiar with the composable machinery.
