### ISSUE TITLE
VSIX references templates from the Universal Windows Platform workload

### ISSUE THREAD

**Issue by daviddetweiler** [microsoft/cppwinrt#1028]
Repro steps: install Visual Studio 2019 Community, enable only the Game Development workload. Download the latest C++/WinRT VSIX, install it. Now open Visual Studio and attempt to create a project with the C++/WinRT Desktop Application template. I recall that the extension referenced the Universal Windows Platform workload as a dependency at one point, but it clearly doesn't anymore.

**Comment by kennykerr** [comment]
I think that's a known issue with the existing VSIX but the next version is baked into the VS installer and should thus have the dependencies sorted out correctly.
