### ISSUE TITLE
Is this project in maintenance mode? What's the future?

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/cppwinrt#1029]
What is the situation with this extension? Is this functionality going to be incorporated into Windows App SDK and Visual Studio?

I'm asking for two reasons:

1) There is an issue with it not providing a way of creating runtime classes clearly. The only way I see is to use the terribly named and even more terribly described ViewModel template. So should we look here for a fix or in the Windows App SDK or Visual Studio?

2) There is an issue with the lack of an automated configuration system in VS projects, which means this is an extra dependency that needs to be communicated to a recipient of a VS project, as they need to manually install it. That is a huge friction point for some scenarios, such as education settings, where we can't expect markers to have this extension installed, and can't expect them to install it. So again, knowing the fate of this extension helps understand how this can be fixed. Will this issue be fixed as a natural consequence of it's functionality being integrated into WindowsAppSDK / Visual Studio? Or is this extension going to be maintained going forward, making the existence of this extension a blocking issue for using C++/WinRT in education settings.

**Comment by sylveon** [comment]
The Windows App SDK VSIX extension provides templates (including a runtime class one) for WASDK apps. C++/WinRT's templates are for UWP.

The C++/WinRT VSIX extension is not needed for building and running C++/WinRT UWP or WA SDK-based apps apps. The extension only provides templates for UWP projects. All the build support is in the NuGet package, which does get automatically acquired and installed when building a project.

There is work to integrate the C++/WinRT extension into Visual Studio being done, but my guess is that it's being done for LTS, not any future improvement. All the investment is in WA SDK now.

**Comment by Gavin-Williams** [comment]
OK, thank you. I had some pretty serious issues with trying to use a UWP app for a Uni project. Which I talked about over on Discord and in a forum. My Uni doesn't have any configuration or workloads installed for UWP, and I think I really pissed off my teacher with the installs and configuration needed - like him having to install UWP workload on his surface tablet to debug my project. And he was even annoyed by having to set Dev mode in Windows. I don't see the fuss myself, but I'm just the messenger here. It seems to be difficult to expect people to perform these manual setups just to debug a project.

I'm happy to hear that integration for the Windows App SDK scenario is going on. I will probably be using that eventually. Just waiting for it to be ready really.
