### ISSUE TITLE
Recompiled header problem.

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#103]
I keep getting the compliant of "fatal error C1010: unexpected end of file while looking for recompiled header. Did you forget to add '#include "pch.h"' to your source?" from compiler. What I'm trying to do is separate .h and .cpp files in my UWP project. I thought C++/WinRT does support standard c++. How do I fix this.

**Comment by bigdimboom** [comment]
one solution: disable this in visual studio:
![image](https://cloud.githubusercontent.com/assets/6119906/22893090/bdd042ae-f1e2-11e6-94d7-90c55c019736.png)

**Comment by KevinWelton** [comment]
If you don't want to use precompiled headers, you are doing the right thing.

**Comment by BrentRe** [comment]
If you *want* to use the pre-compiled headers option, you need to #include "pch.h" in every .cpp file.

As an aside, precompiled headers are an option with the Microsoft C++ compiler. See https://msdn.microsoft.com/en-us/library/szfdksca.aspx for details.

Nothing differs in this regard when using C++/WinRT headers.

**Comment by walbourn** [comment]
The only caveat here is that you probably really _want_ to be using pre-compiled headers since C++/WinRT headers are quite large and complex.
