### ISSUE TITLE
wrong command injection when compiling legacy midl file

### ISSUE THREAD

**Issue by seven-mile** [microsoft/cppwinrt#1033]
When using Visual Studio with CppWinRT, it automatically generate a reference list file `MyProj.vcxproj.midlrt.rsp`.

Then every time VS is to compile an IDL file, it injects something like `@".\dir\MyProj.vcxproj.midlrt.rsp"` in front of the filename, which makes the command like this: `midl.exe /some_options @".\dir\MyProj.vcxproj.midlrt.rsp" filename.idl`.

This logic works well with MIDL 3.0 file (modern idl to be used in WinRT), but breaks the compiling of legacy idl files.

For my instance, the generated final compiling command is

```
midl.exe /W1 /nologo /char signed /env x64 /h "Example.h" /dlldata "dlldata.c" /iid "Example_i.c"
/proxy "Example_p.c" /notlb /client stub /server none /enum_class /ns_prefix /target "NT60"
 @"x64\Debug\MyProj.vcxproj.midlrt.rsp" Example.idl
```

Then error:

```
1>    midl : command line warning MIDL1008: unknown switch "ns_prefix"
// comment: then it indeed read from .midlrt.rsp file and appended reference options
1>    midl : command line warning MIDL1008: unknown switch "reference"
... (many reference warnings)

1>    midl : command line warning MIDL1009: unknown argument ignored "Example.idl"
                                                                      ^^^^^^^^^ my idl file was ignored!

// then tried parsing a binary winmd file, failed.
1>    64 bit Processing ?????\Microsoft.ApplicationModel.Resources.winmd
1>    Microsoft.ApplicationModel.Resources.winmd
1>    ?????\Microsoft.ApplicationModel.Resources.winmd(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>    ?????\Microsoft.ApplicationModel.Resources.winmd(1): error MIDL2025: syntax error : expecting an interface name or DispatchInterfaceName or CoclassName or ModuleName or LibraryName or ContractName or a type specification near "MZ"
1>    ?????\Microsoft.ApplicationModel.Resources.winmd(1): error MIDL2026: cannot recover from earlier syntax errors; aborting compilation
1>    The command exited with code 2026.
```

As you can see, the filename in my project is ignored. I do know `midl.exe` process both legacy and modern idl based on its own detection, and I guess the two modes differ in the way of processing command parameters?

I've tried put the `filename` parameter in front or remove the injected parameter and executed the command, and it just worked.

A typical modern idl compiling command is

```
midl.exe /metadata_dir "..." /winrt /W1 /nologo /char signed /env x64 /winmd "..."
/h "nul" /dlldata "nul" /iid "nul" /proxy "nul" /notlb /client none /server none
/enum_class /ns_prefix /target "NT60"  /nomidl
@"x64\Debug\MyProj.vcxproj.midlrt.rsp" Example.idl
```

It is not very different from mine. I have no idea which switch makes midl.exe accept the argument after injected rsp file.

Generally, shouldn't cppwinrt ignore legacy idl using detection from midl.exe? Or in fact midl.exe should take the responsibilities of misreading the command?

Hmm... At least I think we shouldn't compile a legacy idl with `.midlrt.rsp` references. So I submitted this issue to cpp/winrt repo.

**Comment by sylveon** [comment]
There's no actual way to differentiate modern IDL and legacy IDL from the VS project system, so this is not unexpected.

**Comment by seven-mile** [comment]
> There's no actual way to differentiate modern IDL and legacy IDL from the VS project system, so this is not unexpected.

Then how about generate commands like `midl.exe [filename] /options [injected reference list]`? Or the only workaround may be config the midl build by ourselves...

**Comment by kennykerr** [comment]
You're probably better off writing your own custom build logic, unless you can convince @jlaanstra to take a look.

**Comment by jlaanstra** [comment]
We don't support mixing modern and legacy idl in the same project today. You might to able to make it work using static libraries where on project has modern IDL and the other has legacy idl.
