### ISSUE TITLE
Inquiry about winrt::init_apartment

### ISSUE THREAD

**Issue by kdewald** [microsoft/cppwinrt#1034]
Hi!

I'm currently working on a cross-platform BLE library and I'm running into an issue with `winrt::init_apartment()` where I cannot seem to find enough documentation about the function to understand what is going on.

From my prior understanding of this topic on a past project I worked on, it was necessary to call `winrt::init_apartment()` to ensure any WinRT calls would actually work. Because of that, I made it on my current project that the first function the user runs will call `winrt::init_apartment()` to set everything up. (Link to that part of the code: https://github.com/OpenBluetoothToolbox/SimpleBLE/blob/fe4c932e0784fa2905f654d0c0b293e389963b1d/src/windows/AdapterBase.cpp#L46)

However, I had two cases of users of the library report to me that when calling the library from Python or Unity, that function would assert and cause the program to crash: https://github.com/OpenBluetoothToolbox/SimpleBLE/issues/21

I haven't been able to replicate the problem on my end, and I just discovered that everything seems to work without making any calls to `winrt::init_apartment()`, so I'm struggling to understand exactly what is going on.

- Do I need to call `winrt::init_apartment()`? If so, when?
- What happens if I call this function as part of another environment (like Python or Unity)?
- Is there a way I can know if I need to call this function or not?

Any additional help or documentation would be very useful.

Thanks!

**Comment by Jaiganeshkumaran** [comment]
@kdewald winrt::init_apartment() is simply a wrapper on WinRT RoInitialize (which also calls COM's CoInitializeEx I beleive). If it works without you needing to call winrt::init_apartment(), most probaly WinRT is already initialized on the calling thread and you don't need it.

**Comment by sylveon** [comment]
There's is an implicit MTA on process startup

**Comment by kennykerr** [comment]
`init_apartment` is just a helper function that calls `CoInitializeEx` and throws an exception on failure. Whether to call this function is a difficult question to answer in general. If you're not sure, just don't call it. 

I would suggest you discuss this further on https://stackoverflow.com/.

**Comment by YexuanXiao** [comment]
> There's an implicit MTA on process startup

Who initialized COM, the CRT? Is this documented?

**Comment by sylveon** [comment]
C++/WinRT: https://github.com/microsoft/cppwinrt/blob/16a1c29b5351ca5212f4235d1db5776bdd13ae78/strings/base_activation.h#L31

**Comment by YexuanXiao** [comment]
> C++/WinRT:
> 
> [cppwinrt/strings/base_activation.h](https://github.com/microsoft/cppwinrt/blob/16a1c29b5351ca5212f4235d1db5776bdd13ae78/strings/base_activation.h#L31)
> 
> Line 31 in [16a1c29](/microsoft/cppwinrt/commit/16a1c29b5351ca5212f4235d1db5776bdd13ae78)
> 
>  if (hr == impl::error_not_initialized)

What is the function of CoIncrementMTAUsage? Is it necessary to have an existing MTA before calling it?

**Comment by sylveon** [comment]
> CoIncrementMTAUsage creates the MTA, if the MTA does not already exist. CoIncrementMTAUsage puts the current thread into the MTA, if the current thread is not already in an apartment

**Comment by YexuanXiao** [comment]
> > CoIncrementMTAUsage creates the MTA, if the MTA does not already exist. CoIncrementMTAUsage puts the current thread into the MTA, if the current thread is not already in an apartment

I don't fully trust Windows documentation; it often lacks edge cases. Especially the documentation for APTTYPEQUALIFIER does not mention that CoIncrementMTAUsage can cause this result. In my tests, the main function initially is none, and after calling CoIncrementMTAUsage, the main becomes implicit MTA.  I want to know which thread actually initialized as MTA.

**Comment by kennykerr** [comment]
The documentation @sylveon cited is accurate.
