### ISSUE TITLE
Expose winrt::impl::hstring_builder as winrt::hstring_builder

### ISSUE THREAD

**Issue by lhecker** [microsoft/cppwinrt#1035]
`winrt::impl::hstring_builder` is a rather useful class. It can be used as the out parameter for various Win32 methods, avoiding the need for extra intermediate copies. The idea of making it public was also suggested in #1018.

Would it be feasible to create a public alias of `hstring_builder`?

**Comment by lhecker** [comment]
Ah okay... yeah but that's fine in this case, isn't it? Member functions called `data()` almost always return raw pointers including for boundary-checked classes like `std::vector`. Apart from the finalizing `to_hstring()`, the `hstring_builder` has no other member functions. Adding boundary checked iterators to the class in the future should thus be possible I believe.

**Comment by DHowett** [comment]
Is there a version of those things that automatically manages an `HSTRING_REFERENCE` to effect a zero-copy hstring?

**Comment by kennykerr** [comment]
There is a public API for this. You can simply call `WindowsPreallocateStringBuffer`/`WindowsPromoteStringBuffer`/`WindowsDeleteStringBuffer`.
