### ISSUE TITLE
Recommendation on threads

### ISSUE THREAD

**Issue by qian256** [microsoft/cppwinrt#1039]
In a C++/WinRT project, if i have need to have "a background thread" constantly working on something using a while loop. Is it better to implement it using:
1. recursive IAsyncAction (calling itself before returning)
2. implement the while loop in IAsyncAction (after winrt::resume_background())
3. use std::thread to directly open a thread

Is there any performance difference with these three solutions?
I understand this may not be correct place for this question. But i am looking forward for answers from the experts here!

**Comment by sylveon** [comment]
I would say 3. The first and second options constantly use up a thread of the thread pool.

Whichever option you pick, be careful about synchronization, agility, and keep a strong reference alive (or a weak one which you resolve every loop iteration, terminating the thread once it fails to resolve).

**Comment by kennykerr** [comment]
https://stackoverflow.com/ is a good place for such questions.
