### ISSUE TITLE
Generate consuming projection from IDL within the same project

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#1048]
Currently, cppwinrt only supports generating a projection that produces components (the user implements the APIs) when you add an IDL file to a project. You can't add an IDL file coming from a third-party or generated by `winmdidl` to your project and then consume the API described in the IDL file, as all static methods and constructors will not be generated in the headers, resulting in linker errors. cppwinrt is expecting a `.g.cpp` file to implement them, but this file is never used because the type is never actually implemented in the project (we want to consume the type, not implement it).

Adding the output of winmdidl to a project to consume APIs might be desirable in some cases, like if you would like to avoid checking in .winmd binaries to a git repo.

There should be a way to tell cppwinrt to generate a consuming projection of the IDL within that project, instead of a producing projection.

In #1041, @jlaanstra mentionned this:
> I agree. It might be a bit before I have time to add support. I'm thinking to support metadata on an idl file that we can use to split idl files in two groups. Group 1 will work as today, while Group 2 will generate a reference projection. That way the changes are mostly additive and will have the least amount of impact on existing projects.

**Comment by ChrisGuzak** [comment]
I came up with a solution that is a bit cumbersome but workable. 
1) create a new C++ WinRT component project, delete everything but the .idl file. Optionally trim the .sln and .vcxproj files to a single build, strip out most options that are no not needed.
2) In consuming projects add the `ItemGroup` below **or** package the .winmd file into a .nuget and consume it from that. This has a better workflow in the IDE, not requiring editing the .vcxproj.

```xml
  <ItemGroup>
    <Reference Include="Windows.winmd">
      <IsWinMdFile>true</IsWinMdFile>
      <HintPath>..\InternalSdk\$(Platform)\$(Configuration)\InternalSdk\WindowsUdk.winmd</HintPath>
    </Reference>
  </ItemGroup>
```

**Comment by sylveon** [comment]
Ended up using that solution, worked great besides a few hiccups related to some custom build stuff expecting a DLL.
