### ISSUE TITLE
try to play with the camera/media API, it never the async operation never returns. 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#105]
![image](https://cloud.githubusercontent.com/assets/6119906/22937070/65c84dcc-f2a5-11e6-950e-0975c4ca9249.png)

launch it:
![image](https://cloud.githubusercontent.com/assets/6119906/22937081/74a8468a-f2a5-11e6-8308-2d9ee633e378.png)

unless I'm doing something wrong.
BTW, WinRT API for C++/CX works

**Comment by BrentRe** [comment]
What version of VS are you using? There's a bug in the co-routine support in VS 2015 Update 3 C++ compiler, where the compiler, in certain circumstances, fails to inject a co_return statement in all the appropriate locations. You code doesn't look like it hits that case. However, try adding a co_return; statement at the end of the comsume() method and let us know if that fixes it.

**Comment by bigdimboom** [comment]
Thank you for the reply Brent. I'm using VS 2015 Update 3. Tried adding "co_return" at the end of that method. I also tried the invoking the blocking method on "FindAllAsync(), it didn't work.

**Comment by BrentRe** [comment]
I get the same results using VS 2017 RC.3 (no return). I know nothing about this particular API (e.g. do media services need some other initialization before this will work and so on).

Can you provide the CX code that does work?  I'll look into it.

**Comment by bigdimboom** [comment]
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/CameraFrames/cpp/Scenario1_DisplayDepthColorIR.xaml.cpp
![image](https://cloud.githubusercontent.com/assets/6119906/22942136/47e3e7e2-f2b6-11e6-82f9-4ad0c2fc3e60.png)

**Comment by bigdimboom** [comment]
I think I have found the problem. the program has thrown out "winrt::hresult_access_denied" exceptions. How do I access cameras without getting block.

**Comment by bigdimboom** [comment]
Found the issue. We need enable circled item: 
![image](https://cloud.githubusercontent.com/assets/6119906/22949324/e1c8e38a-f2cf-11e6-9656-2cb7ace80582.png)

**Comment by Scottj1s** [comment]
Even with enabling the webcam capability, you will probably still find that consume().get() never returns.  This is because it's being called on the UI (STA) thread, and thus blocks the await object's completion handler from being scheduled back to that thread, causing a deadlock.  In the latest release, Windows 10 Creator's Update SDK preview release, we've added a debug-mode assert to detect calls like this.  The solution is to remove the blocking get() from the UI thread, either replacing it with a co_await, or moving it to a background thread.

**Comment by dmarjoram** [comment]
There seems to be a bug introduced in the Creators Update.
I'm actually getting no frame sources returned from a call to MediaFrameSourceGroup.FindAllAsync() when using C#. 

This call worked fine in the anniversary update?

Any ideas?

**Comment by BrentRe** [comment]
Sorry, but we have no expertise in specific Windows Runtime APIs. Let alone using them from C#. This forum is for issues specific to the C++/WinRT language projection.

You might trying asking on the answers.microsoft.com site.  They may have members more experienced with this particular API.

https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware-winpc
