### ISSUE TITLE
dead code with winrt/base.h

### ISSUE THREAD

**Issue by tearosccebe** [microsoft/cppwinrt#1055]
I just include the header and it gives me so much dead code in the assembly. This means some header files should not be included.
```
"??$_Getvals@_W@?$time_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@IEAAX_WAEBV_Locinfo@1@@Z": # @"??$_Getvals@_W@?$time_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@IEAAX_WAEBV_Locinfo@1@@Z"
.seh_proc "??$_Getvals@_W@?$time_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@IEAAX_WAEBV_Locinfo@1@@Z"
# %bb.0:
	pushq	%r15
	.seh_pushreg %r15
	pushq	%r14
	.seh_pushreg %r14
	pushq	%rsi
	.seh_pushreg %rsi
	pushq	%rdi
	.seh_pushreg %rdi
	pushq	%rbx
	.seh_pushreg %rbx
	subq	$80, %rsp
	movq	%rcx, %r14
	leaq	32(%rsp), %rdx
	movq	%r8, %rcx
	.seh_stackalloc 80
	.seh_endprologue
	movq	%r8, %r15
	callq	*"__imp_?_Getcvt@_Locinfo@std@@QEBA?AU_Cvtvec@@XZ"(%rip)
	vmovups	32(%rsp), %ymm0
	vmovups	44(%rsp), %ymm1
	vmovups	%ymm1, 56(%r14)
	vmovups	%ymm0, 44(%r14)
	vzeroupper
	callq	*__imp__W_Getdays(%rip)
	testq	%rax, %rax
	je	.LBB1_2
# %bb.1:
	leaq	40(%r15), %rcx
	movq	%rax, %rdx
	movq	%rax, %rsi
	callq	*"__imp_??4?$_Yarn@_W@std@@QEAAAEAV01@PEB_W@Z"(%rip)
	movq	%rsi, %rcx
	callq	*__imp_free(%rip)
...
...
```

**Comment by kennykerr** [comment]
Sounds like an issue for the C++ compiler/optimizer. I'd check with [Visual Studio](https://developercommunity.visualstudio.com/search?space=62) or https://stackoverflow.com/.

**Comment by tearosccebe** [comment]
no. it has nothing to do with compiler and optimizer. looks like more of problems of msvc stl?

A lot of headers you just should not use tbh.

**Comment by sylveon** [comment]
Then maybe you wanted https://github.com/Microsoft/STL?

**Comment by tearosccebe** [comment]
> Then maybe you wanted https://github.com/Microsoft/STL?

I do not know.
That is exactly what happens when you define things in headers without using inline to ALL functions or defining some global objects.

All things in headers MUST be inline.
