### ISSUE TITLE
Where to get VS 2022 extension?

### ISSUE THREAD

**Issue by dgellow** [microsoft/cppwinrt#1056]
Hi there,

Visual Studio 2022 has been released yesterday, and now I'm wondering how I can install the C++/WinRT extension. On the extension marketplace I can find the [2019 version](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264), but no trace for a 2022 extension. Is it published somewhere else, or am I too early and that's something that will be done in the future?

**Comment by sylveon** [comment]
The extension is built-in in VS 2022

**Comment by dgellow** [comment]
Oh, nice. Thanks for the info. I guess that means the README is out of date.

**Comment by kennykerr** [comment]
fyi @stevewhims

**Comment by stevewhims** [comment]
Thanks for the heads up, all, I've updated the section [Visual Studio support for C++/WinRT, XAML, the VSIX extension, and the NuGet package](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package).

**Comment by pjmlp** [comment]
Apparently the VS 2022 extension provides no progress on "Generated Sources" front and given that reflection has just been dropped from C++23, are we ever getting back the XAML C++/CX development experience back?
