### ISSUE TITLE
An error occurred while calling the base class constructor.

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#1057]
idl define:
```
[default_interface]
unsealed runtimeclass Base{
  Base(Object inner);
}

[default_interface]
runtimeclass GlobalSettings : Microsoft.UI.Xaml.Controls.Page
{
  GlobalSettings();
}
```

```
struct GlobalSettings : GlobalSettingsT<GlobalSettings, implementation::Base>
{
  GlobalSettings(): GlobalSettingsT<GlobalSettings>(box_value(false)) // call base class constructor
  {
  }
}
```

build error:
`
error C2614: 'winrt::Workflow::implementation::GlobalSettings': illegal member initialization: 'GlobalSettingsT<winrt::Workflow::implementation::GlobalSettings>' is not a base or member
`

**Comment by sylveon** [comment]
The current build issue you're seeing is the same as https://github.com/microsoft/microsoft-ui-xaml/issues/3331. However, even if this was fixed, you'd still be unable to build this code, as you cannot use multiple inheritance in WinRT.
