### ISSUE TITLE
Compile error when referencing  2 C# Windows Components that both reference another Windows Component

### ISSUE THREAD

**Issue by jasonxz** [microsoft/cppwinrt#1058]
I have a C++ WinRT application that needs to reference 2 Windows Components that each reference another Windows Component.
Component 1 defines _Interface1_ that is implemented in Component 2 (based on a 3rd-party SDK) which passes the object that implements _Interface1_ back to Component 3 which needs to know about _Interface1_ in order to know what to do with it.

When I try to compile, I get a host of MDM 2009 compile errors as the compiler complains that it's finding a duplicate type (_Interface1_) in the Component1.winmd file that it finds in the bin directories of both Component 2 and Component 3.

More detail here:  https://stackoverflow.com/questions/69922229/c-compiler-error-mdm2009-duplicate-type-found-processing-metadata-file-referen
I also have a repo that shows how to reproduce the errors here:  https://github.com/jasonxz/CppWinRTCompileErrorSample

**Comment by kennykerr** [comment]
@jlaanstra thoughts?

**Comment by jlaanstra** [comment]
In this case you should avoid copying Component1.winmd into the bin folder of Component2 and Component3, Usually using <Private>false</Private> on the project references. This is an unfortunate side effect of how mdmerge works right now.

**Comment by jasonxz** [comment]
I did this in the csproj files for both C2 & C3:
![image](https://user-images.githubusercontent.com/1779069/141528229-086cc5fe-1edd-46fb-abe3-14f58e7a2608.png)
I'm still getting the error.  Is that the wrong setting?  Can we be a little more specific about "using false on the project references"?  Pretty please?

**Comment by jlaanstra** [comment]
Updated my comment. Github was hiding the ```<private>``` tags.

**Comment by jlaanstra** [comment]
Note tht you might need to delete the existing ones. If that doesn't work can you attach an msbuild binlog and I can take a look why it isn't working?
