### ISSUE TITLE
C++/WinRT codegen includes pch.h in module.g.cpp even if precompiled header are turned off

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1061]
I'm trying to migrate to modules from precompiled header, however, C++/WinRT tries to include pch.h in module.g.cpp so it doesn't compile. I've disabled precompiled headers from project properties.

**Comment by kennykerr** [comment]
You can use the `-pch` flag to override this. Run `cppwinrt` without any arguments to see the options listed.

**Comment by sylveon** [comment]
If you're using the NuGet package, it shouldn't already. Make sure that you removed pch.h from your project file. 
https://github.com/microsoft/cppwinrt/blob/bddd2e1303ecdf4c26e4721cc6b66a58b37d9949/nuget/Microsoft.Windows.CppWinRT.targets#L795-L811
