### ISSUE TITLE
Allow async property setter

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1062]
I have a property setter that needs to do some asynchronous operations. So I changed the return type from void to fire_and_forget however now it doesn't compile since the codegen in g.cpp attempts to return it which isn't possible in this case since fire_and_forget can't be returned in a void function.

**Comment by kennykerr** [comment]
Specifically, this is an edge case that only affects static setters when you are compiling with `-opt`. Here's a fix: #1063
