### ISSUE TITLE
Error in verbose mode when argv[0] is not an actual path

### ISSUE THREAD

**Issue by blattersturm** [microsoft/cppwinrt#1064]
If running plain `cppwinrt -v` from a console with the Windows SDK in PATH I get the following error:

```
cppwinrt : error canonical: The system cannot find the file specified.: "cppwinrt.exe"
```

It seems the following line expects argv[0] to be an actual path to `cppwinrt.exe` without the `.exe` specified, which is not necessarily the case (e.g. when running from PATH, but also for example on non-Windows platforms with symlinks or certain kinds of `exec` being used):

https://github.com/microsoft/cppwinrt/blob/e1920949fd38bd168469d0ea665bafafbb775234/cppwinrt/main.cpp#L269-L271

**Comment by kennykerr** [comment]
Good catch. Feel free to contribute a fix, otherwise I'll get to it as soon as possible.

**Comment by triplef** [comment]
Running into this as well whenever requesting verbose output while using cppwinrt.exe from Visual Studio in my PATH.
