### ISSUE TITLE
Feature Request: Expose type T as value_type of several Windows::Foundation::Collections container type

### ISSUE THREAD

**Issue by kiddliu** [microsoft/cppwinrt#1068]
### The problem I'm Trying To Solve
I am new to C++ and find it's difficult to work with following types when using templates.

- [ ] IReference<T>
- [ ] IReferenceArray<T>
- [ ] IVector<T>
- [ ] IVectorView<T>

### Current Solution
I need to work around this by creating different templates in my work. 

### Requested Solution
```cpp
template <typename T>
struct __declspec(empty_bases) IReference :
    winrt::Windows::Foundation::IInspectable,
    impl::consume_t<winrt::Windows::Foundation::IReference<T>>,
    impl::require<winrt::Windows::Foundation::IReference<T>, winrt::Windows::Foundation::IPropertyValue>
{
    using value_type = T;
    // ...
}

template <typename T>
struct __declspec(empty_bases) IReferenceArray :
    winrt::Windows::Foundation::IInspectable,
    impl::consume_t<winrt::Windows::Foundation::IReferenceArray<T>>,
    impl::require<winrt::Windows::Foundation::IReferenceArray<T>, winrt::Windows::Foundation::IPropertyValue>
{
    using value_type = T;
    // ...
}
```

**Comment by kennykerr** [comment]
It's not a bad idea. The problem is that the generic arguments aren't always simply `T` or something that would naturally map to something like `value_type`. It does seem like a problem that you can solve in your library, so I'm inclined to leave this alone.
