### ISSUE TITLE
WinRT originate error ?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#107]
I'm trying to create a FrameReader object reading from a webcam. 
![image](https://cloud.githubusercontent.com/assets/6119906/23000178/3eb4b6f4-f3ad-11e6-84c4-6947f03a8c06.png)

But it throws error:
![image](https://cloud.githubusercontent.com/assets/6119906/23000193/54509910-f3ad-11e6-8f77-9e064162a497.png)

**Comment by BrentRe** [comment]
We have no expertise in the WinRT media APIs. I suggest you try StackOverflow or other appropriate site where experts on those APIs hang out.

**Comment by bigdimboom** [comment]
It turns out that there exceptions have no negative impact on my code. They will appear when I call the StartAsync on cameras, but my cameras can work without error.
