### ISSUE TITLE
C++ WinRT headers not automatically generated for projects with NuGet package on some machines using VS19 or VS22

### ISSUE THREAD

**Issue by sp-rafael-lecina** [microsoft/cppwinrt#1070]
Hi

We recently updated some of our projects to use C++20 and C++/WinRT instead of C++17 and C++/CX

I don't know why (nor how to check why) for some devs using latest releases of VS19 or VS22 C++/WinRT headers are not being automatically generated when they try to build the project. For them VS uses the ones on SDK and they face many compiler errors

Our solutions contain a main project and several library projects
I checked and the NuGet package looks to be properly installed on all of them. We are using Microsoft.Windows.CppWinRT:2.0.210922.5 

Also we are running ``MSBuild.exe -t:restore -p:RestorePackagesConfig=true`` before opening the solutions with VS to be sure nuget packages are properly downloaded/installed

Is there something I can take a look to know why is that happening to them? Or something I may be missing?

**Comment by kennykerr** [comment]
Nothing comes to mind - nuget and msbuild are somewhat brittle in my experience. This is a good tool for debugging msbuild issues: https://msbuildlog.com/

**Comment by sp-rafael-lecina** [comment]
Thank you! I did not know about that tool. Looks quite useful

We've found where the issue comes from...
The headers are failing to be generated for those devs using Incredibuild, so I'm trying to get support from them
Using Visual Studio or MsBuild from command line works fine if they did not try an incredibuild build before (I think some files are left around that avoid generation, because after a full clean it works again without icredibuild)

My guess is that the target ``CppWinRTMakeProjections`` is somehow not being properly executed by Incredibuild. The rsp files containing the list of input winmd files seem to be generated fine but the headers are not generated

Do you want me to update this issue once I get support from Incredibuild people? Or do you prefer to close it?

**Comment by kennykerr** [comment]
Thanks for the follow-up - we can close this issue but feel free to keep the conversation going here so future developers can find it.

**Comment by sp-rafael-lecina** [comment]
Hi
We finally found the issue
Looks like Incredibuild is not scaping properly the call to batch files they generate into the user's temporary folder and one of those files contains the command line for cppwinrt.exe
If that temporary user's folder contains spaces on it the cppwinrt command is not executed, which may happen if the user's folder contain a space on it. That's why it was happening just for some of our devs

This is happening with Incredibuild version 9.6.1 and the issue has been moved to their engineering team so they can work on a solution
