### ISSUE TITLE
Warning c4265 in winrt/base.h

### ISSUE THREAD

**Issue by Acretock** [microsoft/cppwinrt#1071]
In project i work on, we try to be warning free, and with our warning policy, we have this warning: 
```cpp
Warning	C4265
'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncActionCompletedHandler,H>': 
class has virtual functions, but its non-trivial destructor is not virtual; instances of this class may not be destructed correctly	
winrt\base.h	5274
```
also i am not completley sure where to report this, if this is wrong plase to do this, could you help with this?

**Comment by kennykerr** [comment]
Can you provide a minimal repro and let me know which version you're using?

**Comment by Acretock** [comment]
version is `2.0.211028.7`

cant share repo, due to NDA; But i think i can share where this warn comes from, somewhere from here
```cpp
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.Devices.Bluetooth.GenericAttributeProfile.h>
#include <winrt/Windows.Devices.Bluetooth.h>
#include <winrt/Windows.Devices.Enumeration.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Security.Cryptography.h>
#include <winrt/Windows.Storage.Streams.h>
#include <winrt/Windows.System.h>
#include <winrt/Windows.UI.Core.h>
```

**Comment by sylveon** [comment]
See https://devblogs.microsoft.com/oldnewthing/20200618-00/?p=103874 and https://devblogs.microsoft.com/oldnewthing/20200619-00/?p=103877. This warning is normally disabled because it's noisy, and there are many valid use cases (like C++/WinRT's) in which this warning is wrong.

**Comment by kennykerr** [comment]
Yes if you're intentionally turning this warning on, I would suggest you disable it before including C++/WinRT headers.
