### ISSUE TITLE
NuGet package: CppWinRTPrecompiledHeader should be "." when not using PCH

### ISSUE THREAD

**Issue by davidmatson** [microsoft/cppwinrt#1072]
In Microsoft.Windows.CppWinRT.targets, in this part of the code:
```xml
        <PropertyGroup Condition="('$(CppWinRTOverrideSDKReferences)' == 'true') or ('$(TargetPlatformVersion)' &gt; '10.0.17708.0')">
            <CppWinRTUsePrefixes Condition="'$(CppWinRTUsePrefixes)' == ''">true</CppWinRTUsePrefixes>
            <CppWinRTPrecompiledHeader Condition="'$(CppWinRTPrecompiledHeader)' == ''">$(_PCH)</CppWinRTPrecompiledHeader>
        </PropertyGroup>
```

Should likely be something like this:
```xml
            <CppWinRTPrecompiledHeader Condition="'$(CppWinRTPrecompiledHeader)' == '' and '$(UsePCH)' == 'true'">$(_PCH)</CppWinRTPrecompiledHeader>
            <CppWinRTPrecompiledHeader Condition="'$(CppWinRTPrecompiledHeader)' == '' and '$(UsePCH)' == 'false'">.</CppWinRTPrecompiledHeader>
```

(Otherwise, when the project has PCH disabled, the generated code fails to compile.)

**Comment by kennykerr** [comment]
@jlaanstra

**Comment by jlaanstra** [comment]
<CppWinRTPrecompiledHeader Condition="'$(CppWinRTPrecompiledHeader)' == '' and '$(UsePCH)' == 'true'">$(_PCH)</CppWinRTPrecompiledHeader>
            <CppWinRTPrecompiledHeader Condition="'$(CppWinRTPrecompiledHeader)' == '' and '$(UsePCH)' == 'false'">.</CppWinRTPrecompiledHeader>

Why the second line? Not sure why we would set it to a single dot?

**Comment by jlaanstra** [comment]
Actually I can't find anything docs about a UsePCH flag? Where is that coming from?

**Comment by kennykerr** [comment]
On the command line, the `.` means that no precompiled header should be used since the default is `pch.h`.

https://github.com/microsoft/cppwinrt/blob/0be01db74002bcbb6c9bcc3fd6f0ef88961bf71b/cppwinrt/main.cpp#L132

https://github.com/microsoft/cppwinrt/blob/0be01db74002bcbb6c9bcc3fd6f0ef88961bf71b/cppwinrt/main.cpp#L138-L141

**Comment by kennykerr** [comment]
But I have no idea what `UsePCH` is. 😜

**Comment by davidmatson** [comment]
I think that was just pseudo-syntax for "checking whether this project has precompiled headers enabled or not".

Here's the syntax added to the project file when enabling them in VS 2019. (They're off by default, at least for some templates.)
```msbuild
<PrecompiledHeader>Use</PrecompiledHeader>
```

I believe the valid values are Use, Create, or NotUsing. (I'm not sure what Create should do in this case; haven't checked exactly what it means.)

**Comment by kennykerr** [comment]
"Create" means create the PCH whereas "Use" means depend on the previously created PCH. Only the "pch.cpp" would have "Create" while everything else (that depend on the PCH) would have "Use".
