### ISSUE TITLE
.DisplayName() crashes sometimes when run as System

### ISSUE THREAD

**Issue by AaronMargosis** [microsoft/cppwinrt#1076]
Repro: compile the attached as Release x86 or x64. Log on as an admin user, open an elevated Cmd/PowerShell and run the compiled exe. (Works as expected, listing name, full name, and display name of all installed packaged apps.) Open a Cmd or PowerShell as System (e.g., psexec -sid PowerShell) and run the same exe there. Crashes for one or more packages when invoking .DisplayName().

Tested on Win10 v 21H1 (19043) Enterprise.

[CppWinrt_BugRepro.cpp.txt](https://github.com/microsoft/cppwinrt/files/7706375/CppWinrt_BugRepro.cpp.txt)

**Comment by sylveon** [comment]
This seems like an issue with the API, not cppwinrt's projection

**Comment by AaronMargosis** [comment]
On another machine, I'm now seeing the exception getting thrown for a regular admin user account, and also for InstalledLocation().
I could just wrap each accessor in a try/catch, but I'd rather have a proper way to check validity and not have to worry about exceptions with every accessor.

**Comment by kennykerr** [comment]
C++/WinRT will translate an error from the underlying API into an exception. This is by design. You can try and catch the error and inspect the message/code/docs to see whether the error is avoidable.
