### ISSUE TITLE
Support for VS 2022

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/cppwinrt#1078]
This extension is only for VS 2019

It would be cool if you could add support for VS 2022

**Comment by sylveon** [comment]
Templates are builtin to VS 2022. There is no need for a separate extension
anymore

**Comment by curia-damiano** [comment]
Yes correct.
I created the issue while reading https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component, that in the prerequisites lists this VS extension.
In reality later it uses just the NuGet package.

I will create an issue on that documentation page.
