### ISSUE TITLE
Will Windows App SDK replace cppwinrt?

### ISSUE THREAD

**Issue by Zwaliebaba** [microsoft/cppwinrt#1079]
With the introduction of Windows App SDK and the fact that UWP is not a strategic direction anymore within Microsoft, will this also impact the development of cppwinrt going forward?

**Comment by sylveon** [comment]
Windows App SDK provides WinRT APIs to consumers, and C++/WinRT is the only supported C++ projection of WinRT APIs going forward. So it's here to stay.
