### ISSUE TITLE
where do I put the game loop?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#108]
I'm using this framework:
![image](https://cloud.githubusercontent.com/assets/6119906/23000596/42fd67ea-f3af-11e6-8354-46b9155595b2.png)
How do I add game loop to it?

I image it should be put in the "run" method. But the program does not pint.

![image](https://cloud.githubusercontent.com/assets/6119906/23000640/6cf8ada2-f3af-11e6-931b-beec16a468cc.png)

**Comment by walbourn** [comment]
Take a look at a [directx-vs-templates](https://github.com/walbourn/directx-vs-templates/tree/master/d3d11game_uwp_cppwinrt_dr) for a C++/WinRT UWP game-centric template.
