### ISSUE TITLE
Incompatibility with MSVC v143

### ISSUE THREAD

**Issue by MarnixKuijs** [microsoft/cppwinrt#1080]
MSVC: 14.30.30705
Windows SDK: 10.0.20348.0

Using Visual Studio 2022 with MSVC v143 and including `<winrt/bash.h>` will result in the following error:

```
Error	C1189	#error:  The <experimental/coroutine> and <experimental/resumable> headers are only supported with /await and implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines.
```
There seems to be no obvious way for me to force winrt to use the non-experimental coroutine header without modifiying the header itself.

**Comment by sylveon** [comment]
Use the NuGet package instead of the version in the SDK. The build in the SDK is old.

**Comment by fredemmott** [comment]
> Use the NuGet package instead of the version in the SDK. The build in the SDK is old.

Is there a recommended way to use c++/winrt when *not* using visual studio/MSBuild? nuget appears to only be an option for MSBuild, Visual Studio, or C# (not C++) projects that use CMake.

I've been loving c++/winrt for windows-only projects, but it seems that the best approach for cross-platform projects with a little windows-specific code is to use WRL or similar instead.

**Comment by fredemmott** [comment]
It feels strange for a project that has 'standard C++' as a major feature is only available in MS-specific packaging formats

**Comment by sylveon** [comment]
You can use NuGet packages in CMake with [VS_PACKAGE_REFERENCE](https://cmake.org/cmake/help/latest/prop_tgt/VS_PACKAGE_REFERENCES.html) when you use the VS generator. While online threads and SO answers say this is C# only because VS only supported PackageReference from C# projects, VS 2022 also supports those from C++ projects now. A few PRs where done to cppwinrt to allow using it from a PackageReference, so it should work.

If you don't use the VS generator, or use another build system, you can manually download the nupkg file, unzip it (it's just a renamed zip file), then run the cppwinrt.exe tool that's in it to generate the headers.

**Comment by fredemmott** [comment]
Thanks; I tried VS_PACKAGE_REFERENCE recently on a project that’s still tied to VS2019 - will try with another one on 2022 soon

**Comment by fredemmott** [comment]
As an aside, if VS_PACKAGE_REFERENCE is supported for C++ now, https://developercommunity.visualstudio.com/t/use-packagereference-in-vcxproj/351636 should be updated

**Comment by MarnixKuijs** [comment]
I don't use the VS generator so that was what I got stuck on, since my project uses CMake (should have clarified that my bad).

> If you don't use the VS generator, or use another build system, you can manually download the nupkg file, unzip it (it's just a renamed zip file), then run the cppwinrt.exe tool that's in it to generate the headers.

I will try this and see if I can automate it somehow through CMake

**Comment by fredemmott** [comment]
> I will try this and see if I can automate it somehow through CMake

not tried, but externalproject_add is probably a good place to start

**Comment by fredemmott** [comment]
https://github.com/fredemmott/OpenKneeboard/blob/683801599e507e9e47aa13f71758c99ee0efa6c0/third-party/cppwinrt.cmake this works fine - though AIUI ideally I should be passing a complete path based on `CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION` instead of just using `-in local`
