### ISSUE TITLE
Should we add winrt::Object to simplify some use cases?

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#1081]
```cpp
namespace winrt
{
    using Object = winrt::Windows::Foundation::IInspectable;
}
```
enables
```cpp
    auto map = winrt::multi_threaded_observable_map<winrt::hstring, winrt::Object>().
        as<winrt::IMap<winrt::hstring, winrt::Object>>();
```
instead of
```cpp
    auto map = winrt::multi_threaded_observable_map<winrt::hstring,
        winrt::Windows::Foundation::IInspectable>().
        as<winrt::IMap<winrt::hstring, winrt::Windows::Foundation::IInspectable>>();
```

**Comment by sylveon** [comment]
This could conflict with somebody using a namespace named `Object`. Feels like something that should be defined in the project's source code, not cppwinrt. Personally, I do `namespace wf = winrt::Windows::Foundation;` so I can type `wf::IInspectable`.

**Comment by kennykerr** [comment]
Yep, adding such "helper" types/aliases is not recommended. You can always add the type alias in your own projects/libraries e.g. WIL. If anything, C++/WinRT needs to be trimmed down further to only include code generated from metadata.

**Comment by Jaiganeshkumaran** [comment]
> This could conflict with somebody using a namespace named `Object`. Feels like something that should be defined in the project's source code, not cppwinrt. Personally, I do `namespace wf = winrt::Windows::Foundation;` so I can type `wf::IInspectable`.

Note that when you're inside a runtime class, you can directly use IInspectable instead of winrt::Windows::Foundation as a type alias exists, even without using Windows::Foundation.
