### ISSUE TITLE
Ambiguous call when using a derived type

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#1082]
IDL:
```idl
namespace MarkupSample
{
    [bindable]
    [default_interface]
    runtimeclass CustomVSM : Windows.UI.Xaml.VisualStateManager
    {
        CustomVSM();
        overridable Boolean GoToStateCore(Windows.UI.Xaml.Controls.Control control, 
                Windows.UI.Xaml.FrameworkElement templateRoot, 
                String stateName, Windows.UI.Xaml.VisualStateGroup group, 
                Windows.UI.Xaml.VisualState state, 
                Boolean useTransitions) ;
    }
}
```

IMPL:
```cpp
namespace winrt::MarkupSample::implementation
{
    struct CustomVSM : CustomVSMT<CustomVSM>
    {
        CustomVSM() = default;

        bool GoToStateCore(winrt::Windows::UI::Xaml::Controls::Control const& control, 
                winrt::Windows::UI::Xaml::FrameworkElement const& templateRoot, 
                winrt::hstring const& stateName, 
                winrt::Windows::UI::Xaml::VisualStateGroup const& group, 
                winrt::Windows::UI::Xaml::VisualState const& state, 
                bool useTransitions) {
            return __super::GoToStateCore(control, templateRoot, stateName, group, state, useTransitions);
        }
    };
}
```

call-site:
```cpp
        auto vsm = MarkupSample::CustomVSM();
        vsm.GoToStateCore(Controls::Button(), grid, L"VS1", vsmGroup, vsmState, true);
```

Results in:
```
error C2668: 'winrt::impl::consume_Windows_UI_Xaml_IVisualStateManagerOverrides<D>::GoToStateCore': ambiguous call to overloaded function
        with
        [
            D=winrt::MarkupSample::CustomVSM
        ]
could be 'auto winrt::impl::consume_Windows_UI_Xaml_IVisualStateManagerOverrides<D>::GoToStateCore(const winrt::Windows::UI::Xaml::Controls::Control &,const winrt::Windows::UI::Xaml::FrameworkElement &,const winrt::param::hstring &,const winrt::Windows::UI::Xaml::VisualStateGroup &,const winrt::Windows::UI::Xaml::VisualState &,bool) const'
        with
        [
            D=winrt::MarkupSample::CustomVSM
        ]
or       'auto winrt::impl::consume_MarkupSample_ICustomVSMOverrides<D>::GoToStateCore(const winrt::Windows::UI::Xaml::Controls::Control &,const winrt::Windows::UI::Xaml::FrameworkElement &,const winrt::param::hstring &,const winrt::Windows::UI::Xaml::VisualStateGroup &,const winrt::Windows::UI::Xaml::VisualState &,bool) const'
        with
        [
            D=winrt::MarkupSample::CustomVSM
        ]

while trying to match the argument list '(winrt::Windows::UI::Xaml::Controls::Button, winrt::Windows::UI::Xaml::Controls::Grid, const wchar_t [4], winrt::Windows::UI::Xaml::VisualStateGroup, winrt::Windows::UI::Xaml::VisualState, bool)'
```

How does one call the overridden implementation?

**Comment by sylveon** [comment]
By adding `GoToStateCore` to the IDL, you're adding a new method to CustomVSM, not overriding the one from VisualStateManager. Simply omitting `GoToStateCore` from the IDL should make your code work (and correctly override `GoToStateCore`).

**Comment by asklar** [comment]
Thanks - I wonder if our docs are wrong though:
https://docs.microsoft.com/uwp/midl-3/intro#method-visibility-modifiers

> The overridable modifier states that this method overrides a method with the same name and signature in a base class.

Also: https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.VisualStateManager?view=winrt-22000#custom-visualstatemanager

> The derived class should override the protected GoToStateCore method. Any instance of the custom VisualStateManager uses this Core logic when its GoToState method is called.

These two led me to believe that in order to create a subclass of `VisualStateManager`, I had to declare `GoToStateCore` as `overridable` in the IDL.

**Comment by sylveon** [comment]
The first quote is definitely wrong. It should say that overridable is what *allows* the function to be overridden by derived classes.

The second however seems fine to me. Maybe what's missing is documentation on how to override in C++/WinRT - the only example of this I can find is https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl#implementing-overridable-functions-such-as-measureoverride-and-onapplytemplate which is not something people would be naturally inclined to look for when trying to override and it doesn't mention that it doesn't need to be present in IDL.

**Comment by asklar** [comment]
Sent these two PRs:
- https://github.com/MicrosoftDocs/winrt-related/pull/284
- https://github.com/MicrosoftDocs/windows-uwp/pull/3582

**Comment by kennykerr** [comment]
Looks like this was a doc bug. Closing this issue.
