### ISSUE TITLE
Enhance IDE support for implementing interfaces through winrt::implements

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1085]
Usually in C++, when you have a struct or class with pure virtual member functions and try to inherit from it but forget to implement those member functions, Visual Studio will give you a red squiggle that tells the user to implement them (indirectly).

<img width="783" alt="Screenshot 2021-12-31 at 19 30 51" src="https://user-images.githubusercontent.com/45227503/147827110-d93e8f61-14c7-43cb-8faf-406b0a5bebc5.png">

Something similar is shown for C++/CX ref classes and structs.

<img width="619" alt="Screenshot 2021-12-31 at 19 36 00" src="https://user-images.githubusercontent.com/45227503/147827316-a3cf9deb-85d9-42bd-880f-3ac954218337.png">

I prefer the C++/CX IntelliSense behaviour as it clearly states that you've not implemented interface members and shows it right in the class definition rather than a variable of the class but that's just because C++/CX has semantics for interfaces whereas standard C++ doesn't (they're usually just classes with all pure virtual methods). Either way, an IntelliSense error is produced at design time so you know that you need to implement all the methods and correct them before building.

With C++/WinRT, there's no IntelliSense error. Obviously, you're not inheriting from the interface directly but using winrt::implements which accepts both ABI types and C++/WinRT projected (smart pointer wrapper) types and the IntelliSense engine doesn't know that you must implement a few methods for successful compilation. The methods aren't virtual, instead, winrt::implements use the CRTP pattern to call your methods from the underlying ABI implementation (CCW in .NET terms, except nothing, is hidden from you). It's efficient compared to simply having a pure virtual method with implementation signature as it has extra overhead and has no real need. However, from a developer's point of view, you're really implementing an interface.
 
<img width="458" alt="Screenshot 2021-12-31 at 19 47 06" src="https://user-images.githubusercontent.com/45227503/147827793-32581d63-25a1-47e5-95c5-1e71e71e4550.png">

C# is better than all of them, it even shows options to let the IDE insert the methods for you. I used char[] as the return type for this example instead of a string as object.ToString already exists but it should similar for every other case.

<img width="1389" alt="Screenshot 2021-12-31 at 20 09 05" src="https://user-images.githubusercontent.com/45227503/147828681-b50642b1-0ad8-42b2-b6e2-bbad9baa43ea.png">

When having a C++/WinRT class implementing an interface (either through winrt::implements or ClassT for runtime class declared IDL), there should be something at design time to indicate that you've not implemented the interface completely if that's the case. Users shouldn't need to build the project and then notice "oh, I forgot to implement the interface methods."

**Proposed solution**: Somehow detect whether the required methods with the right signature are implemented and show IntelliSense error. It could be implemented within the IDE itself or in the VSIX, however, that will only work in Visual Studio and you'll not get the same error during compilation. A better solution would be to detect at compile time (SFINAE? C++20 Concepts?) and use a static_assert if the methods aren't implemented. Obviously, you can't embed the actual name of the interface method in the static_assert message, however since the code is pre-generated on demand by the C++/WinRT compiler, it can embed with the name with the message as well.

**Comment by kennykerr** [comment]
We have experimented with providing such hints in the library itself but that never worked very well and added significant bloat to the code. C# and C++/CX both benefit from IDE support that C++/WinRT lacks. This would ideally be a feature provided directly by Visual Studio, as it is for C# and C++/CX. Unfortunately, we haven't had any luck getting the Visual Studio team to support this and have not managed to get VSIX to provide a comparable experience.

**Comment by pjmlp** [comment]
I would have helped to actually think about these issues instead of deprecating C++/CX without considering paying customers productivity.

**Comment by kennykerr** [comment]
Preaching to the choir. 😜 Please let the Visual Studio team know. 

https://developercommunity.visualstudio.com/search?space=62

**Comment by pjmlp** [comment]
Oh I did, multiple times. Time to move on.

**Comment by sylveon** [comment]
You do get `'ToString': is not a member of 'Stringable'` at build-time, which is a fairly obvious error.

**Comment by Jaiganeshkumaran** [comment]
> You do get `'ToString': is not a member of 'Stringable'` at build-time, which is a fairly obvious error.

But you have to built the project first to see the error.
