### ISSUE TITLE
Why does WINRT_GetActivationFactory return CLASS_E_CLASSNOTAVAILABLE?

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/cppwinrt#1087]
Hi,

I have noticed that `WINRT_GetActivationFactory` function returns `CLASS_E_CLASSNOTAVAILABLE` error when the requested class is not available in the implementation library:

https://github.com/microsoft/cppwinrt/blob/51ec25ce5c657048fa552f3054d7427137c9d9ea/cppwinrt/component_writers.h#L200

However, an official [documentation for `DllGetActivationFactory`](https://docs.microsoft.com/en-us/previous-versions/br205771(v=vs.85)) states that in this case `REGDB_E_CLASSNOTREG` should be returned.

What is supposed to be the correct behavior? 🤔

**Comment by kennykerr** [comment]
Either will work. C++/WinRT prefers `CLASS_E_CLASSNOTAVAILABLE` because that's what WRL used and together they account for the vast majority of WinRT implementations, so I went for consistency.

**Comment by Alovchin91** [comment]
Makes sense. Thanks for the prompt reply! 🙂
