### ISSUE TITLE
Is cppwinrt  included in Windows SDK now?

### ISSUE THREAD

**Issue by maidamai0** [microsoft/cppwinrt#1090]
This is a help question instead of a bug.

I noticed the `cppwinrt` seems included in the Windows SDK such as `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\cppwinrt\winrt`. And there is also a NuGet package [Microsoft.Windows.CppWinRT](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/). 

Is the one in the SDK a some bit older version and the **Microsoft.Windows.CppWinRT** is the latest one?

**Comment by maidamai0** [comment]
Seems the cppwinrt version included in the **windows SDK 10.0.22000** is [2.0.201201.7](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/2.0.201201.7). Since the *SDK* path is included automatically by the compiler how can I tell it to use the one installed with `NuGet`?

**Comment by sylveon** [comment]
The version from NuGet automatically takes priority over the SDK.

**Comment by kennykerr** [comment]
Yes, the msbuild support included with the nuget package should ensure that it takes precedence.
