### ISSUE TITLE
IInspectable try_as awaly success on implements struct type

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#1096]
```
struct One1 : winrt::implements<One1, winrt::IInspectable > {};
struct One2 : winrt::implements<One2, winrt::IInspectable > {};
```

```
auto one1 = winrt::make<One1>();
auto one2 = one1.try_as<One2>(); // one2 always  return none null value.
```

![image](https://user-images.githubusercontent.com/16729017/150637942-80562b7e-4dd5-450a-b418-5e93390e1c35.png)

**Comment by Jaiganeshkumaran** [comment]
This is because both One1 and One2 implement the exact same set of interfaces so there's no way to distinguish between them. Generally it's not recommended to directly access the underlying implementation type and winrt::implements is usually used to create opaque implementation of an interface.

**Comment by sylveon** [comment]
From a standards PoV it's still a problem, that's illegal aliasing.

**Comment by shelllet** [comment]
> This is because both One1 and One2 implement the exact same set of interfaces so there's no way to distinguish between them. Generally, it's not recommended to directly access the underlying implementation type and winrt::implements is usually used to create an opaque implementation of an interface. In this case, it's not a problem since both classes are identical, however, that's not the case most of the time.

So how do change the code to distingish them ( the local implements winrt type) instead of dcelare them via idl?

**Comment by sylveon** [comment]
Create an interface for them, then add it to `winrt::implements`:
```cpp
MIDL_INTERFACE("7F9D905E-F955-4D52-B856-4851A5CBCA7C") IOne1 : IUnknown
{
    // since this is a private interface, functions declared there don't need to adhere to any COM/WinRT requirement
    std::string do_something();
};

MIDL_INTERFACE("7ABE3977-B188-4C4A-909E-8395B325801D") IOne2 : IUnknown
{
    int add(int a, int b);
};

struct One1 : winrt::implements<One1, winrt::IInspectable, IOne1> {};
struct One2 : winrt::implements<One2, winrt::IInspectable, IOne2> {};

auto one1 = winrt::make<One1>();
auto one2 = one1.try_as<IOne2>(); // will return null

**Comment by sylveon** [comment]
Another case where this can occur is the following:
```
namespace Foo
{
    interface IBar {}

    runtimeclass Buz : [default] IBar {}

    [default_interface]
    runtimeclass FooBar : IBar {}
}
```

```cpp
void test(winrt::Foo::IBar thing)
{
    if (const auto buzImpl = thing.try_as<winrt::Foo::implementation::Buz>()
    {
        // you will ALWAYS hit this code path
        // if thing is not actually a Buz, you will have very fun memory corruption issues on your hand.
        buzImpl->DoThing();
    }
    else if (const auto foobarImpl = thing.try_as<winrt::Foo::implementation::FooBar>())
    {
        // this code path will never be hit, even if "thing" is actually a winrt::Foo::FooBar
        fooBarImpl->DoOtherThing();
    }
}
```

Because `[default]` was used for `Buz`, it means there is no `IBuz` (and an associated GUID) for the `try_as` to check against. So it checks against `IBar` meaning that `FooBar` will succeed the check too, and then you effectively get an `winrt::Foo::implementation::FooBar` reinterpret-casted as `winrt::Foo::implementation::Buz`, which is a big problem.

I feel like catching these kinds of issues would be possible from within cppwinrt. Ideally, this wrong code shouldn't compile.
