### ISSUE TITLE
How to specify type on an attribute in MIDL?

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1099]
I'm implementing a XAML MarkupExtension which expects the derived runtime class to have MarkupExtensionReturnTypeAttribute on it that specifies the type of the return value. I initially tried to use a string for specifying the type name however that doesn't work. Turns out that you've to specify the type itself directly and that works however then I get an error on the C++/WinRT side:
```
The type "String" was referenced as an attribute but its type definition was not found.
```

Is this a supported scenario?

**Comment by kennykerr** [comment]
This sounds like a question for the Xaml team. Can you open an issue on their repo? 

https://github.com/microsoft/microsoft-ui-xaml

**Comment by sylveon** [comment]
This is a MIDL compiler issue. You can only refer to types coming from your own assembly. https://stackoverflow.com/questions/52763407/how-to-use-the-templatepart-attribute-on-a-custom-control#comment120704283_52823160
