### ISSUE TITLE
How to write a ServiceConnection program?

### ISSUE THREAD

**Issue by scuhappy** [Microsoft/cppwinrt#11]
I am doing it with winrtcpp like this in my qt program :
`AppServiceConnection appServiceConnection;
	
	ValueSet message;
	hstring key = L"Command";
	Windows::Foundation::IPropertyValue value ;
	value = "aaa";
	message.Insert(key, value);
	IAsyncOperation<AppServiceResponse> response =  appServiceConnection.SendMessageAsync(message);
	response.Completed([&](const auto & sender, AsyncStatus) {
		AppServiceResponse res = sender.GetResults();
		ui->listWidget->addItem("send message success!");
	});`
But I received a compile error, that "aaa"can not be converted to a IPropertyValue  type value. So which type can I use in this place?

**Comment by kennykerr** [comment]
We have not yet added support in C+/WinRT for nullable types, but you can work around it with the help of the Windows::Foundation::PropertyValue class:

```C++
ValueSet message;
hstring key = L"Key";
IPropertyValue value = PropertyValue::CreateString(L"Value").as<IPropertyValue>();
message.Insert(key, value);
```
