### ISSUE TITLE
Add "Internal" methods tutorial to docs

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/cppwinrt#1100]
> I've realized that converting the UserControls projection type back to it's implementation type (https://devblogs.microsoft.com/oldnewthing/20200828-00/?p=104138) is a better way to export information from a UserConrol

>Yup! That's the best way to have "internal" methods like C++/CX and C#

_Originally posted by @sylveon in https://github.com/microsoft/cppwinrt/issues/1089#issuecomment-1008218666_

I really think you should add this to the docs, perhaps before _Passing parameters into the ABI boundary_ since that's where I stopped reading.

Having not come from C++/CX or C# and having not bothered to find out what internal meant, I had to figure out this myself the hard way.

**Comment by kennykerr** [comment]
I thought this was documented but adding @stevewhims in case I missed something.

**Comment by stevewhims** [comment]
It's in here [Instantiating and returning implementation types and interfaces](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-apis#instantiating-and-returning-implementation-types-and-interfaces), I believe.
