### ISSUE TITLE
hstring - Support conversions for std::u16string_view

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1102]
Today hstring has conversions from std::wstring_view. Since the contents of an hstring are always encoded in UTF-16LE, it makes a lot of sense to have conversions for std::u16string_view as it's always 16-bit on any platform, unlike std::wstring_view. Also add a constructor that takes a char16_t const*.

**Comment by kennykerr** [comment]
This makes sense but isn't something I'm planning to add unless we commit to another major update to C++/WinRT.
