### ISSUE TITLE
How to Convert Null value To Visibility in C++/WinRT ?

### ISSUE THREAD

**Issue by odyright** [microsoft/cppwinrt#1108]
Hello, I would like to know the best way to wear " Nullovisconverter.cs" from C# to C++/WinRT.
Source: [NullToVisibilityConverter.cs](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/Common/NullToVisibilityConverter.cs)

**Comment by kennykerr** [comment]
Sorry, I don't know that much about Xaml. You could try the sample repo, the Xaml repo, or stackoverflow.

**Comment by sylveon** [comment]
NullToVisibilityConverter.idl
```cpp
namespace YourNamespace
{
	runtimeclass NullToVisibilityConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		NullToVisibilityConverter();

		[noexcept]
		Windows.UI.Xaml.Visibility NullValue;

		[noexcept]
		Windows.UI.Xaml.Visibility NonNullValue;
	}
}
```

NullToVisibilityConverter.h
```cpp
#pragma once

#include "NullToVisibilityConverter.g.h"

namespace winrt::YourNamespace::implementation
{
	struct NullToVisibilityConverter : NullToVisibilityConverterT<NullToVisibilityConverter>
	{
		NullToVisibilityConverter() = default;

		IInspectable Convert(IInspectable const& value, Windows::UI::Xaml::Interop::TypeName const& targetType, IInspectable const& parameter, hstring const& language);
		IInspectable ConvertBack(IInspectable const& value, Windows::UI::Xaml::Interop::TypeName const& targetType, IInspectable const& parameter, hstring const& language);

		Windows::UI::Xaml::Visibility NullValue() noexcept;
		void NullValue(Windows::UI::Xaml::Visibility value) noexcept;

		Windows::UI::Xaml::Visibility NonNullValue() noexcept;
		void NonNullValue(Windows::UI::Xaml::Visibility value) noexcept;

	private:
		Windows::UI::Xaml::Visibility nullValue = Windows::UI::Xaml::Visibility::Collapsed;
		Windows::UI::Xaml::Visibility nonNullValue = Windows::UI::Xaml::Visibility::Visible;
	};
}

namespace winrt::YourNamespace::factory_implementation
{
    struct NullToVisibilityConverter : NullToVisibilityConverterT<NullToVisibilityConverter, implementation::NullToVisibilityConverter>
    {
    };
}
```

NullToVisibilityConverter.cpp
```cpp
#include "pch.h"
#include "NullToVisibilityConverter.h"
#if __has_include("NullToVisibilityConverter.g.cpp")
#include "NullToVisibilityConverter.g.cpp"
#endif

namespace winrt::YourNamespace::implementation
{
	Windows::Foundation::IInspectable NullToVisibilityConverter::Convert(IInspectable const& value, Windows::UI::Xaml::Interop::TypeName const&, IInspectable const&, hstring const&)
	{
		return value == nullptr ? nullValue : nonNullValue;
	}

	Windows::Foundation::IInspectable NullToVisibilityConverter::ConvertBack(IInspectable const&, Windows::UI::Xaml::Interop::TypeName const&, IInspectable const&, hstring const&)
	{
		throw hresult_not_implemented();
	}

	Windows::UI::Xaml::Visibility NullToVisibilityConverter::NullValue() noexcept
	{
		return nullValue;
	}

	void NullToVisibilityConverter::NullValue(Windows::UI::Xaml::Visibility value) noexcept
	{
		nullValue = value;
	}

	Windows::UI::Xaml::Visibility NullToVisibilityConverter::NonNullValue() noexcept
	{
		return nonNullValue;
	}

	void NullToVisibilityConverter::NonNullValue(Windows::UI::Xaml::Visibility value) noexcept
	{
		nonNullValue = value;
	}
}
```

I haven't actually tested if this works, but it should look something like this.

**Comment by odyright** [comment]
> NullToVisibilityConverter.idl
> 
> ```c++
> namespace YourNamespace
> {
> 	runtimeclass NullToVisibilityConverter : Windows.UI.Xaml.Data.IValueConverter
> 	{
> 		NullToVisibilityConverter();
> 
> 		[noexcept]
> 		Windows.UI.Xaml.Visibility NullValue;
> 
> 		[noexcept]
> 		Windows.UI.Xaml.Visibility NonNullValue;
> 	}
> }
> ```
> 
> NullToVisibilityConverter.h
> 
> ```c++
> #pragma once
> 
> #include "NullToVisibilityConverter.g.h"
> 
> namespace winrt::YourNamespace::implementation
> {
> 	struct NullToVisibilityConverter : NullToVisibilityConverterT<NullToVisibilityConverter>
> 	{
> 		NullToVisibilityConverter() = default;
> 
> 		IInspectable Convert(IInspectable const& value, Windows::UI::Xaml::Interop::TypeName const& targetType, IInspectable const& parameter, hstring const& language);
> 		IInspectable ConvertBack(IInspectable const& value, Windows::UI::Xaml::Interop::TypeName const& targetType, IInspectable const& parameter, hstring const& language);
> 
> 		Windows::UI::Xaml::Visibility NullValue() noexcept;
> 		void NullValue(Windows::UI::Xaml::Visibility value) noexcept;
> 
> 		Windows::UI::Xaml::Visibility NonNullValue() noexcept;
> 		void NonNullValue(Windows::UI::Xaml::Visibility value) noexcept;
> 
> 	private:
> 		Windows::UI::Xaml::Visibility nullValue = Windows::UI::Xaml::Visibility::Collapsed;
> 		Windows::UI::Xaml::Visibility nonNullValue = Windows::UI::Xaml::Visibility::Visible;
> 	};
> }
> 
> namespace winrt::YourNamespace::factory_implementation
> {
>     struct NullToVisibilityConverter : NullToVisibilityConverterT<NullToVisibilityConverter, implementation::NullToVisibilityConverter>
>     {
>     };
> }
> ```
> 
> NullToVisibilityConverter.cpp
> 
> ```c++
> #include "pch.h"
> #include "NullToVisibilityConverter.h"
> #if __has_include("NullToVisibilityConverter.g.cpp")
> #include "NullToVisibilityConverter.g.cpp"
> #endif
> 
> namespace winrt::YourNamespace::implementation
> {
> 	Windows::Foundation::IInspectable NullToVisibilityConverter::Convert(IInspectable const& value, Windows::UI::Xaml::Interop::TypeName const&, IInspectable const&, hstring const&)
> 	{
> 		return value == nullptr ? nullValue : nonNullValue;
> 	}
> 
> 	Windows::Foundation::IInspectable NullToVisibilityConverter::ConvertBack(IInspectable const&, Windows::UI::Xaml::Interop::TypeName const&, IInspectable const&, hstring const&)
> 	{
> 		throw hresult_not_implemented();
> 	}
> 
> 	Windows::UI::Xaml::Visibility NullToVisibilityConverter::NullValue() noexcept
> 	{
> 		return nullValue;
> 	}
> 
> 	void NullToVisibilityConverter::NullValue(Windows::UI::Xaml::Visibility value) noexcept
> 	{
> 		nullValue = value;
> 	}
> 
> 	Windows::UI::Xaml::Visibility NullToVisibilityConverter::NonNullValue() noexcept
> 	{
> 		return nonNullValue;
> 	}
> 
> 	void NullToVisibilityConverter::NonNullValue(Windows::UI::Xaml::Visibility value) noexcept
> 	{
> 		nonNullValue = value;
> 	}
> }
> ```
> 
> I haven't actually tested if this works, but it should look something like this.

Thank you @sylveon for your reponse. However, i've created a repo [NullToVisibilityConverter c++/winrt](https://github.com/odyright/NullToVisibilityConverter) to illustrate the work i did, I certainly made inconsistent codes but as a beginner `c++/winrt` it's better than doing nothing.

**Comment by odyright** [comment]
@sylveon 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/4316506/156055377-dda77ea9-a9cc-46ee-bc6a-63a7f84c00e8.png">
error
<img width="619" alt="image" src="https://user-images.githubusercontent.com/4316506/156055491-dc2ff766-7e3a-4816-bf28-089af5da010a.png">

**Comment by sylveon** [comment]
You have to wrap the return into a call to `box_value`, like this:
```cpp
return box_value(value == nullptr ? nullValue : nonNullValue);
```

**Comment by odyright** [comment]
weird! i'm facing other issues. i tried to fix it following the error code but no way, i don't understand.
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/4316506/156112403-d9e2fc35-c04b-4d32-b716-4d55dd859735.png">
