### ISSUE TITLE
STA MTA

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#111]
How do I use a coroutine and specify its threading model STA or MTA?

**Comment by kennykerr** [comment]
C++/WinRT captures the apartment context before suspending and will resume in the same apartment context. You can also manually switch contexts within a coroutine [as illustrated here](https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/Samples/XamlCode/App.cpp).

We explained this in detail in [our coroutine talk at CppCon](https://www.youtube.com/watch?v=v0SjumbIips) last year.

The thread or apartment that a coroutine begins execution on depends on the coroutine type (return type). Most coroutine types don't switch contexts until the first suspension point.
