### ISSUE TITLE
compile failed: `IVector<IKeyValuePair<hstring, hstring>> outputs = single_threaded_vector<IKeyValuePair<hstring, hstring>>()`;

### ISSUE THREAD

**Issue by shelllet** [microsoft/cppwinrt#1111]
```
IVector<IKeyValuePair<hstring, hstring>> outputs = single_threaded_vector<IKeyValuePair<hstring, hstring>>();
```

![image](https://user-images.githubusercontent.com/16729017/155919657-576fe588-9946-409c-9bae-a772c1aeca63.png)

**Comment by Jaiganeshkumaran** [comment]
Did you include the right header files?

**Comment by shelllet** [comment]
> Did you include the right header files? Normally you would use a map instead of having a vector of pairs.

i'm sure  the the right header  files are included.

i need to keep the order of the vector element.  the map  can't do this in my memory.

**Comment by kennykerr** [comment]
The stock collection implementation provided by `single_threaded_vector` is shared by `single_threaded_map` and infers which type of collection to implement based in part on whether the type is `IKeyValuePair`. This is unfortunate, but the stock collection implementations are just meant to cover the most common scenarios and are unlikely to change at this point. I recommend developers looking for more advanced collection support to implement their own.
