### ISSUE TITLE
Any replacement for CAtlFileMapping?

### ISSUE THREAD

**Issue by UMU618** [microsoft/cppwinrt#1113]
I am looking for a winrt replacement for CAtlFileMapping from <atlfile.h>, and can't find one. why?

**Comment by kennykerr** [comment]
I'm not aware of a WinRT API for memory-mapped files.

**Comment by sylveon** [comment]
I believe you can either keep using CAtlFileMapping, or if you want to get rid of ATL entirely, you can use the raw Win32 memory mapped file API: https://docs.microsoft.com/en-us/windows/win32/memory/file-mapping
