### ISSUE TITLE
Func<T, TResult> Delegate 

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#112]
Will this be available? I'm converting from C#

**Comment by bigdimboom** [comment]
If I'm right, first T is a param for "Func" and TResult is the returning value. Therefore, what you are looking for are coroutine and/or lamda function in c++.

**Comment by kennykerr** [comment]
There are two generic delegates defined by the Windows Runtime. They are projected in C++/WinRT as follows:

```C++
namespace winrt::Windows::Foundation
{
    template <typename T> struct EventHandler;
    template <typename TSender, typename TArgs> struct TypedEventHandler;
}
```

Neither of these returns a result. If you don't need a WinRT abstraction, you can use a lambda or [std::function](http://en.cppreference.com/w/cpp/utility/functional/function).
