### ISSUE TITLE
what is the difference between fire_and_forget and IAsyncAction?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#113]

**Comment by kennykerr** [comment]
IAsyncAction is the simplest of the WinRT async types that you can use to both wait on or return to another language projection. fire_and_forget is an even simpler coroutine type that does not have a WinRT representation and, as its name suggests, is used when you just want to start an async operation and don't intend to wait for its completion directly. You might have some other way to coordinate its completion and don't need the overhead of an actual coroutine type with blocking and cooperative wait support.
