### ISSUE TITLE
Function calls without C++ exceptions?

### ISSUE THREAD

**Issue by saschanaz** [microsoft/cppwinrt#1135]
I just took a brief look at cppwinrt as a part of https://bugzilla.mozilla.org/show_bug.cgi?id=1732673, and it seems quite a lot of things are using `check_hresult()` internally and thus throws an exception if an error happens. For example:

```cpp
namespace Windows::Foundation
{
    struct IActivationFactory : IInspectable
    {
        IActivationFactory(std::nullptr_t = nullptr) noexcept {}
        IActivationFactory(void* ptr, take_ownership_from_abi_t) noexcept : IInspectable(ptr, take_ownership_from_abi) {}

        template <typename T>
        T ActivateInstance() const
        {
            IInspectable instance;
            check_hresult((*(impl::abi_t<IActivationFactory>**)this)->ActivateInstance(put_abi(instance)));
            return instance.try_as<T>();
        }
    };
}
```

[Mozilla's C++ guideline](https://firefox-source-docs.mozilla.org/code-quality/coding-style/using_cxx_in_firefox_code.html#c-language-features) does not allow exceptions, so it seems that this design is a hard blocker for us.

>Also disabled are exceptions; do not use try/catch or throw any exceptions.

Can we introduce an exception-free way (e.g. Rust-like `Result<T>`) to support this situation, or is there already a way?

Thanks!

**Comment by Jaiganeshkumaran** [comment]
You can call the underlying APIs directly that C++/WinRT wraps on top.

**Comment by Jaiganeshkumaran** [comment]
Something like Result<T> could be done, but then every API needs to be exposed twice so that the existing exception-based model still works and in modern C++, exceptions are the mechanism for error handling.

**Comment by saschanaz** [comment]
> Today, the best thing you could do is write an isolated component that internally uses exceptions but catches them and reports them

> But if you're looking for something that is Rust-like then just go with Rust and the windows / windows-sys crate.

Both don't look ideal as both requires another wrapper on top of a wrapper, which then requires another layer of maintenance.  I think I'll be happy for now if there's a helper for `*(impl::abi_t<IActivationFactory>**)this` part, but is it viable?

**Comment by kennykerr** [comment]
`#include <activation.h>` from the Windows SDK will give you the COM definition for `IActivationFactory` that you can use directly from C++ without requiring exceptions.

**Comment by kennykerr** [comment]
The docs do talk about exceptions in various places: https://aka.ms/cppwinrt 

Personally, your two-line example seems far more appealing. 😉

**Comment by sylveon** [comment]
cppwinrt's use of exceptions for error handling is documented [here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/error-handling)

**Comment by saschanaz** [comment]
I'd expect some warning in one of top page/introduction/get started pages for this kind of blocker. Anyway, I guess I can stop here. Thanks for the replies.

>Personally, your two-line example seems far more appealing. 😉

Only if we could actually use it.

**Comment by kennykerr** [comment]
For what it's worth, you can rewrite the default exceptional code...

```C++
UISettings settings;
printf("%d\n", settings.AutoHideScrollBars());
```

...as follows to avoid the exceptions you're likely to encounter when calling this API from an unsupported version of Windows (the reason the code may throw in the first place):

```C++
if (auto factory = try_get_activation_factory<UISettings>()) {
    auto settings = factory.ActivateInstance<IUISettings>();
    if (auto settings5 = settings.try_as<IUISettings5>()) {
        printf("%d\n", settings5.AutoHideScrollBars());
    }
}
```

This seems to satisfy Mozilla's policy where it states that "Libraries that throw exceptions may be used if you are willing to have the throw instead be treated as an abort."

**Comment by saschanaz** [comment]
For that specific function, yes, thanks. It would be hard to consciously avoid exceptions for random functions, though.
