### ISSUE TITLE
NuGet package doesn't work in ATL project

### ISSUE THREAD

**Issue by amtopel** [microsoft/cppwinrt#1138]
The C++/WinRT NuGet package does not work in an ATL project.  The MIDL compiler will fail.

Steps to reproduce:

1. Start a new ATL project
2. Add the C++/WinRT NuGet package
3. Build

The compiler will raise a MIDL2003 error about the redefinition of IUnknown and _FLAGGED_WORD_BLOB.

**Comment by kennykerr** [comment]
Looks like both ATL and C++/WinRT's msbuild support may have conflicting MIDL configurations. Paging @Scottj1s in case he has any suggestions for how to make them play nicely together.

**Comment by kennykerr** [comment]
You may have better luck with the Visual Studio team who now ship both ATL and C++/WinRT I believe.  

https://developercommunity.visualstudio.com/search?space=62

Sorry, this isn't something I know too much about.
