### ISSUE TITLE
How do I inspect/print/log events in the event bus?  

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#114]
I'm using CoreWindow::GetForCurrentThread().Dispatcher() to get the event bus. Does the event system have to be attached to the UI thread or is there a way to attach a event system to the CoreApplication thread? What is the relation between CoreWindow and CoreApplication?  How do I log/print the events that is happening inside the event bus.  How do I keep track of the events that have been registered and revoked? 

There are actually two kinds of event register and revoke methods:

method A. (Described in Doc)
to register: auto tokenA = Object::EventMethod({this, &callback});
to revoke: Object::EventMethod(tokenA);

method B. 
to register: auto tokenB = Object::EventMethod(auto_revoke, {this, &callback});
to revoke: tokenB.revoke();

Mu question is, do I have to call the "revoke()" method in method B in order to revoke the event?

**Comment by BrentRe** [comment]
You *can* call the revoke using method B but you don't *have* to call it.

When you request a token using auto_revoke, when the token's destructor runs, the destructor calls revoke for you. Typically, you would only explicitly call revoke in this scenario when you want to revoke the registration prior to the token going out of scope.
