### ISSUE TITLE
Reliable constexpr check for implementation types

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1142]
Is there a reliable constexpr check (through a type trait) to determine if a type is a C++/WinRT implementation type (deriving from implements or ClassT) similar to has_category_v?

**Comment by kennykerr** [comment]
These checks (including `has_category_v`) are not public and thus subject to change. We could perhaps introduce more traits in future but doesn't seem feasible in the existing code base. Consider bringing it up on #1123.

**Comment by Jaiganeshkumaran** [comment]
Here's a set of concepts I'm proposing for the various type categories.

```cpp
namespace winrt
{
  template <typename T>
  concept category_type = impl::has_category<T>;
  
  template <typename T>
  concept value_type = category_type <T> && !std::derived_from<T, Windows::Foundation::IUnknown>;
  
  template <typename T>
  concept reference_type = category_type<T> && std:: derived_from<T, Windows::Foundation::IUnknown>;
  
  template <typename T>
  concept implementation_type = /* not sure how to check */;
}
```

**Comment by sylveon** [comment]
These should probably be C++17 type traits, cppwinrt supports C++17 and there is no reason to require concepts here.

`category_type` should have a better name, for example `winrt_type`. If we expose `has_category`, should we expose all of `category_t`? `struct_type`, `delegate_type`, `enum_type`, etc.

**Comment by fredemmott** [comment]
I need to write up docs, but https://github.com/fredemmott/bindline/ contains `FredEmmott::cppwinrt::inline cppwinrt_concepts::`

- `winrt_type` (derives from W::F::IInspectable)
- `winrt_implementation` : implementation && has `T::implementation_type`
- `winrt_interface` : `winrt_type` && `!winrt_implementation`
- `winrt_implements<parent>`, e.g. `winrt::implements<T, winrt::Windows::Founation::Foo>` or `winrt::implements<T, winrt::no_weak_ref>`
- `winrt_raw_pointer` : `T*` where `winrt_type<T>`
- `any_com_ptr`: any `winrt::com_ptr<>`
- `winrt_com_ptr`: a `winrt_com_ptr<>` to a winrt type
- `winrt_strong_ref`: `winrt_type` or `winrt_com_ptr`
- `winrt_weak_ref`: not a `winrt_strong_ref` ref, but `.get()` gives a `winrt_strong_ref`

I believe I've avoided implementation details, with the possible exception of checking the existence of `T::implementation_type`
