### ISSUE TITLE
DMC description of weak_ref::operator bool is incorrect

### ISSUE THREAD

**Issue by vidager** [microsoft/cppwinrt#1143]
https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/weak-ref

From the page

Operator | Description
-- | --
weak_ref::operator bool | Checks whether the weak_ref object is targeting a C++/WinRT object that hasn't yet been destroyed.

However, the actual code implementation

```
        explicit operator bool() const noexcept
        {
            return static_cast<bool>(m_ref);
        }
```

Unless the behavior is wrong, DMC should be updated.

**Comment by stevewhims** [comment]
What I'll do is I'll document operator bool to say that it returns true if the weak_ref object owns a weak ref; and false if the weak_ref object owns a null pointer. And in the same description I'll advise the use of get to determine whether or not the weak_ref can be resolved to a strong ref (and I'll make sure the get description makes that clear, too). It's likely folks will look at operator bool for that latter task, and if they do then they'll find that info there.

I'll do that now, but please let me know if you'd like me to make any changes to that.

**Comment by kennykerr** [comment]
Sounds great Steve, thanks so much!

**Comment by stevewhims** [comment]
You're welcome, and those changes are live.
