### ISSUE TITLE
Optimize build time a bit by disabling linker winmd generation if project contains no CX

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#1147]
```
  <Target Name="SetGenerateBuildCompilePassWinMD" BeforeTargets="ComputeLinkInputsFromProject">
    <PropertyGroup>
      <GenerateBuildCompilePassWinMD Condition="'$(GenerateBuildCompilePassWinMD)' == '' and '@(ClCompile->WithMetadataValue('CompileAsWinRT', 'true'))' == ''">false</GenerateBuildCompilePassWinMD>
    </PropertyGroup>
  </Target>

```

**Comment by jlaanstra** [comment]
Probably more reliable to add it to ComputeLinkInputsTargets instead of using BeforeTargets.

**Comment by jlaanstra** [comment]
I don't think the check is right. In a CX project WinMD creation is determined based on %(Link.GenerateWindowsMetadata).

**Comment by Scottj1s** [comment]
> Probably more reliable to add it to ComputeLinkInputsTargets instead of using BeforeTargets.
ComputeLinkInputsTargets is a property, which can be overridden.  BeforeTargets cannot, so is safer.

> I don't think the check is right. In a CX project WinMD creation is determined based on %(Link.GenerateWindowsMetadata). CompileAsWinRT just controls CX syntax as far as I know.
That's true for the Link target, which remains unaffected. But for the CreateWinMD target, Link.GenerateWindowsMetadata is ignored and an explicit value of "Only" is used.

**Comment by kennykerr** [comment]
Feel free to reopen if this something you'd like to work on.
