### ISSUE TITLE
x:FieldModifier is ignored

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/cppwinrt#1148]
Not sure where to open this issue so I'll just put it here for now.

When using XAML in a UWP C++/WinRT project, using `x:FieldModifier` in markup does not generate the proper code-behind that exposes XAML elements. For example, using `x:FieldModifier="public"` on an element `MyButton` does not allow `MyButton()` to be used from outside of the XAML's class.

**Comment by kennykerr** [comment]
You can try the Xaml repo: https://github.com/microsoft/microsoft-ui-xaml or https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by tom-huntington** [comment]
cppwinrt xaml is still waiting on c++ static reflection to get rid of the .idl files.

Until then you just have to declare the button in the idl file if you want it public

```
//MainWindow.idl
Microsoft.UI.Xaml.Controls.Button MyButton{ get; };
```
