### ISSUE TITLE
Off-topic: How to specialize template for COM interfaces?

### ISSUE THREAD

**Issue by Zingam** [Microsoft/cppwinrt#115]
Sorry for this off-topic question but I think here are some people who can give a real answer.

I have currently as exercise these templates:

```
template <class ComInterface>
void
SafeRelease(ComInterface*& object)
{
    if (nullptr != object)
    {
        object->Release();
        object = nullptr;
    }
}

template <typename XAudio2Voice>
void
SafeDestroyVoice(XAudio2Voice*& object)
{
    if (nullptr != object)
    {
        object->DestroyVoice();
        object = nullptr;
    }
}
```

I want the first one to be applied only on objects based on IUnknown and the second one to objects only based on IXAudio2Voice. 
Better yet it would be if I can have all these templated functions have the same name including the standard:

```
template <typename T>
void 
SafeDelete(T*& object)
{
    if (nullptr != object)
    {
        delete object;
        object = nullptr;
    }
}

template <typename T>
void 
SafeDelete_Array(T*& object)
{
    if (nullptr != object)
    {
        delete[] object;
        object = nullptr;
    }
}
```

I guess this can be done with std::enable_if but I can't get the code to compile.

**Comment by BrentRe** [comment]
This is a great question for a forum like StackOverflow.

We'd prefer to keep this issues list focused on issues specially with C++/WinRT.

**Comment by Zingam** [comment]
I was looking at `base.h` how enable_if was used with IUnknown but couldn't what I saw 
what I saw apply to my code.

Sorry about that.
