### ISSUE TITLE
Why isn't the TabView in windows.ui.xaml.controls.h?

### ISSUE THREAD

**Issue by amtopel** [microsoft/cppwinrt#1150]
I'm trying to create a TabView using Xaml Islands, but the TabView isn't declared in winrt/windows.ui.xaml.controls.h.  Any reason why it isn't there?  Thank you for any assistance!

**Comment by DefaultRyan** [comment]
[TabView](https://docs.microsoft.com/en-us/windows/apps/design/controls/tab-view) is in the WinUI library, in `Microsoft.UI.Xaml.Controls`. It's not in the `Windows` namespace.

**Comment by amtopel** [comment]
Thanks, that's actually what I meant.  But the TabView isn't declared in that header, either if you download the cpp/winrt NuGet package, or if you download it as a Visual Studio component.
