### ISSUE TITLE
Project all existing COM interfaces as C++/WinRT interfaces

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1151]
Related to https://github.com/microsoft/xlang/issues/775.

Project all existing the COM interfaces (at least ones in the Windows SDK) as C++/WinRT interfaces that inherits from Windows::Foundation::IUnknown or Windows::Foundation::IInspectable, methods return result instead of HResult with automatic propagation of exceptions and types work as smart pointer wrappers without needing com_ptr.

**Comment by kennykerr** [comment]
One of the considerations for cppwinrt v3 is support for Win32/COM APIs, much like what [windows-rs](https://github.com/microsoft/windows-rs) does by providing uniform access to all APIs and not just WinRT APIs. Certainly not something we can tackle before then but feel free to mention it on #1123.
