### ISSUE TITLE
Include cppwinrt.exe built for x64 and ARM64 in NuGet

### ISSUE THREAD

**Issue by walbourn** [microsoft/cppwinrt#1152]
The `Microsoft.Windows.CppWinRT` NuGet package currently includes only a 32-bit (x86) version of ``cppwinrt.exe``. While this works on most development systems running Windows, it won't run on Windows Server x64 that ships without x86 support by default.

Since this tool should only be used on *development systems* it's reasonable to ship it as an x64 native binary in most cases. That said, for Windows on ARM64 an arm64 native binary is important--Windows 11 on ARM64 supports x64 native emulation, but Windows 10 on ARM64 does not.

**Comment by r2d2Proton** [comment]
I renamed the NuGet package to a zip and zipped it. The unzipped folder structure has bin, build, package, .signature.p7s, LICENSE, readme.txt, etc. I would like to run the tool to update my installed Windows Kits folders. Is that doable?

Currently I am trying the following but getting an Invalid DOS signature:
\Downloads\cppwinrt>bin\cppwinrt -input build\native\Microsoft.Windows.CppWinRT.targets -output "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0"

The tool responds with: cppwinrt : error Invalid DOS signature

I tried with the signature copied into the bin directory but that didn't help.

Can you provide the syntax to update my "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0" folder?

**Comment by sylveon** [comment]
While this is a bit offtopic to the issue - you should not change the SDK's header files. `-input` expects `.winmd` binary files, while you're passing it a msbuild target file, hence the error you're seeing. You should pass in `sdk` and then generate it to a local folder, which you add to your include path. You can get command line help by using `cppwinrt --help`

**Comment by kennykerr** [comment]
Feel free to contribute the necessary change - no objections here - we just don't have the bandwidth to handle this right now.
