### ISSUE TITLE
Equivalent of C++/CX "internal" access modifier in winRT classes

### ISSUE THREAD

**Issue by brabebhin** [microsoft/cppwinrt#1153]
Hello,

This may sound like a stupid question, but i've looked around quite a bit and could not find a good answer.
I am migrating a large-ish library from C++/CX to C++/winRT. This library contains both "winRT C++" and standard C++, and classes from both world interact in a circular fashion (C++/CX calls into standard C++ and standard C++ into C++/CX). With C++/CX this was pretty easy to deal with, as there was a very clear separation of concerns and capabilities that seem to be blured in C++winRT. 

One of the cool things about C++/CX is that it would allow ref classes to contain "internal" members, that would only be available within the namespace of the Windows Runtime Component, but not to outsiders. Those internal members would be consumed by standard C++ classes at will.

C++/winRT does not have this modifier, as it sticks to standard C++ as much as possible. Initially I assumed that I could put stuff in my runtime classes that's not defined in IDL and this would be visible inside the component project but not outside. This seems to have backfired, as it seems "pain C++" classes don't seem to be able to access the non-idl fields.

Is there a special technique to achieve this easily?

Thanks.

**Comment by sylveon** [comment]
You can directly access the class that implements the runtime component from within the same project by calling `thing.as<implementation::MyType>()`. You'll be able to access anything that's public on the implementation type, while the projection still only shows what you've wrote in the IDL.

**Comment by brabebhin** [comment]
Thanks. That worked!
