### ISSUE TITLE
Weird hstring.empty() behavior immediately after using co_await

### ISSUE THREAD

**Issue by YourOrdinaryCat** [microsoft/cppwinrt#1154]
Say I have this block of code:

```C++
IAsyncAction DoThingAsync(hstring const& par)
{
	if (!par.empty())
		throw hresult_invalid_argument(L"first check went wrong: " + par);

	// Some intensive tasks
	using namespace std::chrono;
	co_await 1s;

	if (!par.empty())
		throw hresult_invalid_argument(L"second check went wrong: " + par);
}
```

Passing `hstring{ }` to `DoThingAsync` will throw on the second check, with some weird output:

```
second check went wrong: ˕翻
```

Am I missing something here? Commenting out `co_await 1s;` doesn't throw (as expected), and passing a non empty hstring makes it throw on the first check (as expected).

Using CppWinRT 2.0.220531.1 on VS2022 17.2.3, Platform Toolset set to v143. This is also within a Runtime Component.

**Comment by sylveon** [comment]
You're taking the hstring by reference, so by the point you hit the second `empty()` check it has been freed by the caller (because the coroutine returns to the caller by the first suspension point). If you want a use the parameters in a coroutine, you should take them by value.

**Comment by YourOrdinaryCat** [comment]
Thanks, Visual Studio gave me some weird warning about it but it was showing up inconsistently, thought I was going crazy.
