### ISSUE TITLE
extract a raw pointer from Buffer, SoftwareBitmap, etc. objects

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#116]
How do get a raw pointer from buffer related object? I hope I can find a one-line coding solution for this since the concept for C++/WinRT is standard c++; 

I find a similar example here: https://blogs.msdn.microsoft.com/practice-sharing/2015/08/06/how-to-obtain-the-data-pointer-from-the-imemorybufferreference-c-c/. 

Is there a way not to import com object? After all, it's standard c++?

**Comment by KevinWelton** [comment]
Check out the IBuffer sample in the posted source.

**Comment by bigdimboom** [comment]
This is exactly what I'm looking for. Thanks. But I'm getting a lot of errors. 
![image](https://cloud.githubusercontent.com/assets/6119906/23223421/09c92172-f8f9-11e6-96fd-9d6f45c1087f.png)

BTW, the IBuffer in the repo example runs fine.

**Comment by BrentRe** [comment]
The IBuffer sample includes robuffer.h without issue so you'll need to determine what your code is doing incorrectly/differently that causes the errors.

**Comment by bigdimboom** [comment]
In cpp files, must include pch.h first before you include anything else.
