### ISSUE TITLE
How to initialize the Win8+ Application STA (ASTA)

### ISSUE THREAD

**Issue by lb90** [microsoft/cppwinrt#1162]
Hello, I'm not sure if the question belongs here or should instead be posted to the WindowsAppSdk repo.
I'd like to know whether it's possible to activate the ASTA from regular Win32 applications running on Windows 8 or later. That would be handy to avoid potential re-entrancy issues of the regular STA without resorting to CoRegisterMessageFilter.

Kind regards!

**Comment by kennykerr** [comment]
Yep, probably best to bring this up in a more appropriate forum. I generally recommend:

* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/

This repo is purely for cppwinrt bugs.
