### ISSUE TITLE
How to get activatable class id? 

### ISSUE THREAD

**Issue by brabebhin** [microsoft/cppwinrt#1163]
Hi. 

Some winRT API require activatable clsss id,  like this one

https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.addvideoeffect?view=winrt-22621

How do I get it?

**Comment by BenJKuhn** [comment]
Typically this woudl come directly from documentation. It's usually the fully qualified name of the class in "." notation, case sensitive. E.g. "Windows.Foundation.Uri". For most classes you can also get it from the IInspectable interface on the class, using "GetRuntimeClassName". 

When taken as a parameter like that, it's usually used for activation. E.g. in a call to "RoGetActivationFactory" or similar. Note that not all runtime classes are directly activatable (equivalent to how not all C++ classes have a publicly available constructor).

Ben

**Comment by sylveon** [comment]
You can obtain the fully qualified name with `winrt::name_of`

**Comment by brabebhin** [comment]
Thanks @sylveon
