### ISSUE TITLE
How to consume WinRT component inside Win32 dll project?

### ISSUE THREAD

**Issue by venki-thiyag** [microsoft/cppwinrt#1167]
Using [Registration-free WinRT](https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/) it is possible to load WinRT components inside Win32 application.

What's the process to load WinRT component from inside Win32 dll? I tried the steps mentioned as part of Win32, but winmd files are not generating the corresponding header files.

Main usage scenario is dll can be loaded any application, like electron node addon or c# app etc., Without any changes to application, dll by itself should be able to consume WinRT component!

Same question at stackoverflow:
https://stackoverflow.com/questions/72954078/how-to-consume-winrt-component-inside-win32-dll-project

**Comment by kennykerr** [comment]
This repo is for cppwinrt-specific issues. stackoverflow is a good place to ask such questions. You can also try https://docs.microsoft.com/en-us/answers/topics/windows-api.html
