### ISSUE TITLE
CppWinRT should allow excluding parts of the metadata references from projections

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#1171]
Today cppwinrt allows excluding some types from component codegen.
However no such option exists for types that are part of the reference metadata:

see: https://github.com/microsoft/cppwinrt/blob/f65801e69f1086951ca3a18d59e5156ea79a3291/cppwinrt/main.cpp#L192

The ability to exclude certain types from projection has 2 main benefits, especially in the context of XAML/WinUI apps
- reduced amount of code in projection headers. This has the potential to reduce build times, potentially drastically. 
- with the introduction of WebView2 into WinUI 2.8, applications are now forced to also reference the WebView2 metadata. While there are many benefits to this control over the WebView1 control, many applications that aren't using either WebView control are still forced to carry it around, generate metadata, build the projections, etc.

To solve this (I played with this a bit today but it'd take more time than I have tonight :)), we'd likely need to add some code like this to every `write_*` function template:

```cpp
      if (!settings.projection_filter.includes(type)) {
        auto n = type.TypeName();
        std::printf("Skipping forward %s\n", n.data());
        return;
      }
```

Note that the projection_filter "includes" currently only adds rules for non-platform reference types.
This means that if the app references the MUX metadata, and the MUX metadata references a platform type like `Windows.UI.Xaml.Markup.IXamlMetadataProvider`, it won't be found in the projection filter, and therefore will be excluded.
We don't want that, we want the types in the references to be projected, _unless_ they are excluded via some new `-refExclude` option, for example.

**Comment by sylveon** [comment]
This would be extremely useful for the WinUI 2.8 case, as of right now we have to install the webview 2 nuget, and unless we do some contrived hacks to get it out of the final package while keeping the VS project happy, also have to ship it with our app despite not using it.

**Comment by kennykerr** [comment]
The include/exclude mechanism is somewhat brittle as its encumbered by compatibility constraints, primarily imposed by Xaml, so its unlikely we can easily change this today without very very careful consideration for all of the existing compatibility requirements across the OS and Xaml applications.
