### ISSUE TITLE
Inability to use more than one precompiled header in project using CppWinRT

### ISSUE THREAD

**Issue by disaffecto** [microsoft/cppwinrt#1178]
Although you can use only one precompiled header (.pch) file per source file, you can use multiple .pch files in a project. And if you try to use multiple .pch files in a project using CppWinRT (namely, using xaml) then everything breaks.

The problem comes from two places in `Microsoft.Windows.CppWinRT.targets`. The first is the `CppWinRTMakeComponentProjection` target:
https://github.com/microsoft/cppwinrt/blob/9fc5cecf4ca2039777a3a7ab535d030915d56c18/nuget/Microsoft.Windows.CppWinRT.targets#L800-L814

and the second target is `CppWinRTAddXamlMetaDataProviderCpp`:
https://github.com/microsoft/cppwinrt/blob/9fc5cecf4ca2039777a3a7ab535d030915d56c18/nuget/Microsoft.Windows.CppWinRT.targets#L445-L454

If you have more than one .pch in your project then `_PCH` variable will be populated with list. It leads to error in first target
```
cppwinrt : error Option 'pch' accepts at most 1 value(s)
```
and it will generate invalid include in the second target, for example:
```
#include "pch1.h
pch2.h"
```
Luckily, we can fix error in the first target by defining property `CppWinRTPrecompiledHeader` in project, which makes CppWinRT to use provided pch file name. Although, [readme](https://github.com/microsoft/cppwinrt/blob/9fc5cecf4ca2039777a3a7ab535d030915d56c18/nuget/readme.md#customizing) doesn't mention `CppWinRTPrecompiledHeader`. Is it considered private?

As for the second target - I can't see any workaround. It would be nice to have some way to control the .pch file name for the second target in a similar way:
```
<PropertyGroup>
	<_PCH>@(ClCompile->Metadata('PrecompiledHeaderFile')->Distinct())</_PCH>
	<CppWinRTPrecompiledHeader Condition="'$(CppWinRTPrecompiledHeader)'==''">$(_PCH)</CppWinRTPrecompiledHeader>
	<XamlMetaDataProviderPch Condition="'$(CppWinRTPrecompiledHeader)'!=''">#include "$(CppWinRTPrecompiledHeader)"</XamlMetaDataProviderPch>
	<XamlMetaDataProviderCppLines>
// This file is generated by the build to support Xaml apps
$(XamlMetaDataProviderPch)
#include "XamlMetaDataProvider.h"
#include "XamlMetaDataProvider.g.cpp"
</XamlMetaDataProviderCppLines>
</PropertyGroup>
```

**Comment by kennykerr** [comment]
The build support is largely in maintenance and only receiving critical fixes to avoid destabilizing existing projects. Unless you can convince @Scottj1s to add support, this will unfortunately not be supported.

**Comment by Scottj1s** [comment]
We don't have any plans to support multiple PCH files per project, which is an atypical pattern.  In addition to your workaround, a solution can factor multiple projects (e.g., add a static lib) to achieve the same thing.
