### ISSUE TITLE
Cannot append to IVector

### ISSUE THREAD

**Issue by SushiTee** [Microsoft/cppwinrt#118]
I'm trying to use the file picker to save a file

```C++
    FileSavePicker savePicker;
    savePicker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);

    Collections::IVector<winrt::hstring> plainTextExtensions;
    plainTextExtensions.Append(L".txt");
    savePicker.FileTypeChoices().Insert(L"Plain Text", plainTextExtensions);
    savePicker.SuggestedFileName(L"New Document");

    create_task(savePicker.PickSaveFileAsync()).then([this](StorageFile const & file)
    {
        if (file != nullptr)
        {
            // Prevent updates to the remote version of the file until we finish making changes and call CompleteUpdatesAsync.
            CachedFileManager::DeferUpdates(file);
            // write to file
            create_task(FileIO::WriteTextAsync(file, file.Name())).then([this, file]()
            {
                // Let Windows know that we're finished changing the file so the other app can update the remote version of the file.
                // Completing updates may require Windows to ask for user input.
                create_task(CachedFileManager::CompleteUpdatesAsync(file)).then([this, file](FileUpdateStatus status)
                {
                    if (status == FileUpdateStatus::Complete)
                    {
                        // done
                    }
                    else
                    {
                        // fail
                    }
                });
            });
        }
    });
```

When I try to access the function which runs that code the program crashes at line 4419 in base.h.
```C++
template <typename D, typename T>
void impl_IVector<D, T>::Append(const T & value) const
{
    check_hresult(static_cast<const IVector<T> &>(static_cast<const D &>(*this))->abi_Append(get(value)));
}
```

This is called by this line from my code:
```C++
plainTextExtensions.Append(L".txt");
```

I don't get why I cant append to the IVector. In CX the relevant code looks like this:

```C++
auto plainTextExtensions = ref new Platform::Collections::Vector<String^>();
plainTextExtensions->Append(".txt");
```

What am I doing wrong?

**Comment by kennykerr** [comment]
Your particular example fails because you have not provided an implementation of `IVector<T>`. You merely have an interface that does not yet point to an instance of `IVector<T>`. The next C++/WinRT update will make it easier to create collections.

You should also not use the PPL adapters with C++/WinRT. They don't work well and introduce more problems than they solve. I'm hoping to remove them from a future update. Using coroutines is much simpler. Here's an example that should work for you:

```C++
void SetWindow(CoreWindow const & window)
{
    m_activated = window.Activated(auto_revoke, { this, &App::OnActivated });
}

fire_and_forget OnActivated(CoreWindow, WindowActivatedEventArgs)
{
    m_activated.revoke();

    FileSavePicker savePicker;
    savePicker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
    savePicker.FileTypeChoices().Insert(L"Plain Text", { L".txt" });
    savePicker.SuggestedFileName(L"New Document");

    StorageFile file = co_await savePicker.PickSaveFileAsync();

    if (file == nullptr)
    {
        co_return;
    }

    CachedFileManager::DeferUpdates(file);
    co_await FileIO::WriteTextAsync(file, file.Name());
    FileUpdateStatus status = co_await CachedFileManager::CompleteUpdatesAsync(file);

    if (status == FileUpdateStatus::Complete)
    {
        WINRT_TRACE("done\n");
    }
    else
    {
        WINRT_TRACE("fail\n");
    }
}
```

**Comment by SushiTee** [comment]
Thank you for the reply but when I try this it still crashes here:

```C++
template <typename D, typename TResult>
void impl_IAsyncOperation<D, TResult>::Completed(const AsyncOperationCompletedHandler<TResult> & handler) const
{
    check_hresult(static_cast<const IAsyncOperation<TResult> &>(static_cast<const D &>(*this))->put_Completed(winrt::get(handler)));
}
```

My function looks like this now. And I'm just calling it.

```C++
winrt::fire_and_forget saveAsync() {
	FileSavePicker savePicker;
	savePicker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
	savePicker.FileTypeChoices().Insert(L"Plain Text", { L".txt" });
	savePicker.SuggestedFileName(L"New Document");

	StorageFile file = co_await savePicker.PickSaveFileAsync();

	if (file == nullptr)
	{
		co_return;
	}

	CachedFileManager::DeferUpdates(file);
	co_await FileIO::WriteTextAsync(file, file.Name());
	FileUpdateStatus status = co_await CachedFileManager::CompleteUpdatesAsync(file);

	if (status == FileUpdateStatus::Complete)
	{
		//
	}
	else
	{
		//
	}
```

As additional information... I' not trying to just write a windows store app. This app should also work for Android and iOS. So I'm using Qt to write the app but I try to use some WinRT specific functions to make the user experiance better... saving and open files is just one thing of it.
So the plan is to write a Component in C++ which is usable in QML later. It should just open the native file dialog and return a signal after the file is written.

**Comment by kennykerr** [comment]
I don't know anything about Qt, but we are investigating the coroutine crash.

**Comment by SushiTee** [comment]
My guess is that Qt starts a thread with the correct window handle and so on and then the thread gets caneled before the coroutine is actually done. I tried to replace fire_and_forget with IAsyncOperation and actually return something and then call openAsync().get() in the lambda function there to make it block but it just does that. It blocks and nothing happens anymore.

**Comment by kennykerr** [comment]
Keep in mind that you cannot call .get() from a UI thread since it blocks the message pump.

**Comment by SushiTee** [comment]
This makes sense. The first problem I had was the "invalid window handle". As I understand it the long runOnXamlThread gets the window handle an does seomthing that the WinRT calls work. Qt uses those ABI functions with ComPtr and so on to make the file picker work. But the item which Qt provides doesn't do everything I need. As yu said in your cppcon presentation you can do everything just like you would do with C#.
So I'm wondering if you could do some coroutine which sets the correct window handle and let you do all the stuff. Doing a thread for this so it doesn't run in the UI thread is no problem. I know how to get a window handle but I have no idea how I can use it.

**Comment by kennykerr** [comment]
The coroutine crash ended up being a COM marshaling bug. We've fixed that and will have an update out soon.

**Comment by SushiTee** [comment]
since the latest update this line doesn't work anymore:
```C++
savePicker.FileTypeChoices().Insert(L"Plain Text", { L".txt" });
```
initializer list cannot be converted to IVector<hstring>

**Comment by kennykerr** [comment]
We just published an update that fixes the file picker crash. 

The `FileTypeChoices` collection is an unusual API in that it takes an `IVector<T>` as an input parameter rather than the more customary `IVectorView<T>`. If it were the latter, it would just work. But we need to do a bit more work to support `IVector<T>` in this scenario. For the moment, you can work around this by creating a simple `IVector<T>` implementation explicitly:

```C++
savePicker.FileTypeChoices().Insert(L"Plain Text", single_threaded_vector<hstring>({ L".txt" }));
```

Hope that helps.
