### ISSUE TITLE
Issue with array types in IDL

### ISSUE THREAD

**Issue by DerekDally** [microsoft/cppwinrt#1182]
Hi -

I'm trying to add an array type to one of my interface classes (originally was String[], but I see the issue with UInt16[], etc as well so doesn't seem to be related to the contained type) and I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2672	'unbox_value_type': no matching overloaded function found (compiling source file Generated Files\XamlTypeInfo.g.cpp)	ArrayTest	C:\Users\ddally\source\repos\ArrayTest\ArrayTest\Generated Files\winrt\Windows.Foundation.h	3066	
Error	C2665	'winrt::impl::consume_ArrayTest_IMainWindow<winrt::ArrayTest::IMainWindow>::MyProperty': none of the 2 overloads could convert all the argument types	ArrayTest	C:\Users\ddally\source\repos\ArrayTest\ArrayTest\Generated Files\XamlTypeInfo.g.cpp	88	

It's definitely possible that I'm missing something on my side, is it a matter of needing to include an additional header somewhere?  I did see mention made of certain template specializations related to unboxing only being available if Windows.Foundation.h is included but it's in my pch.h.

Steps to reproduce:
Change "Int32 MyProperty" to "Int32[] MyProperty" in MainWindow.idl of newly created project and update header and source with generated stub functions.

Thanks,
Derek

**Comment by sylveon** [comment]
That appears to be an XAML compiler issue, as the error is in XamlTypeInfo.g.cpp

**Comment by kennykerr** [comment]
Yes, I'd suggest raising the issue with the Xaml team (https://github.com/microsoft/microsoft-ui-xaml).
