### ISSUE TITLE
Zero GUID when unknwn.h is not included

### ISSUE THREAD

**Issue by mcooley** [microsoft/cppwinrt#1186]
Before #1180, this code successfully prints the GUID of ICompositorInterop. After #1180 it prints `{00000000-0000-0000-0000-000000000000}`:

```
#include <winrt/Windows.UI.Composition.h>
#include <windows.ui.composition.interop.h>

int main()
{
    printf("GUID for ICompositorInterop: %ls\n", winrt::to_hstring(winrt::guid_of<ABI::Windows::UI::Composition::ICompositorInterop>()).c_str());
}
```

C++/WinRT should just work in this case, or tell me that I need to include unknwn.h before including winrt/base.h.

Maybe the MSVC part of #1180 should be reverted, since it might not be needed? Maybe the [fallback definition of guid_v](https://github.com/microsoft/cppwinrt/blob/380cb8f773e1b9da8d947f6567eeaac401e0c33c/strings/base_meta.h#L130) should trigger an error when it's used?

**Comment by kennykerr** [comment]
Yes, this looks like a regression which would be hard to catch. I think that #1180 didn't need to "fix" MSVC behavior even if it was questionable. @oldnewthing

**Comment by kennykerr** [comment]
I had a look but couldn't find a way to get the fallback to produce an error.

**Comment by sylveon** [comment]
How about:

```cpp
template <typename T>
struct com_guid
{
#if defined(_MSC_VER) && defined(WINRT_IMPL_IUNKNOWN_DEFINED)
    static constexpr guid value{ __uuidof(T) };
#endif
};

template <typename T>
inline constexpr guid guid_v = com_guid<T>::value;
```
This should error because `value` wouldn't exist.

While the compiler error may not be the easiest to understand, it definitely beats a strange runtime error.

**Comment by kennykerr** [comment]
Sounds good! Want to send me a PR?

**Comment by sylveon** [comment]
I can take a look sometime this weekend
