### ISSUE TITLE
Two cppwinrt VS addons?

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#1188]
I was trying to uninstall an unrelated VS addon and when going through the list of installed addons somehow it appears I have two cppwinrt VS addons - is this normal?

![image](https://user-images.githubusercontent.com/6440374/190885788-0a6ee181-f312-4e9a-9237-94d34eee31c7.png)

**Comment by kennykerr** [comment]
For Visual Studio 2022, the project templates and visualizer now ship as part of the product but the nuget package with the core cppwinrt compiler still ships separately so that it may be updated more frequently.

**Comment by sylveon** [comment]
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0

The first addon from my screenshot is version 2.0.220531.1 and the second addon is version 2.0.210806.1. Though the second addon doesn't say "There are installed components that depend on this extension" while the first does. Since the second is older I can probably just uninstall it.

![image](https://user-images.githubusercontent.com/6440374/191127448-ccd33719-ed4a-4208-8aef-4c71854dccf7.png)

**Comment by kennykerr** [comment]
@DefaultRyan any update on this?

**Comment by DefaultRyan** [comment]
Thanks for the patience, I'll get on this issue this week.
