### ISSUE TITLE
How do I register a button-clicking event? 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#119]
The XamlCode sample shows how to play around with Testblock but without showing how to align these "widget"s correctly. As a system programmer, I wish I can pragmatically create, edit, UI widgets and register some button-clicking events fast just for debugging. I'm wondering where I could find these document/examples.

**Comment by BrentRe** [comment]
This is not a question about C++/WinRT. For "how to" XAML programming questions, I suggest you enlist the community at StackOverflow. They are a great resource. Additionally, many times, you can add a control and examine the code behind file to see how it is created and initialized programmatically.
