### ISSUE TITLE
[question] The natvis warnings for unknown types spam the output window. Is there a possibility to suppress these?

### ISSUE THREAD

**Issue by ridilculous** [microsoft/cppwinrt#1192]
The [natvis warnings for unknown types](https://github.com/microsoft/cppwinrt/blob/64cdc7c6d806c94ae51417042c40f351b4c487b9/natvis/cppwinrt_visualizer.cpp#L234) sometimes spam the output window. Is there a possibility to suppress these?

_Example_:
`Natvis C++/WinRT: Unrecognized type: winrt::impl::producer<winrt::TestApp::implementation::MyValue,winrt::TestApp::IMyValue,void>`

**Comment by kennykerr** [comment]
I don't know - @Scottj1s? This might be more of a feature request for Visual Studio.

**Comment by kennykerr** [comment]
I suggest you try the VS feedback site https://developercommunity.visualstudio.com/search?space=62 or https://stackoverflow.com/ - sorry I don't have any experience with this.
