### ISSUE TITLE
C++ Streams support for hstring and IStringable

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1195]
Today it doesn't seem possible to output an hstring directly to a C++ stream (eg: wcout). 

```
cpp
hstring text;
// Doesn't work.
std::wcout << text;

// Works.
std::wcout << text.c_str();
std::wcout << static_cast<std::wstring_view>(text);
```

Please overload operator<< for hstring, as well as types implementing IStringable.

**Comment by kennykerr** [comment]
This isn't supported but is trivial to work around as you've illustrated. Most applications don't require this support, so it wasn't deemed a necessary dependency.

**Comment by sylveon** [comment]
if you really want `std::wcout << hstr` to compile:
```cpp
std::wostream& operator<<(std::wostream& os, winrt::hstring const& str)
{
    os << static_cast<std::wstring_view>(str);
    return os;
}
```

`IStringable` left as an exercise to the reader ;)

**Comment by Jaiganeshkumaran** [comment]
I would still prefer it to be built-in. Even if Windows GUI apps aren't going to use wcout, they can still use other stream types like wstringstream and wifstream.
