### ISSUE TITLE
What is behavior of const-qualifier on C++/WinRT projected type?

### ISSUE THREAD

**Issue by andy-schmidt** [microsoft/cppwinrt#1197]
I have a minor question about the behavior of `const` qualification of C++/WinRT projected types. The docs state that the [project type is essentially a proxy object containing a smart pointer to the object instance.](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis#:~:text=it%27s%20essentially%20just%20a%20smart%20pointer%20to%20a%20backing%20object)

Can I safely assume then that `const` qualification has the same behavior as[ std::shared_ptr](https://stackoverflow.com/questions/17793333/difference-between-const-shared-ptrt-and-shared-ptrconst-t)? That is, `const` qualification won't transfer ownership of the reference count? I haven't been able to find answer to this in the docs.

This may seem a minor point, but `const`-correctness is often important and it the above assumption may also be incorrectly using a leaky abstraction.

**Comment by sylveon** [comment]
const behaves mostly like std::shared_ptr, correct.

**Comment by tim-weis** [comment]
> That is, `const` qualification won't transfer ownership of the reference count?

I'm not sure what this is asking about. The reference count is a value that represents the number of owners. The reference count has no owner, and consequently ownership of the reference cannot be transferred.

That said, a `const`-qualifier on a projected type doesn't actually describe immutability of the referenced type. It refers to the internally stored interface pointer only, which is ultimately an implementation detail of the smart pointer in use.

**Comment by andy-schmidt** [comment]
The overall question is what does `const` qualification do to C++/WinRT projected types? For example, how does the behavior of `my_uri` declared by
`const winrt::Windows::Foundation::Uri my_uri{ L"https://www.contoso.com" };`
differ from `my_uri` declared by
`winrt::Windows::Foundation::Uri my_uri{ L"https://www.contoso.com" };`
?

This is not covered anywhere in C++/WinRT documentation that I can find. In contrast, there is some documentation on the behavior of [`const` qualification of C++/WinRT implementation types in the C++/WinRT FAQ](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq#why-doesn-t-the-generated-implementation-function-for-a-read-only-property-have-the-const-qualifier-:~:text=C%2B%2B/WinRT.-,Why%20doesn%27t%20the%20generated%20implementation%20function%20for%20a%20read%2Donly%20property%20have%20the%20const%20qualifier,-%3F). Without this documentation, library users have to either make assumptions based on [non-detailed conceptual descriptions of the projected type](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis#:~:text=it%27s%20essentially%20just%20a%20smart%20pointer%20to%20a%20backing%20object), or read the projected type implementation source code itself. When library users start making assumptions about the implementation details of the library, then there is the potential to break the abstraction that the library is providing. Do the C++/WinRT maintainers promise that the detailed behavior of C++/WinRT projected types will not change? In the absence of documentation, this detail must be understood by library users in order to what the above `const` qualification does.

**Comment by sylveon** [comment]
When it's const it means you can't reassign the reference. const is not a concept in WinRT metadata so it does not propagate to the referenced object - all API calls are still available.

**Comment by kennykerr** [comment]
Yep, this is more of a C++ question than a question about C++/WinRT. Most projected types are just wrappers around COM interface pointers and as such the only potentially mutable state is the value of the COM interface pointer itself and there isn't much you can directly do with that value other than transfer ownership.

**Comment by andy-schmidt** [comment]
Thanks for the quick responses, this is very much appreciated. This may seem like splitting hairs, but it helps us out a lot in setting up consistent developer guidelines for using `const` qualifiers.
