### ISSUE TITLE
overridable methods not called on derived classes

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/cppwinrt#1198]
I have a base class with a method which then calls override methods on sub class implementations. Here is an example of the idl:

```
    [default_interface]
    unsealed runtimeclass Class
    {
        protected Class();
        overridable void OnDoTheThing();
        void DoTheThing();
    }

    unsealed runtimeclass Derived : Class
    {
        protected Derived();
        Int32 MyProperty;
    }

    runtimeclass Derived2 : Class
    {
        Derived2();
        Int32 MyProperty;
    }
 ```
 
 When I call `DoTheThing`, the `OnDoTheThing` method is called. However, the overriden methods by subclasses is never called. I've attached a repro app:

[App1.zip](https://github.com/microsoft/cppwinrt/files/9758897/App1.zip)

**Comment by stevenbrix** [comment]
Ok, just found out what I was doing wrong. My base `OnDoTheThing` method needs to look like this:

```
        auto overrides = overridable();
        overrides.OnDoTheThing();
```

**Comment by sylveon** [comment]
You can also make OnDoTheThing virtual on your implementation, I believe: https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#overriding-base-class-virtual-methods

**Comment by kennykerr** [comment]
Overrides are very costly and complex and only exist to support Xaml, so I'd recommend staying clear unless that's actually what you need. Prefer events if practical.
