### ISSUE TITLE
how do I upload dll file or where do I put dll files for a UWP app

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#120]
How do I use dynamically linked lib and upload dlls to a windows device such as XBox?

**Comment by BrentRe** [comment]
This is not a question about C++/WinRT. Additionally, any questions about Xbox should be addressed through your channels as an Xbox developer.

**Comment by walbourn** [comment]
For a UWP, you can include DLLs inside the package. Those DLLs must pass WACK particularly for API validation, need to use the VS 2015 C/C++ Runtime, and need to be listed as dependencies in your AppX manifest.

You can't deploy system DLLS this way, nor can you deploy 3rd party system DLLs generally on Xbox One.
