### ISSUE TITLE
check_bool<T> should return T

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1204]
Today, winrt::check_bool<T> returns void. There are some Win32 APIs that return 0 on failure and a valid result on success eg: [GetFileVersionInfoSizeW](https://learn.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfosizew) so having winrt::check_bool<T> returning T would be convenient while using them.

**Comment by kennykerr** [comment]
Sounds reasonable - feel free to contribute the change.
