### ISSUE TITLE
How can I post some message to UI thread from other thread ?

### ISSUE THREAD

**Issue by Endt4sk** [microsoft/cppwinrt#1208]
How can I post some message to UI thread from other thread ? 

I have a thread create by other c++ lib, when it finish I want to inform UI thread to do some work, How can I do this?

Thanks a lot!

**Comment by kennykerr** [comment]
For general programming questions, please visit https://stackoverflow.com/.

**Comment by sylveon** [comment]
You would want to use DispatcherQueue.TryEnqueue
