### ISSUE TITLE
Where are the abi apis for IBuffer

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#121]
I update winrt library
I can not find the "->" operator for accessing abi calls in Buffer Object. What do I do instead?

**Comment by KevinWelton** [comment]
See the [breaking change notice](https://github.com/Microsoft/cppwinrt/blob/master/Breaking%20Changes.md). The free function _get_abi(your_object_instance)_ should now be used to retrieve an object's ABI in your scenario. With the returned object, you can call the ABI methods.
