### ISSUE TITLE
Feature request: static `as<T>()` for accessing activation factory

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#1213]
C#/WinRT provides a convenience for accessing a class factory, in order to cast to an interop.  C++/WinRT could add that too, to improve discoverability:

So that instead of:
`        auto printManagerInterop = winrt::get_activation_factory<winrt::Windows::Graphics::Printing::PrintManager>().as<IPrintManagerInterop>();
`
You could just:
`        auto printManagerInterop = winrt::Windows::Graphics::Printing::PrintManager::as<IPrintManagerInterop>();`

**Comment by kennykerr** [comment]
Note that you'd have to generate an `as` function template on each runtime class rather than rely on a single `get_activation_factory` function template, but it sounds like it could be quite useful.

**Comment by Jaiganeshkumaran** [comment]
With this you can cast the factory to some interface, but how will you get the default factory in the first place without specifying the interface? I would prefer having a factory "static property" in the class that returns the default factory interface and then you can call as (or try_as) on it.

**Comment by sylveon** [comment]
That's what `get_activation_factory` is for, no? Generally, the activation factory doesn't provide much usefulness compared to just calling statics/constructors directly through the projection. It's mostly useful once you cast it to some interop interface.

**Comment by Scottj1s** [comment]
All, this would simply be a wrapper around get_activation_factory, with the same template param.  So, it's not closing a feature gap - it's trying to make the casting operation a bit more discoverable, with Intellisense, etc.

**Comment by kennykerr** [comment]
And I was just implementing this and realized that adding a static `as` to the class would collide with the inherited non-static `as` from `IUnknown`. Unfortunately, C++ doesn't seem to distinguish between the instance and static functions.
