### ISSUE TITLE
C++/WinRT doesn't delete old projection headers

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#1214]
Let's say you delete or rename a namespace in IDL. When building the project next time, C++/WinRT will generate a projection header for the new namespace, but the old header remains. I've run into situations where I forget to change the includes and the project still compiles, and don't realise this until something breaks. Automatically delete projection headers for namespaces that don't seem to be there in input metadata, or at least print a warning.

**Comment by kennykerr** [comment]
I'm reluctant to do that since we have some complex build configurations that combine headers from different sources in "interesting" ways that I wouldn't want to take the chance.

**Comment by sylveon** [comment]
Maybe make it an on-by-default option? `CppWinRTCleanBeforeBuildingProjection`

**Comment by kennykerr** [comment]
Is that not something you can pretty easily do directly without getting cppwinrt involved?

**Comment by sylveon** [comment]
The thing is that when iterating in APIs, you might rename namespaces, so you get in a state where the headers for the previous namespaces exist, so errors wouldn't show up until the build is cleaned (which doesn't happen during inner loop). The idea here would be that whenever cppwinrt needs to regenerate the projection, it would empty the folder containing the projection first.

**Comment by kennykerr** [comment]
Sure, but you could always wrap cppwinrt.exe in a cppwinrt.cmd that does this, no? I think that's what one of our internal builds does.

**Comment by sylveon** [comment]
Doing that while using the NuGet package is not as easy, but yeah that would work.
