### ISSUE TITLE
Consider making no_switch await adapter built-in

### ISSUE THREAD

**Issue by benstevens48** [microsoft/cppwinrt#1217]
As far as I can see (please correct me if I'm wrong) there is no equivalent of C#'s Task.ConfigureAwait(false) built-in to C++/WinRT when awaiting IAsyncInfo types. There is a sample of how to do it in the doc here https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2 (look for no_switch) and it's also in this 'The Old New Thing' blog post - https://devblogs.microsoft.com/oldnewthing/20191216-00/?p=103217. I wonder if it would be a good idea to make this built-in to C++/WinRT? C# recommends that all libraries should use ConfigureAwait(false) (where it doesn't matter about running on the UI thread) and I assume that we should be doing the same in C++/WinRT so a no_switch await adapter ought to be widely used.

**Comment by kennykerr** [comment]
The various "helpers" in C++/WinRT haven't aged well, particularly the coroutine helpers, so we're not adding any more. Instead, other dedicate libraries can provide such helpers. The C++/WinRT project should focus squarely on the projection itself.

**Comment by sylveon** [comment]
It would be a good addition to wil.

**Comment by kennykerr** [comment]
Yep, WIL already has a few helpers like this: https://github.com/microsoft/wil
