### ISSUE TITLE
Cannot {x:Bind} to property of named XAML control in C++/WinRT

### ISSUE THREAD

**Issue by MouriNaruto** [microsoft/cppwinrt#1218]
When I trying to bind something to the properties of named XAML controls, I met the compile-time error in the compilation.

I started to find why and see someone had mentioned the issue in https://github.com/microsoft/microsoft-ui-xaml/issues/2721.

I hope C++/WinRT can solve the issue.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@sylveon 

> This is a XAML compiler issue, not a cppwinrt issue.

But I found object generated by C++/WinRT IDL doesn't expose the public members from XAML compiler. So it may be the C++/WinRT's issue.

Kenji Mouri

**Comment by sylveon** [comment]
These are not meant to be added to metadata or the projection, only used internally by your implementation class. The fix is to update the xaml compiler to use the implementation type for bindings, instead of the projection type.

**Comment by MouriNaruto** [comment]
@sylveon 

> These are not meant to be added to metadata or the projection, only used internally by your implementation class.

My meaning is only to added to the C++ projection side. Not the IDL metadata.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@sylveon 

> The fix is to update the xaml compiler to use the implementation type for bindings, instead of the projection type.

I don't think XAML compiler team willing to do that. Because both C++/CX and .NET are implemented the similar things in themselves.

Kenji Mouri

**Comment by sylveon** [comment]
The projection is generated from metadata.

C++/CX and C# have partial classes, and makes no distinction between implementation and projection. C++/WinRT does not.

**Comment by MouriNaruto** [comment]
@sylveon 

> C++/CX and C# have partial classes, and makes no distinction between implementation and projection. C++/WinRT does not.

Due to C++/WinRT uses MIDL to define projection interfaces (everyone knows standard C++ needs codegen to achieve reflection and projection elegantly), and the implementations including binding definitions are already drastically different than the projection. And everyone knows it can't be no distinction. Why not introduce more differences and make developers happy？

Kenji Mouri

**Comment by kennykerr** [comment]
The Xaml team will have to decide how to handle this - that may end up being an addition to C++/WinRT, but I'd recommend taking it up with them here: https://github.com/microsoft/microsoft-ui-xaml

**Comment by sylveon** [comment]
I would contribute a fix if the XAML compiler was open source, as I have a fairly decent idea of what's wrong and how to fix it. Unfortunately it's not. Maybe one day when WinUI 3 finally open sources I'll be able to take a crack at it (and plenty of other cppwinrt specific XAML codegen issues)

**Comment by tom-huntington** [comment]
Just making sure this is easy to get around by exposing the component in the idl file
https://github.com/microsoft/microsoft-ui-xaml/issues/2721#issuecomment-737559647
