### ISSUE TITLE
Clang/GCC: Issue with operator co_await and `winrt::impl::awaiter_finder`

### ISSUE THREAD

**Issue by alvinhochun** [microsoft/cppwinrt#1219]
The promises `winrt::fire_and_forget` and `winrt::impl::promise_base` have the member function `await_transform` which uses `winrt::impl::notify_awaiter`, which uses `winrt::impl::get_awaiter`, which in turn uses `winrt::impl::awaiter_finder`.

When you do things like `co_await 10ms` in a coroutine with one of these promise types, the `await_transform` member function is called, and the `operator co_await` for `std::chrono::duration` is resolved by `winrt::impl::get_awaiter` using `winrt::impl::awaiter_finder`.

This works in MSVC, however Clang and GCC don't like it when the `operator co_await` is not declared before the definition of the `awaiter_finder` template class: https://godbolt.org/z/hbhhMdj3d

I believe this is the reason why some of the tests using `co_await` does not work on Clang without [these](https://github.com/microsoft/cppwinrt/pull/1203/commits/78734460aea87f040807be2939e9262f8d43e874) [workarounds](https://github.com/microsoft/cppwinrt/pull/1203/commits/79ec5614503a4983f9aab2da3c05abba2a1102c1) in #1203.

Any ideas? I cannot tell which compilers are doing it wrong.

**Comment by sylveon** [comment]
Maybe it's finally time to nuke get_awaiter? https://github.com/microsoft/cppwinrt/issues/996#issuecomment-896287518 @kennykerr

**Comment by kennykerr** [comment]
Yep, feel free to rip it out - I confirmed that it was never adopted.

**Comment by sylveon** [comment]
Nice! Should probably remove the workarounds from the unit tests as well to make sure that functionality is covered in testing.

**Comment by sylveon** [comment]
@alvinhochun interested in doing this, or am I good to work on it?

**Comment by alvinhochun** [comment]
> @alvinhochun interested in doing this, or am I good to work on it?

I was under the impression that you planned to work on this. Please do go ahead if you don't mind.
