### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by geminik23** [Microsoft/cppwinrt#122]
using Windows 10 Creator's Update SDK preview release

When I put this code in OnLaunched method

```c++
struct App: ApplicationT<App>
{
...
void OnLaunched(LaunchActivatedEventArgs const &)
{
    ...
    this->Suspending(SuspendingEventHandler([](auto&&...) { OutputDebugString(L":::Suspended\n"); }));
    ....
}
...
};
```
there's compile error

>Error	C2451	conditional expression of type 'const App' is illegal

**Comment by kennykerr** [comment]
Thanks for reporting this issue. We've identified the problem and will have a fix out soon.

**Comment by kennykerr** [comment]
We just published an update that fixes this problem.
