### ISSUE TITLE
App.g.h Generated Code errors or doesn't match UWP C++/CX Template

### ISSUE THREAD

**Issue by tgraupmann** [microsoft/cppwinrt#1222]
After adding the CppWinRT package from NuGet to a blank C++ UWP project, I'm getting compile errors.

Platform: Windows 10 Version 22H2 (OS Build 19045.2193)

Windows Target Platform Version:  10.0.22621.0
Windows Platform Min. Version: 10.0.17763.0

```
Build started...
1>------ Build started: Project: Issue_CppWinRT, Configuration: Debug x64 ------
1>XamlTypeInfo.g.cpp
1>D:\Public\Issue_CppWinRT\Generated Files\App.xaml.g.hpp(51,1): warning C4447: 'main' signature found without threading model. Consider using 'int main(Platform::Array<Platform::String^>^ args)'.
1>D:\Public\Issue_CppWinRT\Generated Files\MainPage.xaml.g.hpp(25,19): error C2988: unrecognizable template declaration/definition
1>D:\Public\Issue_CppWinRT\Generated Files\MainPage.xaml.g.hpp(25,19): error C2143: syntax error: missing ';' before '<'
1>D:\Public\Issue_CppWinRT\Generated Files\MainPage.xaml.g.hpp(25,10): error C2182: 'MainPageT': this use of 'void' is not valid
1>D:\Public\Issue_CppWinRT\Generated Files\MainPage.xaml.g.hpp(25,19): error C2059: syntax error: '<'
1>D:\Public\Issue_CppWinRT\Generated Files\MainPage.xaml.g.hpp(25,30): error C2039: 'InitializeComponent': is not a member of '`global namespace''
1>D:\Public\Issue_CppWinRT\Generated Files\MainPage.xaml.g.hpp(26,5): error C2143: syntax error: missing ';' before '{'
```

I created a video about the issue:

https://youtu.be/Oxr_tHbZmZY

Errors compiling with Windows Platform Min. Version: 10.0.18362.0
```
1>D:\Public\Issue_CppWinRT\App.xaml.h(8,10): fatal  error C1083: Cannot open include file: 'App.g.h': No such file or directory
1>Done building project "Issue_CppWinRT.vcxproj" -- FAILED.
```

Errors compiling with Windows Platform Min. Version: 10.0.19041.0

```
1>D:\Public\Issue_CppWinRT\App.xaml.h(8,10): fatal  error C1083: Cannot open include file: 'App.g.h': No such file or directory
1>Done building project "Issue_CppWinRT.vcxproj" -- FAILED.
```

Repro Project - https://github.com/tgraupmann/Issue_CppWinRT

**Comment by sylveon** [comment]
I don't think mixing C++/CX XAML and C++/WinRT in the same project is supported - if you want cppwinrt XAML, you need to install the cppwinrt VS addon, which will create a new Blank App (C++/WinRT) template.

**Comment by tgraupmann** [comment]
@sylveon Do you have a link? This looks 3rd party...

![image](https://user-images.githubusercontent.com/931421/199024109-6f7e4393-7ba7-45aa-a82c-91772b9c09cf.png)

**Comment by kennykerr** [comment]
I think its included in the latest version of Visual Studio - Xaml just probably doesn't support mixing C++ and CX language support in the same project.

**Comment by tgraupmann** [comment]
Yeah I"m trying to mix which for the most part works.

https://github.com/tgraupmann/ChromeOS_Whisper/tree/main/Cpp_Uwp_ServerBase

When I add `DeviceState.h` it's not generating the code for it...

https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/WindowsAudioSession/cppwinrt/DeviceState.h

**Comment by kennykerr** [comment]
Might be simpler to use a separate projects for this. Here are some folks who might have a suggestion for you: @oldnewthing @ChrisGuzak @Scottj1s @jonwis 

Otherwise, you can try: https://learn.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by tgraupmann** [comment]
Using a separate project where I used the Blank App (UWP C++/CX) project as a template. I deleted the config, manifest, and xaml files. I changed the project type from application to DLL. And then added just the `Project.IDL` does generate the files that I need. I did need to use NuGet to import the CppWinRT package to get the IDL to compile under VS 2022.

![image](https://user-images.githubusercontent.com/931421/199032992-52056cba-a8cc-4179-a6bd-3de50dada288.png)

I'll try adding the IDL project's generated folder to the include path and see if that's compatible with the WinRT project.

**Comment by tgraupmann** [comment]
Using a project reference has errors so I had to hardcode the include path.

```
2>D:\Public\ChromeOS_Whisper\Cpp_Uwp_ServerBase\Cpp_Uwp_ServerBase.vcxproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'D:\Public\ChromeOS_Whisper\Cpp_Uwp_ServerBase\x64\Debug\Idl_DeviceState\Idl_DeviceState.winmd'
2>pch.cpp
2>D:\Public\ChromeOS_Whisper\Cpp_Uwp_ServerBase\pch.cpp : fatal  error C1192: #using failed on 'D:\Public\ChromeOS_Whisper\Cpp_Uwp_ServerBase\x64\Debug\Idl_DeviceState\Idl_DeviceState.winmd'
```

**Comment by kennykerr** [comment]
Sorry to hear you're still struggling through this. Unfortunately, I have no experience with Xaml. I'd suggest [the Q&A site](https://learn.microsoft.com/en-us/answers/topics/windows-api.html), which generally gets you a direct line to an engineering team, or the Xaml team directly via their repo: 

https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by tgraupmann** [comment]
Everything compiles at this point. I have one line of WinRT that I had to comment out.
```
if (is_guid_of<::IMFAsyncCallback, ::IUnknown>(riid))
```

https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/WindowsAudioSession/cppwinrt/Common.h#L101

I'll try without and see if the MF callbacks can fire from XAML next.

**Comment by kennykerr** [comment]
You can probably upgrade to a newer version of the cppwinrt nuget and that line should compile. Otherwise, be sure to include `Unknwn.h` before including any cppwinrt headers.

**Comment by tgraupmann** [comment]
That's my first include in `pch.h`.

https://github.com/tgraupmann/ChromeOS_Whisper/blob/main/Cpp_Uwp_ServerBase/pch.h

As soon as I add `2.0.220929.3` I get problems with the generated XAML.

**Comment by tgraupmann** [comment]
Before I convert to P/Invoking from C# to C++, I won't give up on all C++ just yet...

Somehow my XAML MainPage needs to implement `winrt::implements` so that I can use `get_weak()` and `get_strong()`.
```
public ref class MainPage sealed
```

https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/implements

**Comment by oldnewthing** [comment]
The MainPage class is generated by the XAML compiler. Since you started from a C++/CX project, that is going to put C++/CX in charge: The XAML compiler runs in C++/CX mode, which means that the App and MainPage will be ref classes.

If all you need are strong and weak references, then you don't need to derive from winrt::implements. Use the native C++/CX types. In C++/CX land, you use a ^ (hat) pointer for a strong reference, and a Platform::WeakReference for a weak reference.
