### ISSUE TITLE
cmake interoperability

### ISSUE THREAD

**Issue by regnirpsj** [Microsoft/cppwinrt#124]
is there a (minimal) example using cppwinrt in a cmake-based project?

**Comment by bigdimboom** [comment]
Request cmake for regular winrt projects and for UWP projects.

**Comment by johanlindfors** [comment]
CMake already supports UWP projects, and it can easily be configured for generating cppwinrt based solutions as well, the only thing I'm struggling with currently is how to disable /ZW in that project generation.

**Comment by johanlindfors** [comment]
Fixed a simple solution that leverages CMake to generate a project using cppwinrt. Please comment!

**Comment by kennykerr** [comment]
I don't know much about cmake so I'll let others comment on that, but here are the steps you need to convert a C++/CX store project into a standard C++ project.

1. Remove /ZW
2. Remove C++/CX code
3. Add standard wWinMain function
4. Add empty app.winmd file for app package

It's that last step that most people forget. The C++/CX compiler automatically creates one and if you simply convert the project it will work for a while, until you happen to delete your output folder and rebuild.

**Comment by FeBrex** [comment]
Instead of adding an empty app.winmd one can also add a minimal idl and configure the MIDL compiler to generate the winmd

1. add <projectName>.idl, insert a namespace definition
2. Check that /winrt MIDL compiler switch is active
3. Check value of /winmd filename MIDL compiler switch

**Comment by Zingam** [comment]
@FeBrex @BrentRe 

Can we have an official example of this setup?

**Comment by Sunbreak** [comment]
I'm developing Flutter for Windows. Hope the snippet help

https://github.com/woodemi/quick_blue/pull/10/files

```cmake
set_target_properties(${PLUGIN_NAME} PROPERTIES
  VS_PROJECT_IMPORT ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.props
)

target_link_libraries(${PLUGIN_NAME} PRIVATE ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets)
```

**Comment by dirkarnez** [comment]
> I'm developing Flutter for Windows. Hope the snippet help
> 
> https://github.com/woodemi/quick_blue/pull/10/files
> 
> ```cmake
> set_target_properties(${PLUGIN_NAME} PROPERTIES
>   VS_PROJECT_IMPORT ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.props
> )
> 
> target_link_libraries(${PLUGIN_NAME} PRIVATE ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets)
> ```

This works! Thank you so much!
