### ISSUE TITLE
Mark `winrt::resume_foreground` and `co_await <dispatcher>;` with `[[deprecated]]`

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#1244]
Now that the recommended way to move to the foreground is through the wil library, we should mark these functions as deprecated, and point users to wil. Eventually, one might consider removing them entirely. Related to #1123 

Sidenote: should we do the same to apartment_context too? I heard from somewhere that it was pretty slow and usage of the dispatchers is preferred nowadays.

**Comment by JaiganeshKumaran** [comment]
I shouldn't need to install a whole other library for basic stuff. Windows App SDK should've provided co_await support by itself.

**Comment by sylveon** [comment]
You can always manually call TryEnqueue.

**Comment by kennykerr** [comment]
While there are good alternatives, I'm not sure its practical to deprecate these as there is a lot of existing code that uses them, and that code isn't necessarily wrong, and this would force all of that code to be rewritten or pick up a new dependency. I had hoped to remove these for a future v3 but that seems unlikely to happen any time soon.

**Comment by sylveon** [comment]
The deprecated attribute just generates a compiler warning that can easily be ignored (or we could add a macro to disable the warning), and we can add a text blurb to the warning pointing to WIL. It also helps migration because there is an evident warning on all call sites. Code doesn't need to be rewritten until we actually remove it (if ever).

I still support porting the wil changes to cppwinrt and make supported extension points for WinUI 3 to hook into (no explicit support of WinUI 3 is required from our side). That way, we wouldn't have to remove it, require rewrites, or require adding a new dependency.

**Comment by kennykerr** [comment]
Unfortunately, some of our internal builds turns warnings into errors and projects have no control over suppressing them. Primarily, this is how Windows is built and largely why we don't use the deprecated attribute for any code destined for the OS.

**Comment by sylveon** [comment]
Couldn't they do, say,
```cpp
#define WINRT_SILENCE_DEPRECATED_RESUME_FOREGROUND
#include "winrt/base.h"
```

**Comment by kennykerr** [comment]
Sure, but we have a rather enormous code base and it would have to be done for every project which is not practical. The idea of deprecating APIs has just never taken off for this reason. WinRT APIs actually include metadata indicating APIs that are deprecated but it's completely ignored for the same reason.

**Comment by sylveon** [comment]
Understandable. This sounds like a not starter for now, would probably happen only if cppwinrt v3 ever realizes.
