### ISSUE TITLE
trying to access the buffer with raw pointer 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#125]
I'm accessing IBuffer data with a raw pointer. But getting exception: (previous build was good.)  

![image](https://cloud.githubusercontent.com/assets/6119906/23570363/dca66354-0031-11e7-84a2-333317c07221.png)

![image](https://cloud.githubusercontent.com/assets/6119906/23570341/c2d2fa82-0031-11e7-86b6-5e8f13311e6c.png)

**Comment by kennykerr** [comment]
Wrap the statement that is throwing an exception in a try block and catch as winrt::hresult_error. You'll then have both an HRESULT and a description to help you diagnose the problem.

**Comment by KevinWelton** [comment]
I'm able to build the sample and run it OK in VS 2015 and 2017 RC. Are you doing _anything_ special, like using CMake or another custom change? When you crash under the debugger in VS you should get an alert that will let you break and view the call stack. Then you can go to the IBuffer.exe!winrt::impl::throw_hresult(const HRESULT result) and see what the passed HRESULT was.

**Comment by bigdimboom** [comment]
whenever I'm doing write operations on the pointer, it pops "E_FAIL" exceptions. Can I use memcpy on the pointer? I create an instance of Buffer object in a IAsyncOp function. I'm assuming it is thread safe. Do I need lock the buffer? How do I do memory pooling for AsyncActions(operations) correctly?

**Comment by bigdimboom** [comment]
O.K. it turns out, it is not a bug in winrt. it is a bug in an external library. I just recently updated both libraries.
