### ISSUE TITLE
How to build with Build Tools (not full VS)? 

### ISSUE THREAD

**Issue by sztomi** [microsoft/cppwinrt#1254]
We are trying to build a cppwinrt DLL in a CI environment. This project builds cleanly in a local dev environment where a full VS2019 is installed. On the CI, we are using Built Tools but it looks like something is missing:

Error wrapped/shortened for readability:

```
"Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded 
  from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll. 

Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll' or one of its dependencies. The system cannot find the file specified. 

Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies 
are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 
```

<details>
  <summary>Original error</summary>
<pre>
E:\jenkins\conan_build\1863783680\conan-storage\c10ba9\1\appsdkwrapper-git-7ce5d8b\packages\Microsoft.WindowsAppSDK.1.1.5\build\MrtCore.PriGen.targets(911,5): error MSB4062: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [E:\jenkins\conan_build\1863783680\conan-storage\c10ba9\1\appsdkwrapper-git-7ce5d8b\AppSDKWrapper\AppSDKWrapper.vcxproj]
</pre>
</details>

I could not find documentation on what would install this build task. This is how we are building the solution:

```
nuget.exe restore AppSDKWrapper.sln
msbuild /p:Configuration=Release p:Platform=x64 /p:RestorePackagesConfig=true /t:Restore /t:Build AppSDKWrapper.sln
```

(the various ways of doing the "restore" were added over time as a means to troubleshoot the build, so they are probably a bit excessive - but that shouldn't affect the outcome).

**Comment by sylveon** [comment]
You need the UWP development workload.

**Comment by sztomi** [comment]
.

**Comment by ataparia** [comment]
> ublic clas

I don't see a uwp workload when I run the following command:
dotnet workload list 

Do you happen to know what's the ID for the UWP Development workload?

**Comment by sylveon** [comment]
You install it through the Visual Studio installer, not the .NET CLI. The .NET CLI is for C# only.

For the build tools, this is the workload: https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022#universal-windows-platform-build-tools
