### ISSUE TITLE
Provide to_hstring(IStringable const&) overload

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1258]
Provide an overload of to_hstring for IStringable that simply returns IStringable::ToString. This will unify the stringification of WinRT classes and primitive types. This is also useful for XAML since it's only aware of to_hstring and not IStringable::ToString when using from C++/WinRT.

**Comment by sylveon** [comment]
Where does XAML use to_hstring?

**Comment by JaiganeshKumaran** [comment]
@sylveon When binding to something that's not a string to a string.

**Comment by kennykerr** [comment]
Seems like a reasonable addition.

**Comment by kennykerr** [comment]
Of course, I don't know whether that would actually be used by Xaml without changes to Xaml - you'd have to experiment first to see whether that's effective. The overload of `to_hstring` could also not appear beside the other overloads since it depends on `Windows.Foundation`.

**Comment by sylveon** [comment]
I suppose a lot of XAML wouldn't work without Windows.Foundation anyways :P
