### ISSUE TITLE
Prevent source location in release build

### ISSUE THREAD

**Issue by matbech** [microsoft/cppwinrt#1259]
https://github.com/microsoft/cppwinrt/pull/1185 added source information to the exception using C++20 (#ifdef __cpp_lib_source_location). Now, it may not be desirable to have source file paths strings included in release builds. 

Can a facility be added which allows a user to control whether winrt adds source location to the exception?

Maybe through a new configuration define? e.g.
#define WINRT_NO_SOURCE_LOCATION

**Comment by kennykerr** [comment]
Adding @dmachaj for comment.

**Comment by dmachaj** [comment]
That is a reasonable request and would _probably_ not be difficult to add.

Out of curiosity what is your reason for wanting to suppress this information?  Are you concerned about binary size?  Or leaking source code information publicly?  Or some other reason entirely?  That doesn't change the reasonableness of the request but I am curious.

Also, do you have any thoughts on debug vs. release for including this information?  Would you still want debug builds to include this?

**Comment by sylveon** [comment]
I still want this information in my release builds, so automatically disabling them in release should be avoided

**Comment by matbech** [comment]
@dmachaj Primary for privacy reasons (the source tree structure shouldn't be public). In addition, it might also be interesting for reproducible builds.

**Comment by sylveon** [comment]
In regards to reproducible builds, /d1trimfile also affects std::source_location

**Comment by dmachaj** [comment]
`/d1trimfile` is probably worth looking into regardless, if you want reproducible builds.  It will strip out the parts of the path prior to the root of your repo so it is consistent regardless of the directory structure above it.
