### ISSUE TITLE
Option to include SPDX license tags in generated headers

### ISSUE THREAD

**Issue by alvinhochun** [microsoft/cppwinrt#1261]
I would like to have an option to include SPDX license tags in the headers. It would be similar to using the `-license` option which currently adds this:
https://github.com/microsoft/cppwinrt/blob/fe304096fa30583f3cc2ebfdbf564d2b4081e2ad/cppwinrt/code_writers.h#L25-L30

But I would like to include lines similar to the following:

```c++
// SPDX-FileCopyrightText: Copyright (c) Microsoft Corporation
// SPDX-License-Identifier: MIT
```

* Can the license header added by `-license` be changed? (I'm guessing no because this seems to be intended to be used by Microsoft internally when generating the headers for the Windows SDK.)
* If not, will you accept adding a new option for this variation?
    * What should the option be called?

**Comment by kennykerr** [comment]
I'm ok with adding an option to insert an alternative preamble from a text file rather than making it specific to some licensing scheme. So `cppwinrt` and `cppwinrt -license` stay as they are but if you say `cppwinrt -license text.txt` then it uses that text instead of the default here: 

https://github.com/microsoft/cppwinrt/blob/fe304096fa30583f3cc2ebfdbf564d2b4081e2ad/cppwinrt/code_writers.h#L21-L38

**Comment by sylveon** [comment]
I know some people have raised questions about the licensing of the generated headers before. Perhaps it wouldn't be a terrible idea to generate SPDX comments by default, and have -license revert to the SDK style comments. That way the licensing on the generated code is clear.

**Comment by kennykerr** [comment]
We can't change the default behavior without breaking existing customers.

**Comment by sylveon** [comment]
Are comments behavior changes?

**Comment by kennykerr** [comment]
Yes, we run cppwinrt as part of the Windows build to generate the Windows SDK and changes to comments are thus changes to published material. So by behavior here I mean the behavior of the tool changes, not just that the behavior of compiled code changes.
