### ISSUE TITLE
headers disappear 

### ISSUE THREAD

**Issue by wsfrancis71** [microsoft/cppwinrt#1263]
After doing a few builds all my (example <winrt/Microsoft.UI.Composition.h> ) headers report a "E1696 cannot open source file" error. I have updated the nuget "Microsoft.Windows.CppWinRT" to ver 2.0.221121.5 and the issue still persist. Is there a bug and whats the fix?

**Comment by kennykerr** [comment]
This is beyond the scope of cppwinrt - I'd suggest providing a minimal repro here:

https://developercommunity.visualstudio.com/cpp
