### ISSUE TITLE
How to build with Build Tools (not full VS) (redux)?

### ISSUE THREAD

**Issue by sztomi** [microsoft/cppwinrt#1264]
Since my [previous issue](https://github.com/microsoft/cppwinrt/issues/1254) got closed before I got a chance to reply, I'm continuing here (I'm not sure if closed issues are monitored, usually they aren't). The answer I got was that I need "the UWP development workload", but I don't know which component that corresponds to here: https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#visual-c-build-tools

I tried:

  * `Microsoft.VisualStudio.ComponentGroup.UWP.BuildTools`
  * `Microsoft.VisualStudio.ComponentGroup.UWP.VC.BuildTools`

But these don't work. I couldn't find any other component that resembles what I seem to need. I did find that there are choco packages that match the search "UWP development workload" but these require a full Visual Studio installation (i.e. not Build Tools). Do I actually need a full Visual Studio to be able to build cppwinrt projects?

**Comment by sylveon** [comment]
Wouldn't it be this? https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#universal-windows-platform-build-tools

**Comment by sztomi** [comment]
@sylveon so the entire `Microsoft.VisualStudio.Workload.UniversalBuildTools`? That seemed a little excessive but I installed it anyway. No change after a reboot.

**Comment by kennykerr** [comment]
This repo's issues page is for reporting bugs with the cppwinrt compiler. For general questions about how to use Visual Studio or C++/WinRT you're better off asking your question on https://stackoverflow.com/ or https://developercommunity.visualstudio.com/cpp.

**Comment by sztomi** [comment]
@kennykerr Is this really coming off as a general question about _how to use Visual Studio_? I'm trying to build a cppwinrt application in a CI environment. I'm not a native English speaker, but I'm really surprised if my question can be mistaken for that.

**Comment by kennykerr** [comment]
My point is simply that there are better forums where your question will reach a much greater audience of developers that can help you with the issue you've encountered. This is not such a forum. I'm largely the only developer from Microsoft who keeps an eye on this repo, and I don't know have much experience with C++ build systems. 🤷‍♂️

**Comment by sztomi** [comment]
I'm a bit confused why "how to use the thing" is an odd question for the "repo of the thing" and indeed, this is not also not a general question about C++ build systems. There is only one supported build system (msbuild) for using cppwinrt apparently and I would have hoped that the one officially sanctioned way of building is a bit better documented.
