### ISSUE TITLE
Build Metadata option for C++/WinRT projects

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1266]
Since C++/WinRT requires the use of IDL for authoring Windows Runtime types, changes in metadata are not immediately visible to C++ and XAML until the projection headers are updated, which happens after compiling IDL to WinMD and before compiling C++ source. 

I'm finding it quite difficult to implement Windows Runtime types with this workflow because C++ and XAML IntelliSense only recognise the new changes in the component when the projection headers are updated. To make sure IntelliSense works, I start building the project every time after changing IDL and cancel it after WinMD is generated and C++ compilation just starts. Please consider providing an option to just build metadata and generate projection header, without building the entire project, through the C++/WinRT Visual Studio extension.

**Comment by kennykerr** [comment]
This repo is for reporting issues (bugs) with the cppwinrt.exe compiler/library. For API or IDE questions please see the options here: https://github.com/microsoft/cppwinrt/issues/new/choose

**Comment by JaiganeshKumaran** [comment]
There doesn't seem to be an option for feature requests.

**Comment by kennykerr** [comment]
I'm not sure - if it's mostly about Xaml I'd go with Windows API question. If it's mostly about Visual Studio I'd go with Visual Studio question.

**Comment by asklar** [comment]
I think the feature being requested is to add a "Update project metadata" to the CppWinRT VSIX, that calls the build to perform only a couple of things not a full build.
Would feature requests to the VSIX not go into this repo @kennykerr ?

**Comment by kennykerr** [comment]
> Would feature requests to the VSIX not go into this repo

Not if you want someone to work on that feature. 😊 The VS extension is now part of Visual Studio and exists almost entirely in support of Xaml. For historical reasons, some of that code resides here but the teams responsible for it (e.g. Visual Studio and Xaml) don't take feature requests through this repo.

**Comment by asklar** [comment]
Perhaps someone (the community?) could fork the VSIX code and publish it, where it can continue to get features.
