### ISSUE TITLE
"February Anniversary Update and Creator's Update refresh" commit broke version numbers in copyright comment 

### ISSUE THREAD

**Issue by jonitis** [Microsoft/cppwinrt#127]
Last commit 57ecfe1537a389b69a9c99ae58149944a87053e3 updated all 10.0.15042.0/winrt/*.h header files to change "v1.0.private" -> "v1.0.170303.6", but it actually changed to "vv1.0.170303.6" (extra "v")

`// C++ for the Windows Runtime v1.0.private`
vs.
`// C++ for the Windows Runtime vv1.0.170303.6`
 
BTW do not forget to update the "Docs" directory documents (mostly "Interoperability Helper Functions.md") to take into account changes mentioned in "Breaking Changes.md"

**Comment by kennykerr** [comment]
Thanks for pointing this out. We'll get this fixed in the next update.

**Comment by BrentRe** [comment]
I've pushed an update to the Interoperability Helper Functions.md document.
