### ISSUE TITLE
as function missing inside implementation type

### ISSUE THREAD

**Issue by jaigak** [microsoft/cppwinrt#1288]
### Summary

The implementation type doesn't have the as function, requiring you to use try_as (no exception) or QueryInterface instead. Please provide an as function for consistency.

### Reproducible example

```rust
struct MainWindow : Microsoft::UI::Xaml::WindowT<MainWindow>
{
    MainWindow()
    {
        as<IWindowNative>(); //Error.
        try_as<IWindowNative>(); // Works.
    }
};
```

**Comment by JaiganeshKumaran** [comment]
@kennykerr

**Comment by kennykerr** [comment]
Same as https://github.com/microsoft/cppwinrt/issues/1289 - this is probably a much smaller change, so I don't have any objections if you wish to contribute but there doesn't appear to be a lot of benefit and `try_as` is more efficient.
