### ISSUE TITLE
concatenation operator for hstring and hstring_view?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#129]
request "+" or "append(...)" for hstring and hstring_view. 
for now, I'm using std::wstring and then covert it to hstring

**Comment by kennykerr** [comment]
Yes, that's on our todo list. `hstring` is immutable, so `a + b` would return a new hstring and there would be no `append` functionality, but general concatenation via `operator +` is obviously very useful. Thanks for the feedback!

**Comment by BrentRe** [comment]
Created a bug to track this request.
