### ISSUE TITLE
ListView Control

### ISSUE THREAD

**Issue by geminik23** [Microsoft/cppwinrt#13]
I tried using ListView Control. But there's a runtime error. Did I something wrong?

this is what I did in C++/CX. and this works.
``` C++

Platform::Collections::Vector<Platform::String^>^ source
	 = ref new Platform::Collections::Vector<Platform::String^>();
source->Append(L"Testing");

ListView^ view = ref new ListView();
view->ItemsSource = source;

this->Content = view;
```` 

but this code doesn't work.
``` C++

ListView listview;
Collections::IVector<hstring> source({ L"Testing" });
listview.ItemsSource(source);

...

window.Content(listview);

```

**Comment by kennykerr** [comment]
The C++/WinRT collections have some missing capabilities, but the following workaround should get you going:

```C++
IVector<Windows::IInspectable> source{ PropertyValue::CreateString(L"Value") };

ListView view;
view.ItemsSource(source);
```

**Comment by geminik23** [comment]
Okay, it works. Thank you

**Comment by nvictor** [comment]
aww thanks for this @kennykerr been trying to figure this one out for hours this morning!

**Comment by nvictor** [comment]
talked too fast. i am still failing to make this one work.

		IInspectable item1 = PropertyValue::CreateString(L"Item 1");
		IInspectable item2 = PropertyValue::CreateString(L"Item 2");

		IVector<IInspectable> source;
		source.Append(item1); 
		source.Append(item2);

		ListView view;
		view.ItemsSource(source);

		window.Content(view);

i switched to `Append()` because i was getting a list initializer error with the syntax suggested above.

                error C2440: 'initializing': cannot convert from 'initializer list' to 'winrt::Windows::Foundation::Collections::IVector<winrt::Windows::Foundation::IInspectable>'

now `Append()` is failing. i think it's trying to de-reference a null pointer or something.

**Comment by kennykerr** [comment]
The ability create to create an implicit WinRT collection was problematic. You can create an `IVector<T>` implementation for use with `ListView` as follows:

```C++
IVector<IInspectable> items = single_threaded_vector<IInspectable>();
items.Append(PropertyValue::CreateString(L"One"));
items.Append(PropertyValue::CreateString(L"Two"));

ListView view;
view.ItemsSource(items);
```

**Comment by nvictor** [comment]
thank you so much @kennykerr ! it worked like a charm.
