### ISSUE TITLE
Simplify static lifetime implementation

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1300]
When component optimisations are enabled, to have a static lifetime factory and define the static methods in the factory, rather than the implementation type, you need to write static forwarders in the implementation type as shown here: https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/static-lifetime#examples.

Consider making the generated code in g.cpp call into the factory directly if the static_lifetime marker is present instead of calling the static method on the implementation type.

**Comment by kennykerr** [comment]
The relationship between optimizations and static factories is regrettably complex but isn't something we can easily fix without a major overhaul.

**Comment by JaiganeshKumaran** [comment]
Could you provide a generated base class for the implementation type that will automatically call into the factory instead?

**Comment by JaiganeshKumaran** [comment]
Here's a simple solution.
```cpp
namespace winrt::Component
{
    template <int = 0>
    static auto GetObjectHelperStatics()
    {
        if constexpr (winrt::impl::has_static_lifetime_v<factory_implementation::Foo>)
        {
            return winrt::make_self<factory_implementation::Foo>();
        }
        else
        {
            // statics_type will be a new alias on the factory based on FooT's second template parameter.
            return std::add_pointer_t<factory_implementation::Foo::statics_type>{ nullptr };
        }
    }

    void Foo::StaticMethod()
    {
        // Before
        return implementation::Foo::StaticMethod();
        // After.
        return GetObjectHelperStatics()->StaticMethod();
    }
