### ISSUE TITLE
Can not find document for "resume_background" "thread_context"

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#132]
I'm studying "xaml code example". 

Where  are the the documents for "resume_background()" and "thread_context". I've looked everywhere. For now, I'm assuming it's related to the WindowsApp LifeCycle.

**Comment by kennykerr** [comment]
We have not documented these yet. We described them at CppCon:

[Putting Coroutines to Work with the Windows Runtime](https://www.youtube.com/watch?v=v0SjumbIips) ([Slides](https://github.com/CppCon/CppCon2016/raw/master/Presentations/Putting%20Coroutines%20to%20Work%20with%20the%20Windows%20Runtime/Putting%20Coroutines%20to%20Work%20with%20the%20Windows%20Runtime%20-%20Kenny%20Kerr%20and%20James%20McNellis%20-%20CppCon%202016.pdf))

**Comment by bigdimboom** [comment]
"resume_background" is without doubt the coolest concept in concurrent programming. Still, where can I find the documentations for managing the thread pool?

**Comment by BrentRe** [comment]
I created a bug to write documentation detailing our co-routine support.
