### ISSUE TITLE
VS Template: WindowsTargetPlatformMinVersion not set properly when using Console App C++/WinRT Template

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/cppwinrt#1327]
### Summary

When creating the project, you are prompted for target and minimum versions, but only the WindowsTargetPlatformVersion property of the project gets set. You have to manually change the min version. The min version defaults to some other number. 

Excerpt from a project file where I had specified 10.0.20348 for both target and minimum when prompted.

```
<WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0.20348.0</WindowsTargetPlatformVersion>
<WindowsTargetPlatformMinVersion>10.0.17134.0</WindowsTargetPlatformMinVersion>
```

**Comment by kennykerr** [comment]
I've tagged a few project maintainers. If one of them is available to offer guidance and mentorship for this issue, they will reach out according to the [contributing guide](https://github.com/microsoft/cppwinrt/blob/master/docs/contributing.md) to discuss and agree on an approach.

https://github.com/orgs/microsoft/teams/cppwinrt-maintainers
