### ISSUE TITLE
Weird compiler behaviour with C++/WinRT and modules

### ISSUE THREAD

**Issue by yottaawesome** [microsoft/cppwinrt#1328]
### Version

v2.0.220110.5

### Summary

Firstly, apologies for this one, as it's a bit of an unusual case that I discovered when I was using C++/WinRT in modules at work. I'm aware that C++/WinRT doesn't support modules yet, but this is a bit different, and I suspect the problem is with MSVC rather than C++/WinRT.

Consider the sample code. It's an executable with a simple module that exports a class that has a C++/WinRT type as a private member and also has a user-provided empty default constructor defined in the class. This requires the `/std:c++latest` compiler setting (you can find a download link of a vcxproj further below if necessary).

When I attempt to compile this code in Visual Studio 17.6.4, it fails with `error C2676: binary '==': 'const winrt::guid' does not define this operator or a conversion to a type acceptable to the predefined operator`. _However_, if I move the user-supplied constructor to be defined out of class, the error goes away and the code compiles fine.

I strongly suspect this is an MSVC bug -- where the constructor is defined should not matter. Is this your impression as well?

I have [reported it to Microsoft](https://developercommunity.visualstudio.com/t/Strange-compiler-behavior-when-using-C/10404101) (you can download the repro project from there), but they closed it as "not a bug" with the explanation that a C++/WinRT template must be exported from the module. This explanation doesn't make sense given that I can get the code to compile fine by simply messing with the constructors with no template export required. If it was due to a template export, then I expect the sample to fail to compile regardless of where the constructor is defined.

Anyway, I wanted to get some confirmation that I'm not missing something or going mad.

Thanks,
Vasilios

### Reproducible example

```cpp
// main.cpp
import somemodule;

int main()
{
    SomeNamespace::SomeClass obj;
    return 0;
}


// somemodule.ixx
module;

#include <winrt/windows.foundation.h>
#include <winrt/windows.foundation.collections.h>
#include <winrt/windows.data.json.h>

export module somemodule;

export namespace SomeNamespace
{
	class SomeClass
	{
		public:
			SomeClass() {} // Comment this out to fix the issue
			//SomeClass(); // Uncomment this to fix the issue

		private:
			winrt::Windows::Data::Json::JsonObject m_root;
	};
	//SomeClass::SomeClass() {} // Uncomment this to fix the issue
}
```

### Expected behavior

Compilation should succeed or fail regardless of where the class' user-supplied default constructor is defined when using C++/WinRT in the sample code.

### Actual behavior

Where the class' user-supplied default constructor is defined affects whether compilation succeeds or fails when using C++/WinRT in the sample code.

**Comment by kennykerr** [comment]
This would be a question for the Visual C++ team. I suggest you bring this up here:

https://developercommunity.visualstudio.com/cpp

**Comment by rtanabe999** [comment]
winrt::Windows::Data::Json::JsonObject m_root;

to

winrt::Windows::Data::Json::JsonObject m_root = nullptr;

**Comment by sylveon** [comment]
This is a pretty clear cut compiler bug - nothing cppwinrt can directly do to fix. It would be ideal if you could do a minimum repro without cppwinrt to submit to DevCom.

**Comment by YexuanXiao** [comment]
Hello everyone, I've added C++ module support to C++/WinRT and written a blog post about my journey. With my fork, you can reference the modules you need on demand, just like in C#. I've published it on NuGet with the ID YexuanXiao.CppWinRTPlus. The repository link is https://github.com/YexuanXiao/cppwinrtplus, and the blog post is at https://github.com/YexuanXiao/cppwinrtplus/blob/master/about_module.md. The project is currently in the experimental stage, and I hope you'll enjoy it. Welcome any bug reports, feature suggestions, and other feedback.
