### ISSUE TITLE
dynamic cast from a winrt object to another

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#133]
![image](https://cloud.githubusercontent.com/assets/6119906/23809608/4c04886a-059c-11e7-9d3e-8e273ffe859c.png)

Above code shows dynamic casting from one type to another in c++/cx style from the c++/cx camera example.  How do I do dynamic cast in c++/winrt?

**Comment by kennykerr** [comment]
The `as` and `try_as` methods can be used for this. In WinRT and COM, a "dynamic cast" is really just a call to `QueryInterface`. The `as` the `try_as` methods encapsulate that functionality. The `as` method will throw an exception on failure, while the `try_as` method will return an object initialized with a `nullptr`. 

```C++
IAsyncInfo base = ...

if (IAsyncAction derived = base.try_as<IAsyncAction>())
{
    // succeeded ...
}

try
{
    IAsyncAction derived = base.as<IAsyncAction>();
    // succeeded ...
}
catch (hresult_no_interface const &)
{
    // failed ...
}
```

**Comment by bigdimboom** [comment]
I tried about using "as" and "try_as" for casting, but it gives me error when I use them.
