### ISSUE TITLE
Can non_agile be used in a derived class?

### ISSUE THREAD

**Issue by amtopel** [microsoft/cppwinrt#1332]
I've been trying to create single-threaded classes in C++/WinRT using `non_agile`, and based on some anecdotal testing, it seems that `non_agile` works with classes that don't derive from a base class.  But if a class does derive from a base class, then it doesn't work, and the class is agile.

Is that accurate?

And if so, is there any way to make a derived class `non_agile`?

Thanks for any assistance.

**Comment by sylveon** [comment]
Can you share some code?

**Comment by kennykerr** [comment]
`non_agile` just instructs the `implements` class template not to implement the `IAgileObject` and `IMarshal` interfaces by default but does not have any control over whether the composed base type does so.

**Comment by amtopel** [comment]
Thanks for your response.  Would it be possible for `implements::query_interface` to check `IAgileObject` and `IMarshal` first, and then to proceed with the rest of `query_interface` after that?

So for example, if the interface being queried is `IAgileObject`, and the derived class is declared as `non_agile`, then return `hresult_no_interface`.  Otherwise, carry on.

It seems like this would be ideal, so that a derived class doesn't inherit agility when it doesn't want to.

**Comment by amtopel** [comment]
So how does one go about creating a single-threaded component that derives from something else?

Could you at least add an extension point, like an overridable `query_interface_begin` or something, that provides an opportunity to return `hresult_no_interface` before anything else?  Note that ATL has stuff like `COM_INTERFACE_ENTRY_NOINTERFACE` and `COM_INTERFACE_ENTRY_FUNC`.

**Comment by kennykerr** [comment]
You may want to stick with ATL. 😊

Note that agility and thread-safety are not the same thing and the composition support in C++/WinRT is only there to support Xaml where you really can't mess with the agility or concurrency of the base type.

**Comment by amtopel** [comment]
I think you're onto a good slogan:

C++/WinRT: "You may want to stick with ATL."

**Comment by amtopel** [comment]
I figured out how to do it.  You declare the class `non_agile`, and then you do this:

int32_t query_interface_tearoff(guid const& id, void**)
        const noexcept override
  {
       return (id == guid_of<::IMarshal>()) ? E_FAIL : E_NOINTERFACE;
  }
