### ISSUE TITLE
Bug: winrt.ixx is overwriten and contains only Windows Runtime APIs

### ISSUE THREAD

**Issue by sotanakamura** [microsoft/cppwinrt#1336]
### Version

2.0.230706.1

### Summary

In a WinUI 3 project, cppwinrt generates the projection for Windows Runtime APIs and Windows App SDK APIs. However, winrt.ixx contains only Windows Runtime APIs. This is the problem of Visual Studio build process. cppwinrt can generate winrt.ixx properly in command line.

### Reproducible example

1. Create a WinUI 3 project and build it.
2. Open winrt.ixx and you can see it dosen't contain "Microsoft.\*.h".

### Expected behavior

winrt.ixx should contain "Microsoft.\*.h".

### Actual behavior

winrt.ixx contains only "Windows.\*.h".

### Additional comments

Additional information by @DarranRowe https://github.com/microsoft/WindowsAppSDK/issues/3767#issuecomment-1653807149

**Comment by kennykerr** [comment]
That file was for testing C++ module support, which has been blocked on compiler bugs for years, so you can just ignore it.

**Comment by sylveon** [comment]
I'm not sure if winrt.ixx works right now, last I tried I was getting weird runtime crashes. I had #953 (which adds proper modules support), but it is blocked by compiler bugs. It doesn't fix your issue, but I was aware of it when working on it. IIRC it would require some changes to the MSBuild machinery (which would be the last item on the checklist for modules support, but we're blocked on earlier than that).

**Comment by sotanakamura** [comment]
This is an additional information. cppwinrt.exe with the combination of input and reference options dosen't generate winrt.ixx. So, winrt.ixx is not overwrriten, but Windows App SDK APIs are not added in winrt.ixx during the step 2, CppWinRTMakeReferenceProjection.

**Comment by YexuanXiao** [comment]
Hello everyone, I've added C++ module support to C++/WinRT and written a blog post about my journey. With my fork, you can reference the modules you need on demand, just like in C#. I've published it on NuGet with the ID YexuanXiao.CppWinRTPlus. The repository link is https://github.com/YexuanXiao/cppwinrtplus, and the blog post is at https://github.com/YexuanXiao/cppwinrtplus/blob/master/about_module.md. The project is currently in the experimental stage, and I hope you'll enjoy it. Welcome any bug reports, feature suggestions, and other feedback.
