### ISSUE TITLE
Serialize/Deserialize using StorageFolder & StorageFile

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#134]
Me serialize method commences with:
StorageFolder _storageFolder = nullptr;
auto _turboCalc = co_await _storageFolder.CreateFolderAsync(L"TurboCalc",      CreationCollisionOption::OpenIfExists);
which throws error: Access Violation Reading Location 0x0...
My guess is that   _storageFolder should be initialized with something like this c# code:
	 //Get the app's local folder.
	StorageFolder localFolder =
		Windows.Storage.ApplicationData.Current.LocalFolder;

Is there a cppwinrt solution?

**Comment by DefaultRyan** [comment]
Correct, your StorageFolder instance is null, so that crash is expected. The cppwinrt code you want is nearly identical to the C# solution:

StorageFolder localFolder = ApplicationData::Current().LocalFolder()

**Comment by JackDetrick** [comment]
Problem solved. Thanks...
