### ISSUE TITLE
Bug: linux hosted builds fail due to missing WinMD

### ISSUE THREAD

**Issue by jonwis** [microsoft/cppwinrt#1341]
### Summary

#1239 added use of a Windows.WinMD file from the windows-rs repo to help validate conformance of cppwinrt's output. https://github.com/microsoft/windows-rs/pull/2609/files?file-filters%5B%5D=.winmd&show-deleted-files=true&show-viewed-files=false# renamed the file in that repo, causing the existing `curl ...` command in our action to fail.

We should probably have our own copy of the WinMD as test collateral available in this repo.  In an ideal world, we wouldn't rely on Windows.WinMD at all and instead use a local custom metaplatform.winmd, but that's not feasible due to heavy reliance on `Windows.Foundation.*` types, behaviors, and attributes. It is, after all, C++/Win[dows]RT.

**Comment by kennykerr** [comment]
FYI @alvinhochun

**Comment by kennykerr** [comment]
I much prefer smaller discrete yml workflows (hence [this collection](https://github.com/microsoft/windows-rs/tree/master/.github/workflows)) because then you can just disable individual workflows via the GitHub Actions UX.

**Comment by kennykerr** [comment]
I've also had to remove tests that rely on GNU to build in #1348 since their import libs don't include some Windows 8 exports.
