### ISSUE TITLE
Remove old Windows 7 support code

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#1344]
Probably want to consider dropping Windows 7 support some time as well. That could further simplify this stuff a bit.

_Originally posted by @kennykerr in https://github.com/microsoft/cppwinrt/pull/1342#discussion_r1300565346_

**Comment by jonwis** [comment]
Generally this is righteous.  Kind of wish we had better telemetry to see where this is really being used.  I'm concerned that if this flows back into the PSDK copy of cppwinrt it'll break people who were somehow relying on it. https://learn.microsoft.com/en-US/lifecycle/faq/extended-security-updates says that there are Win7 variants supported until 2024.

**Comment by kennykerr** [comment]
Older versions of the C++/WinRT nuget package continue to be the supported way of handling this. This is no different. We don't encourage developers to use the version of C++/WinRT that ships in the Windows SDK since that version is locked to the version that *that* particular version of the OS was built with which is almost always extremely old (currently Jan 2022). In fact, half the time it doesn't even build with current MSVC or Clang compilers. It exists in the Windows SDK for legacy reasons only.
