### ISSUE TITLE
Bug: Truncation casts in array_view/com_array and elsewhere?

### ISSUE THREAD

**Issue by jonwis** [microsoft/cppwinrt#1347]
### Version

2.0.220131.2

### Summary

See #1343 where we noticed a bunch of places that convert from a `size_t` to an ABI-friendly `uint32_t` via `static_cast`. Each instance _probably_ needs to be analyzed and replaced with a `WINRT_ASSERT` or `WINRT_VERIFY` or some form of "checked conversion cast" method.

**Comment by JaiganeshKumaran** [comment]
Seems like both `WINRT_ASSERT` and `WINRT_VERIFY` are only for debug mode. We should probably throw or abort instead, as the size of a collection can vary at run-time.
