### ISSUE TITLE
is there plan of creating stl iterator support for IVectorView

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#135]
In c++/cx version, IVectorView can do ranged for loop? Will C++/winrt support stl iterator too in the future?

**Comment by kennykerr** [comment]
I'm not sure what you mean. This works today.

**Comment by bigdimboom** [comment]
for example:
IVectorView<MediaDevice> deviceList = co_await Device::findAllMediaDeviceAsync();
// I want to be able to do the follwoing: 
for(auto& elem : deviceList)
{
  // todo:
}
// right now, I can only do this:
for(size_t i = 0; i < deviceList.Size(); ++i)
{
   // to do: 
}

**Comment by BrentRe** [comment]
As Kenny mentions, you can do this today:

```
IVectorView deviceList = co_await Device::findAllMediaDeviceAsync();
for(auto& elem : deviceList)
{
    // todo:
}
```

Give it a try. I've used it many times.

**Comment by bigdimboom** [comment]
okay. it does work. Thanks...

However visual studio's intellisense is freaking out.

![image](https://cloud.githubusercontent.com/assets/6119906/23871714/f31a04d8-0801-11e7-9fcc-b2631dc4f214.png)

**Comment by BrentRe** [comment]
There are a number of known issues with Intelliense and the C++/WinRT projection. They are being addressed by the Intelliense team.

**Comment by tim-weis** [comment]
[Range-based for loops](http://en.cppreference.com/w/cpp/language/range-for) expand to a number of expressions, that try to match a class member `begin()` or a free function `begin()`. When using C++/WinRT, the compiler selects the free function template [`begin()`](https://github.com/Microsoft/cppwinrt/blob/master/10.0.15042.0/winrt/base.h#L5294) when constructing a range-based for loop over an `IVectorView`.
