### ISSUE TITLE
Recognise local types for get_activation_factory

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1359]
Currently (try_)get_activation_factory does not work for 'local' types. In some situations it can be useful to get the activation factory for a local type, which currently requires calling into winrt_get_activation_factory manually.

**Comment by sylveon** [comment]
Just use `make_self<winrt::Namespace::factory_implementation::MyClass>()`

**Comment by JaiganeshKumaran** [comment]
> Just use `make_self<winrt::Namespace::factory_implementation::MyClass>()`

No, I need it from a string.
