### ISSUE TITLE
Adding ToString() to IInspectable ?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#136]
C++/CX has the Object class which contains ToString() method. Are you going  add this method to the IInspectable? Similar question, are you going to add the reflection support to the c++/winrt projection?

**Comment by BrentRe** [comment]
No, we will never add anything to `IInspectable`. Interfaces are immutable so `IInspectable` will never change.

The Windows Runtime defines the `IStringable` interface, which has a `ToString` method. Windows Runtime classes that wish to support conversion to a string will state that they implement `IStringable`. If they do so, the C++/WinRT projection of that Windows Runtime class will have the appropriate `ToString` method.

Additionally, there is no way we could arbitrarily add a `ToString` method to any class. We have no knowledge of the implementation of any arbitrary Windows Runtime class. If the class doesn't provide a mechanism to get a string representation of an instance, we have no way to provide one on behalf of the instance.

We will not be adding reflection support to the C++/WinRT projection. Should the Windows Runtime in the future add such Windows Runtime APIs, we will, of course, projection those APIs as we do all current ones.

**Comment by shelllet** [comment]
how to add `IStringable`  to `IMap` and `IVector`   and such these interface?

**Comment by sylveon** [comment]
You cannot. But you can provide your own implementation of IVector/IMap that also implements IStringable. Or you could simply write a helper method that makes a string out of these interfaces, instead of using IStringable.

**Comment by shelllet** [comment]
> You cannot. But you can provide your own implementation of IVector/IMap that also implements IStringable. Or you could simply write a helper method that makes a string out of these interfaces, instead of using IStringable.

thks, how to implement `IVecotr/IMap` ,is there any example?

is this?
`strcut MyVector:  implements<IVector, IStringable>{}` ?

**Comment by sylveon** [comment]
```cpp
struct MyVector : implements<MyVector, IVector<int>, IStringable> {};

**Comment by shelllet** [comment]
ok! thks, this is very usefull.

> ```c++
> struct MyVector : implements<MyVector, IVector<int>, IStringable> {};
> ```

ok! thks, this is very usefull.
