### ISSUE TITLE
std::vformat equivalent for hstring

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1361]
There only seems to be winrt::format; no winrt::vformat to specify a runtime format string.

**Comment by sylveon** [comment]
This is not possible because std::vformatted_size and std::vformat_to_n do not exist.

We would need a dynamically increasing temporary buffer, at which point that would be equivalent to just using std::vformat and converting to winrt::hstring after.

**Comment by sylveon** [comment]
This will be fixed in the future with [`std::runtime_format`](https://en.cppreference.com/w/cpp/utility/format/runtime_format)
