### ISSUE TITLE
winrt::impl::reference::Get(T) functions should cast safely

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1362]
Currently winrt::impl::reference::Get(T) functions simply use a static_cast, which can narrow. This behaviour is inconsistent from the built-in PropertyValue objects returned by various PropertyValue::Create(T) methods, where they throw an exception in case a conversion could not be done.

**Comment by JaiganeshKumaran** [comment]
Another thing, winrt::impl::reference (mainly used for enums), throws hresult_not_implemented for GetSingle and GetDouble, while the built-in ones for integers do not.

**Comment by kennykerr** [comment]
I've tagged a few project maintainers. If one of them is available to offer guidance and mentorship for this issue, they will reach out according to the [contributing guide](https://github.com/microsoft/cppwinrt/blob/master/docs/contributing.md) to discuss and agree on an approach.

@microsoft/cppwinrt-maintainers
