### ISSUE TITLE
stl collections to winrt collections interpolation

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#137]
e.g. is there a way of casting a stl vector to a winrt::IVectorView()
Is a concrete class for winrt::IVectorView in winrt lib?

**Comment by BrentRe** [comment]
No, you cannot cast but don't really need to.

If you want to pass a std::vector to a WinRT method requiring an IVectorView, just do that. For example, if there is a Windows Runtime method such as this:

``` SomeMethod ([in] IVectorView* view);```

It will project in C++/WInRT as:

``` SomeMethod (vector_view const & view);```

And you can call it like so:

```
std::vector myVec = ...
...
obj.SomeMethod (myVec);
```

Alternatively, if you really want an IVectorView, you can construct one over your std:vector:

`winrt::Windows::Foundation::Collections::IVectorView myView (myVec);`

**Comment by xprssn2** [comment]
I need to implement a function that returns an `IVectorView`, what is the official way to do it?
```cpp
Windows::Foundation::Collections::IVectorView<Windows::Foundation::Point> BezierFunction::GetQuadraticBezierPoints()
{
    std::vector<Windows::Foundation::Point> points;
    // ...
    return ???;
}
```

**Comment by kennykerr** [comment]
C++/WinRT currently provides two general purpose collections. The `single_threaded_vector` function creates an `IVector<T>` and the `single_threaded_map` function creates an `IMap<K, V>`. You can use `IVector<T>`'s `GetView` method to create an `IVectorView<T>`. For example:

```C++
std::vector<Point> points;

// Populate points...

return single_threaded_vector(std::move(points)).GetView();
```
