### ISSUE TITLE
no interface support?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#138]
![image](https://cloud.githubusercontent.com/assets/6119906/23876183/8b04c6f6-0812-11e7-9297-34a446e3e32d.png)

I'm calling a new camera control interface from winrt/c++. however,

![image](https://cloud.githubusercontent.com/assets/6119906/23876202/ad62c324-0812-11e7-8619-87be5089d4cc.png)

**Comment by bigdimboom** [comment]
need windows 10 v10.0.15042 to support.....

**Comment by BrentRe** [comment]
This is not a C++/WinRT problem. The object you are trying to use does not support the requested interface. That's what the hresult_no_interface exception states. And you're code is not detecting whether the interface is supported and conditionally using it only when it is.

Possibly you are not running on the latest version of Windows 10 that matches the 15042 SDK.
