### ISSUE TITLE
does c++/winrt support openmp? or is there a similar mechanism in c++/winrt?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#139]
for example, in openmp we can do this:
std::vector<CONCURRENT_OBJ> objs(size, initFunc(....))
for(auto i = 0; i < obj.size();++i)
{
   do_something_in_parallel(objs[i]);
}

BTW, I do know how to save the IAsync token and retrieve the result later.

**Comment by kennykerr** [comment]
OpenMP is an unrelated technology supported by the Visual C++ compiler. We neither support nor prevent you from using it with C++/WinRT.
