### ISSUE TITLE
Expose wrapped APIs to open Win32 handles for WinRT storage items

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/cppwinrt#1394]
The [WindowsStorageCOM.h](https://learn.microsoft.com/en-us/windows/win32/api/windowsstoragecom/) file defines interop interfaces for Windows::Storage.* types, but ironically it seems to be unusable under the UWP due to incorrect #ifdef-ing.

Could C++/WinRT expose wrappers for these? C++/WinRT already has an RAII type for file handles: [winrt::file_handle](https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/file-handle), so no need to put it in WIL.

**Comment by sylveon** [comment]
This feels like a wrapper that would work best in WIL.
