### ISSUE TITLE
GetChildrenInTabFocusOrder no longer a member of the generated code

### ISSUE THREAD

**Issue by martgoodall** [microsoft/cppwinrt#1395]
### Version

2.0.240111.5

### Summary

after upgrading from 2.0.230706.1 to 2.0.240111.5 , GetChildrenInTabFocusOrder() is no longer a member of the generated code, so the winappsdk/winrt c++  app no longer compiles the exe.

[WinUI.zip](https://github.com/microsoft/cppwinrt/files/14530434/WinUI.zip)

### Reproducible example

```cpp
pre upgrade, the following would compile - see attachment for complete source containing the following code:-

c++
   StackPanel stackPanelItems = containerContentChangingEventArgs.ItemContainer().ContentTemplateRoot().as<StackPanel>();
   auto autoItems = stackPanelItems.GetChildrenInTabFocusOrder();

GetChildrenInTabFocusOrder is not generated as a member of the class.
```

### Expected behavior

to still compile existing code under the new release

### Actual behavior

GetChildrenInTabFocusOrder is not generated as a member of the class.

### Additional comments

app is built successfully with the following:-

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Graphics.Win2D" version="1.1.1" targetFramework="native" />
  <package id="Microsoft.Windows.CppWinRT" version="2.0.230706.1" targetFramework="native" />
  <package id="Microsoft.Windows.ImplementationLibrary" version="1.0.240122.1" targetFramework="native" />
  <package id="Microsoft.Windows.SDK.BuildTools" version="10.0.22621.3233" targetFramework="native" />
  <package id="Microsoft.WindowsAppSDK" version="1.5.240227000" targetFramework="native" />
</packages>

app fails to build by upgrading
Microsoft.Windows.CppWinRT

**Comment by dmachaj** [comment]
@sylveon this appears to be another question related to #1319.

If I understand the description of that PR it should be considered invalid for something outside the StackPanel implementation to call GetChildrenInTabFocusOrder.

**Comment by sylveon** [comment]
It's an [overridable method on UIElement](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.getchildrenintabfocusorder?view=winrt-22621), which means it is protected. So yeah, the proper way would be to inherit from StackPanel to use it, like one would in C#. Alternatively as a workaround, using `sp.as<IUIElementOverridable>().GetChildrenInTabFocusOrder()` should work.

**Comment by martgoodall** [comment]
I really appreciate the feedback.
I was able to get it to compile under 1.5.0 with the following change:-

auto autoItems = stackPanelItems.as<IUIElementOverrides>().GetChildrenInTabFocusOrder();
(which is almost what you suggested but IUIElementOverrides instead of IUIElementOverridable).

using winrt c++/windowsappsdk/Xaml, I'm really not sure how to implement the other suggestion of "inherited StackPanel in a similar fashion to the C#".....if anyone had a code sample doing similar, it would be very appreciated, since there are so few decent  winrt c++/windowsappsdk/Xaml examples on the web.

again many thanks for the feedback.

**Comment by sylveon** [comment]
It is not very obvious, but the way to do this is to:
- Create a blank page from VS (right-click the project in the Solution Explorer > Add > New Item... > Blank Page (WinUI 3))
- Open the IDL, change `Microsoft.UI.Xaml.Controls.Page` to `Microsoft.UI.Xaml.Controls.StackPanel`
- Open the XAML, change `<Page` to `<StackPanel` and `</Page>` to `</StackPanel>`
- Put some contents, or if you don't want to add XAML to that class and delegate setting the contents to consumers, you can use the View Model (C++/WinRT) template when creating a new item instead of Blank Page (WinUI 3)
- You should now be able to access `GetChildrenInTabFocusOrder` within the class:
  ![image](https://github.com/microsoft/cppwinrt/assets/6440374/95d73018-2bdd-4c06-8d37-0c41ef4bb4d7)

**Comment by torleifat** [comment]
So I stumbled across this issue just recently. However I also discovered another issue which I think is related, and even if it is, it might be outside the scope of cppwinrt to fix(if it should be fixed at all).

Attempting to call an overridable function from a derived class in Xaml

Say you have an IDL like this: 

```
    [default_interface]
    unsealed runtimeclass A
    {
        A();

        overridable void MyFancyFunction();
    }

    [default_interface]
    runtimeclass B : A
    {
        B();
    }

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        B Model{ get; };
    }
```

And in your MainWindow  xaml you call on MyFancyFunction, something like this:

```
<Button x:Name="myButton" Click="{x:Bind Model.MyFancyFunction}">Click Me</Button>
```

In 2.0.230706.1 this will compile and work fine. In 2.0.240111.5 it will lead to a compile-error where it could not find the MyFancyFunction as a member of B. 
If this was in code I could do something like `Model().as<IAOverrides>().MyFancyFunction()`. However seeing as this is done in Xaml it complicates matters. (Note that there's ways around this, by adding MyFancyFunction to the B's IDL, and not adding any actual override in the implementation it'll successfully call A's MyFancyFunction.)

Now there's a chance that there are good reasons why this should not be allowed to begin with. I am not very well versed in MIDL 3.0 or C++/Winrt, but I am wondering if this intended. For me it does seem a little counter-intuitive that this should not work.

**Comment by sylveon** [comment]
This is indeed intended. To quote the [WinRT type system](https://learn.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system#overridable-interfaces):

> A composable class may declare zero or more of its member interfaces to be overridable. An overridable interface may only be queried for, and used within, a composition chain—similar to the rules about accessing protected interfaces detailed previously. However, where a protected interface may only be implemented by the class that originally declared it, overridable interfaces may be re-implemented by classes that compose the class that implemented the overridable interface.

**Comment by martgoodall** [comment]
Thanks for the suggestion.

I believe the new attachment is what you suggested and appears to work but could you please confirm it looks right to you as this stuff is all new to me and it seems to me to be a strange change to now protect GetChildrenInTabFocusOrder forcing a custom method requirement for basic functionality.

[WinUI.zip](https://github.com/microsoft/cppwinrt/files/14565283/WinUI.zip)

Xaml reads as follows (<StackPanel> changed to <local:StackPanelViewModel>) :-

============================

     <local:StackPanelViewModel 
                 x:Name="StackPanelQueue"
                 AllowDrop="True"
                 DragOver="GridViewQueues_DragOver"
                 Drop="GridViewQueues_Drop"
                 Width="200"
                 Height="220">

========================

the c++ file reads as follows :-

// old code
//   StackPanel stackPanelItems = containerContentChangingEventArgs.ItemContainer().ContentTemplateRoot().as<StackPanel>();
//
// old code
//   for (auto autoStackPanelItem : stackPanelItems.as<IUIElementOverrides>().GetChildrenInTabFocusOrder())
//   {
 //  }


// new code
   auto autoStackPanelViewModel = containerContentChangingEventArgs.ItemContainer().ContentTemplateRoot().try_as<StackPanelViewModel>();
   if (autoStackPanelViewModel == nullptr)
      co_return;

   for (auto autoStackPanelItem : autoStackPanelViewModel.get()->ViewModelGetChildrenInTabFocusOrder())
   {
   }

===================

thanks
Mart


> It is not very obvious, but the way to do this is to:
> 
> * Create a blank page from VS (right-click the project in the Solution Explorer > Add > New Item... > Blank Page (WinUI 3))
> * Open the IDL, change `Microsoft.UI.Xaml.Controls.Page` to `Microsoft.UI.Xaml.Controls.StackPanel`
> * Open the XAML, change `<Page` to `<StackPanel` and `</Page>` to `</StackPanel>`
> * Put some contents, or if you don't want to add XAML to that class and delegate setting the contents to consumers, you can use the View Model (C++/WinRT) template when creating a new item instead of Blank Page (WinUI 3)
> * You should now be able to access `GetChildrenInTabFocusOrder` within the class:
>   ![image](https://private-user-images.githubusercontent.com/6440374/311409186-95d73018-2bdd-4c06-8d37-0c41ef4bb4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTc3ODksIm5iZiI6MTcxMDE5NzQ4OSwicGF0aCI6Ii82NDQwMzc0LzMxMTQwOTE4Ni05NWQ3MzAxOC0yYmRkLTRjMDYtOGQzNy0wYzQxZWY0YmI0ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMjI1MTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDlkMTRiNDU2MjU1MTFlMmQxNDgzOGVkNGRmNTU4ZDlmZTA1ZTcyNzM2ZDI0OTVhYzdkNzk5MDdiOWVmNzZhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mOZkrtaWfUnNNsbzMYu7XUA_alDHzVuBLDxs_FPtV1I)

**Comment by sylveon** [comment]
Seems fine to me - FWIW `GetChildrenInTabFocusOrder` has always been `protected virtual` in C#.

**Comment by DefaultRyan** [comment]
> 
> Say you have an IDL like this:
> 
> ```
>     [default_interface]
>     unsealed runtimeclass A
>     {
>         A();
> 
>         overridable void MyFancyFunction();
>     }
> 
>     [default_interface]
>     runtimeclass B : A
>     {
>         B();
>     }
> 
>     [default_interface]
>     runtimeclass MainWindow : Microsoft.UI.Xaml.Window
>     {
>         MainWindow();
> 
>         B Model{ get; };
>     }
> ```
> 
> And in your MainWindow xaml you call on MyFancyFunction, something like this:
> 
> ```
> <Button x:Name="myButton" Click="{x:Bind Model.MyFancyFunction}">Click Me</Button>
> ```
> 
> In 2.0.230706.1 this will compile and work fine. In 2.0.240111.5 it will lead to a compile-error where it could not find the MyFancyFunction as a member of B. If this was in code I could do something like `Model().as<IAOverrides>().MyFancyFunction()`. However seeing as this is done in Xaml it complicates matters. Note that there's ways around this, by adding MyFancyFunction to the B's IDL, and not adding any actual override in the implementation it'll successfully call A's MyFancyFunction. In this specific case we could also just remove the override flag, but in a theoretical case there could be a derived class C, which needs to override MyFancyFunction.
> 
> Now there's a chance that there are good reasons why this should not be allowed to begin with. I am not very well versed in MIDL 3.0 or C++/Winrt, but I am wondering if this intended. For me it does seem a little counter-intuitive that this should not work.

First, I'll note that you don't need `overridable` to customize the _implementation_ within your component. You can do that by making the internal implementation method(s) `virtual`. You only need to mark a method `overridable` if your intent is to give component-external consumers the ability to customize some behavior in a way that is visible to the base type(s) in your [shipped] component, and so you needed some way of making this customizability part of the public-facing interface of your component for consumers to extend later on.

It's common practice (I'd even say "standard practice") to separate _interface_ from _implementation_ by making the _interface_ public and the _implementation_ non-public. When dealing with virtual functions, it's a common idiom (but not universal) to treat the public interface as stable and non-virtual, and to treat the customizeable/virtual behavior as implementation by making it non-public. This pattern can be especially useful when the overridable bit needs to be surrounded by pre- and post- action.

A familiar example of this is XAML's [`Measure`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.measure?view=winrt-22621#windows-ui-xaml-uielement-measure(windows-foundation-size))and [`MeasureOverride`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.measureoverride?view=winrt-22621#windows-ui-xaml-frameworkelement-measureoverride(windows-foundation-size)). `Measure` is non-virtual, while subclasses can customize their behavior by overriding `MeasureOverride`. Only the base `Measure` is callable publicly, and it performs work both before and after calling the overridable `MeasureOverride`.

Coming back to your example, you need to decide if you truly need `overridable` in your IDL for external components to subclass and customize your type. You probably don't, and will be able to remove `overridable` from `MyFancyFunction` in your IDL. If you want custom behavior between `A` and `B`, just make your implementation function `virtual`. While you're at it, it's probably worth checking your design to verify that `B` truly "is-a" `A` - whether it's required that `A` and `B` be so tightly coupled in both _interface_ and _implementation_, or if you'd be better served by separating the two and offloading this common behavior into an interface:
```csharp
interface IFancyFunction
{
  void FancyFunction();
}

[default_interface]
runtimeclass A : IFancyFunction
{
  A();
}

[default_interface]
runtimeclass B : IFancyFunction
{
  B();
}
```

__Finally__, if you truly need `B` to derive from `A`, _and_ you truly need a __component-external overridable__ method. Declare a public non-overridable method in the base that calls the overridable method in subclasses. Here Be Dragons - the actual implementation is non-trivial and easy to get wrong. You've been warned. :)
```csharp
unsealed runtimeclass A
{
  A();

  void FancyFunction();
  overridable void FancyFunctionOverride();
}

[default_interface]
runtimeclass B : A
{
  B();
}
```

(Fun trivia, C++ virtual function behavior can sometimes get non-intuitive in the face of __hiding__ and __overloading__ - https://isocpp.org/wiki/faq/strange-inheritance#protected-virtuals)

**Comment by torleifat** [comment]
Thanks for the insight @DefaultRyan. 
The original code where this came up does indeed not require `overridable `. Since it is not really customer exposed code to begin with, so it was a quick fix, and as you say if needed an override can be handled in the implementation instead.
