### ISSUE TITLE
Bug: version 2.0.240111.5 does not work correctly with XAML

### ISSUE THREAD

**Issue by YexuanXiao** [microsoft/cppwinrt#1397]
### Version

2.0.240111.5

### Summary

After I upgraded the C++/WinRT version, my WinUI3 project failed to build. After switching to the previous version, it built normally.

```shell
1>D:\Projects\PlayerWinRT\src\Player.vcxproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Data, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime.'
1>XamlMetaDataProvider.cpp
```

WindowsAppSDK v1.5.240311000
SDK.BuildTools v10.0.26031-preview

**Comment by sylveon** [comment]
Try cleaning the project before building after upgrading cppwinrt

**Comment by YexuanXiao** [comment]
I found out that https://github.com/microsoft/cppwinrt/pull/1381 is causing my project to break.

Is this result intentional? @Scottj1s

**Comment by kennykerr** [comment]
For Xaml issues please use this repo: https://github.com/microsoft/microsoft-ui-xaml

**Comment by YexuanXiao** [comment]
> For Xaml issues please use this repo: https://github.com/microsoft/microsoft-ui-xaml

I’ve found it’s due to a change in the nuget/Microsoft.Windows.CppWinRT.targets file from #1381, so it’s unrelated to the XAML repository.

**Comment by kennykerr** [comment]
Yes, but that largely serves to support Xaml and the change was made by the same team. I'd love to help but that's your best bet at getting the issue in front of the appropriate developers.

**Comment by Scottj1s** [comment]
@YexuanXiao I'd be glad to take a look at a repro project, if you have one

**Comment by YexuanXiao** [comment]
> @YexuanXiao I'd be glad to take a look at a repro project, if you have one

I have a repository that replicates the problem: https://github.com/yexuanXiao/PlayerWinRT

**Comment by Scottj1s** [comment]
@YexuanXiao thank you for the repro.  A fix has been made to CppWinRT: https://github.com/microsoft/cppwinrt/pull/1404

**Comment by Scottj1s** [comment]
Fix has been published: https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/2.0.240405.15
