### ISSUE TITLE
Compiler support

### ISSUE THREAD

**Issue by ericLemanissier** [Microsoft/cppwinrt#14]
Are there any plan on supporting MinGW or clang ?

**Comment by kennykerr** [comment]
We have successfully used the Clang front end with C++/WinRT, but the Clang compiler that ships with Visual Studio 2015 Update 3 and Preview 5 both have a bug that prevents them from compiling successfully.

**Comment by ssb22** [comment]
and what about MingGW?  (Thanks for answering about Clang)

**Comment by kennykerr** [comment]
I have no experience with that compiler. Feel free to contribute any conformance fixes needed to support additional compilers.

**Comment by ssb22** [comment]
Thanks.  Well so far all I am getting from MinGW is `fatal error: winrt/Windows.Foundation.h: No such file or directory`, and as I can't find any files in this repository called `Windows.Foundation.h` I don't know what `-I` parameters to add to make MinGW find it.  (Is this repository the *whole* of C++/WinRT, or is there more of it which is not MIT-licensed?)

**Comment by kennykerr** [comment]
This repo contains the source code for the `cppwinrt.exe` tool that generates the headers. For example, you can grab a copy of the execute here:

https://www.nuget.org/api/v2/package/Microsoft.Windows.CppWinRT/2.0.200203.5

This is just a zip file containing the executable. And then you can run it as follows to generate headers:

> cppwinrt.exe -in local -verbose

**Comment by ssb22** [comment]
Thanks.  For reference, it seems this requires a real Windows system (which I don't have right now): it tries to read `C:\windows\SysNative\WinMetadata` which isn't there on WINE.

**Comment by kennykerr** [comment]
You just need the winmd files – you can grab them from the Windows SDK or any Windows 10 machine’s WinMetadata folder. The `local` just says go and find the local `WinMetadata` folder but you can point `-in` to any folder that contains the winmd files you would like to target.
