### ISSUE TITLE
document for the new winrt::Windows::Foundation::TimeSpan

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#140]
according to the c++/cx doc online. TimeSpan has one field: duration.
link:
https://docs.microsoft.com/en-us/uwp/api/windows.foundation.timespan

the new winrt::Windows.Foundation:TimeSpan has multiple fields:
min(), max(), count(), zero()

Where do you document TimeSpan? What is the unit for count()

**Comment by KevinWelton** [comment]
winrt::Windows::Foundation::TimeSpan is an alias for std::chrono::duration<int64_t, 100 * std::nano>

This means the count() member will return units in 100ns intervals, which is the documented unit for [Windows::Foundation::TimeSpan](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.TimeSpan).

See [http://en.cppreference.com/w/cpp/chrono/duration](http://en.cppreference.com/w/cpp/chrono/duration) for documentation on the meaning of the various fields in std::chrono::duration.
