### ISSUE TITLE
Building the samples with VS2017

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#141]
Are the samples VS2015 specific? I get problems when VS2017 upgrades working samples.

**Comment by walbourn** [comment]
What problems are you seeing in particular?

**Comment by MRahilly** [comment]
On a PC with no web connection, I am using the 14393 github.com download and an offline download of VS2017 Community Edition. The “Blocks” VS2015 sample project gets upgraded to VS2017 builds fine but gives a blank window at runtime (no blocks!). I am thinking of reverting to VS2015 where everything was fine.

**Comment by johanlindfors** [comment]
I'm sorry to say MRahilly, but the Blocks sample works just fine in my installation of VS2017. Differences though is that I have the Enterprise Edition and I upgraded the sample explicitly from within the Properties dialog.
