### ISSUE TITLE
Bug: Weird c++20 MainWindow.xaml.g.hpp bug

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/cppwinrt#1421]
### Version

2.0.230706.1

### Summary

The Xaml compiler generates code that calls `winrt::Windows::Foundation::IReference<bool>::Value` https://github.com/microsoft/microsoft-ui-xaml/issues/9214.

If you force the instantiation of `winrt::Windows::Foundation::IReference<bool>::Value` there is no problem.

Otherwise, you get the classic `a function that returns 'auto' cannot be used before it is defined` error even though the header is properly included.

Feel free to close it seems like a msvc bug since in only happens on `/std:c++20`, I just though you might want to know.

### Reproducible example

https://github.com/tom-huntington/auto-bool-visibility-conversion-cpp20-regression

```cpp
//MainWindow.xaml.h
#if 1
inline void force_instantiation_of_IRefBoolValue()
{
    &winrt::Windows::Foundation::IReference<bool>::Value;
}
#else
//error C3779 : 'winrt::impl::consume_Windows_Foundation_IReference<winrt::Windows::Foundation::IReference<bool>,T>::Value' : a function that returns 'auto' cannot be used before it is defined
#endif
```

**Comment by kennykerr** [comment]
Thanks, if you think this is a compiler bug your best bet is to report a problem here:

https://developercommunity.visualstudio.com/cpp

For Xaml-related issues you're better off engaging directly with the Xaml team here:

https://github.com/microsoft/microsoft-ui-xaml
