### ISSUE TITLE
Bug: observable_map_base::call_changed is private

### ISSUE THREAD

**Issue by Patschkowski** [microsoft/cppwinrt#1422]
### Version

C++/WinRT v2.0.220110.5

### Summary

Dear all,

`winrt::observable_vector_base::call_changed` is declared protected, while `winrt::observable_map_base::call_changed` is declared private.

Propose to change the latter to the way it is declared in the former.

Kind regard,
Felix

### Expected behavior

`winrt::observable_map_base::call_changed` should be possible to access from a derived class.

### Actual behavior

Cannot access `winrt::observable_map_base::call_changed` from a derived class.

**Comment by kennykerr** [comment]
@dunhor may be able to comment on visibility.

**Comment by dunhor** [comment]
Going based off source history, it looks like `call_changed` has existed since the very first commits; I did not add them. That aside, I don't see any reason why `call_changed` can't be `protected` in both types.

**Comment by kennykerr** [comment]
Ah, I may have written that after all. 😊

**Comment by kennykerr** [comment]
Feel free to offer a contribution.
