### ISSUE TITLE
Bug: C++WinRT does not correctly handles Chinese characters using `Windows.Foundation.Uri`

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/cppwinrt#1424]
### Version

2.0.240405.15

### Summary

I have a uri with Chinese character and query string that needs to be parsed with `Windows.Foundation.Uri`. Using C++WinRT, it always returns me an empty result. But equivalent C# code does returns me expected result.

I have tried changing the file encoding to either `UTF-8` and `UTF-8 BOM`, nothing worked.

### Reproducible example
With C++WinRT, create a C++WinRT console application:
```cpp
    winrt::Windows::Foundation::Uri uri{ LR"(myapp://open?file="C:/我.txt")" };
    winrt::Windows::Foundation::WwwFormUrlDecoder parsed{ uri.Query() };
    for (auto entry : parsed)
    {
        std::wcout << entry.Name().data() << L'\t' << entry.Value().data() << L'\n';
    }
```

With C#, create a UWP project:
```csharp
            var uri = new Uri("myapp://open?file=\"C:/我.txt\"");
            var parsed = new WwwFormUrlDecoder(uri.Query);
            foreach (var entry in parsed)
            {
                Debug.WriteLine(entry);
            }
```

### Expected behavior

C# result is expected:
![image](https://github.com/microsoft/cppwinrt/assets/42881734/cf9ed712-d846-496e-9160-dfcfa9f97d63)

### Actual behavior

C++WinRT result:
![image](https://github.com/microsoft/cppwinrt/assets/42881734/31e315b5-e8dc-4c47-9196-8c7a2023f681)

### Additional comments
[Repro here](https://github.com/HO-COOH/WinUI-Bug/tree/main/10-UriWithChinese)

**Comment by sylveon** [comment]
Are you sure the bug is not with the console output? Check the debugger maybe?

**Comment by HO-COOH** [comment]
> Are you sure the bug is not with the console output? Check the debugger maybe?

The break point inside the `for` loop is not hit. That should be clear enough.

**Comment by kennykerr** [comment]
For API questions I suggest: https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by HO-COOH** [comment]
@kennykerr I don't know, but both examples uses the same `Windows.Foundation.WwwFormUrlDecoder` class which makes me wondering. I will ask there too.

**Comment by DefaultRyan** [comment]
It uses the same `Windows.Foundation.WwwFormUrlDecoder` class, but `System.Uri` is not the same as `Windows.Foundation.Uri`. The doc page for `Windows.Foundation.Uri` calls out some of these potential differences in the Remarks, including potentially relevant statements about percent-encoding non-ASCII characters.

That's as far as I got, but I'm confident that this is where you're seeing behavior differences.
