### ISSUE TITLE
Bug: "Common properties" not showing in VC++ project

### ISSUE THREAD

**Issue by meirumeiru** [microsoft/cppwinrt#1429]
### Version

2.0.240405.15

### Summary

In the property view for the VC++ project, the part "Common properties" is missing when the "ProjectGuid" property of the project contains uppercase letters. Everything works fine if the guid contains only lowercase letters and numbers.

**Comment by dmachaj** [comment]
Can you please include some screenshots or other additional data?  The problem is not clear to me based on the provided information.

**Comment by meirumeiru** [comment]
sure... in the next picture, you can see the properties of a C++ project in Visual Studio after adding the nuget package

![image](https://github.com/user-attachments/assets/a83f0697-f65d-4a99-9f11-0fc72fe20bd1)

on top you see the newly added "Common Properties" Element and right below the always awailable "Configuration Properties"...

in case of having uppercase letters in the ProjectGuid value of the vcxproj file belonging to these properties, my Visual Studio (german version, maybe that makes a difference?) doesn't show the point "Common Properties"

**Comment by dmachaj** [comment]
This sounds like an issue with Visual Studio that is unrelated to cppwinrt.  In that case, I'd recommend filing feedback with Visual Studio directly.  There is a feedback button in the upper right corner of VS next to the close button.
