### ISSUE TITLE
Topic Closed but since recent news maybe open again.

### ISSUE THREAD

**Issue by vixuque** [Microsoft/cppwinrt#143]
modern.exe avaliability.

Hi!
Excuse me for ask again the same.
Visual Studio 2017 comes with enhaced c++ support and with c++/winrt support.
I guest an utility like modern for make tests.
It will be spent more time for modern.exe release ?

Thanks.
This project is fantastic and will give an impactly progress for using c++ easy in Windows.

**Comment by tim-weis** [comment]
Visual Studio 2015 Update 3 is capable of compiling C++/WinRT code. In that regard, the release of Visual Studio 2017 hasn't changed much, and the answer to issue #34 still holds: *cppwinrt.exe* (formerly known as *modern.exe*) will be released in due time.

In fact, *cppwinrt.exe* **must** be released, to make C++/WinRT a complete development environment for the Windows Runtime. Without it, it is not possible (or at least not feasible) to create Windows Runtime Components. Windows Runtime Components are necessary to provide XAML support.

Rest assured, *cppwinrt.exe* will be released, at some point in the future.
