### ISSUE TITLE
XamlCode.exe RPC_E_WRONG_THREAD SHCore.dll thread Mobile Emulator

### ISSUE THREAD

**Issue by VSChawathe** [Microsoft/cppwinrt#144]
I chose mobile emulator to run the XamlCode sample as x86 Debug from VS2017 with cppwinrt installed via nuget and Pictures Library Capability enabled from Package.appxmanifest
It throws RPC_E_WRONG_THREAD error. The thread appears as SHCore.dll

**Comment by bigdimboom** [comment]
Some functionalities must be invoked in ui thread. What is the "Capability" you are using?

**Comment by VSChawathe** [comment]
It's the sample from this repository itself. It does OCR on an image that user selects from the device's Pictures library. "Capabilty" list can be seen by opening the appxmanifest file within VS. The target for running the app, as mentioned above, should be selected as emulator to get the error.

**Comment by bigdimboom** [comment]
some functionalities must be called by the UI thread for security reason.

**Comment by BrentRe** [comment]
XAML components enforce that you call their methods on the UI thread. This isn't really a security issue. It's a correctness enforcement. As UI components execute on a (single) UI thread, a developer doesn't need to make their state safe for multi-threaded access. XAML, therefore, checks on each call that the caller is running on the UI thread.

This isn't particular to C++/WinRT. It's just how XAML has always been implemented.

So, for example, if you've some callback running on an arbitrary thread, and you want to call a UI object's method, you'll need to switch to the UI thread first.
