### ISSUE TITLE
Grid method puzzle?

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#148]
Why does Grid use append() rather than add()? I expected add() looking at C# samples

**Comment by kennykerr** [comment]
It depends on the class, but in general such a difference stems from the fact that the CLR chooses to provide different but equivalent types for WinRT collections, whereas C++/WinRT provides a literal projection of WinRT types as much as is practical. A particular API might use `Windows.Foundation.Collections.IVector<T>` but .NET will replace it with  `System.Collections.Generic.IList<T>` as a convenience to C# developers. `IVector` has an `Append` method while `IList` has an `Add` method.

**Comment by MRahilly** [comment]
Thank you Kenny.
