### ISSUE TITLE
Creating Custom Windows Runtime Component via C++/WinRT

### ISSUE THREAD

**Issue by amtlib-dot-dll** [Microsoft/cppwinrt#152]
I have tried to create and implement a new Windows Runtime Component module without C++/CX or WRL

https://gist.github.com/amtlib-dot-dll/bddac8c5d674b63e5feffe01b549aef5

It is usable but should be more elegant. Looking for your update of WinRT Component support!

**Comment by kennykerr** [comment]
We're working on it!

**Comment by amtlib-dot-dll** [comment]
Thanks 👍

**Comment by wes566** [comment]
@kennykerr you wouldn't happen to have any rough timeline or roadmap, would you?

**Comment by nikobarli** [comment]
One vote for this feature too.

**Comment by BrentRe** [comment]
All we can say for now is that we are working on it.

**Comment by nikobarli** [comment]
Hi @amtlib-dot-dll 

Do you have a complete solution/vcxproj sample for https://gist.github.com/amtlib-dot-dll/bddac8c5d674b63e5feffe01b549aef5 ? I am trying to use it but still cannot get my component activated from another C# project.

**Comment by BrentRe** [comment]
This forum is for C++/WinRT questions. I've no idea what the amtlib project is and we have no connection to it.

**Comment by amtlib-dot-dll** [comment]
:joy: This is just my personal Gist, like a cloud-synchronized clipboard, not a repo. My name is amtlib-dot-dll


@nikobarli  @BrentRe
