### ISSUE TITLE
a feature for co_await, co_await (some_condition && timespan)

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#153]
I really like the co_await feature, 
now, we can do: 
co_await 1ms
co_await someIAsyncFunction

Can we add something like: 
co_await_if ( some_boolean_value == false )?

Currently I do:
co_await []()->IAsyncOp {
  while (some_boolean_value == false)
  {
  }
}();

**Comment by kennykerr** [comment]
You could use an [event](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682396(v=vs.85).aspx) with `winrt::resume_on_signal`. If all you have is a Boolean expression, you may be better off using a [condition variable](http://en.cppreference.com/w/cpp/thread/condition_variable).

As for your other suggestions, we don't own the coroutine proposal.

**Comment by bigdimboom** [comment]
winrt::resume_on_signal(Handle h, TimeSpan span);
Does the handle have to be an event? Can I pass something like a "waiting for a predicate" in conditional_variable?  

On the other hand, if I use conditional variable because no conditional variable like syntax for "resume_on_signal", I will have to block the many current running windows thread, which is very wasteful.

**Comment by kennykerr** [comment]
Any valid waitable object will do. An event is just the simplest and widely applicable example. Others include:

Change notification
Console input
Event
Memory resource notification
Mutex
Process
Semaphore
Thread
Waitable timer

The wait is performed by the kernel so you cannot simply use a construct of your own design.
