### ISSUE TITLE
view switching

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#154]
how do I switch from one view to another?

e..g one view is IFrameworkView for direct draw, the other one is ApplicationT. 

I wan to load my app with the UI XAML app and then press something to switch to an instance of the IFrameworkView for animation rendering. How can I achieve this?

**Comment by kennykerr** [comment]
That's a great question for http://stackoverflow.com/.

**Comment by bigdimboom** [comment]
![image](https://cloud.githubusercontent.com/assets/6119906/24315717/2e9d396a-10bf-11e7-8f36-2095006f61e8.png)
