### ISSUE TITLE
Where does GUIDs of generics come from?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [Microsoft/cppwinrt#155]
There are some definitions of the specialized generic types, for example

https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/winrt/internal/Windows.Storage.Streams.2.h#L20

However I am not able to find a similar GUID in system provided .winmd files or in SDK provided .idl files, so may I guess that they are just randomly generated?

**Comment by amtlib-dot-dll** [comment]
Well I have found some of them in the SDK provided headers and midlrt.exe generated headers; now the question is, are they randomly generated? If so, why are those GUIDs generated every time just all the same, even for custom objects; if not, then what is the rule? Wish I could get an answer here, thank you very much

**Comment by KevinWelton** [comment]
Thanks for the question. Generation of the GUIDs is not random, and we are working on options that will not require a namespace which happens to use the generic to be included. For now, you can also check out the [RoGetParameterizedTypeInstanceIID](https://msdn.microsoft.com/en-us/library/windows/desktop/br229857.aspx) function.

**Comment by amtlib-dot-dll** [comment]
Thanks, that should be what I am looking for
