### ISSUE TITLE
how to identify which thread is triggered an exception.

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#156]
I'm getting a windows exception from the debugger, but I can not trace back where it starts, which thread actually triggering the error, on call stack of visual studio 2015. Do I need a specialized debug symbol server?

for example,
![image](https://cloud.githubusercontent.com/assets/6119906/24512061/853f0390-153b-11e7-8123-f02250167007.png)

The call stack is not complete. The very last one is not my code. I want to find what actually caused the error in my code.

**Comment by kennykerr** [comment]
You can use the Visual Studio Exception Settings windows (Ctrl + Alt + E) to configure the debugger to break when an exception is thrown.
