### ISSUE TITLE
Debugging and experimantal modules

### ISSUE THREAD

**Issue by Fleischner** [Microsoft/cppwinrt#157]
First: Great work!
I compared the syndication sample to a c# equivalent and syntax is similar. Really really nice.

However debugging experience is more than shocking. Where c# shows clean information instantaneous (including nested members) with cppwinrt variables are either not recognized at all or list cryptic unusable garbage. Can/will this be improved?

And compile times... I hope modules will help a lot. I tried to compile one of the headers as an experimental c++ module (still vs2017 rc1). Compiler instantaneously crashed with an internal compiler error messaging that the header is too complex. Did you try/succeed to create module interface files?

**Comment by kennykerr** [comment]
Thanks for the feedback. We're well aware of these challenges and are working at solutions for improved debugging and better build performance. We have experimented with C++ modules in the past and plan to support them in a future update. They certainly provide a dramatic improvement over precompiled headers.
