### ISSUE TITLE
Progress and sticking points with using simple controls

### ISSUE THREAD

**Issue by andrew7webb** [Microsoft/cppwinrt#16]
I experimented a bit with some simple controls, and had a bit of success, but was not able to get all the approaches working mentioned in the announcement comments.  See the "Won't"s.   I just changed the App.cpp in the XamlCode project as follows.

```C++
struct App : ApplicationT<App>
{

	void myStyle( TextBlock & block )
	{
		block.FontFamily(FontFamily(L"Segoe UI Semibold"));
		block.FontSize(72.0);
		block.Foreground(SolidColorBrush(Colors::Orange()));
		block.VerticalAlignment(VerticalAlignment::Center);
		block.TextAlignment(TextAlignment::Center);
		block.TextWrapping(TextWrapping::Wrap);
	}

	void myMethod( winrt::Windows::IInspectable const & sender, const Windows::UI::Xaml::RoutedEventArgs & e)
	{
		int w = 3;
	}

    void OnLaunched(LaunchActivatedEventArgs const &)
    {
		Button    button;

		// button.Content( L"Button" );	// Won't work because
                // "cannot convert from 'const wchar_t [7]' to 'const winrt::Windows::IInspectable"

		Windows::IInspectable value = PropertyValue::CreateString(L"Click the button");	// Works 
		button.Content(value);

		// button.Click([=](auto const &&, auto const &&) 	{  int w = 5; 	});  // Won't compile
		button.Click({ this, &App::myMethod });		// Works.

		Grid grid;

        TextBlock block;
		myStyle(block);

		block.Text( L"hello world" );		

		StackPanel stackPanel;
		stackPanel.HorizontalAlignment( Windows::UI::Xaml::HorizontalAlignment::Center );
		stackPanel.Orientation(winrt::Windows::UI::Xaml::Controls::Orientation::Horizontal );
		stackPanel.Children().Append(block);
		stackPanel.Children().Append(button);


        Window window = Window::Current();
        window.Content(stackPanel);
        window.Activate();
    }
};
int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
    Application::Start([](auto &&) { make<App>(); });
}
```

I believe the button.Click was button::Click in the comments, but no luck with assigning a lambda that way either.
I assume there are a number of ways to create an IInspectable but I'm not too familiar with these classes.    

An example that shows how a basic application could be created with C++/WinRT would help people understand what is possible quicker.  Also, Intellisense works well and shows the types of the parameters needed if the right parameter type is already present.  If you have it wrong, like button.Content( L"Button" );	, then I see nothing helpful.   

I'm encouraged by your progress, and I think the goal is good.   I hope more documentation and sample generating resources get assigned to the project.

**Comment by kennykerr** [comment]
Nullable/reference/boxed types aren’t directly support yet, although you can use the PropertyValue class as a workaround to create them today.

The lambda signature you tried is not valid. You can be explicit and use the exact types as follows:

```C++
button.Click([=](Windows::IInspectable const & sender, RoutedEventArgs const & args)
{
    // ...
});
```

If you prefer to use auto, then this will work:

```C++
button.Click([=](auto const & sender, auto const & args)
{
    // ...
});
```

Or if you really don’t care about the parameters you might write something like this:

```C++
button.Click([=](auto && ...)
{
    // ...
});
```

We are keenly aware of the limitations around Xaml support. Thanks for the feedback. Keep it coming!

**Comment by andrew7webb** [comment]
Thanks.   I guess "Migrating C++ CX source code to C++ WinRT.md" and  "Registering for events using a lambda" was either over my head, or did not apply directly to button clicks.  I'll try again.

**Comment by kennykerr** [comment]
The documentation is a bit misleading. We'll get that fixed up - thanks!
