### ISSUE TITLE
Setting lambda on Loaded doesn't retain this

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#160]
```
  Loaded([=](const IInspectable &sender, const RoutedEventArgs &e) {
    setup_interface();
  });
```

setup_interface() is called properly (this exists), but immediately fails because __vfptr is garbage

**Comment by kennykerr** [comment]
Hi Matt, you'll have to give us a bit more context. If you're seeing UB or AV, it likely means something is going out of scope earlier than you expect.

**Comment by eklipse2k8** [comment]
@kennykerr *this* is a subclass of UserControl. I'm trying to set the main window content to it, but I am guessing that XAML controls cannot be subclassed with the current release.

I then tried subclassing with UserControlT<> and the compiler complained of a missing GUID.

**Comment by DefaultRyan** [comment]
Subclassing XAML types in general works now. For example, if you look at the XamlCode sample, you can see that it subclasses the XAML Application type with Application<T>. Is your code doing something substantially different from the pattern in that sample?
