### ISSUE TITLE
Returning std::future<StorageFile>

### ISSUE THREAD

**Issue by raffaeler** [Microsoft/cppwinrt#162]
Let's take for example this function returning a `winrt::Windows::Storage::StorageFile`:
```
static std::future<StorageFile> PickFileSaveFromDialog()
{
	winrt::Windows::Foundation::Collections::IVector<winrt::hstring> extensions;
	extensions.Append(L".jpg");
	extensions.Append(L".jpeg");
	extensions.Append(L".png");
	extensions.Append(L".bmp");

	w::FileSavePicker picker;
	picker.FileTypeChoices().Insert(L"Images", extensions);
	picker.SuggestedStartLocation(w::PickerLocationId::PicturesLibrary);
	picker.SuggestedFileName(L"Image");
	return co_await picker.PickSaveFileAsync();
}
```

This will generate (VS2017) the infamous error "no appropriate default constructor available" described [here](https://github.com/Microsoft/cppwinrt/blob/a0ffedfa3a4b388d460e17ee56aee32f303b8580/Docs/Migrating%20C%2B%2B%20CX%20source%20code%20to%20C%2B%2B%20WinRT.md).

The problem is that I can't control the construction of the object because it's up to the std::future implementation pretending to create the object. Here is the relevant part of "future" include file

```
	_Associated_state(_Mydel *_Dp = 0)
		: _Exception(),
		_Retrieved(false),
		_Running(false),
		_Ready(false),
		_Ready_at_thread_exit(false),
		_Has_stored_result(false),
		_Deleter(_Dp)
		{	// construct                                  // <== !!
		// TODO: _Associated_state ctor assumes _Ty is default constructible
		_Init_refs();
		}
```

I currently resolved by returning `std::future<StorageFileWrapper>` instead:
```
struct StorageFileWrapper
{
	w::StorageFile StorageFile = nullptr;
	operator w::StorageFile() { return StorageFile; }
	StorageFileWrapper() { }
	StorageFileWrapper(const w::StorageFile& storageFile) : StorageFile(storageFile) {}
};
```
And then modifying the function this way:
```
static std::future<StorageFileWrapper> PickFileSaveFromDialog()       // <== !!
{
	winrt::Windows::Foundation::Collections::IVector<winrt::hstring> extensions;
	extensions.Append(L".jpg");
	extensions.Append(L".jpeg");
	extensions.Append(L".png");
	extensions.Append(L".bmp");

	w::FileSavePicker picker;
	picker.FileTypeChoices().Insert(L"Images", extensions);
	picker.SuggestedStartLocation(w::PickerLocationId::PicturesLibrary);
	picker.SuggestedFileName(L"Image");
	return StorageFileWrapper(co_await picker.PickSaveFileAsync());   // <== !!
}
```
The caller does not need to be changed thanks to the implicit operator instead.

Is there a solution or a better workaround to avoid using the wrapper?

**Comment by kennykerr** [comment]
This is a problem with std::future where it insists on T having a default constructor. There are many other problems with std::future, not the least of which is its poor performance. None of these issues can be fixed without a change to the C++ standard or the introduction of a new coroutine type. C++/WinRT's IAsyncOperation and friends don't suffer from any of these problems but currently requires you to explicitly associate a specific GUID with any specialization that doesn't appear in the projection ([here's an example](https://github.com/Microsoft/cppwinrt/blob/master/10.0.15063.0/Samples/JustCoroutines/Main.cpp)). That will be fixed in a future update thanks to improved constexpr support in Visual C++ 2017.

Of course IAsyncOperation and friends only supports WinRT types. I have it on my todo list to write a better future library, but that's not directly related to C++/WinRT.

**Comment by raffaeler** [comment]
Thank you @kennykerr 
Totally agree. The future<T> library also does not reconcile the continuation, therefore you get a WrongThreadException as soon as visual component is accessed.
Do you suggest to use the PPL instead?
What is the current best way to return a task/future/promise at the moment?

**Comment by kennykerr** [comment]
Don't use PPL. It has even more problems than std::future. Your best bet is to use IAsyncAction/IAsyncOperation whenever possible. Best performance, correct thread context, best support for WinRT types.

**Comment by raffaeler** [comment]
Thanks @kennykerr, this info should deserve a new "best practices" document if I didn't miss it.
I believe I will have to use the PPL because the app also contain the REST toolkit (ex casablanca), but I will see how to convert all the calls (boring and long :) )

**Comment by raffaeler** [comment]
So basically the "rules" are:
- For WinRT types use as much as possible the `winrt::Windows::Foundation::IAsyncXXX<>` as return types. The thread context of the caller is captured automatically.
Follow the previously linked document to write these correctly, specifically the declaration with guids.

- For all the other types (including Platform::Size) use future<> instead. In this case the thread context of the caller is **not** captured and must be done (if required) manually (w is the winrt namespace):
```
w::thread_context ui_thread;
auto data = co_await DomeSomethingReturningAFuture();
co_await ui_thread;
// code needing to be executed in the main (UI) thread
```
```
This would be the equivalent to write this instead:
Dispatcher->RunAsync(CoreDispatcherPriority::Normal, ref new DispatchedHandler([this]()
{
    // code needing to be executed in the main (UI) thread
}));
```
Please note that the last snippet use C++/CX because usually the thread context need to be queued back to the main thread when writing UI interfaces and currently there is still no support from cppwinrt to use XAML ... we are all waiting for this great moment :)

- In certain cases (REST sdk also known as Casablanca) the libraries may return the ppl tasks. In this case the context is captured automatically but the diagnostics is more complex, so I try to avoid them.
