### ISSUE TITLE
https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/Samples/CL/main.cpp report error "c3861:'initialize': identifier not found", 

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/cppwinrt#163]
Sample https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/Samples/CL/main.cpp has error "c3861:'initialize': identifier not found", since ‘initialize’ have renamed to init_apartment, this issue fixed with revision ‘74c56cb35’, however, the latest revision ‘532b09e’ for WinRT looks report this issue again. and we can’t find the revision ‘74c56cb35’, does anyone revert that fix?

Here is details for revision ‘74c56cb35’:
D:\WinRT\src>git show 74c56cb35fdf7ebcf13f9b99c2469387cadfe617
commit 74c56cb35fdf7ebcf13f9b99c2469387cadfe617
Author: Brent Rector <brent.rector@microsoft.com>
Date:   Wed Mar 8 13:28:40 2017 -0800

    Update main.cpp

diff --git a/10.0.14393.0/Samples/CL/main.cpp b/10.0.14393.0/Samples/CL/main.cpp
index 9b33abd..8164f51 100644
--- a/10.0.14393.0/Samples/CL/main.cpp
+++ b/10.0.14393.0/Samples/CL/main.cpp
@@ -6,5 +6,5 @@ using namespace winrt;

 int main()
 {
-    initialize();
+    init_apartment();
 }

**Comment by kennykerr** [comment]
Sorry this happened again Phoebe. Our publishing process needs a bit of work... :disappointed:

**Comment by KevinWelton** [comment]
I new release has just been dropped that should solve your problem :)

**Comment by PhoebeHui** [comment]
Thank you Kenny and Kevin! WinRT is clean now.
