### ISSUE TITLE
A potential bug in the StreamSocket projection?

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#164]
server code:
![image](https://cloud.githubusercontent.com/assets/6119906/24770542/4483df72-1ad8-11e7-8532-9e34737ab3ca.png)
client code:
![image](https://cloud.githubusercontent.com/assets/6119906/24770556/4f4d68ec-1ad8-11e7-9158-d78bdd4ec80d.png)
The problem is, when the "onConnection" event has been triggered on server, "ConnectAsync" is blocking forever on client. I wonder if this is bug in the winrt/c++ projection. The sample code for c++/cx runs correctly.

**Comment by bigdimboom** [comment]
btw, the "co_await d_socket.ConnectAsync(...)" does not crash, does not throw error; it is just block forever. The IAsyncAction.IsComplete() is always false;

**Comment by BrentRe** [comment]
We'd need more information to help. E.g. What version of Visual Studio are you using? VS2015 or VS2017. VS2015 has a known code generation bug for co-routines that result in the same symptom. I can't tell if you're encountering it because I'd need to see all the code in the method containing the co-await call. Basically, you can hit it if there are multiple return statements in the method containing the co_await call.

There are two workarounds if you're hitting this particular C++ compiler code generation bug: 1) Switch to VS2017, or 2) add a co_return statement at every function exit point in the function containing the co_await call.

**Comment by bigdimboom** [comment]
![image](https://cloud.githubusercontent.com/assets/6119906/24772453/65f9744e-1adf-11e7-9500-74166bc649b7.png)
vs 2015

**Comment by bigdimboom** [comment]
So, I rewrite some code and did some experiments on this issue. Here is some interesting facts:

The simplified version of socket connection works fine. The following code does not have "forever blocking" effects. (good code)

![image](https://cloud.githubusercontent.com/assets/6119906/24803026/e92b4944-1b77-11e7-918b-d01aeb01d608.png)

A modified version of the simplified version of socket connection also works fine. (good code)
![image](https://cloud.githubusercontent.com/assets/6119906/24803141/4ab3a0a8-1b78-11e7-8450-f15d992c7f01.png)
It is good, because there should be no difference between "routine" and "co_routine";

I went even further, which also works well: (good code)
![image](https://cloud.githubusercontent.com/assets/6119906/24803363/fde33be8-1b78-11e7-9444-009eadfaa588.png)

OK, here goes my code, which is the problematic one, which I don't understand why it happens:
fist, my interface of socket connection is none co_routine:
"virtual void connect(std:string address) = 0"

then, when I was implementing the interface I use "co_routine". Something like the previous post, which I assume is totally fine and it should be fine: (bug code)
![image](https://cloud.githubusercontent.com/assets/6119906/24803578/abf5e1e0-1b79-11e7-8da5-4f5d726c4003.png)

What did do wrong?

**Comment by bigdimboom** [comment]
OK, for now, the only way to walk around is to change the interface "virtual void connect(std::string address) = 0" to co_routine "virtual IAsyncAction connectAsync(std::string address) = 0";

**Comment by bigdimboom** [comment]
I also test out some other co_await XXXXXAsync situation.
![image](https://cloud.githubusercontent.com/assets/6119906/24818954/9448f00a-1bb0-11e7-8f5b-1ebe658410d4.png)

The above example works fine. However if I do this "co_await someCoRoutineHandler", it will block forever.

**Comment by bigdimboom** [comment]
O.K. Problem solved. I missed a co_return in one other co_routine.
