### ISSUE TITLE
BLE API problem

### ISSUE THREAD

**Issue by andrewramsay** [Microsoft/cppwinrt#165]
Apologies in advance if I'm doing something stupid here, but I'm trying to port some pretty simple code using the new BLE GATT API from a working UWP application to a WinRT application, and calling BluetoothLEDevice::FromBluetoothAddressAsync() just seems to hang indefinitely no matter what I do. 

I know the address I'm passing in is valid for the device I'm trying to access, and I was also able to get advertisement scanning to work using a BluetoothLEAdvertisementWatcher object and extract the address directly from the results to pass to FromBluetoothAddressAsync. It's definitely correct. 

I've tried calling the function as if it were synchronous with BluetoothLEDevice::FromBluetoothAddressAsync(address).get(), and also naturally with co_await as seems to be the recommended convention for cppwinrt code. I tried another couple of *Async APIs (e.g. BluetoothAdapter::GetDefaultAsync()) and those worked. Is there anything unusual about this particular function that could be responsible for what I'm seeing? 

I understand the BLE GATT APIs are still very new but they do work as expected in my UWP app. I've had this problem for a couple of SDK versions now, and am currently using 10.0.15063.0.

**Comment by kennykerr** [comment]
This appears to be API-specific. You may need to enable the Bluetooth capability in your app manifest.

**Comment by andrewramsay** [comment]
OK, I was assuming that wasn't necessary because it allowed me to scan for BLE adverts from the console app with no manifest, while the same operation failed in the UWP app without the "bluetooth" DeviceCapability added. I've just tried modifying one of the cppwinrt samples that had a manifest already, and after adding the "bluetooth" capability and a few lines of code to call that API it seems to be working, so that's great, thanks!

I'm a bit unclear on what's possible in terms of manifests and capabilities and the various platforms: can I somehow create a VS2017 project which will let me use cppwinrt, has a manifest so I can add capabilities, but ***isn't*** a Windows Store/GUI app? If you can point me to any relevant documentation that would be much appreciated! Ideally what I'd like to do is package up some BLE code into a dll that could be linked to an existing application, but I'd settle for a simple console app instead.

**Comment by tim-weis** [comment]
@andrewramsey: Almost the entire UWP API surface is accessible from desktop applications, with two notable exceptions: The XAML UI APIs, and APIs that require the calling app to have a package identity<sup>1</sup>. Whether a particular API is available to desktop applications is controlled by the [DualApiPartition](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.DualApiPartitionAttribute) attribute. The [BluetoothLEDevice](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice) class has this attribute set.

Capabilities (as listed in an application's manifest) are not evaluated for desktop applications. As far as I know, no additional provisioning with respect to specifying required capabilities is required to access UWP APIs from a desktop application.

<hr/>

<sup>1</sup> *See [UWP APIs callable from a classic desktop app](https://msdn.microsoft.com/en-us/library/windows/desktop/mt695951.aspx).*

**Comment by andrewramsay** [comment]
Thanks for clearing that up, that's what I was hoping was the case from what I could understand of the documentation. It's certainly true that I don't have any problems calling the other BLE APIs I've tried so far from a desktop app, but I still can't get it to give me a BluetoothLEDevice instance. 

I doubtful it's a cppwinrt issue by this point though. I think the problem is more likely to be related to the BLE devices I'm working with, the BT hardware/driver or the BLE API itself (it doesn't work reliably even in UWP apps), so I'll just close this issue for now.

**Comment by andrewramsay** [comment]
Just to say that after coming back to this problem recently, I came across [this post](https://social.msdn.microsoft.com/Forums/en-US/58da3fdb-a0e1-4161-8af3-778b6839f4e1/bluetooth-bluetoothledevicefromidasync-does-not-complete-on-10015063?forum=wdk) referenced from issue #179. So it *was* an API issue, and the workaround given in that thread got things working for me.
