### ISSUE TITLE
Any chance of Winrt Project Templates not specific  DirectX 

### ISSUE THREAD

**Issue by IkoLogs** [Microsoft/cppwinrt#167]
I was very pleased to find winrt/cpp nuget package now available, and seems to work without need for winrt project side header includes.

But would be very nice to have winrt project template that is not specific to 3D all i could find were Directx winrt templates. 

Currently i use a native win32 c++ project for winrt with project settings as per winrt  ReadMe doc
except now i use Nuget winrt instead of adding headers directly.

I am doing some work on uwp diagnostics /etw providers and my code compiles fine, but is failing but never returns ffrom deep inside winrt call at runtime, whilst registring logenabled event handler . (inti apartment call was fine code never returns from first event registration )

Again The short version of my question is Winrt project templates for non directx specific app

cheers

**Comment by BrentRe** [comment]
Providing project templates for UWP and Desktop apps using C++/WinRT is on our backlog. We'll get to them eventually. We have a lot of things we want to do. :)
