### ISSUE TITLE
winrt::attach to C++/CX ref class

### ISSUE THREAD

**Issue by dacendale** [Microsoft/cppwinrt#17]
The documentation Interoperability Helper Functions talks about using winrt::attach to take ownership of an ABI value to give ownership to a C++/WinRt type. I'd like to use it to get ownership from a C++/CX type, which is stated in the file ~line 83, however, I can't figure out what I need to cast the C++/CX type to in order to use it. I'd love to see an example of this. The code I'm working with is something like this:
```C++
RefClass::RefClass(SwapChainPanel^ swapChainPanel)
{
    winrt::Windows::UI::Xaml::Controls::SwapChainPanel panel(nullptr);
    winrt::attach(panel, swapChainPanel);
}
```
This doesn't compile because it can't convert swapChainPanel into something usable for panel. I'm thinking I need to reinterpret_cast swapChainPanel to an IUnknown and then get the address of the com object, or something of that nature.
Thanks for any suggestions. I really love this library btw.

**Comment by dacendale** [comment]
Apparently I should have tried the obvious solution first. This seems to work:
```C++
RefClass::RefClass(SwapChainPanel^ swapChainPanel)
{
   auto asAbi = reinterpret_cast<winrt::ABI::Windows::UI::Xaml::Controls::ISwapChainPanel*>(swapChainPanel);
   winrt::attach(_swapChainPanel, asAbi);
}
```
Is this the correct way of attaching a C++/CX object to a C++/WinRt instance?
I really like how I can have a ref class and mix in cppwinrt in pieces. The incremental conversion makes things much easier. Thanks for the great library.

**Comment by kennykerr** [comment]
You're close. In C++/CX, the reinterpret_cast will return the ABI pointer but not increment the reference count. So in your second example, you’re attaching the reference still held by the hat. Instead, you want the C++/WinRT object to get its own reference. So in this case you should use the copy_from function rather than the attach function.

```C++
winrt::copy_from(_swapChainPanel, asAbi);
```

This will ensure that AddRef is called.

**Comment by dacendale** [comment]
I mis-read the documentation. I thought it was attach/detach that managed the reference count and copy_to/copy_from didn't. The note on attach says it 'takes ownership' and I assumed that meant incrementing the ref count and didn't read further where copy_* does say that it uses the ref counting mechanic. That's what I get for not reading the full section. Thanks for the clarification.
