### ISSUE TITLE
does any one know how to swap buffer.

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#171]
I want to use double buffering. I have to buffer one is called "Buffer renderBuffer", the other one is called "Buffer Buffer", I want to be able to swap underneath buffer in order to achieve double buffering. I know how to receive the raw pointer(void*) underneath, but I don't know how to do content switching in winrt/c++, meaning how do I get void**

**Comment by bigdimboom** [comment]
I found one cx/c++ code that might fit the job, but how do I translate it:

![image](https://cloud.githubusercontent.com/assets/6119906/25014609/82023150-2046-11e7-918b-07d5018c871f.png)

**Comment by kennykerr** [comment]
I assume you're referring to the `Windows::Storage::Streams::Buffer` class. You can use [`std::swap`](http://en.cppreference.com/w/cpp/algorithm/swap).

```C++
using namespace Windows::Storage::Streams;

Buffer a(10);
Buffer b(20);

assert(a.Capacity() == 10);
assert(b.Capacity() == 20);

std::swap(a, b);

assert(a.Capacity() == 20);
assert(b.Capacity() == 10);
```

If you need atomicity you'll need to [use a lock](http://en.cppreference.com/w/cpp/thread). James McNellis [explains the rationale here](http://stackoverflow.com/questions/4503628/how-can-i-atomically-swap-two-pointers-on-windows).

**Comment by bigdimboom** [comment]
Thanks, Kenny. Actually, I mean the memory underneath  the "Buffer" object. I want to do some memory pooling with my own memory manager.  The question is how do I do memory pooling for most of winrt/c++ object? The interface does not support allocator for object construction.

**Comment by kennykerr** [comment]
Unless the Windows::Storage::Streams API provides explicit support for that, the only way to achieve it would be to write your own implementation of Windows::Storage::Streams::IBuffer.

**Comment by BrentRe** [comment]
There is no mechanism provided to swap the underlying buffers in an IBuffer. It would be highly dangerous and non-deterministic to do so as you generally have no knowledge of whether someone is using raw pointer to the current buffer.

Instead, you should swap IBuffer objects.
