### ISSUE TITLE
In-App product purchases

### ISSUE THREAD

**Issue by yperaltag** [Microsoft/cppwinrt#172]
Hi guys, I'm experimenting with this new modern cpp project for winrt, it seems great but I'm having some problems with a simple code about in-app product purchases using the Windows.Services.Store namespace. I have windows 10 installed with Version 1607 (OS Build 14393.970) and I also have an application published in Microsoft Store for testing purposes. I have developed two projects in visual studio 2017 (community edition): one using c++/cx and the other using c++/winrt. The one using c++/cx lists my application add-ons (3 add-ons published in the store) but the one using c++/winrt says I have no add-ons. In both projects I have associated the application with the one I have published in the store. If any of you have any idea of why I'm having this error, please I would really appreciate it.

This is the c++/cx version (the one that works):
```cpp
auto filterList = ref new Vector<String^>({ "Consumable" ,"Durable", "UnmanagedConsumable" });
auto storeContext = StoreContext::GetDefault();
auto addOns = co_await storeContext->GetAssociatedStoreProductsAsync(filterList);

if (addOns->ExtendedError.Value != S_OK) {
    textBlock1->Text = "ERROR!";
}
else if (addOns->Products->Size == 0) {
    textBlock1->Text = "NO add-ons!";
}
else {
    textBlock1->Text = "";
    for (auto addOn : addOns->Products) {
        auto product = addOn->Value;
        textBlock1->Text += product->StoreId + "\n";
    }
}
```

and this is the c++/winrt version (the one that doesn't works):
```cpp
iterable<hstring> filterList = { L"Consumable" , L"Durable" , L"UnmanagedConsumable" };
auto storeContext = StoreContext::GetDefault();
auto addOns = co_await context.GetAssociatedStoreProductsAsync(filterList);

if (addOns.ExtendedError()) {
    textBlock1.Text(L"ERROR!");
}
else if (addOns.Products().Size() == 0) {
    textBlock1.Text(L"NO add-ons!");
}
else {
    std::wostringstream result;
    for (auto addOn : addOns.Products()) {
        auto product = addOn.Value();
        result << product.StoreId().c_str() << "\n";
    }
    textBlock1.Text(result.str());
}
```

**Comment by kennykerr** [comment]
There are a few problems here, but the main one is that the `iterable<T>` (lowercase) class is not meant to be used as a local variable. It will very likely be renamed to something like `param::iterable<T>` as it's not obvious, but this won't work as written. Instead, just pass the initializer list directly to the method call:

```C++
GetAssociatedStoreProductsAsync({ L"a" , L"b" , L"c" })
```

Then there are what I presume are some typos. The CX version calls `GetAssociatedStoreProductsAsync` on the `storeContext` object but the C++ version calls it on some other object called `context`. Finally, the `ExtendedError` method returns an `HRESULT`. You presumably need to compare this against `S_OK`.

Beyond that I don't know anything about this particular API, but I hope that helps.

**Comment by KevinWelton** [comment]
If you are really wanting to declare the list as a local variable, you can just use a std::vector for filterList. This can be passed as the parameter to GetAssociatedStoreProductsAsync().

So this
```
iterable<hstring> filterList = { L"Consumable" , L"Durable" , L"UnmanagedConsumable" };
auto storeContext = StoreContext::GetDefault();
auto addOns = co_await context.GetAssociatedStoreProductsAsync(filterList);
```
could be written like this
```
std::vector<hstring> filterList = { L"Consumable" , L"Durable" , L"UnmanagedConsumable" };
auto storeContext = StoreContext::GetDefault();
auto addOns = co_await context.GetAssociatedStoreProductsAsync(filterList);
```

**Comment by kennykerr** [comment]
Thanks Kevin, I meant to point that out as well but I was too focused on the problem. 😄

**Comment by yperaltag** [comment]
Thank you Kenny and Kevin for your soon answers, but actually neither of them worked to me, with your suggestions I got the message "ERROR!" because the return value of GetAssociatedStoreProductsAsync wasn't S_OK, but now I solved the problem, I did it this way using moving semantics:
```cpp
std::vector<hstring> filterList = { L"Consumable" , L"Durable" , L"UnmanagedConsumable" };
auto storeContext = StoreContext::GetDefault();
auto addOns = co_await storeContext.GetAssociatedStoreProductsAsync(std::move(filterList));
```
PD: I think it would be nice to be able to use the **_auto_** keyword when creating the filter list as in c++/cx version, but currently it throws compilation errors.

**Comment by kennykerr** [comment]
Glad you got it working. We've taken the usability issues into consideration for a future update.

**Comment by tim-weis** [comment]
@yperaltag One of the jobs of the re-specified `auto`-keyword is to remove the need for type duplication. That works for the C++/CX code snippet, because the type is spelled out in full on the right-hand side (`Vector<String^>^`). Contrast that with the C++/WinRT code snippet, where the type is only ever named on the left-hand side. If you replaced that, too, with `auto`, the compiler would have no way of knowing, that you meant `{ L"a", L"b", L"c" }` to be converted to `std::vector<hstring>`. That's nothing C++/WinRT can change. You'd have to bring this up with the [ISO C++ Committee](https://isocpp.org/std/the-committee).

**Comment by yperaltag** [comment]
hi @tim-weis, thanks for your opinion, but when I stated that it would be nice to be able to use something like this:
```cpp
auto filterList = { L"Consumable" , L"Durable" , L"UnmanagedConsumable" };
auto addOns = co_await storeContext.GetAssociatedStoreProductsAsync(filterList);
```
I didn't mean that `filterList` had to be of type `std::vector<hstring>`, but insted that the parameter in the method `GetAssociatedStoreProductsAsync` should be able to accept something created with the syntax above, ie `std::initializer_list<const wchar_t *>`.
