### ISSUE TITLE
missing constructor in array_view

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#174]
I think we are missing a constructor for array_view<T>.
"array_view<T>::array_view(size_t size)", other wise how do I initialize an empty array with a fixed size.

**Comment by kennykerr** [comment]
You should not create a `winrt::array_view` directly. You can use [`std::array`](http://en.cppreference.com/w/cpp/container/array) (or `std::vector`) instead. The `winrt::array_view` is meant for parameter binding.
