### ISSUE TITLE
StorageFolder/StorageFile - check for existence in co_routine ?

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#175]
try/catch doesn't work. What is the proper approach.

**Comment by kennykerr** [comment]
It depends what you're trying to do, but this should work:

```C++
IAsyncAction Sample()
{
    try
    {
        StorageFile file = co_await StorageFile::GetFileFromPathAsync(L"C:\\folder\\file.txt");

        printf("opened: %ls\n", file.DisplayName().c_str());
    }
    catch (hresult_error const& e)
    {
        printf("failed: %ls\n", e.message().c_str());
    }
}

int main()
{
    init_apartment();

    Sample().get();
}
```

**Comment by JackDetrick** [comment]
Here's my code that fails (file in nonexistent)

IAsyncOperation<int>  DataBase::ReadDataBase(
	RegisterItems const &  ptrRegisterItems,
	StringItems  const & ptrStringItems,
	ResourceContent const & ptrResourceContent) {

	StorageFolder _turboCalc = co_await ApplicationData::Current().LocalFolder().GetFolderAsync(L"TurboCalc"); //valid folder	

	StorageFile _fileDoubles = nullptr; //no default constructor
		try {
			_fileDoubles = co_await _turboCalc.GetFileAsync(L"FileDoublesxxx.dbo");
		}
		catch (hresult_error const & e) {
			printf("error: %ls\n", e.message().c_str());
		}
...

If fails with:
exception thrown at 0x74533AC2 in IBuffer.exe: Microsoft C++ exception : winrt::hresult_error at memory location 0x02CBE1FC.

**Comment by JackDetrick** [comment]
Posted the problem on StackOverflow...
