### ISSUE TITLE
XAML

### ISSUE THREAD

**Issue by Azhang74** [Microsoft/cppwinrt#176]
Can I use cppwinrt with XAML ?  Where is Documments? thank you!

**Comment by FeBrex** [comment]
Yes you can, at least I have managed to use it. Even though not all features are supported out of the box (e.g. XAML metadata).

This is what I did:

* Start with the XamlCode sample
* Add a XAML file
* Remove the code behind (C++/CX)
* Disable the XAML compiler for the file and make it deployable (right click the file in Solution Explorer, Properties -> General: Content: Yes, Item Type: Xml
* Load the Xaml file from code

```
fire_and_forget App::OnLaunched(LaunchActivatedEventArgs const&)
{
	// Asynchronously load UI from XAML file.
	auto const packageFolder = Package::Current().InstalledLocation();
	auto const file = co_await packageFolder.GetFileAsync(L"MainPage.xaml");
	auto const xaml = co_await FileIO::ReadTextAsync(file);

	auto const uiElement = XamlReader::Load(xaml).as<Page>();

	// TODO: Perform view related binding until XAML support is mature.

	// Display UI.
	auto window = Window::Current();
	window.Content(uiElement);
	window.Activate();
}
```

Example for binding a command:

```
auto const openFileAppBarButton = uiElement.FindName(L"OpenFileAppBarButton").as<AppBarButton>();
openFileAppBarButton.Command(mainPageViewmodel_.openFileCommand);
```

Field `openFileCommand` is a of a custom type that `winrt::implements<..., winrt::Windows::UI::Xaml::Input::ICommand>`

Example for binding to a property:

```
auto const xTextBlock = uiElement.FindName(L"XTextBlock").as<TextBlock>();
{
	Binding b;
	b.Source(mainPageViewmodel_);
	b.Path(PropertyPath(L"X"));
	b.Mode(BindingMode::OneWay);
	xTextBlock.SetBinding(TextBlock::TextProperty(), b);
}
```
`mainPageViewmodel_`'s type `winrt::implements<..., winrt::Windows::UI::Xaml::Data::ICustomPropertyProvider>`

Xaml designer works for me as well (more or less)

**Comment by kennykerr** [comment]
Nice. 😄

**Comment by Azhang74** [comment]
@kennykerr @FeBrex Thank you very much!  I am looking forward to XAML support as C++/CX and C# very soon.  thank you again!

**Comment by BrentRe** [comment]
Greatly improved support for using C++/WinRT with XAML is coming... Can't say quite when yet, but it is coming...

**Comment by DomXC** [comment]
@FeBrex could you please give me a guide for dummies (I have never actively worked with XAML), how to add a XAML file?
My steps: Add New Item -> Visual C++ -> XAML -> what now? Blank Page? XAML View?
For both I am getting the error: Invalid Markup (ThemeResource is not supported in a Windows Universal Project).
Could you please provide a simple valid XAML code? Just a box with button, whatever :-)
Thank you!

**Comment by FeBrex** [comment]
I've recorded a small video to get you started: https://youtu.be/eHCDTsQrTX8

**Comment by FeBrex** [comment]
Here is another video on command handling: https://youtu.be/E1Y9UKg9Ndg

**Comment by mustaphakd** [comment]
Great!
just what I was looking for :)

**Comment by geolffrey** [comment]
@FeBrex, I have followed your tutorials and this helped me a lot in my learning. Now trying to go a little bit ahead, I'm trying to binding myCommand to several buttons, is that possible or I have to implement <CommandInput, ICommand> for each button?

{
	auto const btn1 = uiElement.FindName(L"myButton1").as<ButtonBase>();
	btn1.Command(cmd);
}

{
	auto const btn2 = uiElement.FindName(L"myButton2").as<ButtonBase>();
	btn2.Command(cmd);
}

{
	auto const btn3 = uiElement.FindName(L"myButton3").as<ButtonBase>();
	btn3.Command(cmd);
}

**Comment by geolffrey** [comment]
@FeBrex, I have followed your tutorials and this helped me a lot in my learning. Now trying to go a little bit ahead, I'm trying to binding myCommand to several buttons and make them execute separated functions, is that possible or I have to implement <CommandInput, ICommand> for each button?

{
	auto const btn1 = uiElement.FindName(L"myButton1").as<ButtonBase>();
	btn1.Command(cmd);
}

{
	auto const btn2 = uiElement.FindName(L"myButton2").as<ButtonBase>();
	btn2.Command(cmd);
}

{
	auto const btn3 = uiElement.FindName(L"myButton3").as<ButtonBase>();
	btn3.Command(cmd);
}

**Comment by FeBrex** [comment]
@geolffrey, thanks for your feedback! The short answer is, no, you don't have to implement this for each button.

The long answer is, you can accomplish this by multiple (different) ways. I'll name a few options. Feel free to use the full power of standard C++ to implement your own solution if you don't like my proposals

The first solution is inspired by C#'s DelegateCommand pattern. I'm using this solution in my own code. The idea is that your class stores generalized function pointers to "functions" that implement the logic of CanExecute and Execute. I only present the part that is different from my previous postings, but in case you still have a question feel free to ask.

```
struct Function_command : implements<Function_command, ICommand> {
  // Make these members "point" to the functionality that should be executed.
  std::function<void (const IInspectable&)> execute_;
  std::function<bool (const IInspectable&)> can_execute_;

  void Execute(const IInspectable& value) { execute_(value); }

  bool CanExecute(const IInspectable& value)
  {
    const auto can_execute = can_execute_(value);
    if (can_execute != could_execute_) {
      could_execute_ = can_execute;
      can_execute_changed_event_(*this, nullptr);
    }
  }
};
```

The following proposals are based on inheritance. The first solution uses dynamic polymorphism, the second uses static polymorphism.

```
struct Dyn_poly_command : implements<Dyn_poly_command, ICommand> {
  void Execute(const IInspectable& value) { do_execute(value); }

  void CanExecute(const IInspectable& value)
  {
    const auto can_execute = do_can_execute(value);
    if (can_execute != could_execute_) {
      could_execute_ = can_execute;
      can_execute_changed_event_(*this, nullptr);
    }
  }

  // "Force" implementor of derived class to provide implementation.
  virtual void do_execute(const IInspectable&) = 0;

  virtual void do_can_execute(const IInspectable&) = 0;
};

struct My_command : Dyn_poly_command {
  void do_execute(const IInspectable&) override
  {
    // ....
  }

  bool do_can_execute(const IInspectable&) override
  {
    return /* ... */;
  }
};
```

```
template<typename Derived>
struct Stat_poly_command : implements<Stat_poly_command<Derived>, ICommand> {
  void Execute(const IInspectable& value) { static_cast<Derived*>(this)->do_execute(value); }

  void CanExecute(const IInspectable& value)
  {
    const auto can_execute = static_cast<Derived*>(this)->do_can_execute(value);
    if (can_execute != could_execute_) {
      could_execute_ = can_execute;
      can_execute_changed_event_(*this, nullptr);
    }
  }
};

// "override" functionality of base class.
struct My_command : Stat_poly_command<My_command> {
  void do_execute(const IInspectable&)
  {
    // ....
  }

  bool do_can_execute(const IInspectable&)
  {
    return /* ... */;
  }
};
```

Please consider these snippets as ideas not actual implementations, except for the first one I haven't tried the last two yet.

**Comment by geolffrey** [comment]
FeBrex, thank you very much. I went with the first idea.

**Comment by sbeachdev** [comment]
@FeBrex: How did you define " std::function<void (const IInspectable&)>" and  "std::function<bool (const IInspectable&)>" in the *.idl file?
