### ISSUE TITLE
Bluetooth LE Notifications

### ISSUE THREAD

**Issue by anlumo** [Microsoft/cppwinrt#179]
Hello,

I'm trying to talk to a Bluetooth LE device from a desktop non-managed C++ application using cppwinrt. I've managed to use the BluetoothLEAdvertisementWatcher to discover devices and access the values in the GATT services. However, now I'm trying to get notifications for value changes:

    characteristic.ValueChanged([&](GenericAttributeProfile::GattCharacteristic characteristic, 
    GenericAttributeProfile::GattValueChangedEventArgs eventArgs) {
      std::wclog << L"Notification received!" << std::endl;
    });
    
    GenericAttributeProfile::GattCommunicationStatus status = co_await characteristic.WriteClientCharacteristicConfigurationDescriptorAsync(GenericAttributeProfile::GattClientCharacteristicConfigurationDescriptorValue::Notify);
    if (status != GenericAttributeProfile::GattCommunicationStatus::Success) {
      std::wclog << L"Device had error " << int(status) << L" while trying to write to characteristic configuration" << std::endl;
      return;
    }

The status I receive back is success, but I don't get any notifications (even though the device constantly changes the values). The notifications work fine from a desktop C# application with the same calls, but I need this in non-managed C++. Do you have an idea what's wrong? Maybe there's a problem with the lack of an event loop of some kind? I'm not sure on which thread this `ValueChanged` event is supposed to be fired on (my `std::wclog` is safe to be called from any thread there). Just reading the values with `ReadValueAsync()` works fine.

**Comment by kennykerr** [comment]
I'm not familiar with this API, but if you can provide a self-contained repro we can investigate.

**Comment by anlumo** [comment]
The problem is that you need hardware to reproduce this. Do you have any Bluetooth LE device you can use for testing?

**Comment by kennykerr** [comment]
Sorry I don't.

**Comment by anlumo** [comment]
Maybe someone from the team working on the Bluetooth Stack can help? I can receive advertisements, so callbacks work in general, just not the ones for notifications.

**Comment by mtbeaver** [comment]
Can you please collect logs for the issue with the Feedback Hub?  Providing a repro app would be helpful as well, as I am not familiar with this project.

Instructions for using the Feedback Hub Reproduce feature: 
>Launch the Feedback Hub.
Select the "Add new feedback" button.
Mark the issue as a problem.
Fill out the summary and the details.
Select the "Hardware, devices and Drivers" category.
Select the appropriate Bluetooth subcategory based on your issue.
Hit the "Start capture" button.
Toggle the Bluetooth radio off-on via the quick action menu or the remote device's power (we need the connection information).
Repro the issue.
Hit the "Done" button.
Hit the "Post feedback" button.

Logs will be uploaded over the course of the next few hours (to help it along connect your device to AC power and the network at the same time)

**Comment by anlumo** [comment]
In the meantime, this has become a known issue and is tracked here: https://social.msdn.microsoft.com/Forums/en-US/58da3fdb-a0e1-4161-8af3-778b6839f4e1/bluetooth-bluetoothledevicefromidasync-does-not-complete-on-10015063?forum=wdk
