### ISSUE TITLE
C++/WinRT milestones

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#181]
Which is likely to ship next, XAML inclusion or .winmd generation?

**Comment by BrentRe** [comment]
Support for XAML will come first.

At that time, if you need a .winmd (and you will in many XAML application use cases), you will need to create it using existing tools (IDL+MIDLRT and so on).

**Comment by MRahilly** [comment]
Thanks Brent

**Comment by VSChawathe** [comment]
XAML/CX just [works](https://gitlab.com/iProcess/modernCX) if using nugget one restores the winrt package.
![nuget restore](https://cloud.githubusercontent.com/assets/3293600/25366693/046ee9ca-298f-11e7-90cc-954ea15ce9bb.png)
