### ISSUE TITLE
Direct2d / DirectWrite

### ISSUE THREAD

**Issue by tbandrowsky** [Microsoft/cppwinrt#185]
WinRT / CPP is rather amazing.  Does it support Direct2d?  Or, rather, is Direct2d the recommended API to use for immediate mode graphics?

Thanks!

**Comment by kennykerr** [comment]
Thanks! Yes, Direct2D does work with C++/WinRT.

**Comment by walbourn** [comment]
Direct2D/DirectWrite, Direct3D, etc. are COM-based APIs, not Windows Runtime APIs, so they work the same with C++/CX or C++/WinRT.

If you are using [Win2D](https://github.com/Microsoft/Win2D) which is a Windows Runtime wrapper for Direct2D/DirectWrite, then you'll need to get C++/WinRT projection headers to use it.

**Comment by tbandrowsky** [comment]
Are there C++/WinRT project headers out there for Win2d?  I've googled and haven't found.  I missed the DirectX stuff not being part of the Windows Runtime proper and I must admit part of this is my own unfamiliarity with it.  Like, I was kinda hoping I could go old school and write something in normal C++ and just draw a few lines on screen.  The Blocks demo gets you to CoreWindow and application and coupled with Kenny's other article about using Direct2d via WRL, might not be all that bad.

**Comment by BrentRe** [comment]
Currently, there are no C++/WinRT headers for Win2D. However, with the next release, you will be able to generate them.
