### ISSUE TITLE
What is the plan regarding C++ modules?

### ISSUE THREAD

**Issue by DBJDBJ** [Microsoft/cppwinrt#188]
Or the "roadmap" for the lack of the better word.

Thanks ...

**Comment by kennykerr** [comment]
That's largely up to the C++ standards committee. Modules didn't make it into C++17, making it harder for us to support it in general. We will likely provide experimental support in a future update, as it is provides clear benefits for C++/WinRT.

**Comment by DBJDBJ** [comment]
@kennykerr  And clear benefits to "everything and everybody" else. The famous on-line to consider:

import windows; //  instead of #include "windows.h"

I can only imagine the "interesting" challenges one can have, when planning the cppwinrt roadmap. Thanks for the CppWinRT and keep up a good work.

Kind regards ...

**Comment by DBJDBJ** [comment]
closed
