### ISSUE TITLE
Using IBuffer without allocating extra memory

### ISSUE THREAD

**Issue by yperaltag** [Microsoft/cppwinrt#189]
hi guys, I'm trying to read the contents of a file but I'm not familiar with `IBuffer`, I prefer using a pointer to `char`, so my doubt is how can I do something like this:
```cpp
std::ifstream stream(MyFilePathname);
stream.read(MyMemoryAddressCastedToChar, MyMemorySizeInBytes);
```
using the `FileOpenPicker` in this library? I've started coding but I'm stuck in the last line:
```cpp
FileOpenPicker picker;
picker.FileTypeFilter().Append(L"*");
auto file = co_await picker.PickSingleFileAsync();
auto stream = co_await file.OpenSequentialReadAsync();

co_await stream.ReadAsync(IBufferWithMyMemoryAddress, MyMemorySizeInBytes, Partial); //this is where I need help
```
To be more precise what I want is to create an `IBuffer` instance without allocating more memory, I want to use `MyMemoryAddress` as the internal pointer of the `IBuffer` instance, so after the call to `ReadAsync` I'll be able to forget about the `IBuffer` instance and keep working with `MyMemoryAddress`.

**Comment by BrentRe** [comment]
You'll need to create your own custom IBuffer implementation that provide the extra support of encapsulating a user provided backing store. 

There's not one provided for you in the Windows Runtime because there's no raw byte/char pointer type in the Windows Runtime type system.

**Comment by DefaultRyan** [comment]
There's another option that's available if you're willing to step slightly outside of the Windows Runtime. According to [https://msdn.microsoft.com/en-us/library/hh846267(v=vs.85).aspx](url), IBuffer implementations also implement IBufferByteAccess. This interface isn't in the Windows Runtime API surface, but it's just another COM interface, so it's compatible with winrt::com_ptr and as<I>() methods.

    #include <robuffer.h>
    StorageFile file = /* your code */;
    IBuffer buffer = co_await FileIO::ReadByfferAsync(file);
    auto byteAccess = buffer.as<::Windows::Storage::Streams::IBufferByteAccess();
    byte* data = nullptr;
    check_hresult(byteAccess->Buffer(&data);

**Comment by yperaltag** [comment]
thanks @BrentRe, I have no problem to have my own implementation but I don't know how to do it, I can do this:
```cpp
class MyBuffer : public IBuffer
{
  public:
    MyBuffer(void *address, uint size) : m_address(address), m_size(size), m_count(0) {}
    uint Capacity() { return m_size; }
    uint Length() { return m_count; }
    void Length(uint lenght) { m_count = length; }
  private:
    void *m_address;
    uint m_size;
    uint m_count;
};
```
just reimplementing the `IBuffer` interface got from here https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.ibuffer but how do I return the real address? ie that interface only deals with capacity and length.

thanks @DefaultRyan too, but I don't want the underlaying implementation to use its own buffers and later will copy the contents to mine, I want the underlaying implementation to use mine, so no more memory allocation be done, just for efficiency stuff. Besides your link is redirecting me to this https://github.com/Microsoft/cppwinrt/issues/url which is a blank page.

**Comment by BrentRe** [comment]
See our IBuffer sample code for demonstrating *use* of IBuffer.

We don't have a sample demonstrating implementation of IBuffer as we prefer folks use the system implementation. But in your case, you need a custom implementation

All IBuffer implementations must implement IBuffer plus the COM interfaces IBufferByteAccess (which returns the buffer address), IAgileObject (a marker interface), and IMarshal (to marshal by value). You may be able to fail cross-process marshals (depending on your scenario) which makes implementing IMarshal relatively trivial.

**Comment by yperaltag** [comment]
hey @BrentRe I think that seems too much complicated just for doing something trivial, I wonder if there is a simple way in windows runtime to reuse my memory address instead of allocating more memory.

**Comment by BrentRe** [comment]
No, there isn't. You'll have to use Win32 APIs otherwise. But using them may be a problem if you submit the app to the Store.

**Comment by yperaltag** [comment]
yeap, I want to be able to submit my appx to the store, so no win32 api. This is too frustrating because since the beginning of times using C language that can be done, and now using a modern windows runtime programming it can not. Might you guide me where can I find info for implementing the `IBuffer` interface, I didn't understand what you told me about 

> COM interfaces IBufferByteAccess (which returns the buffer address), IAgileObject (a marker interface), and IMarshal (to marshal by value). You may be able to fail cross-process marshals (depending on your scenario) which makes implementing IMarshal relatively trivial.

**Comment by kennykerr** [comment]
I'm not sure what you're after. If you want to use the `FileOpenPicker` but not the resulting `StorageFile` then you can always ask the `StorageFile` for the file's path via the `Path` property. You can then use that to open a memory mapped file or use some other API for reading the file. Many traditional file I/O APIs are now supported in store app submissions.

**Comment by yperaltag** [comment]
hi @kennykerr let me explain you better what I want, I do want to use the resulting `StorageFile` from the `FileOpenPicker` but I don't want to allocate more memory when reading the contents of this file, instead what I want is to reuse a memory I already have allocated. I'm not sure if now I'm clear. About this

> Many traditional file I/O APIs are now supported in store app submissions.

do you mean that if I use the `file` struct from your **AsyncReader** example, the following way:
```cpp
FileOpenPicker picker;
picker.FileTypeFilter().Append(L"*");
auto myFile = co_await picker.PickSingleFileAsync();

file reader(myFile.Path());
co_await reader.read(0, MyMemoryAddress, MyMemorySizeInBytes)
```
will my appx be accepted in a windows store submission?

**Comment by kennykerr** [comment]
Most of the main Win32 I/O functions like `ReadFile` are now supported in store apps. I think you might need to use `CreateFile2` rather than `CreateFile` and `CreateFileMappingFromApp` rather than `CreateFileMapping` but there should be a way forward. If you're looking for the best possible performance then that's probably your best bet, but it is a bit more work.

If you just need a simple in-process `IBuffer` implementation where you can control the allocation yourself then you can implement it with C++/WinRT as follows:

```C++
struct __declspec(uuid("905a0fef-bc53-11df-8c49-001e4fc686da")) IBufferByteAccess : ::IUnknown
{
    virtual HRESULT __stdcall Buffer(uint8_t** value) = 0;
};

struct CustomBuffer : implements<CustomBuffer, IBuffer, IBufferByteAccess>
{
    std::vector<uint8_t> m_buffer;
    uint32_t m_length{};

    CustomBuffer(uint32_t size) :
        m_buffer(size)
    {
    }

    uint32_t Capacity() const
    {
        return m_buffer.size();
    }

    uint32_t Length() const
    {
        return m_length;
    }

    void Length(uint32_t value)
    {
        if (value > m_buffer.size())
        {
            throw hresult_invalid_argument();
        }

        m_length = value;
    }

    HRESULT __stdcall Buffer(uint8_t** value) final
    {
        *value = m_buffer.data();
        return S_OK;
    }
};
```

And you might use it as follows:

```C++
StorageFile file = ...

IRandomAccessStream stream = co_await file.OpenAsync(FileAccessMode::Read);

IBuffer buffer = make<CustomBuffer>(100);

co_await stream.ReadAsync(buffer, buffer.Capacity(), InputStreamOptions::None);

com_ptr<IBufferByteAccess> byte_access = buffer.as<IBufferByteAccess>();
uint8_t* bytes{};
byte_access->Buffer(&bytes);

WINRT_TRACE("%.*s", buffer.Length(), bytes);
```

Hope that helps.

**Comment by andrew7webb** [comment]
This might help:

IBuffer CxCrypto::toIBuff(const std::vector<unsigned char> & vuc)
{
	using namespace Windows::Security::Cryptography;		// For CryptographicBuffer
	return CryptographicBuffer::CreateFromByteArray(vuc);
}

**Comment by yperaltag** [comment]
thanks @kennykerr very very much, your `CustomBuffer` class is not what I'm looking for but it was easy for me to adapt it to my needs, this is the class I was looking for:
```cpp
struct __declspec(uuid("905a0fef-bc53-11df-8c49-001e4fc686da")) IBufferByteAccess : ::IUnknown
{
    virtual HRESULT __stdcall Buffer(void** value) = 0;
};

struct CustomBuffer : implements<CustomBuffer, IBuffer, IBufferByteAccess>
{
    void *m_address;
    uint32_t m_capacity;
    uint32_t m_length;

    CustomBuffer(void *address, uint32_t capacity) : m_address(address), m_capacity(capacity), m_length(0) { }
    uint32_t Capacity() const { return m_capacity; }
    uint32_t Length() const { return m_length; }
    void Length(uint32_t length) { m_length = length; }

    HRESULT __stdcall Buffer(void** value) final
    {
        *value = m_address;
        return S_OK;
    }
};
```
so I can use it this way:
```cpp
StorageFile file = ...
auto stream = co_await file.OpenSequentialReadAsync();
CustomBuffer buffer(MyMemoryAddress, MyMemorySizeInBytes);
co_await stream.ReadAsync(buffer, buffer.Capacity(), InputStreamOptions::None);
auto bytes_read = buffer.Length();

//here I can forget about buffer because the bytes read are in MyMemoryAddress, THIS IS WHAT I WAS AFTER
```
Although here there are some things I don't understand, but I'll open another thread for that because I think this should be closed, so thanks again very very much.

**Comment by yperaltag** [comment]
thanks @andrew7webb, after reading your comment I was doing some tests to see if I could use the `CreateFromByteArray` method to avoid implementing my custom buffer but unfortunately I couldn't because it allocates more memory instead of using mine.
```cpp
array_view<const uint8_t> temp(MyMemoryAddressCastedToUint8, MyMemoryAddressCastedToUint8 + MyMemorySizeInBytes);
auto buffer = CryptographicBuffer::CreateFromByteArray(temp);

com_ptr<IBufferByteAccess> byte_access = buffer.as<IBufferByteAccess>(); //this is the same IBufferByteAccess struct from previous comments.
uint8_t* bytes{};
byte_access->Buffer(&bytes);

assert(bytes == MyMemoryAddressCastedToUint8); //FAILED
```
