### ISSUE TITLE
C++/WinRT book?

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#190]
Looking beyond this fine website, are there any plans for a (Kerr?/Petzold/Rector/Richter) book?

**Comment by DBJDBJ** [comment]
What is this, now you want the book ?! 👍 🥇 
I thought I am [the cheeky one](https://github.com/Microsoft/cppwinrt/issues/186) ...

**Comment by kennykerr** [comment]
It's harder and harder to justify the time commitment to write a technical book these days, but I plan to author a [Pluralsight course](https://www.pluralsight.com/authors/kenny-kerr) on C++/WinRT.

**Comment by MRahilly** [comment]
Many thanks Kenny

**Comment by Musenginst** [comment]
A book would be great! I haven't had too much of a chance to use it myself, but I hope that C++/WinRT will get the traction it deserves!

**Comment by wooowchik** [comment]
So,where is the book?
