### ISSUE TITLE
coroutine can not catch exception!

### ISSUE THREAD

**Issue by Azhang74** [Microsoft/cppwinrt#192]
I write this C++/CX function:
task<void> App::ReadConfigFromXml(Platform::String^ FileName)
{
	try
	{

		StorageFolder^ folder = Windows::Storage::ApplicationData::Current->LocalFolder;
		auto  CurrentData = co_await folder->GetFileAsync(FileName);

		if (CurrentData == nullptr)
			return;
		auto text = co_await FileIO::ReadTextAsync(CurrentData);
		if (text == nullptr)
			return;
		XmlDocument^ document = ref new XmlDocument();
		document->LoadXml(text);
	}
	catch (COMException^ e)
	{
		String ^str = e->Message;
	}
	catch (std::exception e)
	{
		e.what();
	}
	catch (...)
	{
		;
	}
}
When I run this function ,I get this message    Exception thrown at 0x00007FFE98DA9E08 in iPDA.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x000000BB78BFD7B0. HRESULT:0x80070002 System can not find the File。
WinRT information: System can not find the File。

  I can not  catch this exception at all!  why?  please help me ! thank you!!

**Comment by bigdimboom** [comment]
Read "Mapping C++/CX Platform types to C++/WinRT types" in Docs. It helped me before. I had the same issue before.
