### ISSUE TITLE
hresult_error::message occurs  asserttion error when debug build

### ISSUE THREAD

**Issue by hdmyt** [Microsoft/cppwinrt#193]
The error message is shown below.

> File: minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp
> Line: 36
> 
> Expression: c >= -1 && c <= 255
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts.

winrt/base.h (10.0.15063.0 line:1467)
```
    inline hstring trim_hresult_message(const wchar_t * const message, uint32_t size) noexcept
    {
        const wchar_t * back = message + size - 1;

        while (size && isspace(*back))
        {
            --size;
            --back;
        }

        hstring result;
        WindowsCreateString(message, size, put_abi(result));
        return result;
    }
```
In Japanese environment, the error message has Japanese character, so "*back" is over 255.

_message_ is "プロセスにパッケージ ID がありません。\r\n".
_back_ is "。\r\n".

**Comment by kennykerr** [comment]
Thanks for reporting this issue. The `trim_hresult_message` function should be using `iswspace` rather than `isspace`.
