### ISSUE TITLE
CoreDispatcherPriority::Idle

### ISSUE THREAD

**Issue by neonxc** [Microsoft/cppwinrt#194]
Hi,
I've encountered an error using this enum value as an argument to Dispatcher::RunAsync method.

Using latest cppwinrt for Win 10.0.14393 and VS2017.2. This code always throws. Is that defined behaviour?

`dispatcher.RunAsync(CoreDispatcherPriority::Idle,
      [=]()
    {
    });`

Thanks for looking into it and great work overall.

**Comment by kennykerr** [comment]
This is not specific to C++/WinRT. The `RunAsync` method does not support the `CoreDispatcherPriority::Idle` value. Only `Low`, `Normal` and `High` are supported. Any other value will result in an `hresult_invalid_argument` exception.

**Comment by neonxc** [comment]
Oh I see it now. Sorry for false alarm.
