### ISSUE TITLE
GetFolderAsync & GetFileAsync error handling problem

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#196]
These methods do not return a null if they encounter an error. I have a coroutine that is called by an XAML button click handler. This coroutine contains both of these methods. When an error occurs try/catch does not work instead the behavior is as if the handler had completed bypassing any recovery code.

In the future, will these methods be changed to return a null ?

**Comment by kennykerr** [comment]
These methods throw an exception on failure. You can catch the exception within the coroutine as follows:

```C++
StorageFolder folder = KnownFolders::DocumentsLibrary();

try
{
    StorageFile file = co_await folder.GetFileAsync(L"filename.txt");
}
catch (hresult_error const& e)
{
    WINRT_TRACE("%ls\n", e.message().c_str());
    throw;
}
```

**Comment by JackDetrick** [comment]
I'm using 
catch (hresult_error const & e)
in the try/catch.
Could the problem be that it's in button click handler ?

**Comment by kennykerr** [comment]
That shouldn't be an issue.

**Comment by JackDetrick** [comment]
The plot thickens...
I'm using a copy of iBuffer for my test code. I created a new method that includes my test code. I call this method in wWinMain before Application::Start,,, The try/catch in this new method (with my code) WORKS  as advertised. 
But that doesn't solve my problem because I need it in an XAML button click.

**Comment by JackDetrick** [comment]
Ah, there is a difference!!!
My problem coroutine, that is in the button click.  contains 3 parameters. Each of which is a class being passed by reference.. These classes are not referenced until AFTER the get folder and get file. My initial tests indicate that files reads are able to update these classes.  
The problem appears to be that the mere presence of such parameters causes any try/catch to fail.

My workaround is 2 coroutines; 1 with no parameters  that checks are corrects missing  folders and files and a second with parameters. which update the classses.

**Comment by kennykerr** [comment]
You should avoid reference parameters on coroutines involving suspension points (async calls).

**Comment by JackDetrick** [comment]
The purpose of my coroutine is to replicate my C#  UWP App's deserialization method. This method is called only in the app class's constructor and app class  OnLaunched method. This is occurs while the app;s logo is displaying and prior to the call rootFrame.Navigate(typeof(MainPage), e.Arguments);..
That being said, is it safe to use reference parameters or should I use out parameters.
In any case what is the proper way to handle serialization and  deserialization in a C++/winRT app? (stay  with C# is not an option).

**Comment by JackDetrick** [comment]
I'm closing this and will attempt to use global classes instead. If that doesn't work I create a new issue._
