### ISSUE TITLE
 GetFolderAsync & GetFileAsync error handling issue

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#197]
I'm using GetFolderAsync & GetFileAsync to perform application serialization and deserialization. The related coroutines require the use on non local data for storage and retrieval. 
From my testing there appears no problem in reading/updating this non local data except when there is a missing file or folder. I use try/catch for GetFolderAsync and GetFileAsync., In that case the try does a throw but my catch is not called. If I remove all reference to non local data the try/catch works OK.
I'm attempting to replicate my C# UWP app's serialization and deserialization. There they are called in application startup and shutdown. For startup deserialization is called prior to the call to navigate to the mainpage.
My workaround is to use two coroutines in the deserializaton process. One (with only local data) will use the try/catch to create missing folders or files. The second will use non-local data to complete the deserialization.

Is there a better way? I feel uncomfortable with this approach.

**Comment by kennykerr** [comment]
Can you share a minimal standalone repro?

**Comment by JackDetrick** [comment]
Can do,,,

**Comment by JackDetrick** [comment]
Just installed Visual Studio Community 2017 Preview, Version 15.3 and problem still exists.

**Comment by BrentRe** [comment]
Once we have the minimal standalone repro, we'll investigate...

**Comment by JackDetrick** [comment]
Hi Brent –



Make a copy of IBuffer. The attached zip file has 5 files,  add them to iBuffer. There are 2 classes and a replacement for App.cpp.  Add cppwinrt to the project properties. It should compile…



Set 3 break points

            DataBase::ReadDataBase

                        36 try

                        39 catch

            App.cpp  ClickHandler


                        89 – just after the call to ReadDataBase



If you run the app you will only stop at break point line 36



If you remove lines 65 & 66 of ReadDataBase and run the app, it will stop at all 3 break points.

You will also see a returned value of -1 and it you select continue  after the App break point and file picker will be displayed.



If this does not fail then I can take hope that  the problem is of my own making.  When I discover it I’ll let you know



Thanks again



Jack D


________________________________

**Comment by BrentRe** [comment]
Sorry for the delay. I started to look into this but there is no attachment so I don't know how to repro the issue.

**Comment by JackDetrick** [comment]
Lets see if this works

________________________________

**Comment by JackDetrick** [comment]
[Repro_197.zip](https://github.com/Microsoft/cppwinrt/files/1075801/Repro_197.zip)

**Comment by BrentRe** [comment]
I still don't see an attachment. Are you attaching this by dragging and dropping them into the edit window here? Or by clicking the "selecting them" highlight text at the bottom of the edit window?

**Comment by BrentRe** [comment]
Never mind. I see the response with them now! Thanks.

**Comment by JackDetrick** [comment]
Today (8/22/2017} I downloaded VS 15.3.1 and guess what--- this problem has been resolved.
Thanks again to all of the staff
