### ISSUE TITLE
SDK Version Directory in Repo

### ISSUE THREAD

**Issue by joewood** [Microsoft/cppwinrt#2]
Just a question about the repo structure. Is the intention to have multiple SDK versions supported in the single repo, sitting parallel to the `10.0.14393.0` dir? If not, wouldn't a tagged release be a more traditional approach?

**Comment by kennykerr** [comment]
Yes, the layout is intended to support multiple projections targeting different SDKs or builds. Newer commits will also have the C++/WinRT compiler's version stamped into the headers. You can see the version number [at the top of each header](https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/winrt/base.h).

**Comment by BrentRe** [comment]
Our thinking is that a developer may want a set of headers for a particular SDK release. And there will be multiple SDK releases supported at any given time. As we find and fix a bug, or add new features to the header code gen tooling, we'll want to regenerate the set of headers for each release.

**Comment by joewood** [comment]
Yup, makes sense, I guess - at least to support multiple OS version builds. Assuming the headers are pretty much mutually exclusive for a build), and as you suggest, you could have multiple binary builds, each would have a different include path. 

My only suggestion would be to make that more explicit, with maybe have a "current version" dir. And is it necessary to include the samples for each version? 

Generally speaking, isn't it better practice to support a single binary with progressive functionality that lights up with newer builds?
