### ISSUE TITLE
The 10.0.14393.0 link has an incorrect label

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#200]
Surely this should read "Anniversary Update" not "Creators Update"?

**Comment by walbourn** [comment]
Which 'link' in particular are you referring to?

**Comment by VSChawathe** [comment]
It's the commit message if I am not mistaken. Eg. Visit https://github.com/Microsoft/cppwinrt/tree/master/10.0.14393.0/Samples The Creators Update commit message is shown only for items last updated when the commit made that last updated those items was with the git commit message Creators Update.

**Comment by MRahilly** [comment]
https://github.com/microsoft/cppwinrt
The descriptive string (beside 10.0.14393.0) should read "Anniversary Update" i.e. what it is or, at least, what it was?

**Comment by tim-weis** [comment]
@Mrahilly: The text you are referring to is the **commit message** of the last commit that made changes to this object. The message is correct. You need to adjust your expectations. This is not a description of the folder contents.

**Comment by VSChawathe** [comment]
@MRahilly The message is for the commit shown by last column as "2 months ago". Maybe this issue should be redirected at GitHub to let users choose skins to get greater clarity.
