### ISSUE TITLE
why can't I use my custom type in IAsyncOperation<T>

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#201]
I'm having an issue of that IAsyncOperation does not support my custom type.
 It does support all primitive types. How do I make it support my own type/class?
![image](https://cloud.githubusercontent.com/assets/6119906/26416727/df72ca12-4084-11e7-8ca8-6b278eb46041.png)

How do i provide my own UUID? Can you post an example.

**Comment by kennykerr** [comment]
There are various ways to figure out what the GUID should be but its non-trivial and we've fixed this in the next major update where C++/WinRT will compute this automatically. For now you can [look at this example](https://github.com/Microsoft/cppwinrt/blob/master/10.0.15063.0/Samples/JustCoroutines/Main.cpp).
