### ISSUE TITLE
Namespace for Atomic Objects in WinRT

### ISSUE THREAD

**Issue by IkoLogs** [Microsoft/cppwinrt#202]
I am trying to find out how to access API such as Interlocked functions and semaphores etc, but not sure what namespace to go for this under winrt.

tried  winrt::windows::foundation   winrt::windows::system   but no luck
was expecting to find Threading under system, but no such thing.
winrt::Windows::System:: (no threading name space)

could you pls point me to namespace under winrt:: where i can get access to atomic objects.

The  UWP documentation uses these API in examples but the link goes to .Net API.

Any direction much appreciated

**Comment by kennykerr** [comment]
It sounds like you're looking for the [C++ standard library](http://en.cppreference.com/w/cpp). 

Check out the "Atomic operations library" and the "Thread support library" pages.

**Comment by IkoLogs** [comment]
Hi Kenny

Thanks for the quick reply, C++ standard library. is my backup plan to solve this problem.

But i used to use under win32/wince these
https://msdn.microsoft.com/en-us/library/aa911383.aspx

I see them being used in UWP examples (search the page for interlocked)
https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-media-frames-with-mediaframereader

But i cannot find any or similar API under winrt namespace tree.
Like you mentioned if all else fails i will fall back to C++ STD .

The API am looking for should be in same namespace as semaphore if that still exists under winrt
I am using winrt for IoT  some of these type API are quite critical fore my project.

Thanks again

**Comment by BrentRe** [comment]
InterlockedIncrement et all are Win32 APIs, not Windows Runtime APIs. Simply use them as you would from any C++ app - include winbase.h and call them. Or, as Kenny mentioned, use the standard C++ library types with equivalent functionality.

**Comment by IkoLogs** [comment]
Thank you very much gents much appreciated i was looking for 2 options to compare, got what i wanted cheers.
