### ISSUE TITLE
unresolved external symbol winrt::Windows::Globalization::impl_ILanguage

### ISSUE THREAD

**Issue by peter8179** [Microsoft/cppwinrt#208]
Hi cppwinrt expert,

i use cppwinrt\10.0.14393.0 in VS2015, and in the source code try to print the info with following code:

winrt::Windows::Globalization::Language& lang = vl.GetAt(i);
printf("i=%d, tag=%ws, disp=%ws, native=%ws\n",
i, lang.LanguageTag().c_str(), lang.DisplayName().c_str(), lang.NativeName().c_str());

The compile is ok, but when link i got the errors:

error LNK2001: unresolved external symbol "public: struct winrt::hstring __cdecl winrt::Windows::Globalization::impl_ILanguage::NativeName(void)const "
error LNK2001: unresolved external symbol "public: struct winrt::hstring __cdecl winrt::Windows::Globalization::impl_ILanguage::DisplayName(void)const "
error LNK2001: unresolved external symbol "public: struct winrt::hstring __cdecl winrt::Windows::Globalization::impl_ILanguage::LanguageTag(void)const "

please help, i link with the windowsapp.lib, but these symbols not in this lib?

**Comment by spumoni1201** [comment]
Have you verified that you explicitly include winrt/Windows.Globalization.h? You may be getting forward declares of objects in the winrt::Windows::Globalization namespace from another namespace. If you invoke methods on objects that are not fully defined, you can run into these types of errors.

**Comment by BrentRe** [comment]
Correct. The omission of #include "winrt/Windows.Globalization.h" is the problem here. I also responded to the same issue raised on the Windows-universal-samples GitHub.

**Comment by peter8179** [comment]
thank you experts so much. After include the header, It just works.
it's implemented in the header, i'm stupid to search the symbols in the lib files,~~!
