### ISSUE TITLE
How to: Extract a string from a Button Context

### ISSUE THREAD

**Issue by andrew7webb** [Microsoft/cppwinrt#21]
void myButtonClick(winrt::Windows::IInspectable const & sender, const Windows::UI::Xaml::RoutedEventArgs & args )
	{
		Button sendButton = sender.as<Button>();
		auto senderContent = sendButton.Content().as< SomeTypeIGuess >(); 
                                     // What type can I use to get the Context from a Button?

		textBlock.Text(L"Method hit");
	}

I was wondering how I can use the passed parameters for a button click.   I made some progress to get the Button from the sender, but how do I get the Button's Content as a string of some sort?

**Comment by geminik23** [comment]
It depends on what did you set on Content property. 
 If you did set TextBlock on Content

``` C++
    Button button;
    TextBlock btnTxt; 
    btnTxt.Text(L"Button");
    button.Content(btnTxt);    
````

then

```C++
void myButtonClick(winrt::Windows::IInspectable const & sender, winrt::Windows::UI::Xaml::RoutedEventArgs const & args )
{
    Button sendButton = sender.as<Button>();
    auto senderContent= sendButton.Content().as<TextBlock>(); 
    // change 
    senderContent .Text(L"Method hit");
}
```

**Comment by andrew7webb** [comment]
Hmm, I think I set a hstring_ref when I did this code:

`	void myButtonClick(winrt::Windows::IInspectable const & sender, const Windows::UI::Xaml::RoutedEventArgs & args )
	{
		Button sendButton = sender.as<Button>();
		auto senderContent = sendButton.Content().as< hstring_ref >();  // What type can I use to get the Context from a Button?

		textBlock.Text(L"Method hit");	
		UNREFERENCED_PARAMETER(args);
	}

	void setButtonContent(Button & button, const std::wstring & text )
	{
		Windows::IInspectable value = PropertyValue::CreateString(text);
		button.Content(value);
	}

	void OnLaunched(LaunchActivatedEventArgs const &)
	{
		textBlock.Text(L"hello world");
		myStyle(textBlock);

		setButtonContent(buttonM, L"Click method button");
		myButtonStyle(buttonM);
		buttonM.Click({ this, &HelloGui::myButtonClick });
		
		setButtonContent(buttonM2, L"Click method 2");
		myButtonStyle(buttonM2);
		buttonM2.Click({ this, &HelloGui::myButtonClick });
etc`

But I get these errors on
1>c:\users\andrew\downloads\cppwinrt-master\cppwinrt-master\10.0.14393.0\winrt\internal\../base.h(2361): error C2787: 'winrt::hstring_ref': no GUID has been associated with this object

1>  AndrewApp.cpp(50): note: see reference to function template instantiation 'auto winrt::Windows::IUnknown::as<winrt::hstring_ref>(void) const' being compiled
=

**Comment by kennykerr** [comment]
You cannot assign text directly to `Button.Content` since it expects an object (`IInspectable`). You might assign it an `IPropertyValue` containing text or a `TextBlock`. Either way, the `Content` property can be cast to the original type assigned to that property via the `as` method. The `as` method is backed by `QueryInterface` so it will only allow you to query for interfaces (e.g. `IPropertyValue`) or runtime classes (e.g. `TextBlock`). You cannot use it to query for `hstring` or `hstring_ref` since those are not COM objects.

**Comment by andrew7webb** [comment]
void myButtonClick(
	winrt::Windows::IInspectable const & sender,
	const Windows::UI::Xaml::RoutedEventArgs & args )
{
	Button sendButton = sender.as<Button>();
	IPropertyValue senderContent = sendButton.Content().as< IPropertyValue >();
	hstring hstr= senderContent.GetString();
	std::wstring wstr = hstr;
	textBlock.Text( wstr );  // L"Method hit"
	UNREFERENCED_PARAMETER(args);
}


Thanks, that worked when I set the button Content this way:
void setButtonContent(Button & button, const std::wstring & text )
{
    Windows::IInspectable value = PropertyValue::CreateString(text);
    button.Content(value);
}
