### ISSUE TITLE
MapControl constructor null reference exception:

### ISSUE THREAD

**Issue by tbandrowsky** [Microsoft/cppwinrt#210]
Trying to construct a map control crashes with a null reference exception

inline MapControl::MapControl() :
    MapControl(activate_instance<MapControl>())
{}

Exception thrown at 0x503535AE (JpMapControl.dll) in SiteRisq.exe: 0xC0000005: Access violation reading location 0x00000000.

template <typename Class, typename Instance = Class>
Instance activate_instance()
{
    return get_activation_factory<Class>().ActivateInstance().template as<Instance>();
}

**Comment by kennykerr** [comment]
I can't reproduce this. Let us know if you have more information on this issue.
