### ISSUE TITLE
No mapping of free functions like CreateDirect3DSurface?

### ISSUE THREAD

**Issue by digimatic** [Microsoft/cppwinrt#211]
I cannot find any way to invoke CreateDirect3DSurface from my C++/WinRT code. 
If I try to include Windows.Graphics.DirectX.Direct3D11.interop.h and enabled /ZW it seems to conflict. 
It would be nice if C++/WinRT had som mapping for those functions.

**Comment by DefaultRyan** [comment]
C++/WinRT only maps to types in the WinRT type system, and the associated .winmd files. If you want to call non-WinRT functions like the one you describe, you should be able to do so like any other function, and you can get the usual C++/WinRT exception behavior by wrapping that call in winrt::check_result().

What sort of conflict are you seeing?

**Comment by Scottj1s** [comment]
Consider calling the WRL-compatible CreateDirect3D11SurfaceFromDXGISurface instead, and wrapping with winrt::check_result() as Ryan suggests.

**Comment by digimatic** [comment]
Yes I saw that the implementation of CreateDirect3DSurface used CreateDirect3D11SurfaceFromDXGISurface so that was how I managed to solve it.
Thanks for your answers.
