### ISSUE TITLE
I installed cppwinrt wih vcpkg and cannot run XamlCode sample!

### ISSUE THREAD

**Issue by juandent** [Microsoft/cppwinrt#212]
Hi,
I have vcpkg installed and working. I installed cppwinrt for three targets: x86-windows, x64-windows, x64-uwp.
Trying to debug the sample called XamlCode.sln, it starts to Deploy and stays there forever... What am I missing? Am I perhaps missing XAML in my system? If so, how can I get it?
(BTW, other cppwinrt samples debug correctly)
Regards,
Juan Dent

**Comment by Scottj1s** [comment]
Hi Juan, 
You might try running a repair on VS, or running VS as admin.  You could also troubleshoot deployment issues by inspecting the event log (details [here](https://msdn.microsoft.com/en-us/library/windows/desktop/hh973484(v=vs.85).aspx)), or by publishing to a local appx and deploying manually via the powershell add-appxpackage cmdlet.  If none of these help, I would encourage you to direct your question to a VS support forum.
Best,
Scott Jones

**Comment by yeboahgyan** [comment]
Hi Juan,

Could it be your Visual Studio Solution Platform option (drop-down box near the green play button) for the project is currently set to ARM?

**Comment by juandent** [comment]
Yes you were right. Yet now I have a different error:
To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.15063.0 or higher. You currently are running version 10.0.10586.962. Please update your OS, or change your deployment target to a device with the appropriate version

How do I solve this?
Juan

**Comment by yeboahgyan** [comment]
Hi Juan,
Try changing the Target Platform Min. Version to 10.0.10586.0 from the project Property Pages
(right-click the project and select Properties).
Regards,
Kwame

**Comment by juandent** [comment]
Hi,
I don't have 10.0.10586.0  sdk installed and I downloaded the latest sdk (higher than 10.0.15063.0 ) but it does not appear as an option in Target Platform Min. Version or Target Platform Version...
It seems like my machine MUST be running that latest SDK instead of just having it.. But how do I tell Windows to use this later SDK??

Regards,
Juan
