### ISSUE TITLE
help with unresolved external

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/cppwinrt#214]
Do we know why Case1 and Case3 fails

std::future<void> fromResourceCandidate(winrt::ResourceCandidate& rc)
{
	auto str = co_await rc.GetValueAsStreamAsync();

	// Case 1: Fails
	auto sz = str.Size();

	// Case 2: Succcessful.
	uint64_t sz2;
	winrt::check_hresult(winrt::get_abi(str)->get_Size(&sz2));

	// Case 3: Fails
	winrt::Buffer buffer((uint32_t)sz2);

	/*
	var buffer = new Windows.Storage.Streams.Buffer((uint)str.Size);

	var bytesBuffer = await str.ReadAsync(buffer, (uint)str.Size, Windows.Storage.Streams.InputStreamOptions.None);
	var bytes = bytesBuffer.ToArray();
	var utf = Encoding.UTF8.GetString(bytes);
	*/
}

// Case 1 - Error message
 unresolved external symbol "public: unsigned __int64 __cdecl winrt::Windows::Storage::Streams::impl_IRandomAccessStream<struct winrt::Windows::Storage::Streams::IRandomAccessStream>::Size(void)const 

// Case 3 - Error message
unresolved external symbol "public: __cdecl winrt::Windows::Storage::Streams::Buffer::Buffer(unsigned int)

**Comment by BrentRe** [comment]
You are using types from the Windows.Storage.Streams namespace but haven't included the header to define those types.

Add
#include "winrt/Windows.Storage.Streams.h"

**Comment by mediabuff** [comment]
Great. Thank you for the quick reply.
