### ISSUE TITLE
Non-trivial GUI example

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/cppwinrt#215]
As there isn't an integration with VS studio (read  XAML designer) yet, could you add an example the builds a UI that is a little bit more complex, like having multiple UI elements  arranged in some grid or stackpanel that also automatically stretches to the whole window.

I tried to tranlate some of the UWP examples on the web, but that turned out to be all but trivial (at least for an inexperienced user like me). E.g. most examples either only show XAML code which I can't use or c# code, which apparently has access to some methods not available at cppwinrt. In both cases it is often not clear, what the equivalent cppwinrt syntax to a particular XAML / c# example would be, even if the respective functions are available.

**Comment by FeBrex** [comment]
Please have a look here: https://github.com/Microsoft/cppwinrt/issues/176

I plan to record a video on bindings this weekend.

**Comment by MikeGitb** [comment]
@FeBrex: I had a look at your solution and it is really handy. However, I am actually interested in how to compose the UI's programatically and as far as I understand your solution it leaves me with the same problem of the difference between the API used in the c# examples and the onw available via the cppwinrt library.

**Comment by DefaultRyan** [comment]
Could you list some of the APIs you're talking about? We project all the APIs present in the metadata, so if there's an issue, it's most likely a fundamental difference in the C++ Windows API surface area that has nothing to do with cppwinrt.

**Comment by MikeGitb** [comment]
Unfortunately I haven't documented my exact problems. One thing that comes to mind and was afaik already mentioned here somewhere was add vs append and I think I ran into problems once or twice due to the lack of properties in c++.

**Comment by MikeGitb** [comment]
Any updates on this? Do you need more information? Or is it just too low on your priority list?

**Comment by VikingExplorer** [comment]
I'll second MikeGitb's request. I'd like to see an example that combines regular controls like labels, combo boxes, text boxes, with some Composition visual functionality, like a rectangle that spins.

**Comment by Mr1Penguin** [comment]
Working example of bindings https://github.com/Mr1Penguin/cppwinrtbinding

**Comment by Mr1Penguin** [comment]
And spinning button using composition https://github.com/Mr1Penguin/cppwinrtcomposition

**Comment by rvinothrajendran** [comment]
Basic stack panel sample program.
  http://www.c-sharpcorner.com/article/learn-universal-windows-programming-via-modern-cpp-stackpanel/

**Comment by MikeGitb** [comment]
@rvinothrajendran: thanks, that was pretty much, what I was looking for. Can you also give an example using a gridlayout? If I remember correctly, this was where my trouble started. Also, what is the best way to create overlapping UI elements?

@Mr1Penguin: Thank you too. Your approach seems like the best one for professional use, but first I would like to get a feeling of how to compose (and manipulate) a UI programmatically.

**Comment by andrew7webb** [comment]
Continuing with Vinoth's article on stack panel, I have been using a menu of buttons in my experiments.
From a high level, each button starts a function.  The GUI namespace handles most of the plumbing: 

`#pragma once
#include "pch.h"

struct LabelHandler {
	hstring label;
	Windows::UI::Xaml::RoutedEventHandler handler;
};

namespace Gui
{
	// Add these labeled handlers as buttons to the stack panel
	void appendButtons(std::vector< LabelHandler > & menu, std::vector< Button > & buttons, StackPanel & stackPanel);


	void myBlockStyle(TextBlock & block);
	void myButtonStyle(Button & button);

	void setButtonContent(Button & button, const std::wstring & text);

	std::wstring getButtonContent(Button & button);

};
`
`#include "pch.h"

namespace Gui
{

// Add these labeled handlers as buttons to the stack panel
//
void appendButtons(std::vector< LabelHandler > & menu, std::vector< Button > & buttons, StackPanel & stackPanel )
{
	for (auto lh : menu) {
		buttons.push_back(Button());
		Gui::myButtonStyle(buttons.back());
		Gui::setButtonContent(buttons.back(), lh.label);
		buttons.back().Click(lh.handler);
		stackPanel.Children().Append(buttons.back());
	}
}

	void myBlockStyle(TextBlock & block)
	{
		block.FontFamily(FontFamily(L"Segoe UI Semibold"));
		block.FontSize(32.0);
		block.Foreground(SolidColorBrush(Colors::Orange()));
		block.VerticalAlignment(VerticalAlignment::Center);
		block.TextAlignment(TextAlignment::Center);
		block.TextWrapping(TextWrapping::Wrap);
	}


	void myButtonStyle(Button & button)
	{
		button.FontFamily(FontFamily(L"Segoe UI Semibold"));
		button.FontSize(36.0);
		button.Foreground(SolidColorBrush(Colors::DarkBlue()));
		button.VerticalAlignment(VerticalAlignment::Center);
		button.HorizontalContentAlignment(HorizontalAlignment::Left);
		button.MinWidth(350);
	}


	void setButtonContent(Button & button, const std::wstring & text)
	{
		Windows::IInspectable value = PropertyValue::CreateString(text); // std::wstring converted to hstring
		button.Content(value);
	}



	std::wstring getButtonContent(Button & button)
	{
		IPropertyValue senderContent = button.Content().as< IPropertyValue >();
		return senderContent.GetString();	// hstring converted to std::wstring
	}
}
`

So all I have to do is pass a vector of LabelHandler into appendButtons, and I get a menu of buttons.


class HelloGui : public ApplicationT<HelloGui>		// Or struct HelloGui : ApplicationT<HelloGui>
{
public:
	StackPanel stackPanel;
	TextBlock textBlock;
	std::vector< Button > buttons;

	void OnLaunched(LaunchActivatedEventArgs const &)
	{
		std::vector< LabelHandler > menu = {

		{ L"Write own content",
			[=](Windows::IInspectable const & sender, RoutedEventArgs const & args)
		{
			// How to use the event parameters
			// See https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.RoutedEventArgs
			try {
				Button sendButton = sender.as<Button>();
				textBlock.Text(Gui::getButtonContent(sendButton));
			}
			catch (winrt::hresult_error const & ex) {
				textBlock.Text(ex.message());
			}
		}
			},


		{ L"OCR from Image",
			[=](Windows::IInspectable const & sender, RoutedEventArgs const & args)
		{
			Ocr_ForegroundAsync(textBlock);   // Implement your own function here...
			UNREFERENCED_PARAMETER(sender);
			UNREFERENCED_PARAMETER(args);
		}
			},

		};



		textBlock.Text(L"Textblock fill");
		Gui::myBlockStyle(textBlock);

		stackPanel.HorizontalAlignment(Windows::UI::Xaml::HorizontalAlignment::Left);
		Gui::appendButtons(menu, buttons, stackPanel);
		stackPanel.Children().Append(textBlock);

		using namespace Windows::UI::ViewManagement;
		ApplicationView appView = ApplicationView::GetForCurrentView();
		appView.Title(L"Menu of buttons");

		Window window = Window::Current();
		window.Content(stackPanel);
		window.Activate();
	}

Hope this helps people trying to experiment without the XAML infrastructure.

**Comment by rvinothrajendran** [comment]
@mikegitb surely i will share the sample but I am on vacation , i will update on coming Friday , hope meantime you find the way or some folks will share it

**Comment by MikeGitb** [comment]
No worries I'm not on any project that uses einer. Just wanted to play around a bit.

**Comment by rvinothrajendran** [comment]
@mikeGitb please find the Grid sample application 
https://github.com/rvinothrajendran/CppuwpExample

**Comment by MikeGitb** [comment]
Thank you very much. Worked like a charm. I still think it would be nice, if examples like these would be added to the repo, but as far as I am concerned, this issue can be closed.

**Comment by rvinothrajendran** [comment]
@MikeGitb you're welcome

**Comment by VikingExplorer** [comment]
I haven't had time to look into them yet, but assuming that one of these examples shows how to mix 3D animations and regular controls, I'd like to also thank you very much.

**Comment by geolffrey** [comment]
What am I missing? I got a link error related to buttonbase:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: struct winrt::event_token __cdecl winrt::impl::consume_Windows_UI_Xaml_Controls_Primitives_IButtonBase<struct winrt::Windows::UI::Xaml::Controls::Button>::Click(struct winrt::Windows::UI::Xaml::RoutedEventHandler const &)const " 

I reviewed "pch.h" and all the headers are included, as far as my knowledge allows me to see.

#pragma once

#pragma comment(lib,"windowsapp")

#include <winrt\base.h>
#include <winrt\Windows.ApplicationModel.h>
#include <winrt\Windows.ApplicationModel.Activation.h>
#include <winrt\Windows.Foundation.h>
#include <winrt/Windows.UI.Xaml.Input.h>
#include <winrt\Windows.UI.Xaml.Controls.h>
#include <winrt\Windows.UI.Xaml.Media.h>
#include <winrt\Windows.Storage.Streams.h>
#include <winrt\Windows.Graphics.Imaging.h>
#include <winrt\Windows.Media.Ocr.h>
#include <winrt\Windows.Networking.h>
#include <winrt\Windows.UI.Popups.h>

Please help.

**Comment by rvinothrajendran** [comment]
Hi 
Please include #include "winrt/Windows.UI.Xaml.Controls.Primitives.h"
Thanks,
Vinoth

**Comment by geolffrey** [comment]
Perfect! Work wonderfully!

Thanks a lot.

Geolffrey.

**Comment by rvinothrajendran** [comment]
Thanks goes to @Scottj1s 👍
