### ISSUE TITLE
Reason for "Unresolved symbol winrt::Windows::UI::Xaml::Input::TappedEventHandler" ?

### ISSUE THREAD

**Issue by andrew7webb** [Microsoft/cppwinrt#22]
void myButtonTapped(
		winrt::Windows::IInspectable const & sender,
		const Windows::UI::Xaml::RoutedEventArgs & args)
	{
		textBlock.Text( L"Tapped" );
	}

	void OnLaunched(LaunchActivatedEventArgs const &)
	{
		buttonM.Tapped({ this, &HelloGui::myButtonTapped });
		// error LNK2019 : unresolved external symbol winrt::Windows::UI::Xaml::Input::TappedEventHandler::TappedEventHandler
		//  <class HelloGui,void (__cdecl HelloGui::*)(struct winrt::Windows::IInspectable const &,struct winrt::Windows::UI::Xaml::RoutedEventArgs const &)>
		// 
		// referenced in function HandleTapped(void)

I thought to try a button Tapped event handler instead of a Click.   It compiled, but did not link.

**Comment by ajorians** [comment]
Hi @andrew7webb ,

You need to add the include for `TappedEventHandler` which is what the `Tapped` method is taking.  So add:
```cpp
#include "winrt/Windows.UI.Xaml.Input.h"
```

Once you do that you'll have a compile error instead of a linking error.  But then change:
```cpp
buttonM.Tapped({ this, &HelloGui::myButtonTapped });
```
to:
```cpp
buttonM.Tapped({ &HelloGui::myButtonTapped });
```

And that worked for me! :smiley:

**Comment by andrew7webb** [comment]
The additional include helped the problem, but  because button was a class member in my code, I still needed to use 
buttonM.Tapped({ this, &HelloGui::myButtonTapped });

My declaration of buttonM....
class HelloGui : public ApplicationT<HelloGui>	
{
public:
	Button    buttonM, buttonL, buttonM2;

And now it works.  😃  Thank you.

**Comment by kennykerr** [comment]
That’s right. Generally, when you hit a linker error it means that you’re using definitions from a namespace you haven’t included. Some other namespace pulled in the declarations but the definitions aren't included automatically to reduce build time. Hopefully C++ modules will make this problem go away in future.
