### ISSUE TITLE
At this point, I really need a document page for the winrtcpp projection for experimenting this repos.

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#221]
So here is the code snippet I have.

I use cppwinrt projection and get an IDrect3dSurface object. 

![image](https://user-images.githubusercontent.com/6119906/28826231-5667042e-7697-11e7-8ab3-ef2647b490aa.png)

If I'm understanding correctly, d3dsurface is like a pixel buffer.
In  order to render this surface, I need to make it a texture. In order to make a texture I have to have a interpolation class, introduced by this page:

https://msdn.microsoft.com/library/windows/apps/Windows.Graphics.DirectX.Direct3D11.IDirect3DDevice

Another problem is, without the prior knowledge of windows programming, cppwinrt does not really make regular c++ programmers easier. All document online right now are in "C++/CX".  

I'm a pure graphics/computer vision programmer, I don't think I need learn too much c++/cx. That's why I think cppwinrt is really a good idea. But it really needs some form of documents. Correct me if I'm wrong.

**Comment by walbourn** [comment]
Since you are using ``ref`` you are using C++/CX, not C++/WinRT, for those interfaces.
