### ISSUE TITLE
Develop cppwinrt in the open?

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#226]
Have you guys considered developing the framework directly in GitHub with full PR support? Would be cool to be part of development process.

**Comment by BenJKuhn** [comment]
We would love to move to a fully open development process. We've been evaluating if and when to do that on a regular basis, but have not yet made the switch. We appreciate your enthusiasm though. Knowing that others are interested in contributing is a factor in our decision process.

Thanks,

Ben
