### ISSUE TITLE
Inheritance from IInspectable and const reference parameter

### ISSUE THREAD

**Issue by Mr1Penguin** [Microsoft/cppwinrt#227]
Hello! 
I tried to implement properties for binding and my class inherits from IInspectable. There is also _impl classes-helpers used as object for m_ptr.
My problem is when function accepts const reference of my objects it's getting a 'corrupted' version.
When trying to use default objects such as TextBlock everything is fine.

If somebody can look at my code and find reason why it's happening it would be very helpful.

https://github.com/Mr1Penguin/cppwinrtbinding

**Comment by kennykerr** [comment]
I took a quick look. There are a number of problems with this example, but they stem from limitations with the current version of the library on GitHub that are not easy to work around today. The good news is that we're preparing an update that solves many, if not all, of these problems and makes it that much easier. I think you will be pleasantly surprised at how much simpler your example will become.

Hang in there. 😉

**Comment by Mr1Penguin** [comment]
That's great to hear!
