### ISSUE TITLE
Event Handler Issue after upgrade WinRT

### ISSUE THREAD

**Issue by rvinothrajendran** [Microsoft/cppwinrt#230]
I have tried sample program for RadioButton checked event handler , previous version  is working fine below code
RadioButton RButton;
RButton.Checked({ this,&App::RdButtonClick });
void RdButtonClick(IInspectable const& sender, RoutedEventArgs const& args)
{
}
**After upgrade a new WinRT version** is not working , its throw an compile time error

Error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: struct winrt::event_token __thiscall winrt::impl::consume_Windows_UI_Xaml_Controls_Primitives_IToggleButton<struct winrt::Windows::UI::Xaml::Controls::RadioButton>::Checked(struct winrt::Windows::UI::Xaml::RoutedEventHandler const &)const " (?Checked@?$consume_Windows_UI_Xaml_Controls_Primitives_IToggleButton@URadioButton@Controls@Xaml@UI@Windows@winrt@@@impl@winrt@@QBE?AUevent_token@3@ABURoutedEventHandler@Xaml@UI@Windows@3@@Z) referenced in function

Please let me know , how to fix this 
Thanks 
Vinoth.

**Comment by Scottj1s** [comment]
Vinoth, you can fix this by adding:
#include "winrt/Windows.UI.Xaml.Controls.Primitives.h"

Generally, when you see a link error for an unresolved C++/WinRT artifact, you can fix it by #including the namespace header for that artifact.  In a future release, we hope to distribute C++/WinRT in module form as well, which will eliminate these kinds of errors.

**Comment by rvinothrajendran** [comment]
Thanks Scott , Its working fine

**Comment by rvinothrajendran** [comment]
@Scottj1s , Using ListBox -> SelectionChanged event it throw an compile time error 
lstBox.SelectionChanged({ this, &App::lstBoxSelectionChange });

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'void *winrt::Windows::Foundation::IUnknown::operator new(::size_t)': attempting to reference a deleted function	CreateCpp	C:\CPPWinRT\winrt\base.h	3360	

Please let me know , how to fix it
Thanks.
Vinoth.

**Comment by kennykerr** [comment]
The error seems to be unrelated to the code snippet you provided. Can you provide a standalone repro? Hint: you should never use "new" to create a C++/WinRT type. For example, the following code:

```C++
new ListBox;
```

Will produce the following compiler error:

```
error C2280: 'void *winrt::Windows::Foundation::IUnknown::operator new(::size_t)': attempting to reference a deleted function
```

This is intentional. Simply create the ListBox on the stack:

```C++
ListBox box;
```

**Comment by rvinothrajendran** [comment]
@kennykerr  yes , am not using new keyword 

please find the sample in the here https://github.com/rvinothrajendran/CPP-WinRT-Samples/tree/master/ListBox/CreateCpp

thanks.
Vinoth.

**Comment by kennykerr** [comment]
That's a misleading compiler error. I haven't looked into why that is, but your event handler's second parameter should be SelectionChangedEventArgs rather than SelectionChangedEventHandler. Change that and it should compile.

**Comment by Scottj1s** [comment]
Vinoth, your event handler has a typo (wrong event args type) - it should be:
	void lstBoxSelectionChange(IInspectable const& sender, SelectionChangedEventArgs const & args)

**Comment by rvinothrajendran** [comment]
Thanks @kennykerr and @Scottj1s , its working fine.
