### ISSUE TITLE
Is it possible to use good old COMMTIMEOUTS structure?

### ISSUE THREAD

**Issue by CodeMusher** [Microsoft/cppwinrt#233]
I'm trying to port an old application communicating over a serial port to use cppwinrt.
Is it possible to make use of the good old COMMTIMEOUTS somehow? Setting ReadTimeout and WriteTimeout seems not to be enough.

**Comment by kennykerr** [comment]
This sounds like a good question for [stackoverflow.com](https://stackoverflow.com/).

**Comment by Scottj1s** [comment]
@CodeMusher, see the documentation for [SerialDevice](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.SerialCommunication.SerialDevice).  In particular, the ReadTimeout and WriteTimeout properties.,

**Comment by CodeMusher** [comment]
Thank you for your quick answer! I've managed to solve my problem by implementing a Desktop Bridge. 
I'm now closing this issue.
