### ISSUE TITLE
In-proc and out-of-proc modules

### ISSUE THREAD

**Issue by YohDeadfall** [Microsoft/cppwinrt#234]
Is it planned to implement an in/out-proc module support like in WRL? I think it would be a good idea to write libraries using cppwinrt.

**Comment by kennykerr** [comment]
Yes, we plan to support the development of WinRT components with C++/WinRT. You can do so manually today only as long as you restrict yourself to interfaces defined by the Windows SDK. Full component authoring support requires the cppwinrt.exe compiler that will be included in the Windows SDK in the coming weeks.

**Comment by asklar** [comment]
@kennykerr  is there a pointer on how to write/activate out of proc custom WinRT components with cppwinrt? Specifically I'm looking at writing a C# winrt component, have an exe written in C# act as the server for that component, and have some cppwinrt code call into it. Is that possible?
