### ISSUE TITLE
DeviceWatcher::Start throws E_ILLEGAL_METHOD_CALL.

### ISSUE THREAD

**Issue by fxb** [Microsoft/cppwinrt#235]
I've tried using `DeviceWatcher` (https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher) via cppwint from a classic desktop app, both with and without a package identity.

In any case, calling `Start()` on a `DeviceWatcher` that is in the `Created` state, I get an `E_ILLEGAL_METHOD_CALL` error.

I've tried a normal C# UWP project where this works without problems. The API documentation lists the `DualApiPartition` attribute, so I expect this API to work fine.

I realize this might be a Windows bug and not a cppwinrt bug. Anyways, other users of cppwinrt will likely be affected. It would be nice to get this forwarded to the appropriate team.

**Comment by kennykerr** [comment]
Hi Felix, 

Can you share a standalone repro? This API appears to work fine for me. Here's an example:

```C++
#pragma comment(lib, "windowsapp") 
#include "winrt/Windows.Devices.Enumeration.h"

using namespace winrt;
using namespace Windows::Devices::Enumeration;

int main()
{
    init_apartment();

    DeviceWatcher w = DeviceInformation::CreateWatcher();

    w.Added([](DeviceWatcher const& sender, DeviceInformation const& args)
    {
        printf("Name: %ls\n", args.Name().c_str());
    });

    w.Start();
    getchar();
}
```

**Comment by fxb** [comment]
Hi Kenny,

Thanks for the fast response! It turns out that this one was a user-error... ;-)

Your example showed me what I was doing wrong. I used `winrt::auto_revoke`, but while I was just playing around, I didn't store the `winrt::event_revoker<>`, which meant every event callback got revoked immediately after being registered. Calling `Start` without any event callbacks registered results in `E_ILLEGAL_METHOD_CALL`.
