### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by AlexBAV** [Microsoft/cppwinrt#237]
Could you please update NuGet package with the latest release of the library?

**Comment by Scottj1s** [comment]
Yes, our NuGet package maintainer was on vacation when we updated.  It's on the way, thanks for your patience.

**Comment by walbourn** [comment]
I'm putting it together now... should have it up shortly.

**Comment by walbourn** [comment]
I have updated NuGet with the current release [here](https://www.nuget.org/packages/cppwinrt/2017.8.25.1)

**Comment by AlexBAV** [comment]
Thanks, Chuck. Everything is working now!
