### ISSUE TITLE
How to use with classic desktop app and Radial Controller

### ISSUE THREAD

**Issue by k88albr** [Microsoft/cppwinrt#238]
Firstly thanks for the tremendous work in putting this together.  Some awesome engineering in here.
Watched the CppCon video with a lot of respect.

So, I have an interop issue...   I'm using the Radial Controller in a classic desktop application and have it mostly working in the C++/WRL Raw style like that long Hello World in the CppCon video.  Would love to just do the whole thing with cppwinrt but there's some snags.

This journey started when I wanted to remove some default menu items.  There's an api for it, SetDefaultMenuItems and in C# it's trivial to give it a list of the enums for the menu items you want.  Not so in classic desktop.  I have tried many approaches to bridge the gap.  Thought I had it with this project.

One of the issues is that there's a separate api for getting a Radial Controller for an HWND.  This is exposed by IRadialControllerInterop which you can get like this:
    RETURN_IF_FAILED(Windows::Foundation::GetActivationFactory(
        HStringReference(RuntimeClass_Windows_UI_Input_RadialController).Get(),
        &_controllerInterop));
It's defined by the header in C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\UM\RadialControllerInterop.h

I need to call a method IRadialControllerInterop::CreateForWindow but this is not wrapped within cppwinrt, only a RadialController::CreateForCurrentView which takes a CoreWindow.
I have the same problem with IRadialControllerConfigurationInterop::GetForWindow which returns an IRadialControllerConfiguration.  It's this interface I need to use in order to change the default menu.  There's only a RadialControllerConfiguration::GetForCurrentView that also takes a CoreWindow

IRadialControllerConfiguration::SetDefaultMenuItems takes an IIterable. 
Tried collections.h but that only works for C++/Cx and consuming the extensions.  Thus far haven't found a good way to get from std::vector to something it wants.  Of course I'd like to just pass the vector but unless I can use the projected version, I'm a bit stuck.

Thanks again!

**Comment by kennykerr** [comment]
Firstly, you need to make it very clear that my management needs to give me a Surface Studio so I can really help you. 😉 

Seriously, it should not be too hard, although I don't actually have a radial controller so I can't verify. Since there's no metadata for interop APIs, you need to write a helper function of some kind to bridge the gap. Here's what I'd do. You can use a function like this to create a RadialController object for a given HWND:

```C++
RadialController GetRadialController(HWND window)
{
    auto factory = get_activation_factory<RadialController>();
    auto interop = factory.as<IRadialControllerInterop>();

    RadialController controller = nullptr;

    check_hresult(interop->CreateForWindow(window,
                                           guid_of<RadialController>(),
                                           reinterpret_cast<void**>(put_abi(controller))));

    return controller;
}
```

You can then stick to the C++/WinRT language projection from there on out:

```C++
HWND window = GetWindow();

RadialController controller = GetRadialController(window);
printf("degrees: %.2f", controller.RotationResolutionInDegrees());
```

You can do much the same for creating a RadialControllerConfiguration object:

```C++
RadialControllerConfiguration GetRadialControllerConfiguration(HWND window)
{
    auto factory = get_activation_factory<RadialControllerConfiguration>();
    auto interop = factory.as<IRadialControllerConfigurationInterop>();

    RadialControllerConfiguration config = nullptr;

    check_hresult(interop->GetForWindow(window,
                                        guid_of<RadialControllerConfiguration>(),
                                        reinterpret_cast<void**>(put_abi(config))));

    return config;
}
```

You can then stick to C++/WinRT to use it. The language projection will automatically bind to a variety of C++ containers to make the SetDefaultMenuItems call work. Here I'm using an initializer list:

```C++
    RadialControllerConfiguration config = GetRadialControllerConfiguration(window);

    config.SetDefaultMenuItems({ RadialControllerSystemMenuItemKind::Scroll,
                                 RadialControllerSystemMenuItemKind::Zoom });
```

You can also use a std::vector if you wish:

```C++
RadialControllerConfiguration config = GetRadialControllerConfiguration(window);

std::vector<RadialControllerSystemMenuItemKind> items
{
    RadialControllerSystemMenuItemKind::Scroll,
    RadialControllerSystemMenuItemKind::Zoom
};

config.SetDefaultMenuItems(items);
```

Hope that helps. And please send me a Surface Studio!

**Comment by k88albr** [comment]
Indeed it does! Awesome thanks!  It works :)  

Note I don't have Surface Studio either but the Dial works with a Surface or a Dell Canvas or pretty much anything that has Win10 Creators Edition on it as long as it will pair with the Dial over Bluetooth.   It's a cool accessory.

Yes, Microsoft, please get Kenny a Surface Studio for all the great contributions he's made to the C++ community over the years.  

Now in porting the raw stuff to cppwinrt, sometimes I don't feel 'with it'  Especially when the compiler spews what seems to be hundreds of With statements.  That's a slight drag to working with templates but I've run into the same sometimes with STL. It is surprising how much spew a few misteps can make.

Thanks again for all that you do!

Keith
(Jer 29.11)
