### ISSUE TITLE
Custom IInspectable interface

### ISSUE THREAD

**Issue by geminik23** [Microsoft/cppwinrt#24]
Is there a way to cast the custom object(inhereted ::IInspectable interface) to winrt::Windows::IInspectable?

**Comment by kennykerr** [comment]
I'm not sure what you mean. Perhaps something like this?

```C++
void Sample(::IInspectable * raw)
{
    Windows::IInspectable value;
    copy_from(value, reinterpret_cast<ABI::Windows::IInspectable *>(raw));
}
```

If you mean to take ownership then use attach rather than copy_from.

**Comment by geminik23** [comment]
Right. Thank you
