### ISSUE TITLE
Using cppwinrt from windows driver?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/cppwinrt#241]
In an [issue about accessing bluetooth APIs from a windows driver](https://stackoverflow.com/questions/45773666/developing-an-hid-input-device-driver-for-a-ble-gatt-device-on-windows-10) on stackoverflow, @AlainMichaud from Microsoft said that the way to go is to use cppwinrt.

Since I can nowhere find a sample or documentation on using cppwinrt from the context of a windows driver, I'm wondering whether you could comment on things to keep in mind and how to do it. Providing a sample and documentation would be even better!

**Comment by kennykerr** [comment]
UMDF drivers can certainly use cppwinrt since its just standard C++ and runs in user-mode. We don't have a sample of this at the moment (nor have we tested this), but it should work much the same way that you would include cppwinrt in any other C++ project.
