### ISSUE TITLE
what is effect of /d1permissive- option?

### ISSUE THREAD

**Issue by mibintc** [Microsoft/cppwinrt#243]
Some of the samples are using /d1permissive- option, can you explain what that does?  I work on the Intel c++ compiler and am working through the sample code. Thanks and regards, Melanie Blower

**Comment by kennykerr** [comment]
/d1permissive- was an experimental version of what became the /permissive- option. It raises the bar of standard conformance. Our samples should now be using /permissive-. This option is described here:

https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/

**Comment by mibintc** [comment]
thanks!

**Comment by kennykerr** [comment]
Also, let me know how things are with the Intel compiler. Our [own compiler devs](https://www.reddit.com/r/cpp/comments/6vffok/cwinrt_shows_some_signs_of_life_documentation/) have found that C++/WinRT is a very useful stress test for a C++ compiler.

**Comment by mibintc** [comment]
The Intel c++ compiler doesn't support coroutines at present and all the samples appear to use those directly. Awhile ago when I looked at the samples there was one that didn't--the simplest sample, and we could build and execute that OK. I want to make sure we can handle the wrappers--I found a couple of problems in the samples, we're analyzing those now.  Besides the samples, are there other test cases you can suggest?

I had recently downloaded the zip file and that had /await and /d1permissive- in the solution, perhaps I should clone to get an updated version.  I am building them with vs2017 15.4. A couple of the solutions won't build with that version and want me to install vs2015, I didn't try out those samples.

**Comment by kennykerr** [comment]
Coroutines are optional. I can share some examples along those lines. There were also some regressions in the C++ compiler prior to 15.3 but those should all be fixed now that the Visual C++ team uses our sources as part of their daily build validation. Be sure to clone or download the latest headers. Email me and I can get your more information and samples. Thanks!

Kenny.Kerr@microsoft.com

**Comment by walbourn** [comment]
With the VS 2017 15.3 update or later, you should also read [this post](https://blogs.msdn.microsoft.com/vcblog/2017/09/11/two-phase-name-lookup-support-comes-to-msvc/) in addition to the [original post](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/) on ``/permissive-``

**Comment by mibintc** [comment]
Thanks, I keep an eye on the blogs (love the blogs!) and had noted the information about 2-phase lookup. We use the C++ implementation from EDG so we've got some support for that which we can wire to the options .
