### ISSUE TITLE
Hamburger Button style is not working

### ISSUE THREAD

**Issue by rvinothrajendran** [Microsoft/cppwinrt#245]
Hi ,
I have tried to create Hamburger button style program  but is not working as excepted , output is display as "Box char"

sample code
`Button BtnHamburger;
IInspectable captionText = PropertyValue::CreateString(L"&#xE700;");
BtnHamburger.Content(captionText);
BtnHamburger.FontFamily(FontFamily(L"Segoe MDL2 Assets"));`

Please let me know , how to fix this issue.

**Comment by anhoavu** [comment]
You were using xml escaped char, the equivalent one for C++ to get unicode string is \u prefix i.e. \uE700

**Comment by rvinothrajendran** [comment]
Thanks @anhoavu , its working fine.
