### ISSUE TITLE
XamlMarkup (Universal Windows) Sample Erros say Page and TextBlock not supported in WUP

### ISSUE THREAD

**Issue by Stricklyspeaking** [Microsoft/cppwinrt#246]
I am using VS 2017 Ver 15.3.5. I pulled the cppwinrt code from GitHub 2 days ago and I have been building each of the sample applications and studying how they work.  I admit that I am trying to learn these concepts and likely have some issues.

When I build the XamlMarkup ap I get two errors complaining about Page and TextBlock not being in the Windows Universal project. However, the application does build and run properly.

I have built it targeted for an ARM as delivered and I have tried it with x64 getting the same errors.
I reviewed the namespaces used and looked for them in the Object Browser and I do not see Windows::UI::XAML::Controls listed on system. I have expanded the packages installed by VS trying to be sure everything is there.

I want to add additional Xaml like buttons to the sample code but when I add them to the code I get the same error and the code will not compile or run. I probably need to add additional Namespace but I am confused about why I see the errors.

Can someone give me an idea of why I see the errors?

**Comment by Scottj1s** [comment]
I just confirmed that I can build the XamlMarkup sample with VS 2017 15.3.5, in several configurations/platforms, including ARM and x64.  So I'm not sure what you're experiencing.  Is it only a problem with the XamlMarkup sample?  Can you attach your build output verbatim?

**Comment by Stricklyspeaking** [comment]
Thanks for reply Scott.  As I indicated the sample builds and seems to run fine. The issue is there are two errors reported.
Build Output Verbatim:
1>------ Rebuild All started: Project: XamlMarkup, Configuration: Debug x64 ------
1>        1 file(s) copied.
1>pch.cpp
1>App.cpp
1>XamlMarkup.vcxproj -> C:\Users\Bob\cppwinrt\10.0.15063.0\Samples\XamlMarkup\Debug\x64\XamlMarkup.exe
1>XamlMarkup.vcxproj -> Debug\x64\XamlMarkup.pdb (Partial PDB)
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Error List:
X    Page is not supported in a Windows Universal project             XamlMarkup          MainPage.xaml     1
X    TextBlock is not supported in a Windows Universal project      XamlMarkup          MainPage.xaml     3

I have attached an image showing the errors indicated in the code and the Invalid Markup GUI. I guess this Markup GUI would be working if there were no errors.

![xamlmarkuperrors](https://user-images.githubusercontent.com/8163691/30997881-55356baa-a490-11e7-9369-5035a89c3aa1.PNG)

**Comment by Scottj1s** [comment]
I see - it's a schema validation error.  In that case, it's probably an OS version or SDK version issue.  You might follow it up within Visual Studio : Help | Send Feedback | Report a Problem

**Comment by Stricklyspeaking** [comment]
Thanks very much for the email.

I am fine with the comment about the thread if you are.  I am on a steep learning curve with this stuff and just working through the examples trying things out. I mainly wanted to let people at Microsoft know about the issue in case it was a problem.

Keep up the good work!

Best Regards,

Bob Stricklin


On Oct 26, 2017, at 1:35 PM, Kenny Kerr <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #246<https://github.com/Microsoft/cppwinrt/issues/246>.

**Comment by jevansAN** [comment]
I see the same error when trying to view MainPage.xaml in that xamlmarkup sample project. But I just downloaded the latest SDK and tools, etc. so I really wonder if it will be possible to use xaml at all in a C++/RT project -?

**Comment by jevansAN** [comment]
I see the same error when attempting to view the MainPage.xaml file in that sample project. But this is after downloading today the latest preview SDK (though on the "slow" setting), latest VS, etc - perhaps it is not actually possible yet to use xaml in a C++/WinRT project?
