### ISSUE TITLE
How to not use Visual Studio IDE to compile C++/WinRT programs?

### ISSUE THREAD

**Issue by jlvandenhout** [Microsoft/cppwinrt#247]
I'm trying to brush up on modern C++ together with graphics programming on Windows 10. With the example below I hope you guys can help me understand the underlying concepts of the Windows Runtime API and how to build against it.
It has been a few days now that I tried to read up on this, but most of the documentation assumes Visual Studio IDE and poorly documented behind-the-scenes magic (which I hate - looking at you MSDN). I still can not get this to work:

So I have the Visual C++ Build Tools 2017 with the Windows 10 SDK. I added the C++/WinRT project to my folder with shared libraries.
I have reduced the Blocks sample to the simplest C++ file I could imagine (see below), I open up a Native Tools Command Prompt and run the compiler as per instruction in the Getting Started file (see below).
It compiles, but when trying to run the program it crashes (see below).
So how would one go about and compile a program that uses the C++/WinRT bindings, without the use of the Visual Studio IDE?

**The program (main.cpp)**
```
#pragma comment(lib, "windowsapp") 

#include "winrt/Windows.ApplicationModel.Core.h"
#include "winrt/Windows.UI.Core.h"


using namespace winrt;
using namespace winrt::Windows::ApplicationModel::Core;
using namespace winrt::Windows::UI::Core;


struct App : implements<App, IFrameworkViewSource, IFrameworkView>
{
    //IFrameworkViewSource methods
    IFrameworkView CreateView()
    {
        return *this;
    }

    //IFrameworkView methods
    void Run()
    {
        CoreWindow window = CoreWindow::GetForCurrentThread();
        window.Activate();

        CoreDispatcher dispatcher = window.Dispatcher();
        dispatcher.ProcessEvents(CoreProcessEventsOption::ProcessUntilQuit);
    }

    void Initialize(CoreApplicationView const &) {}
    void Load(hstring const &) {}
    void Uninitialize() {}
    void SetWindow(CoreWindow const &) {}
};

int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
    init_apartment();
    CoreApplication::Run(App());
}
```

**The compiler command**
```
cl main.cpp /I {shared-folder}\cppwinrt\10.0.15063.0 /EHsc /std:c++latest /permissive- /await
```

**The exception**
```
Exception thrown at 0x76F7B832 (KernelBase.dll) in main.exe: 0x40080201: WinRT originate error (parameters: 0x80070057, 0x0000000A, 0x00EFEF94).
Exception thrown at 0x76F7B832 in main.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x00EFFAB0.
Unhandled exception at 0x76F7B832 in main.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x00EFFAB0.
```

**Comment by light-tech** [comment]
You can't run this program as you would a Win32 program since it uses XAML technology. See my issue #229. You need **an app container**. So you need to learn how to run `MakeAppx` or whatever commands to generate and sign the UWP app package which you can install to the machine and run the app from the Start menu.

It is possible to run the app container directly but this is a secret baked into Visual Studio IDE if I recalled correctly from a Stackoverflow question.

**Comment by Scottj1s** [comment]
@jlvandenhout, as @light-tech mentions, this code requires execution in an app container.  Ideally, such code would fail to compile (or at least link), and not waste your time debugging it.  I'm investigating ways to implement that for the next release.

**Comment by jlvandenhout** [comment]
@light-tech Thank you, that helped me further to understand the Windows Runtime concepts.
@Scottj1s  It indeed has taken a while for me to understand it was the wrong environment in which I tried to run the program. Failing to build such an app would help a lot!

It seems like the Windows documentation is more geared towards "just write your code and hit Build", while not really explaining the relationships between the different technologies. This confuses me still. An overview of where the different technologies reside in the system and how they can be used would clear up a lot.

As a side-question to this: is there an easier way to see which parts of the Windows Runtime can be used outside the app container?

**Comment by jlvandenhout** [comment]
Nevermind, I found this:  [https://msdn.microsoft.com/en-us/library/windows/desktop/mt695951(v=vs.85).aspx](url)

I will look into this myself. Thank you for your answers and good work!

**Comment by eklipse2k8** [comment]
I believe they've added support in WinDBG now to support app container debugging. You'll still need to "install" the package before running it just as Visual Studio does this on every run before it launches the debugger.

**Comment by jlvandenhout** [comment]
That's interesting! Although I think the VS way still outweighs the non-VS way of coding for UWP. I get the whole safety thing of running apps in a sandbox, but it makes building an app really non-trivial when coming from a general C++ background. If only MS could provide a kind of generic "debugging sandbox" to run our apps in in debugging stage, just like you can do with Python (I know, something with apples and oranges, but still).

**Comment by Tryum** [comment]
Does every app using C++/winrt must run in an uwp app container ?
I need to get access to the front-facing camera and was thinking of using MediaCapture for futurproofing my code... but if I can't run it as a standard desktop app, that makes no sense for me :/

**Comment by kennykerr** [comment]
Yes, only certain APIs require an app container. A growing number of APIs work just fine from the desktop. Here is an example I showed at CppCon recently. This is just a simple console app.

```C++
using namespace Windows::Foundation;
using namespace Windows::Storage;
using namespace Windows::Media::Capture;
using namespace Windows::Media::MediaProperties;

IAsyncAction Sample()
{
    auto library = co_await StorageLibrary::GetLibraryAsync(KnownLibraryId::Pictures);
    auto folder = library.SaveFolder();

    auto file = co_await folder.CreateFileAsync(L"cppcon.jpg",
        CreationCollisionOption::ReplaceExisting);

    MediaCapture capture;
    co_await capture.InitializeAsync();

    auto props = ImageEncodingProperties::CreateJpeg();
    co_await capture.CapturePhotoToStorageFileAsync(props, file);
}

int main()
{
    init_apartment();
    Sample().get();
}
```
