### ISSUE TITLE
fatal error C1083: Cannot open include file 'winrt/base.h'

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#248]
I was surprised to get this error (Note 1 below) with the Blocks sample using the latest of everything:

Windows 10 Pro:
1703                             (Version)
15063.632                    (OS Build)

Windows SDK:
15063.468.170612-1856.rs2_release_svc_sec_WindowsSDK

WinRT:
cppwinrt\10.0.15063.0
(I edit pch.h to use the full include path to the header files)

(Note 1) Solution has been retargeted (ver and min ver) to 10.0.15063.0

**Comment by walbourn** [comment]
How is your project set up to consume C++/WinRT headers? Are you using NuGet or did you add your own _Additional Include Paths_?

**Comment by MRahilly** [comment]
I have always edited the pch.h like so having first copied the cppwinrt directory tree into the VS Projects folder so that the cppwinrt folder is a the same level as the Blocks project folder in this case.
#include "..\cppwinrt\10.0.15063.0\winrt\Windows.ApplicationModel.Core.h"

It has just struck me that this latest VS 2017 did not create a familiar "Projects" folder and instead created an empty "repos" folder which could be my problem if "repos" is now the new default working folder as I am using "..\" etc when I compile. I created my own "Projects" folder and used that instead.

**Comment by MRahilly** [comment]
I got the same C1083 error with the CL sample using the command line outside of VS 2017.

**Comment by kennykerr** [comment]
Please make sure that your include paths point to the folder **containing** the `winrt `folder and not the folder itself. That's often the cause of this error.

**Comment by MRahilly** [comment]
Thanks Chuck and Kenny. For now, I will just hard code the full path to the winrt header files and avoid any "..\cppwinrt\10.xxxxx.x\winrt\" relative references and see how that works. Still strange though. Until now all I had to do was update the 10.0.xxxxx.x version string which each great update and everything worked just fine.

**Comment by MRahilly** [comment]
Used your advice and the issue is resolved. Thanks.
There is still a VS 2017 inconsistency here: go to a VS Command prompt and the default folder is "source"; start a new project in IDE and the default folder is "repos" underneath "source".
