### ISSUE TITLE
Creating a subclass of IInspectable with a guid?

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#249]
I'd like to create a subclass of IInspectable so I can pass this into:

```cpp
struct MyTag : winrt::implements<MyTag, IInspectable> {};

MyTag x;

item.Tag(x);  <-- works great!
```

What is the magical incantation to get MyTag back out from there?

```cpp
auto x = item.Tag();
```

### 1
```
x.as<MyTag>();
```
I'd like to get this pattern to work, but the compiler fails with missing GUID. What's the best way to supply a GUID that works? Do I need to create an IDL file as well or can this be avoided? Might also be helpful if anyone knows the easiest way to add a GUID to the struct.

### 2
Also, Is there any built in mechanism to know what type it is when it comes back from the projection as IInspectable? Or will I need to create an interface such as IMattsTaggableType with some kind of overridable method that returns its typename?

**Comment by Scottj1s** [comment]
Note that as<> works with interfaces (via QueryInterface), identified by GUIDs 'attached' to the template type argument.  If you want that kind of awareness in the projection, with the ability to pull an arbitrary object (IInspectable) out of another object and dynamically downcast it, you'll probably need to express it in IDL.  If, on the other had, you want to simply instantiate a concrete implementation of a runtime class, and hold on to that derived type, you can use winrt::make_self<T>.  Hope this helps.

**Comment by kennykerr** [comment]
Just to add to what Scott said, you must use `make` or `make_self` to construct an implementation to ensure correct behavior and lifetime management. There are very few scenarios where you can get away with a stack allocation.
