### ISSUE TITLE
Create declarations for interop interfaces in winrt

### ISSUE THREAD

**Issue by smj389** [Microsoft/cppwinrt#25]
At the moment, if you want to use the interop types in e.g. windows.ui.composition.interop.h you have to include the include file from the sdk which declares them in ::ABI and you have to consume them with a winrt::com_ptr. It would be nice to be able to use those directly in winrt or at the least have them in winrt::ABI. Otherwise, using namespace winrt; makes ABI ambiguous meaning you have to say ::ABI or winrt::ABI.

**Comment by kennykerr** [comment]
You have a few options. You can be explicit as follows:

```C++
using namespace winrt;

com_ptr<::ABI::Windows::UI::Composition::ICompositionDrawingSurfaceInterop> p;
```

Notice the scope resolution operator before the ABI namespace.

Another option is to use a namespace alias:

```C++
using namespace winrt;
namespace sdk_abi = ::ABI::Windows::UI::Composition;

Compositor compositor;
com_ptr<sdk_abi::ICompositorInterop> interop = compositor.as<sdk_abi::ICompositorInterop>();
```

You can also combine different "ABI" namespaces into one:

```C++
namespace sdk_abi
{
    using namespace ::ABI::Windows::UI::Composition;
    using namespace ::ABI::Windows::UI::Xaml;
}
```

Hope that helps.
