### ISSUE TITLE
error APPX0702: Payload file '...\HelloWorld_Uwp.winmd' does not exist.

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/cppwinrt#251]
I started with the Direct2d sample and incrementally modified to suit my needs. I use VS2017. I get the above error. How did the 'app.winmd' get generated ? Normally, it's part of the build process. But the sample seems to hardcode the file and contents ? How I generate HelloWorld_Uwp.winmd for my app ?

**Comment by Scottj1s** [comment]
[See here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/d5deeca4-7fd6-47b7-a8d3-ba83b04cadb6/error-appx0702-payload-file-projectswrc1debugwrc1wrc1blankpage1xaml-does-not-exist?forum=winappswithnativecode) for guidance.   Alternately, if the dependency was inadvertent and unnecessary, you can set the Generate Windows Metadata linker switch to No (/WINMD:NO)

**Comment by mediabuff** [comment]
Thank you. I had to set /WINMD:NO.

**Comment by tqk2811** [comment]
I follow this: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/interop-winrt-cx

first build success, but when i change type build (debug/release, x64/x86) i got
Error APPX0702 Payload file '<solution folder>\Debug\<proj name>\<proj name>.winmd' does not exist.

Generate Windows Metadata linker was switch to No.
I was change back, but it n't work.
