### ISSUE TITLE
Is cppwinrt going into the fall creators update sdk?

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#252]
I was looking for it in the latest insider sdk but couldn’t find it.

**Comment by BrentRe** [comment]
No. C++/WinRT will start appearing in the next series of Insider SDKs - i.e. post the Fall Creator's Update SDK.

**Comment by CodeChief** [comment]
I find the C++ Shared Items project a great way to incorporate the libraries (project references to the shared C++ project allow the includes to behave the same way). Then when the SDK is available (and it's part of the standard include paths) all you have to do is remove the shared project.

Coupled together with a script to help download/update the C++/WinRT files, it's not that much of an issue to put up with. For a working example/script see: https://github.com/emlid/Navio-SDK-Windows-IoT/tree/master/Dependencies

**Comment by walbourn** [comment]
We also publish the headers to [NuGet](https://www.nuget.org/packages/cppwinrt/) as an 'interim' solution until they get integrated into a future Windows 10 SDK.

**Comment by eklipse2k8** [comment]
Oh, I don't mind linking to the github clone, that's what I'm doing right now. I'm more excited for the cppwinrt compiler so that I can use other winmd classes without needing to fall back to midl.

**Comment by walbourn** [comment]
This has been published to [GitHub}(https://github.com/Microsoft/cppwinrt/releases/tag/fall_2017_creators_update_for_vs_15.3) and [NuGet}(https://www.nuget.org/packages/cppwinrt/2017.10.13.1)

**Comment by anhoavu** [comment]
Well, guess we have to wait for another 6 months for the promised `cppwinrt.exe`, the most crucial part for me to adopt C++/WinRT.
