### ISSUE TITLE
.as() no longer available?

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#253]
Just updated to latest SDK, thanks for getting that out!

One of my XAML subclasses used to use .as<>(), but it no longer exists. How do I get the UIElement of this?

**Comment by kennykerr** [comment]
The `as` call was used internally but we switched to using `try_as` for efficiency. I didn't realize people would be using this directly since we provide implicit conversions as well. We'll give this some though, but you can use `try_as` instead of `as` for now.

**Comment by MikeGitb** [comment]
> I didn't realize people would be using this directly

To quote [Hyrum's law](http://www.shanekirk.com/2016/12/hyrums-law/) ;)

> “With a sufficient number of users of an interface, it doesn’t matter what you promised in the interface contracts, all observable behaviors of your class or function or whatnot will be depended upon by somebody.”

**Comment by kennykerr** [comment]
Appreciate the sense of humor. 😄 

It's one of the reason I'm such a proponent of C++ modules. Its incredibly difficult building a sophisticated header-only library without bleeding all sorts of implementation details.

**Comment by eklipse2k8** [comment]
@kennykerr wait what?! I *extremely* appreciate that this framework is open source and completely open for review. I can step through the debugger and I can understand why certain things are behaving one way or another. Obviously I do not have the context for why decisions are made one way or another because I'm not on your team, but it's easy to see the high level reasoning.

One of c++/cx's most frustrating design decisions was that the generated code was completely opaque.

**Comment by kennykerr** [comment]
Agreed, I'm all for open source and not obscuring the implementation. Modules simply provide more control over what you can do with that visibility. Many thanks for the feedback. We aim to write the code in such a way that you can follow along and drill down as far as you wish.

**Comment by kennykerr** [comment]
We're tracking this internally (16084267). Thanks again for the feedback.
