### ISSUE TITLE
Data binding in C++/WinRT

### ISSUE THREAD

**Issue by light-tech** [Microsoft/cppwinrt#257]
Per the title, how would we do data binding in C++/WinRT? For instance, how to translate the following piece of XAML snipet

	<ListView IsItemClickEnabled="True" ItemClick="ListViewClickHandler">
		<ListView.ItemTemplate>
		    <DataTemplate x:DataType="MyCustomType">
			<Button Content="{x:Bind Action}" Click="PerformAction" />
		    </DataTemplate>
		</ListView.ItemTemplate>
	</ListView>

into C++/WinRT code?

**Comment by DefaultRyan** [comment]
We are currently working with the XAML team to light up x:Bind. It's getting close, but is not quite ready for production use yet. Stay tuned!

**Comment by Scottj1s** [comment]
Same goes for {Binding}.  The XAML compiler is being updated to resolve bindings to C++/WinRT projection, regardless of the markup extension used.

**Comment by Scottj1s** [comment]
Correction - the XAML team informs me that only x:Bind will be supported

**Comment by xprssn2** [comment]
Can the `Binding` markup extension still be used in code by `make`ing a `Windows.UI.Xaml.Data.Binding` and passing it to `Windows.UI.Xaml.FrameworkElement.SetBinding`, or will the `Windows.UI.Xaml.Data.Binding` class be removed?

**Comment by kennykerr** [comment]
The XAML effort is about completing the toolchain to support functionality beyond the language projection, but the same APIs that you might use to program XAML with code rather than markup will continue to be available.
