### ISSUE TITLE
ThreadPoolTimer no appropriate default  in std::map

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/cppwinrt#259]
I am trying to use thread pool timers in a std::map like:
std::map<uint_ptr, winrt::Windows::System::Threading::ThreadPoolTimer> m_timers

I get error on the line as follows:
'winrt::Windows::System::Threading::ThreadPoolTimer::ThreadPoolTimer': no appropriate default constructor available

**Comment by kennykerr** [comment]
Many of the traditional STL containers and functions assume that value types have cheap default constructors, but that is not always the case. The ThreadPoolTimer class doesn't provide a default constructor, so the following code will not compile:

```C++
ThreadPoolTimer timer = ...

std::map<uint32_t, ThreadPoolTimer> m_timers;
m_timers[0] = timer; // error C2512
```

The `operator[]` may attempt to perform an insertion before returning a reference to the value. That insertion requires some value and a default constructor is assumed. Fortunately, C++11 introduced the `emplace` functions that will perform the insertion "in place" with the provided arguments forwarded to avoid first calling a default constructor. 

```C++
ThreadPoolTimer timer = ...

std::map<uint32_t, ThreadPoolTimer> m_timers;
m_timers.emplace(0, timer);
```

Hope that helps.

**Comment by mediabuff** [comment]
Thank you Kenny. That solves one side of the problem (assignment) - when you want to add an element to std::map. 
How do remove and get a reference to the removed element - 'erase' will remove, but will not give a reference to the element.

**Comment by mediabuff** [comment]
This doesn't work:

auto timer = std::move(m_timers[nIDEvent]);
timer.Cancel();

**Comment by mediabuff** [comment]
The following stupid workaround worked. Is there a better way?

		auto timer = m_timers.find(nIDEvent);
		if (timer != m_timers.end())
		{
			(*timer).second.Cancel();
			m_timers.erase(nIDEvent);
		}

**Comment by mediabuff** [comment]
c++17 has a better way:
		auto timer = m_timers.extract(nIDEvent);
		if (!timer.empty())
			timer.mapped().Cancel();		}

**Comment by DefaultRyan** [comment]
I wasn't aware Visual C++ had implemented that feature yet. See the entry for P0083R3.

https://blogs.msdn.microsoft.com/vcblog/2017/08/11/c17-features-and-stl-fixes-in-vs-2017-15-3/
