### ISSUE TITLE
Can your example run on the Windows Iot?

### ISSUE THREAD

**Issue by scuhappy** [Microsoft/cppwinrt#26]
Because when I open the sample project, the debug options does not contain a "remote machine" option.
![capture](https://cloud.githubusercontent.com/assets/4221635/19712227/a14ef64a-9b6e-11e6-86ec-bc2b9e0e348c.PNG)

**Comment by kennykerr** [comment]
C++/WinRT works on Windows 10 IoT. We'll look into publishing an IoT sample.

**Comment by scuhappy** [comment]
Thanks a lot!
