### ISSUE TITLE
C1083 error with 2Gb RAM on 32 bit Win 10 Fall Creators Update

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#260]
Direct2D and Blocks samples build and run just fine.
I get C1083 temp\blah.pch not enough space errors compiling each of the three Xaml... samples when the original XamlCode sample used to build and run with VS 2017 15.3 and earlier.

Could VS 2017 version 15.4 and the cppwinrt headers have exceeded the capability of a 2Gb RAM PC running 32 bit Win 10 Fall Creators Update?

**Comment by kennykerr** [comment]
Until C++ modules arrive, XAML projects will require more memory to compile. The PCH memory usage is not very predictable. It can succeed in some cases and fail in others. The x64 cross compiler is the only reliable way to build these projects.

**Comment by MRahilly** [comment]
Thanks Kenny. The move to 64 bits worked.
