### ISSUE TITLE
Linker Error : XamlTypeInfo.g.obj : error LNK2019

### ISSUE THREAD

**Issue by sohel364** [Microsoft/cppwinrt#261]
What does this error means:
XamlTypeInfo.g.obj : error LNK2019: unresolved external symbol __Platform_AcquireSRWLockShared referenced in function "private: void __cdecl Platform::EventSource::DoInvokeVoid<class Windows::Foundation::Collections::VectorChangedEventHandler<struct Windows::UI::Xaml::Markup::IXamlMetadataProvider ^>,class <lambda_e7f2d868892b75e9054b0d8b72f53d64> >(struct Platform::Details::EventLock *,class <lambda_e7f2d868892b75e9054b0d8b72f53d64>)" (??$DoInvokeVoid@V?$VectorChangedEventHandler@PE$AAUIXamlMetadataProvider@Markup@Xaml@UI@Windows@@@Collections@Foundation@Windows@@V<lambda_e7f2d868892b75e9054b0d8b72f53d64>@@@EventSource@Platform@@AEAAXPEAUEventLock@Details@1@V<lambda_e7f2d868892b75e9054b0d8b72f53d64>@@@Z)
XamlTypeInfo.g.obj : error LNK2019: unresolved external symbol __Platform_ReleaseSRWLockShared referenced in function "private: void __cdecl Platform::EventSource::DoInvokeVoid<class Windows::Foundation::Collections::VectorChangedEventHandler<struct Windows::UI::Xaml::Markup::IXamlMetadataProvider ^>,class <lambda_e7f2d868892b75e9054b0d8b72f53d64> >(struct Platform::Details::EventLock *,class <lambda_e7f2d868892b75e9054b0d8b72f53d64>)" (??$DoInvokeVoid@V?$VectorChangedEventHandler@PE$AAUIXamlMetadataProvider@Markup@Xaml@UI@Windows@@@Collections@Foundation@Windows@@V<lambda_e7f2d868892b75e9054b0d8b72f53d64>@@@EventSource@Platform@@AEAAXPEAUEventLock@Details@1@V<lambda_e7f2d868892b75e9054b0d8b72f53d64>@@@Z)

I am just trying to run a simple new project to start using c++/winrt

**Comment by Scottj1s** [comment]
It looks like you began by converting a XAML C++/CX app, which generates XamlTypeInfo.g.cpp.  This file is silently compiled and linked into your binary, but if you've changed language type to C++ in the project (e.g., by adding <CompileAsWinRT>false<CompileAsWinRT>), then the project will pull in different CRT/STL libs, resulting in this error.  You can try deleting this source from the Generated Files folder, along with any other CX artifacts there, to get to a clean C++ state.

**Comment by sohel364** [comment]
Actually i created uwp project using VS project template. So i cam to this situation.
Is there any way to create c++/winrt project from visual studio?

**Comment by sohel364** [comment]
got reply on last query below
https://github.com/Microsoft/cppwinrt/issues/263
