### ISSUE TITLE
XamlMarkup doesn't compiler

### ISSUE THREAD

**Issue by sohel364** [Microsoft/cppwinrt#262]
- Target : 10.0.14393.0

Errors :
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'ILanguageExceptionErrorInfo2': is not a member of '`global namespace''	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2418	
Error	C2065	'ILanguageExceptionErrorInfo2': undeclared identifier	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2418	
Error	C2923	'winrt::impl::guid': 'ILanguageExceptionErrorInfo2' is not a valid template type argument for parameter 'T'	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2419	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2421	
Error	C2065	'ILanguageExceptionErrorInfo2': undeclared identifier	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2474	
Error	C2923	'winrt::com_ptr': 'ILanguageExceptionErrorInfo2' is not a valid template type argument for parameter 'T'	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2474	
Error	C2672	'winrt::com_ptr<IRestrictedErrorInfo>::try_as': no matching overloaded function found	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2474	
Error	C2974	'winrt::com_ptr<IRestrictedErrorInfo>::try_as': invalid template argument for 'To', type expected	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2474	
Error	C2512	'winrt::com_ptr': no appropriate default constructor available	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2474	
Error	C2451	conditional expression of type 'winrt::com_ptr' is illegal	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2474	
Error	C2678	binary '->': no operator found which takes a left-hand operand of type 'winrt::com_ptr' (or there is no acceptable conversion)	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2476	
Error	C2039	'CapturePropagationContext': is not a member of 'winrt::com_ptr'	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2476	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2955	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2965	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2981	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	2986	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	3001	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	3821	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	3826	
Error	C2953	'winrt::impl::guid': class template has already been defined	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	5966	
Error	C2977	'winrt::impl::guid': too many template arguments	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	5985	
Error	C2913	explicit specialization; 'winrt::impl::guid' is not a specialization of a class template	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	6694	
Error	C2953	'winrt::impl::guid': class template has already been defined	XamlMarkup	c:\users\userabc\desktop\cppwinrt-master\10.0.16299.0\winrt\base.h	6712	

Am i missing any compiler options? It builds fine with target 10.0.16299.0.

**Comment by kennykerr** [comment]
Please use the latest SDK. The older SDK did not include the ILanguageExceptionErrorInfo2 interface.

**Comment by sohel364** [comment]
@kennykerr  Thanks.
