### ISSUE TITLE
Need some basic help

### ISSUE THREAD

**Issue by sohel364** [Microsoft/cppwinrt#263]
- How to create a new project for cppwinrt? Is there any template on VS 2017 for it?
- Can I get my xaml resources by id or name in the cpp code behind? Didn't see any sample for that.
- Can I do data binding with the UI component like - with listbox, pivot etc?
- Can I consume cpp library without building it with /ZW option?
- I want to move my project to cppwinrt from c++/cx? Is it stable enough to create package(bundle) for distribution in offline and store mode?

**Comment by rvinothrajendran** [comment]
How to create a new project for cppwinrt? Is there any template on VS 2017 for it?
please check here -->http://www.c-sharpcorner.com/article/learn-universal-windows-programming-via-modern-cpp/
Can I get my xaml resources by id or name in the cpp code behind? Didn't see any sample for that.-> here am now using any xaml design , just start writing the serious of articles , how to use the XAML controls in C++/WinRT 
http://www.c-sharpcorner.com/article/learn-universal-windows-programming-via-modern-cpp-dispatchertimer/

Thanks & Regards ,
Vinoth.

**Comment by kennykerr** [comment]
- How to create a new project for cppwinrt? Is there any template on VS 2017 for it?

Project templates are still under development. The simplest way to start is with one of the sample projects here on GitHub.

- Can I get my xaml resources by id or name in the cpp code behind? Didn't see any sample for that.
- Can I do data binding with the UI component like - with listbox, pivot etc?

No, we are still working on data binding.

- Can I consume cpp library without building it with /ZW option?

Yes.

- I want to move my project to cppwinrt from c++/cx? Is it stable enough to create package(bundle) for distribution in offline and store mode?

We are fast closing the gap with C++/CX, but it is ready for app development so do give it a try.

**Comment by sohel364** [comment]
@kennykerr @rvinothrajendran Thanks for the details.

**Comment by walbourn** [comment]
For a Direct3D app model application, you can take a look at the VS templates at [directx-vs-templates](https://github.com/walbourn/directx-vs-templates). It looks like, however, you are looking for a XAML app model template which I don't support.
