### ISSUE TITLE
Sdk 10.0.17025.0 :   FileOpenPicker hangs in get_activation_factory()

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/cppwinrt#266]
I have the latest OS and sdk integrated cppwinrt.  
VC2017 15.5 Preview 2.0. 
OS 1709, OS Build 17025.1000

Even the 'video' sample doesn't work.

**Comment by kennykerr** [comment]
A bit more information would be helpful as I can't reproduce this problem.

**Comment by mediabuff** [comment]
The stack constructor for 'FileOpenPicker ' never returns (from Video sample):

    fire_and_forget OnActivated(CoreWindow window, WindowActivatedEventArgs)
    {
        m_activated.revoke();

        Compositor compositor;
        SpriteVisual visual = compositor.CreateSpriteVisual();
        Rect bounds = window.Bounds();

        visual.Size({ bounds.Width, bounds.Height });
        m_target = compositor.CreateTargetForCurrentView();
        m_target.Root(visual);
....


        FileOpenPicker picker;

        picker.SuggestedStartLocation(PickerLocationId::VideosLibrary);

**Comment by kennykerr** [comment]
Do you experience the same behavior when using C++/CX or C#?

**Comment by mediabuff** [comment]
Yes, sample problem with C++/CX. Neve returns from  ref new abi::FileOpenPicker(); (belwo)

Some thing wrong with the latest Win10 insider build ?

#include "pch.h"
#include "MainPage.xaml.h"

using namespace App2;

#include <windows.storage.pickers.h>
namespace abi
{
	using namespace Windows::Storage::Pickers;
}

MainPage::MainPage()
{
	InitializeComponent();
}

concurrency::task<void> MainPage::PickAnImage()
{
	auto picker = ref new abi::FileOpenPicker();
	picker->FileTypeFilter->Append(L".jpg");
	picker->SuggestedStartLocation = abi::PickerLocationId::PicturesLibrary;

	auto file = co_await picker->PickSingleFileAsync();
	if (nullptr == file)
		return;
}

void App2::MainPage::Button_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e)
{
	PickAnImage();
}

**Comment by kennykerr** [comment]
That may be. I'm not able to reproduce this on older or newer builds.

**Comment by Scottj1s** [comment]
Thanks @mediabuff  - we're investigating with Visual Studio team and will reply back

**Comment by Scottj1s** [comment]
We've been able to reproduce this internally.  I don't have specifics on the regression, but it appears to be resolved with the next Windows insider fast ring release, which should be going out any day.  Let us know if the update does not resolve.

**Comment by mediabuff** [comment]
Thanks for the follow-ups. I will wait for the update and revert.

**Comment by mediabuff** [comment]
This seems to be fixed in OS Build 17035.1000. Thank you all.
