### ISSUE TITLE
Can not create a Win32 desktop app with c++/winrt ?

### ISSUE THREAD

**Issue by jacking75** [Microsoft/cppwinrt#270]
I think it was possible in previous versions, but now I do not know what to do

**Comment by Scottj1s** [comment]
Yes, it's still possible - what issue are you encountering?

**Comment by jacking75** [comment]
Can I see the example code?

https://moderncpp.com/windows-runtime/
The code in this article does not work as it is now.

**Comment by Scottj1s** [comment]
Much has changed since that release.  Have a look at the samples included here instead, particularly the [syndication sample](https://github.com/Microsoft/cppwinrt/blob/master/10.0.16299.0/Samples/Syndication/Main.cpp) which is a simple console app,
