### ISSUE TITLE
api usage, threadpooltimer update xaml ui content and toast notification

### ISSUE THREAD

**Issue by gettf** [Microsoft/cppwinrt#272]
learning cppwinrt from samples xamlmarkup,
implemention need:
1) install a timer : use CreatePeriodicTimer of windows.system.threading.threadpooltimer
2) in timer every 5min DOWORK: update XAML's textblock = current time, and pop a toast notification

question：
how to implement 1 & 2,  want demo codes. 

(ask here because cppwinrt doc is too little, msdn api and winrt sample(c# cx) dosnt help, need more sample and api usage demo)

**Comment by kennykerr** [comment]
I haven't used toast notifications so I can't comment on that. The MSDN documentation should provide you with enough information to use the API. Regarding timers, I don't personally recommend the Windows::System::Threading namespace as it's not particularly efficient or simple, but if you want to go down that route then you need to create a periodic timer via the static CreatePeriodicTimer method and provide it with a TextBlock captured by value. Then within the handler you must get the TextBlock's dispatcher and call RunAsync given a second handler that also captures the TextBlock by value. Within this second handler you can update the TextBlock as you're now on the correct UI thread to do so. You can also avoid all of the captures by using a member so long as you ensure the lifetime of the TextBlock. Here's an example that updates the TextBlock every 5 seconds:

```C++
using namespace std::chrono;
using namespace Windows::Globalization::DateTimeFormatting;
using namespace Windows::System::Threading;
using namespace Windows::UI::Core;
using namespace Windows::UI::Xaml::Controls;

void Sample(TextBlock const& block)
{
    ThreadPoolTimer::CreatePeriodicTimer([block](ThreadPoolTimer const&)
    {
        block.Dispatcher().RunAsync(CoreDispatcherPriority::Normal, [block]
        {
            DateTimeFormatter formatter(L"longtime");
            block.Text(formatter.Format(clock::now()));
        });
    },
    5s);
}
```

A simpler and more efficient approach is to use coroutines. You can use the apartment_context object to capture the context for the UI thread, use an efficient thread pool timer to wait a few seconds, switch back to the UI thread, and then update the TextBlock. Here's an example of that:

```C++
using namespace std::chrono;
using namespace Windows::UI::Xaml::Controls; 
using namespace Windows::Globalization::DateTimeFormatting;

fire_and_forget Sample(TextBlock block)
{
    apartment_context ui_thread;

    while (true)
    {
        co_await 2s;
        co_await ui_thread;
        DateTimeFormatter formatter(L"longtime");
        block.Text(formatter.Format(clock::now()));
    }
}
```

Notice that the coroutine captures the TextBlock by value. Hope that helps.

**Comment by mediabuff** [comment]
The first approach is cancellable any time, how would you go about doing that in the second approach

**Comment by gettf** [comment]
Both code works.
I thought CreatePeriodicTimer is factory method, and setup a member, but compiler report threadpooltimer has no default constructor.
What's the lifetime of the timer instance return from CreatePeriodicTimer? it's created and living in pool?

Prefer approach 2,  can compute wait time to resume at fixing timepoint, it's great and simpler.
Didnt know apartment_context is UI and can be waited. and datetimeformatter is in api.    
It's a DEMO code than I want in api docs. 
Thank you Kenny.

**Comment by eklipse2k8** [comment]
@mediabuff it's a simple C while loop, so you can just pass in a cancel token that changes to false to exit the while loop. If you want to interrupt the formatter, you can also check for the cancel token before switching back to the ui thread.
