### ISSUE TITLE
Request : DataTemplate Sample

### ISSUE THREAD

**Issue by rvinothrajendran** [Microsoft/cppwinrt#273]
Hello Team,
Can you please upload any sample using DataTemplate in code-behind page.
Thanks 
Vinoth.

**Comment by kennykerr** [comment]
@DefaultRyan can correct me if I'm wrong, but it sounds like this would require XAML compiler support and that hasn't shipped yet.

**Comment by rvinothrajendran** [comment]
@kennykerr Please upload Image control sample

**Comment by kennykerr** [comment]
I don't have such a sample available.
