### ISSUE TITLE
how to solve the optional header issue

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#278]
I downloaded the latest winrt headers butit requires the "optional" header which is an c++17 feature. How do I run the new cppwinrt under visual studio 2015 pro?

**Comment by kennykerr** [comment]
The latest version only supports Visual Studio 2017 version 15.3 or later. If you need to compile with Visual Studio 2015 you'll have to use an older version of C++/WinRT.

**Comment by Scottj1s** [comment]
Such as the February 2017 Release, as noted in the change log.
