### ISSUE TITLE
Question: Add support for std::byte

### ISSUE THREAD

**Issue by jonitis** [Microsoft/cppwinrt#280]
Hello,

Since new cppwinrt relies on C++17 and STL now includes the std::byte implementation it immediately caused conflicts with SDK rpcndr.h that uses byte typedef in global scope. It was good excuse to try (again) convert code from uint8_t to std::byte. Once all user code is converted the interaction with cppwinrt is awkward, since arary_view\<T\> wrappers expect containers of uint8_t, and there is no straight conversion from/to std::byte. The only way to pass vector\<std::byte\> to API is to use array_view constructor with start/end pointer args and to explicitly cast pointers:

        const std::vector<std::byte> buffer = cmdSelect.GetBuffer();
        auto cmdSelectBuffer = CryptographicBuffer::CreateFromByteArray({
                reinterpret_cast<const uint8_t*>(buffer.data()),
                reinterpret_cast<const uint8_t*>(buffer.data() + buffer.size())
            });

- I would like to know what approach will you choose in future in cppwinrt to provide transparent conversion from c++ containers containing std::byte and ABI layer expecting buffers of "unsigned char"?
- Do you think conversion  between these buffers should be automatic or user must explicitly call some conversion function?

I've experimented with providing alternative constructors to array_view\<T\> that allow to completely transparently pass any container of std::byte to array_view (my template-fu was not enough to make initializer_list work as I wanted). It worked fine for my test program, but probably there are many other scenarios that I am not aware of. Not yet sure whether same changes required to com_ptr\<T\> as well.

See my std::byte aware array_view\<T\>:
https://gist.github.com/jonitis/797712c7b8c61fb29cc9f06e675f1fff

Thanks in advance

**Comment by kennykerr** [comment]
Thanks for the suggestion. We are evaluating whether to support `std::byte` directly. Although I like the functionality of `std::byte`, I am of the opinion that it was very poorly named. Given that Windows has included a type alias called `byte` for time immemorial (at least as far back as the Windows NT 4 SDK, but likely much earlier), following the convention of the [fixed width integer types](http://en.cppreference.com/w/cpp/types/integer) (such as `byte_t`) might have been a more practical choice to encourage wide adoption.

**Comment by kennykerr** [comment]
We are unlikely to make such a change at this stage due to compatibility with existing code that uses both the Windows SDK and the C++ standard library. There are efforts to modernize the Windows SDK, but that's another matter. There's also nothing wrong with using uint8_t. Keep in mind that while we require a C++17 compiler and embrace much of modern C++, we are under no obligation to embrace all of it. For example, there's no value in us using std::future, std::function or std::shared_ptr since we have alternatives that are more suitable to WinRT.

**Comment by jonitis** [comment]
Thank you for clarification.
