### ISSUE TITLE
[Question] How to add DualApiPartitionAttribute to WinRT class?

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/cppwinrt#281]
Hi, I'm working now on a Desktop Bridge app that is to be "extended" by a WinRT component, and I'm considering using C++/WinRT for that. 

So far I managed to use cppwinrt.exe compiler to make a WinRT component, and I can even use it from my app. But as far as I know, the WinRT class should be marked with [DualApiPartitionAttribute](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.dualapipartitionattribute) to indicate that it can be used by a desktop app. 

How can I mark my C++/WinRT class with this attribute? Do I even need this? Thanks!

**Comment by Scottj1s** [comment]
It is not necessary to mark your class with the DualApiPartitiionAttribute immediately, since cppwinrt does not currently enforce it in the projected headers.  However, we are considering add that support, so you may want to add it preemptively.

**Comment by Alovchin91** [comment]
@Scottj1s Thanks for the answer!
How can I add it preemptively?

**Comment by Scottj1s** [comment]
I just mean to attribute your runtime class in preparation for when the attribute is implemented/enforced, like so:
[dualapipartition(NTDDI_WIN10_RS3)]
runtimeclass Foo { ... }

**Comment by Alovchin91** [comment]
@Scottj1s This is exactly what the question is about: **how** can I mark the runtimeclass with this attribute? :) Specifying `[dualapipartition(NTDDI_WIN10_RS3)]` in .idl file doesn't work.

**Comment by kennykerr** [comment]
I wouldn't worry about dualapipartition. This is only intended for use by OS components and is mainly used as a hint for the documentation folks that certain APIs can be called from desktop apps. Feel free to ignore it as we do. 😉

**Comment by Alovchin91** [comment]
@kennykerr Thank you for the explanation! :) That's exactly what I needed)
