### ISSUE TITLE
error C2039: 'GetSystemTimePreciseAsFileTime': is not a member of '`global namespace''

### ISSUE THREAD

**Issue by aramovski** [Microsoft/cppwinrt#284]
Hello

I get this error message after trying to call new UWP functions with C++/WinRT,  e.g.

`winrt::Windows::Perception::Spatial::SpatialLocator mLocator`

I did NOT install the latest Windows 10 Insider Preview release but using SDK 10.0.16299.0 and VS2017.

Thanks for any advise or hint to solve this problem!

**Comment by kennykerr** [comment]
GetSystemTimePreciseAsFileTime is a standard function provided by the Windows SDK (Windows.h) and is required by C++/WinRT. It should be present as long as you're using an unmodified Windows SDK and have not customized the build environment to exclude the standard inclusion of headers. You should be able to confirm this with a simple console app:

```C++
#include <windows.h>

int main()
{
    FILETIME ft;
    ::GetSystemTimePreciseAsFileTime(&ft);
}
```

**Comment by aramovski** [comment]
@kennykerr thanks for the fast reply! Indeed the project im working on customised the build environment regarding Windows Versions...
