### ISSUE TITLE
Boost_1_65_1 

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#285]
Is there any reason why c++/winRT cannot use Boost?

**Comment by kennykerr** [comment]
There should be no reason why you cannot use C++/WinRT with Boost as with any other C++ library. They are however independent libraries and there's no reason why they should have interdependencies.  C++/WinRT is meant to be a thin layer between WinRT and standard C++. You can of course write other libraries on top of both C++/WinRT and Boost that might provide added value, but that's beyond the scope of C++/WinRT itself.

**Comment by JackDetrick** [comment]
The problem is that Boost is using std::unary_function

**Comment by kennykerr** [comment]
Ah, well std::unary_function was removed in C++17 so it sounds like you have a problem with Boost. 😉
