### ISSUE TITLE
UWP Community Toolkit

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#286]
Are there plans for the toolkit to include c++/winrt

**Comment by kennykerr** [comment]
Unfortunately, the UWP Community Toolkit is written in C# and is thus largely a set of helpers classes for .NET apps only. There have been some discussions about supporting C++, but that would involve rewriting most/all of it in C++ for greater reach.

**Comment by JackDetrick** [comment]
Thanks - that helps in my planned # to C+.winrt convrsion
