### ISSUE TITLE
How can I use C++/WinRT to render a PDF file? 

### ISSUE THREAD

**Issue by sergyu91ma** [Microsoft/cppwinrt#288]
Hi,

Can you help me with some sample code to render a PDF file with cppwinrt? 

I got stuck here so far. 

`
Storage::Pickers::FileOpenPicker picker;
		picker.SuggestedStartLocation(Storage::Pickers::PickerLocationId::DocumentsLibrary);
		picker.FileTypeFilter().Append(L".pdf");
		Storage::StorageFile file = co_await picker.PickSingleFileAsync();

		if (!file)
		{
			CoreApplication::Exit();
			return;
		}

		auto pdf = PdfDocument::LoadFromFileAsync(file);

		  

		Concurrency::create_task([file]()
		{
			return PdfDocument::LoadFromFileAsync(file);
		}).then([](Concurrency::task<PdfDocument> & task)
		{
			auto pdfdoc = task.get();
			//pdfdoc->GetPage(0); // no GetPage method
			 

		});

`

Thanks.

**Comment by kennykerr** [comment]
I would avoid mixing coroutines (co_await) and concurrency tasks. It's simpler and more efficient to wait with coroutines alone. Something like this should work:

```C++
FileOpenPicker picker;
picker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
picker.FileTypeFilter().Append(L".pdf");
StorageFile file = co_await picker.PickSingleFileAsync();

if (!file)
{
    co_return;
}

PdfDocument document = co_await PdfDocument::LoadFromFileAsync(file);

PdfPage page = document.GetPage(0);
```

**Comment by sergyu91ma** [comment]
Thanks @kennykerr . I have learned a lot from your pluralsight videos. 

Looks like intellisense from VA and/or ResharperC++ doesn't work with cppwinrt, that's why my confusion too. I work on an win app (https://myco.yonan.ro/) and we use a lot COM here. I would like to rewrite native COM parts and use more of cppwinrt as it`s more readable and a lot easier to write. 

BTW Keep up the good work! I like a lot cppwinrt and what you did. C++/CX was a big fail IMO.  

![image](https://user-images.githubusercontent.com/6949205/33575131-48ebfdd0-d944-11e7-9ae7-8289596d6128.png)

**Comment by kennykerr** [comment]
Thanks! C++/WinRT is a challenge to parse for today's C++ compilers. IntelliSense parsers tend to be a generation behind the compiler itself. Hopefully these tools will catch up soon.

**Comment by sergyu91ma** [comment]
Hi,

I managed to finish the PDF rendering. I can provide the sample to add it to Samples if that is ok with you. 
Thanks.

**Comment by kennykerr** [comment]
Hi @sergyu91ma - thanks for the offer. We're not looking to grow our sample collection at the moment as there is a time commitment to keep them up to date and relevant. Feel free to link to your repo with the sample. That way folks with related questions will easily be able to find it.
