### ISSUE TITLE
How do you convert from cppwinrt type to implementation

### ISSUE THREAD

**Issue by xprssn2** [Microsoft/cppwinrt#289]
Let's say I have an implementation
```cpp
namespace winrt::Native::implementation {
    struct BezierControlPoint : BezierControlPointT<BezierControlPoint>{...};
}
```
and a function
```cpp
void winrt::Native::implementation::BezierControlPointCollection::Remove(winrt::Native::BezierControlPoint const& controlPoint)
```

How do I get back the `winrt::Native::implementation::BezierControlPoint` from `Native::BezierControlPoint const&`?
I walked up the call stack and deduced this which works for now, but I think it's a dirty hack, especially since it involves `reinterpret_cast`.
```cpp
template <typename D, typename I>
D& to_impl(I const& from) noexcept
{
    return reinterpret_cast<impl::produce<D, impl::default_interface<I>::type>*>(get_abi(from))->shim();
}
```

**Comment by kennykerr** [comment]
There is a helper function called `from_abi` that will do this for you:

```C++
Namespace::Type object = ...
auto p = from_abi<implementation::Type>(object);
```

The resulting `implementation::Type*` is the implementation of the object. Keep in mind that there is no check to confirm whether or not this is in fact your implementation. The `from_abi` function just performs the pointer adjustment assuming the object is exclusive to your implementation.

**Comment by xprssn2** [comment]
I get this error, which is why I wrote `to_impl` as a near duplicate except it uses `reinterpret_cast` instead of `static_cast`.
```
c:\program files (x86)\windows kits\10\include\10.0.17040.0\cppwinrt\winrt\base.h(4680): error C2440: 'static_cast': cannot convert from 'IUnknown *' to 'winrt::impl::produce<D,I> *'
        with
        [
            D=winrt::Native::implementation::BezierControlPoint,
            I=winrt::Native::BezierControlPoint
        ] (compiling source file BezierControlPointCollection.cpp)
c:\program files (x86)\windows kits\10\include\10.0.17040.0\cppwinrt\winrt\base.h(4680): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast (compiling source file BezierControlPointCollection.cpp)
```
Source lines
```cpp
void BezierControlPointCollection::Remove(Native::BezierControlPoint const& controlPoint)
{
// ...
    com_ptr<BezierControlPoint> impl;
    impl.attach(from_abi<BezierControlPoint>(controlPoint));
              //[--------------Error here----------------]
// ...
}
```

**Comment by kennykerr** [comment]
Ah, apologies. I simplified `from_abi` a while back, but it hasn't made it into the public SDK yet. The syntax I described above will work in a future update. For now, you need to include a second type parameter indicating the interface (of the class) being converted. For example:

```C++
Namespace::Type object = ...
auto p = from_abi<implementation::Type, Namespace::Interface>(object);
```

In your example, it might look something like this:

```C++
void BezierControlPointCollection::Remove(Native::BezierControlPoint const& controlPoint)
{
    com_ptr<BezierControlPoint> impl;
    impl.copy_from(from_abi<BezierControlPoint, Native::IBezierControlPoint>(controlPoint));
}
```

Note that the interface pointer returned by `from_abi` is still owned by the `controlPoint` object. If you want to store it in a `com_ptr<T>` then you must give it its own reference. That is why I switched your example from using `attach` to `copy_from`.

**Comment by xprssn2** [comment]
I changed my `to_impl` to
```cpp
template <typename D, typename I>
D* get_impl(I const& from) noexcept
{
    return&static_cast<impl::produce<D, impl::default_interface<I>::type>*>(get_abi(from))->shim();
    //                                  [            new bit             ]
}
```
which is now near identical to `from_abi` in the public SDK except the new bit and it works with the exact same syntax as your first `from_abi`. I assume that's the simplification.
