### ISSUE TITLE
command line of any (or an) windows executable module

### ISSUE THREAD

**Issue by DBJDBJ** [Microsoft/cppwinrt#291]
I need to produce command line data of any of several kinds of WIN 10 executable modules.  Modern C++ abstraction to hold this is vector<string_type> ... where sting_type is wide or narrow string. 

Is it wide or narrow depends on the stdlib.h value __wargv . If and when it is null we use it or we use __argv. 

Sound simple? But after several days (!) of cogitation the most modern C++ solution implemented in msvc I could come up with is this:

```
 #include <stdlib.h>
namespace {
#define _CRT_DECLARE_GLOBAL_VARIABLES_DIRECTLY

const auto  wargv_ = (__wargv);
const auto  argv_ = (__argv);
const auto  argc_ = (__argc);

#undef _CRT_DECLARE_GLOBAL_VARIABLES_DIRECTLY

namespace {

    using wvecT = std::vector<std::wstring>;
    using nvecT = std::vector<std::string >;

    // wargv_ !=  nullptr
    inline auto decide(std::true_type tt) {
        return wvecT{ wargv_, wargv_ + argc_ };
    }
    // wargv_ ==  nullptr
    inline auto decide( bool ft) {
        return nvecT{ argv_, argv_ + argc_ };
    }
}

auto cli_data = []() {
    return decide( 
        wargv_ != NULL 
        ? std::true_type{}
        : false
    );
};
} // nspace

```
usage is then simple:

```
auto my_cli = cli_data() ;
// 
auto  this_module_file_name = my_cli[0] ;
```

This is the solution even after VS 15.5 update.  Can anyone offer a better one using msvc? 

How is (if it is) cppWinRT obtaining the command line of executable module it is running in?

Please advise ...

**Comment by Scottj1s** [comment]
This question isn't specifically about C++/WinRT usage.  I'd advise posting it to a more general forum like stackoverflow.

**Comment by tim-weis** [comment]
A C++/WinRT application obtains the command line like any other application: By calling [GetCommandLine](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683156.aspx) (either directly, or by using the facilities provided by the CRT), which reads out the value stored in the [PEB](https://msdn.microsoft.com/en-us/library/windows/desktop/aa813706.aspx). There's also a convenience implementation ([CommandLineToArgvW](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391.aspx)) to parse the command line and decompose it into individual arguments.

If "modern" is your goal, you shouldn't be using ANSI encoding at all. Once you remove all ANSI clutter from your code, you'll see the complexity significantly go down.

Besides, if what you really want is the module name of the executing code, call [GetModuleFileName](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683197.aspx) (and friends). This returns the real thing, and isn't subject to someone passing you unexpected command line arguments.

At any rate, this is really a generic question about any Windows executable, not related to C++/WinRT at all, so you might want to consider taking it to another site, as suggested by Scott Jones.

**Comment by DBJDBJ** [comment]
@Scottj1s 

cppWinRT is astonishing work. The context of my comments is that cppWinRT problem is msvc. By msvc team own admission C++17 is only 75% implemented in msvc. cppWinRT mandates C++17. But which compiler is to be used, one has to ask?

**Relevance to the cppWinRT** comes from the fact that the msvc (+ win10 sdk ) code I have presented has obvious utility but it is ridiculous because it is a workaround so that it is possible to compile it in msvc the latest ... whatever is the rev number after VS 15.5 update ...

> Workaround done in order that msvc can compile something are leaving technical debt inside cppWinRT.

1. By " modern", I mean nothing else but "modern C++" , C++17 and so on 
2.  I do not want to use WIN32 API to obtain command line of the executable module 
3. __wargv, __argv, __argc are in the stdlib.h and as a such perfectly OK to use and legal in UCRT.

cppWinRT mandates C++17. The code above is simple if using gcc/clang ... it is not of course part of cppWinRT but shows what simple lambdas msvc C++17 can not do currently, and leaves one wondering about the workarounds cppWinRT team had to do to make it compile with  msvc c++17.

Good example revolves around the modern C++ code  to obtain command line as a vector of narrow or wide strings. Core lambda for that  is still [not possible in msvc but it is in gcc and clang](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHIBSAJgGY8AO2QAbZlgDU3fgGEGBYsOAzs3AAwBBPoJHipM2QDdMyIsVUbtWoQEMAtpgYAHW%2B0kAjWwzzIA%2Bs7EqB6imPbSAOwAQpLSWrGStsxEkvYMRv7oqE5%2BQqgEfmj2znih0vwAItIArFHc1VUQicmokn4KSkLAkgCUcZoJkgC0qpIK6CAgJmYkhpJYYgQAns6YEO2Kyn2W8ZF1u7HEmASsQmMEE1Om5oYLosur6x1bltHcERUy%2BwORn/zf70%2BWiswgIqVswggoMSxGAyFIkmQCFsxAAVDDgEZ6nUGj0rO9vrEkilpuUql4fP5AsFQvZJmkMn4sjk8gUiiVQhBxpNnl0CYC8f8rIdjqdJOpygCPlZOD1SKIuNVOKQhFx1MrUFxZHw6rwYkxWO4dLRlQQ1bK5QBrEC8aryrgAFmVqs46tIms4yoYIHUpDNrtlpDgsBgiBQqGKpUwZAoEHZUeIIGAEV4pAAZqUCNHvRAPObSB5hCillwTaQio4hAQAPJCUQlgOkLD2WxdUL5/BHMx4EzexuYAAepmSHE4ZdBmAVjc2dIDctEeA83sgctQzgIeFQQj7Q3GMgqyB1OtoAC8vSw2BxaPPFc78x6BwAOABsQ2fDskcOQkgiADpeJIEC4IQJDSAI9CSLIEYctGYH8Neprmj0VogNUvpTk6pB0mhKr3lwXo%2Bn6SFBqGEBICwBDOMk5CUPGoSJvQmD4OYdA3pwSq4Y2HrGpIADuhAIJIT6vu%2Bn7IN%2Bf68Ihc5yggmC2FgiYQGxmHYb6Lpuh6BG%2Bv66rIaQ1q2vanD8HeXH4URc4kfAwZhnR0Y0XG0EJigoitsAaG%2Bhm9zZpQeaNoWdjEA2ZYVpgVa1vWHZhO57aNp21w9k4%2BaDsOWalsqE5Tm6M7EQuS7wKu66btuXC7hc%2B6Hnqx5nowF7sKxxkcRpGpcMJb4fmI7mSNUv7qH1gHAeYcEQVBkb0XBvA9NJekofw/C/vNS3LStxmqah6l4Z6jCEbpga2WRIAUVRBCOfZiapkxIEMWxzVbToAH8QQgntaJXVdD1fV9TNFqkHJCnRpQKnKmpnGaRZ3o6UhKFGVOplg61217XKB2kUg51nc59GubQACcfj8Km3lZsQOb%2BW6gXFhl5YRpWNZ1g2brNrFo5M3gXYbr2KVDsgI7U1l%2Ba5VZ%2BXLsp7rFVuO57pUVW6lEp7noaV63WZ4OcMJkgALIAMoAGqyJIeOSLw6i0BEkgAEoACoAOqDcxoHGgiY0wcQcH8NNlmzQZNp2hhIMbQj7oQ7txEHeRyQnZj42A/wpBXSx15NariM6PwfECUJL5a3rBtGybZuW7bP36f9ilA2tAc4S1wfbZDXu/YZftcPDNdaQ3%2BlTlJQft8jcomKTJUgA6QA%3D%3D) .. This simple lambda makes simple API possible:

> auto cli_data = obtain_cli () ; 
> // cli_data is wide or narrow strings vector, depending on the runtime situation

**Comment by VSChawathe** [comment]
Assuming Compiler Explorer is using the newest 15.5 preview 4 (1912) and not 15.2 (1910) as the VS version, the argument to it must still be replaced from -std=c++1z to /std:c++latest
Lambdas arrive with C++11. Have you thought of more modern approach, like say, [structured bindings](https://www.fluentcpp.com/2017/10/23/results-expressive-cpp17-coding-challenge/)?
