### ISSUE TITLE
dynamic_cast_helper

### ISSUE THREAD

**Issue by ChMar** [Microsoft/cppwinrt#292]
The 10.0.17040.0 SDK ships with the cppwinrt integrated in it. I set 
`<LanguageOverride>CppWinRT</LanguageOverride>`
Inside the .vcxproj MSBuild in order to activate the XamlCompiler for CppWinRT and while the MSBuild task start to generate files they use an undefined `dynamic_cast_helper` as well as an undefined `winrt::unbox<T>`.  Any solution to how to implement the `dynamic_cast_helper` and `winrt::unbox<T>`

**Comment by kennykerr** [comment]
The 17040 SDK does not include working XAML compiler support for C++/WinRT. We hope to have a preview available in the new year.
