### ISSUE TITLE
Windows RT for Fall Creators Update 16299 - Windows RT Components cannot be used in WinJS application

### ISSUE THREAD

**Issue by antlhuede** [Microsoft/cppwinrt#293]
To replicate this issue follow this tutorial:
[https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript)

All you need is a WinJS application and a WindowsRT Component.

Then explicitly set the targeted  Universal Windows version to (Windows 10 Fall Creators Update 10.0 build 16299) for both the WinJS app and WindowsRT component.

Trying to reference imported Windows RT Components in a WinJS application targeting 16299 fails with "Unknown JavaScript Error", whereas dropping the targeted version to 15063 or below, this issue does not occur.

**Comment by BenJKuhn** [comment]
Hi Anthony, this issue does not sound related to the C++ /WinRT project. As such, we're not going to address it in this forum. However, I have made a note of this issue and will route it to the appropriate team.

A more appropriate forum for this question would be:
   https://social.msdn.microsoft.com/Forums/en-US/home?forum=wpdevelop

Thanks,

Ben
