### ISSUE TITLE
RangeChecks instrumentation code detected an out of range array access.

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/cppwinrt#294]
This line is triggering an exception.

```
auto types = winrt::single_threaded_vector<winrt::hstring>({ L"Option1" });
```

Unhandled exception at 0x00007FFD0C6B0D60 (ntdll.dll) in App.exe: RangeChecks instrumentation code detected an out of range array access.

**Comment by eklipse2k8** [comment]
It looks like this works:

```cpp
  std::vector<winrt::hstring> types;
  types.push_back(L"Option1");
```

but this triggers that exception:

```cpp
  std::vector<winrt::hstring> type = { L"Option1" };
```

**Comment by kennykerr** [comment]
Hi Matt, I'm unable to reproduce this. Can you give us a bit more context, compiler version, anything that would narrow it down?
