### ISSUE TITLE
Bluetooth Beacon usage

### ISSUE THREAD

**Issue by gclarkii** [Microsoft/cppwinrt#295]
Greetings,

I must be brain dead.  For the life of me I can not figure out how to use a bluetooth device to create a beacon.  Can someone give a sample?  All of the online samples are for C# and I'm just hitting too many walls.

Thanks,
Gary

**Comment by RobJellinghaus** [comment]
Um... are you sure you are asking your question in the right project?  Why do you think this project has anything to do with Bluetooth?

**Comment by DefaultRyan** [comment]
Do you have a link to the C# examples? If they’re using the WinRT API, it should be straightforward to convert.

Sent from my Windows 10 phone

________________________________
