### ISSUE TITLE
Support for tiling ImageBrush

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/cppwinrt#296]
TileMode doesn't seem to be available in the ImageBrush class, so it appears there is no way to tile a background in cppwinrt using repeated tiles (the default one-tile-per-background does work). Or maybe I'm missing something. Is this feature in the works? Thanks.

**Comment by kennykerr** [comment]
C++/WinRT doesn't directly support rendering of any kind. It is merely a language projection of the [Windows API](https://docs.microsoft.com/en-us/uwp/). If you find a suitable API that may help to achieve your goals, you should be able to use C++/WinRT to access the API from C++.

**Comment by jevansAN** [comment]
Maybe I'm misunderstanding something, then. The documentation for ImageBrush says that it can be used to fill a background, and that the TileMode property determines whether the image is stretched to fill the background or alternatively is repeated. The ViewPort property provides the offset and size into the bitmap image to  be repeated. But neither of those properties appears in ImageBrush when I examine it in my project, and I noticed a comment from someone back in 2012 saying that tiling of background images had not been included in winrt - as of that time. Do you know of a way to address those properties of ImageBrush from a cppwinrt project?

**Comment by jevansAN** [comment]
I think I'm starting to get it, though. Apparently tiling with an ImageBrush was never implemented in winrt, so there's just no access to those properties from cppwinrt. Too bad, but thanks.

**Comment by kennykerr** [comment]
I think you may be confusing the .NET Framework APIs with the Windows APIs. There are some classes with similar names, but they are not interchangeable. The link I shared above will give you the documentation for the APIs available via C++/WinRT.

**Comment by jevansAN** [comment]
That's exactly what I was doing. I have been mixed up about the various Win technologies using the same class names. I appreciate your help.
