### ISSUE TITLE
Doesn't build with VS "15" Preview 5 Toolset.

### ISSUE THREAD

**Issue by smj389** [Microsoft/cppwinrt#3]
Reproduction steps: Open XAMLCode sample. In properties, change the platform toolset to Visual Studio 2016 (v41). Compile.
I have attached the error
[XamlCode.txt](https://github.com/Microsoft/cppwinrt/files/527628/XamlCode.txt)

**Comment by kennykerr** [comment]
We’ll get an update out that also supports Visual Studio “15”. Thanks for the feedback!
