### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by geminik23** [Microsoft/cppwinrt#30]
When I try to build UWP Project (with compile option /await /std:c++latest, and min. version '10.0.14393.0') to use cppwinrt library, 
there's compile error like this

```
1>  pch.cpp
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\collection.h(2174): error C2039: 'unary_function': is not a member of 'std'
1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\unordered_map(14): note: see declaration of 'std'
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\collection.h(2174): error C2504: 'unary_function': base class undefined
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\collection.h(2174): error C2143: syntax error: missing ',' before '<'
```

**Comment by LYP951018** [comment]
Try removing
```cpp 
#include <collection.h>
#include <ppltask.h>
```
in `pch.h`.

**Comment by MikeGitb** [comment]
Unary function has been removed from the c++17 standard (and was deprecated since 11). I believe `latest` tracks this, but I think there is a precompilation switch that brings it back

**Comment by raffaeler** [comment]
Adding the following definition before any other in pch.h should solve
#define _HAS_AUTO_PTR_ETC 1

**Comment by geminik23** [comment]
After adding #define _HAS_AUTO_PTR_ETC 1, compile works. Thank you.

**Comment by raffaeler** [comment]
And I pass my thanks to @kennykerr :)

**Comment by kennykerr** [comment]
As Raffaele mentioned, this is a limitation in collection.h but the workaround is simple enough.
