### ISSUE TITLE
Attempting to use UWP AudioGraph API via cppwinrt -> unresolved AudioGraph symbols

### ISSUE THREAD

**Issue by RobJellinghaus** [Microsoft/cppwinrt#301]
I am working on a cppwinrt library wrapping the Win10 AudioGraph API.

My first stab at it is here: https://github.com/RobJellinghaus/cppwinrt
And specifically: https://github.com/RobJellinghaus/cppwinrt/tree/master/AudioGraph

I forked Kenny's cppwinrt samples repository, copied the Video sample (didn't even change the GUIDs yet), and ported the code from the UWP-universal-samples AudioCreation Scenario1 playback example, which is in C#.  The port was staggeringly easy to get to compile -- cppwinrt is an amazing thing.  I'm using insider build 17063 with the insider SDK version 17061.  (The problem below should be reproducible by cloning the above repo and trying to build the AudioGraph sample, after updating to your Win10 SDK version of course.)

Unfortunately, while cl.exe is happy, link.exe is not:

`LNK2019	unresolved external symbol "public: class std::chrono::duration<__int64,struct std::ratio<1,10000000> > __cdecl winrt::impl::consume_Windows_Media_Audio_IAudioFileInputNode<struct winrt::Windows::Media::Audio::IAudioFileInputNode>::Duration(void)const " (?Duration@?$consume_Windows_Media_Audio_IAudioFileInputNode@UIAudioFileInputNode@Audio@Media@Windows@winrt@@@impl@winrt@@QEBA?AV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@XZ) referenced in function "public: struct winrt::fire_and_forget __cdecl App::OnActivated$_ResumeCoro$2(struct winrt::Windows::UI::Core::CoreWindow,struct winrt::Windows::UI::Core::WindowActivatedEventArgs)" (?OnActivated$_ResumeCoro$2@App@@QEAA?AUfire_and_forget@winrt@@UCoreWindow@Core@UI@Windows@3@UWindowActivatedEventArgs@5673@@Z)`

This looks to be complaining about a missing implementation of the "TimeSpan IAudioFileInputNode::Duration()" method, which certainly exists in the cppwinrt headers, but does not seem to exist when linking against WindowsApp.lib.

I have been unable to find any indication that linking against any other library than WindowsApp.lib should be necessary for using AudioGraph.  Did I miss something?  Or is there some other aspect of the AudioGraph APIs that makes them unlinkable from cppwinrt?

**Comment by kennykerr** [comment]
Did you perhaps forget to `#include "winrt/Windows.Media.Audio.h"`?

**Comment by RobJellinghaus** [comment]
Why yes, yes I did.  Overlooked those in pch.h.  Haven't previously seen a failure to include a header cause a link-time failure only, but modern C++ is modern :-)

I pushed the fixes.  Would you accept a pull request for this new sample back into your kennykerr/cppwinrt repo?

I plan to next write a P/Invokable wrapper for AudioGraph, such that I can use AudioGraph from Unity UWP and desktop apps (Unity desktop apps are pretty much stuck with P/Invoke as that's all that the Mono runtime supports).  cppwinrt looks like it will save me enormous amounts of time and boilerplate, as I'm already familiar with C# AudioGraph programming and cppwinrt maps almost line-for-line to it.  Thanks really very much for your work here!

**Comment by xprssn2** [comment]
You might want to take a look here before moving on
https://docs.unity3d.com/Manual/IL2CPP-WindowsRuntimeSupport.html

**Comment by kennykerr** [comment]
Hi @RobJellinghaus - thanks for offer. I'm actually trying to keep the samples at https://github.com/kennykerr/cppwinrt to a minimum as it is a bit of work to maintain them with every new release of the Windows SDK. Mainly I'm trying to limit the samples to unique scenarios that people typically have questions about, how to use Windows.UI from the desktop, how to load a custom component, how async works, and so on.

**Comment by BrentRe** [comment]
Hi Rob,
    To give more background on why you encountered this C++ link time error...

    When you explicitly #include a C++/WinRT header file for a namespace, we transitively pull in all required header files to declare all necessary function prototypes plus the header files to define all necessary function implementations for the types in the explicitly included namespace.

   However, types in the explicitly included namespace likely reference types in other namespaces. For those implicitly referenced types, we only pull in the headers files needed to declare the function prototypes. We don't pull in the definitions of the implementations.

    That allows everything to compile with minimal overhead as the compiler can see the declarations for everything referenced - explicitly or implicitly. However, when you explicitly use/call one of the types members in one of the implicitly included namespaces, the linker will not find the implementation. Explicitly including the namespace of the type mentioned in the linker error pulls in the implementation headers soliving the problem.

    Our only (currently available) alternative would be to always pull in all ~40 MBs of header files, which negatively affects build time. So we don't do that. Especially as, in the near future, when C++ Module support is ready, we'll have a C++/WinRT module that you can reference instead of header files, thus solving a number of issues, including this one.

**Comment by RobJellinghaus** [comment]
@xprssn2 -- Thanks, but I need my library to work on desktop, not only UWP, and it seems the Unity Windows Runtime support doesn't exist on desktop.

@BrentRe  -- Appreciate the information!  Thanks.  Can't wait for modules to ship for real in 2018.
