### ISSUE TITLE
Sample Suggestion

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#304]
Could we please have a Build.bat for one of the larger samples such as XamlMarkup showing command lines and switches for any tool used such as cl, link, midl / midlrt?.

It could be instructive to see the detail that MSBUILD hides.

**Comment by Scottj1s** [comment]
@MRahilly, thanks for the suggestion.  We do have a simple [CL sample](https://github.com/Microsoft/cppwinrt/blob/master/10.0.16299.0/Samples/CL/build.bat) that shows what C++ switches are necessary.  For general tracing of any tool invoked during the build, I'd recommend turning on verbose MSBuild diagnostics, either from within VS via Tools|Options|Projects and Solutions|Build and Run, or on the command line via /clp:v=d/diag.  I doubt we will create a complex sample built from a batch file, as it doesn't address dependencies and so on.
