### ISSUE TITLE
CompositionVirtualDrawingSurface

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/cppwinrt#306]
I'm looking into some way to main a large scrolling image area that needs only partial redraws and supports scaling, etc. CompositionVirtualDrawingSurface appears to be available in winrt but some data types required for it don't seem to be buildable using cppwinrt - e.g. SizeInt32 is recognized as a struct but I cannot find a way to declare it and specify its members. Can anyone tell me if CompositionVirtualDrawingSurface is in fact usable in cppwinrt? Thanks.

**Comment by kennykerr** [comment]
Yes, the Windows.UI.Composition API is fully supported by C++/WinRT. `SizeInt32` is defined in the Windows.Graphics namespace, so be sure to include the appropriate C++/WinRT headers:

```
#include "winrt/Windows.UI.Composition.h"
#include "winrt/Windows.Graphics.h"
```

**Comment by jevansAN** [comment]
Thanks very much - I was missing those includes. Watching now a presentation on the Visual Layer: Composition API, which is apparently addressable with standard C++ and looks very good. Guy actually mentioned music notation, which is what I do. Hope is reborn.

**Comment by jevansAN** [comment]
Here's one thing from the Windows.UI.Composition API that I can't seem to find supported: ElementCompositionPreview::GetContainerVisual(UIElement theElement) - I see ElementCompositionPreview::GetElementVisual(UIElement theElement) but the former seems to be absent. I'm looking through sample code in James Clark's presentation on the Visual Layer, which uses that (it also uses SolidColorVisual, and the Compositor method CreateSolidColorVisual(), which also don't seem to show up in the winrt includes. Is that source code just out of date?

**Comment by kennykerr** [comment]
Some of those APIs were in preview and subject to change - mostly minor name changes. I suggest you install the latest Insider SDK, as that will reflect the most up-to-date shape of these APIs.

**Comment by jevansAN** [comment]
Thanks - I joined the Insider program in, I think, November,  and thought I was getting automatic updates. I'll check that out.
