### ISSUE TITLE
StorageFolder - 	3 unresolved externals

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#308]
I am using a copy of of XamlButton, 

In this method
IAsyncOperation<int>  DataBase::ReadDataBase() {... 

I add this line of code...
StorageFolder _turboCalc = co_await ApplicationData::Current().LocalFolder().GetFolderAsync(L"MyFolder");

It compiles OK but the linker coughs up this:
Error	LNK2019	unresolved external symbol "public: struct winrt::Windows::Storage::StorageFolder 
__thiscall winrt::impl::consume_Windows_Storage_IApplicationData<struct winrt::Windows::Storage::IApplicationData>::
LocalFolder(void)const " (?LocalFolder@?$consume_Windows_Storage_IApplicationData
@UIApplicationData@Storage@Windows@winrt@@@impl@winrt@@QBE?AUStorageFolder@Storage@Windows@3@XZ) 
referenced in function "public: static struct winrt::Windows::Foundation::IAsyncOperation<int> 
__cdecl CalculatorClassLibrary::DataBase::ReadDataBase$_ResumeCoro$2(void)" 
(?ReadDataBase$_ResumeCoro$2@DataBase@CalculatorClassLibrary@@SA?AU?$IAsyncOperation@H@Foundation@Windows@winrt@@XZ)	
XamlButton	C:\C++_WinRT\XamlButton_CalcLib\DataBase.obj	1

..................................
Error	LNK2019	unresolved external symbol "public: struct winrt::Windows::Foundation::IAsyncOperation<struct winrt::
Windows::Storage::StorageFolder> __thiscall winrt::impl::consume_Windows_Storage_IStorageFolder<struct winrt::
Windows::Storage::IStorageFolder>::GetFolderAsync(struct winrt::param::hstring const &)const " 
(?GetFolderAsync@?$consume_Windows_Storage_IStorageFolder@UIStorageFolder@Storage@Windows@winrt
@@@impl@winrt@@QBE?AU?$IAsyncOperation@UStorageFolder@Storage@Windows@winrt@@@Foundation@Windows@3@ABUhstring@param@3@@Z) 
referenced in function "public: static struct winrt::Windows::Foundation::IAsyncOperation<int> 
__cdecl CalculatorClassLibrary::DataBase::ReadDataBase$_ResumeCoro$2(void)" 
(?ReadDataBase$_ResumeCoro$2@DataBase@CalculatorClassLibrary@@SA?AU?$IAsyncOperation@H@Foundation@Windows@winrt@@XZ)	

.........................................
Error	LNK2019	unresolved external symbol "public: static struct winrt::Windows::Storage::ApplicationData 
__cdecl winrt::Windows::Storage::ApplicationData::Current(void)" (?Current@ApplicationData@Storage@Windows@winrt@@SA?AU1234@XZ) 
referenced in function "public: static struct winrt::Windows::Foundation::IAsyncOperation<int> 
__cdecl CalculatorClassLibrary::DataBase::ReadDataBase$_ResumeCoro$2(void)" 
(?ReadDataBase$_ResumeCoro$2@DataBase@CalculatorClassLibrary@@SA?AU?$IAsyncOperation@H@Foundation@Windows@winrt@@XZ)	
XamlButton	C:\C++_WinRT\XamlButton_CalcLib\DataBase.obj

**Comment by BrentRe** [comment]
You are using the Windows::Storage::IApplicationData type but you failed to #include "winrt/Windows.Storage.h"

**Comment by JackDetrick** [comment]
Thanks...
