### ISSUE TITLE
Component sample fails to compile

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#309]
Here's the offending entry: (not found)

#include "winrt/Component.h"

**Comment by kennykerr** [comment]
Which component sample? Which SDK? Which compiler? More information would help. 😉

**Comment by JackDetrick** [comment]
The component sample is part of the 17069 group - Store, (1/15/2018). Visual Studio 2017 15.5.4
The sdk is 10.00.17069
The h. file not found is in App,cpp.  This also fails: using namespace Component;,

**Comment by kennykerr** [comment]
I just updated the [samples repo to the 17069 SDK](https://github.com/kennykerr/cppwinrt) and tested all samples with 15.5.4 and everything builds cleanly. Would you mind pulling the latest updates from github and performing a complete rebuild?

**Comment by JackDetrick** [comment]
It compiles - thanks Kenny
