### ISSUE TITLE
Why I can not use the winrtcpp in a library project

### ISSUE THREAD

**Issue by scuhappy** [Microsoft/cppwinrt#31]
I created a library project via UWP/virtual c++, it looks like this:
![image](https://cloud.githubusercontent.com/assets/4221635/19755487/eac6b454-9c48-11e6-8743-a29904ee5231.png)

and I create a class to list devices:(TServiceClient.cpp)

```
#include"pch.h"
#include"TServiceClient.h"
IAsyncOperation<int> TServiceClient::ListDevices(char16_t* devinfo)
{
    hstring selector = SerialDevice::GetDeviceSelector();
    DeviceInformationCollection deviceList = co_await DeviceInformation::FindAllAsync(selector);
    for (int i = 0; i < deviceList.Size(); i++)
    {
        int size = sizeof(deviceList.GetAt(i).Id().c_str());
        memcpy(devinfo, deviceList.GetAt(i).Id().c_str(), size);
        devinfo += size;
    }
    return deviceList.Size();
}
```

(TServiceClient.h)

```
#pragma once
#include"UWP_Lib.h"
class TServiceClient
{
public:
    IAsyncOperation<int> ListDevices(char16_t* devInfo);
};

```

Then build it, I get a error : 
![image](https://cloud.githubusercontent.com/assets/4221635/19755568/78212b40-9c49-11e6-9623-84c0d3658456.png)

Why does it happens? Thank you!

**Comment by scuhappy** [comment]
I find if I change the return type to "IAsyncAction" then it can be compiled.....

**Comment by kennykerr** [comment]
It's hard to tell without more information, but the compiler error indicates that the problem might be at the call site.

**Comment by KevinWelton** [comment]
Try changing the signature for 

`IAsyncOperation<int> TServiceClient::ListDevices(char16_t* devinfo)`

to

`IAsyncOperation<uint32_t> TServiceClient::ListDevices(char16_t* devinfo)`

DeviceInformationCollection::Size() returns an unsigned 32 bit integer, which isn't the same as int. Returning a uint32_t when int is the type you are expecting in your function signature is causing the problem.

**Comment by scuhappy** [comment]
Thank you! you are right! problem solved..
