### ISSUE TITLE
Compilation error: 'winrt::impl::produce_dispatch_to_super'

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/cppwinrt#310]
Hi @kennykerr,

I've been playing further with the abilities of C++/WinRT and found a bug in cppwinrt.exe compiler.

#### Repro:
Consider having this kind of IDL:
```
namespace WinRtComponent.Composables
{
    runtimeclass NativeComposable;

    [version(2.0)]
    [uuid(2ac58481-96b8-526f-bde4-340f055b25d4)]
    [exclusiveto(NativeComposable)]
    interface INativeComposable : IInspectable
    {
        HRESULT DoSomething();
    }

    [version(2.0)]
    [uuid(bef63057-1984-5536-87c2-eaf8dcd01791)]
    [exclusiveto(NativeComposable)]
    interface INativeComposableFactory : IInspectable
    {
        HRESULT CreateInstance([in] IInspectable* outer, [out] IInspectable** inner, [out, retval] NativeComposable** instance);
    }

    [version(2.0)]
    [uuid(4223486f-6471-5630-99d2-3ce994306826)]
    [exclusiveto(NativeComposable)]
    interface INativeComposableOverrides : IInspectable
    {
        HRESULT YouCanOverrideThis([in] HSTRING input);
    }

    [version(2.0)]
    [composable(INativeComposableFactory, public, 2.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass NativeComposable
    {
        [default] interface INativeComposable;
        [overridable] interface INativeComposableOverrides;
    }
}
```
When the cppwinrt.exe compiler invokes, it produces a `module.g.h` file that contains the following definition:
```cpp
namespace winrt::impl {
// ...
template <typename T, typename D>
struct WINRT_EBO produce_dispatch_to_super<T, D, WinRtComponent::Composables::INativeComposableOverrides>
    : produce_dispatch_to_super_base<T, D, WinRtComponent::Composables::INativeComposableOverrides>
{
    void YouCanOverrideThis(hstring const& input)
    {
        WinRtComponent::Composables::INativeComposableOverrides super = this->shim_super();
        if (super)
        {
            return super.YouCanOverrideThis(input);
        }
        return this->shim().YouCanOverrideThis(input);
    }
};
}
```
Now the compilation of the project fails because the compiler can't find the definition of `INativeComposableOverrides`:
```
1>module.g.cpp
1>d:\lab\winrtcomponent\winrtcomponent\generated files\module.g.h(14): error C2653: 'WinRtComponent': is not a class or namespace name
1>d:\lab\winrtcomponent\winrtcomponent\generated files\module.g.h(14): error C2065: 'INativeComposableOverrides': undeclared identifier
1>d:\lab\winrtcomponent\winrtcomponent\generated files\module.g.h(15): error C2923: 'winrt::impl::produce_dispatch_to_super': 'INativeComposableOverrides' is not a valid template type argument for parameter 'I'
1>d:\lab\winrtcomponent\winrtcomponent\generated files\module.g.h(26): error C2976: 'winrt::impl::produce_dispatch_to_super': too few template arguments
1>d:\lab\winrtcomponent\winrtcomponent\generated files\module.g.h(15): note: see declaration of 'winrt::impl::produce_dispatch_to_super'
```
On the other hand, there is a `WinRtComponent.Composables.2.h` file that contains an empty namespace definition:
```cpp
namespace winrt::impl {

}
```
If I move the above `produce_dispatch_to_super` class definition to this empty space (removing it from `module.g.h`), everything compiles fine and works as expected. So I believe that:

#### Expected behavior:
`produce_dispatch_to_super` class should be defined in `WinRtComponent.Composables.2.h` file. Project compiles.

#### Actual behavior:
`produce_dispatch_to_super` class is defined in `module.g.h` file. Project does not compile.

**Comment by xprssn2** [comment]
The `produce_dispatch_to_super` structs are not referenced anywhere else in code. In other words, they are unused.
I could build and run with them all commented out.

**Comment by Alovchin91** [comment]
@xprssn2 They are referenced if you use `this->super()` in your class.

**Comment by kennykerr** [comment]
Thanks for the feedback @Alovchin91. We are going to move `produce_dispatch_to_super_base` out of module.g.h and get rid of that header entirely.

**Comment by Alovchin91** [comment]
@kennykerr Thank you for the answer! I'm looking forward to see CppWinRT shipped)

**Comment by xprssn2** [comment]
I was able to eliminate the compiler errors by including all the referenced namespaces from the `winrt` folder in `pch.h`. In my case I had derived from `Windows.UI.Xaml.FrameworkElement`, I put these lines in `pch.h`
```cpp
#pragma once
#include <winrt\base.h>
#include <winrt\Windows.UI.Xaml.h>
// The rest...
```

**Comment by BrentRe** [comment]
FYI. You never need to include base.h in your source files. All C++/WinRT header files that need base.h explicitly pull it in.

**Comment by xprssn2** [comment]
Where is `this->super()` defined?

**Comment by Alovchin91** [comment]
@kennykerr The issue isn't fixed in SDK build 17083. Is it fixed in the internal build?

**Comment by xprssn2** [comment]
I am unable to find `this->super()`, but I use `m_inner.as<IWhateverOverrides>()`.
You can work around this by including the header(s) generated at the root of the `winrt` folder.

**Comment by kennykerr** [comment]
@Alovchin91 I'm not sure whether this change made it into the RS4 SDK. It looks like it was committed on Jan 26, but the last update to the RS4 SDK happened on Jan 24. Will check with the team.

**Comment by kennykerr** [comment]
The final RS4 SDK should have the change that will make this a lot more intuitive.

**Comment by Alovchin91** [comment]
@kennykerr Thank you for the update! Keep up the great work :)
