### ISSUE TITLE
Regarding derivation from WinRT types

### ISSUE THREAD

**Issue by jlvandenhout** [Microsoft/cppwinrt#311]
What is the use of the class templates? I get that Application is implemented as a singleton, so there has to be an ApplicationT template to make it possible to derive from it. But what is the use of others, like CanvasT and PageT? Maybe something clever we can do with it?

As a related question about deriving classes from WinRT types. What is the cleanest way to access members of derived classes in for example event callbacks, using pure C++? In case of WinRT types, we could use try_as-methods, but not in case of derived classes. Example:

```
struct MyButton : Button
{
	int state;

	MyButton()
	{
		Width(200);
		Height(200);
	}
};

struct App : ApplicationT<App>
{
	MyButton button;

	App()
	{
		button.Click(RoutedEventHandler(this, &App::OnButtonClick));
	}

	void OnButtonClick(IInspectable const & sender, RoutedEventArgs const & e)
	{
		//How to use MyButton instance state member for logic?
	}

	void OnLaunched(LaunchActivatedEventArgs const &)
	{
		Window window = Window::Current();
		window.Content(button);
		window.Activate();
	}

	static void Initialize(ApplicationInitializationCallbackParams const &)
	{
		make<App>();
	}
};

int WINAPI wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
	Application::Start(App::Initialize);
}
```

**Comment by DefaultRyan** [comment]
Class inheritance and singleton patterns are orthogonal concepts. The "Foo"T classes exist for a developer to easily derive a non-final base class provided by the framework, and customize its behavior through its overridable functions.

So, in your example, you've defined your own App class that derives from Windows.UI.Xaml.Application, and overridden its OnLaunched method.

In your OnButtonClick method, you're free to access your instance variable as your please. Since this is the handler for that particular button, the sender argument should be the same instance.

```
void OnButtonClick(IInspectable const & sender, RoutedEventArgs const & e)
{
  assert(button == sender.as<Button>());
  button.Content(box_value(L"I've been clicked!");
}
```

**Comment by jlvandenhout** [comment]
I was googling around before I asked the question and came up with [this](https://cboard.cprogramming.com/cplusplus-programming/117560-singleton-base-template-class-how-do-you-do.html). To me that sounded like a great solution to having a singleton-like class and still be able to derive from it. That's what got me thinking that the two concepts are not completely orthogonal in this special case and could be an explanation for the ApplicationT class.

Whit regard to the handler question. I'm aware I can access the members of the Button part of the instance, but I'm not certain how to get to the 'state' member of the MyButton class. 'sender.try-as<MyButton>()' fails with a GUID related error.

**Comment by DefaultRyan** [comment]
I’m not sure this is indicative of a bug in C++/WinRT bug. Perhaps stackoverflow would be a more appropriate place to ask usage questions.
