### ISSUE TITLE
Samples that include a *.winmd file query

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/cppwinrt#312]
I am curious as to why two samples (Direct2D and XamlCalendar) have a *.winmd file and the other samples do not.

**Comment by kennykerr** [comment]
They're just historical artifacts and are no longer needed if you set up the project correctly. You'll notice that none of the projects targeting the Windows SDK have .winmd files:

https://github.com/kennykerr/cppwinrt

**Comment by MRahilly** [comment]
Thank you Kenny. Separately, I was looking at the C++/CX generated files in the CPetzold 2013 book Ch01 example "Hello" and wondering whether to translate the *.g.h, *.g.hpp, *.g.cpp as well as the main source files all to C++/WinRT and link all the *.obj together or not? Maybe I need to wait for a modern rewrite of https://blogs.msdn.microsoft.com/vcblog/2012/08/24/connecting-c-and-xaml/
