### ISSUE TITLE
How to cast winrt::Windows::IInspectable const & sender to Button?

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/cppwinrt#314]
Elsewhere in this discussion I've seen the following quoted in a handler for a button click:

      Button sendButton = sender.as<Button>(); 
In the current environment this won't compile - the error is
"No suitable user-defined conversion from "winrt::impl::com_ref<winrt::Windows::UI::Xaml::Controls::Button> to "winrt::Windows::UI::Xaml::Controls::Button" exists.

The other quoted method also fails:

       Button sendButton = sender.as();

The error in this case is 
"No instance of overloaded function "winrt::Windows::Foundation::IInspectable::as" matches the argument list   Object type is "const winrt::Windows::Foundation::IInspectable"

Since the above were quoted in these pages in 2016 I assume something must have changed since then - can anyone tell me what would be the correct current method for casting the sender argument to a Button? Thanks.

**Comment by kennykerr** [comment]
I created the following sample to illustrate these techniques:

https://github.com/kennykerr/cppwinrt/blob/master/Store/XamlButton/App.cpp

**Comment by jevansAN** [comment]
Thanks Kenny. But your example does it this way:
    Button button = sender.as<Button>();
And that is exactly what will not compile when I try it. What stumps me is why it won't work for me if the same thing works for you. The full thing looks like this:

    button.Click([&](winrt::Windows::Foundation::IInspectable const & sender, Windows::UI::Xaml::RoutedEventArgs const & args)
			{
			Button sendButton = sender.as<Button>();
			ClickedInstrumentButton(sendButton.Tag);
			});

**Comment by jlvandenhout** [comment]
Maybe it has something to do with issue #253, did you try the `try_as` method instead of `as`?

**Comment by jevansAN** [comment]
Thanks for that suggestion - for a minute I thought this must be it, but I get the same error if I use

    Button sendButton = sender.try_as<Button>();

Perhaps I don't have the correct usage?

**Comment by DefaultRyan** [comment]
The fact that the original error was complaining about converting from impl::com_ref is a clue that the correct function was being called, so something more subtle is at play here.

Any chance you could boil this down to a simple self-contained repro in a single file? I just don’t see this sort of error happen when I type the exact same code, so there’s got to be something else going on – another header, a conflicting definition, different compiler options – that’s causing your error.

Ryan

**Comment by jevansAN** [comment]
One hint: I noticed that in Kenny's example he is not using the fully-qualified name for sender. I was using

     winrt::Windows::Foundation::IInspectable const & sender

If I change that to just 

    IInspectable const & sender

as in his example code (and using the same namespaces declared in his example) I am told that "IInspectable is ambiguous." This must mean something. Putting back the full name fixes that but the compile error remains.

**Comment by kennykerr** [comment]
Have you tried building the [XamlButton sample](https://github.com/kennykerr/cppwinrt/tree/master/Store/XamlButton) using the 17069 SDK directly with Visual Studio 2017 15.5 or later?

**Comment by jevansAN** [comment]
Kenny, thanks, if there's a zip archive I can quickly get for that I can give it a try, but right now I think I had better just kludge around this and not use the sender argument. This project is built from the XamlButton sample in the first place. Later on when VS has a built-in way of creating new cppwinrt projects I plan to transfer the code to a newly-created project.

**Comment by DefaultRyan** [comment]
I just thought of something. Are you referring to the Intellisense red squiggly? I see the same thing and I believe it's a known bug in Intellisense. The code as written should build and run just fine.

**Comment by kennykerr** [comment]
If you feel there is a usability issue here, please raise it at https://developercommunity.visualstudio.com/.
