### ISSUE TITLE
MIDI sample code using cppwinrt?

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/cppwinrt#315]
Has anyone created a sample project showing an implementation of MIDI (at least output to the internal synth) using cppwinrt? I've tried the MIDI sample in the winrt collection, which compiles but doesn't run past the splash screen.  My own attempts to even declare a MIDIOutPort variable have been unsuccessful. It would be great to know that this has been done in cppwinrt.
Here's a tiny sample in which the declaration of a MidiOutPort produces the error "Incomplete type is not allowed." The MidiOutPort type name is recognized,  however, if I begin the namespace with ABI.

    #pragma once
#include "Windows.Devices.Midi.h"

using namespace winrt;
using namespace ABI::Windows::Devices::Midi;

class MIDIHandler
{
protected:

	MidiOutPort m_midi_out_port;

public:
	MIDIHandler();
	~MIDIHandler();
};

**Comment by DefaultRyan** [comment]
You need to #include <winrt/Windows.Devices.Midi.h>. If you omit the "winrt" prefix, you're going to get the ABI header, not the cppwinrt one. That's why it works with the ABI namespace prefix.

**Comment by jevansAN** [comment]
DefaultRyan, thanks very much. That does the trick. I was beginning to worry that MIDI was not yet supported in cppwinrt.
