### ISSUE TITLE
Getting the string representation of an enum

### ISSUE THREAD

**Issue by rigdern** [Microsoft/cppwinrt#316]
Is there an easy way to get the string representation of a WinRT enum? If not, have you considered generating code to make that easy?

This is useful for logging and debugging. Here's an example:

```
void some_function(CoreDispatcherPriority priority)
{
  cout << "some_function called with priority " << winrt::enum_to_string(priority));
  // ...implementation details...  
}
```

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
This is not currently supported, but we have considered adding this feature. Thanks for the feedback!
