### ISSUE TITLE
DesktopComposition sample hanges in Version 1709(OS Build 17083.1000)

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/cppwinrt#318]
https://github.com/kennykerr/cppwinrt/tree/master/Desktop/DesktopComposition.

After the initial display, you get the hour glass! I had the stop the debugger to terminate the app.

Using latest VS2017 and SDK.

**Comment by kennykerr** [comment]
That's a known bug in certain RS4 Insider builds. The composition team is investigating.
