### ISSUE TITLE
C++/WINRT Data Binding Example

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#322]
II downloaded Windows Universal Samples to look for an example of C++ data binding, I found xBindSamplesCX which is an app with 2 projects. One project is C++CX which contains the XAML, cpp & h files. The second project ix C# and contains the data source. It uses strings with get & set.

Does C++/WinRT follow the same pattern ?

**Comment by kennykerr** [comment]
Data binding with XAML is still under development, so there are no samples to share at this time.

**Comment by JackDetrick** [comment]
I was hoping that your approach was to pass a reference.  As it  is now,changing a controls properties based upon data content creates a a lot of code in in the C# code-behind. (i.e. visibility)..
