### ISSUE TITLE
Intellisense broken?

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/cppwinrt#33]
I'm trying to use this on a DirectX XAML UWP project.  If you create one of these projects from the VS template, as soon as you #include a header from the cppwinrt project, intellisense stops working.  

I'm simply adding 

`#include "winrt\base.h"`
to the pch.h file and suddenly no intellisense.  I'm somewhat of a C++ novice so I can't really figure out what's wrong.

(FYI, I wanted to simply try and rewrite the static methods in DirectXHelper.h to use WinRT/C++.  I haven't figured out if this library would be good for anything else at the moment.)

**Comment by raffaeler** [comment]
It looks like a VS2015 specific issue.
I was successful in using the VS15 Preview 5 intellisense, when mixing C++/CX and cppwinrt.

**Comment by limefrogyank** [comment]
Ah, you're right.  I just installed Preview 5 and it works fine.  I suppose I need to run this preview code on a preview IDE for now.

**Comment by raffaeler** [comment]
Previews requiring preview, which requires preview ... :)

**Comment by kennykerr** [comment]
Thanks for reporting this. We continue to work with the C++ team to improve IntelliSense support.
