### ISSUE TITLE
"All rights reserved." alone in each source-code file grants far fewer rights to copy than MIT License in the LICENSE file

### ISSUE THREAD

**Issue by optikos** [Microsoft/cppwinrt#332]
I fear that I might make a pest of myself, but, for the good of all developers using C++/WinRT, this needs to be brought up (and hopefully fixed) at some point anyway for •all•‡ users of (supposedly-)open-source portions of C++/WinRT, so today might as well be the day.  Someone needs to make this request, so I might as well be the one.

‡ not only me

1) Although “All rights reserved.” is often boilerplate in default copyright notices for proprietary/trade-secret software, and
2) although legal matters often make developers' eyes glaze over out of apathy, and
3) although that “All rights reserved.” declaration was (formerly) de facto required ‘magic wording’ to evoke ownership of copyright under the 1910 [Buenos Aires Convention](https://en.wikipedia.org/wiki/Buenos_Aires_Convention),

the statement “All rights reserved.” still has valid and non-defunct (and non-Buenos-Aires-Convention) legal contract-law meaning in courts of law when placed in a work of art for which the owner claims rights to copy that work of art and all its derivative works of art thereof.  Its presence no longer is needed to assert ownership of rights to copy (as the Buenos Aires Convention has been supplanted on this matter).  But when present, its presence guides a court of law to demarcate which acts of copying are permitted and which are prohibited.  Its presence is out-of-vogue in much of the open-source community, but Apple & Microsoft still often place “All rights reserved.” in their open-source source-code, so let's just accept “All rights reserved.” as a given, and not try to remove it.  When present •within• an open-source license, it is usually in the context of “All rights reserved •except•” the permissions/terms/conditions that are granted governing the copying.

C++/WinRT is on one hand licensed under the MIT License as stated at the GitHub repository's file Microsoft/cppwinrt/[LICENSE](https://github.com/Microsoft/cppwinrt/blob/master/LICENSE).  But on the other hand, when viewing the numerous .h and .cpp [file](https://github.com/Microsoft/cppwinrt/blob/master/10.0.16299.0/winrt/base.h)s, only “All rights reserved.” appears without any mention of the MIT License at all.  This could cause ambiguity regarding precisely what the definition/scope of “this software” is the MIT License in the Microsoft/cppwinrt/LICENSE file.  Obviously by habit & yearned-for desire among developers, the definition/scope of “this software” in the LICENSE file is every single file throughout the [Microsoft/cppwinrt repository](https://github.com/Microsoft/cppwinrt), but a court of law could conceivably resolve this ambiguity differently to find that the scope of “this software” is some other extent than every file in the cppwinrt repository.  (In Texas conservative law, contracts are generally immutable in a court of law except in the case of an •ambiguity•, which the court is then granted the power to resolve, perhaps differently than any one party intended.)  For example, the repository's source code builds software, but is a mere tree of files software per se, when most modern (post-1970s) definitions of software is ‘executable software package’ of which a GitHub repository of source code as a bunch of flat text files could be argued to not be.

Just in case anyone considers these paragraphs above to be tilting at windmills needlessly over excessively-nit-picking fabricated-issue contrivances, an analogous open-source project from Microsoft in recent years declares in each source-code file what I would expect to see in each of C++/WinRT's source-code files in GitHub.  The [Microsoft/ChakraCore repository](https://github.com/Microsoft/ChakraCore)'s analogous [LICENSE.txt](https://github.com/Microsoft/ChakraCore/blob/master/LICENSE.txt) file contains the same declaration of rights to copy as the Microsoft/cppwinrt/LICENSE file does.  But each ChakraCore [source-code file](https://github.com/Microsoft/ChakraCore/blob/master/lib/Parser/Parse.cpp) overtly declares rights to copy that overtly mention & evoke the MIT License in that repository's LICENSE.txt.  Although perhaps some stickler for open-source correctness could argue that having “All rights reserved.” and “Licensed under the MIT License.” as 2 separate sentences without any conjunction such as the word “except” to modify the word “all” could be written more water-tightly legally, having the “Licensed under  the MIT License.” immediately following “All rights reserved.” seems to implicitly have that ‘except’ meaning of modifying the ‘all’ in the ways overtly stated in the MIT License to grant certain permissions to copy.  The ChakraCore developer overtly explicitly knows from Microsoft's expressed written text at the top of each source-code file that “All rights reserved.” is clearly to be interpreted in the context of “Licensed under the MIT License.”  The C++/WinRT developer has no such assurance.

Respectful request for the benefit of all C++/WinRT developers:
Please follow the prior precedent as established via multiple Microsoft open-source projects‡‡ (as well as perhaps overtly stated in Microsoft's internal corporate policies) of **placing “Licensed under the MIT License.” in each source-code file throughout the Microsoft/cppwinrt repository**, because Microsoft/cppwinrt/LICENSE's MIT License versus the “All rights reserved.” alone in each source-code file could be construed to grant drastically different rights to copy.

‡‡ e.g., the Microsoft/ChakraCore GitHub repository's source-code files; the [Microsoft/msbuild](https://github.com/Microsoft/msbuild) GitHub repository's [source-code file](https://github.com/Microsoft/msbuild/blob/master/src/Framework/BuildEngineResult.cs)s; the [Microsoft/cpprestsdk](https://github.com/Microsoft/cpprestsdk) GitHub repository's [source-code file](https://github.com/Microsoft/cpprestsdk/blob/master/Release/src/json/json_parsing.cpp)s.

**Comment by kennykerr** [comment]
I’m not a lawyer so I can’t helpfully comment on this, but the feedback is noted. Thanks!

**Comment by walbourn** [comment]
FWIW, it looks like a pretty common comment header block for MS MIT-licensed samples and libraries is:

    // Copyright (c) Microsoft. All rights reserved. 
    // This code is licensed under the MIT License (MIT). 
    // THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF 
    // ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY 
    // IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR 
    // PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT. 

For my numerous GitHub libraries, I'm missing the _This code is licensed under the MIT License (MIT)._ so I should fix that.

**Comment by optikos** [comment]
@kennykerr, does “closed” mean that all the source-code files throughout C++/WinRT will now/soon be changed to conform to the “All rights reserved.  **Licensed under the MIT license. See LICENSE file in the project root for full license information.**” convention used in multiple other Microsoft GitHub repositories?  Or does “closed” here mean something closer to rejected (for the time being)?

I wasn't looking for lawyerly commentary‡, or mere mental note.  I was hoping that you would overtly agree to pursue‡‡ changing C++/WinRT's initial boilerplate comment in each source-code file so that it conforms to the prior Microsoft precedent in other GitHub repositories.

‡ I tried already as best as I could as a nonlawyer to summarize a layman's view of all that to move away from the legal domain to merely following someone else's prior-precedent lead within Microsoft, as a matter of already-established already-settled policy, pinching off actual legal-topic debate—evoking the Project Management Department more than the Legal Department.

‡‡ I understand that you might need to contact someone internal to Microsoft about this matter, to get proper authorization or the like.

**Comment by optikos** [comment]
@walbourn, please click on the original issue's linked singled-out-example source-code files in C++/WinRT, ChakraCore, cpprestsdk, and msbuild Microsoft GitHub repositories (as well as multiple other less-brand-name repositories).  I expended some effort to call out in detail what I am talking about in each of those 4 example repositories' source-code files.  There is nothing wrong with the MIT License in the LICENSE file itself; the content within the MIT License in the LICENSE file is not itself germane to this issue, so please don't focus there.  What is germane is the boilerplate comment at the top of the thousands of source-code files in all these repositories;  C++/WinRT's doesn't match (any of?) the other Microsoft GitHub repositories' boilerplate comment at the top of each source-code file.

**Comment by BrentRe** [comment]
C++/WinRT headers follow current guidance from our legal team for source code that we make available to the public under the the specified license. I don’t expect this to change.

**Comment by optikos** [comment]
@BrentRe, so **all** the other Microsoft GitHub repositories are out of compliance with guidance from your legal team?  I can hardly believe that C++/WinRT is the only one that got it correct and everyone else goofed up.

**Comment by walbourn** [comment]
@optikos I didn't mention the ``LICENSE`` file at all.

``Copyright (c) Microsoft Corporation. All rights reserved.`` has been the consistent requirement for all Microsoft source files for decades. Samples started adding the warranty disclaimer many years ago as well.

The extra comment line in each source file being MIT licensed vs. just assuming the ``LICENSE`` file covers the repro is less consistent with the hundreds of Microsoft organizational GitHub projects.

**Comment by BrentRe** [comment]
@optikos Guidance changes over time and we're following guidance current at the time we initially release the C++/WinRT headers. But you make compelling points. I'll follow up with legal to see if can / should update to something different.

Note that we won't be releasing further updates to the C++/WinRT headers here on GitHub. All future releases of the library will be via the Windows 10 SDK. Currently the available releases of the RS4 Preview Windows SDK have far more current C++/WinRT headers. Plus, the SDK contains the C++/WinRT compiler itself.

**Comment by optikos** [comment]
@walbourn, you copy-pasted the •content• of the LICENSE file, which is an even stronger bringing up of the LICENSE file than merely referencing it by name.  I am not requesting any change to the content of the LICENSE file (or its name).  I am not requesting any change to the license actually granted to each source-code file (under most people's reasonable resolution of the ambiguity).  I am requesting that Microsoft do for C++/WinRT's source-code files what Microsoft wisely did for 3 other major Microsoft GitHub repositories's source-code files:  msbuild, cpprestsdk, and ChakraCore.

And @BrentRe brings up a good point:  this is effectively a moot point here on this GitHub repository.  The focus should instead be on the corresponding source-code files in the Windows 10 SDK.

**Comment by optikos** [comment]
@BrentRe, @kennykerr,  Hmmmm.   Based on Brent Rector's comment above, I went to see (in the 17095 Windows 10 SDK) what interaction the boilerplate copyright comment has with C++/WinRT's LICENSE file there.  To my initial surprise (and then no real surprise at all, upon further contemplation), there is no MIT-License-based LICENSE file there for C++/WinRT.  Instead, C++/WinRT in the 17095 Windows 10 SDK is governed by the same EULA that governs the entire Windows 10 SDK.  Because the GitHub repository for C++/WinRT is becoming obsolescent (and henceforth C++/WinRT will be distributed solely in the Windows 10 SDK), henceforth C++/WinRT is not truly open-source, but rather proprietary software governed by a proprietary Microsoft EULA.  As this GitHub repository becomes more & more obsolescent, C++/WinRT's MIT License fades into historical obscurity, whereas the proprietary EULA for subsequent releases of C++/WinRT lives on.

For example, a question arises as to whether C++/WinRT is “the Microsoft .NET framework”.  A reasonable person would say, no, C++/WinRT is not part of the .NET framework, despite C++/WinRT being applicable to the .NET framework.  Hence, the following disconcerting clause applies to C++/WinRT:

“Except for the Microsoft .NET Framework, you must obtain Microsoft's prior written approval to disclose to a third party **any benchmark test of the software**.”

So I guess published performance comparisons of C++/WinRT and anything else will be few & far between.

Also, “You **may not … work around any technical limitations of the software**;” seems to relegate users of C++/WinRT to waiting (perhaps months) for a subsequent release of C++/WinRT when a bug arises in C++/WinRT as distributed in the Windows 10 SDK.  A reasonable person would define “work around” drastically broadly:  no fixes whatsoever, no alternative usages whatsoever, no rectifications of any kind whatsoever; no bypasses of the defect whatsoever; no ability to edit a tweak of a .h file whatsoever.

Both of those clauses are drastic curtailments in what the user of C++/WinRT is capable of doing with C++/WinRT under the MIT License.  Hmmmm.  Food for thought regarding what this EULA-instead-of-MIT-License means for C++/WinRT going forward.

@kennykerr, although you closed this issue, the topic seems to be begetting wider & wider less-resolved questions.  For example, will C++/WinRT in future Windows 10 SDK releases (and/or in future Visual Studio releases) always be governed by that EULA as now worded, or will C++/WinRT receive one or more special treatments like .NET Framework does?  As another example (and I haven't checked yet), what is the license granted (e.g., MIT or EULA or none/all-rights-reserved-totally) to output source-code generated by cppwinrt.exe when pointed at a non-Microsoft WinRT component's DLL & .winMD files?  Conversely, what is the license granted to output source-code generated by cppwinrt.exe when pointed at Microsoft's WinRT components (substantially regenerating what is in the 17095 Windows SDK)?  It would seem that cppwinrt.exe's generated source code files should inherit the license of the WinRT .DLL and .winRT files at which cppwinrt.exe is pointed at.  Hmmmmmm.

I thought in the original GitHub issue that I was merely requesting fixing a minor typographical error type of goof.  I did not intend to be an annoying pest dredging up deep-thought legalistic matters, but this got juicy quickly.

**Comment by BrentRe** [comment]
That is a Preview SDK. Content in it can, likely will, change from now until RTM.

**Comment by optikos** [comment]
@BrentRe, which is why I am raising the issue as rapidly as I can:  so you all can decide whether this is exactly where you want to leave things to go out the door publicly officially at RTM.  I am trying to do a favor/service.

**Comment by BrentRe** [comment]
I appreciate it. We're actively working to address this issue appropriately.
