### ISSUE TITLE
Should module.g.cpp import <atomic>?

### ISSUE THREAD

**Issue by rigdern** [Microsoft/cppwinrt#333]
I’m using cppwinrt.exe v1.0.171122.1.

I get some compiler errors in the generated file module.g.cpp like this:

```
module.g.cpp(10): error C2039: 'atomic': is not a member of 'std'
```

It seems like module.g.cpp should be importing `<atomic>` but it’s not.

Is this a known issue in that version of cppwinrt.exe or am I doing something wrong?

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
This has been fixed. Please try a newer version of C++/WinRT.

**Comment by rigdern** [comment]
@kennykerr Thanks for the quick response!

Is there an easier way to obtain the latest version of cppwinrt.exe than installing a preview version of Windows and installing the preview Windows SDK? This process is a bit painful given that I'm using and targeting an older version of Windows 10.

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
Yes, you can email the internal C++/WinRT discussion alias and we'll point you to the internal build share.
