### ISSUE TITLE
Documentation: Does a method need to retain WinRT component (`this`) during co_await?

### ISSUE THREAD

**Issue by rigdern** [Microsoft/cppwinrt#335]
Suppose I use `co_await` in a method of my WinRT component. Do I have to ensure the WinRT component's reference count doesn't reach 0 or does the `co_await` take care of this for me? Here's a snippet to illustrate what I mean:

```c++
namespace winrt::MyLib::implementation
{
  winrt::Windows::Foundation::IAsyncOperation<int> Test::GetNumberAsync()
  {
    co_await std::chrono::seconds(5);
    // Are we at risk of the reference count of `this` reaching 0 and
    // the WinRT component being destroyed by the time we get
    // here?
    return this->m_number;
  }
}
```

(This discussion assumes the app doesn't have any reference counting bugs)

It would be great to include this information in the `Docs` folder of this repo.

Adam Comella
Microsoft Corp.

**Comment by kennykerr** [comment]
Yes, you will need to ensure that the object remains alive if you depend on it for your coroutine implementation.
