### ISSUE TITLE
weak_ref support non-sdk classes

### ISSUE THREAD

**Issue by LukeGKelly** [Microsoft/cppwinrt#337]
I'm trying to create a weak_ref to a class very similar to the App class in this sample:
https://github.com/Microsoft/cppwinrt/blob/dc92f6f56a1f3bd9cac78cee8955fbec79bc7a3c/10.0.16299.0/Samples/Blocks/App.cpp

I have no issue with the SDK types.  But with for types like these I get:
error C2059: syntax error: 'template'

**Comment by kennykerr** [comment]
We added the `get_weak` and `get_strong` functions to simplify this, but unfortunately they did not make it into the RS4 SDK.
