### ISSUE TITLE
__cplusplus_winrt preprocessor directive

### ISSUE THREAD

**Issue by optikos** [Microsoft/cppwinrt#338]
When compiling in /Zw mode for C++/CX, the __cplusplus_winrt preprocessor macro is defined to be the integer 201009L.  If that is the way of bounding C++/CX-based app source code via conditional compilation directives [e.g., one of #if __cplusplus_winrt >= 201009L or #if __cplusplus_winrt or #if defined(__cplusplus_winrt) ], then conversely what is the way of bounding C++/WinRT-based app source code via conditional compilation directives?

Please note the apparent potential confusion perhaps causable by C++/CX's choice of name of preprocessor macro:  __cplusplus_winrt.

**Comment by kennykerr** [comment]
As you know, C++/CX is provided directly by the compiler and as such it was important for library developers to detect the presence of these rather disruption language extensions. C++/WinRT is just a library and provides no specific preprocessor definitions. The header-only version of C++/WinRT does define `CPPWINRT_VERSION`, which you can use in the short term but with the introduction of a module-only version of C++/WinRT even this will disappear. You can of course define your own preprocessor definition to signal to the inclusion of C++/WinRT within a given project.
