### ISSUE TITLE
No documentation for WinRT IDL

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/cppwinrt#339]
Hi @kennykerr,

First of all, thank you for all your fantastic work! C++/WinRT is a marvelous project, I hope it will make Windows Runtime great again)

But for that to happen, we really need to get an extensive documentation on the Modern IDL. It looks like it’s pretty much streamlined and simplified, so this should not be much of an issue.

Unfortunately, historically there was almost zero documentation on the WinRT IDL since its first appearance. I believe that after 7 years it’s time to get this done :)

**Comment by BrentRe** [comment]
We have the goal of releasing documentation on a new Windows Runtime class description syntax on docs.microsoft.com - likely around the //Build conference timeframe. Though, as always, precise dates are hard to predict.

One remaining issue is that we haven't yet settled on a name for this new syntax. :)

**Comment by kennykerr** [comment]
Keep in mind that IDL is a separate language and the tools are maintained by a separate team that does not keep an eye on this GitHub project. This GitHub project is squarely about C++/WinRT.
