### ISSUE TITLE
what is winrt::param::async_iterable 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#341]
I can find doc about "winrt::param::async_iterable ". Can anyone answer what it is. And how to use it. How do i convert std::vector or std::map to it?

**Comment by kennykerr** [comment]
param::async_iterable<T> is much like param::iterable<T> except that it will only accept a std::vector<T> rvalue to avoid having an async method refer to a local that may go out of scope prior to async completion. Given some API that expects an async_iterable<T>, you can copy or std::move the argument.
