### ISSUE TITLE
Visual Studio code analysis complains about missing annotations in cppwinrt header files

### ISSUE THREAD

**Issue by sylveon** [Microsoft/cppwinrt#343]
Create a simple Visual C++ command line project with the following (assuming you have done the prerequisites for cppwinrt):
```cpp
#include <winrt\Windows.ApplicationModel.h>

int main()
{
    return 0;
}
```
Then enable all code analysis rules in project settings:
![](https://files.charlesmilette.net/SevereDarkkhakiGrunion)

Run code analysis (Alt-F11)

The file `winrt/base.h` will generate code analysis warnings:
![](https://files.charlesmilette.net/DeterminedYouthfulHoiho)

**Comment by kennykerr** [comment]
It looks like you're still using the headers from the GitHub repo. We are now shipping the [headers in the Windows SDK](https://moderncpp.com/) (RS4). Those headers do not exhibit this behavior.

**Comment by sylveon** [comment]
Awesome! Eagerly waiting for the stable RS4 release
