### ISSUE TITLE
"Warning non-agile factory" in standard C++ DLL

### ISSUE THREAD

**Issue by monsieurgustav** [Microsoft/cppwinrt#346]
Hi,
I embed some WinRT features (fingerprints) in a basic C++ DLL. Some functions are dllexported to be consumed by a console app.

Calling winrt::Windows::Security::Credentials::UI::UserConsentVerifier::CheckAvailabilityAsync in my DLL gives a "non-agile factory" warning, whereas UserConsentVerifier is agile.

Calling the same function in the Syndication sample gives the same warning.

Calling the same function in the XamlCalendar sample works normally though.

Do I miss some initialization function (in addition of winrt::init_apartment) ?
Can I safely ignore the warning ?

Thanks,
Guillaume

**Comment by kennykerr** [comment]
This was an informational warning indicating that the factory (implementation) is non-agile and thus a potential source of performance and reliability issues. There isn't much you can do about it. This warning has been removed in the version of C++/WinRT that ships in the Windows SDK and we're separately working on updating those factories.
