### ISSUE TITLE
Link Error when trying to get Windows::Perception::People::HeadPose properties

### ISSUE THREAD

**Issue by joejo-unity** [Microsoft/cppwinrt#348]
Using code similar to the following
			auto frame = // Get frame from holographic space
			auto prediction = frame.CurrentPrediction();
			auto sourceState = // Get source state(s) from holographic space
			auto sourcePose = sourceState.TryGetPointerPose(/*...*/);

			winrt::Windows::Foundation::People::HeadPose head = sourcePose.Head();
                        // Next line causes linker error
			winrt::Windows::Foundation::Numerics::float3 position = head.Position();

Will produce the following linker error:
error LNK2019: unresolved external symbol "public: struct winrt::Windows::Foundation::Numerics::float3 __cdecl winrt::impl::consume_Windows_Perception_People_IHeadPose<struct winrt::Windows::Perception::People::IHeadPose>::Position(void)const " (?Position@?$consume_Windows_Perception_People_IHeadPose@UIHeadPose@People@Perception@Windows@winrt@@@impl@winrt@@QEBA?AUfloat3@Numerics@Foundation@Windows@3@XZ) 

Replacing that line with the unwrapped call directly to the interface like so:

			winrt::Numerics::float3 value{};
			winrt::check_terminate((*(winrt::abi_t<perc::People::IHeadPose>**)&static_cast<perc::People::IHeadPose const&>(head))->get_Position(winrt::put_abi(value)));

Compiles and links just fine.

Same issue happens with ForwardDirection and UpDirection.

**Comment by BrentRe** [comment]
You must #include <winrt/Windows.Foundation.Numerics.h> header file to use types in that namespace.

**Comment by BrentRe** [comment]
Actually I didn’t read far enough. I got distracted by the return value.

You need to #include <winrt/Windows.Perception.Peole.h>

_____________________________

**Comment by joejo-unity** [comment]
I would expect that missing header to cause compile issues, not linker. Thanks.

**Comment by joejo-unity** [comment]
Yes, it worked after including the people header. Interesting that it
compiled with no issues given it's a template.

Joseph Jones
Senior Software Engineer
Unity3D
