### ISSUE TITLE
Build ignores namespaces if multiple WinMD files contain the same namespace

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#351]
If I have two WinMD files for which I'm generating C++/WinRT headers, and those two WinMD files contain the exact same namespace, only the types in the namespace in the first WinMD file have C++/WinRT types generated for them in the headers.  See this repro app for a demonstration:

[CppWinRTSameNamespaceBugRepro.zip](https://github.com/microsoft/xlang/files/3683825/CppWinRTSameNamespaceBugRepro.zip)

ClassA defines a type; ClassB derives from ClassA in the same namespace; ClassC derives from ClassA in a different namespace.  C++/WinRT types are generated for ClassA and ClassC, but not for ClassB, leading to a build break.

The scenario in which my team has encountered this is in the [WinUI 3.0 effort](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md), which is having us rename our Windows.UI.Xaml.* namespaces to be Microsoft.UI.Xaml.* instead.  However, we already have other types in WinUI 2.0 in the Microsoft.UI.Xaml.* set of namespaces, causing us to hit this issue.

I currently have a workaround in place where we merge Xaml and WinUI 2.0 types together into a single WinMD file external to our existing WinUI project, run that through C++/WinRT, and then pick up the results from that in our existing WinUI project.  However, it'd be a lot more convenient if we could just keep our existing workflow, which we could do were it not for this issue.

**Comment by kennykerr** [comment]
@Scottj1s @jlaanstra has this issue been addressed?

**Comment by Scottj1s** [comment]
Not to my knowledge, but worth evaluating with Johan's latest improvements

**Comment by kennykerr** [comment]
It still repros with the latest NuGet package.

**Comment by kennykerr** [comment]
We are not currently investing further in our msbuild support. As there is a workaround I'm going to close this issue.
