### ISSUE TITLE
Support partial weak ref suppression

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#352]
Xaml's handling of weak ref support is rather brittle and this would make it more reliable in some cases.

If there's an m_inner then don't answer IWeakReferenceSource queries has been floated as a reasonable solution.

This is really about Xaml's unique reference tracking implementation.

From Jevan:

> To be clear, we just need to make sure that IReferenceTrackerExtension is reported only if outer() is null. See https://github.com/microsoft/microsoft-ui-xaml/blob/826de66b1a3065fb5151e8d32daf5d483c3e66e7/dev/inc/RuntimeClassHelpers.h#L81 for the specific thing we do.

**Comment by kennykerr** [comment]
Closing this issue as there doesn't appear to be any demand for this.

**Comment by jevansaks** [comment]
Just to be clear, this is one of two reasons we need to override QueryInterface so if trying to hide that part of the implementation is a goal for C++/WinRT then we'd need this to be addressed. But otherwise this is fine to punt.

**Comment by kennykerr** [comment]
Do we have an issue for the other reason?

**Comment by jevansaks** [comment]
I don't see an open issue for the other. The reasons are described in the comments in the file you linked in the issue description but they are:

1) Avoiding a crash for QIs of IWeakReferenceSource during construction. This is a XAML bug and we've fixed the known scenarios of this but we still need to be able to run on downlevel OSes where we don't have the fix. 
2) Implementing IReferenceTrackerExtension only when outer() is null, even in cases where the outer() doesn't implement IReferenceTrackerExtension.
