### ISSUE TITLE
Delete operators that allow assignment to rvalues

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#359]
From internal bug report:

Rookie mistake that I’ve made when converting large chunks of C++/CX to C++/WinRT.

```
TextBlock textBlock = …;

hstring newValue = …;

textBlock.Text() = newValue; // oops, intended textBlock.Text(newValue);
```

This successfully compiles but does nothing. You are obtaining an hstring from the Text property and overwriting your local copy of the hstring with newValue. The original Text property remains unchanged.

Similarly for other smart types like com_ptr.

This can be converted to a compiler error by making the existing operator= explicitly for the lvalue reference (adding “&”) and deleting the rvalue reference version.

```
struct hstring
{
    hstring& operator=(hstring const& value) & // <- add ampersand here
    {
        m_handle.attach(impl::duplicate_string(value.m_handle.get()));
        return*this;
    }

    hstring& operator=(hstring const&) && = delete; // delete the rvalue version
}
```

Assigning to an rvalue is not particular useful. Since it isn’t named, you can’t take thee modified rvalue and do anything with it.

Okay, so maybe you could do something nuts like this

```
(textBlock.Text() = newValue).c_str()
```

but there’s no real value there. you can just remove the assignment

```
newValue.c_str()
```

or if the method you’re calling is a mutating method, you can copy the object so the method takes place on the copy.

```
hstring(newValue).c_str()
```

**Comment by kennykerr** [comment]
Closing old issue as not urgent. Feel free to contribute a fix if so desired. @oldnewthing

**Comment by ChrisGuzak** [comment]
someone reported a bug due to this today, so +1 to fixing this

**Comment by wenyizou** [comment]
> someone reported a bug due to this today, so +1 to fixing this

Thanks for moving forward to fixing this :)

**Comment by ackrumb** [comment]
Upvote. This would remove a bunch of pain from people migrating from CX. If possible, is there a way to add a static_assert in that definition that will tell them what went wrong (e.g. "this is the right way to do what you were trying to do")

**Comment by kennykerr** [comment]
Feel free to contribute a PR. 😉
