### ISSUE TITLE
Question: How do I get a proper TypeName instance?

### ISSUE THREAD

**Issue by johanlindfors** [Microsoft/cppwinrt#36]
Sorry for a rookie question (possibly not an issue), but how do I get a TypeName instance which I can pass to the Windows::UI::XAML::Controls::Frame::Navigate(...) method?

**Comment by raffaeler** [comment]
If I remember well, this code worked for me.

```
auto tn = Windows::UI::Xaml::Interop::TypeName(MainPage::typeid);
TypeName rtn;
rtn.Kind = static_cast<winrt::Windows::UI::Xaml::Interop::TypeKind>(tn.Kind);
rtn.Name = winrt::hstring(tn.Name->Data());

auto objArgs = winrt::Windows::Foundation::PropertyValue::CreateString(rte.Arguments());
rootFrame.Navigate(rtn, objArgs);
```

I guess there is an easier way ...

**Comment by johanlindfors** [comment]
The compiler complains about the MainPage::typeid

Expected an identifier

**Comment by raffaeler** [comment]
I am not close to my pc right now but I guess that error is a namespace importing issue

**Comment by raffaeler** [comment]
I confirm my "using namespace" are just the following (and the project compiles):
```
using namespace winrt::Windows::ApplicationModel;
using namespace winrt::Windows::ApplicationModel::Activation;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::Foundation::Collections;
using namespace winrt::Windows::UI::Xaml;
using namespace winrt::Windows::UI::Xaml::Controls;
using namespace winrt::Windows::UI::Xaml::Controls::Primitives;
using namespace winrt::Windows::UI::Xaml::Data;
using namespace winrt::Windows::UI::Xaml::Input;
using namespace winrt::Windows::UI::Xaml::Interop;
using namespace winrt::Windows::UI::Xaml::Media;
using namespace winrt::Windows::UI::Xaml::Navigation;
```

**Comment by kennykerr** [comment]
While you can easily create a TypeName value (it’s just a struct), doing something useful with it requires a non-trivial amount of work. Mainly the Application-derived type must implement IXamlMetadataProvider. That’s easy enough to do, but it also requires support for IWeakReferenceSource which is not on GitHub yet.

**Comment by johanlindfors** [comment]
So I guess the following code is a bit naive...

struct MainPage : Page {

	MainPage() {
		TextBlock block;

		block.FontFamily(winrt::Windows::UI::Xaml::Media::FontFamily(L"Segoe UI Semibold"));
		block.FontSize(72.0);
		block.Foreground(SolidColorBrush(Windows::UI::Colors::Orange()));
		block.VerticalAlignment(VerticalAlignment::Center);
		block.TextAlignment(TextAlignment::Center);
		block.TextWrapping(TextWrapping::Wrap);

		hstring text(L"Hello world");
		block.Text(text);

		Content(block);
	}
};


struct App : ApplicationT<App>
{
	void OnLaunched(LaunchActivatedEventArgs const &)
	{
		Frame rootFrame;

		auto window = Window::Current();
		window.Content(rootFrame);
		window.Activate();

		auto tn = Windows::UI::Xaml::Interop::TypeName(MainPage::typeid);
		TypeName rtn;
		rtn.Kind = static_cast<winrt::Windows::UI::Xaml::Interop::TypeKind>(tn.Kind);
		rtn.Name = winrt::hstring(tn.Name);


		rootFrame.Navigate(rtn);
	}
};

int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
	Application::Start([](auto &&) { make<App>(); });
}

Sorry for the formatting, can't get it properly styled. Also, I'm confused why the SolidColorBrush instantiation works withouth namespace, but the FontFamily requires explicit namespace declaration.

**Comment by raffaeler** [comment]
@kennykerr is the solution I posted the current best workaround or do you believe there is something better we can write?
Thank you

**Comment by drewcanitz** [comment]
I think you may need a GetRuntimeClassName on MainPage, and as Kenny mentioned you'll need IWeakReferenceSource.  If you use Frame.Navigate I think there will be an attempted lookup of MainPage in the App's IXamlMetadataProvider.  Instead of Navigate you could try to create a MainPage with make and then directly assign the frame content.

But if you had an IXamlMetadataProvider implemented on your app that exposes MainPage your code might look like this...

void App::OnLaunched(LaunchActivatedEventArgs const & e)
{
    auto window = Window::Current();

    Frame rootFrame = nullptr;
    auto content = window.Content();
    if (nullptr != content)
    {
        rootFrame = content.as<Frame>();
    }

    if (rootFrame == nullptr)
    {
        Frame frame;
        rootFrame = frame;
        window.Content(rootFrame);
    }

    if (rootFrame.Content() == nullptr &&
        !rootFrame.Navigate({L"MainPage", TypeKind::Custom}, PropertyValue::CreateString(e.Arguments())))
    {
        throw hresult_error(E_FAIL, L"Failed to create initial page");
    }

    window.Activate();
}

int WINAPI WinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
    Application::Start([](auto &&) { make<App>(); });
}

**Comment by kennykerr** [comment]
What Drew said. Raffaele, there is no workaround until the winrt::implements class template supports IWeakReferenceSource.
