### ISSUE TITLE
activating a partial trust object from the dll that hosts it short-circuits the activation due to -opt

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#360]
When creating a partial trust object in the same DLL where the implementation lives, the `-opt` behavior short circuits activation (RoActivateInstance) and the object does is not created in RuntimeBroker.exe.

This DLL has many other objects and I want to retain the use of -opt at the scope of the project.

> Scott Jones:   Or just explicitly call what that default ctor would have called:

`Foo foo(impl::call_factory<Foo>([](auto&& f) { return f.template ActivateInstance<Foo>(); }));`

But this would access the impl namespace and we should not do that... so we need support in winrt/base.h.

**Comment by ChrisGuzak** [comment]
A work around seems to be to use `winrt::get_activation_factory<IFooStatics>(winrt::name_of<winrt::Foo>())`

**Comment by kennykerr** [comment]
Yes, you can always use one of the various activation helpers to directly call the factory and avoid any short circuiting.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.

**Comment by jonwis** [comment]
I've got a type, `TheType` that has multiple `ITheTypeStatics/2/3` interfaces hanging off of it.  I'd like to be able to say:

```c++
auto statics = winrt::get_factory_statics<winrt::TheType>();
auto x = statics.MethodOnInitialContract();
auto y = statics.MethodOnSecondContract();
```

For now I'll just do what @ChrisGuzak describes, getting the "main" factory statics and then using `.as<winrt::ITheTypeStatics2>()` to move up the version list.
