### ISSUE TITLE
CI build needs to compile with both Clang and VC

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#368]
We currently only build with Clang on non-Windows platforms. That means that C++/WinRT itself is never built with Clang as part of the build. We have a growing number of teams that need to use C++/WinRT with Clang on Windows so this is becoming very important.

**Comment by kennykerr** [comment]
Clang is unable to compile all of the C++/WinRT unit tests - hitting various compiler limits. We may reevaluate this issue in future if Clang improves.

**Comment by MarkIngramUK** [comment]
What about the code that is generated by C++/WinRT? If I reference the `<winrt/…>` headers from a project that is compiled with clang, is that a supported scenario? Do you have separate unit tests for the generated code?

**Comment by kennykerr** [comment]
Some teams use C++/WinRT in Clang builds, but Visual C++ continues to be the dominant compiler. I don't have any automated tests for Clang. Feel free to suggest something - contributions are welcome. :wink:

**Comment by MarkIngramUK** [comment]
Thanks @kennykerr , we build with both Clang and MSVC (on Windows), so this might be a useful thing for me to look at adding.
(We use both compilers on Windows, as we're cross-platform, so it's useful to build with the same compiler that we use on other platforms, for validation, and performance comparison etc.)
