### ISSUE TITLE
Move XamlMetaDataProvider.cpp out of CppWinRTAddXamlMetaDataProviderIdl target

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#369]
Some builds execute in multiple passes, with IDL and C++ compiled independently.  This causes XamlMetaDataProvider.cpp not to be compiled.  The solution is to move the ClCompile entry outside of the CppWinRTAddXamlMetaDataProviderIdl target with something like this:
```
 
  <ItemGroup Condition="Exists('$(GeneratedFilesDir)XamlMetaDataProvider.cpp')">
    <ClCompile Include="$(GeneratedFilesDir)XamlMetaDataProvider.cpp" />
  </ItemGroup>

```

**Comment by jlaanstra** [comment]
I believe this was already fixed as part of https://github.com/microsoft/xlang/pull/609

**Comment by kennykerr** [comment]
thanks again!
