### ISSUE TITLE
AppServiceConnection.OpenAsync() does not return .

### ISSUE THREAD

**Issue by scuhappy** [Microsoft/cppwinrt#37]
Below is my code:

```
IAsyncAction MainWindow::ConnectToServer()
{
	ui->listWidget->addItem("begin connect111");
	AppServiceConnectionStatus status = co_await m_Connection.OpenAsync();
	if (status == AppServiceConnectionStatus::Success)
	{
		ui->listWidget->addItem("connect success!");
	}
	else
	{
		ui->listWidget->addItem("connect failed!");
	}
}
```
the "connect success" or "connect failed" message never printed.
but the connection have been built already , I can send message to the server successfully and set the GPIO to make LED light On or OFF.
And when I call AppServiceConnection.Close(), then it print the "connect success" ,seems that the connect function does not  return until now.
below is my close function:
```
void MainWindow::on_CloseBtn_clicked()
{
	m_Connection.Close();
}

```

I create the AppServiceConnection class as a class member:

```
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();
	IAsyncAction ConnectToServer();
private slots:


IAsyncAction on_LEDOnBtn_clicked();

IAsyncAction on_LEDOffBtn_clicked();

void on_ConnectBtn_clicked();

IAsyncAction on_InitBtn_clicked();

void on_CloseBtn_clicked();

private:
    Ui::MainWindow *ui;
	//TServiceClient m_Client;
	AppServiceConnection m_Connection;
};
```

and set the service name at construct function:
```
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
	m_Connection.AppServiceName(L"App2AppComService");
	m_Connection.PackageFamilyName(L"TestService_nsmz8dbv8bkn8");
}
```

**Comment by scuhappy** [comment]
I use  
`AppServiceConnectionStatus status = m_Connection.OpenAsync().get(); `
instead, And it works OK,
I find that if I want to use co_await, I need to use it in a sub thread instead of GUI thread.

**Comment by kennykerr** [comment]
I’m not familiar with Qt, but for co_await to work from a UI thread that thread must be an STA with a compatible message pump that will allow the completion to be queued back onto the thread.

**Comment by scuhappy** [comment]
Thank you for your explanation.
