### ISSUE TITLE
Since upgrading to VS 2019 v16.3.2 Store Menu missing.

### ISSUE THREAD

**Issue by matthewacme** [microsoft/cppwinrt#375]
Version 16.2.3 of Visual Studio 2019 with the C++/WinRT addin installed I was able to right mouse on the project node for a store app that was part of a solution that contained a C++ project that targeted WinRT.
The store menu had an option to build for the store, and the WinRT built correctly for submission to the store.

I upgraded to v 16.3.2 of Visual Studio 2019, and the Store menu on the context menu was gone. I was able to build a store app using the Publish context menu, but that resulted in a build of the C++ WinRT project that failed Store Certification.

I uninstalled / reinstalled the VSIX AND the cppwinrt nuget packages, Still no love. Checked for updates to Visual Studio 2019 and downloaded and updated to v16.3.4 (latest release).

Still unable to access the Store menu and successfully build the C++ WinRT library to pass store certification.

Co-worker had not yet updated their installation of VS, they were still using v 16.2.3.
The co-worker was able to download the same source, and still had the `Store` menu in their context menu. They were able to build the project and the project passed Store Certification.

**Comment by matthewacme** [comment]
Visual Studio Current Configuration from About
Microsoft Visual Studio Professional 2019
Version 16.3.4
VisualStudio.16.Release/16.3.4+29409.12
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA931
Microsoft Visual C++ 2019

.ignore   1.2.77
A language service that makes it painless to handle all types of .ignore files such as .gitignore, .tfignore, etc.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.285.24939
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.3.285.24939
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.3.285.24939
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.285.24939
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.2000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.3.285.24939
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.2000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Child Process Debugging Power Tool   1.0
Power tool to add child process debugging to Visual Studio.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually

Git Tools 2019   3.1.1
This extension provides a git changes window, and menus to launch Git Bash, Git Extenstions and TortoiseGit.

GitHub.VisualStudio   2.10.7.8114
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IncrediBuild Build Acceleration   1.5.0.10
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JsonViewer   1.0
JSON viewer

Microsoft Azure HDInsight Azure Node   2.4.2000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.2000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.2000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.226
2.4.226

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Sharpen   0.10.0
Sharpen is a Visual Studio extension that intelligently introduces new C# language features into your existing code base. It makes your code smaller, simpler, faster, more expressive and more readable, in one word - sharper.

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

StopOnFirstBuildError   1.0
StopOnFirstBuildError

Stops a solution build immediately after a project has failed to build.

http://tech.einaregilsson.com/2011/01/06/stop-build-on-first-error-in-visual-studio-2010/

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.29230.54
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   16.0.29230.54
Visual C++ for Cross Platform Mobile Development (iOS)

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualLinter   1.1.0
Visual Studio JavaScript linter using ESLint.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Template Studio   3.4.19254.1
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

Xamarin   16.3.0.277 (d16-3@c0fcab7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.3.0 (d16-3/4d45b41)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@5608fe0abb3
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.4.0.2 (e37549b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by kennykerr** [comment]
We are away of some regressions in Visual Studio's store support. It would help greatly if you can [report this here](https://developercommunity.visualstudio.com/spaces/62/index.html). That way, the C++ team will automatically get a bug report filed against them. Feel free to link to your issue here and we'll make sure it gets attention.

**Comment by Noemata** [comment]
Using VS2019 v16.3.5, you get (right click on project node)->Publish->Associate App with the Store

In one instance I have a C++/WinRT component project and a C# UWP project (works).  In the other case I have a C++/WinRT component with a C++/WinRT UWP project (works).

**Comment by matthewacme** [comment]
> 
> 
> Using VS2019 v16.3.5, you get (right click on project node)->Publish->Associate App with the Store
> 
> In one instance I have a C++/WinRT component project and a C# UWP project (works). In the other case I have a C++/WinRT component with a C++/WinRT UWP project (works).

Thanks for the quick doublecheck @Noemata , While I do have the same menu `Publish` on my context menu, and it successfully builds my project, I fail certification for the store with an error of "Failed API Check".

When built using the Publish menu, instead of the Store menu, there is something in my C++/WinRT that compiles in such a way that it surfaces an API. Obviously the Store menu causes the build to happen such that the API is not erroneously marked as being used.

**Comment by Scottj1s** [comment]
​Do you have the "Desktop Development with C++"  workload installed, as suggested in the solution here?

https://developercommunity.visualstudio.com/content/problem/612880/store-menu-will-not-appear-for-template-project.html

**Comment by matthewacme** [comment]
Hello @Scottj1s , Yes, since the store menu was present and my project was building correctly and passing certification, prior to the VS upgrade, I had to have had the `Desktop Development with C++ ` package included in my install previously in order to work with the cppwinrt system.

But just to be sure, I tried uninstalling and reinstalling that package using VSInstaller, as suggested in that very article.

It had no effect.

**Comment by Scottj1s** [comment]
It appears that the Store context menu has simply been renamed to Publish (the menu items are identical), and that is independent of C++/WinRT - you see that with a C++/CX app project as well.  What is the API that is failing validation?

**Comment by matthewacme** [comment]
Hello @Scottj1s , again, I'm afraid you are mistaken. My fellow programmer has halted his upgrades of Visual Studio is currently running V16.2.3 and is able to build and pass certification when he uses the `Store` menu to build for the store.  

While he has the _Store_ menu on his project context menu he **also** has the _Publish_ menu, 

if he uses the _Store_ menu to build, it passes Certification. If he uses the _Publish_ menu, he gets the same app failed certification when tested using the Windows App Certification Kit.

**Comment by Scottj1s** [comment]
That may well be - I'm not an authority on Visual Studio - just reporting what I'm observing.  I also see that generating an appx package from VS 2017 via the Store menu, and from VS 2019 (16.3.5) via the Publish menu, and running them both through the app certification API test, they both pass.  This is based on the C++/WinRT blank app template, which most likely requires fewer imports than your project.  What API is failing for you?

**Comment by matthewacme** [comment]
hi @Scottj1s , I'll need to rebuild it again, that will take about 20 minutes, which I suspect goes to reaffirm your point that my project has a few more imports than the blank app template.

I suspect one of the imports in my C++/WinRT is causing the Publish menus build process to fail, where the Store menu succeeds.  I'll have that information for you as soon as the build process completes.

**Comment by Noemata** [comment]
Publishing to the Store with C++/WinRT has been working well.  C++/WinRT in particular is a huge improvement over C++/CX.  The VS2019 IDE still has a number of rough spots unfortunately.  There seems to be a lot of churn with Microsoft products of late, with less rigorous testing within some teams and design changes that seem to happen at will.  The folks working on C++/WinRT are most certainly on the high caliber side of things.  I wish the other teams were as fussy and as prudent.  If you can, install a VS2019 instance with most things turned on though obvious items such as Python can be left off.  If that works, then whittle back what's installed based on documented requirements for UWP.  The docs are getting better and are generally quite good.

**Comment by Scottj1s** [comment]
Thanks @Noemata.  I appreciate the feedback and recognition of good responses from the xlang team.  Unfortunately, there's only so much we can address if the issue ends up being in Visual Studio, as this one appears to be.

**Comment by matthewacme** [comment]
@Scottj1s 

I reference this back to you folks, because it was your nuget package with the VSIX that first put the _Store_ menu on my context menu. It seems sorta obvious to me that since your group added that specific menu, for just this particular type of project, there was something Unique to this groups _Store... | create app packages... _ over the already provided _Publish_ menu.

I was hoping you could tell me what the actual difference is (I'm assuming it adds some secret sauce into the build process) so that I could implement a work around.

![image](https://user-images.githubusercontent.com/11168104/66941463-e98f3700-f014-11e9-9726-f413df5ec365.png)

This is for an existing app in the store, hence why I'm not associating it 
![image](https://user-images.githubusercontent.com/11168104/66941525-0d527d00-f015-11e9-9d85-ae0d0a53da89.png)

![image](https://user-images.githubusercontent.com/11168104/66941552-1e9b8980-f015-11e9-9b7b-3d746a98b7e9.png)

![image](https://user-images.githubusercontent.com/11168104/66944061-6f61b100-f01a-11e9-9112-93e685f0487f.png)

![image](https://user-images.githubusercontent.com/11168104/66945793-a9808200-f01d-11e9-9874-ce23a85b2654.png)

Below is the output from the failed test.  Please note in particular the following entry from the reports information

**Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable.**

This makes me suspect that the _Store | create app packages_ menu makes the necessary change in order to prevent the environment from pulling in an unsupported API.

XML of results included as attachment
[cert test results.xml.txt](https://github.com/microsoft/cppwinrt/files/3735788/cert.test.results.xml.txt)



```
Supported API test

FAILED
    Supported APIs

    Error Found: The supported APIs test detected the following errors:
        API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. TectonicWinRT.dll calls this API.
    Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
    How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information:
    Alternatives to Windows APIs in Microsoft Store apps. 
```

**Comment by matthewacme** [comment]
@Scottj1s I appreciate that it is most likely a Visual Studio but that is [breaking your VSIX add-in you offer / support](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264), but until they get their stuff together, perhaps you folks could tell me what your VSIX exactly did to add the Store build to the Context menu, and how I can work around it's absence while we wait for you folks to coordinate with VS group to fix your VSIX?

**Comment by matthewacme** [comment]
@Scottj1s 
Oh and yes I did uninstall / reinstall the C++/WinRT VSIX module.

**Comment by Scottj1s** [comment]
The C++/WinRT VSIX does not add the Store context menu to your project - this occurs with CX projects as well.  C++/WinRT does not modify the VS UI in any way (other than adding debug visualizations).  The menu change is due to a Visual Studio update, and not the C++/WinRT VSIX.

Regarding the API issue, __CxxFrameHandler4 was recently added to the VC Runtime as part of the [Frame Handler version 4 ("/FH4")](https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/) optimization work.  The link indicates it was disabled for store apps due to runtime support, but enabled for v16.3, consistent with your experience.  It appears there may now be a version mismatch between your /FH4 use and the app certification kit.  With this information, the Visual Studio team should now have enough to address the issue.

**Comment by matthewacme** [comment]
thank you for the clarification on the VSIX... I had assumed that was what added it, since it hadn't been available to me until after I installed the Nuget and the VSIX.  Well to be fair, I didn't notice until after I had installed those two items, maybe it was always there...

I'm glad I got you the correct information so you could help me get it noticed by the correct people to get it fixed.

**Comment by Scottj1s** [comment]
good luck, Matthew!
