### ISSUE TITLE
How can I new a winrt object?

### ISSUE THREAD

**Issue by scuhappy** [Microsoft/cppwinrt#38]
I want to new a winrt object , but can not , the compiler said the operator has been deleted..
![image](https://cloud.githubusercontent.com/assets/4221635/19993249/1cbde57c-a27f-11e6-987c-d33f32a764dd.png)

![image](https://cloud.githubusercontent.com/assets/4221635/19993317/9d6784e4-a27f-11e6-8150-198d7a7af4ef.png)

**Comment by BrentRector** [comment]
AppServiceConnection m_Connection;

**Comment by scuhappy** [comment]
I want to use a pointer to a object, how can I do this?

**Comment by scuhappy** [comment]
And do you know how to convert a IInspectable value to a hstring value? It makes me crazy now.

**Comment by kennykerr** [comment]
I talked about the relationship between [objects and instances here](https://moderncpp.com/2015/04/07/a-classy-type-system-for-modern-c/). You don't need pointers to WinRT objects in C++/WinRT.

**Comment by scuhappy** [comment]
Get that! Thank you so much!
