### ISSUE TITLE
IntelliSense is getting slaughtered

### ISSUE THREAD

**Issue by Noemata** [microsoft/cppwinrt#384]
Using the VS2019 Windows Runtime Component (C++/WinRT) template to create a component, you wind up with an unusable IntelliSense context.

Here are two variations.  The first, with nothing changed after the project is generated reports 5 errors.  The second, with only modest changes reports 5K errors.

![image](https://user-images.githubusercontent.com/6632315/66927189-64e4ee80-effd-11e9-9ef7-831bcb53f226.png)

![image](https://user-images.githubusercontent.com/6632315/66927233-74fcce00-effd-11e9-9ec3-7d5f198b8bcb.png)

**Comment by ChrisGuzak** [comment]
I've created an issue here:
https://developercommunity.visualstudio.com/content/problem/836608/c-intellisense-is-broken-with-the-latest-version-o.html

**Comment by ChrisGuzak** [comment]
@kennykerr can you re-activate this to track implementing the work around?
```
<- template <> inline constexpr auto& name_vWindows::Foundation::Point{ L"Windows.Foundation.Point" };
-> template <> inline constexpr auto& name_vWindows::Foundation::Point = L"Windows.Foundation.Point" ;
```
