### ISSUE TITLE
How to convert a IInspectable value to a hstring value?

### ISSUE THREAD

**Issue by scuhappy** [Microsoft/cppwinrt#39]
I meet this problem  when I want to parse a ValueSet type value, and get the value of it.

**Comment by andrew7webb** [comment]
I had this question too.   See Closed Issue #21 

void myButtonClick(
 winrt::Windows::IInspectable const & sender,
 const Windows::UI::Xaml::RoutedEventArgs & args )
 {
 Button sendButton = sender.as();
 IPropertyValue senderContent = sendButton.Content().as< IPropertyValue >();
 hstring hstr= senderContent.GetString();
 std::wstring wstr = hstr;
 textBlock.Text( wstr ); // L"Method hit"
 UNREFERENCED_PARAMETER(args);
 }

when the button's Content was originally set with:
oid setButtonContent(Button & button, const std::wstring & text )
 {
 Windows::IInspectable value = PropertyValue::CreateString(text);
 button.Content(value);
 }

**Comment by kennykerr** [comment]
What Andrew said. You can use PropertyValue or IStringable, but it really depends on what the IInspectable actually represents.

**Comment by scuhappy** [comment]
Thank you! I will close this issue
