### ISSUE TITLE
Is it possible to use cppwinrt in one single application that runs both on Win10 and Win7?

### ISSUE THREAD

**Issue by Andreas0xffff** [Microsoft/cppwinrt#40]
At the moment, cppwinrt statically links to system librarys (API-MS-WIN-CORE-WINRT-L1-1-0.DLL) that only exist in Win10.
Is it possible to dynamically link all of the necessary dlls?

**Comment by kennykerr** [comment]
You can use [delay loading](https://msdn.microsoft.com/en-us/library/151kt790.aspx) to achieve this.

**Comment by BrentRe** [comment]
Note that the app will not be able to use *any* C++/WinRT functionality when running on Win7 as the Windows Runtime does not exist on Win7.

**Comment by kennykerr** [comment]
Right, delay loading is useful if you have to ship the same binary on different platforms but only "light up" with WinRT on Windows 8+.

**Comment by jhatch28** [comment]
I have attempted this by specifically listing the DLLs  that showed up under `dumpbin /depends` with `/DELAY`, and each time my executable attempts to load all of them before my `WinMain` is called, despite them each being listed as delay load dependencies. Does this mean that linking with C++/WinRT causes code from its libs to run at startup? Should I make a new issue on this?

**Comment by BrentRe** [comment]
C++/WinRT does not provide any libs. It is a header-file only library. It sounds like your C++ project configured is using an SDK for Win10 and/or project settings to say "build as a Win10 app." That would bring in the reference to the WINRT APISet dll.

You'll likely need to look at a project that's specifically targeting the down-level OS release that you need to run on. Then copy the appropriate settings (linker libs in this example), to your C++/WinRT project.

**Comment by walbourn** [comment]
The Windows 10 SDK will support targeting Windows 7 Service Pack 1 for "classic" Win32 desktop apps, but you need to set ``_WINNT_WIN32`` to ``0x0601`` rather than ``0x0A00``.

**Comment by jhatch28** [comment]
>Getting a single EXE to work as both a Win32 'classic' desktop app and a UWP app for Windows 10 is not practical.

After fighting this for quite some time, I'd agree. At this point I'm just going to deploy different EXEs based on OS version, which is really no big deal.

@BrentRe I played around with changing the Windows SDK Version and Platform Toolset to no avail. When attempting to compile with an older SDK (or toolset), I can't use the `/std:c++latest` flag, so there are unsupported language features that prevent compilation. I was able to use Windows SDK Version **7.0** with **Visual Studio 2017 - Windows XP (v141_xp)**, but that still caused the delay load errors.

**Comment by walbourn** [comment]
You don't need to use the ``v141_xp`` Platform Toolset and the Windows 7.1 SDK to target Windows 7 SP1, only if you need to support Windows XP SP3 / Windows Server 2003 SP1.

The ``v141`` Platform Toolset and the Windows 10 SDK are fine as long as you don't need to target older than Windows Vista SP2.

[Dual-use Coding Techniques for Games](https://blogs.msdn.microsoft.com/chuckw/2012/09/17/dual-use-coding-techniques-for-games-part-1/)

[Visual Studio 2012 Update 1](https://blogs.msdn.microsoft.com/chuckw/2012/11/26/visual-studio-2012-update-1/)

**Comment by jhatch28** [comment]
@walbourn I was just attempting those in response to @BrentRe's suggestions

**Comment by BrentRe** [comment]
My suggestion was that you update the existing VS2015/2017 project to link to the same libraries used by a project targeting your target OS. I did not suggest trying to compile C++/WinRT with a very old toolset. That will not work, as you discovered.

Compiling C++/WinRT requires a very up to date C++ compiler. In fact, the next release of C++/WinRT will require a minimum compiler of VS 2017 Update 3 (aka 15.3 RTM) in order to compile our header files. Only that compiler contains support for the C++ language features used in the header files of the next release.

**Comment by daxpedda** [comment]
So it was not quite clear to me if somebody actually got it to work on Windows 7.
As far as I understand it shouldn't work, but the comments here gave me some false hope I think ;).

So while reading through this and some linked articles I added `_WINNT_WIN32=0x0601;WINVER=0x0601;WINAPI_FAMILY=100;` to the Preprocessor Definitions, with the same results.
I used the newest Visual Studio 2017 with the with the Windows 10 SDK (10.0.15063.0), is there anything else I forgot?

**Comment by walbourn** [comment]
What would you do with C++/WinRT on Windows 7? The OS doesn't implement any Windows Runtime types to consume,

**Comment by daxpedda** [comment]
Of course ... I misunderstood the discussion of this Issue, thanks for the clarification.

**Comment by CodeChief** [comment]
I've noticed these type of questions so often and had them myself at the beginning. I think the underlying misunderstanding is people thing this C++/WinRT thing is a new clean template library which revolutionizes C++ programming for the whole Windows SDK API surface. But sadly that is only valid in scope of the new Windows 10 ABI.

With MFC and ATL being considered legacy then, why don't Microsoft make a new core template library that has nothing to do with specific platforms or outdated technologies? Like a Microsoft Boost (of course using Boost is the next best alternative). The standard C++ and C libraries are a mess, just look at the out the box string, locale and type conversion! This is core stuff which should be available out the box with Visual Studio and Windows SDKs.  We need a suite of language extensions, types and templates with simple intuitive naming/hierarchy and no complex signatures/dependencies (better streams, buffers, smart pointers).

C++ is getting already getting much better and easier to work with each new Visual Studio release. It seems like it's going this way anyway but there's really an immediate demand for something as clean as C# but still as powerful as C++, whilst remaining alignment to the standards and cross-platform capabilities Microsoft are now adopting well.
