### ISSUE TITLE
Latest nuget breaks intellisense with lots of E0461s

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/cppwinrt#401]
Latest nuget package is overwhelming intellisense by throwing E0461s.

https://developercommunity.visualstudio.com/content/problem/253927/incorrect-c-code-compiles-intellisense-warns-with.html

**Comment by kennykerr** [comment]
Is this the "initial value of reference to non-const must be an lvalue" warning? I just start noticing this today.

**Comment by kennykerr** [comment]
I haven't investigated this issue, but for what it's worth I can no longer reproduce this with VS 16.4 Preview 2.

**Comment by kennykerr** [comment]
This is confirmed to be a bug in the IntelliSence compiler. A fix is planned for 16.5.
