### ISSUE TITLE
Add boxing support for arrays

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#407]
The `box_value` and `unbox_value` helpers should provide support for boxing and unboxing arrays via `IReferenceArray<T>`.

**Comment by FredeJ** [comment]
I'm sorry for budding in here but is this missing feature the reason why I am unable to solve this issue?  😄 https://stackoverflow.com/questions/58878974/how-to-unbox-multivalue-string-in-c-winrt?noredirect=1#comment104029524_58878974

**Comment by kennykerr** [comment]
Sorry for the delay @FredeJ - yes it looks like it would simplify that example.

**Comment by kennykerr** [comment]
We probably need to extend `reference_traits` to cover the array types that `PropertyValue` provides and then extend the custom `IReference` implementation (or add a parallel array implementation) to support arrays of types not covered by `PropertyValue`. We then just need to make sure the boxing helper functions support both array and non-array types. 

Care should be taken that the developer experience is natural and idiomatic for C++ developers. Finally, testing this should be pretty exhaustive both to ensure existing boxing behavior isn't affected and that arrays are supported comprehensively.

**Comment by DefaultRyan** [comment]
I've been wanting this as well lately. I was wondering, given that the state of arrays in the C++ type system is slightly murky, would it be preferable instead to provide
- `IInspectable box_array(array_view<T>)`
- `com_array<T> unbox_array(IInspectable)`

That would eliminate any potential collisions with boxing other types.

**Comment by kennykerr** [comment]
Yes, I like that - seems like it would be less likely to break the world. 😉

**Comment by kennykerr** [comment]
I'm unlikely to get to this. Feel free to keep the conversation going and contribute a PR as needed.
