### ISSUE TITLE
Build fails with "unresolved external symbol WINRT_GetErrorInfo" after upgrading to the latest NuGet package (v2.0.191018.6)

### ISSUE THREAD

**Issue by tim-weis** [microsoft/cppwinrt#410]
I just upgraded a C++/WinRT Windows Runtime Component project to use the latest NuGet package v2.0.191018.6<sup>1</sup>. After doing so, the build fails with link errors:

>     unresolved external symbol WINRT_GetErrorInfo

Is this a regression in C++/WinRT, an issue with my project, or have the library requirements changed for some reason in the latest release?

Note: Changing the project configuration's linker settings to explicitly link against OleAut32.lib solves the immediate issue, although I don't know whether doing so will subsequently fail store submission certification; there's no information on the [GetErrorInfo](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-geterrorinfo) documentation, and it's not listed under [APIs present on all Windows 10 devices](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis) either.

---

<sup>1</sup> *Upgrading to NuGet package v2.0.191029.4 exhibits identical behavior.*

**Comment by kennykerr** [comment]
`GetErrorInfo` is now used by C++/WinRT to provide greater interoperability with legacy APIs. This function is allowed for store submissions. All the functions C++/WinRT requires may be resolved using `onecore.lib` - I'd suggest using that.
