### ISSUE TITLE
"T must be WinRT type" error for GUID properties

### ISSUE THREAD

**Issue by osolo** [microsoft/cppwinrt#412]
Adding GUID properties in an .idl files leads to the following error:

> C2338	T must be WinRT type.

Sample .idl:
```
namespace CppWinRTXaml
{
    [default_interface]
    runtimeclass BlankUserControl : Windows.UI.Xaml.Controls.UserControl
    {
        BlankUserControl();
        Guid MyProperty;
    }
}

```

The error stems from the generated `XamlTypeInfo.Impl.g.cpp` using `GUID` and not the newer `winrt::guid` class:
```

const MemberInfo MemberInfos[] = 
{
    //   0 - CppWinRTXaml.BlankUserControl.MyProperty
    L"MyProperty",
    &GetValueTypeMember_MyProperty<::winrt::CppWinRTXaml::BlankUserControl, GUID>,
    &SetValueTypeMember_MyProperty<::winrt::CppWinRTXaml::BlankUserControl, GUID>,
    0, // Guid
    -1,
    false, false, false,
};

```

As a temporary workaround, I added the following to my `pch.h` (but I cannot guarantee correctness):
```
namespace winrt
{
    template <>
    inline Windows::Foundation::IInspectable box_value<GUID>(GUID const& value)
    {
        return Windows::Foundation::IReference<winrt::guid>(winrt::guid(value));
    }
}
```

**Comment by kennykerr** [comment]
@danzil do you know whether this is an issue with the Xaml compiler generated code?

**Comment by danzil** [comment]
@kennykerr, is the guidance for developers to use winrt::guid in their code? If yes, then the generated code should also use winrt::guids and I'll make this a bug on WinUI 3. If no, then I guess cppwinrt should add support for that.

**Comment by kennykerr** [comment]
@danzil it's both. In general, C++/WinRT lets you use `GUID` where `winrt::guid` is expected. However, as a type parameter, `winrt::guid` must be defined as it is used in various recursive calculations following type instantiation. So I'll update `winrt::box_value` to likewise handle `GUID`, but if you're generating code that generates `GUID` types then you should prefer to use `winrt::guid` as only the latter is strictly speak a "WinRT type".
