### ISSUE TITLE
project system generates C++ CX code when WindowsTargetPlatformVersion version is missing specific suffix

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#414]
When accepting the defaults in the UI of the the VS "Retarget Projects" feature (Projects.Retarget solution) the `WindowsTargetPlatformVersion` value in the .vcxproj file is modified, removing the numeric suffix. This results in the XamlCompiler generating C++ CX code that does not compile. Manually adding back the suffix works around this or select a specific SDK version. 

C++ WinRT project settings configure the xaml compiler, so perhaps this is a bug there or an issue with the compiler itself.

fix
```
-    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
+    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
```

**Comment by kennykerr** [comment]
Adding @danzil for comment.

**Comment by danzil** [comment]
There is a property that the Xaml Compiler uses to determine the language to be used: $(XamlLanguage). I believe the cppwinrt props/targets set that property early on, which would indicate this is an issue upstream from Xaml.

**Comment by kennykerr** [comment]
We are not actively investing further in our msbuild support. If there is a workaround or fix available, please feel free to contribute.
