### ISSUE TITLE
Using IMap/IObservableMap as ItemsSource for ListView

### ISSUE THREAD

**Issue by Holo-Krzysztof** [microsoft/cppwinrt#418]
I've described the problem on [StackOverflow](https://stackoverflow.com/questions/58816784/binding-iobservablemap-to-an-itemscontrol-e-g-listview) already and also filed a [docs issue](https://github.com/MicrosoftDocs/windows-uwp/issues/2077) before finding out that the docs are actually technically right.

To summarize, I can bind an `IVector<T>` to a ListView control just fine, but when I substitute it with an `IMap<K,V>` or `IObservableMap<K,V>` I get exceptions. As I've found out this is due to `IMap<K,V>` not implementing `IIterable<IInspectable>` which is what the ItemsSource property expects.

However, it is possible to use Dictionary in C# and everything works just fine, so there must be something else happening here. Do you know how to CLR handles this and how I can accomplish this in C++?

**Comment by kennykerr** [comment]
This question is specific to the Xaml API. I suggest bringing it up on the Xaml issues page:

https://github.com/Microsoft/microsoft-ui-xaml/issues

**Comment by kennykerr** [comment]
Here is a simple implementation that implements IIterable<IInspectable>, as has been suggested by the Xaml team. If someone can test this against Xaml and confirm that this provides the desired behavior then we can update C++/WinRT to do the same.

https://gist.github.com/kennykerr/6eace7378a1a06b5e2f21da127be102a
