### ISSUE TITLE
winrt::array_view cannot convert from gsl::span or other such representations

### ISSUE THREAD

**Issue by miniksa** [microsoft/cppwinrt#421]
Trying to use something in an already safe structure like a gsl::span<T> or a std::basic_string_view<T> (until C++20's std::span<T>) should be easily convertable to winrt::array_view<T>.

I've found it is not.

winrt::array_view<T> seems to accept either a bare array, a std::array<T>, or a std::vector<T>. 

While I'd like it to naturally accept the gsl::span<T> or std::basic_string_view<T>, that might be difficult. But I had expected to at least be able to pass the .data() and .size() elements directly over to the other form.

However, that particular constructor is hidden from public view on winrt::array_view<T>. 

This represents a request to either make that constructor public so I can just hand over the data and size members to effectively yet-another-span type or to implement constructors accepting conversions from GSL and STD types that are spans as well.

**Comment by miniksa** [comment]
So the guidance is then "suck it up buttercup and suppress your cppcorechecks warnings about bare pointer math because this train ain't leaving the station until mid to late 2020 when `std::span` should arrive?"

I can do that. Just confirming.

**Comment by kennykerr** [comment]
Pretty much. 😄

**Comment by miniksa** [comment]
Alrighty. Thanks, Kenny. Works for me.
