### ISSUE TITLE
Maps (propertysets) of K to Object could get an unboxing [Try]Lookup

### ISSUE THREAD

**Issue by jonwis** [microsoft/cppwinrt#427]
There's a bunch of code like this:

```c++
ValueSet v = /* ... */
auto g = winrt::unbox_value<winrt::guid>(v.Lookup(L"someKey"));
auto q = winrt::unbox_value_or<winrt::hstring>(v.TryLookup(L"anotherKey"), winrt::hstring{});
```

It'd be neat if 'unbox object to type' was directly supported so I could have written:

```c++
ValueSet v = /* ... */
auto g = v.Lookup<winrt::guid>(L"someKey");
auto q = v.TryLookup<winrt::hstring>(L"anotherKey");
```

**Comment by kennykerr** [comment]
Perhaps more generally, `IInspectable`'s `as` function should support unboxing in addition to queries.

Today:

```C++
IInspectable a = ...
IStringable s = a.as<IStringable>();
```

Future:

```C++
IInspectable a = ...
hstring s = a.as<hstring>();
```

If that were so, your lookup example would work as follows:

```C++
ValueSet v = ...
auto s = v.Lookup(L"someKey").as<hstring>();
```

A little more generic and composable and not "hardcoded" for `IMap` and `IMapView`.

**Comment by oldnewthing** [comment]
I think there's a small typo in the proposal above. `as<hstring>()` would *throw* if not a boxed `hstring`, whereas it is `try_as<hstring>()` that returns an empty string on failure.

**Comment by kennykerr** [comment]
I've returned to this issue every few weeks with a different solution and every time I've come up short with various drawbacks. So I finally settled on something a little more conservative. I hope you like it: #688

**Comment by kennykerr** [comment]
This has now been fixed: https://github.com/microsoft/cppwinrt/pull/695
