### ISSUE TITLE
MIDL2011 When consuming interface from C# Runtime Library within same solution

### ISSUE THREAD

**Issue by MarkARussell** [microsoft/cppwinrt#429]
I have a solution in which I've defined a C# based Windows Runtime Component (WRC) library with a single interface in it.  In the same solution I've created a C++/WinRT WRC project that has a project reference to the C# WRC project.  Further, in the C++/WinRT project I've created an .idl file with a class that attempts to implement the interface defined by the C# library.

At compile time, I receive a MIDL2011 error stating 'unresolved type declaration' for the interface that the class is attempting to use.  If instead of a project reference, I add a direct reference to the winmd produced by the C# library, then the midl error goes away.  It is my assertion that adding a direct reference to the winmd is only a work-around and that a project reference should be sufficient.

Note that this appears to be a regression as this same scenario worked previously with 1.0.190211 (and without the direct winmd reference).

I have attached the solution/project files that reproduces this issue.

[ConsumeCSharpWrcUsingCppWinRT.zip](https://github.com/microsoft/cppwinrt/files/3856250/ConsumeCSharpWrcUsingCppWinRT.zip)

**Comment by kennykerr** [comment]
@jlaanstra or @Scottj1s - do you know whether this is a regression? I can confirm the behavior reported here.

**Comment by kennykerr** [comment]
> It is my assertion that adding a direct reference to the winmd is only a work-around and that a project reference should be sufficient.

I will just add that this workaround is required more often than we'd like due to various limitations/bugs in the Visual Studio support for cross-language references. That may be your best bet.
