### ISSUE TITLE
Uncompilable/unimplementable stubs generated when interface function name conflicts exist

### ISSUE THREAD

**Issue by MarkARussell** [microsoft/cppwinrt#430]
The current version of CppWinRT (2.0.191111.2) generates stubs that are unusable if there are conflicting function definitions in the interfaces implemented by a runtimeclass.  A contrived example is embedded below.  In my specific case, I was trying to implement a C# interface that derived from IEnumerable<T>.  In C++/WinRT IEnumerable appears to derive from both IBindableIterable and IIterable, and have a conflicting First() function.

C++/CX had a mechanism where you could implement the function with a different name and assign that function as the interface implementation function.  Perhaps something similar could be done in the IDL?  So far though, I have been unable to come up with a work-around to this situation beyond "don't do that".  The standard C++ work-around for this would be helper classes that individually implement the interface and provide alternatively named functions.  However given the restrictions on composable classes, I've been unable to figure out a way to use this approach.

I fully realize that this might not be something best handled by the stubs generator, but perhaps some guidance as to how best to handle this situation could be added to the documentation? 

Related stackoverflow: https://stackoverflow.com/q/58920573/10876559

Contrived Example IDL:
```
namespace CppImplementation
{
    interface InterfaceOne
    {
        Int32 GetValue();
    }

    interface InterfaceTwo
    {
        Single GetValue();
    };

    [default_interface]
    runtimeclass ClassWithConflicts : InterfaceOne, InterfaceTwo
    {
        ClassWithConflicts();
        Int32 MyProperty;
    }
}
```

Resulting generated class:
```
    struct ClassWithConflicts : ClassWithConflictsT<ClassWithConflicts>
    {
        ClassWithConflicts() = default;

        int32_t MyProperty();
        void MyProperty(int32_t value);
        int32_t GetValue();  <-- Function differs only by return type
        float GetValue();    <-- Function differs only by return type
    };
```

[CppWinRT_IEnumerable_CodeGenProblem.zip](https://github.com/microsoft/cppwinrt/files/3865710/CppWinRT_IEnumerable_CodeGenProblem.zip)

**Comment by kennykerr** [comment]
[Here's an example of how to handle this](https://github.com/microsoft/cppwinrt/blob/190a347999a87b73e7450370158ab86bed64b07c/strings/base_collections_vector.h#L58). There are other options, but this is probably the simplest for your scenario. 

[More info](https://devblogs.microsoft.com/oldnewthing/20191106-00/?p=103066).

**Comment by MarkARussell** [comment]
My searchFu has clearly failed me as that is exactly what I've been looking for.  Thank you so much.

I'll be sure to update the stackoverflow question later in case others run across it in the future.
