### ISSUE TITLE
cppwinrt.exe v3 simple model code generation feature

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/cppwinrt#431]
Just making a v3 feature request. I find that I'm adding simple models with IPropertyNotify and would love cppwinrt to generate a completely code generated model, without stubs. It could support things like all the various copy construction, default event handling and property "get/set"

I realize this request expands the scope of the code generator, but it seems like going from midl3 to code that I don't have to write could really take this to the next level. It's essentially what c++/cx used to do.

**Comment by kennykerr** [comment]
Have you considered using the winmd reader to generate your own domain-specific code? This is what cppwinrt uses to parse winmd files:

https://github.com/microsoft/winmd

I'm not saying it's a bad idea, but it may help to experiment with a separate tool before considering a contribution to cppwinrt itself.
