### ISSUE TITLE
WINRT_IMPL_AUTO should be included in the hint file

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#434]
Creating an issue for this comment.

According to https://github.com/microsoft/cppwinrt/pull/433#discussion_r351522551

> Going through this macro route, it would be a "syntax changing macro" that probably should be included in the [hint file](https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019).

@LukaszMendakiewicz are you suggesting we add this to the VSIX project templates?

**Comment by LukaszMendakiewicz** [comment]
Yes, dropping cpp.hint in the generated project structure should work for this purpose.

**Comment by kennykerr** [comment]
@LukaszMendakiewicz I looked at the doc page, but it's not clear what problem this would solve for C++/WinRT developers. Any thoughts?

**Comment by LukaszMendakiewicz** [comment]
There is not a simple answer to "what problem this would solve". Generally it will cause the IntelliSense engine to operate with less accurate information, with more heuristics, which would lead to less accurate results.
Two pieces of UI where the difference would be visible are for example:

1) "Go to All" details panel, which for `WINRT_IMPL_AUTO(int)` would either show verbatim that or `int` as a return type of the function in absence/presence of the hint file.
2) Right-click in editor > Rescan > Display Browsing Database Errors will report all the usages.

So probably overall it is not a huge deal, but if you have a chance to drop the hint file, it will have some benefit.
