### ISSUE TITLE
missing right } 

### ISSUE THREAD

**Issue by oldoldman** [microsoft/cppwinrt#436]
Hi dear all,
take a look at following code please
`namespace wf = winrt::Windows::Foundation;`
`wcout << name_of<wf::IUnknown>() << endl;`

the output is : {00000000-0000-0000-c000-000000000046
the right } is missing , many thanks!

**Comment by kennykerr** [comment]
Thanks for reporting this. I can't repro this with the latest build. It's likely I fixed this at some point and you just need to grab a newer build.
