### ISSUE TITLE
Safety of manipulating member variables in async callback?

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#437]
In my code, I fire off a task at startup, which when completed assigns the result to a member variable:
```cpp
// Error checking ignored
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::ApplicationModel;
using Collections::IVectorView;
StartupTask::GetForCurrentPackageAsync().Completed([this](const IAsyncOperation<IVectorView<StartupTask>> &op, AsyncStatus)
{
	m_StartupTask = op.GetResults().GetAt(0);
});
```
There doesn't seem to be actually much details on how safe that is (except if `this` gets destroyed, which is already greatly covered) because as far as I understand, the result of the operation might very well run on another thread (documentation on apartments isn't very clear about this one) and therefore face concurrency issues. This class currently does not have any thread safety included, and I am not sure if I should add some around `m_StartupTask` to avoid concurrency issues (or if WinRT consumer types already are thread-safe)

**Comment by kennykerr** [comment]
In general, implementations should be agile but that's up to the implementation. An agile object may be accessed from any thread or apartment. If the API is not agile then you can use `apartment_context` or `resume_foreground` depending on the API. Regardless of apartment context, any concurrency you introduce (such as the example above) needs appropriate locking if you think there may be a race. WinRT does not provide any such thread-safety automatically, except what may be provided implicitly by using something like `resume_foreground` or `thread_pool` to queue work onto a single thread.
