### ISSUE TITLE
cppwinrt -optimized generates .g.cpp files with calls to make instead of winrt::make

### ISSUE THREAD

**Issue by jevansaks** [microsoft/cppwinrt#442]
Minor issue, but we don't do a "using winrt" in our project and so `winrt::make` and things like it need to be fully qualified namespaces. C++/WinRT's generated code is pretty good about sticking to fully qualified references, except for in the -optimize generated files. I am seeing naked `make` in there:

```c++
    AcrylicBrush::AcrylicBrush() :
        AcrylicBrush(make<Microsoft::UI::Xaml::Media::implementation::AcrylicBrush>())
    {
    }
```

I think the problem is here:

https://github.com/microsoft/cppwinrt/blob/d9862149abbeb9396808f0ea5d1f1c4510c861a2/cppwinrt/component_writers.h#L412

Please update this to be winrt::make? Thanks!

**Comment by kennykerr** [comment]
Why is that a problem? This code should be generated within the `winrt` namespace and thus not need to be fully qualified.

**Comment by jevansaks** [comment]
Ohhh ok. You're right. Sorry!
