### ISSUE TITLE
IReference<Enum> should return Type() as PropertyType::UInt32 or Int32

### ISSUE THREAD

**Issue by jevansaks** [microsoft/cppwinrt#446]
The IReference<T> implementation always returns "OtherType" from Type() but this causes XAML to go down a fallback codepath where it queries GetRuntimeClassName() and then uses the string name to try to figure out what the boxed type is.

This is just inefficient most of the time but with WINRT_LEAN_AND_MEAN it stops working because those strings aren't returned anymore.

Hopefully it's simple to fix the Type() implementation to return Int32 or UInt32 instead.

**Comment by kennykerr** [comment]
https://github.com/microsoft/cppwinrt/pull/447

Will this do?

**Comment by jevansaks** [comment]
Looks like it to me! Is it possible to try the cppwinrt.exe from that change in my local MUX build?

**Comment by kennykerr** [comment]
Here you go: \\scratch2\scratch\kennykerr\cppwinrt.exe

Let me know if this is good and I'll spin another published build.

**Comment by jevansaks** [comment]
You did what I asked but unfortunately there's still something wrong on the XAML side that I need to look into, and it makes me think that I'm wrong about what the behavior should be. I'll debug more and let you know.

**Comment by jevansaks** [comment]
I sent email on another thread -- the issue that came up with XAML where Style setters don't work with WINRT_LEAN_AND_MEAN is the same. XAML ends up using the GetRuntimeClassName on the `IReference<T>` to preserve type information. It's arguably a bug in XAML but not one we can fix soon. :(

Either we just can't use WINRT_LEAN_AND_MEAN or we need the IReference type names included.

**Comment by kennykerr** [comment]
Fixed in https://github.com/microsoft/cppwinrt/pull/451
