### ISSUE TITLE
Coroutine resumption logic can cause RPC_E_WRONG_THREAD exception.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#458]
Some WinRT methods return back on a thread with apartment type APPTYPE_NA. This in turn can cause E_RPC_WRONG_THREAD when calling GetResults(). In the example code below `GetToastCollectionAsync` returns on a thread with apartment type APPTYPE_NA, causing the issue:

```
    winrt::fire_and_forget Test()
    {
        co_await resume_background();

        auto notificationManager = ToastNotificationManager::GetDefault();
        ToastCollectionManager collectionManager = notificationManager.GetToastCollectionManager();
        ToastCollection collection = co_await collectionManager.GetToastCollectionAsync(L"Test");

        InMemoryRandomAccessStream testStream{};
        auto decoder = co_await BitmapDecoder::CreateAsync(testStream);
    }
```

**Comment by BenJKuhn** [comment]
This is a long-standing design issue with toast notification manager. You can see a very early discussion about it here:
https://stackoverflow.com/questions/8057821/backgroundworker-returns-to-wrong-thread

Although it allows you to start the async operation on a background thread, it expects completion to occur on a UI thread. Because you have co_await resume_background() in your code above, the entire operation is running on a background thread, and trying to complete there as well (in this case, the NA is the neutral apartment, which is where COM typically dispatches multi-threaded work queued by a cross-process COM call). This is not a C++ WinRT issue. You can file an issue against the API using feedback hub. Use category developer platform -> notifications and tiles. I'm going to close out the issue here since this is not an issue in the C++ /WinRT projection, but rather an issue with the API implementation.

**Comment by jlaanstra** [comment]
This regressed with #546 and worked before that change. Therefore I believe this should still be fixed and also provided a fix that solves this.

**Comment by BenJKuhn** [comment]
In that case I'll wait and see what Kenny thinks. After looking at that change, my guess is that this is by design though, and that the old behavior was doing more work than it should have to the detriment of everything else.

**Comment by kennykerr** [comment]
Will take a look soon. Down with the flu.

**Comment by kennykerr** [comment]
I'm inclined to agree with Ben. This may have worked before, but if it did then it was just an accident. If the API expects to complete on a UI thread, then the caller must be on that UI thread when using `co_await` - that will ensure that the thread context is restored prior to calling `GetResults` This is and has always been the only supported behavior. Most APIs with such an expectation will raise the "wrong thread" error early, but some don't.

**Comment by jlaanstra** [comment]
@kennykerr 
> that will ensure that the thread context is restored prior to calling GetResults This is and has always been the only supported behavior.

My understanding is that if I am on Context1 before calling co_await, I should be on Context1 after co_await and your comment suggests that this is the only supported behavior. This is also what the docs say at https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2. This bug shows a case where this behavior is no longer what is happening.

Here's the above code snippet with more comments:

```
    winrt::fire_and_forget Test()
    {
        co_await resume_background();
        // We are in MTA

        auto notificationManager = ToastNotificationManager::GetDefault();
        ToastCollectionManager collectionManager = notificationManager.GetToastCollectionManager();

        // We are still in MTA
        ToastCollection collection = co_await collectionManager.GetToastCollectionAsync(L"Test");
        // We are now in NA, because GetToastCollectionAsync returns in NA
        // Because the call wasn't started from STA, the following code is run, and execution continues in the NA. This the bug as the co_await contract says it should run on the MTA:
        // if (is_sta())
        // {
        //     resume_background(handle);
        // }
        // else
        // {
        //     handle();
        // }

        InMemoryRandomAccessStream testStream{};
        // We are still in NA
        auto decoder = co_await BitmapDecoder::CreateAsync(testStream);
        // CreateAsync callback comes back on MTA, and calling GetResults() causes the E_RPC_WRONG_THREAD 
    }
```

If we simply invert the optimization logic from https://github.com/microsoft/xlang/pull/546 as I do in https://github.com/microsoft/cppwinrt/pull/459 this works as expected.

**Comment by kennykerr** [comment]
I see, the NA is confusing things. That's rather unorthodox for a WinRT API. We just need to be extremely careful in changing anything about the concurrency support as it has serious implications for stability. I'll take a look at the PR.

**Comment by kennykerr** [comment]
Left a few comments.
