### ISSUE TITLE
CppWinRTOptimized and .g.cpp 

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#461]
I have two cppwinrt projects. One of generates .g.cpp files and other does'nt.  Could'nt figure what build flag triggers this. Finally, may have traced it to 'CppWinRTOptimized'. Is this correct ?

If so, the behaviour is odd - because it breaks all compilation - rather randomly. Should the user component file to include ".g.cpp" ? is this by design ? If so, we can make it consistent irrespective of 'CppWinRTOptimized'

**Comment by kennykerr** [comment]
This is by design and described here:

https://kennykerr.ca/2019/06/07/cppwinrt-optimizing-components/

And here:

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#opt-in-to-uniform-construction-and-direct-implementation-access

**Comment by mediabuff** [comment]
Kenny, thanks for the pointer and I understand the constructs. I was thinking that the presence of 'g.cpp' can be had in both situations - may be a stub. So the compilation doesn't break when even you change the optimization flag -  without retrofitting all files to include (or remove the reference) .
