### ISSUE TITLE
com_ptr equality - consider comparing as IUnknown

### ISSUE THREAD

**Issue by benstevens48** [microsoft/cppwinrt#468]
I notice that equality of com_ptr<T>s does not currently query for IUnknown before comparing the raw pointers for equality. Is there a good reason for this? I struggle to think of a situation where you wouldn't want the cast to IUnknown. Perhaps, if there is a good reason, it might be useful to emit a warning when comparing quality of com_ptr that are not IUnknown as it's an easy mistake to make.

**Comment by kennykerr** [comment]
All of the projected types - derived from `winrt::Windows::Foundation::IUnknown` - already provide identity-based equality. 

It is only `com_ptr` that provides a more low-level pointer value based equality. I consider `com_ptr` a very low-level interop building block and thus I don't want to impose any overhead that may not be needed. Keep in mind that implementing identity-based equality is much more expensive and many scenarios don't need it.

**Comment by benstevens48** [comment]
@kennykerr Ok, I understand the performance reasons, so I'd like to make an alternative suggestion - implement the equivalent of this function to test for identity-based equality - <https://docs.microsoft.com/en-us/cpp/atl/reference/ccomptrbase-class?view=vs-2019#isequalobject>

As well as being slightly more convenient that using `as<IUnknown>`, the existence of such a function would act as a reminder to developers, especially those not too familiar to COM, that it is necessary to query for IUnknown in order to test for identity equality, which is surely what you would want to do most of the time (unless you were sure that this wasn't necessary because of the way you arrived at the com_ptrs, which seems a bit dodgy too me). I think the reasons for such a function being in the ATL library still apply.

**Comment by kennykerr** [comment]
I'm not convinced this needs to be in the base library. Someone would have to know they need it before they'd go looking for such a function. At that point they could just write the trivial function themselves. Again, if you're dealing with the projection then "it just works", but if you're dealing with `com_ptr` you're assumed to be in the "I know what I'm doing" camp. 😉

**Comment by benstevens48** [comment]
OK, fine, it's just I've been using `com_ptr` out of necessity for interacting with WIC in a UWP app whilst being in the "I don't really know what I'm doing camp". I agree that's probably rare, but anyone new to C++/WinRT could easily run into this issue, and I don't think it's very clear in the docs. My point about the existence of the function was that whenever I use a new class I tend to have a quick glance through the docs for it, and if there was a function called `equals_object` or something then that would probably catch my eye (and I assume other developers might do something similar).

**Comment by kennykerr** [comment]
That's a good point. We could probably update the docs for `com_ptr` to point this out and even offer an example of how to perform identity equality.

**Comment by benstevens48** [comment]
That sounds good. I have to admit that if I was trying to write the most general version of such a function, I'd be a bit confused as to whether to query for `::IUnknown` or `Windows::Fundation::IUnknown`.

**Comment by kennykerr** [comment]
Either way. I'd do something like this for maximum portability:

```C++
template <typename T>
inline bool equal(winrt::com_ptr<T> const& left, winrt::com_ptr<T> const& right) noexcept
{
    if (left.get() == right.get())
    {
        return true;
    }

    if (!left || !right)
    {
        return false;
    }

    return winrt::get_abi(left.try_as<winrt::Windows::Foundation::IUnknown>()) == winrt::get_abi(right.try_as<winrt::Windows::Foundation::IUnknown>());
}
```

**Comment by benstevens48** [comment]
Thanks. One minor change I'd make, in case you put this in the docs, is I'd allow the com_ptrs to have different template types (one being a base of the other would be quite common).
