### ISSUE TITLE
Question about 16 bit endian_swap function in base_identity.h

### ISSUE THREAD

**Issue by vbaderks** [microsoft/cppwinrt#472]
Hi,

I am trying to understand the endian_swap function:

https://github.com/microsoft/cppwinrt/blob/0651af8a48ac7939e7bef2bac1b6410d4f189c9b/strings/base_identity.h#L227-L231

Is there a specific reason to first bit mask it and then shift. Should a shift alone not be enough, or are there CPU platforms that require this?

**Comment by kennykerr** [comment]
It's been a long time since this was written. Off the top of my head the masking here isn't required, but was probably done out of consistency with the 32-bit endian_swap.

**Comment by vbaderks** [comment]
Thanks for the update, I was intrigued by the fact that all major C++ compilers (MSVC, clang, GCC) would convert this pattern (in 64bit with O2, for the 32 bit variant) to:

```
unsigned int endian_swap(unsigned int)
        bswap   ecx
        mov     eax, ecx
        ret     0
```

My initial thought was that the additional bit masks were needed to ensure the compiler can recognize the pattern correctly, but after some experiments I see that it can recognize many variants.

Probably a copy the GCC byteswap.h C macros:

```
/* Swap bytes in 16 bit value.  */
#define __bswap_constant_16(x) \
((unsigned short int) ((((x) >> 8) & 0xff) \| (((x) & 0xff) << 8)))

/* Swap bytes in 32 bit value.  */
#define __bswap_constant_32(x) \
((((x) & 0xff000000) >> 24) \| (((x) & 0x00ff0000) >>  8) \|                      \
(((x) & 0x0000ff00) <<  8) \| (((x) & 0x000000ff) << 24))
```
