### ISSUE TITLE
Need a way to mock/hook WinRT runtime class activation for testing

### ISSUE THREAD

**Issue by mithrandir** [microsoft/cppwinrt#476]
Previously, we could override `WinRT_RoGetActivationFactory` to hook RoGetActivationFactory and return mock object instead. With #469 this is not supported. There is new reg-free activation support in that change, like searching dlls implicitly. For example, "Foo.Bar.Baz" is the runtime class name, then it will search "Foo.Bar.dll", "Foo.dll" and probe DllGetActivationFactory(). This only happens when it failed to activate system registered one.

In case of testing for authoring WinRT component, we need mocking mechanism for dependency runtime classes we can use even there is existing runtime class in the system.

**Comment by kennykerr** [comment]
The base library provides [extensibility hooks](https://github.com/microsoft/cppwinrt/blob/master/strings/base_extern.h) (used by WIL) to inject low-level behavior into C++/WinRT. We could add another function for hooking activation and preempt the usual activation workflow.

**Comment by kennykerr** [comment]
https://github.com/microsoft/cppwinrt/pull/477
