### ISSUE TITLE
Provide a conversion from winrt::ABI::<type>* to ::ABI::<type>*

### ISSUE THREAD

**Issue by smj389** [Microsoft/cppwinrt#48]
By declaring your own ABI types you lead to frustrating errors like this one:

rror C2664: 'HRESULT ABI::Microsoft::Graphics::Canvas::ICanvasDeviceStatics::CreateFromDirect3D11Device(ABI::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice *,ABI::Microsoft::Graphics::Canvas::ICanvasDevice **)': cannot convert argument 1 from 'winrt::ABI::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice *' to 'ABI::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice *'

I can work around this but it is inconvenient.

It also makes functions like this harder to use:

HRESULT WINAPI CreateDirect3D11DeviceFromDXGIDevice(
  _In_  IDXGIDevice  *dxgiDevice,
  _Out_ IInspectable **graphicsDevice
);

You have to remember to use ::IInspectable instead of IInspectable because in a winrt class that is winrt::IInspectable. 

BTW it would be nice if the windows SDK included nice wrappers in C++/winrt for functions like this.

**Comment by kennykerr** [comment]
Ideally, we should release the Win2D header for C++/WinRT and then the canvas problem goes away. 

Interop APIs like CreateDirect3D11DeviceFromDXGIDevice are a necessary evil until a native WinRT API is created for DirectX.

**Comment by jjhegedus** [comment]
How does one go about using CreateDirect3D11DeviceFromDXGIDevice?  When I include the <windows.graphics.directx.direct3d11.interop.h> header, I get errors on the uuid attributes...

1>c:\program files (x86)\windows kits\10\include\10.0.14393.0\um\windows.graphics.directx.direct3d11.interop.h(28): error C2337: 'uuid': attribute not found.

I've been struggling to find a way to get a winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice interface though I am able to create a ID3D11Device4 and get a IDXGIDevice interface from it.

Any advice would be greatly appreciated.

**Comment by smj389** [comment]
I copied the signature of CreateDirect3D11DeviceFromDXGIDevice  into a header file like so:
STDAPI CreateDirect3D11DeviceFromDXGIDevice (
	_In_         IDXGIDevice* dxgiDevice,
	_COM_Outptr_ IInspectable** graphicsDevice );

Then if you have winrt::com_ptr<IDXGIDevice>:

	com_ptr<::IInspectable> inspectable { nullptr };
	check_hresult ( CreateDirect3D11DeviceFromDXGIDevice ( get ( dxgidevice_ ), put ( inspectable ) ) );
	auto device_winrt =
		inspectable.as<::ABI::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice> ();

**Comment by jjhegedus** [comment]
Thanks.  That worked perfectly.

**Comment by BenJKuhn** [comment]
Glad to hear that you found a suitable workaround.
