### ISSUE TITLE
array_view<const T> should be constructible from array_view<T>

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#480]
The following code doesn't compile, but should:
```
using namespace winrt;
using namespace winrt::Windows::Foundation;
IInspectable repackage(IPropertyValue pv)
{
  com_array<uint8_t> data;
  pv.GetUInt8Array(data);
  return PropertyValue::CreateUInt8Array(data);
}
```
This breaks because no conversion exists from `array_view<T>` to `array_view<const T>`.

Adding this constructor for `array_view` should fix things.
```
template <typename U, std::enable_if_t<std::is_convertible_v<U*, T*>, int> = 0>
array_view(array_view<U> const& other)
  : array_view(other.data(), other.size())
{}
```

**Comment by oldnewthing** [comment]
Defect in the proposed constructor is that it would allow things like

```cpp
struct Base { int b; };
struct Derived : Base { int d; };

array_view<Base> b{...};
array_view<Derived> v = b; // oops
```

Can be repaired by requiring element type to be the same, minus cv-qualifiers, and for T to be at least as qualified as U.

```cpp
template <typename U, std::enable_if_t<std::is_same_v<std::remove_cv_t<T>, std::remove_cv_t<U>>, int> = 0>
array_view(array_view<U> const& other)
  : array_view(other.data(), other.size())
 // let the constructor validate that T is at least as qualified a U
{}
```

Another point of friction between `array_view<T const>` and `array_view<T>` is the inability to compare them. Can be repaired by allowing `array_view<T>` and `array_view<U>` to be compared, as long as `T` and `U` are comparable.

```cpp
    template <typename T, typename U>
    bool operator==(array_view<T> const& left, array_view<U> const& right) noexcept
    {
        return std::equal(left.begin(), left.end(), right.begin(), right.end());
    }
   // similarly with the other comparisons
```

This takes advantage of the fact that `std::equal` and `std::lexicographical_compare` support comparisons of ranges with different element types.

**Comment by DefaultRyan** [comment]
You read my mind on the conversion issues. :) I agree, the comparison friction would be great to address at the same time.
