### ISSUE TITLE
C3861	'WINRT_GetActivationFactory': identifier not found

### ISSUE THREAD

**Issue by yadavbdev** [microsoft/cppwinrt#484]
I'm getting the following error with the latest version of the C++/WinRT (version 2.0.200116.6) even in a blank app project without any of my changes, is this a known issue and if so is there a workaround this?

Thanks.

**Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'WINRT_GetActivationFactory': identifier not found	BlankApp1	C:\Users\yadavb.REDMOND\source\repos\BlankApp1\BlankApp1\Generated Files\App.xaml.g.hpp	34	
Error	C3861	'WINRT_CanUnloadNow': identifier not found	BlankApp1	C:\Users\yadavb.REDMOND\source\repos\BlankApp1\BlankApp1\Generated Files\App.xaml.g.hpp	39**

**Comment by kennykerr** [comment]
Yes, I'm aware of this. Should have an update out soon.

**Comment by kennykerr** [comment]
Thanks for your patience. This has been fixed as of build 2.0.200117.5.

**Comment by yadavbdev** [comment]
Thank you for this quick turn around.
