### ISSUE TITLE
Visual Studio 2019 version 16.4.3 produces bad code gen

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#486]
Version 16.4.3 of the Visual C++ compiler will in some cases neglect to generate the machine code for certain constructors, leading to crashes inside destructors or assignment operators.

16.4.2 and 16.5 are unaffected. Prefer to use one of those versions if possible.

Alternatively, you can define `__INTELLISENSE__` as a workaround until a fix is available for the C++ compiler. In order for that to work, you need to use a recent version of C++/WinRT (2.0.191202.2 or later).

**Comment by stecrain** [comment]
Glad this is already filed. I hit this issue when iterating a Windows Foundation Collection such as iterating children of a Xaml panel 
```
 for (winrt::UIElement child : Children())
    child.Measure(childConstraint);
```

**Comment by dfields-msft** [comment]
FYI, the compiler issue is tracked here:
https://developercommunity.visualstudio.com/content/problem/886694/access-violation-reading-location-0xffffffffffffff.html

**Comment by kennykerr** [comment]
@stecrain make sure you're using the latest version of C++/WinRT.

**Comment by jlaanstra** [comment]
VS 2019 16.4.4 is now available with a fix for this issue: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.4.4
