### ISSUE TITLE
Project generated by the Windows Console Application (C++/WinRT) fails to build

### ISSUE THREAD

**Issue by zomglol** [microsoft/cppwinrt#487]
Visual Studio 2019 Professional 16.4.3
Windows 10 Pro 1809
Using the C++/WinRT extension v. 2.0.200117.5
Created a new project using the Windows Console Application (C++/WinRT) template, targeting Windows 10 1809. 
Fails to link (both x86/x64 Debug and Release), complaining about missing symbols:
```
1>main.obj : error LNK2001: unresolved external symbol WINRT_IMPL_GetErrorInfo
1>main.obj : error LNK2001: unresolved external symbol WINRT_IMPL_SetErrorInfo
```
Any ideas? I've installed the UWP workload and `C++ (v142) Universal Windows Platform tools`.
Anything else I'm missing?

**Comment by kennykerr** [comment]
Did you install the "Desktop development with C++" workload? You'll need that as well.

**Comment by zomglol** [comment]
Yes, I did. It's what I had installed in the first place. Wanted to try out C++/WinRT, installed the VSIX extension from the gallery, got an error upon project creation that was caused by the missing UWP workload, after adding it using the VS installer I tried creating a sample project again. This time it succeeded, but now it fails during the linking step.

**Comment by kennykerr** [comment]
It could be something wrong with the libs from the SDK you have installed. That's been known to happen. According to the docs, [GetErrorInfo](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-geterrorinfo) and [SetErrorInfo](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-seterrorinfo) are linked via `OleAut32.lib` - you could check that this has been added explicitly.

**Comment by zomglol** [comment]
Checked the linker input in project properties and the only libraries listed there were `kernel32.lib`, `user32.lib` and `WindowsApp.lib` -- adding `OleAut32.lib` fixed the issue. 
Thanks!
