### ISSUE TITLE
Visual Studio 2019 16.4.3 cannot find the cpp/winrt headers with intellisense.

### ISSUE THREAD

**Issue by EternalSaga** [microsoft/cppwinrt#489]
I tried to install vs2019 with the latest update on two windows 10 PC. Then I installed the cpp/winrt through the vsix. Both of the vs2019 IDE cannot find the cpp/winrt headers.
However, default project templates/examples can be compiled successfully.
How can I fix this problem?

**Comment by EternalSaga** [comment]
I tried to use the nuget and installed the cpp/winrt package again, the error still exsited.

**Comment by kennykerr** [comment]
IntelliSense doesn't always work 100% reliably but, given enough time, it does seem to work reasonably well in most cases. If you are having issues please let the C++ team know by creating an issue here:

https://developercommunity.visualstudio.com/spaces/62/index.html
