### ISSUE TITLE
Provide hstring a conversion to std::wstring_view

### ISSUE THREAD

**Issue by smj389** [Microsoft/cppwinrt#49]
winrt::hstring has an operator std::wstring. It would be convenient to have a std::wstring_view now that this has been implemented in VC++.

**Comment by kennykerr** [comment]
Now that std::wstring_view is in the standard we can certainly consider how best to support it. Ideally, we can drop the implicit conversion to std::wstring since that is costly.

**Comment by BrentRe** [comment]
We will add this functionality to the next release.
