### ISSUE TITLE
How can I change the PointerCursorType in cppwinrt?

### ISSUE THREAD

**Issue by lpnxDX** [microsoft/cppwinrt#491]
I want to change the apperance of the PointerCursor . How can I do this with cppwinrt?

The C++/CX style was like that:

```
CoreCursorType uwp_cursor = CoreCursorType::Arrow;
switch (eCursor)
{
case Cursor_Arrow:        uwp_cursor = CoreCursorType::Arrow; break;
case Cursor_TextInput:    uwp_cursor = CoreCursorType::IBeam; break;
case Cursor_Hand:         uwp_cursor = CoreCursorType::Hand; break;
}
corewindow->PointerCursor = ref new CoreCursor(uwp_cursor, 0);

```

**Comment by kennykerr** [comment]
There is a lot of practical information on how to move from C++/CX to C++/WinRT in our [documentation](https://aka.ms/cppwinrt). You could start here:

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx

For help with specific APIs you're better off asking such questions on https://stackoverflow.com/
