### ISSUE TITLE
Perfect forwarding not used correctly in projections

### ISSUE THREAD

**Issue by fghzxm** [microsoft/cppwinrt#501]
I noticed that the implementations of constructors of projection types of delegate types do not seem to use the perfect forwarding pattern correctly, like in ctors of `winrt::Windows::Foundation::EventHandler<T>`:

```
template <typename T>
template <typename L>
EventHandler<T>::EventHandler(L /* should be L&& */ handler) :
    EventHandler(impl::make_delegate<EventHandler<T>>(std::forward<L>(handler)))
{
}

template <typename T>
template <typename F>
EventHandler<T>::EventHandler(F* handler) :
    EventHandler([=](auto&&... args)
    {
        return handler(args... /* should be std::forward<decltype(args)>(args)... */);
    })
{
}
// et al.
```

Am I missing anything or is this a bug?

Version: Microsoft.Windows.CppWinRT v2.0.200117.5
Steps to reproduce:
1.  In Visual Studio, create a new C++/WinRT project.
2.  Build.
3.  Open `Generated Files\winrt\Windows.Foundation.h`, and search for `template <typename T> template <typename L> EventHandler<T>::EventHandler(L handler)`.  Should be able to find the constructors defined as above.

**Comment by kennykerr** [comment]
Thanks, I'll take a look. There isn't any particular reason for following one forwarding pattern or another in the code as it stands. The only issue is that the code is written to optimize code gen, so any change to make it "more correct" would need to ensure that code gen and in particular memory layout is unaffected.

**Comment by kennykerr** [comment]
Closing old issue as not urgent. Feel free to contribute a fix if so desired.
