### ISSUE TITLE
Codegen bug with delegate param of array of custom struct

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#509]
repro IDL:
    struct BlittableStruct
    {
        Int32 i32;
    };
    delegate BlittableStruct[] ArrayParams_BlittableStruct_Del(BlittableStruct[] a, ref BlittableStruct[] b, out BlittableStruct[] c);

resulting projection:
    inline auto ArrayParams_BlittableStruct_Del::operator()(array_view<TestComp::BlittableStruct const> a, array_view<TestComp::BlittableStruct> b, com_array<TestComp::BlittableStruct>& c) const
    {
        uint32_t result_impl_size{};
        struct struct_TestComp_BlittableStruct* result{}; // <-- bug
        check_hresult((*(impl::abi_t<ArrayParams_BlittableStruct_Del>**)this)->Invoke(a.size(), get_abi(a), b.size(), put_abi(b), impl::put_size_abi(c), put_abi(c), &result_impl_size, &result));
        return com_array<TestComp::BlittableStruct>{ result, result_impl_size, take_ownership_from_abi };
    }

and compile error:
2>D:\git\cswinrt\TestComp\Generated Files\winrt\TestComp.h(2069,192): error C2664: 'int32_t winrt::impl::abi<winrt::TestComp::ArrayParams_BlittableStruct_Del,void>::type::Invoke(uint32_t,winrt::impl::struct_TestComp_BlittableStruct *,uint32_t,winrt::impl::struct_TestComp_BlittableStruct *,uint32_t *,winrt::impl::struct_TestComp_BlittableStruct **,uint32_t *,winrt::impl::struct_TestComp_BlittableStruct **) noexcept': cannot convert argument 8 from 'winrt::TestComp::ArrayParams_BlittableStruct_Del::()::struct_TestComp_BlittableStruct **' to 'winrt::impl::struct_TestComp_BlittableStruct **' (compiling source file Class.cpp)
2>D:\git\cswinrt\TestComp\Generated Files\winrt\TestComp.h(2069,185): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast (compiling source file Class.cpp)

appears that this:
        struct struct_TestComp_BlittableStruct* result{};
should be this:
        struct winrt::impl::struct_TestComp_BlittableStruct* result{};

**Comment by kennykerr** [comment]
Good catch - so glad we're fleshing out our WinRT testing. 😉
