### ISSUE TITLE
Question about Application::Start

### ISSUE THREAD

**Issue by Firelark** [Microsoft/cppwinrt#51]
Hello, this is not an issue, just a question. I've just started to playing around with cppwinrt and I started with the sample project "XamlCode".

I'm a little bit confused about the following code found in `wWinMain`:
```
Application::Start(
[](auto &&) 
{
make<App>();
});
```
This lambda seems to create an instance of `App` but it is not returning it to the caller. 

My Question: How is the function `OnLaunched` and other functions like `OnWindowsCreated` and `OnActivated` getting called?

I'm just curious.

Thanks for the cppwinrt initiative, it is really needed in my opinion.

**Comment by smj389** [comment]
Windows.UI.Xaml.Application takes a delegate as its argument. The Lambda is converted to that. In the callback you create your app object.

**Comment by Firelark** [comment]
Yes, but the App object doesn't seem to go anywhere, from the looks of it the object should die just as soon as it returns from `make<App>();` as there is nothing to keep it alive. Unless it is somehow assigned to some global internal variable inside the `make<App>` funktion? 

I reckon that there should only be one App object within the application and so I'm figuring that it might be implemented in a singleton pattern with a static data member somewhere?

I just find the
```
Application::Start(
[](auto &&) 
{
make<App>();
});
```
to be a little unintuitive and confusing. Perhaps have a differently named function to make and register the App objekt, maybe something like `register_new<App>()` or something similar instead of `make<App>()`. 

Just my thoughts, and I might have misunderstood things.

**Comment by smj389** [comment]
When you create a Windows UI XAML Application, the constructor does not return. Instead it ends up in CoreDispatcher::ProcessEvents. What I'm saying is that make<App> will not return (until the App closes.)

**Comment by Firelark** [comment]
Aha that makes a lot more sense! Thanks smj389 for clarifying that. 

If I could make a suggestion, maybe have a function named `run<App>()` or something like that would be more clear than `make<App>()`.

**Comment by kennykerr** [comment]
The XAML startup model is a bit odd because if you only look at WinMain it seems as if the XAML framework never gets a reference to your App class, but keep in mind that your App class derives from the XAML Application class. This causes the Application constructor to run, which is the way that the XAML framework discovers that the app is ready for launch.

**Comment by Firelark** [comment]
Thanks for the information and for the good work on cppwinrt!
