### ISSUE TITLE
C++/WinRT Wizard for XAML Designer

### ISSUE THREAD

**Issue by dr-eck** [microsoft/cppwinrt#514]
I'd really, really like to move from MFC to C++/WinRT for desktop app development, but I'm not a full time developer.  I don't want to learn how to develop and maintain IDL code just to access a property of an element or write an event handler.  With MFC, there's a wizard for the View Designer that takes care of the details; all I have to do is flesh out the function stub that is generated in the file I specify.  Please add this to the XAML Designer so I can modernize my code without learning IDL.

**Comment by kennykerr** [comment]
Hey, thanks for the suggestion! Those were the days. 😉 

Unfortunately, we don't work on either Xaml or Visual Studio. You might want to suggest this on either of their issues pages:

Xaml: https://github.com/microsoft/microsoft-ui-xaml/
Visual Studio: https://developercommunity.visualstudio.com/spaces/62/index.html

**Comment by dr-eck** [comment]
Kenny,  Thanks for responding and for the suggestions; I'm pursuing them.  I look forward to the day when I can easily use C++/WinRT and kiss MFC goodbye.
