### ISSUE TITLE
init_apartment - option not to throw

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#517]
There are situations in which a thread is already CoInitialize'd - not under app control, say a framework library.

init_apartment should have an option to ignore - rather than throw - already initialized thread.

**Comment by kennykerr** [comment]
The `init_apartment` function simply calls [CoInitializeEx](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex) - you can call that functions directly to avoid the exception.
