### ISSUE TITLE
Declare byte access in idl

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#526]
I am trying to define the following in cppwinrt project. Get compilation errors. Tried turning off winrt flag as well

```
   [uuid(7CC000DB-5EE2-4EAF-909B-40BB4D5F2807), version(COMPONENT_VERSION)]
    interface IMetaData : IInspectable
    {
        HRESULT SetMetaData[[in] UINT32 __metaDataSize,[in][size_is(__pixelsSize)] BYTE* metaData);
    };
```

Standard Windows inbox example: winrt/windows.graphics.imaging.idl 
```
interface IBitmapEncoder : IInspectable
{
   HRESULT SetPixelData(..... [range(0x00000000, 0x7FFFFFFF)] [in] UINT32 __pixelsSize, [in] [size_is(__pixelsSize)] BYTE* pixels);
}
```

**Comment by kennykerr** [comment]
Why not use the modern IDL syntax? The method would be something like this:

```
void SetMetaData(UInt8[] value);
```

More [examples here](https://github.com/microsoft/TestWinRT/blob/master/TestComponent/TestComponent.idl)
