### ISSUE TITLE
 no GUID has been associated with this object

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#528]
Although I have attributed an interface in IDL with uuid, cppwinrt does'nt generate that attribute in the header file. Thus I can't query an interface using GUID.

Attached a zip file. Modified the project generated by cppwrint class lib template.
[CppwinrtComponentLib.zip](https://github.com/microsoft/cppwinrt/files/4199618/CppwinrtComponentLib.zip)

**Comment by kennykerr** [comment]
`__uuidof` is a Visual C++ language extension that C++/WinRT knows nothing about. You can use `winrt::guid_of` to get the guid for a given type in C++/WinRT.
