### ISSUE TITLE
Cannot compile with clang-cl when using #include <experimental/coroutine>

### ISSUE THREAD

**Issue by christophpurrer** [microsoft/cppwinrt#531]
- Our project or a dependency as [folly](https://github.com/facebook/folly/search?q=%23include+%3Cexperimental%2Fcoroutine%3E&unscoped_q=%23include+%3Cexperimental%2Fcoroutine%3E) might ```#include <experimental/coroutine>```
- We can't compile the program anymore due to ```redefinition of 'coroutine_handle<void>'```

## Repro:
- Create 'Windows Console Application (C++/WinRT)' in VS 2019
- Change Platform Toolset to 'LLVM (clang-cl)'
- Either change 'C++ Language Standard' to 'Preview - Features from the Latest C++ Working Draft (/std:c++latest)' OR
- Keep 'C++ Language Standard' to 'ISO C++17 Standard (/std:c++17)'' and add ```-Xclang -fcoroutines-ts``` to Additional Options in C++ \ All Options

-> Compile and run the program: Observe that it works

- Now add #include <experimental/coroutine> to main.cpp

-> Doesn't compile anymore

**Comment by kennykerr** [comment]
The trouble is that the coroutine ABI is different between Visual C++ and Clang. As a consequence, the <experimental/coroutine> header from Visual C++ is not compatible with Clang. That's why C++/WinRT attempts to smooth things over by providing an implementation that is compatible with Clang in such cases.

**Comment by christophpurrer** [comment]
Okay.
I have diffed C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include\experimental\resumable with the bash.h generated from cppwinrt.exe and it seems they are indeed different.
However, I don't have the technical expertise to spot the specific details ;-)
They are also different in 14.24.28314

It seems this problem is related to https://github.com/microsoft/STL/issues/100 and it seems it won't be solved as C++20 has ```#include <coroutine>```

Two entities carrying a different implementation can't bear the same name.
I am using a preprocessor statement now to fix that in our code base:

```
#pragma push_macro("experimental_compat")
#define experimental experimental_compat
// Include C++/WinRT headers, e.g.:
// #include <Windows.UI.Xaml.Hosting.DesktopWindowXamlSource.h>
// #include <winrt/Windows.UI.Xaml.Hosting.h>
#undef experimental
#pragma pop_macro("experimental_compat")
```
Now the program links correctly

-> Would this be something we should integrate into this project?

**Comment by kennykerr** [comment]
Given that <coroutine> is coming and will hopefully have compatibility with both compilers, I should probably remove the Clang version from the base header to make it easier for projects to include the support they need.

**Comment by christophpurrer** [comment]
This issue was only apparent when also including folly and got eventually fixed upstream > https://github.com/facebook/folly/commit/cbdf3df78086c1aef2b9d74e826f960824c043b6#diff-4fc4184ad9f9ddf4ceb5e792384c7a4d

As my particular scenario was to use react-native-windows https://github.com/microsoft/react-native-windows with Clang I still need to provide an experimental awaitable future support so I am adding my fix just for reference > https://gist.github.com/christophpurrer/442614beda29b46b9761b57326927a60
