### ISSUE TITLE
Failing to build HelloWinUICppWinRT

### ISSUE THREAD

**Issue by pavelpokutnev** [microsoft/cppwinrt#532]
Just starting to evaluate the C++/WinRT. I created the HelloWinUICppWinRT as described [here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started). I installed the "C++ (v142) Universal Windows Platfrom tools", "C++/WinRT Visual Studio Extension (VSIX)" and the corresponding NuGet package. But the blank new project doesn't compile/link with following error messages:

``
1>main.obj : error LNK2019: unresolved external symbol _WINRT_IMPL_SetErrorInfo@8 referenced in function "private: static int __stdcall winrt::hresult_error::fallback_RoOriginateLanguageException(int,void *,void *)" (?fallback_RoOriginateLanguageException@hresult_error@winrt@@CGHHPAX0@Z)
1>main.obj : error LNK2019: unresolved external symbol _WINRT_IMPL_GetErrorInfo@8 referenced in function "public: __thiscall winrt::hresult_error::hresult_error(struct winrt::hresult,struct winrt::take_ownership_from_abi_t)" (??0hresult_error@winrt@@QAE@Uhresult@1@Utake_ownership_from_abi_t@1@@Z)
``

I'm on Visual Studio 2019, Windows 10 1809.

It seems that at least for the console application it is enough to add "ole32.lib;oleaut32.lib" as per #520. But for XAML app I'm still getting:

``
>XamlTypeInfo.g.obj : error LNK2001: unresolved external symbol _WINRT_IMPL_LoadLibraryW@4
1>XamlMetaDataProvider.obj : error LNK2001: unresolved external symbol _WINRT_IMPL_LoadLibraryW@4
1>App.obj : error LNK2001: unresolved external symbol _WINRT_IMPL_LoadLibraryW@4
1>MainPage.obj : error LNK2001: unresolved external symbol _WINRT_IMPL_LoadLibraryW@4
1>module.g.obj : error LNK2001: unresolved external symbol _WINRT_IMPL_LoadLibraryW@4
1>XamlTypeInfo.Impl.g.obj : error LNK2001: unresolved external symbol _WINRT_IMPL_LoadLibraryW@4
1
``

**Comment by pavelpokutnev** [comment]
OK, it looks I can solve it by adding "ole32.lib;oleaut32.lib;Kernel32.lib" to the AdditionalDependencies.

**Comment by kennykerr** [comment]
Glad you found a workaround. Libs are a bit of an issue today. #488

**Comment by JX75** [comment]
I had exactly the same issue today with an empty, VS Studio generated C++/WinRT console project (also desktop project).
Visual Studio Professional 2022 17.8.6, Windows 10 22H2.
Adding  "ole32.lib;oleaut32.lib;Kernel32.lib" to the AdditionalDependencies also fixes the error.
