### ISSUE TITLE
Propagate any thrown C++ exception through WinRT error handling

### ISSUE THREAD

**Issue by jkoritzinsky** [microsoft/cppwinrt#533]
Today in C++/WinRT, any application-type exceptions that aren't one of the known exception types get lost at the ABI boundary in `to_hresult()`. Additionally, even if the exception is a known type (such as a user-derived type of `std::exception`) any information other than the message is lost when translating for the ABI layer.

The WinRT ABI supports passing around a (wrapped) language-projection-specific exception object that can be restored and re-thrown once the code re-enters the C++/WinRT projection. With the `std::exception_ptr` type and the related functions, the language projection can preserve exceptions transparently across the ABI boundary.

The .NET projections use this feature to preserve .NET Exceptions across the ABI boundary. They also support preserving other projection's language exceptions through the .NET projection surface so the exceptions will be correctly handled even if the .NET code doesn't catch them.

**Comment by kennykerr** [comment]
The trouble is ABI-stability. The C++ exception value may not have the same representation on either side of the ABI and there's no guarantee that the same version of C++/WinRT let alone the C++ standard library (including all preprocessor and build state) match to make this work reliably.

**Comment by JaiganeshKumaran** [comment]
Here is a way around the ABI problem. Use the pointer value of typeid(some_cpp_type). This should be unique for the particular ABI (or project).
