### ISSUE TITLE
Generic interface defition in IDL?

### ISSUE THREAD

**Issue by axodox** [microsoft/cppwinrt#534]
After hours of searching I could not find how I could define generic interfaces in IDL. I have seen plenty examles of using them, but not a single one defining them. If I would like to create a custom interface with a type argument in IDL, how I could do it?

**Comment by kennykerr** [comment]
WinRT does not support custom generic interface definitions.

**Comment by axodox** [comment]
So where are the current generic types defined? Eg. IMap<>

**Comment by axodox** [comment]
Anyway thanks for the quick answer

**Comment by kennykerr** [comment]
They're not defined in IDL at all. They are defined in [IL](https://en.wikipedia.org/wiki/Common_Intermediate_Language) as part of bootstrapping WinRT inside the OS build pipeline.

**Comment by axodox** [comment]
Is there a plan to support them at some point? It would be useful.

**Comment by kennykerr** [comment]
No plans, but we've talked about supporting this in future - it would certainly be useful.

**Comment by axodox** [comment]
Great to hear. It is shaping up to be a really nice framework! Thanks again.
