### ISSUE TITLE
Are ppl tasks still suppose to work in code based on cppwinrt?

### ISSUE THREAD

**Issue by rhenninger** [Microsoft/cppwinrt#54]
Simply including "winrt/ppl.h" in code causes compile errors.  The errors come from its including <mutex> in its header. In fact, simply including <mutex> alone causes the same compile errors.  <mutex> doesn't fail in non-winrt/xxx projects.

While I notice that none of this site's samples use ppl, the doc implies that ppl tasks are supported with certain caveats.  I am happy to keep experimenting with coroutines, so this isn't stopping me on anything.  Still, I am wondering whether the doc is stale or there is a conflict in current cppwinrt and ppl that prevents compiling.

Could we have a little more doc on things like fire_and_forget and adapter?  Though I've mimicked the samples and stuff works, I'd rather not have to unravel the templates to infer proper usage.

**Comment by alessiot89** [comment]
I had similar issues caused by including "winrt/ppl.h", especially I got many conflict with the std::mutex header. I solved this issues including it before any other winrt headers.

**Comment by rhenninger** [comment]
@alessiot89 Thanks.  I put winrt/ppl.h as the first include in my pch.h file and all symptoms went away.  Still, this kind of delicacy in programming caveats means that cppwinrt still has some glitches that need resolving.  I'll leave this issue open so it gets looked at more deeply.

**Comment by kennykerr** [comment]
C++/WinRT is designed to work with C++ coroutines for all your async consumption and production needs. You can [learn more about that here](https://www.youtube.com/watch?v=v0SjumbIips).

Please don’t use PPL. PPL itself doesn’t work well and our C++/WinRT adapters for PPL have a few drawbacks. The PPL support was only meant to help one of our internal customers who could not immediately upgrade to the C++ compiler that supports coroutines. While Visual C++ will continue to support PPL for some time, we do not encourage its use for new code and will likely remove the PPL header from a future update of C++/WinRT.

**Comment by rhenninger** [comment]
@kennykerr Thanks for the heads up on PPL and cppwinrt, Kenny.  I am trying coroutines out on a new project, so I am fine using those in lieu of PPL.  If ppl tasks are not to be used, how do we house functions containing co_await? I've spotted devices like adapters, auto_revoke, IAsyncOperation<>, fire_and_forget in the samples.  What are you recommending?

**Comment by kennykerr** [comment]
You can use any suitable coroutine type. Visual C++ ships with std::future that will work in many cases. You can also use C++/WinRT’s implementation of IAsyncAction as the coroutine type or fire_and_forget if you really don’t care about waiting for its completion. Here's [an example of fire_and_forget](https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/Samples/XamlCode/App.cpp). The other WinRT [async interfaces are also supported](https://github.com/Microsoft/cppwinrt/blob/master/10.0.14393.0/Samples/JustCoroutines/Main.cpp) by C++/WinRT as coroutine types but they're generic interfaces and they don't currently "just work" due to limitations in VC 2015 that we're addressing shortly for VC 2017. You currently need to manually specialize the generic interfaces, which is rather difficult. This will "just work" in a future update without requiring you to do anything and the compiler will take care of creating the necessary specializations.

**Comment by rhenninger** [comment]
@kennykerr Thanks for the clarifications and suggestions.  I can work within those parameters with fire_and_forget and IAsync... with ABI templates for now.  <future>, however, also fails for the same reason PPL fails: the inclusion of <mutex>. For now, if I wanted, I could place mutex in pch.h ahead of the winrt includes. However, I presume that long term you want any and all parts of the STL to play nice with cppwinrt.  Where can I read up on the adapter, auto_revoke and fire_and_forget keyword/structs?

**Comment by rhenninger** [comment]
@kennykerr On a related topic, are other features in the concurrency namespace like concurrent_vector also off-limits long term?  These seem to compile ok.

**Comment by kennykerr** [comment]
The compilation issues are a separate matter to whether or not you should use these libraries. If there is a specific order of inclusion with STL or PPL that is causing trouble, please let us know and we can look into that. Ideally with simple repro steps. Thanks!

**Comment by rhenninger** [comment]
I'll see if I can get a simple stand-alone example.  Some classes trigger the below message others don't.
Here is the message

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2248	'std::_Mutex_base::_Mymtx': cannot access private member declared in class 'std::_Mutex_base' (compiling source file UiCompositionMain.cpp)	UiCompositionApp	c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex	565

**Comment by rhenninger** [comment]
It seems to be some kind of interaction caused when using "using namespace winrt" before including the STL's mutex module. I've included a bare bones UWP app with define/undef macro to turn the error off and on.  "pch.h is empty of includes. The working version explicitly uses winrt:: as a prefix for all usings and fully qualified class references bypassing the "using namespace winrt" statement used in the failing version.  Hope this gives you enough to go on.
 
[MutexTest.zip](https://github.com/Microsoft/cppwinrt/files/655806/MutexTest.zip)

**Comment by walbourn** [comment]
As a general C++ best practice, you shouldn't put ``using namespace`` statements before including headers or in headers.

**Comment by kennykerr** [comment]
Chuck is exactly right. That's a recipe for problems and it would take a lot of convincing to get the Visual C++ team to harden their headers to somehow defend against this.

**Comment by rhenninger** [comment]
@walbourn @kennykerr  Yeah, my fingers hurt after I type a "using namespace" statement in a header. I have always used fully qualified names in headers before.  Somewhere in my reading on moderncpp/cppwinrt I thought I saw that the "using namespace winrt;" statement was needed to avoid potential confusion with the original namespaces of the same classes.  I am relieved that normal best practices in header writing actually does coincide with what you are recommending for correct usage of cppwinrt.

**Comment by rhenninger** [comment]
That the "using namespace winrt;" statement in an insert was a red herring - valid point about headers, but that masks the real problem about include and using interactions.
I can cause the problem directly in the cppwinrt samples.  Take Blocks in "app.cpp", for example: just put "#include <mutex>" right after the "using namespace winrt" statement in line 3 to make it happen.  Of course, placing the include statement before the using makes the compile errors go away, but that the order matters is a little concerning for those who would try to use STL futures. 
I'll leave this issue open as a marker if you care to deal with making STL usage a little more robust. @kennykerr  Feel free to close it, however, if you consider this too minor to deal with for now.

**Comment by kennykerr** [comment]
The two are related and this practice is just as detrimental in source files as it is in headers. To quote item 59 from the [C++ Coding Standards](http://a.co/j6AAWvh):

> Namespace **using**s are for your convenience, not for you to inflict on others: Never write a **using** declaration or a **using** directive before an **#include** directive. 


I won’t repeat all the arguments here. The book does a good job of this.

**Comment by rhenninger** [comment]
@kennykerr Good to know.  Thanks for bearing with me on this -  just trying to offer feedback as I encounter stumbling blocks: doc vagueness or code.  I am enjoying the journey so far.  Thanks for creating what is so far a joy to use - it feels so much better than C++/CX.

**Comment by kennykerr** [comment]
We very much appreciate the feedback!

**Comment by mediabuff** [comment]
Hi all  - Could someone clarifiy on the guidance about "Please don’t use PPL" and use co_routines with Async winrt stuff. This fine for Windows  components that rely on Winrt services.

What about multi-platforms shared c++ libraries - that are linked into Windows projects ? What task library to use for co_routine support ?
