### ISSUE TITLE
Using WinRT using plain C

### ISSUE THREAD

**Issue by HiImJulien** [microsoft/cppwinrt#540]
Hey there!

I am working on a [small library ](https://github.com/HiImJulien/foundation), which is similar to GLFW, for myself. It is also written in C. I am looking to extend its capabilities to create WinRT windows.

My question is naturally: can WinRT application be developed using plain C (perhaps using COM)?
If so, where could I start? Can anyone point me to some examples?

**Comment by kennykerr** [comment]
It's certainly possible, but highly impractical. API calls are really COM interface calls that are just collections of virtual functions. You could create a struct in C with a bunch of function pointers or simply offset the address of the function pointers, but it is very tedious. A simpler approach might be to use C++/WinRT to make the API calls and then wrap that behind a C-style API that you can call from your C code.
