### ISSUE TITLE
Error C2065: 'get_activation_factory': undeclared identifier on MSVC + /permissive-

### ISSUE THREAD

**Issue by QuellaZhang** [microsoft/cppwinrt#548]
Hi, we found error C2065 when build CppWinRT latest code under /permissive- mode on income released MSVC, can you help look?

Repro step:
1. Open VS2019 x86 tools command
2. git clone https://github.com/microsoft/cppwinrt cppwinrt
3. cd cppwinrt
4. F:\CppWinRT\src\build_test_all.cmd x86 Release

Error:
f:\CppWinRT\src\strings\base_implements.h(1220,43): error C2065: 'get_activation_factory': undeclared identifier
f:\CppWinRT\src\strings\base_implements.h(1220,43): error C3861: 'get_activation_factory': identifier not found

**Comment by kennykerr** [comment]
Please email me with the (internal) location of this compiler build so I can look into this.
