### ISSUE TITLE
Array delay initialization

### ISSUE THREAD

**Issue by fghzxm** [microsoft/cppwinrt#549]
The docs page on [porting CX code to C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx#how-the-default-constructor-affects-collections) states that:

> There's no shorthand [in C++/WinRT] for creating an array of empty references. You have to repeat `nullptr` for each element in the array.

That is, to create a `TextBox boxes[100]` of delayed-initialized objects, I have to write:

```code-cpp
TextBox boxes[100]
{
    nullptr, nullptr, nullptr, ...
    ...,
    ..., nullptr, nullptr, nullptr // 100 `nullptr's in total
};
```

There is, however, [a TMP way to do this](/MicrosoftDocs/windows-uwp/pull/2264).  I originally suggested the docs page may include that solution, but the page author suggests that, due to the complexity of my code, I instead either

1. just post that code on my gist, or
2. submit feedback on Microsoft Q&A.

I decided that I'd better bring that solution here for you to review.  Does that use case of delayed initialization warrant support from C++/WinRT?  If so, where in the project can I add the function?

**Comment by kennykerr** [comment]
Thanks for the suggestion. While interesting, I'm not sure how valuable this would be for developers in general as there are a variety of ways to solve this problem and I don't believe it comes up very often in WinRT API usage.
