### ISSUE TITLE
Consider enabling symbol baselining for vpack publishing

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#553]
Instead of a manual process to update good.txt, the symbol indexing can be moved from the release pipeline to the build pipeline and the vpack publish command can be configured to update the symbol baselines.  This will probably require some back and forth with SMEs to deal with the non-realtime symbol indexing prerequisite, etc.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
