### ISSUE TITLE
Crash in await_suspend

### ISSUE THREAD

**Issue by Zingam** [Microsoft/cppwinrt#56]
While trying the samples I experienced a crashed on several occasions StorageFile file = await picker.PickSingleFileAsync(); I am attaching a couple of screenshots.

![capture1](https://cloud.githubusercontent.com/assets/3337419/21290534/b2db135e-c4c6-11e6-8866-4f3a16144e55.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3337419/21290533/b2dae7bc-c4c6-11e6-9797-55c94ca77d37.PNG)

**Comment by Firelark** [comment]
I have experienced this as well, although it only happened occasionally.

**Comment by kennykerr** [comment]
Which version of Visual Studio are you using? The Visual Studio 2017 RC fixes a number of coroutine bugs.

**Comment by Zingam** [comment]
Visual Studio 2015 Update 3

**Comment by Zingam** [comment]
OK. I'll give it a try to this and to the other issues I have but probably after the holidays.

**Comment by kennykerr** [comment]
There are a number of features and fixes we need to make for C++/WinRT that will only work with VS 2017 as the new C++ compiler fixes various bugs and adds important language features that are missing in VS 2015. So yes those new features will only be available for VS 2017. You will still be able to use the existing version of C++/WinRT with VS 2015 but without those fixes and features. 

C++ coroutines specifically is a feature provided by the C++ compiler. While it is supported (by Visual Studio) in VS 2015 Update 3, it is far more reliable in VS 2017 as a number of important bug fixes are only available with VS 2017.

**Comment by Zingam** [comment]
I couldn't wait until the end of the holidays. I borrowed a laptop and installed VS2017 RC. I loaded the same sample Video and I still can crash it. A little bit harder, easier via the debugger and somewhat harder when I run it via the Start Menu.
What I do might be a strain on the application Lifecycle but I believe no matter what it should never crash.
I run it then I cancel the picker. Then I repeat until it crashes. When compiled with VS2015 Update 3 on another machine the app would crash on startup (when showing the picker). Now it crashes when I cancel the picker but in the same place I think.
So if I understand correctly the problem is in WinRT itself? Should I report this somewhere?

![capture](https://cloud.githubusercontent.com/assets/3337419/21576919/37acd5fa-cf4d-11e6-8b4f-0726799595d1.PNG)

**Comment by Zingam** [comment]
To summarize: previously (VS2015) the app would crash randomly at start-up when calling the file picker. now (VS2017) when I repeatedly run the app and cancel the picker it will eventually crash when calling the file picker.

**Comment by kennykerr** [comment]
The coroutine crash ended up being a COM marshaling bug. We've fixed that and will have an update out soon.

**Comment by kennykerr** [comment]
We just published an update that fixes the file picker crash.
