### ISSUE TITLE
Cannot use clang-tidy in combination with winrt/base.h

### ISSUE THREAD

**Issue by vbaderks** [microsoft/cppwinrt#566]
The latest versions of Visual Studio 2019 have support for clang-tidy static analysis. The problem is that clang-tidy relies on clang to compile the source for the actual analysis and the generated winrt/base.h cannot be compiled with clang due to a call to co_await():

```
    template <typename T>
    auto get_awaiter(T&& value) noexcept -> decltype(static_cast<T&&>(value).operator co_await())
    {
        return static_cast<T&&>(value).operator co_await();
    }

    template <typename T>
    auto get_awaiter(T&& value) noexcept -> decltype(operator co_await(static_cast<T&&>(value)))
    {
        return operator co_await(static_cast<T&&>(value));
    }

winrt/base.h(8200,87): error G58EA42A4: unknown type name 'co_await' [clang-diagnostic-error]
winrt/base.h(8206,63): error G58EA42A4: unknown type name 'co_await' [clang-diagnostic-error]
```
As this causes clang-tidy to generate a "clang-diagnostic-error" error and not just a warning the MSBuild build of the project will fail. Using clang-tidy with WinRT is thus not possible at the moment.

Used Visual Studio version: 2019 16.6.0 Preview 1.0
Used Nuget WinRT: 2.0.200316.3

Workaround:
Wrapping these 2 functions in #ifndef \_\_clang\_\_ / #endif (as is done in other places in base.h) solves the problem for clang-tidy in my case. As base.h can be regenerated and is often done, this is not a good long-term solution.

**Comment by kennykerr** [comment]
Thanks for catch this. They need to be wrapped with `#ifdef __cpp_coroutines`.

**Comment by asklar** [comment]
@kennykerr any idea when this might be addressed? is this just a matter of putting the ifndef? 
I assume that workaround is only for code that doesn't use coroutines outside of cppwinrt's own usage?

**Comment by kennykerr** [comment]
Sorry for the delay. It looks like C++20 settled on different feature macro names, which has complicated adding a fix here.

**Comment by asklar** [comment]
@kennykerr  yeah you should be able to turn on clang analysis if you open a C++ proj in VS, go to properties, Code Analysis at the bottom and turn on clang and run code analysis on build, then close the properties window and either build or go to the build menu and click run code analysis

![image](https://user-images.githubusercontent.com/22989529/88968127-b2b4a580-d263-11ea-908d-9a79a8a56871.png)
![image](https://user-images.githubusercontent.com/22989529/88968184-d11aa100-d263-11ea-9e1b-5acacd97df16.png)

**Comment by clarkezone** [comment]
This also appears to break Clang 11 compatibility with C++/WinRT hope that a fix can be prioritized.

**Comment by kennykerr** [comment]
I can't reproduce this on the 16.8 preview 3. We've also made improvements to coroutine conformance, so that may also have helped.

**Comment by vbaderks** [comment]
The problem is still there:
Used Visual Studio version: 2019 16.8.0 Preview 3.2
Used Nuget WinRT: 2.0.201008.2

To reproduce, clone: https://github.com/team-charls/jpegls-wic-codec and enable Clang-Tidy for the jpegls-wic-codec project and build. 

Clang-Tidy will report the following errors:
```
Generated Files\winrt/base.h(8280,9): error GEF7559A7: no matching function for call to 'submit_threadpool_callback' [clang-diagnostic-error]
Generated Files\winrt/base.h(8314,78): error G58EA42A4: unknown type name 'co_await' [clang-diagnostic-error]
Generated Files\winrt/base.h(8317,60): error G58EA42A4: unknown type name 'co_await' [clang-diagnostic-error]
Generated Files\winrt/base.h(8407,53): error G58EA42A4: unknown type name 'co_await' [clang-diagnostic-error]
Generated Files\winrt/base.h(8411,29): error G58EA42A4: unknown type name 'co_await' [clang-diagnostic-error]
```

**Comment by clarkezone** [comment]
@vbaderks you didn't reopen the issue

**Comment by asklar** [comment]
I think only repo admins can reopen. CC @kennykerr

**Comment by vbaderks** [comment]
Hi @clarkezone : I cannot reopen, normally the owner gets a notification. I normally wait before opening the same issue twice.

**Comment by kennykerr** [comment]
Thanks for the repro - I'll take a look when I get a moment.

**Comment by clarkezone** [comment]
@kennykerr wondering if you've had a chance to look at this?

**Comment by kennykerr** [comment]
Looking now. It seems Clang doesn't yet honor the C++20 coroutine feature macros leading to some trouble.

https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros

**Comment by kennykerr** [comment]
Here's a PR that fixes these issues: https://github.com/microsoft/cppwinrt/pull/779
