### ISSUE TITLE
Add an item template for a custom xaml control.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#569]
Custom xaml controls require a few things to ensure they work correctly across languages. Template would prevent common mistakes.

Requires #568

**Comment by jevansaks** [comment]
I think the templates would come from @danzil and @fabiant3-zz

**Comment by danzil** [comment]
For WinUI we already have one for .Net and we will add one for C++/WinRT, too, in the WinUI VSIX (not the C++/WinRT VSIX). WinUI feature requests are tracked at https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by kennykerr** [comment]
@danzil Is there some overlap with the two VSIX? Perhaps we should trim down the C++/WinRT VSIX if so.

**Comment by danzil** [comment]
Yes, there is overlap, but the C++/WinRT VSIX targets Windows.UI.Xaml (OS Xaml) while the WinUI one targets Microsoft.UI.Xaml (WinUI 3.0) and it's not yet released (it's an Alpha).

**Comment by kennykerr** [comment]
OK thanks. Either way we don't have the resources to expand the C++/WinRT templates so I'd like to focus any new investment on the WinUI side.
