### ISSUE TITLE
C++ WinRT debug visualizer breaks visualizing some WRL RuntimeClass cases

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#571]
VS ships with `winrt.natvis` that supports `Microsoft::WRL::RuntimeClass`. This cleans up the class hierarchy and displays the object refcount in the details.

When the C++ WinRT vsix is installed it tries to visualize `RuntimeClass` instances that it thinks are WinRT types. When it is unable to, it blocks VS from using the visualizer in `winrt.natvis` breaking visualization.

I hope there is a way for your visualizer to say "not mine" and let VS handle it.

The workaround is to uninstall the vsix.

I can share a link to a project that demos this if that is useful.

**Comment by DefaultRyan** [comment]
Looks like the visualizer is "helpfully" taking over the visualization for any object that inherits from `::IInspectable`, which will supersede `Microsoft::WRL::RuntimeClass`.

I think we should be less eager to take over all IInspectable visualizations. If a dev has an ABI IInspectable and wants to use the cppwinrt visualizer, I *think* they can do that in the watch window by simply casting it into `winrt::Windows::Foundation::IInspectable`.

**Comment by kennykerr** [comment]
Unfortunately, the team does not have the capacity or skills to deal with bugs outside of the core C++/WinRT library and compiler. Feel free to keep the conversation going and contribute a PR as needed.
