### ISSUE TITLE
Running code analysis fails

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/cppwinrt#573]
1) Install the C++/WinRT extension from Microsoft
2) Create a new blank C++/WinRT "MyProject"
3) Open the context menu of the project and select
   Analyze and Code Cleanup > Run Code analysis on MyProject

Compilation fails with
MyProject\Generated Files\XamlTypeInfo.g.cpp(9,10): fatal error C1083: Cannot open precompiled header file: 'Debug\pch.pch.codeanalysis': No such file or directory

Probable cause:
The PrecompiledHeaderOutputFile property is set to 'Debug\pch.pch' for all files (including pch.cpp)
but to 'Debug\pch.pch.codeanalysis' for 'Generated Files\XamlTypeInfo.g.cpp'

**Comment by kennykerr** [comment]
Hi Frank, which version of Visual Studio are you using?

**Comment by FrankHeimes** [comment]
> Hi Frank, which version of Visual Studio are you using?

Visual Studio 2019 Enterprise, version 16.5.2

**Comment by kennykerr** [comment]
Thanks, I do see this failure but again this is not a feature I have any control over. The project itself compiles without issue. Please report this here:

https://developercommunity.visualstudio.com/spaces/62/index.html

**Comment by FrankHeimes** [comment]
Reported here: https://developercommunity.visualstudio.com/content/problem/975713/running-code-analysis-fails.html
