### ISSUE TITLE
Compilation with warning level /Wall fails

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/cppwinrt#574]
1) Install the C++/WinRT extension from Microsoft
2) Open attached solution
   Ignore Designtime build failure; this is caused by a missing NuGet package
3) Compile solution
> Error	C4596	'implements_type': illegal qualified name in member declaration (compiling source file App.cpp)
4) Change C++ warning level from /Wall to /Level4
5) Compile solution
   This time, compilation succeeds.

**Comment by FrankHeimes** [comment]
OK, how or where can I upload the sample solution required to reproduce the problem right away?

**Comment by kennykerr** [comment]
Any reason why you're using /Wall - it's designed to produce tons of warnings. They're  informational warnings. They're not meant to indicate problems but a greater degree of diagnostics to help you understand the code. If you can share a minimal repro where it won't compile I'll take a look. Also include which version of Visual Studio you're using. But warnings are expected.

**Comment by FrankHeimes** [comment]
> Any reason why you're using /Wall - it's designed to produce tons of warnings. They're ... meant to indicate ... a greater degree of diagnostics to help you understand the code.

You're answering your own question. We enable /Wall because it causes quite some usefull warnings and we then globally disable just the most silly ones.

> If you can share a minimal repro where it won't compile I'll take a look.

I initially didn't realize how to do this. But now here it is: [WarningWallFails.zip](https://github.com/microsoft/cppwinrt/files/4419505/WarningWallFails.zip)

I'm using Visual Studio 2019 Enterprise, version 16.5.2

> But warnings are expected.

Agreed. But the whole point of this issue is that changing the warning level must not produce any more - or less - **errors**.

**Comment by kennykerr** [comment]
Good, just making sure you weren't misunderstanding the purpose of that option or using /WX and expecting it to compile. That's been known to happen. 😉 

I do notice the error in your project when compiling with /Wall. I also noticed that it didn't compile at /W4 either, but for different reasons. I fixed that, but the issue with /Wall persists. This looks like a bug in the C++ compiler. The /Wall option should not introduce additional errrors, but that's not something I can control. If you can share a repro with the C++ team I can make sure they take a look:

https://developercommunity.visualstudio.com/spaces/62/index.html

Just make sure the repro compiles cleanly with /W4 and only produces an error with /Wall. If they do find that it is in fact an issue with the C++/WinRT code gen they'll let me know and I'll get that fixed, but if that is the case I would expect them to make it an error regardless of the warning level.
