### ISSUE TITLE
Project requires absolute output path

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/cppwinrt#577]
1. Build attached solution as Debug|x86.
[RelativeOutDirFails.zip](https://github.com/microsoft/cppwinrt/files/4423353/RelativeOutDirFails.zip)

The OutDir property has been changed from $(SolutionDir)\\.... to "Final\\....".

The build succeeds.

2. Start the application.
Deployment fails with:

_========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
Copying files: Total 3 mb to layout...
DEP1000: Cannot copy file "Final\Debug\VGOUI\VGOUI.winmd" to layout "D:\VGOUIbar\Final\Debug\VGOUI\AppX\VGOUI.winmd". DirectoryNotFoundException - Could not find a part of the path 'Final\Debug\VGOUI\VGOUI.winmd'. [0x80070003]_

_Probable cause:_
The AppxPackagedFile entry for VGOUI.winmd in "D:\VGOUIbar\Final\Debug\VGOUI\VGOUI.build.appxrecipe" assumes that its path is
absolute. But that path has been copied from the OutDir property without prefixing the value of $(MSBuildProjectDirectory)

Relative paths for the OutDir property work in other project types without problems.
Using Visual Studio 2019, version 16.5.2.

**Comment by kennykerr** [comment]
@Scottj1s @jlaanstra is this something we can/should support?

**Comment by jlaanstra** [comment]
I'll take a look. In general relative output paths should work.

**Comment by jlaanstra** [comment]
I am unable to repro this using your provided project on VS 2019 16.5.3. If you can still repro, could you share a binlog of the build? https://msbuildlog.com/

**Comment by FrankHeimes** [comment]
I just did repro the bug using VS 2019 16.5.3. See the binlog in [msbuild.zip](https://github.com/microsoft/cppwinrt/files/4449157/msbuild.zip)

**Comment by kennykerr** [comment]
Unfortunately, the team does not have the capacity or skills to deal with bugs outside of the core C++/WinRT library and compiler. Feel free to keep the conversation going and contribute a PR as needed.
