### ISSUE TITLE
winrt::Windows::Foundation::Size is missing the equality operators

### ISSUE THREAD

**Issue by Zingam** [Microsoft/cppwinrt#58]
The c++/CX version of Windows::Foundation::Size has == and !=.

I checked some other structures and apparently they are also missing missing methods and operators. For example winrt::Windows::Foundation::Rect.

https://msdn.microsoft.com/library/windows/apps/br225995
https://msdn.microsoft.com/library/windows/apps/br225994

**Comment by smj389** [comment]
I find that using namespace using namespace winrt::Windows::Foundation::Numerics helps - there are operators there.

**Comment by kennykerr** [comment]
This is a known issue. We plan to add the comparison operators for all structures in a future update. The Numerics namespace is an interesting exception as those structs are provided by the Windows SDK.
