### ISSUE TITLE
Easy to accidentally modify a temporary produced by an iterator

### ISSUE THREAD

**Issue by oldnewthing** [microsoft/cppwinrt#580]
The collection iterators (either the slow iterator or the `fast_iterator`) return a mutable object from the `operator*`, which could lead to user confusion:

```cpp
IVector<Rect> v;
auto first = begin(v);
(*first).Height -= 2; // shrink the first rectangle
first[1].Height -= 2; // shrink the second rectangle
```

This doesn't actually modify the Rects in the vector. It modifies copies of the Rects, and the original Rects remain unchanged.

We could prevent this by making the `operator*` and `operator[]` return a `const value_type`, but that would make it impossible to `std::move` the result.

I think the downside is worse than the upside, but creating this issue so we can say that we discussed it and decided to leave things as they are.

Other negative decisions:

#### No `fast_iterator::operator->`

We could have implemented `operator->` as
```cpp
        auto operator->() const
        {
            struct arrow_wrapper
            {
                value_type value;
                pointer operator->() { return &value; }
            };

            return arrow_wrapper{ m_collection->GetAt(m_index) };
        }
```

but I chose not to do this because that would make it easier to make the mistake mentioned above.

#### No `*it = new_value`

We could have implemented `operator*` in terms of `operator[0]`, and `operator[]` as

```cpp
        auto operator[](difference_type n) const
        {
            struct proxy
            {
                fast_iterator const iterator; // NB: Captured by value, not reference
                operator value_type()
                {
                    return iterator.m_collection->GetAt(iterator.m_index);
                }
                void operator=(value_type const& value)
                {
                    iterator.m_collection->SetAt(iterator.m_index, value);
                }
            };
            return proxy{ *this + n };
        }
```

but I chose not to do that because it would have made

```
auto v = *it;
```

result in `v` being deduced as a `proxy` rather than as the element type.

**Comment by kennykerr** [comment]
Yep, the WinRT iterators are cheating by design. 😊

Because as you say, the cure is worse than the status quo. The standard library algorithms seem quite happy with the WinRT iterators. I agree that leaving them the way they are is probably the best.
