### ISSUE TITLE
C++/WinRt does not give a useful error message when I try to implement an exclusive interface not defined by my component

### ISSUE THREAD

**Issue by hendryems** [microsoft/cppwinrt#583]
I'm porting some code that implements ::ABI::Windows::ApplicationModel::Core::ICoreApplicationView:

```
#include "pch.h"
 
#include <winrt/Windows.ApplicationModel.Core.h>
#include <winrt/Windows.UI.Core.h>
 
using namespace winrt;
using namespace winrt::Windows::ApplicationModel::Activation;
using namespace winrt::Windows::ApplicationModel::Core;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::UI::Core;
 
struct NullApplicationView
    : implements<NullApplicationView, ICoreApplicationView>
{
    event<EventHandler<IActivatedEventArgs>> m_activatedEvent;
 
    event_token Activated(EventHandler<IActivatedEventArgs> const& handler)
    {
        return m_activatedEvent.add(handler);
    }
 
    void Activated(event_token const& token)
    {
        m_activatedEvent.remove(token);
    }
 
    CoreWindow CoreWindow()
    {
        return nullptr;
    }
 
    int32_t IsMain()
    {
        return false;
    }
 
    int32_t IsHosted()
    {
        return false;
    }
};
```

Attempting to do this in C++/WinRT on a brand new 'Windows Runtime Component (C++/WinRT)” project failed with a cryptic error:

```
error C2079: 'winrt::impl::producer<D,winrt::Windows::ApplicationModel::Core::ICoreApplicationView,void>::vtable' uses undefined struct 'winrt::impl::produce<D,I>'
        with
        [
            D=NullApplicationView
        ]

```

Turns out the issue here is that ICoreApplicationView is an exclusive interface. According to its definition, it may only be implemented by the CoreApplicationView class and hence I'm getting this error.

This is partly because, the default C++/WinRT project template has `WINRT_LEAN_AND_MEAN`  defined (in the vcxproj), which removes the ability to implement interfaces that are exclusive to a class not from the library.

I had to remove this this WINRT_LEAN_AND_MEAN to get it compiling, but it sure would have been great if the original error message was telling me more explicitly that implementing an exclusive interface was the issue.

**Comment by kennykerr** [comment]
Unfortunately, convincing the C++ compiler to produce useful error messages is a hard problem. We have actually spent a lot of engineering time on this. Believe it or not, it's a lot better than it used to be. 😊 

In earlier versions, many of these errors were linker errors that often didn't even mention the undefined type or the originating line of application code that attempted to instantiate said type. Short of improvements to the C++ language, there isn't much we can do about this right now.

**Comment by ChrisGuzak** [comment]
Implementing exclusive interfaces is important when creating test mocks. So `WINRT_LEAN_AND_MEAN` must not be used in this case. Ideally this would be in the [official docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq) but in the mean time this issue serves that purpose.
