### ISSUE TITLE
Spurious warning 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#584]
Repro provided by Noel Cross.

[Delegate-Repo.zip](https://github.com/microsoft/cppwinrt/files/4462956/Delegate-Repo.zip)

**Comment by oldnewthing** [comment]
Trying to figure out which warning this is about. Is it 4265 "class has virtual functions, but its non-trivial destructor is not virtual; instances of this class may not be destructed correctly"?

**Comment by oldnewthing** [comment]
The warning in question is

> C5205: delete of an abstract class winrt::impl::implements_delegate\<winrt::Windows::Foundation::TypedEventHandler\<winrt::Windows::Foundation::IInspectable,winrt::Windows::Media::Devices::DefaultAudioRenderDeviceChangedEventArgs>,H> that has a non-virtual destructor results in undefined behavior

This is a real bug, which was fixed in [PR 278](https://github.com/microsoft/xlang/pull/278) in the old xlang repo for build 190405.3. The 18362 SDK comes with build 190111.3 which doesn't have the fix.
