### ISSUE TITLE
.hpp files instead of .h

### ISSUE THREAD

**Issue by kirillkovalenko** [microsoft/cppwinrt#585]
Is there a way to have .hpp files generated instead of .h ?

**Comment by kennykerr** [comment]
No, there's no way to do that. We could in theory provide such an option but there are already many other tools that rely on the file name convention that making such a change would not be very practical.

**Comment by kirillkovalenko** [comment]
>  but there are already many other tools that rely on the file name convention that making such a change would not be very practical

Many teams have guidelines such that c++ header files should have .hpp suffix,  so your answer is not really acceptable.

What tools are you talking about, BTW? Some MS internal ones? If so, how such an option (say turned off by default) would affect these tools?

**Comment by kennykerr** [comment]
Coding guidelines generally don't apply to third party libraries. There are numerous great C++ libraries that don't follow a consistent style. 

We have various internal tools yes, but I was referring to the Visual Studio extensions and particularly those for building Xaml apps that depend on C++/WinRT. 

If you'd like to contribute a command line option to generate headers with the `.hpp` extension I'd be happy to review the PR.
