### ISSUE TITLE
Structured bindings don't work with WinRT collection types

### ISSUE THREAD

**Issue by dfields-msft** [microsoft/cppwinrt#586]
[Structured bindings](https://en.cppreference.com/w/cpp/language/structured_binding) are a very useful syntax for iterating a collection of tuples:

```cpp
std::map<int, int> mapping;
for (const auto& [ key, value ] : mapping)
{
    std::cout << key << " maps to " << value << std::endl;
}
```

Unfortunately, these don't seem to be properly supported by WinRT collections:

```cpp
winrt::Windows::Foundation::Collections::IMap<int, int> mapping;

// error C2248: 'winrt::Windows::Foundation::IUnknown::m_ptr': cannot access private member declared in class 'winrt::Windows::Foundation::IUnknown'
for (const auto& [ key, value ] : mapping)
{
    std::cout << key << " maps to " << value << std::endl;
}
```

**Comment by kennykerr** [comment]
In theory we should be able to provide a `get` partial specialization that resolves the `IIterator` and returns the key and value parts...

**Comment by kennykerr** [comment]
Thanks Raymond!
