### ISSUE TITLE
Problems with Coroutines in  VC++ 19.10.24728

### ISSUE THREAD

**Issue by smj389** [Microsoft/cppwinrt#59]
In this build, the specialization coroutine_traits<winrt::Windows::Foundation::IAsyncAction, Args ...> does not compile because AsyncStatus is not qualified. Adding using namespace winrt::Windows::Foundation in the local scope of GetResults() and return_void() is necessary to get it to compile.

This was not a problem in an earlier build of the compiler.

**Comment by kennykerr** [comment]
That's a newer build than the 2017 RC. I presume you got that from the NuGet compiler drops. While we don't support those builds, we'll take a look to make sure something's not broken. Thanks for the heads up!

**Comment by smj389** [comment]
It's from an RC refresh.

**Comment by AndrewPardoe** [comment]
@smj389: My mistake: I got the RC.2 build number wrong and told Kenny that it was probably a NuGet build. Sorry for the trouble.

**Comment by kennykerr** [comment]
Thanks Andrew. I'll get the latest update and investigate.

**Comment by kennykerr** [comment]
I have updated to RC.2 but I don't see any problems. Can you share a small repro?

**Comment by smj389** [comment]
I attach the project I tested the problem in. Note I have /permissive- on.
I also attach the diff I made to base.h to make things work.
Without these changes, view.cpp won't compile.

[diff.txt](https://github.com/Microsoft/cppwinrt/files/664713/diff.txt)
[ComposedApp.zip](https://github.com/Microsoft/cppwinrt/files/664714/ComposedApp.zip)

**Comment by kennykerr** [comment]
Let us know if you're still experiencing compiler issues with the latest update of C++/WinRT on Visual Studio 2017 RC.4 - otherwise I'll assume this has been resolved.
