### ISSUE TITLE
Red squiggles when creating a new C++/WinRt Core App in Visual Studio 2019 16.6

### ISSUE THREAD

**Issue by merlynoppenheim** [microsoft/cppwinrt#592]
In Visual Studio 16.6 Preview 3 or higher:
1. Create a new C++/WinRT Core App
2. Open App.cpp
3. Observe whether or not there are errors and red squiggles

Expected: There are none
Actual: There are several

Workaround:
1. Perform a build
2. Right click on the project and click Rescan Solution

Screenshot below:

![Capture](https://user-images.githubusercontent.com/44985659/79627717-72377e80-80ef-11ea-855e-f4b85e953975.PNG)

**Comment by kennykerr** [comment]
Thanks for the feedback. Unfortunately this is a limitation of the relatively minimal Visual Studio integration. There's not much we can do about this until Visual Studio begins to offer first-class support for C++/WinRT. Feel free to bring this up with the Visual Studio team:

https://developercommunity.visualstudio.com/spaces/62/index.html

**Comment by merlynoppenheim** [comment]
Hi @kennykerr , I logged this ticket on behalf of a customer who posted feedback on Developer Community.  Sorry for the confusion.  I'll reach out to you.

**Comment by HppZ** [comment]
VS still no first-class support for C++/WinRT?

**Comment by CERobertson** [comment]
Still a problem in 2023
