### ISSUE TITLE
CppWinRTModernIDL does not default to True for x64 platform resulting in MIDL failure

### ISSUE THREAD

**Issue by riverar** [microsoft/cppwinrt#596]
After adding the cppwinrt NuGet package to a C++ project with a simple IDL file, the project will fail to build if the x64 platform is targeted. Upon closer inspection, this appears to be due to `CppWinRTModernIDL` being explicitly set to `False` (by `Microsoft.Cpp.x64.user` prop sheet) for x64 platforms. This does not align with the [cppwinrt default property value documentation](https://github.com/microsoft/cppwinrt/tree/master/nuget).

# Environment
cppwinrt NuGet package 2.0.200316.3
Visual Studio 2019 16.5.1
Windows 10 10.0.19041.207

# Steps to reproduce
1. Create a new C++ Static Library (Universal Windows) project.
2. Add sample IDL file:
```idl
namespace test
{
    [version(1)]
    runtimeclass BackgroundHandler
    {
        BackgroundHandler();
        void Run(Windows.ApplicationModel.Background.IBackgroundTaskInstance taskInstance);
    }
}
```
3. Add the cppwinrt NuGet package to the project.
4. Set the Solution Platform to `x86` and build the project.
5. Observe the project builds successfully.
6. Set the Solution Platform to `x64` and build the project.
7. Observe the project fails to build, with error `Error MIDL2011 [msg]unresolved type declaration [context]: Windows.ApplicationModel.Background.IBackgroundTaskInstance [ Parameter 'taskInstance' of Procedure 'Run' ( RuntimeClass 'test.BackgroundHandler' ) ] ...`	

# Expected
Consistent cppwinrt compilation experience regardless of Solution Platform selected.

# Actual
Compilation error:  `Error MIDL2011 [msg]unresolved type declaration [context]: Windows.ApplicationModel.Background.IBackgroundTaskInstance [ Parameter 'taskInstance' of Procedure 'Run' ( RuntimeClass 'test.BackgroundHandler' ) ] ...`

**Comment by kennykerr** [comment]
Rafael, thanks for the high quality bug reports!

**Comment by riverar** [comment]
This one might be a dud. I just discovered MSBuild `Microsoft.Cpp.x64.user.props` can be edited by the user (or any plugins, etc.) at any time and mine contained some errant CppWinRT properties. I restored it to the original (effectively blank).

**Comment by kennykerr** [comment]
I checked the repro steps myself and was not able to reproduce the problem either. Thanks for confirming.
