### ISSUE TITLE
Where is CoInitializeEx called?

### ISSUE THREAD

**Issue by schlzber** [Microsoft/cppwinrt#6]
Probably not really related to this Project, but I copied app.cpp, pch.cpp and pch.h to my UWP Project (created with Blank template and deleted App.xaml.* and MainPage.xaml.*).
I get an exception with HRESULT 0x800401f0 (CoInitialize was not called) in wWinMain (Application::Start... line). 
Am I missing a project or manifest Setting?

**Comment by kennykerr** [comment]
The Visual C++ CRT should call RoInitialize (the WinRT equivalent of CoInitializeEx) before you enter WinMain. Have a look at a sample like [Blocks](https://github.com/Microsoft/cppwinrt/tree/master/10.0.14393.0/Samples/Blocks). If you’re doing something slightly different (a desktop or console app) then you must call RoInitialize yourself. You can use the winrt::initialize wrapper function. An example of that can be found in the [Syndication](https://github.com/Microsoft/cppwinrt/tree/master/10.0.14393.0/Samples/Syndication) sample.

**Comment by schlzber** [comment]
Thank you! I fixed it by adding a call to 	initialize(); just before instantion of the App class.
I still wonder, where is that call happening in the XamlCode example?

**Comment by kennykerr** [comment]
Did you not remove the /ZW option? This allows you to combine C++/CX code but changes the CRT's startup behavior. If you remove /ZW then you won't have to call initialize.

**Comment by schlzber** [comment]
Yes I removed it to make sure not to use any C++/CX features by accident. Thanks for Clearing that up!
