### ISSUE TITLE
Detailed guide for beginners

### ISSUE THREAD

**Issue by peteyy** [Microsoft/cppwinrt#60]
I know this is only a "developer preview", but I'm really interested in building apps with it. 

Coming from a non-cpp background, your library is not really approachable for me. It would be nice to have a channel that we could reach you on, IRC, Slack or Gitter are both nice alternatives for chats, and are free for open-source projects.

I'd be more than happy to help you with documentation along the way.

**Comment by kennykerr** [comment]
Hi Peter, feel free to reach out via [twitter](https://twitter.com/kennykerr) or simply ask questions here. I have a [getting started guide here](https://kennykerr.ca/2016/10/24/cppwinrt-getting-started/), but if you're new to C++ then you may want to start with an introduction to C++ before diving into C++/WinRT. We have some great [courses for beginners and experts on Pluralsight](https://www.pluralsight.com/).

**Comment by peteyy** [comment]
Alright so I'm going to go ahead and collect everything on this thread.

I see no template for starting out a project on visual studio, which is the one I should start out with? Should I first get familiar with the Visual C++ for Universal Windows project structure? Or where could I get guidelines for starting out something like this?

**Comment by kennykerr** [comment]
Visual Studio doesn't yet include suitable project templates for C++/WinRT. You can work your way back from the existing project templates but that's complicated. The simplest way to get started is to use [one of the sample projects](https://github.com/Microsoft/cppwinrt/tree/master/10.0.14393.0/Samples) as a starting point.

**Comment by peteyy** [comment]
In most of your tutorials (like this one https://moderncpp.com/asynchronous-programming/) I see you're using some of the Windows API classes with ease, but I'm not sure where could I get familiar with these classes.

Where should I look for documentation on usages, on HTTP clients, and basic XAML controls?

**Comment by walbourn** [comment]
Note that the [Direct3D VS Game templates project](https://github.com/walbourn/directx-vs-templates) now includes C++/WinRT variants.

**Comment by kennykerr** [comment]
Thanks Chuck!

**Comment by kennykerr** [comment]
Peter, you can find the list of [Windows Runtime APIs documented here.](https://msdn.microsoft.com/en-us/library/windows/apps/br211377.aspx)
