### ISSUE TITLE
Any guidance on reducing generation of same projection headers again and again?

### ISSUE THREAD

**Issue by riverar** [microsoft/cppwinrt#605]
# Environment
cppwinrt NuGet package 2.0.200316.3
Visual Studio 2019 16.5.1
Windows 10 10.0.19041.207

# Scenario
I'm doing research to determine if we can reduce the number of times the _same_ projection headers get generated in a solution containing ~35 projects during a CI build pass (no previous `Generated Files` to rely upon).

Some thoughts:
* Is there any documentation on `CppWinRTUseHardlinksIfPossible`? Sounds useful.
* Can we override the projection header output path to, say, a common path, and share that solution wide? Do you foresee any issues there?
* How does Microsoft handle this internally?

**Comment by jlaanstra** [comment]
```CppWinRTUseHardLinksIfPossible``` is simply used to control to ```UseHardlinksIfPossible``` property of any copy steps in the targets.

You can use the ```CppWinRTEnablePlatformProjection``` property to turn off the platform projection generation and use a dedicated project to generate those or manually run cppwinrt to generate the platform projection. You then simply need to add the output folder to every other project's include path.

**Comment by kennykerr** [comment]
> How does Microsoft handle this internally?

Note that the cost is in recompiling the headers, not the fact that they are generated repeatedly. Generating the headers is very cheap. Compiling them repeatedly is very costly. 

The only way I know of today is to use a shared PCH file. In the future, when C++ modules are working, we should be able to use that instead.

**Comment by riverar** [comment]
Great tips, thanks!
________________________________
