### ISSUE TITLE
Document how to disable pch in exe help

### ISSUE THREAD

**Issue by davidmatson** [microsoft/cppwinrt#606]
Suggestion:
In cppwinrt.exe help, mention that "." is the way to disable using a pre-compiled header.

I ended up figuring this out by hunting around and saw it here:
https://github.com/microsoft/cppwinrt/blob/master/test/test_component_no_pch/test_component_no_pch.vcxproj

But I wouldn't have guessed that syntax.

The help today:
https://github.com/microsoft/cppwinrt/blob/master/cppwinrt/main.cpp
says:
"Specify name of precompiled header file (defaults to pch.h)"

Here's a suggested edit:
"Specify name of precompiled header file (defaults to pch.h; use '.' to disable)"

**Comment by kennykerr** [comment]
Thanks David! That's a good suggestion. Feel free to contribute a PR, otherwise I'll get to it soon.
