### ISSUE TITLE
Provide type trait or concept to verify if a projection type derives from another

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#609]
It might be useful in cases where a template uses a C++/WinRT projection type, to constrain that template to only types deriving from another projection type.

This can currently be achieved multiple ways:
```cpp
template<typename T>
	requires std::derived_from<T, winrt::impl::base_one<T, winrt::Windows::UI::Xaml::Controls::Page>>
class XamlPageHost final : public BaseXamlPageHost {
```
```cpp
template<typename T>
	requires std::convertible_to<T, winrt::Windows::UI::Xaml::Controls::Page>
class XamlPageHost final : public BaseXamlPageHost {
```

The problem with solution 1 is that it taps into implementation details of C++/WinRT, which is undesirable for a consumer of the library, but it is a reliable way currently to detect if `T` derives from `Page`.
Solution 2 has the issue that if some other non-projection type offers a conversion operator to the desired projection type, the template will match.

To resolve this situation, there should be a `winrt::is_derived_from<T, U>` type trait (and `winrt::is_derived_from_v` shorthand) which would have a `static constexpr` member `value` that is `true`, if the projection type `T` derives from type `U`.

**Comment by kennykerr** [comment]
We could potentially offer a type trait that will tell you whether T is a WinRT type. You could then combine that with `std::is_convertible` to answer such a question. Do you have a production scenario where this is needed?

**Comment by sylveon** [comment]
I have a template which can host any page which is derived from `TranslucentTB.Xaml.FramelessPage` (which implements some common functionality, like allowing XAML to alter the window's title just by setting a property) in an XAML island.

I simply want to add some compile-time validation in here, because `no member function named Title` (nested in between a bunch of other template errors) isn't a very helpful error compared to `type does not derive from TranslucentTB.Xaml.FramelessPage`

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.

**Comment by sylveon** [comment]
If I where to implement this myself, what would be the better way to detect if a type is a projection?

**Comment by kennykerr** [comment]
Paging @DefaultRyan as your scenario seems to involve Xaml composition and that's a bit of a mix of projected and implementation types. Perhaps he has a suggestion beyond `std::is_convertible`.
