### ISSUE TITLE
Can I create my own Projection on a custom component?

### ISSUE THREAD

**Issue by Nirmal4G** [Microsoft/cppwinrt#61]
I read your articles on C++ with WinRT on [Modern](https://moderncpp.com).

Where you also mentioned without your "modern.exe" compiler, you can't project into C++ (cppwinrt).
So How can I project a library I wrote as WinRT component into consumable in C++ language?
Is your compiler is the only way? or WinMD automatically projects them?

Any resources if already there would be fine too!
I searched and I couldn't find anything except your articles

**Comment by kennykerr** [comment]
You need the cppwinrt.exe compiler (previously called modern.exe) in order to do this. We will make this available in a future update.

**Comment by Nirmal4G** [comment]
Will it available in the Creators Update SDK?

**Comment by kennykerr** [comment]
I don't have any specifics on when C++/WinRT will be available through the Windows SDK, but we will publish an update of C++/WinRT for the Windows 10 Creators Update.

**Comment by Nirmal4G** [comment]
Thanks.
Looking forward to it.

**Comment by yura-yaroshevich** [comment]
Waiting for modern.exe to be published publicly.
