### ISSUE TITLE
C6011 code analysis warnings in base.h

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#616]
Code analysis is raising C6011 in base.h:

![image](https://user-images.githubusercontent.com/1564575/81608931-e205f580-938b-11ea-970d-8513e27b9322.png)

![image](https://user-images.githubusercontent.com/1564575/81608976-f34f0200-938b-11ea-8709-27bf26fb941d.png)

**Comment by vbaderks** [comment]
There is an open issue about this caused by assert (WINRT_ASSERT in this case):
https://developercommunity.visualstudio.com/idea/978757/dont-emit-c6011-for-debug-configuration-if-there-i.html

**Comment by kennykerr** [comment]
Sounds like something Visual Studio should fix. Thanks @vbaderks.
