### ISSUE TITLE
Filtering should issue an error if no match found

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#620]
To help make build systems more robust, the filtering switches (-filter, -include, -exclude) should support erroring out if no match is found, indicating a possible typo.  This behavior would have to be opt-in, say with a -strict switch.

See also #622

**Comment by Scottj1s** [comment]
cc: @roywill

**Comment by oldnewthing** [comment]
How about allowing the opt-in/out on a per-namespace basis by using punctuation, like we do with references (which uses + as a per-flag option).

`-exclude A.B.C D.E.F! -include G H!`

this says "exclude A.B.C if you see any (but don't complain if you don't). Also exclude D.E.F and it should definitely be excluded, complain if you don't see one. Include G if you see it (but don't complain if you don't). Also include H and complain if it's not there."

**Comment by Scottj1s** [comment]
That's nice and compact.  My only concern would be ensuring that a build system is robust by default.  A -strict switch could automatically be supplied, independently, which would ensure that users did the right thing.  But that's somewhat orthogonal to your suggestion, as it could just change the default interpretation of an unsuffixed -include/-exclude entry.  I.e., with -strict, you could then relax back to optional - equivalent to your example:
`-exclude A.B.C? D.E.F -include G? H
`

**Comment by oldnewthing** [comment]
I'm wary of switches named things like `-optimize` or `-strict` because you have nowhere to go for v2. `-superoptimize`? And then `-extra-double-secret-superoptimize`? Would new switches `-mustexclude` and `-mustinclude` work? Or does that have the same build system problem?

**Comment by Scottj1s** [comment]
Sure, I'm open to a narrower switch: maybe -filterstrict, so that it applies evenly to all?

**Comment by roywill** [comment]
When there are levels of things like optimize, I would expect it to be an option of the switch

-o:dbcea

not

-od -ob

and other invented names. 

In this case do we want to change the behavior to -version behavior and just bump that instead of adding blocks of switches?

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
