### ISSUE TITLE
cppwinrt should support explicit enumeration of expected generated headers 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#622]
To help make build systems more robust, cppwinrt should support an explicit enumeration of expected generated projection headers.  This list could be supplied via multiple -out switches.  This behavior would have to be opt-in, say with a -strict switch.

See also #620

**Comment by Scottj1s** [comment]
cc: @roywill

**Comment by fghzxm** [comment]
+1 from mesonbuild/meson#7624

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
