### ISSUE TITLE
How does throw_hresult cause the app to crash with error cpp_exception_e06d7363?

### ISSUE THREAD

**Issue by benstevens48** [microsoft/cppwinrt#625]
I have a Windows Runtime Component written in C++/WinRT that I'm using as part of a C# UWP app. Recently I noticed a handful of crashes in the Dev Center where the stack trace is like this.

Frame | Image | Function
-- | -- | --
KERNELBASE.dll | RaiseException | 0x0000000000000069
1 | VCRUNTIME140_APP.dll | _CxxThrowException | 0x00000000000000AD
2 | MyComponent.dll | winrt::throw_hresult | 0x00000000000000B2
3 | MyComponent.dll | winrt::MyComponent::implementation::MyClass::MyFunction | 0x00000000000003E9
4 | MyComponent.dll | winrt::MyComponent::implementation::MyClass::MyFunctionAsync$_ResumeCoro$2 | 0x00000000000002AC
5 | MyComponent.dll | winrt::impl::resume_background_callback

The name it gives to the exception is
```
cpp_exception_e06d7363_mycomponent.dll!winrt::mycomponent::implementation::myclass::myfunction
```

In the C# part of my app I call the function roughly as follows.
```C#
try{
    await MyComponent.MyFunctionAsync();
}catch(Exception){
    return;
}
```
Note that the exception should be caught and the app shouldn't crash. So why is the app crashing with a C++ exception? Is it a bug in my app, a bug in C++/WinRT, a bug in Windows or a hardware failure or maybe lack of memory, or is the stack trace wrong/misleading?

The function `MyFunction` does not call `throw_hresult` directly, but it calls `check_hresult` on the result of some COM calls.

**Comment by kennykerr** [comment]
It's hard to know without looking at a debugger. I'd turn on your debugger's first-chance exceptions and see what kind of exception is being thrown and then follow it to the ABI boundary to determine what happens and whether it is properly propagated.

**Comment by benstevens48** [comment]
Thanks for the advice. Unfortunately I can't reproduce the error on my PC, so the above info obtained from the Windows Dev Center crash report is all I'm likely to get.

**Comment by DefaultRyan** [comment]
0xe06d7363 is the generic code used for C++ exceptions. Any C++ exception that's thrown without being caught will probably look like this. For some tips on how to decode what actually happened if you have crash dumps, see this Raymond Chen blog: https://devblogs.microsoft.com/oldnewthing/20100730-00/?p=13273

**Comment by benstevens48** [comment]
Thanks or the info. I don't actually have a crash dump, only the info from the Dev Center.

The thing is, I would expect `throw_hresult` to produce a hresult exception that would travel through the ABI boundary and be caught by C# code. I don't understand why a C++ exception eventually gets thrown. However, looking at the code for `throw_hresult`, I see it is possible for it to throw `std::bad_alloc`, so maybe that's it. I don't really understand the logic of this. I'm using the pattern `try{ check_hresult(...)}catch(hresult_error){}` a lot in my code and I assumed that would catch all exceptions thrown by `check_hresult`, but perhaps that's not correct.

**Comment by kennykerr** [comment]
C++/WinRT handles `std` exceptions and `winrt` exceptions. Anything else will not be handled. C++/WinRT itself uses `winrt::to_hresult` to translate any supported exception to an `HRESULT`. You could also try to catch both `winrt::hresult_error` and `std::exception`. 

Hopefully that helps, but without more information about the crash it's hard to know for sure. You might want to figure out how you can get a dump or if that's not possible add some tracing or logging.

**Comment by benstevens48** [comment]
@kennykerr - after coming across this again, I now think that I am seeing the result of this compiler bug <https://developercommunity.visualstudio.com/t/In-some-instances-an-exception-escapes/1144291>. If you have any influence with the MSVC team perhaps you could encourage them to fix it, as the way C++/WinRT handles co_await IAsyncOperation is probably particularly susceptible. (Note I may be wrong about this bug but it's my best guess).
