### ISSUE TITLE
hstring and nullptr don't play nice.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#627]
Currently you can't initialize an hstring from nullptr, but assigning nullptr works.

```
hstring str{ nullptr }; // error
hstring str = nullptr; // error

hstring str{};
str = nullptr; // works
```

This is inconsistent. We should consider disabling the assignment of nullptr by adding:

```
hstring& operator=(std::nullptr_t) = delete;
```

**Comment by kennykerr** [comment]
Good idea - we should delete this operator.

**Comment by BenJKuhn** [comment]
nullptr is the definitive value for an empty string. If you want to assign an empty string explicitly (as opposed to using a default-constructed string), what would that alternative code look like?

**Comment by kennykerr** [comment]
A `nullptr` is the value of an empty `HSTRING` on the ABI but not in C++/WinRT. An empty string in C++/WinRT (as with the C++ standard library) is a valid zero-length string literal e.g. `L""`.
