### ISSUE TITLE
VSIX debug visualizer can't handle types not referenced directly in source

### ISSUE THREAD

**Issue by davidmatson** [microsoft/cppwinrt#628]
Per @Scottj1s, the debug visualizer requires that the types be present in the PDB. Types not present in the PDB cannot be visualized, which is unfortunate as a developer may want to debug to see values for properties which are not yet referenced in source.

```c++
#include <iostream>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.System.h>

#pragma comment(lib, "windowsapp")

int main()
{
    auto users = winrt::Windows::System::User::FindAllAsync().get();
    //winrt::Windows::System::UserAuthenticationStatus s{};
    //winrt::Windows::System::UserType t{};

    for (const auto& user : users)
    {
        std::wcout << static_cast<uint32_t>(user.Type()) << L"\n";
    }
}
```

Debugging (w/a little data redacted):
![image](https://user-images.githubusercontent.com/3360277/82390832-9b9c4080-99f4-11ea-8fa5-f6fb3db813c1.png)

If the two commented lines above are uncommented, debugging works.

**Comment by kennykerr** [comment]
Same as #634.
