### ISSUE TITLE
VSIX debug visualizer fails for enum properties in Watch 1 tab

### ISSUE THREAD

**Issue by davidmatson** [microsoft/cppwinrt#629]
May be related to #628.

```c++
#include <iostream>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.System.h>

#pragma comment(lib, "windowsapp")

int main()
{
    auto users = winrt::Windows::System::User::FindAllAsync().get();
    winrt::Windows::System::UserAuthenticationStatus s{};
    winrt::Windows::System::UserType t{};

    for (const auto& user : users)
    {
        std::wcout << static_cast<uint32_t>(user.Type()) << L"\n";
    }
}
```

(Some minor data has been redacted in screenshots below.)

Initial display of some properties in Watch 1 fails:
![image](https://user-images.githubusercontent.com/3360277/82391038-22511d80-99f5-11ea-801e-2f9c823c141f.png)

In the Locals tab, it works just fine:
![image](https://user-images.githubusercontent.com/3360277/82391062-37c64780-99f5-11ea-8450-3f2bb3a7af34.png)

And if the Watch 1 item is deleted and re-added after viewing in the Locals tab, it then works fine:
![image](https://user-images.githubusercontent.com/3360277/82391143-6e9c5d80-99f5-11ea-8794-ceb3d75bb6ef.png)

**Comment by kennykerr** [comment]
Same as #634.
