### ISSUE TITLE
Link error with Hello CppCon example code

### ISSUE THREAD

**Issue by harrywye** [Microsoft/cppwinrt#63]
Went through some docs, but I still cannot figure out how to create a simple UWP app using C++/WinRT. I've tried a number of different sample codes, but nothing really "runs" (using main() or wWinMain()). For example, I tried a sample code from CppCon 2016 presentation, and it fails to link. Any help will be greatly appreciated.

### Sample code:

	struct App : ApplicationT<App> 
	{
		void OnLaunched(LaunchActivatedEventArgs const &)
		{
			TextBlock block; 
			block.FontFamily(FontFamily(L"Segoe UI Semibold"));
			block.FontSize(140.0); 
			block.Foreground(SolidColorBrush(Colors::HotPink()));
			block.VerticalAlignment(VerticalAlignment::Center); 
			block.TextAlignment(TextAlignment::Center);
			block.Text(L"Hello CppWinRT!");
			Window window = Window::Current();
			window.Content(block); window.Activate();
		}
	};
	int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
	{
		Application::Start([](auto &&) { make<App>(); });
	}
   
### Build error:

	Error	LNK2019	unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) 	
	C:\Projects\cppwin\hello-world\build\x86-Debug\HelloCppWinRT.vcxproj
	C:\Projects\cppwin\hello-world\build\x86-Debug\MSVCRTD.lib(exe_main.obj)	1

**Comment by kennykerr** [comment]
Based on the error message, it sounds like the linker is searching for the wrong entry point function. C++/WinRT is just a library. It's still up to you to properly configure the build. This can admittedly be a daunting task. If you're not sure how to configure the project then I suggest you start with [one of the sample projects](https://github.com/Microsoft/cppwinrt/tree/master/10.0.14393.0/Samples/XamlCode).

**Comment by harrywye** [comment]
Hi @kennykerr Thanks for the tips. I was able to successfully run the XAML-Code sample app using the C++/WinRT nuget package. I was trying to use vcpkg cppwinrt port in the original test app project (using cmake). I guess that'll have to wait until the next year. :). Thanks!
