### ISSUE TITLE
Add support for the builder pattern

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#631]
WinRT properties that are writable should return a reference to self (`D const&`) to allow chaining calls to various properties.

**Comment by MikeGitb** [comment]
Shouldn't that be a mutable reference then?

**Comment by kennykerr** [comment]
No, the reference itself is not mutable. It is the COM object being pointed to by the reference that is changed.

**Comment by eklipse2k8** [comment]
Usually in a builder pattern at least commonly used in Java/Android, the class you use to build with is a mutable builder class, that once you call .build(), will return an immutable non-builder class.

I think that WinRT properties in general are quite "unstable", as some setters actually trigger state changes. A builder should be a stand-in for a constructor, and allowing normal WinRT setters to operate as builders will make for a messy codebase.

Right now the **.prop(value)** setter pattern in cppwinrt puts the onus on the developer to understand side-effects on setters.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
