### ISSUE TITLE
VSIX debug visualizer doesn't show IPropertySet values

### ISSUE THREAD

**Issue by davidmatson** [microsoft/cppwinrt#634]
I'm trying this with a private C++/WinRT API.

![image](https://user-images.githubusercontent.com/3360277/82479041-aef7ec00-9a86-11ea-8a08-7be67a9ec6ff.png)

Since IPropertySet implements ```IIterable<IKeyValuePair<winrt::hstring, IInspectable const &>>```, it should be possible to show all its contents.

More generally, it would be great to add visualization support for:
* IIterable of anything (at least show an item for each element; show actual values where the types are visualizable)
* KeyValuePair of anything (show actual key and/or value if those types are visualizable)

**Comment by kennykerr** [comment]
Thanks David, this is a known issue with the visualizer that it cannot display information about generic types like `IIterable`. Feel free to contribute a fix but we don't have a developer working on the visualizer at the moment. Our hope was that the Visual Studio team would eventually consume this support and provide it directly. There are many issues with the visualizer that we unfortunately cannot fix without direct support from Visual Studio.

**Comment by DefaultRyan** [comment]
@davidmatson I'm fixing the KeyValuePair right now in https://github.com/microsoft/cppwinrt/pull/1472, and will address IIterable soon.
