### ISSUE TITLE
Support consuming events from types that are not themselves WinRT APIs

### ISSUE THREAD

**Issue by davidmatson** [microsoft/cppwinrt#635]
It would be great to have support for consuming WinRT events in member functions without having to author a WinRT type.

The docs nicely distinguish between what's needed to [consume an API](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis) vs [author an API](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis). They rightly point out how the asynchronous nature of events means you need to be careful when [using a member function as a delegate](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/weak-references#if-you-use-a-member-function-as-a-delegate). But the only solutions offered include authoring WinRT APIs, which an event consumer isn't always doing.

I came up with (I think) a way to extend the author APIs-style pattern of strong_this and weak_this to support shared_ptr/weak_ptr for consumer-only types.

Two questions:
1. Does this usage look correct?
2. If so, could even handler constructor overloads be added to support shared_ptr/weak_ptr directly, similar to the existing com_ptr/weak_ref versions?

Here's a simplified version of the pattern:

ConsoleNetworkWatcher.h:
```c++
#pragma once

#include <iostream>
#include <memory>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Networking.Connectivity.h>

template <typename T>
struct WeakEventHandler : winrt::Windows::Foundation::EventHandler<T>
{
    template <typename O, typename M> WeakEventHandler(std::weak_ptr<O>&& object, M method) :
        winrt::Windows::Foundation::EventHandler<T>([o = std::move(object), method](auto&&... args) {
        if (auto s = o.lock()) { ((*s).*(method))(args...); } })
    {
    }
};

template <typename TSender, typename TResult>
struct WeakTypedEventHandler : winrt::Windows::Foundation::TypedEventHandler<TSender, TResult>
{
    template <typename O, typename M> WeakTypedEventHandler(std::weak_ptr<O>&& object, M method) :
        winrt::Windows::Foundation::TypedEventHandler<TSender, TResult>(
            [o = std::move(object), method](auto&&... args) { if (auto s = o.lock()) { ((*s).*(method))(args...); } })
    {
    }
};

struct WeakNetworkStatusChangedEventHandler : winrt::Windows::Networking::Connectivity::NetworkStatusChangedEventHandler
{
    template <typename O, typename M> WeakNetworkStatusChangedEventHandler(std::weak_ptr<O>&& object, M method) :
        winrt::Windows::Networking::Connectivity::NetworkStatusChangedEventHandler(
            [o = std::move(object), method](auto&&... args) { if (auto s = o.lock()) { ((*s).*(method))(args...); } })
    {
    }
};

struct ConsoleNetworkWatcher final
{
    static std::shared_ptr<ConsoleNetworkWatcher> Create()
    {
        auto result{ std::shared_ptr<ConsoleNetworkWatcher>{ new ConsoleNetworkWatcher{} } };
        Initialize(result);
        return result;
    }

    ConsoleNetworkWatcher(const ConsoleNetworkWatcher&) = delete;
    ConsoleNetworkWatcher(ConsoleNetworkWatcher&&) noexcept = delete;

    ~ConsoleNetworkWatcher()
    {
    }

    ConsoleNetworkWatcher& operator=(const ConsoleNetworkWatcher&) = delete;
    ConsoleNetworkWatcher& operator=(ConsoleNetworkWatcher&&) = delete;

private:
    ConsoleNetworkWatcher()
    {
    }

    // Two-phase initialization is required since event registration requires using a weak_ptr, which is only possible
    // after this object is managed by a shared_ptr, which it only can be after the constructor completes.
    static void Initialize(std::shared_ptr<ConsoleNetworkWatcher> instance)
    {
        instance->m_statusChangedRevoker =
            winrt::Windows::Networking::Connectivity::NetworkInformation::NetworkStatusChanged(winrt::auto_revoke,
                WeakNetworkStatusChangedEventHandler{ std::weak_ptr{ instance }, &NetworkStatusChanged });
    }

    void NetworkStatusChanged(const winrt::Windows::Foundation::IInspectable&)
    {
        std::wcout << L"Network status has changed " << ++changeCount << L" time(s).\n";
        std::wcout.flush();
    }

    int changeCount{}; // Sample instance state
    winrt::Windows::Networking::Connectivity::NetworkInformation::NetworkStatusChanged_revoker m_statusChangedRevoker{};
};
```

Main.cpp:
```c++
#include "ConsoleNetworkWatcher.h"
#include <Windows.h>

int main()
{
    auto watcher{ ConsoleNetworkWatcher::Create() };

    Sleep(-1);
}
```

Additional notes:
The workaround I have with derived event handler types is a bit uglier to call than built-in support would be. Maybe there's a way to extend without requiring specifying new concrete/derived types, but I didn't come up with one.

I only added an overload for weak_ptr in this example, but I think the natural shared_ptr overload would work as well.

Of the three types at the top, only WeakNetworkStatusChangedEventHandler is used in this example. I left the other two (WeakEventHandler and WeakTypedEventHandler) to show what I'm using for more conventional events (with both sender and e).

The event consumer type is required to be put on the heap via shared_ptr/Create factory method to enable reference counting. I left the type as non-copyable and non-movable since that's sufficient for my case and I wasn't sure if copying/moving types with registered event handlers would make work correctly.

(I had original derived from std::enable_shared_from_this, but then realized it didn't help much since the two-phase init was needed anyway and calling result->Inintialize() vs Initialize(result) was about the only price to pay to keep the public surface area of the event consumer type smaller.)

**Comment by ChrisGuzak** [comment]
looks cool. a couple of minor things in the impl. use `std::make_shared`, and publicly derive from `std::enable_shared_from_this<ConsoleNetworkWatcher>'

**Comment by davidmatson** [comment]
Thanks, Chris. I had originally done enable_shared_from this (notes above), but it seemed like it just increased public surface area. I wanted to use make_shared, but apparently it requires the constructor to be [public](https://stackoverflow.com/questions/8147027/how-do-i-call-stdmake-shared-on-a-class-with-only-protected-or-private-const/8147213), which seemed worth hiding since it wouldn't be in the right state.

**Comment by kennykerr** [comment]
Thanks David and sorry for the delay in commenting on this issue. I'm a little reluctant to add code gen to support `std` shared and weak pointers as it adds considerable code gen and I'm just not sure whether this is something that would be widely used. Note that you can use a lambda to create a delegate  and the lambda can easily capture whatever is required including `std` shared or weak pointers. Given there is a simple workaround, what do you say about using that approach until such time as we find more users that would commit to using this feature.

**Comment by davidmatson** [comment]
@kennykerr - thanks for the reply! Sure, if we don't think this functionality would be widely used yet, keeping code gen smaller makes sense. I was thinking it would be fairly common for other types to subscribe to WinRT events, not just types that are themselves WinRT APIs. I thought I'd seen the recommendation to make types WinRT types only when necessary - i.e., don't add the extra overhard/complexity of an ABI except where it's needed. So I am a little surprised that only types that are themselves WinRT APIs would commonly be subscribing to WinRT events, but if that's what happens in practice today, waiting makes sense.

I think the biggest drawback at the moment is that the existing codegen + docs doesn't make it easy to figure out what to do if the type subscribing to the event isn't itself a WinRT API but wants to call a non-static member function. Putting some guidance on the docs site would be enough to resolve that drawback.

I think you're suggesting using a lambda to handle the weak_ptr part inline in the statement that subscribes to the event, rather than using a derived event handler type to encapsulate the weak_ptr handling. Is that correct? Something like this?

```c++
static void Initialize(std::shared_ptr<ConsoleNetworkWatcher> instance)
{
    auto weakPointer{ std::weak_ptr{ instance } };

    instance->m_statusChangedRevoker =
        winrt::Windows::Networking::Connectivity::NetworkInformation::NetworkStatusChanged(winrt::auto_revoke,
            [weakPointer](winrt::Windows::Foundation::IInspectable const& sender)
            {
                auto sharedPointer{ weakPointer.lock() };

                if (sharedPointer)
                {
                    sharedPointer->NetworkStatusChanged(sender);
                }
            });
}
```

If so, having something like that in the in the [use a member function as a delegate](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/weak-references#if-you-use-a-member-function-as-a-delegate) section would be great.


Thanks for your help!

**Comment by kennykerr** [comment]
@stevewhims for the documentation suggestion. Thanks all!

**Comment by stevewhims** [comment]
I've created a work item for myself for the documentation suggestion. Thanks! :)
