### ISSUE TITLE
Including <windows.graphics.interop.h> after <winrt/base.h> causes failure to inherit from interface

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/cppwinrt#638]
If `#include <windows.graphics.interop.h>` is included after any WinRT header, the following error is generated when trying to implement `ABI::Windows::Graphics::IGeometrySource2DInterop`.

> GeometrySource2D.h(17): error C3668: 'GeometrySource2D::GetGeometry': method with override specifier 'override' did not override any base class methods
GeometrySource2D.h(18): error C3668: 'GeometrySource2D::TryGetGeometryUsingFactory': method with override specifier 'override' did not override any base class methods

To reproduce, include the following code in an empty cpp.

```
#define GENERATE_COMPILE_ERROR 1

#if GENERATE_COMPILE_ERROR
#include <winrt/Windows.Graphics.h>
#include <windows.graphics.interop.h>
#else
#include <windows.graphics.interop.h>
#include <winrt/Windows.Graphics.h>
#endif

struct GeometrySource2D : winrt::implements<GeometrySource2D,
                                            winrt::Windows::Graphics::IGeometrySource2D,
                                            ABI::Windows::Graphics::IGeometrySource2DInterop>
{
	IFACEMETHODIMP GetGeometry(ID2D1Geometry** value) override;
	IFACEMETHODIMP TryGetGeometryUsingFactory(ID2D1Factory* factory, ID2D1Geometry** value) override;
};
```

The problem can be alleviated by `#include <unknwn.h>` before any WinRT header, but this isn't an obvious step.

**Comment by kennykerr** [comment]
The C++/WinRT library does not rely on the Windows SDK headers for `IUnknown` and will compile without it, but in order to support interop you need to include `unknwn.h` before including any C++/WinRT headers otherwise it doesn't recognize it as a valid interface.

**Comment by MarkIngramUK** [comment]
Thanks @kennykerr , I was aware of the requirement for `unkwn.h`, but I was more querying whether it would be possible to have improved diagnostics for this situation (similar to when you attempt to use a `winrt::com_ptr<ID3Dxxx>). As when using the `override` keyword, you get a confusing error message about no method to override, and without the `override` keyword the program will build with no errors, and run, but your function(s) will never be called.

**Comment by kennykerr** [comment]
Ah, thanks for clarifying. Nothing comes to mind, but feel free to share a solution if you think of something.
