### ISSUE TITLE
Co_awaiting apartment_context from another STA causes RO_E_BLOCKED_CROSS_ASTA_CALL

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#639]
In an application with multiple CoreDispatchers, using apartment_context as recommended in the docs can cause RO_E_BLOCKED_CROSS_ASTA_CALL when trying to switch from one dispatcher to the other.

**Comment by kennykerr** [comment]
Had a chat with Johan. We're going to close this issue for now and revisit when we have more to share.
