### ISSUE TITLE
Correct way to declare enum in idl as function's parameter

### ISSUE THREAD

**Issue by petercoin** [microsoft/cppwinrt#646]
Hi,
I am not sure if it is ok to post the question here.
I am trying to author a function which takes enum as a parameter.
I declared the enum in both of .h and .idl file.
However, when I tried to build the project, the compiler shew
```
C2664: cannot covert argument 1 from 'const winrt::mylib::myenum to 'winrt::mylib::implmentation::myenum'
```
to Error List window.

The Output window shew
```
'Conversion to enumeration type requires an explicit cast'.
```
The enum in idl is as below:
```
namespace mylib
{
    enum myenum
    {
        cat1 = 0
    };

    [default_interface]
    runtimeclass mylib
    {
        mylib();
    }
}
```

The enum in header is as below:
```
namespace winrt::mylib::implementation
{
    enum class myenum : int32_t
    {
        cat1 = 0
    };

    struct mylib : mylibT<mylib>
    {
    public:
        mylib() = default;
        Boolean foo(myenum category);
    }
}
```

The auto generated code is as below:
```
*result = detach_from<bool>(this->shim().foo(*reinterpret_cast<mylib::myenum const*>(&category)));
```

Could someone help me to figure out the root cause?

**Comment by kennykerr** [comment]
After a WinRT enum is defined in .idl and midlrt produces a .winmd for it, the cppwinrt compiler will generate the C++ definition. In your example you would merely need to include the `winrt/mylib.h` header to include the definition. 

https://stackoverflow.com/ is generally a better place to ask general questions.
