### ISSUE TITLE
Activation Hook: Need to load WinRT class instance from LoadPackagedLibrary

### ISSUE THREAD

**Issue by mjfusa** [microsoft/cppwinrt#649]
Prior to the latest C++/WinRT update (16.6.1), I was able to hook activation by implementing WINRT_RoGetActivationFactory and loading my WinRT class using LoadPackagedLibrary, expanding on the technique used here: https://cc.bingj.com/cache.aspx?q=OS_RoGetActivationFactory&d=4572400899654277&mkt=en-US&setlang=en-US&w=iZuV8U12DMQfSZVgRHk6exGbUOEFzZ8f
Can I still do this using the new winrt_get_activation_factory()? 

I need a way to create an instance of a class at runtime that is in a dll.

**Comment by kennykerr** [comment]
Hi Mike, if you really need to hook activation you can use [winrt_activation_handler](https://github.com/microsoft/cppwinrt/pull/477/files), but you shouldn't need to do so in most cases. 

Packaged apps no longer require the use of `LoadPackagedLibrary` and you can simply use `LoadLibrary`. And if you follow the recommended convention of using the namespace of your API to name your DLL then newer language projections like C++/WinRT will automatically find and load your DLL without requiring you to hook activation at all.

When you have a class named "A.B.TypeName" it should be contained in a DLL called A.B.dll - or at least A.dll - this allows language projections to activate non-system APIs without requiring the developer to provide manifest/registration information. Specifically, both C++/WinRT and Rust/WinRT use this heuristic to find the component DLL when `RoGetActivationFactory` fails.

**Comment by mjfusa** [comment]
Thanks for the quick reply. That's perfect. 
If I have Namespace::Class the dll would be Namespace.Class.dll, correct?
What's the best way to instantiate the object this way?
Do you know of a sample demoing this? If not I can provide a gist based on your answers.

**Comment by kennykerr** [comment]
> If I have Namespace::Class the dll would be Namespace.Class.dll, correct?

No, if you have a `Namespace::Class` then the dll would be `Namespace.dll`. The assumption is that there may be a few different classes within the same dll.

> What's the best way to instantiate the object this way?

Just make sure the dll is in the same location as the executable and it should "just work" via the C++/WinRT generated constructors and statics.
