### ISSUE TITLE
Can't compile base.h with memory leak detection turned on.

### ISSUE THREAD

**Issue by rui-rebelo** [Microsoft/cppwinrt#65]
To find memory leaks from the 'new' operator, [Microsoft suggests to redefine it through the preprocessor](https://msdn.microsoft.com/en-us/library/x98tx3cf(v=VS.100).aspx) using this:

`
#ifdef _DEBUG

   #ifndef DBG_NEW

      #define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )

      #define new DBG_NEW

   #endif

#endif  // _DEBUG
`

However, that brakes the compiling of base.h on line 2310:
`	void * operator new(size_t) = delete;`

with the errors: C2059 (syntax error 'constant'), C2091 (function returns function) and C2802 (static member operator 'new' has no formal parameters).

I surrounded that line on base.h with `#ifndef _DEBUG`, to remove it from compilation and everything _seems_ to be working fine.

However I know I'll get into trouble. Does anyone know what dangers lie ahead? Is there any safer workaround on this?

**Comment by kennykerr** [comment]
That is a terrible recommendation and I’ll get the MSDN folks to remove it. It is non-standard and ill-advised to redefine C++ keywords with macros. 

The `new` keyword is used in a host of expressions, particularly in modern C++ that would not be compatible with such preprocessor hacking.

**Comment by rui-rebelo** [comment]
Thank you Kenny.

I'll disable the MSDN hack and see what they suggest instead.

**Comment by kennykerr** [comment]
[MSDN has been updated](https://msdn.microsoft.com/en-us/library/x98tx3cf(v=vs.140).aspx).

**Comment by rui-rebelo** [comment]
Nice!

Thank you Kenny.
