### ISSUE TITLE
Add the ability for static lifetime store to be explicitly cleared

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#651]
in the case of a Win32 service that uses the static lifetime store (using [`static_lifetime`](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/static-lifetime)) we need to respond to the service shutdown request and un-register our factories. to do this we need to be able to clear the entry in the static lifetime store

**Comment by kennykerr** [comment]
The static lifetime store is designed to clear itself when the last apartment is torn down. Is this not working?

**Comment by oldnewthing** [comment]
The issue here is a shared service. One service needs to clean up all its COM objects, but other services are still using COM. I am working on a PR to address this specific scenario.
