### ISSUE TITLE
get_self does not detect ambiguous IInspectable usage

### ISSUE THREAD

**Issue by oldnewthing** [microsoft/cppwinrt#652]
I choose `IClosable` because it's a small interface with just one method.

```cpp
struct Sample : implements<Sample, IClosable, IInspectable>
{
  void Close(){}
  int magic = 42;
};

void test()
{
    auto s = winrt::make_self<Sample>();
    {
        winrt::IInspectable insp = *s;
        auto x = winrt::get_self<Sample>(insp);
        WINRT_ASSERT(x->magic == 42); // okay
    }

    {
        winrt::IClosable cl = *s;
        winrt::IInspectable insp = cl;
        auto x = winrt::get_self<Sample>(insp);
        WINRT_ASSERT(x->magic == 42); // fail
    }
```

This tries to recover the `Sample` from the `IInspectable`, but if the `IInspectable` came from `IClosable`, the `get_self` assumes that the `IInspectable` came from the explicitly-implemented `IInspectable`.

In regular C++, you (sometimes) get a compiler error when this occurs:
```cpp
struct B {};
struct D : B {};
struct C : D, B {};

C* c = whatever;
B* b = c; // error: ambiguous base class B (from gcc and clang; MSVC is silent)
```

But C++/WinRT fails to detect this case, potentially resulting in frustrating memory corruption bugs.

Options:

* Detect the ambiguity and raise a warning (not sure how).
* Detect the ambiguity and raise a compiler error.
* Detect the ambiguity and resolve it by explicitly QI'ing for the default interface.
* Something else.

**Comment by kennykerr** [comment]
Yes, `get_self` was designed to be used with an unambiguous interface. There are of course ways to abuse this even in such a case. You might have a non-exclusive interfaces (or an exclusive interface implemented by someone else anyway) and `get_self` will not know the difference. It is an implementation trick that comes with some risk.

**Comment by oldnewthing** [comment]
The problem is that a common case is that you want to recover your implementation of some data you hung off a XAML object, like a `Tag`, and `Tag` uses `IInspectable`, so the common case is that you want to recover an implementation from `IInspectable`, and `IInspectable` is exactly the interface that is problematic. I think I might be able to metaprogrammatically detect the ambiguous `IInspectable` and add an explicit QI to work around it.

**Comment by oldnewthing** [comment]
Okay, this isn't as bad as it looks, because you run into this problem only if you do something inadvisable in the first place, which is listing `IInspectable` as an explicit implemented interface. So maybe the thing to do is just raise a build break if you try to use `get_self` on such a poorly-formed class. Working on it.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
