### ISSUE TITLE
Update class factory cache to detect rundown of remote factories and re-create

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#653]
C++ WinRT caches agile factories. When the factory is remote, implemented in a win32 service, and that service is shutdown, calls on it will throw “RPC server is unavailable”. Since these services will auto-start attempts to re-bind will succeed. 

The factory cache should detect this case, release the bad factory and try again.

This is similar to the support in event delegates that detect RPC server is unavailable and remove the delegate from the event collection.

**Comment by kennykerr** [comment]
As a workaround, callers can detect the failure and call `winrt::clear_factory_cache` to clear the cache. The next time a request is made, a new factory pointer will be cached.

**Comment by ChrisGuzak** [comment]
#654 provides a work around

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
