### ISSUE TITLE
BreakPad for WinRT C++ Crash Analysis?

### ISSUE THREAD

**Issue by mjfusa** [microsoft/cppwinrt#658]
AppCenter doesn't have direct support for capturing crash information for WinRT apps. However they recommend using BreakPad and the App Center upload API to upload the captures to AppCenter for viewing.
Docs: [Unmanaged Code Crash Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/unmanaged-code-crash-support)

Is this the recommended approach for capture crash information for WinRT C++ apps?

**Comment by kennykerr** [comment]
Mike, I hope you found a way to capture a dump. I know Visual Studio has a way to capture dumps from running processes. This is not specific to C++/WinRT. Any tooling for Visual C++ will work with C++/WinRT.
