### ISSUE TITLE
how to translate cpp/cx code (runasync dispatchedhandler )

### ISSUE THREAD

**Issue by gettf** [Microsoft/cppwinrt#66]
pls help translate following code:		
```C++
               // Associate swap chain with SwapChainPanel
		// UI changes will need to be dispatched back to the UI thread
		m_swapChainPanel->Dispatcher->RunAsync(CoreDispatcherPriority::High, ref new DispatchedHandler([=]()
		{
                        // skip!!
			// Get backing native interface for SwapChainPanel
			//ComPtr<ISwapChainPanelNative> panelNative;
			//DX::ThrowIfFailed(
			//	reinterpret_cast<IUnknown*>(m_swapChainPanel)->QueryInterface(IID_PPV_ARGS(&panelNative))
				//);

			//DX::ThrowIfFailed(
			//	panelNative->SetSwapChain(m_swapChain.Get())
			//	);

		}, CallbackContext::Any));
```

**Comment by KevinWelton** [comment]
It's not clear to me what the intent of the code is. Most code is commented out. Please make an attempt at writing the CPP/WinRT version and let us know if you need further help.

**Comment by gettf** [comment]
i mean: how to make a DispatchedHandler instance and  use CallbackContext::Any parameter.
please write cpp/winrt code. thanks

**Comment by kennykerr** [comment]
You can create and run a callback (handler) on the UI thread as follows.

```C++
CoreDispatcher dispatcher = ...

dispatcher.RunAsync(CoreDispatcherPriority::Normal, []
    {
        // handler ...
    });
```

**Comment by gettf** [comment]
thanks, then how to control context ,  run in threadpool thread

**Comment by kennykerr** [comment]
That's up to the dispatcher, not the handler. You might use the ThreadPool class to execute a delegate on the thread pool as follows:

```C++
using namespace Windows::System::Threading;

ThreadPool::RunAsync([](IAsyncAction const &)
    {
        // handler ...
    });
```

For a more flexible and efficient way of dispatching work in the appropriate context I suggest you [take a look at coroutines](https://www.youtube.com/watch?v=v0SjumbIips).

**Comment by gettf** [comment]
thanks kk, wish ver 1 realese asap. Will we wait half year or more?

**Comment by kennykerr** [comment]
We won't keep you waiting that long for an update.
