### ISSUE TITLE
Slow build time

### ISSUE THREAD

**Issue by hasaranga** [microsoft/cppwinrt#664]
Created an empty C++/WinRT desktop(Win32) application project. First build took a long time. And then I closed the VS and then opened the project again. Again the build time too slow for the first build. Nearly 3 minutes.

Why taking so much time for the first build after opening the project every time?

VS 2019 Community v16.6.2
Win10 1909

**Comment by hasaranga** [comment]
While typing the code, "C++ Background Code Analysis" runs in background forever! Seems to be an IntelliSense issue.

![wint](https://user-images.githubusercontent.com/3483400/84584261-af826900-ae1f-11ea-93e6-fb321d82d9a6.png)

**Comment by kennykerr** [comment]
Hey there, sorry you're running into trouble here. The Visual Studio team owns the toolchain including code completion and static analysis engines. They'd love to hear from you here:

https://developercommunity.visualstudio.com/spaces/62/index.html
