### ISSUE TITLE
Version information shouldn't require hand-parsing

### ISSUE THREAD

**Issue by jonwis** [microsoft/cppwinrt#668]
Per https://task.ms/26741093 - `CPPWINRT_VERSION` is a string. Could it also be a four-part structure?

```c++
struct cppwinrt_version_t {
    uint16_t major;
    uint16_t minor;
    uint16_t release;
    uint16_t build;
};
constexpr cppwinrt_version_t get_cppwinrt_version() {
    return { 2, 0, 20609, 3 };
}
```

**Comment by Scottj1s** [comment]
Note that this versioning scheme isn't SemVer-compliant.  You may want to consider restructuring it before locking it in further.

**Comment by kennykerr** [comment]
Version APIs are hard. 😉 

WIL uses this to light up feature support depending on the version of C++/WinRT it is being included with. The trouble with adding a new function is that this function won't exist in older versions and thus prevent WIL from using it.

Feel free to reopen if there's interest in exploring this further.
