### ISSUE TITLE
Component projection templates don't support COM interface implementations

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#670]
Using the [example from the docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-coclasses) with a component template fails (no interface):
    struct Class : ClassT<Class, IInitializeWithWindow>

The same with a direct implements succeeds:
    struct Class : implements<Class, IInitializeWithWindow>

In both cases, unknwn.h is #included before anything else in pch.h

**Comment by Scottj1s** [comment]
The implemented_interfaces expansion is failing to include the COM interfaces in the failing case, and I have no idea how to debug the template machinery.

**Comment by kennykerr** [comment]
Hey Scott, I can't repro. The following works for me:

```C++
#include <Shobjidl.h>
#include <winrt/base.h>

struct Type : winrt::implements<Type, IInitializeWithWindow>
{
    HRESULT STDMETHODCALLTYPE Initialize(HWND) override
    {
        return S_OK;
    }
};

int main()
{
    winrt::com_ptr<IInitializeWithWindow> init =
        winrt::make<Type>();

    init->Initialize(nullptr);
}
```

**Comment by Scottj1s** [comment]
Yes, that works for me too - direct implements call.  It's the component template scenario that fails.

**Comment by kennykerr** [comment]
What compiler error are you seeing? Just including `Shobjidl.h` into the C++/WinRT component project introduces a compiler error for me:

```
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19028.0\um\shobjidl_core.h(31712,18): error C2061: syntax error: identifier 'SHGDNF'
``` 

If I instead include `objidl.h` I can then add an implementation of `IPersist` to the component's `Class` implementation without any trouble:

```C++
namespace winrt::RuntimeComponent2::implementation
{
    struct Class : ClassT<Class, IPersist>
    {
        Class() = default;

        int32_t MyProperty();
        void MyProperty(int32_t value);

        HRESULT STDMETHODCALLTYPE GetClassID(CLSID*)  override
        {
            return S_OK;
        }
    };
}
```

So depending the error you ran in to, it may have something to do with the `Shobjidl.h` header and not with implementing COM interfaces.

**Comment by kennykerr** [comment]
Including `Shobjidl.h` into C++/WinRT's test component and implementing `IInitializeWithWindow` works without a hitch.

It may have something to do with the fact that the C++/WinRT project templates define `WINAPI_FAMILY=WINAPI_FAMILY_APP`. I have no idea why they're doing that though. I've never been a fan of that partitioning stuff - it just gets in the way.

**Comment by kennykerr** [comment]
I would just avoid the pesky Windows SDK headers and define it directly:

```C++
MIDL_INTERFACE("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")
IInitializeWithWindow : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE Initialize(HWND hwnd) = 0;

};

namespace winrt::RuntimeComponent2::implementation
{
    struct Class : ClassT<Class, IInitializeWithWindow>
    {
        Class() = default;

        int32_t MyProperty();
        void MyProperty(int32_t value);

        HRESULT STDMETHODCALLTYPE Initialize(HWND hwnd) override
        {
            return S_OK;
        }
    };
}
```

**Comment by kennykerr** [comment]
We should also figure out how to remove the WINAPI partitioning so that a C++/WinRT component can use any Win32 API.

**Comment by Scottj1s** [comment]
The error is a 0x80004002 (E_NOINTERFACE) when attempting to cast via `as<IInitializeWithWindow>`.

**Comment by kennykerr** [comment]
I had no idea you were referring to the query failing. That's why a repro is handy. 😉

**Comment by Scottj1s** [comment]
Sorry - mentioned "(no interface)" but I guess that wasn't clear.

**Comment by kennykerr** [comment]
Still can't repro. Added an `IInitializeWithWindow` implementation to the existing test component as follows:

```C++
namespace winrt::test_component::implementation
{
    struct Class : ClassT<Class, IInitializeWithWindow>
    {
        Class() = default;
        Class(hstring const&) {}

        HRESULT STDMETHODCALLTYPE Initialize(HWND) override
        {
            return S_OK;
        }
.
.
.
```

Added a test as follows:

```C++
TEST_CASE("com_interop")
{
    Class object;

    auto init = object.as<IInitializeWithWindow>();

    REQUIRE(init);
    REQUIRE(get_abi(object) != get_abi(init));

    init->Initialize(nullptr);
}
```

Stepped through it. Everything is working. 

Would love to see a repro. 😊

**Comment by Scottj1s** [comment]
Hmm, sorry for randomizing - I can no longer repro myself now.  May have been some VS build dependency issue with the pch.  I restored the few lines in class.h and my unit test, did a rebuild as before, and now I'm seeing the COM interfaces in the implemented_interfaces intantiation. Sigh...
