### ISSUE TITLE
Audio Stream Routing

### ISSUE THREAD

**Issue by UtkarshBhatthere** [microsoft/cppwinrt#672]
Hey, I was working on a project where I have to pick an Audio Stream (say the Audio from a YT video running or chrome or from a Game that I am playing) and feed it into my Audio Processing Code without disturbing the Audio being played on a Hardware Device (say a speaker or a Headset). From what I have been able to understand I'll have to use Windows.Media.Stream along with Windows.Media.Audio (Input and Output nodes). I.E. an audio mixer kind of setup where the original stream is being put out to 1.) The original Audio Output Device and 2.) My Audio Processing Code. I am well versed with Cpp but new to Windows Development. Can anyone help?

**Comment by kennykerr** [comment]
This repo is for the tool that generates the C++ bindings for WinRT APIs. We don't have any specific knowledge or experience with individual APIs. I think you'll have better luck posting the question on https://stackoverflow.com/
