### ISSUE TITLE
Implement upcoming STL C++20 coroutines support

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#676]
The Microsoft STL has recently merged non-experimental coroutine support: https://github.com/microsoft/STL/pull/894

This support, once shipped (expected around 16.8 preview 1), will prevent mixing code using the new coroutines and the experimental ones.

Using the `/await` command line (which is forced in various places by the C++/WinRT project files) will prevent including `<coroutine>`, telling you to use `<experimental/coroutine>`. Similarly, using the `/std:c++latest` command line (my code makes use of many new C++ 20 only features), will prevent including `<experimental/coroutine>`, telling you to instead use `<coroutine>`.

This puts me in a weird spot: I can't include `<coroutine>` because C++/WinRT uses `<experimental/coroutine>` and `/await`, but neither can I include `<experimental/coroutine>` because I use `/std:c++latest`.

Ideally, the C++/WinRT headers should detect the presence of C++20 coroutines (using `__cpp_impl_coroutine`) and use the right header. Additionally, the project files should not force `/await` in VS 16.8 and newer, or provide a way to opt-out from this behavior.

**Comment by kennykerr** [comment]
Yes, it might soon be time to create a C++17 branch for servicing and then switch master over to C++20. I'd like to avoid supporting both C++17 and C++20 as it can become quite complex especially since Clang and Visual C++ are never quite in line.

**Comment by DefaultRyan** [comment]
It looks like you're saying VC++ in C++17 mode does not define `__cpp_impl_coroutine`. Did I read that correctly?

**Comment by sylveon** [comment]
https://github.com/microsoft/STL/blob/21acd23ad81463628e95cb6c571c56ba7200cdba/stl/inc/yvals_core.h#L1162-L1164

https://github.com/microsoft/STL/blob/21acd23ad81463628e95cb6c571c56ba7200cdba/stl/inc/coroutine#L12-L21

Yes

**Comment by sylveon** [comment]
It happened, VS 16.8 Preview 1 is out and my code doesn't compile anymore:

![image](https://user-images.githubusercontent.com/6440374/89701538-e481d800-d905-11ea-9efc-5adc1a24c864.png)

**Comment by sylveon** [comment]
Looks like `__cpp_impl_coroutine` isn't defined yet so existing code using `<experimental/coroutine>` will build fine (once this is defined `<experimental/coroutine>` will stop working with `/std:c++latest`), but trying to use `<coroutine>` anywhere else will fail because of the C++/WinRT props file forcing `/await`

**Comment by AlexBAV** [comment]
Now VS 16.8 Preview 3.0 is out with "full C++20 coroutines support".
What is the ETA of WinRT support for conformant coroutines?
What is the recommended (if any) way to switch own code to C++20 coroutines and still use the current version of WinRT?

**Comment by kennykerr** [comment]
I've been away for a few weeks but should be back in the "office" next week and plan to take a look at 16.8 support.

**Comment by DethRaid** [comment]
Subscribed to this issue because I'm also blocked by it

**Comment by kennykerr** [comment]
The C++/WinRT library has been updated to support both C++17 and C++20 coroutines.

**Comment by DethRaid** [comment]
Can confirm that I'm now un-blocked. Thank you so much!

**Comment by mauriceackel** [comment]
Hi @kennykerr,

I was just trying to build my C++/WinRT header (which I have created using `cppwinrt.exe -input local -output .`) with c++20. However, there seems to be an obvious error with this. My `base.h` header includes the passage:

```
#ifndef __clang__

#include <experimental/coroutine>

#else
...
```

Which will try to include `<experimental/coroutine>` as I compile with MSVC.

My `cppwinrt.exe` version is `C++/WinRT v2.0.200203.5`. I'm a bit confused at the moment given that some people reportedly were able to successfully compile with c++20... Do you perhaps see where the issue is?

**Comment by sylveon** [comment]
That cppwinrt version is super old, it seems to be from around February 2020. Try the NuGet for an up to date version.
