### ISSUE TITLE
It would be nice if winrt::com_ptr had a member function like Microsoft::WRL::ComPtr::as

### ISSUE THREAD

**Issue by smj389** [Microsoft/cppwinrt#68]
The advantage of that one is that you can pass another ComPtr (or in this case any cppwinrt object) and it would deduce the type for the Query Interface. Instead of doing this

```
com_ptr<SomeType> ptr1;

ptr1 = ptr2.as<SomeType>();

```
You could just do this

ptr2.as(put(ptr1));

**Comment by gettf** [comment]
needs: reset or =(nullptr), releaseandgetaddressof

**Comment by KevinWelton** [comment]
smj389, the code in your original comment won't compile as is. Assuming you mean something like

```
com_ptr<IDerived> ptr_derived;
ptr_base = ptr_derived.as<IBase>();
```

In this case, you can simply use
```
ptr_base = ptr_derived;
```

**Comment by smj389** [comment]
I think it removed my template arguments (it must have thought they were tags or something.)

I did mean something like that only I was referring to the case where the two interfaces are not related by inheritance so you need to do a QI to get the new interface (which is what as does).

```
com_ptr<IInterface1> ptr1;
com_ptr<IInterface2> ptr2;

ptr2 = ptr1.as<IInterface2>();

```

**Comment by KevinWelton** [comment]
I see. Thanks for the clarification.

In the case of our com_ptr class, we have specifically avoided using an out parameter in com_ptr<T>::as<U>(). We are avoiding the COM pattern of having return values as out params where we can.

A few more words on using put() to get the raw pointer like in the alternative as() call you mentioned, This presents the developer with a couple of problems you should be aware of, the behavior of which may not be totally obvious:

1. In debug builds, put() requires the underlying pointer of a com_ptr<T> object to already be nullptr
2. In retail builds, if we had an overload like the one you mentioned and the underlying pointer to the com_ptr<T> parameter is **not** nullptr, then the the pointer value would get overwritten without the previous object having been freed, causing a leak.

The short of it is that put() is primarily intended as a way to inter-operate with COM classes at the ABI layer. Be careful using it elsewhere.

**Comment by smj389** [comment]
I see. The advantage I'm seeking is template type deduction for the case when you want to QI to an interface for which a com_ptr has already been declared. 
Essentially a short hand for:


```
com_ptr<IType1> x;
com_ptr<IType2> y;

y = x.as<decltype(y)::type>();

```

The specific use case I have in mind is something like this:
I have member variables:

```
Compositor comp_ { nullptr };
com_ptr<::ABI::Windows::UI::Composition::ICompositorInterop> interop_ { };

```

I then have code like this:

```
	comp_ = Compositor { };
	interop_ = comp_.as <decltype( interop_ )::type> ();

```

It would be convenient to be able to write (as in WRL):

`	comp_.as (&interop_);
`

**Comment by kennykerr** [comment]
As Kevin mentioned, we have made a deliberate design choice to avoid out parameters (with pointer types). Having said that, we could conceivably add an overload of the `as` member to handle this quite elegantly:

```C++
template <typename To>
void as(com_ptr<To> & to)
{
    to = as<To>();
}
```

Of course, this is just C++ and you can easily write a little helper function to do what you desire today:

```C++
template <typename From, typename To>
void as(From const & from, com_ptr<To> & to)
{
    to = from.as<To>();
}
```

Thanks for the suggestion!

**Comment by BrentRe** [comment]
I created a bug to track this request internally.
