### ISSUE TITLE
Suggest a small improvement to VSIX generated code for C++/WinRT Blank App

### ISSUE THREAD

**Issue by MRahilly** [microsoft/cppwinrt#684]
The event handler should be prototyped as:
    void ClickHandler(winrt::Windows::Foundation::IInspectable const&, Windows::UI::Xaml::RoutedEventArgs const&);
rather than:
    void ClickHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::RoutedEventArgs const& args);

**Comment by kennykerr** [comment]
Can you elaborate on why this would be an improvement?

**Comment by MRahilly** [comment]
I should have written: give the full namespace for the type in a header file
- rather than an improvement.
