### ISSUE TITLE
Minor typos in doc Migrating C++ CX source code to C++ WinRT.md

### ISSUE THREAD

**Issue by 40tude** [Microsoft/cppwinrt#69]
Bonjour
Very quick
1 - Search for "CX++/WinRT" and replace with "C++/WinRT"
2 - Search for "esultTask" and replace with "ResultTask"

Many many thanks for the job done.
Best regards, Philippe

**Comment by KevinWelton** [comment]
Thanks for the feedback. I've updated the doc :)
