### ISSUE TITLE
make<> and make_self<> do not support array

### ISSUE THREAD

**Issue by anup-das** [microsoft/cppwinrt#693]
I am trying to instantiate an array of runtime class objects such that they are in consecutive memory locations for performance

winrt::make<T [ ]>( element count ) or
winrt::make_self<T [ ]>( element count )

do not work. std::make_unique<T [ ]>( element count ) works with the same syntax.
I can't find a way to instantiate an array; maybe this is by design - but if it is then its a severe limitation from performance perspective

**Comment by kennykerr** [comment]
The `winrt::make` and `winrt::make_self` functions are not meant to be used for creating arrays of objects. If you need a heap-allocated contiguous container I'd suggest `std::vector<T>` (or `winrt::com_array<T>` if you need to pass it across an ABI boundary).

**Comment by anup-das** [comment]
> The `winrt::make` and `winrt::make_self` functions are not meant to be used for creating arrays of objects. If you need a heap-allocated contiguous container I'd suggest `std::vector<T>` (or `winrt::com_array<T>` if you need to pass it across an ABI boundary).

I tried using std::vector<T> where T is an runtime class type. I get an error T is abstract ...use_make_function_to_create_this_object(void)': is abstract

same with winrt::com_array<T> - can you kindly tell me how it should be done ?
