### ISSUE TITLE
DateTimeFormatter strings break std::wcout

### ISSUE THREAD

**Issue by Greyze** [microsoft/cppwinrt#694]
Hi All. Firstly sorry if this is user error, I can't find an example on the internet to learn from.

I'm experimenting with C++/WinRT and the project setup is:

Project Type: Windows Console Application (C++/WinRT)
Windows SDK Version: 10.0.18362.0
Platform Toolset: Visual Studio 2019 (v142)
Build: x64 (debug or release)
No Common Language Runtime Support

I'm having a problem with strings that come from the DateTimeFormatter class.
Every winrt::hstring i've come across I have no problem with using and printing with std::wcout, but any string I get from DateTimeFormatter is impossible to print, I either get nothing or garbage. EG:

	winrt::hstring hello{ L"Hello World" };
	winrt::hstring goodbye{ L"Goodbye Universe" };

	std::wstring strs{ hello + L" and "+ goodbye };

	// Works
	std::wcout << hello.c_str() << L"\n";
	std::wcout << strs.c_str() << L"\n";

	winrt::Windows::Foundation::DateTime dt = winrt::clock::now();
	const auto strLongTime = DateTimeFormatter::LongTime().Format(dt);

	// Fails: prints nothing
	std::wcout << strLongTime.c_str() << L"\n";
	// Fails: prints garbage. EG: ÔÇÄ12ÔÇÄ:ÔÇÄ23ÔÇÄ:ÔÇÄ01ÔÇÄ ÔÇÄPM  
	std::cout << winrt::to_string(strLongTime) << "\n";

Visual Studio shows strLongTime has a valid value in debug mode too. It looks like a completely valid string just like any other working hstring.

![delete](https://user-images.githubusercontent.com/1690930/87781861-5eec9a00-c829-11ea-85ec-8d1bbe7e2a47.png)

Or if what i'm doing simply can't be done can someone suggest an alternative way to print the datetime or store it in a std::wstring?

Thanks

**Comment by DefaultRyan** [comment]
The code is working as designed. The source of your pain is that the DateTimeFormatter class puts [left-to-right](https://en.wikipedia.org/wiki/Left-to-right_mark) and [right-to-left](https://en.wikipedia.org/wiki/Right-to-left_mark) marks in the output string.

You're not the first one to be tripped up by this behavior, as these 7-8 year old posts attest:
- https://social.msdn.microsoft.com/Forums/en-US/0345aee8-1ca7-4716-97ae-9fe288e0e70f/datetimeformatter-bug
- https://stackoverflow.com/questions/12747413/datetimeformatter

One suggestion I've seen in response to this is to remove the marks. This can be done either before or after copying to a `std::wstring`
```
inline constexpr bool is_bidi_marker(wchar_t wc)
{
    return wc == 0x200e || wc == 0x200f;
}

std::wstring cleaned = strLongTime.c_str();
cleaned.erase(
  std::remove_if(cleaned.begin(), cleaned.end(), is_bidi_marker,
  cleaned.end());

std::wstring cleaned2;
std::copy_if(strLongTime.begin(), strLongTime.end(), std::back_inserter(cleaned2),
  [](wchar_t wc) {return !is_bidi_marker(wc); });
```

**Comment by Greyze** [comment]
Fascinating problem.. didn't even know such markers existed. Thanks for the code samples! they put me in the right direction (it fixed the marker problem but also revealed another string issue :/)

It would have been great to avoid all of this and just the timestamp value directly alongside C++. I noticed the timestamp is Windows::Foundation::DateTime, which is just a typedef "DateTime = std::chrono::time_point<clock, TimeSpan>;"
But unfortunately I can't seem to interface that datetime value with the rest of std::chrono to convert it my own way.

Thanks for replying!

**Comment by DefaultRyan** [comment]
I'm curious to hear which issues you're having. The only thing that comes to mind is that it doesn't have clean wrappers to convert `winrt::clock::time_point` to `winrt::system_clock::time_point`.

C++20 brings some more comprehensive support for this via https://en.cppreference.com/w/cpp/chrono/clock_cast. As I look at how that's powered, I believe I can get `winrt::clock` essentially there by implementing the static members `from_sys(t)` and `to_sys(t)`.

I've opened #697 to add those members. Please let me know if there's some other trouble you're having with DateTime.

**Comment by Greyze** [comment]
Oh wow thanks for doing that!

You hit the nail on the head really. I expected it would have been an easy task to do that conversion but couldn't find an appropriate solution. That ticket is exactly what I needed :)

By the way, is there a more appropriate place to discuss C++ WinRT? I'd like to join a community where I could occasionally ask questions or get advice on this topic and I feel like making tickets here isn't appropriate.

**Comment by DefaultRyan** [comment]
Stackoverflow is reasonably active:
https://stackoverflow.com/questions/tagged/c%2b%2b-winrt
