### ISSUE TITLE
Modify Runtime Component project template to take advantage of converged VCLibs.UWPDesktop framework package 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#699]
The runtime component project template creates a Universal Windows dll, with linkage to UWP CRT binaries (vcruntime140_app.dll, etc).  To host such a dll in a Desktop app requires a reference to the VCRT Forwarders nuget, which provides adapters from vcruntime140_app.dll to vcruntime140.dll, etc.  Visual Studio will soon ship with a converged VCLibs.UWPDesktop framework package, which provides the complementary behavior.  A dll with desktop CRT linkage (vcruntime140.dll) can be hosted by a UWP app, with VCLibs.UWPDesktop providing forwarders in the opposite direction.  New runtime component projects should begin using this technique instead.

**Comment by weltkante** [comment]
I've been running into this problem, whats the right setup to author and consume a winrt library in a desktop application?

**Comment by Scottj1s** [comment]
Changing the runtime component template to link against the desktop CRT imports is not sufficient - consuming projects also need to reference the latest VCLibs.UWPDesktop.  So the C++/WinRT app template should also be updated.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
