### ISSUE TITLE
Using Xaml containers

### ISSUE THREAD

**Issue by Specter754** [Microsoft/cppwinrt#7]
I understand that using XAML markup is not supported in this release. However is it possible to use XAML containers in code. I tried using the Grid and StackPanel classes. I can create objects of those classes but it doesn't look like there is a way to add child controls to them. Is this an issue with the preview or am I doing something wrong?

**Comment by BrentRe** [comment]
Not sure if you asked the same question on the C++ team blog (where I replied). But let me put the answer here as well for the benefit of others. I've written this code off the top of my head but hopefully I didn't make too many typos:

using namespace winrt::Windows::UI::Xaml;
using namespace winrt::Windows::UI::Xaml::Controls;

StackPanel stackPanel;

stackPanel.HorizontalAlignment (HorizontalAlignment.Center); // Property set call of enum value

Button myMethodButton;
myMethodButton.Content (“myMethod”); // Property set

// Wire up an event handler
myMethodButton::Click([=] (auto const &&, auto const &&)
{
    MainPage::myMethod();
});

stackPanel.Children().Append( myMethodButton ); // Children is a propget – needs ()

**Comment by Specter754** [comment]
Thanks. I tried to use the Children member without calling it as a method. As a result the Append method wasn't showing up. With that change it works.
