### ISSUE TITLE
Can't do unit tests via VS's microsoft test when /std::c++latest flag active

### ISSUE THREAD

**Issue by rhenninger** [Microsoft/cppwinrt#70]
The real question is what pattern/framework are you recommending for unit testing parts of a larger project built via c++winrt?

I tried using VS's built-in test framework, but that won't compile when the /std::c++latest flag is set. collections.h, which is used in CppUnitTests.h, contains std::unary_function which is deprecated in C++11. Removing the /std::c++latest flag allows compilation until you reference a class using C++winrt then c++winrt starts complaining that nested-namespace-definition requires the /std::c++latest flag.

How should we be doing unit testing for now? Just simple main()'s with Assert's? Is there a framework that works currently within VS, or is this being addressed in VS2017?

**Comment by BrentRector** [comment]
Until collections.h is fixed to not used std::unary_function, you can always reenable unary_function by defining _HAS_AUTO_PTR_ETC=1 along with using /std:c++latest.

Collections.h may already be fixed in VS2017 but I don't have it handy to check.

**Comment by rhenninger** [comment]
@BrentRector Thanks for the info.  It failed at first with new errors, but by removing the /d1permissive- flag which is present in the Samples vcxproj files we are supposed to use as a base, it finally did work.  Is the /d1permissive- flag needed for c++winrt to work right? No adverse symptoms have yet to surface by removing it from a unit test process.  I'll be on the lookout for run-time trouble.

**Comment by kennykerr** [comment]
The permissive flag (/permissive- in Visual Studio 2017) is optional. The flag helps you avoid non-standard C++ but is not itself required by C++/WinRT.

**Comment by rhenninger** [comment]
@kennykerr Good to know. Thanks. Light XAML, UI Composition C++winrt and MSTest now all seem to be playing nice with each other.  Feel free to close this unless you want a use it as a flag to verify that VS2017's MSTest works out of the box with c++winrt.
