### ISSUE TITLE
Question: Does hstring create a copy when constructing from a wchar_t?

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#701]
In C++/CX, creating a Platform::String^ from wchar_t* would always create a copy since WinRT strings are immutable and are reference counted. Is this the same with C++/WinRT's hstring type or does it do something similar to Platform::StringReference?

**Comment by kennykerr** [comment]
C++/WinRT automatically uses string references (that don't copy) for string input parameters whenever possible. You can explore the implementation here:

https://github.com/microsoft/cppwinrt/blob/master/strings/base_string_input.h

Note that this is done in such a way that callers don't have to think about this optimization. You should never try to force it by using the `winrt::param` types directly.
