### ISSUE TITLE
Implement support for synchronous coroutines as IIterable<T>.

### ISSUE THREAD

**Issue by jkoritzinsky** [microsoft/cppwinrt#705]
As part of the new coroutines support in C++20, there is also support for synchronous coroutines. When looking at porting code from C#, it is currently very difficult to port iterator blocks from C# to C++/WinRT. If `co_yield`-based coroutines could return an implementation of `IIterable<T>`, then porting over iterator blocks from C# to C++/WinRT would be significantly simpler.

**Comment by oldnewthing** [comment]
I think this is something better-suited to a library rather than the core C++/WinRT system. Perhaps [wil](https://github.com/microsoft/wil).

**Comment by jkoritzinsky** [comment]
The main reason I recommend it here is that C++/WinRT already owns the asynchronous coroutines-as-IAsyncOperation glue code, so it would make sense that the glue code for synchronous coroutines to live in a similar place.

**Comment by oldnewthing** [comment]
Async operations are fundamental to the Windows Runtime execution model. Iterators, on the other hand, are typically just iterating over an existing collection, rather than generating objects on the fly. C++20 is rumored to be getting a `std::generator` which will make on-the-fly iteration easier to implement.

**Comment by kennykerr** [comment]
While implementing `IIterable<T>` with a coroutine sounds cool, I'm not sure how much it would actually be used in practice. `IIterable<T>` by itself is not a very efficient way to communicate a collection of things, so most APIs should prefer `IVectorView<T>` wherever possible.

I'm reluctant to add more coroutine features unless they're critical to WinRT authoring *and* coroutine support in C++ stabilizes and matures. If you'd like an example of a generator for your own use you can [have a look at this one](https://dev.azure.com/microsoft/dart/_git/ModernCPP?path=%2Fcppwinrt%2Fsource%2Fgenerator.h) that powered early versions of C++/WinRT's code generator. You could certainly experiment with using that to implement `IIterable<T>` yourself.
