### ISSUE TITLE
Visual Studio snippets

### ISSUE THREAD

**Issue by chingucoding** [microsoft/cppwinrt#708]
When developing UWP apps in C#, developers can take advantage of different Visual Studio snippets such as `propdp` which inserts a dependencyproperty with the appropiate getter and setter.

However as far as I could tell, those snippets do not exist for C++ winrt, and would make it a bit easier to develop apps.

The `propdp` snippet inserts the following snippet, and allows to change the type,name etc upon adding that snippet for the first time:

```c#

        public int MyProperty
        {
            get { return (int)GetValue(MyPropertyProperty); }
            set { SetValue(MyPropertyProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty MyPropertyProperty =
            DependencyProperty.Register("MyProperty", typeof(int), typeof(ownerclass), new PropertyMetadata(0));
```

**Comment by kennykerr** [comment]
Yes, that would be great but would be a feature of the Visual Studio IDE. You could try and suggest it here:

https://developercommunity.visualstudio.com/spaces/62/index.html

**Comment by chingucoding** [comment]
Given that C++/WinRT is currently delivered through a separate extension, wouldn't it make more sense to ship those snippets as part of that extension? Visual Studio extensions can provide custom snippets as part of the extension as shown [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-distribute-code-snippets?view=vs-2019).

**Comment by kennykerr** [comment]
In theory perhaps that's true. In practice, our team doesn't have the skills or manpower to maintain the existing VS extension, let alone add new features. We are focused on the C++/WinRT compiler and library.

**Comment by chingucoding** [comment]
Fair enough, created [this proposal](https://developercommunity.visualstudio.com/idea/1192640/cwinrt-code-snippets.html). Would community contributions be welcomed in this area or would it be better to wait for the result of the VS proposal?
