### ISSUE TITLE
Question: Why does the Visual Studio tool not link to this repo

### ISSUE THREAD

**Issue by chingucoding** [microsoft/cppwinrt#709]
As the title says, I am wondering why the [Visual Studio C++/WinRT tool/extension](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264) does not link to this repository. The link that is listed there is the [microsoft/xlang repository](https://github.com/Microsoft/xlang) which seems a bit strange to me given that this repo contains everything C++/WinRT related.

**Comment by kennykerr** [comment]
That's a good question. I'm not sure how to update that but I'll try to find out. Maybe @Scottj1s knows.

**Comment by kennykerr** [comment]
Found it - thanks for letting us know!
