### ISSUE TITLE
"The text associated with this error code could not be found" on WININET_E_CANNOT_CONNECT 

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#710]
![image](https://user-images.githubusercontent.com/22989529/88886334-151f8e80-d1ef-11ea-91d7-32a9fd7dee87.png)

**Comment by oldnewthing** [comment]
This text isn't coming from C++/WinRT. It's coming from `RoOriginateLanguageException` because `FormatMessage` cannot obtain a string for `WININET_E_CANNOT_CONNECT`. You'll have to take it up with the owners of `RoOriginateLanguageException` or possibly `FormatMessage`.

```cpp
int main()
{
    init_apartment();

    RoOriginateLanguageException(WININET_E_CANNOT_CONNECT, nullptr, nullptr);
    winrt::com_ptr<IErrorInfo> info;
    GetErrorInfo(0, info.put());
    BSTR desc;
    info->GetDescription(&desc);
    printf("%ls\n", desc); // "The text associated with this error code could not be found."

    wchar_t buffer[256]{};
    auto size = FormatMessageW(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
        nullptr,
        WININET_E_CANNOT_CONNECT,
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
        buffer,
        256,
        nullptr);
    printf("%d\n", size); // size = 0, error text not available
    printf("%ls\n", buffer); // prints nothing
}
```

**Comment by kennykerr** [comment]
Yes, WININET assumes you're going to call `FormatMessage` with the `wininet.dll` module handle as its second parameter. But that's not something C++/WinRT can do in general so its up to you to make the `FormatMessage` call yourself if you'd like WININET's error message.

**Comment by asklar** [comment]
@oldnewthing @kennykerr is this behavior specific to wininet or is this a more general pattern with other modules?
from an app's perspective, we just have a try catch around some code and we catch the hresult_error and try to print out a useful message, we dont necessarily know that it's from wininet or some other module. How can we find out how to get an error message that's appropriate for a given hresult_error/HRESULT?

**Comment by kennykerr** [comment]
This is specific to the WININET API. Most APIs should be using `SetLastError` or `RoOriginateError` from within their APIs before returning an error code in order to attach richer error information. C++/WinRT attempts to harvest error information from such general sources. WININET chose not to do so and as a result forces callers to retrieve error information in a more roundabout way. Thus, part of the responsibility for anyone using WININET is to gather the error information from the API. Ideally, this should be handled by a WININET wrapper library. That's the way I used to use WININET in the past.

**Comment by JunielKatarn** [comment]
@kennykerr this topic came up in a [React Native Windows PR](https://github.com/microsoft/react-native-windows/pull/5174).

Seems like the ABI static data member allows retrieving the restricted info coming from WININET (WinHTTP?) (at least, connection errors).
https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/error-handling/hresult-error#hresult_errorfrom_abi-static-data-member

**Comment by kennykerr** [comment]
No, the `from_abi` marker type doesn't know anything about WININET either.

**Comment by JunielKatarn** [comment]
> No, the `from_abi` marker type doesn't know anything about WININET either.

Interesting. Using the ABI marker, I get this error message when constructing an `hresult_error`:
```
A connection with the server could not be established
```

Removing the marker, using only the HRESULT value to construct the `hresult_error`:
```
The text associated with this error code could not be found.
```

Maybe there's a layer above WININET that sets the message?

**Comment by kennykerr** [comment]
`from_abi` just tells `winrt::hresult_error` to call `GetErrorInfo` to retrieve any error information associated with the thread (TLS). If that works for you it means that someone has gone and called `SetErrorInfo` (or one of its variants) to place the error information there for the caller. Anyway, glad you got it working. 👍
