### ISSUE TITLE
Natvis has difficulties with IInspectable properties

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#714]
Trying to visualize an object that has an IInspectable property (I used Windows.UI.Xaml.RoutedEventArgs) causes the natvis to behave undefined behavior.

The signature blob for such a property is typically 3 bytes {0x20 0x00 0x1c}. With the 1c referring to "Object". Unfortunately, in GetInterfaceData, if a simple element type is encountered, it assumes it's in the range ElementType::Boolean (0x01) to ElementType::String (0x0e), which then leaves the category variable uninitialzed and mayhem ensues.

**Comment by kennykerr** [comment]
Unfortunately, the team does not have the capacity or skills to deal with bugs outside of the core C++/WinRT library and compiler. Feel free to keep the conversation going and contribute a PR as needed.
