### ISSUE TITLE
GpioPin.ValueChanged event cannot be registered under x86-build platform

### ISSUE THREAD

**Issue by linjordy** [microsoft/cppwinrt#716]
This is a simple code that i wrote to test the event callback from **GpioPin.ValueChanged**, I found out that x64 build version works fine while x86 build version failed to register the event, the error code i got stands for "**ERROR_INSUFFICIENT_BUFFER**", meaning that **the data area passed to a system call is too small**. Not sure the exact reason why this happens.

![GPIO_Callback_test](https://user-images.githubusercontent.com/47997275/89248060-54137100-d641-11ea-8785-51d752c14392.PNG)

![image](https://user-images.githubusercontent.com/47997275/89244917-43abc800-d63a-11ea-9534-15487b235f62.png)

**Comment by oldnewthing** [comment]
This is not an issue with C++/WinRT. That error is coming from the `GpioPin` implementation. You should take up the issue with the people responsible for GpioPin.
