### ISSUE TITLE
should winrt::weak_ref<>::get() use [[nodiscard]]?

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#718]
I just read some code that does not store the result of this. can we avoid that bug by adding [[nodiscard]] here?

**Comment by kennykerr** [comment]
Yes, `[[nodiscard]]` should be applied where appropriate. Same goes for `agile_ref` and probably a few other places. It is very useful for catching bugs.

**Comment by ChrisGuzak** [comment]
#719
