### ISSUE TITLE
Problem in resumables

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#72]
The following snipped show how to create the problem:
```C++
bool  DataBase::Async(RegisterItems ptrRegItems, 
							 StringItems ptrStringItems, 
							 SerializedState ptrSerializedState, 
							 bool isReadData) {
	StorageFile storageFile = nullptr; //no default constructor
	Uri uri = Uri(L"ms-appx:///FileDoubles.dbo");
	if (isReadData) {													
		//2017-0108 this all compiled but causes an error in resumables*
		//2017-0109, un comment this line and error results only in resumable, line 44:  using  promise_type = typename _Ret::promise_type;
		//auto file = co_await storageFile.GetFileFromApplicationUriAsync(uri);  

		//2017-0108 the followint all compiled OK
		////auto stream = co_await file.OpenAsync(FileAccessMode::Read);

		////IInputStream inputStream = stream.GetInputStreamAt(0);
		////DataReader dataReader = DataReader(inputStream);
```

**Comment by kennykerr** [comment]
You must use a coroutine type as the return type of any function including a co_await statement. You might for example want to use std::future<bool> instead of bool as the return type.

**Comment by JackDetrick** [comment]
I changed the method to return void - problem persists. 
The compiler has no problem with this line of code:
auto file = co_await storageFile.GetFileFromApplicationUriAsync(uri);
but line 44 of resumable fires off 4 errors.

**Comment by kennykerr** [comment]
`void` is not (by default) a coroutine type either. You might want to try `std::future<void>` instead.

**Comment by JackDetrick** [comment]
Using std::future<bool> solved the problem - thanks...
