### ISSUE TITLE
Casting IInspectable to ListViewItem does not work

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#722]
I'm working on a XAML application and I have a ListView control with an event handler attached for item click. In C++/CX, I was able to cast the ClickedItem property of ItemClickEventArgs to a ListViewItem using a static_cast. In C++/WinRT, I tried using unbox_value<ListViewItem> but I get an exception saying "No such interface supported".

**Comment by Jaiganeshkumaran** [comment]
I tried using try_as<ListViewItem> but even that's not working.

**Comment by Jaiganeshkumaran** [comment]
This issue occurs on both 2004 and 1903.

**Comment by Jaiganeshkumaran** [comment]
try_as is now working for me after a rebuild.

**Comment by YexuanXiao** [comment]
> try_as is now working for me after a rebuild.

I have encountered the same problem. Is there any other solution?
