### ISSUE TITLE
CanvasRenderTarget.Dispose() not implemented?

### ISSUE THREAD

**Issue by jevansAN** [microsoft/cppwinrt#723]
I want to dispose of a number of CanvasRenderTargets, and the docs say that CanvasRenderTarget inherits Dispose() from CanvasBitMap. But VS tells me that 'class "winrt::Microsoft::Graphics::Canvas::CanvasRenderTarget" has no member "Dispose." I'm using winrt 2.0.200316.3 and Win2D 1.24. Everything else works great so I do hate to update unless told the update contains a fix. Or is there now a different way to dispose of these?

**Comment by DefaultRyan** [comment]
I assume you're referring to these docs: https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasRenderTarget.htm

You want to call the `Close()` method on `IClosable`.

Unfortunately, they are displaying their documentation in terms of the .NET projection, which projects `Windows.Foundation.IClosable` as `System.IDisposable`. The [documentation for IClosable](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IClosable?view=winrt-19041) helpfully points this out, but the .NET documentation isn't returning the favor, apparently.

This is not a C++/WinRT issue, but more of an api question and issue with others' documentation. Probably more appropriate for someplace else like stackoverflow.

**Comment by jevansAN** [comment]
Thanks very much - could I ask what is the best, most appropriate documentation source for Win2D using C++/winrt? I could just go there first.

**Comment by DefaultRyan** [comment]
I looked briefly, but didn't see any. You'll want to take it up with the owners of Win2D. https://github.com/microsoft/Win2D/issues
