### ISSUE TITLE
Non c++ standard keyword "sealed" in document for C++/WinRT?

### ISSUE THREAD

**Issue by jjlee9** [microsoft/cppwinrt#727]
One example :
https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject?view=winrt-19041

Non c++ standard keywords should not be used in C++/WinRT. (like "sealed") Please remove this kind of mistakes.

**Comment by walbourn** [comment]
The code sample on that page is for C# where [sealed](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sealed) is a standard keyword. It's not using C++ either via C++/CX or C++/WinRT.

**Comment by jjlee9** [comment]
I switched to C++/WinRT and I found "sealed". Didn't you?

**Comment by jjlee9** [comment]
For **C++/WinRT** in https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject?view=winrt-19041.
(Please switched to C++/WinRT first.)

class JsonObject **sealed** : IIterable<IKeyValuePair<winrt::hstring, IJsonValue const &>>, IMap<winrt::hstring, IJsonValue const &>, IStringable

**Comment by walbourn** [comment]
Ah, I see it now...

Those appear to automatically generated from meta-data like:

```
<!-- Class syntax.
public class JsonObject : Windows.Data.Json.IJsonObject, Windows.Data.Json.IJsonObjectWithDefaultValues, Windows.Data.Json.IJsonValue, Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<System.String, Windows.Data.Json.IJsonValue>>, Windows.Foundation.Collections.IMap<System.String, Windows.Data.Json.IJsonValue>, Windows.Foundation.IStringable
-->
```

The addition of ``sealed`` must be baked into the doc tooling.

@kennykerr You might want to track down who owns that doc logic to get this fix.

**Comment by kennykerr** [comment]
@stevewhims any thoughts?

**Comment by stevewhims** [comment]
Yes, I'll pursue this internally since as Chuck says it's out of the hands of the writer. It's just a case of filing a bug with the content engineering team and then tracking that.

**Comment by kennykerr** [comment]
Thanks!
