### ISSUE TITLE
New user control doesn't sanitize namespace name

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#728]
Create a new CppWinRT XAML user control in a project that has a dot in its name (e.g. `Microsoft.ReactNative`).
The resulting generated code includes the dots in the namespace which is not valid:

```cpp

namespace winrt::Microsoft.ReactNative::implementation
{
    struct DevMenu : DevMenuT<DevMenu>
    {
        DevMenu();

        int32_t MyProperty();
        void MyProperty(int32_t value);

        void ClickHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::RoutedEventArgs const& args);
    };
}

namespace winrt::Microsoft.ReactNative::factory_implementation
{
    struct DevMenu : DevMenuT<DevMenu, implementation::DevMenu>
    {
    };
}
```

**Comment by asklar** [comment]
This value is coming from the `RootNamespace` property which for our project is set to `Microsoft.ReactNative` (same thing as the project name). Note however that this property cannot be set to a C++ friendly namespace name like `Microsoft::ReactNative` since winmdexp uses the root namespace value to construct file names which cannot include colons.
So I think CppWinRT needs to be smart here and convert dots to colons if it encounters them in the `RootNamespace` variable

**Comment by asklar** [comment]
DevComm issue: https://developercommunity.visualstudio.com/content/problem/1151282/vsix-does-not-correctly-provide-rootnamespace-and.html

**Comment by kennykerr** [comment]
Unfortunately, the team does not have the capacity or skills to deal with bugs outside of the core C++/WinRT library and compiler. Feel free to keep the conversation going and contribute a PR as needed.
