### ISSUE TITLE
Issue with capturing winrt types by reference in lambdas

### ISSUE THREAD

**Issue by DJankauskas** [Microsoft/cppwinrt#73]
Whenever I pass a winrt type to a lambda by reference, member function calls performed on the referenced type cause an exception to be thrown. Here is an example: 
```cpp
        Grid grid;
	Window window = Window::Current();
	window.Content(grid);
	window.Activate();
	TextBlock text_block;
	text_block.Text(L"Test");
	text_block.Tapped([&](auto&&, auto&&) {
		text_block.Text(L"bug!");
	});
	grid.Children().Append(text_block);
```
However, the code works perfectly fine when capturing by value.

**Comment by kennykerr** [comment]
Presumably, the `Tapped` event is raised after the `text_block` local variable goes out of scope. This is a bug in your code and as you guessed, capturing by value is the solution. That will ensure that the lambda, which outlives this local scope, has its own (COM-style) reference to the TextBlock object.

**Comment by DJankauskas** [comment]
I moved `text_block` into an `App` member variable, and the code works properly now. Therefore, it appears you are correct.  Thanks for your help in solving this issue.
