### ISSUE TITLE
User Control cannot live in project subfolder

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#731]
Windows target: 19041 / 17734
cppwinrt: 200729

1. Add a blank cppwinrt user control in a subfolder in the project (e.g. Views)
2. Build

## Expected
everything works

## Actual
Build break because the generated code expects the header to live in the root folder and if it doesn't exist, it won't include it meaning that you will get errors for undefined symbols:

![image](https://user-images.githubusercontent.com/22989529/90301468-ed6a3080-de54-11ea-940b-888411dea8b7.png)

`MyControl1.g.h`:
![image](https://user-images.githubusercontent.com/22989529/90301481-04108780-de55-11ea-8918-570e2c98920d.png)

**Comment by asklar** [comment]
the workaround is to add AdditionalIncludeDirectories but this seems wrong as well as fragile...

**Comment by kennykerr** [comment]
Unfortunately the location is based on the namespace of the class and cannot be changed as the Xaml compiler relies on this naming scheme.

**Comment by asklar** [comment]
@kennykerr could we then update the VSIX to not let you create a control in a sub folder? And update the docs?

**Comment by kennykerr** [comment]
I don't know how the VSIX works and whether that's possible, but feel free to contribute a PR.
