### ISSUE TITLE
Question: IDataReader

### ISSUE THREAD

**Issue by MBuehrer** [Microsoft/cppwinrt#74]
Maybe I got something wrong. I's like to instantiate a IDataReader from an IInputStream:
`IInputStream strm=File.GetInputStreamAt(0);
IDataReader rdr(strm);`
IntelliSense tells me that IDataReader does not have an overloaded constructor... (and it woiuldn't compile).
How should I do this ?

**Comment by kennykerr** [comment]
The `IDataReader` interface is just that, an interface. You need an implementation to bring it to life. You can use the `DataReader` class as follows:

```C++
IDataReader reader = DataReader(stream);
```

Or simply:

```C++
DataReader reader(stream);
```

**Comment by MBuehrer** [comment]
Thanks. Seems, I'm getting blind with all that hats ^.
