### ISSUE TITLE
Error while implementing a windows runtime interface for local consumption while porting from c++/cx to c++/winrt

### ISSUE THREAD

**Issue by shankartnj** [microsoft/cppwinrt#740]
I had this in C++/CX:

```
ref class DerivedClass sealed : public BaseClass {
public:
explicit DerivedClass(Windows::UI::Xaml::FrameworkElement^ &control)
    : BaseClass(control) {}
}
```

In c++/winrt, with some help, I got to this point:
```
class DerivedClass : winrt::implements<DerivedClass, BaseClass> {
public:
DerivedClass(winrt::FrameworkElement& control) : 
error===>implements_type(control) {}
}
```
But I get an error:

> no instance of constructor "winrt::implements<D, I, ...>::implements [with D=DerivedClass, I=BaseClass]" matches the argument list argument types are: (winrt::Windows::UI::Xaml::FrameworkElement)

I do have BaseClass Constructor defined which takes in &FrameworkElement as an argument. So I am not sure what I am getting this error. Would appreciate some input on this.

**Comment by DefaultRyan** [comment]
Already answering this on https://stackoverflow.com/questions/63822275/error-while-implementing-a-windows-runtime-interface-for-local-consumption-while/63823903?noredirect=1#comment112876777_63823903. No evidence this is a C++/WinRT issue.
