### ISSUE TITLE
error C2039: 'wait_for': is not a member of 'winrt::impl'

### ISSUE THREAD

**Issue by IanMDay** [microsoft/cppwinrt#744]
After updating to VS 16.8.0 Preview 3 (c++/winrt 2.0.190620.2), build is now failing at:

Windows.Foundation.0.h(983,26): error C2039: 'wait_for': is not a member of 'winrt::impl'

Looks like impl::wait_for is defined later in Windows.Foundation.h:2960, but other foundation headers (via 2.h, 1.h and 0.h) included earlier require it.

Windows.Foundation.h is the first file I include.

**Comment by kennykerr** [comment]
The version of C++/WinRT that ships in the Windows SDK is rather old and fails to compile with the stricter conformance expectations of more recent compilers. You can get a newer version of C++/WinRT here:

https://aka.ms/cppwinrt/nuget

**Comment by IanMDay** [comment]
Erk. That's quite awkward. The new CMake method of including those packages method does not appear to work for cppwinrt at all. Think I'll just stick with non-preview until the next update.

**Comment by Sunbreak** [comment]
> Erk. That's quite awkward. The new CMake method of including those packages method does not appear to work for cppwinrt at all. Think I'll just stick with non-preview until the next update.

@IanMDay  Could you share any working gist of CMake & CppWinRT?

I encounter `missing cppwinrt.exe` via following commit:
https://github.com/woodemi/quick_blue/commit/16c8163c1c35d12de185737c74f59979e08d849c

```cmake
exec_program(${NUGET_EXE}
    ARGS install "Microsoft.Windows.CppWinRT" -Version 2.0.201102.2 -ExcludeVersion -OutputDirectory ${CMAKE_BINARY_DIR}/packages)
......
target_link_libraries(${PLUGIN_NAME} PRIVATE ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets)
```

Github Action log:

https://github.com/woodemi/quick_blue/runs/1370383465?check_suite_focus=true

```
[  +35 ms]   '"D:\a\quick_blue\quick_blue\quick_blue_example\build\windows\packages\Microsoft.Windows.CppWinRT\build\native\"cppwinrt' is not recognized as an internal or external command,
[        ]   operable program or batch file.
```

**Comment by Sunbreak** [comment]
Get it done

https://github.com/woodemi/quick_blue/pull/10/files

```cmake
set_target_properties(${PLUGIN_NAME} PROPERTIES
  VS_PROJECT_IMPORT ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.props
)

target_link_libraries(${PLUGIN_NAME} PRIVATE ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets)
```

**Comment by IanMDay** [comment]
> > Erk. That's quite awkward. The new CMake method of including those packages method does not appear to work for cppwinrt at all. Think I'll just stick with non-preview until the next update.
> 
> @IanMDay Could you share any working gist of CMake & CppWinRT?

I ended up running the cppwinrt.exe manually since I couldn't get the CMake VC_PROJECT_IMPORT to work. This works well for me and the headers are all generated in my build folder at generation time.

```cmake
# Requires 3.19 to allow add_library to have source files and appear in solution
# Also, if there's no real target, you cannot use target_include_directories
cmake_minimum_required(VERSION 3.19)

set(CPPWINRT_FOLDER ${GENERATING_FOLDER}/cppwinrt)
if (NOT EXISTS ${CPPWINRT_FOLDER}/winrt/base.h)
    execute_process(
            COMMAND ${CMAKE_CURRENT_LIST_DIR}/cppwinrt/bin/cppwinrt.exe -overwrite -base -input sdk -output ${CPPWINRT_FOLDER} )
endif()

file(GLOB CPPWINRT_HEADERS ${CPPWINRT_FOLDER}/winrt/*.h)
file(GLOB CPPWINRT_HEADERS_IMPL ${CPPWINRT_FOLDER}/winrt/impl/*.h)

add_library(cppwinrt INTERFACE ${CPPWINRT_HEADERS} ${CPPWINRT_HEADERS_IMPL})
source_group("Header Files\\impl" FILES ${CPPWINRT_HEADERS_IMPL})
target_include_directories(cppwinrt INTERFACE ${CPPWINRT_FOLDER})
set_target_properties(cppwinrt PROPERTIES FOLDER 3rdParty)
```
