### ISSUE TITLE
Document how to use XAML in a WinRT component from C++/WinRT

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#745]
We had an issue in the react-native-windows repo where a developer was trying to reference a C# WinRT component in their C++/WinRT app, but they were hitting a build error not being able to find the C# WinRT xaml type info. My recommendation to them was to add `#include <winrt/Cam.Cam_XamlTypeInfo.h>` in their cppwinrt PCH. This should be documented somewhere related to cppwinrt.

Related: https://github.com/microsoft/react-native-windows/issues/6003

**Comment by kennykerr** [comment]
@stevewhims can comment on documentation.

**Comment by stevewhims** [comment]
Yes, I'll take care of documenting this. @asklar, I'll shoot you an email for details.

**Comment by asklar** [comment]
Thanks Steve!
ref: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/troubleshooting
ref: https://docs.microsoft.com/en-us/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt
