### ISSUE TITLE
MSBuild error when "Enable Copy Local Defaults" (CppWinRTEnableDefaultPrivateFalse) is true

### ISSUE THREAD

**Issue by boostafazoo** [microsoft/cppwinrt#746]
Changes for #704 introduced MSBuild syntax errors into Microsoft.Windows.CppWinRT.props.

https://github.com/microsoft/cppwinrt/blob/e504a0e1d489967aea79bb0fc15b15b0d7163eab/nuget/Microsoft.Windows.CppWinRT.props#L51

https://github.com/microsoft/cppwinrt/blob/e504a0e1d489967aea79bb0fc15b15b0d7163eab/nuget/Microsoft.Windows.CppWinRT.props#L57

This results in an error dialog and/or build errors when **CppWinRTEnableDefaultPrivateFalse** is true.

![error](https://user-images.githubusercontent.com/3084444/93724418-c392e080-fb5b-11ea-9261-aafa94011f8f.png)

**Comment by kennykerr** [comment]
@jlaanstra can you take a look?
