### ISSUE TITLE
C++/WinRT samples

### ISSUE THREAD

**Issue by shankartnj** [microsoft/cppwinrt#749]
1.  Are there any C++/WinRT samples I can use? I can't seem to find any samples in this repo. 

2.  I am trying to create a new C++WinRT project. From [Docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example), I see 

> In Visual Studio, create a new project using the Blank App (C++/WinRT) project template. Make sure that you're using the (C++/WinRT) template, and not the (Universal Windows) one.

But I don't see any template with that name. I am using VS 2019 (just updated today).

3. I would also appreciate some thoughts on this: https://stackoverflow.com/questions/63947106/error-setting-comptr-to-winrtusercontroltag. Please let me know if you need any additional info.

**Comment by DefaultRyan** [comment]
These are generally the sort of questions that will get a better response on StackOverflow.

> Are there any C++/WinRT samples I can use? I can't seem to find any samples in this repo.

https://github.com/microsoft/Windows-universal-samples hosts many UWP samples. Some, but not all of them have been ported to cppwinrt. [This search](https://github.com/microsoft/Windows-universal-samples/search?q=cppwinrt) is a good place to start to find cppwinrt-ported samples.

> I am trying to create a new C++WinRT project. From Docs, I see

>>In Visual Studio, create a new project using the Blank App (C++/WinRT) project template. Make sure that you're using the (C++/WinRT) template, and not the (Universal Windows) one.

> But I don't see any template with that name. I am using VS 2019 (just updated today).

You'll need to install [https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package]. Post on stackoverflow if you still don't see it.

> I would also appreciate some thoughts on this: https://stackoverflow.com/questions/63947106/error-setting-comptr-to-winrtusercontroltag. Please let me know if you need any additional info.

I'll take a look over there.
