### ISSUE TITLE
cppwinrt does not contain Windows.UI.Color

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#75]
Is this a future ?

**Comment by kennykerr** [comment]
`Windows::UI::Color` is available. Be sure to include the appropriate namespace header.

```C++
#include <winrt/Windows.UI.h>
```

**Comment by JackDetrick** [comment]
I have included #include "winrt/Windows.UI.h" with no problem...
The problem is with #include "winrt/Windows.UI.Color.h" and
using namespace Windows::UI::Color

Do I have an out of date cppwinrt?

**Comment by kennykerr** [comment]
`Windows::UI::Color` is not a namespace. It is a struct called `Color` in the `Windows::UI` namespace.

**Comment by JackDetrick** [comment]
Thanks,,,
