### ISSUE TITLE
Support MSBuild Sdk-based consumption

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/cppwinrt#750]
I've stumbled across a substantially easier way of enabling reliable nuget-support for CppWinRT, which I'd like to know if it could be integrated as a default (or opt-in feature).

Following changes need to be done:
* Remove packages.config
* Create "global.json" file in solution-directory
* Reference `Microsoft.Windows.CppWinRT` in `msbuild-sdks`

This way it is possible to _not_ use the solution-relative packages-directory, not depend on hacky-ways of trying to resolve cross-repository packages-resolving strategies. (i.e. Git Submodules in Git Submodules trying to resolve the path to their known path of "..\packages\Microsoft.Windows.CppWinRT"-package)
The vcxproj needs to have following changes:
```
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\build\native\Microsoft.Windows.CppWinRT.props" Sdk="Microsoft.Windows.CppWinRT" />
```
```
<ImportGroup Label="ExtensionTargets">
  <Import Project="..\build\native\Microsoft.Windows.CppWinRT.targets" Sdk="Microsoft.Windows.CppWinRT" />
</ImportGroup>
```
Instead of the default packages.config-stuff.

The global.json needs following content:
```
"msbuild-sdks": {
	"Microsoft.Windows.CppWinRT": "2.0.200729.8"
}
```

If this is not possible I'd like to see that there is atleast a "Sdk"-folder inside the CppWinRT nuget package for Sdk.props and Sdk.targets which automatically resolves to `build\native\Microsoft.Windows.CppWinRT.props` / `build\native\Microsoft.Windows.CppWinRT.targets` respectively.

This does work with `<Import Project="..\build\native\Microsoft.Windows.CppWinRT.props" Sdk="Microsoft.Windows.CppWinRT" Version="2.0.200921.6" />`, though a `<Sdk Name="Microsoft.Windows.CppWinRT" Version="2.0.200921.6" />` would be nice as well …

**Comment by kennykerr** [comment]
Not knowing much about msbuild, I'm not really sure whether this is a question about C++/WinRT or just msbuild in general. You may have better luck over on https://stackoverflow.com/, but perhaps @jlaanstra would like to comment.

**Comment by jlaanstra** [comment]
@AliveDevil NuGet support for C++ is very limited. As far as I know MSBuild SDKs are unsupported for C++? Do you have docs that say otherwise?

**Comment by AliveDevil** [comment]
@jlaanstra well … I dont have any docs that prove that this should work, nor that it shouldn‘t. This happened by accident trying to get NuGet without the packages.config to work - as PackageReference is not working, and Sdk-Includes require Sdk.props and Sdk.targets, I just tried rewriting the default Import-directive with a relative path to the „expected“ sdk/-folder, which - to my suprise - worked just out of the box. I expect this is part of the .Common-includes, which work regardless of project type.

**Comment by jlaanstra** [comment]
It looks like global.json is explicitly part of the .NET tooling, see https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x which means we are not able to rely on this.

**Comment by AliveDevil** [comment]
Going to check later whether setting an explicit version in the `<Import Project=".props" Sdk="" Version="" /`>-directive (without using `global.json`) works without having .NET Core SDK installed - if this is the case I'd argue that atleast with the explicit Sdk-import this works independently using MSBuild 16.7 and 16.8.

Given that there's this document ([https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019]), where there is this quote:
> The NuGet-based SDK resolver supports specifying a version in the global.json file, which allows you to control the project SDK version in one place rather than in each individual project:

Given these steps for trying to resolve a SDK
> - A NuGet-based resolver that queries your configured package feeds for NuGet packages that match the ID and version of the SDK you specified.
> - A .NET CLI resolver that resolves SDKs that are installed with .NET CLI.
> - A default resolver that resolves SDKs that were installed with MSBuild.

The second being unavailable for, and the first one being active `[only] if you specified an optional version. It can be used for any custom project SDK.`,

I'd say: C++-projects are capable - by design (since MSBuild 15.0) - to use Sdk-based project imports.

**Comment by jlaanstra** [comment]
@rainersigwald thoughts on if this is something that would work?

**Comment by kennykerr** [comment]
Feel free to keep the conversation going, but this is outside the scope of what we can tackle as part of C++/WinRT.
