### ISSUE TITLE
NuGet: 2.0.200921.6 release that introduced "C++20 coroutine support", still specifies /await in Microsoft.Windows.CppWinRT.targets file

### ISSUE THREAD

**Issue by AlexBAV** [microsoft/cppwinrt#751]
Latest release that introduced "C++20 coroutine support" still forces old behavior by having `/await` option in `Microsoft.Windows.CppWinRT.targets` file in NuGet package.

**Comment by kennykerr** [comment]
Yes, I noticed this:

https://github.com/microsoft/cppwinrt/blob/fa6bb7a2e2eee3276154e6fd33b97cb9f3125bd0/nuget/Microsoft.Windows.CppWinRT.props#L32

Which I assume is forcing something, but it would be up to @jlaanstra or @Scottj1s or anyone with msbuild skills to contribute a PR to fix that.

**Comment by jlaanstra** [comment]
I suppose we want to only set it when the language version is C++ 17?

**Comment by kennykerr** [comment]
The /await flag is not the issue. The msbuild files seem to force C++17. The project templates must default to C++17, but must not prevent it from being changed (to something newer). That seems to be the problem - a developer cannot change it for their project.

**Comment by jlaanstra** [comment]
@kennykerr The line you mentioned only sets the LanguageStandard if it's not already specified and does so in the props file so the value in the project file always will always override it.

**Comment by AlexBAV** [comment]
I think NuGet package should not force `/await`, making standard coroutine mode the default one. If the user needs "old mode" for some reason, he can set `/await` on the project level. C++/WinRT will work correctly in either mode.

That is, specifying only `/std:c++latest` is enough, no need to additionally have `/await`.

**Comment by kennykerr** [comment]
That's good to know. I thought the `/await` flag would be ignored by C++20 but if that's the issue it seems harmless to remove it by default. Developers using C++17 can always add it if they need to. I did confirm that `/await` forces VC to use the C++17 version of coroutines even when compiling for C++20. As it stands, there doesn't appear to be a way to override this as the cppwinrt.targets file appears to force the inclusion of `/await`.

**Comment by jlaanstra** [comment]
I'll submit a PR to fix this.

**Comment by kennykerr** [comment]
Thanks for your patience. I've fixed the msbuild issue and published another version of the nuget package that includes the fix: 2.0.201006.7

**Comment by AlexBAV** [comment]
I can confirm the latest version of NuGet package works correctly in standard-compliant mode. Excellent work @kennykerr and team!

Thank you!

**Comment by Zingam** [comment]
@kennykerr 
Can I assume this was not included in Windows 10 SDK 10.0.19041.0 and Visual Studio 16.8.3?
I started a new UWP CMake 3.18 generated project.
