### ISSUE TITLE
C++/WinRT Return IVector<SomeStruct> to C# application

### ISSUE THREAD

**Issue by JeffMushmo** [microsoft/cppwinrt#752]
I'm attempting to return a list of structs from C++/WinRT to C#. The error message I get is: The stub received bad data.

IDL:
```
namespace SampleComponents
{
	[version(1.0)]
	struct DateTimeInfo
	{
		Int32 Year;
		Int32 Month;
		Int32 Day;
		Int32 Hour;
		Int32 Minute;
		Int32 Second;
		Int32 Milliseconds;
	};

	[version(1.0)]
	struct SampleStruct
	{
		String Name;
		DateTimeInfo Created;
		Int64 Amount;
	};

	[default_interface]
	runtimeclass SampleRetrieval : ISampleRetrieval
	{
		SampleRetrieval();
	}

	[version(1.0)]
	[uuid(aa11a991-7a39-4278-973b-9a73776d6519)]
	interface ISampleRetrieval : IInspectable
	{

		HRESULT GetSamples([out, retval] Windows.Foundation.Collections.IVector<SampleStruct>** result);

	}

}
```

SampleComponents.h:
```
#include "SampleComponents.g.h"

using namespace winrt::SampleComponents;

namespace winrt::SampleComponents::implementation
{

	struct SampleRetrieval : SampleRetrievalT<SampleRetrieval>
	{
		SampleRetrieval() {

		};

		Windows::Foundation::Collections::IVector<SampleStruct> GetSamples() const;
		
	};


}

namespace winrt::SampleComponents::factory_implementation
{
	struct SampleRetrieval : SampleRetrievalT<SampleRetrieval, implementation::SampleRetrieval>
	{
	};

}
```

SampleComponents.cpp:
```
#include "pch.h"
#include "SampleComponents.h"

using namespace winrt;

namespace winrt::SampleComponents::implementation
{

	Windows::Foundation::Collections::IVector<SampleStruct> SampleRetrieval::GetSamples() const
	{
		Windows::Foundation::Collections::IVector<SampleStruct> items{ winrt::single_threaded_vector<SampleStruct>() };
		do
		{
                        ... GET DATA ...

			SampleStruct sample;

			... FILL SAMPLE DATA ...

			items.Append(sample);

		} while (... CONDITION ...);


		return items;
	}

}
```

When I call SampleRetrieval.GetSamples() from C# is when I get the exception.

I'm not sure what I'm missing here. I've tried many different ways and cannot get this working.

**Comment by kennykerr** [comment]
The C++ portion seems reasonable. I suggest you post a question on https://stackoverflow.com/ with more info on how the C# side is constructed and including detailed error info. You could also simplify the example to the point where it works and then identify which change causes it to fail. This will help narrow the problem down. A minimal self contained repro is best

**Comment by Alkanores** [comment]
> The C++ portion seems reasonable. I suggest you post a question on https://stackoverflow.com/ with more info on how the C# side is constructed and including detailed error info. You could also simplify the example to the point where it works and then identify which change causes it to fail. This will help narrow the problem down. A minimal self contained repro is best

I have same issue, and this don't C# error. I'm trying to insert std::vector<uint8_t> into ValueSet by convert into IVector<uint8_t>, but I can't. The application does not display any error, it is simply silent.

C++ side:
![image](https://user-images.githubusercontent.com/49155506/108509541-6cda3000-72ce-11eb-92fd-40d1fe9609e8.png)

C# side:
![image](https://user-images.githubusercontent.com/49155506/108509732-aca11780-72ce-11eb-8c24-7747634a9440.png)

C# FullTrust Manager Code:
```csharp
public async Task<ValueSet> SendRequest(string type, ValueSet parameters = null)
{
        ValueSet data;

        if (parameters != null)
        {
                data = parameters;
        }
        else
        {
                data = new ValueSet()
                {
                        { "request_type", type }
                };
        }

        AppServiceResponse response = await App.Connection.SendMessageAsync(data);

        return response.Message;
}
```

Maybe you try to explain, what's happened?

**Comment by Alkanores** [comment]
@kennykerr
