### ISSUE TITLE
Visual Studio complains when using co_await for FileOpenPicker::PickSingleFileAsync

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#753]
When using co_await for FileOpenPicker::PickSingleFileAsync, Visual Studio's IntelliSense tells that it's a deleted function however it compiles successfully.

`function "winrt::impl::notify_awaiter<T>::notify_awaiter(const winrt::impl::notify_awaiter<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Storage::StorageFile>> &) [with T=winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Storage::StorageFile>]" (declared implicitly) cannot be referenced -- it is a deleted function`

PC information:
- Windows 10 Pro build 19041 version 2004
- Visual Studio version 16.7.2
- C++/WinRT package version 2.0.200921.6

**Comment by Jaiganeshkumaran** [comment]
After a rebuild it's gone

**Comment by kennykerr** [comment]
IntelliSense bugs can be reported here:

https://developercommunity.visualstudio.com/spaces/62/index.html

They will need a minimal self-contained repro. Feel free to add a link to the issue you create over here and we'll try to make sure it gets some attention.

**Comment by seven-mile** [comment]
@kennykerr  [this issue](https://developercommunity.visualstudio.com/t/declared-implicitly-cannot-be-referenc/1203236?space=62&q=%28declared+implicitly%29+cannot+be+referenced+--+it+is+a+deleted+function) is closed because they think it's cpp/winrt bug. I can repro it sometimes on the latest version VS2022 + nuget package.

**Comment by rbaprado** [comment]
I see the same error here on 2.0.211028.7

**Comment by kennykerr** [comment]
Can you share a minimal repro?

**Comment by rbaprado** [comment]
> Can you share a minimal repro?

This is the current code:

```
IAsyncAction winrt::Precog::implementation::MarketPage::importHistoricalSeriesButton_Click(winrt::Windows::Foundation::IInspectable const& sender, winrt::Microsoft::UI::Xaml::RoutedEventArgs const& e)
{
	FileOpenPicker picker;
	picker.FileTypeFilter().Append(L"*.zip");
	picker.SuggestedStartLocation(PickerLocationId::Downloads);
	HWND hwnd = GetActiveWindow();

	const auto initializeWithWindow = picker.as<IInitializeWithWindow>();
	winrt::check_hresult(initializeWithWindow->Initialize((HWND)hwnd));


	auto file = co_await picker.PickSingleFileAsync();
}
```

**Comment by rbaprado** [comment]
Just some additional details: I was working on this yesterday (the same code worked fine and I got no VS warning on co_await). Today I got some Windows Updates and updated to the newest WinRT nugget package prior to running the code again.

**Comment by kennykerr** [comment]
Thanks for the information - I tried this myself and it is showing up as an IntelliSense error. The compiler itself does not complain about the code at all. This is not uncommon but something the IntelliSense team needs to resolve. I'll ping them internally to see if we can reopen this issue:

https://developercommunity.visualstudio.com/t/declared-implicitly-cannot-be-referenc/1203236?space=62&q=%28declared+implicitly%29+cannot+be+referenced+--+it+is+a+deleted+function

**Comment by kennykerr** [comment]
Good news, the C++ team confirms this is an IntelliSense bug. I believe that issue has been reopened.

**Comment by adriancalavie** [comment]
Hi, I am currently getting the same behaviour.

My configuration:
* Windows 11 Pro: version 2009, build 22000.527
* Visual Studio Community 2022: version 17.1.0
* C++/WinRT: version 2.0.220131.2
