### ISSUE TITLE
co_await  TimeSpan resumes on a different thread

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/cppwinrt#754]
There are documented examples of using the `co_await` oeprator on a TimeSpan/chrono::duration like this:

```c++
// Wait a bit
co_await 1s;
// Continue doing some work
```

This calls `winrt::resume_after` under the hood, which uses `CreateThreadPoolTimer`. The coroutine is resumed directly from the timer callback, which may not be fired on the original thread.

There are quite a few examples online of `co_awaiting` a timespan, but none I could find mention the semantics involving a thread jump. This can be a little surprising, and should ideally be documented if it is the intention.

**Comment by ysc3839** [comment]
[This document](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#execution-contexts-resuming-and-switching-in-a-coroutine) says:
```
    // No matter what the thread context is at this point...
    co_await 5s;
    // ...we're on the thread pool at this point.
```

**Comment by NickGerleman** [comment]
Oh wow I totally missed that. Thanks for pointing out the document.
