### ISSUE TITLE
Nuget package does not work with on a project using absolute paths

### ISSUE THREAD

**Issue by rosca** [microsoft/cppwinrt#758]
The first error I get is because of these two variables:
`<MetadataFileName>$(IntDir)Unmerged\%(Filename).winmd</MetadataFileName>`
`<WinMDPath>%(Midl.OutputDirectory)%(Midl.MetadataFileName)</WinMDPath>`

In $(IntDir) is an absolute paths, then `WindMDPath` will not be valid.
This is the first error I get, but if I fix it there are others as well.

It would be difficult for us to switch to relative paths, since we are generated all the projects.

**Comment by kennykerr** [comment]
The nuget package is heavily used and is very difficult to change at this point without the risk of breaking changes. I'm afraid there isn't much I can suggest as I don't know much about msbuild.
