### ISSUE TITLE
XamCode sample : unable to reference a dll

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#76]
It appears that winmd is the only option. Is this permanent?

**Comment by KevinWelton** [comment]
Hi Jack. For a UWP app, you are restricted to winmd references. If you have other projects in the solution for WinRT components, you should be able to reference those projects as well.

If you want to reference a Win32 dll, I recommend starting [here](https://msdn.microsoft.com/en-us/library/mt186162.aspx). This gives background on linking to your Win32 dll and instructions for including it in the app package.

**Comment by JackDetrick** [comment]
Kevin
For a  C# UWP  app, a dll can be referenced if it is portable. So my question is, will C++/winrt be able to access a portable dll

**Comment by KevinWelton** [comment]
I see. Thanks for the clarification.

Portable DLLs are .NET assemblies, but are not WinRT type libraries. Hence no available winmd to  reference. In a C# UWP app, this isn't a problem. But in a C++ application, you need to enable the /clr option to add .NET assemblies (portable or otherwise) as project references. C++/winrt uses compiler flags and syntax that are not compatible with the /clr option.

**Comment by JackDetrick** [comment]
Kevin,


Bottom line, it looks like I will be unable to convert my apps from C# to C++/winrt...


Thanks for your help


Jack

________________________________

**Comment by BrentRe** [comment]
You can convert apps from C# to C++/WinRT. Basically, this means converting the C# app code to C++ code (especially as C++/WinRT is simply standard C++ code).

But standard C++ code cannot link to C# libraries, portable or not. Therefore, you'd need to convert the libraries from C# to C++ as well.

Nothing here is particular to C++/WinRT.

**Comment by JackDetrick** [comment]
Brent


I have converted my C# code into C++/winrt   (the non XAML portion).The issue, is I need to reference a portable DLL from my C++/winRT code (and then let the certification process validate it).

________________________________

**Comment by JackDetrick** [comment]
Brent
The DLL in question was written in C#,. Does that mean it must be rewitten in C++/CX ?

**Comment by BrentRe** [comment]
There's no need to rewrite the C# code into C++/CX.

Standard C++ cannot use/call .NET types, and C++/WinRT is simply standard C++. However, you can use C++/CLI to interoperate with C++ and .NET types.

You could write an interop component using C++/CLI. That component would expose a C++ layer that your client code would call. In turn the C++/CLI component could map the incoming C++ calls to outgoing .NET calls to your C# DLL and vice-versa.

Note that this applies to any interop between C++ and .NET components. It's not specific to C++/WinRT.

**Comment by JackDetrick** [comment]
Thanks
