### ISSUE TITLE
use C++20 std::source_location to report error origination information

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#761]
The [wil error handling macros](https://github.com/Microsoft/wil/wiki/Error-handling-helpers) log error origination information, source file, line number, etc. it can do this because it uses macros and those have access to `__FILE__` and `__LINE__`. C++20 adds [`std::source_location`](https://en.cppreference.com/w/cpp/utility/source_location) which lets you get this information without macros. 

Given the wil functionality, the guidance for the OS repo is to use the wil macros instead of C++WinRT error handling (`winrt::check_hresult`). This, of course, creates problems, the need to integrate the error handling (via wil/cppwinrt.h), catch errors differently (use wil macros) and generally is ugly (macros, ugh!).

I've not tracked the status of std::source_location in vc, so we need to make sure that is coming.

**Comment by kennykerr** [comment]
> The wil error handling macros log error origination information, source file, line number, etc

What exactly does WIL do with this information? Is it added to the error information object (IRestrictedErrorInfo/IErrorInfo) as a description or stored elsewhere?

@manodasanW any suggestions?

**Comment by sylveon** [comment]
For source_location status: https://github.com/microsoft/STL/pull/664

**Comment by ChrisGuzak** [comment]
> What exactly does WIL do with this information?

https://github.com/Microsoft/wil/wiki/Error-handling-helpers#logger-defaults-and-customization

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
