### ISSUE TITLE
Strange behaviour when using BluetoothLEDevice and MidiInPort  

### ISSUE THREAD

**Issue by dingari** [microsoft/cppwinrt#768]
Hi, I'm using C++/WinRT in my project and am experiencing very strange behavior where a connection to more than one MidiInPort and their corresponding BluetoothLEDevice instance seems to severly limit the throughput of other such connections.

I compiled as minimal of an example as I could and uploaded to [github](https://github.com/dingari/winrt-midi-test). The readme of the repo describes the problem in detail.

Can anyone shine a light on what might be happening here?

**Comment by kennykerr** [comment]
Hi Daníel, I'm afraid I don't know anything about this particular API. The issues page on this repo is for reporting issues with C++/WinRT itself. You may have better luck posting your question on https://stackoverflow.com/. Adding @jonwis in case he happens to know who owns Bluetooth.

**Comment by jonwis** [comment]
@mziller can you help route?

**Comment by jonwis** [comment]
(oopsie, meant to comment not reopen)

**Comment by dingari** [comment]
@kennykerr I understand this issue may not relate directly to the C++/WinRT language projection, but probably more towards the Windows runtime itself. If I remember correctly, this behavior was also present when using WRL to interface with the Windows runtime. Thanks anyway.

@mziller Thanks for the help. I haven't been able to test this issue with many 3rd party devices since it requires the device to send data through MIDI and a proprietary BLE service. I haven't come across any devices that do that at a sufficiently high rate.

And just to be clear, I'm just using JUCE for the GUI and some utility since that's what I'm most familiar with. I'm using the Windows [MidiInPort](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi.midiinport?view=winrt-19041) and [BluetoothLEDevice](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice?view=winrt-19041) classes directly in the example. Believe it or not, this *is* the most minimal example I can cook up.
