### ISSUE TITLE
RuntimeClassName as a static member 

### ISSUE THREAD

**Issue by zh4ui** [microsoft/cppwinrt#771]
When authoring a runtime class, e.g. TeddyBear, C++/WinRT will generate the following method for it:

```c++
        hstring GetRuntimeClassName() const
        {
            return L"Toms.TeddyBear";
        }
```

GetRuntimeClassName() belongs to an instance, I was wondering if it's possible to bind `L"Toms.TeddyBear"` to a static member, so it can be accessed without creating an instance of the runtime class?

**Comment by ysc3839** [comment]
IIRC you can use `winrt::name_of<Class>()` to get the class name.

**Comment by zh4ui** [comment]
> IIRC you can use `winrt::name_of<Class>()` to get the class name.

I checked https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/winrt, it seems `winrt::name_of<Class>()` is an undocumented feature.

**Comment by ysc3839** [comment]
@zh4ui I think it's just missing in the docs, because `winrt::init_apartment()` is also absent.

**Comment by kennykerr** [comment]
`winrt::name_of<T>` is the right answer. Generally, things in the `winrt` namespace are fair game.

**Comment by zh4ui** [comment]
`winrt::name_of<Class>()` doesn't work in some cases.

For example, let's say Toms.TeddyBear is directly derived from DependencyObject, and I'm going to register a s_sizeProperty which is a DependencyProperty on it.

```cpp
struct TeddyBear: TeddyBearT<TeddyBear>
{
  static DependencyProperty s_sizeProperty;
};

DependencyProperty TeddyBear::s_sizeProperty =
  DependencyProperty::Register(L"Size",
                               winrt::xaml_typename<int>(),
                               winrt::xaml_typename<TeddyBear>(),
                               PropertyMetadata{ nullptr });
```

I got this error: 

```
Windows.UI.Xaml.Interop.h(643,29): error C2338: T must be WinRT type.
```

Then I tried to change it to

```cpp
DependencyProperty TeddyBear::s_sizeProperty =
  DependencyProperty::Register(L"Size",
                               winrt::xaml_typename<int>(),
                               TypeName{
                                 .Name = winrt::name_of<TeddyBear>(),
                                 .Kind = TypeKind::Metadata,
                               },
                               PropertyMetadata{ nullptr });

```

I got even more errors.

But it will work if I use the runtimeClassName directly:

```cpp
DependencyProperty TeddyBear::s_sizeProperty =
  DependencyProperty::Register(L"Size",
                               winrt::xaml_typename<int>(),
                               TypeName{
                                 .Name = L"Toms.TeddyBear",
                                 .Kind = TypeKind::Metadata,
                               },
                               PropertyMetadata{ nullptr });
```

Not a strong case, but I think it'd be good to make the runtimeClassName statically accessible.

**Comment by Jaiganeshkumaran** [comment]
> `winrt::name_of<Class>()` doesn't work in some cases.
> 
> For example, let's say Toms.TeddyBear is directly derived from DependencyObject, and I'm going to register a s_sizeProperty which is a DependencyProperty on it.
> 
> ```c++
> struct TeddyBear: TeddyBearT<TeddyBear>
> {
>   static DependencyProperty s_sizeProperty;
> };
> 
> DependencyProperty TeddyBear::s_sizeProperty =
>   DependencyProperty::Register(L"Size",
>                                winrt::xaml_typename<int>(),
>                                winrt::xaml_typename<TeddyBear>(),
>                                PropertyMetadata{ nullptr });
> ```
> 
> I got this error:
> 
> ```
> Windows.UI.Xaml.Interop.h(643,29): error C2338: T must be WinRT type.
> ```

xaml_typename only works on projected types, replace the xaml_typename<TeddyBear> with xaml_typename<Toms:: TeddyBear>;

**Comment by sylveon** [comment]
You can also write `xaml_typename<class_type>()` as a more generic solution because the TeddyBearT base class provides that handy typedef to access the projection type.
