### ISSUE TITLE
Cannot consume Windows.Data.Json.JsonObject

### ISSUE THREAD

**Issue by phraemer** [microsoft/cppwinrt#772]
I suspect this could be a simple misunderstanding on my part but advice would be very welcome.

Using the PhotoEditor example app https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/photo-editor-sample

I add the following property to `Photo.idl`

```idl
	Windows.Data.Json.JsonObject JsonProp{ get; };
```

and then implement it in `Photo.h`:

```cpp
        Windows::Data::Json::JsonObject JsonProp() const
        {
            return Windows::Data::Json::JsonObject::Parse(L"{}");
        }
```

I end up with a linker error:

```
1>------ Build started: Project: PhotoEditor, Configuration: Debug x64 ------
1>Photo.cpp
1>MainPage.obj : error LNK2019: unresolved external symbol "public: static struct winrt::Windows::Data::Json::JsonObject __cdecl winrt::Windows::Data::Json::JsonObject::Parse(struct winrt::param::hstring const &)" (?Parse@JsonObject@Json@Data@Windows@winrt@@SA?AU12345@AEBUhstring@param@5@@Z) referenced in function "public: struct winrt::Windows::Data::Json::JsonObject __cdecl winrt::PhotoEditor::implementation::Photo::JsonProp(void)const " (?JsonProp@Photo@implementation@PhotoEditor@winrt@@QEBA?AUJsonObject@Json@Data@Windows@4@XZ)
1>C:\b\tests\Windows-appsample-photo-editor\x64\Debug\PhotoEditor\PhotoEditor.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "PhotoEditor.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I would have thought anything in the `Windows` namespace was linked?

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis#if-the-api-is-in-a-windows-namespace

**Comment by kennykerr** [comment]
You're probably missing the `winrt/Windows.Data.Json.h` namespace header.

**Comment by phraemer** [comment]
Basically correct, thank you!

Further detail in case anyone else searches for this:
My mistake was to place the include in the `.cpp` file and not in the header.
The fact it compiled made me think it was some other issue.
