### ISSUE TITLE
Consider adding boxing overloads for UIElement::AddHandler

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#776]
Users wanting to call [UIElement::AddHandler](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.addhandler?view=winrt-19041) have to manually box up the delegate. Apparently, there must have been some magic happening for CX and C# to support this, because I can't find any documentation of this requirement anywhere.

Essentially, `AddHandler`'s second parameter is expecting to get `IReference<T>` where `T` corresponds to a `RoutedEvent`. users are stuck trying to discover and use the boxing code manually with this:
```c++
using namespace winrt;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::UI::Xaml;
using namespace winrt::Windows::UI::Xaml::Input;

void OnTapped(IInspectable const& sender, TappedRoutedEventArgs const& args);
void f(UIElement const& element)
{
  element.AddHandler(UIElement::TappedEvent(), box_value(TappedEventHandler{ &OnTapped }, true);
}
```
There's roughly 20 of these events. It shouldn't be too hard to add some overloads of this method that provide some helpful guardrails for the user. Perhaps for each of these events, provide either:
```c++
void UIElement::AddHandler(TappedEventHandler const& handler, bool routedEventsToo)
{
  AddHandler(UIElement::TappedEvent(), box_value(handler), routedEventsToo);
}
```
or
```c++
void UIElement::AddHandler(IReference<TappedEventHandler> const& handler, bool routedEventsToo)
{
  AddHandler(UIElement::TappedEvent(), handler, routedEventsToo);
}
```

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
