### ISSUE TITLE
No generated code for console app

### ISSUE THREAD

**Issue by kennykerr** [microsoft/cppwinrt#780]
@jlaanstra could this PR https://github.com/microsoft/cppwinrt/pull/774 have broken the "Windows Console Application" project template? It no longer generates any headers. The "Windows Runtime Component" project template still works. 

It's the only msbuild-related change since 2.0.201017.1 where this project template still works.

**Comment by jlaanstra** [comment]
@kennykerr This is possible. For a console application, I don't think the C++ tooling automatically adds WinMD references. I think we should update the project template to add them. I'll add submit a PR today.

**Comment by sylveon** [comment]
This also happens for Win32 DLL and GUI projects
