### ISSUE TITLE
Consider adding winrt::to_hstring(char16_t) overload

### ISSUE THREAD

**Issue by marksrasmussen** [microsoft/cppwinrt#783]
Yes, there are already 13 overloads to winrt::to_hstring, but handling char16_t strings would be handy - at least for me.

**Comment by kennykerr** [comment]
You may want to grab a newer version of C++/WinRT.

https://github.com/microsoft/cppwinrt/blob/094921d04b9f3fead1239ab274f0f4d787e7f346/strings/base_string.h#L578-L582

**Comment by marksrasmussen** [comment]
Windows::Foundation::IInspectable const& value = winrt::box_value(winrt::to_hstring(u"Hello"));
produces
error C2665: 'winrt::to_hstring': none of the 13 overloads could convert all the argument types

**Comment by kennykerr** [comment]
Oh, you want a string not a literal (as the title suggests). Yes, that's a bit more involved but doable. Feel free to contribute such a conversion. @DefaultRyan probably has an opinion. 😉

**Comment by DefaultRyan** [comment]
Yeah, should actually be pretty simple. `wchar_t` strings are UTF-16 on Windows, so the `char16_t` overload(s) can simply cast from `char16_t` to `wchar_t` and call. No conversion needed on Windows; reinterpret the bits.

The bigger question is whether `char16_t` support should be narrow (add an overload for `to_hstring` only), or broad (add constructors to `hstring` and `param::hstring` to accept `std::u16string`, `std::u16string_view`, and `char16_t const* const`).

I think there is merit to both approaches. My personal opinion is that Windows developers need to be moving in the direction of promoting cross-platform and interoperability, which means stop being the odd duck and encourage `char16_t` and start a gradual shift away from `wchar_t`, while allowing seamless interop between the two (in my world all the "W" flavored Windows APIs would accept both `wchar_t` and `char16_t`). So I prefer the broader approach.
