### ISSUE TITLE
Watch does not work for IReference<TimeSpan>

### ISSUE THREAD

**Issue by tonuv** [microsoft/cppwinrt#784]
If you are trying to view a Windows::Foundation::IReference<Windows::Foundation::TimeSpan> type in watch then the value is not displayed and debug window shows:

Natvis C++/WinRT: Could not find metadata for Windows.Foundation.IReference`1<Windows.Foundation.TimeSpan>

**Comment by kennykerr** [comment]
The visualizer doesn't support generic types. Unfortunately, we don't have the resources to invest in visualizer improvements at this time.
