### ISSUE TITLE
Use of /Zc:wchar_t breaks IDL generated source with type Char

### ISSUE THREAD

**Issue by marksrasmussen** [microsoft/cppwinrt#787]
Adding IDL type "Char" to the BlankPage template
````namespace BrokenMIDL_Char
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 MyProperty;
        Char MyStationLetter_1;
     }
}
````
and the backing functions
````        wchar_t MyStationLetter_1();
            void MyStationLetter_1(wchar_t value);
````
will succeed only of wchar_t are not treated as built-in type.

**Comment by kennykerr** [comment]
I tried with both `/Zc:wchar_t` and `/Zc:wchar_t-` and all seems well. Perhaps @DefaultRyan can spot something but unless there's more info I don't see a problem here.
