### ISSUE TITLE
cppwinrt.exe does not run on Windows 7

### ISSUE THREAD

**Issue by stl68** [microsoft/cppwinrt#789]
FWIW, I am currently still working on a Windows 7 machine. My new build machine (Win 10) is already sitting on my desk, however I won't have time to set it up for production use for a couple of weeks to come.

Now, I just installed the official C++/WinRT extension from the Visual Studio Marketplace in Visual Studio 2017 and created a new skeleton application using the "Windows Desktop Application (C++/WinRT)" new project wizard. So far this all worked like a charm.

But trying to build this shiny new application immediately fails without any clear indication of the problem (in the VS IDE). Looking into the build log file then reveals the following error (removed the user specific path components):

> [...]\WindowsApplication2\packages\Microsoft.Windows.CppWinRT.2.0.201102.2\build\native\Microsoft.Windows.CppWinRT.targets(674,9): error MSB3073: The command ""[...]\WindowsApplication2\packages\Microsoft.Windows.CppWinRT.2.0.201102.2\build\native\..\..\bin\"cppwinrt @"Debug\WindowsApplication2.vcxproj.cppwinrt_plat.rsp"" exited with code -1073741511

So cppwinrt.exe from the NuGet Package "Microsoft.Windows.CppWinRT.2.0.201102.2" is the culprit here. Manually trying to run this version of cppwinrt.exe on Windows 7 leads to an error message box with the following text:

> The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll

Looking up the documentation for [CreateFile2](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfile2) surely enough specifies the "Minimum Supported Client" as being Windows 8.

I do not know if you dropped Windows 7 from your list of supported build environments. I was under the [impression](https://kennykerr.ca/2019/06/19/cppwinrt-fewer-dependencies/) that C++/WinRT 2.0 on a technical level in fact supports Windows 7 as build environment. At least Visual Studio 2017 happily allows installation of the C++/WinRT extension and offers the C++/WinRT application wizards on Windows 7, which in turn reference the above NuGet package, so I would assume that the intended behavior is that this should work.

**Comment by stl68** [comment]
Some additional bit of information: it is possible to compile the wizard-generated skeleton application by downgrading the NuGet package to "Microsoft.Windows.CppWinRT.1.0.190211.5".

**Comment by kennykerr** [comment]
C++/WinRT itself doesn't use `CreateFile2` so it may be a new dependency of the CRT we're linking against. The actual code produced by C++/WinRT should run on Windows 7, although we don't test or validate that much anymore. I'd get that Windows 10  build machine up and running. 😉
