### ISSUE TITLE
About float2 and "winrt/Windows.Foundation.Numerics"

### ISSUE THREAD

**Issue by 40tude** [Microsoft/cppwinrt#79]
Bonjour
I wanted to use float2 data type
I wrote "using namespace Windows::Foundation::Numerics;" at the top of the source code 
See : https://blogs.msdn.microsoft.com/win2d/2015/06/02/winrt-vector-and-matrix-types-in-windows-10/

Then I wrote "#include "winrt/Windows.Foundation.Numerics" at the end of pch.h
Intellisense tells me it can't find "winrt/Windows.Foundation.Numerics"
I was able to "fix" the issue with a "#include "winrt/Windows.UI.Input.h"
FYI : Using a "#include "winrt/base.h" instead of "#include "winrt/Windows.UI.Input.h" I was able to compile bit not to link the project.

I tought I was following the advises one can read in "Header File Desing.md" file.
Could some one tell me what is wrong in my thinking and what is the best way to include the right header file. In fact, at least for me, it is not obvious to find that if I use float2 I have to use one namespace and include a header file whose name is very different. 

I'm pretty sure I'm missing something however but I can"t find it.

Any advise will be welcome
Best regards, Philippe

**Comment by rhenninger** [comment]
I've had no trouble with using windows numeric in cppwinrt code.  The only glitch I see in the literal code in our post: your using statement also needs winrt in it so you don't accidentally refer to the non-cppwinrt implimentations.  You want: using namespace winrt::Windows::Foundation::Numerics;

Windows numerics structs are defined in WindowsNumerics.impl.h which you get whenever base.h is included.  Since supporting header files get brought in with a specific hearer, almost any winrt/xxx.h will bring in base.h which means it is always there if you refer to any winrt/xxx.h header.  Using statements, on the other hand, must be specific, refer exclusively to the winrt::Windows::xxxx you intend to use as a shortcut for inferring the classes the classes you use.

**Comment by kennykerr** [comment]
Numerics are foundational to the Windows Runtime. As @rhenninger mentioned, the numerics are provided by the Windows SDK and C++/WinRT grafts them into the `winrt::Windows::Foundation::Numerics` namespace. This is implemented by the `winrt/base.h` header, which is directly or indirectly included by every other header in C++/WinRT. Thus, at a minimum you can use the numerics as follows:

```C++
#include "winrt/base.h"

using namespace winrt::Windows::Foundation::Numerics;

int main()
{
    float2 point{ 1.0f, 2.0f };
}
```

**Comment by 40tude** [comment]
Sorry for the delay but the time zone doesn't really help :-)
Anyway, thanks a lot. I went back to my code snippet and with your help I found & corrected my mistakes. 
It was a mix of misunderstanding of header files to be included for Point and float2 on one hand and not using the right namespace identifier on the other plus the fact I was forgetting "winrt::" at the head of the namespace name.
Anyway. I learnt something. Thank you for your time.
My code snippet works and is now similar to : 

```cpp
#pragma comment(lib, "windowsapp")

#include "winrt/base.h"
using namespace winrt::Windows::Foundation::Numerics;

#include "winrt/Windows.Foundation.h"	
using namespace winrt::Windows::Foundation;	

int main()
{
    float2 Mypoint{ 1.0f, 2.0f };
    Point AnotherPoint { 3.0f, 4.0f };
}```

Best regards, Philippe

PS : 
Since  writting "using namespace winrt::xwy::...;" is the thing to do, why this is not what is demonstrated in the samples code. I just re-read "Naming Convention for C++/WinRT types" and I understand many naming conventions can be used. However from the "teaching" point of view I guess it could help if all the samples code would use "using namespace winrt::....".

**Comment by kennykerr** [comment]
Happy to help!

Just a little comment about your last code snippet: place all `#include` directives before namespace `using` directives. This is explained in detailed in rule 59 in the [C++ Coding Standards](http://a.co/dI9Jq9V).
