### ISSUE TITLE
CppWinRT.2.0.201102.2 causes midl.exe internal errors due to including .winmd files from multiple copies of the SDK

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/cppwinrt#790]
I updated to Microsoft.Windows.CppWinRT.2.0.201102.2 (was on 2.0.200729.8) and now get build errors in a console app project that contains a .idl file. midl.exe reports an internal error. 

The response files contents are the problem, containing .winmd references from multiple copies of the SDK.
```
1>    C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\midl.exe /metadata_dir "C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\windows.foundation.foundationcontract\4.0.0.0" /winrt /W1 /nologo /char signed /env x64 /winmd "x64\Debug\Unmerged\MyClass.winmd" /h "nul" /dlldata "nul" /iid "nul" /proxy "nul" /notlb /client none /server none /target "NT60"  /nomidl @"x64\Debug\CppWinRtClient.vcxproj.midlrt.rsp" MyClass.idl
...

1>    Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.17763.0\windows.ai.machinelearning.machinelearningcontract\1.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
...
1>    Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.18362.0\windows.ai.machinelearning.machinelearningcontract\2.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
...
1>    Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.ai.machinelearning.machinelearningcontract\3.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
```
I see #781 might be related. either fixing, or causing this problem.

**Comment by kennykerr** [comment]
@jlaanstra is this related to your recent changes?

**Comment by ChrisGuzak** [comment]
does 2.0.201102.2  include @jlaanstra 's change? how do I map commits to package versions?

**Comment by ChrisGuzak** [comment]
I see I have that change

**Comment by ChrisGuzak** [comment]
I think I spotted the problem, see [my comment](https://github.com/microsoft/cppwinrt/pull/781/files#diff-a6e27a7c76e73432aa99ae7b02962b367a4748eda7d4043997ae67249ab72e58R897) in the PR.

**Comment by kennykerr** [comment]
Thanks Chris. Feel free to contribute a fix. Johan's been the only (volunteer) maintainer of the msbuild support for some time and I'm sure he could do with some support. 😉

**Comment by ChrisGuzak** [comment]
I tried changing that but it did not work.

**Comment by ChrisGuzak** [comment]
Think I found it. See [this comment](https://github.com/microsoft/cppwinrt/pull/781/files#diff-a6e27a7c76e73432aa99ae7b02962b367a4748eda7d4043997ae67249ab72e58R157).

**Comment by AlexBAV** [comment]
This is probably related to https://github.com/microsoft/cppwinrt/issues/785

**Comment by jlaanstra** [comment]
I'll have a look tomorrow.

**Comment by jlaanstra** [comment]
I have a repro. Will add this as a test case to the NuGetTest solution.

**Comment by kennykerr** [comment]
[2.0.201113.7](https://github.com/microsoft/cppwinrt/releases/tag/2.0.201113.7) has now been published.

**Comment by kennykerr** [comment]
Feel free to reopen if this is still an issue.
