### ISSUE TITLE
Codegen should be resilient to param-type name collisions

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#795]
If I have a type defined like this in IDL:

```C#
namespace Foo
{
  runtimeclass Package
  {
    static void DoSomething(Package Package);
  }
}
```

The generated consumption code causes a compile error because it looks something like this:
```c++
namespace winrt::Foo
{
  inline auto Package::DoSomething(Foo::Package const& Package)
  {
    return impl::call_factory<Package, IPackageStatic>([&](IPackageStatic const& f) { return f.DoSomething(Package); });
  }
}
```

This causes a compilation error because the template arg to `call_factory` is not namespace qualified, causing it to be mistaken for the function argument.

The fix is simple: qualify the template type and function params params to `call_factory`, just like the function params are already qualified in the enclosing method definition.

```c++
namespace winrt::Foo
{
  inline auto Package::DoSomething(Foo::Package const& Package)
  {
    return impl::call_factory<Foo::Package, Foo::IPackageStatic>([&](Foo::IPackageStatic const& f) { return f.DoSomething(Package); });
  }
}
```

**Comment by kennykerr** [comment]
I assume you mean:

```
static void DoSomething(Package Package);
```

**Comment by DefaultRyan** [comment]
Yes. Updated the issue.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
