### ISSUE TITLE
Failed to automatically include winmd from Microsoft.Services.Store.Engagement

### ISSUE THREAD

**Issue by zh4ui** [microsoft/cppwinrt#799]
Hi,

The environment has the following nuget packages installed:

* Microsoft.Services.Store.Engagement, 10.1901.28001
* Microsoft.Windows.CppWinRT, 2.0.201113.7

In the project, a reference is added to Microsoft.Services.Store.Engagement.

However, the problem is cppwinrt doesn't include Microsoft.Services.Store.Engagement.winmd when generating the headers. The winmd is found at the path relative to the project root

```
\packages\Microsoft.Services.Store.Engagement.10.1901.28001\SDK\Windows Kits\10\ExtensionSDKs\Microsoft.Services.Store.Engagement\10.0\References\CommonConfiguration\neutral
```

Although an explicit reference to Microsoft.Services.Store.Engagement.winmd can be added manually, isn't it the right expectation that cppwinrt can find it automatically?

**Comment by kennykerr** [comment]
I can confirm the msbuild support includes the [Win2D](https://www.nuget.org/packages/Win2D.uwp) package but fails to include this package. I'm not sure what's different about the two.

@jlaanstra @Scottj1s @ChrisGuzak any ideas?

**Comment by kennykerr** [comment]
I did notice that the internal structure of the nuget package for Microsoft.Services.Store.Engagement is vastly different to any of the others I've seen. This may account for this not working. You may have to unpack it yourself and just reference the winmd and DLLs directly. Unfortunately, the msbuild/nuget support in Visual Studio is mostly geared toward C# projects. Let me know if that works.

**Comment by zh4ui** [comment]
Yeah, manually adding reference to the winmd does work. There seems to be no need for adding reference to the DLLs.

**Comment by kennykerr** [comment]
Glad you got it working.
