### ISSUE TITLE
check_hresult throws if HRESULT is S_FALSE.

### ISSUE THREAD

**Issue by fxb** [Microsoft/cppwinrt#8]
`S_OK` and `S_FALSE` are defined as a success codes, but `check_hresult` only checks for `S_OK`.

This is especially annoying when using setters of properties, which return `S_FALSE` if their value didn't change. Currently one needs to wrap all setters inside a try-catch block or use `obj->put_X`, ignoring the result.

I suggest changing the implementation from

    __forceinline void check_hresult(const HRESULT result)
    {
        if (result != S_OK)
        {
            impl::throw_hresult(result);
        }
    }

to

    __forceinline void check_hresult(const HRESULT result)
    {
        if (FAILED(result))
        {
            impl::throw_hresult(result);
        }
    }

**Comment by kennykerr** [comment]
WinRT APIs should only be using S_OK for success. Do you have an example?

**Comment by fxb** [comment]
@kennykerr: I'm seeing the problem with [SystemMediaTransportControls.PlaybackStatus](https://msdn.microsoft.com/en-us/library/windows/apps/windows.media.systemmediatransportcontrols.playbackstatus)

**Comment by kennykerr** [comment]
Unfortunately, that’s a bug in the PlaybackStatus property and check_hresult should not let it slip through. Thanks for reporting this. We have notified the team responsible for this API.

You can work around it as follows:

```C++
SystemMediaTransportControls controls = SystemMediaTransportControls::GetForCurrentView();

// controls.PlaybackStatus(MediaPlaybackStatus::Paused);

HRESULT hr = controls->put_PlaybackStatus(MediaPlaybackStatus::Paused);

if (FAILED(hr))
{
    throw hresult_error(hr, hresult_error::from_abi);
}
```

This will ensure that any rich error information is propagated along with the HRESULT value.

**Comment by fxb** [comment]
@kennykerr: Thanks for looking into it!

I'm using exactly the workaround you described and will probably have to go with doing the same for any other property setter, since there might be other APIs that return S_FALSE in some cases.

I see that changing `check_hresult` can in turn affect other WinRT APIs, but in that case I would argue that they are buggy as well by using a success code as a failure code (if they return `S_FALSE` in error cases).

[Error handling in COM](https://msdn.microsoft.com/en-us/library/windows/desktop/ff485842(v=vs.85).aspx) specifically says that one should not just test for `S_OK`, since there can be other success codes. I couldn't find any article or documentation about the WinRT APIs revoking this.

Even if WinRT APIs _should_ only use S_OK, there are exceptions, like _PlaybackStatus_. Wouldn't it still make sense to use `FAILED` in `check_hresult`?

**Comment by BrentRe** [comment]
As Kenny mentions, WinRT APIs are prohibited from using S_FALSE. This differs from COM and is a deliberate design decision by the Windows Runtime. As a consequence, no language projection for WinRT will handle S_FALSE as a success value. As such, check_hresult is correct as is and we won't be changing it to allow S_FALSE.

We are working with the team that owns the PlaybackStatus property to figure out the proper fix for that API. If we find any other WinRT property that behaves similarly, we will get those corrected as well. But I know of none at this time.

**Comment by Noemata** [comment]
What project template if any do you use to kick start a C++ UWP solution using cppwinrt (Blank C++ UWP APP)?  It would also be useful to show real XAML integration.  A simple multi-page app would be a good start.  A redo of the RSS reader sample would certainly cover a lot of ground.

**Comment by fxb** [comment]
Okay, makes sense! I will close this issue then.

**Comment by fxb** [comment]
Just adding some more information.

It seems like all properties on SystemMediaTransportControls can return S_FALSE. I used the debugger to log the return values, calling the `set_*` methods with the same value twice:

First call:

    PlaybackStatus: S_OK
    IsPlayEnabled: S_OK
    IsPauseEnabled: S_OK
    IsNextEnabled: S_OK
    IsPreviousEnabled: S_OK

Second call:

    PlaybackStatus: S_FALSE
    IsPlayEnabled: S_FALSE
    IsPauseEnabled: S_FALSE
    IsNextEnabled: S_FALSE
    IsPreviousEnabled: S_FALSE

**Comment by fxb** [comment]
I just noticed that even RoInitialize can return S_FALSE and also will make the winrt::initialize wrapper throw.

**Comment by kennykerr** [comment]
Thanks, we also noticed that the other properties of that class return S_FALSE. We have a bug open to fix those. 

Yes, RoInitialize returns S_FALSE but that function is not part of the WinRT API surface. It is meant to be used by language projections. We make it available as part of C++/WinRT as this is the language projection for the systems programmer. In this case, you just need to be careful not to call it twice from the same thread. In most cases you don’t need to call winrt::initialize at all. It is only really necessary when writing a desktop or console app. For store apps the Visual C++ CRT will call it for you.

**Comment by fxb** [comment]
@kennykerr: Yes, I'm working with a desktop app. At the moment it is easiest to have balanced RoInitialize / RoUninitialize calls.

We currently need to call `RoInitialize(RO_INIT_SINGLETHREADED)`, since `RO_INIT_MULTITHREADED` conflicts with `CoInitialize(COINIT_APARTMENTTHREADED)`, which is required by `ITaskBarList3::ThumbBarSetImageList`.

**Comment by kennykerr** [comment]
If you need balanced calls that support recursion, then you’re probably better off creating a class that calls RoInitialize in its constructor and RoUninitialize in its destructor.

**Comment by kennykerr** [comment]
The issue with S_FALSE has been fixed and will be available in an upcoming version of Windows.
