### ISSUE TITLE
File operations have high memory usage; 10x C#/winrt equivalent

### ISSUE THREAD

**Issue by lawabider** [microsoft/cppwinrt#800]
This uses a 1GB peak on my computer:
`
        auto _root = winrt::Windows::Storage::StorageFolder::GetFolderFromPathAsync(L"c:\\program files\\").get();
        auto _storageFiles = _root.GetFilesAsync(CommonFileQuery::OrderByName).get();
 `
There is also a residual memory usage of maybe 200MB. Initially I assumed "memory leak", but it was explained to me that this is probably a caching implementation;
[https://stackoverflow.com/questions/64938385/uwp-file-operations-give-memory-leaks](https://stackoverflow.com/questions/64938385/uwp-file-operations-give-memory-leaks)

Update:
I've just done a version without get(), by making the following click handler in a C++/winrt app. Could be that get() that has a problem.

`
Windows::Foundation::IAsyncAction MainPage::ClickHandler(IInspectable const&, RoutedEventArgs const&)
    {

        Windows::Storage::Pickers::FolderPicker _folderPicker;
                                                _folderPicker.FileTypeFilter().Append(winrt::hstring(L"*"));

        winrt::Windows::Storage::StorageFolder    _folder = NULL;

        _folder = co_await _folderPicker.PickSingleFolderAsync();
        auto _storageFiles = co_await _folder.GetFilesAsync(Windows::Storage::Search::CommonFileQuery::OrderByName);

        std::wstring    _debugMessage = std::to_wstring(_storageFiles.Size());
        OutputDebugString(_debugMessage.data());

        myButton().Content(box_value(L"Clicked"));
    }
`

**Comment by kennykerr** [comment]
Here's a simple repro:

```C++
#include <winrt/Windows.Foundation.Collections.h>

#include <winrt/Windows.Storage.Search.h>

 

using namespace winrt;

using namespace winrt::Windows::Storage;

using namespace winrt::Windows::Storage::Search;

 

int main()

{

    auto folder = StorageFolder::GetFolderFromPathAsync(L"c:\\windows").get();

    auto files = folder.GetFilesAsync(CommonFileQuery::OrderByName).get();

    printf("%d\n", files.Size());

}
```

I've shared this internally. As a workaround, you can switch to using `CommonFileQuery::DefaultQuery` and the problem goes away. The API owners are aware of this issue and should address it in a future update to the operating system.

**Comment by lawabider** [comment]
Thanks. BTW specifying CommonFileQuery::DefaultQuery is totally different, because this is how to stop it from doing the subdirectories. 
I have done my own recursive version that uses DefaultQuery, but I'm pretty sure that this area of the API is riddled with problems. Hopefully we will see the improvements after Windows updates in the not-too-distant future.

**Comment by kennykerr** [comment]
Good catch - I didn't look at the docs. 😉 

I would use [FindFirstFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilew) or [std::filesystem::directory_iterator](https://en.cppreference.com/w/cpp/filesystem/directory_iterator) (which is just a convenient wrapper around `FindFirstFile`/`FindNextFile`) if possible. Both are very fast.
