### ISSUE TITLE
Produce IntelliSense comments from winmd custom attributes

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#804]
Implements proposal to leverage any attribute named HelpStringAttribute (in any namespace).
This PR will produce comments in the projected code of the form `/// <summary>comment</summary>`, where `comment` is a string stored in a custom attribute named HelpStringAttribute

Assume this IDL:
```idl
namespace Windows.Foundation.Metadata
{
    [attributeusage(target_runtimeclass, target_interface, target_struct, target_enum, target_delegate, target_field, target_property, target_method, target_event)]
    [attributename("helpstring")]
    attribute HelpStringAttribute {
      String Content;
    }
}

namespace test_component
{
    [helpstring("this is an interface")]
    interface InterfaceWithDoc
    {
      [helpstring("this is a function with docs")]
      void f();

      [helpstring("this is a property")]
      Int32 InterfacePropertyWithDoc;
    };

    [helpstring("this is an enum")]
    enum EnumWithDoc
    {
      Dog,
      Cat,
      [helpstring("this is a gecko")] // xmldoc in enum values aren't properly displayed by VS yet
      Gecko
    };

    [helpstring("this is a struct")]
    struct StructWithDoc
    {
      [helpstring("this is the value")]
      Int32 val;
    };

    [helpstring("this is a class")]
    runtimeclass ClassWithDoc
    {
      [helpstring("this is a property")]
      Int32 SomeValue;

      [helpstring("this is a method")]
      void g();
    }
```
With this you get these kind of suggestions:

## on an interface
![image](https://user-images.githubusercontent.com/22989529/100529708-24174d00-319f-11eb-9361-9507d3cbbad9.png)

## on a method in an interface
![image](https://user-images.githubusercontent.com/22989529/100529707-1f529900-319f-11eb-81a9-39eb31918d00.png)

## on a property in an interface
![image](https://user-images.githubusercontent.com/22989529/100529700-0ea22300-319f-11eb-8603-1026203a9d2d.png)

## on enums
![image](https://user-images.githubusercontent.com/22989529/100529694-01853400-319f-11eb-9f69-d0072b19f59e.png)

## on enum values
![image](https://user-images.githubusercontent.com/22989529/100529747-6e003300-319f-11eb-8722-1ddf6945182b.png)

## on structs
![image](https://user-images.githubusercontent.com/22989529/100529689-f3cfae80-319e-11eb-91a8-13ecd4d8dc88.png)

## on struct fields
![image](https://user-images.githubusercontent.com/22989529/100529781-9c7e0e00-319f-11eb-8542-9329859a640c.png)

## on classes
![image](https://user-images.githubusercontent.com/22989529/100529692-fa5e2600-319e-11eb-96ee-0ad463a85444.png)

## on a method in a class
![image](https://user-images.githubusercontent.com/22989529/100529803-cfc09d00-319f-11eb-996c-0ccd76d4b8b1.png)

## on a property in a class
![image](https://user-images.githubusercontent.com/22989529/100529810-e2d36d00-319f-11eb-94a5-ad4b05fd0f7f.png)

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.

**Comment by asklar** [comment]
Yes I am still exploring it. I don't have permissions to reopen though...
