### ISSUE TITLE
Processing XML with cppwinrt and the STL

### ISSUE THREAD

**Issue by MathiasMagnus** [Microsoft/cppwinrt#81]
Hi!

Since documentation of interop with the STL is fairly limited, I wanted to ask a few things about my first attempt at trying to use the library. Bear with me, as I'm a WinRT newbie:

```cpp
int main()
{
    winrt::hstring path{ L"doc.xml" };

    auto file_future = winrt::Windows::Storage::StorageFile::GetFileFromPathAsync(path);

    winrt::Windows::Data::Xml::Dom::XmlDocument doc;

    doc.LoadFromFileAsync(file_future.get());

    auto it = doc.ChildNodes().First();

    using child_node_iter = decltype(it);
    using child_node_interface = decltype(*it);

    std::for_each(it,
                  child_node_iter{},
                  [](child_node_interface node)
    {
        std::wcout << node.InnerText().c_str();
    });

    return EXIT_SUCCESS;
}
```
Questions are:
1. Why doesn't XmlNodeList work with the range-based for loop? It [inherits IVectorView and IIterable](https://msdn.microsoft.com/en-us/library/windows/apps/windows.data.xml.dom.xmlnodelist.aspx), so why the hassle with forcing me to use std::for_each?
2. If ChildNodes().First() is an iterator, couldn't it be a conforming [RandomAccessIterator](http://en.cppreference.com/w/cpp/concept/RandomAccessIterator)? decltype(*it) while works and is terse, I'd rather depend on child_node_iter::value_type, which is known to be a member alias of a conforming STL iterator.
3. Why isn't there an overload for std::wostream operator<<(winrt::hstring) and winrt::hstring_ref? If I'm developing a console application for quick testing (or as an ultimate end result), writing things on the console seems natural enough and the STL allows to overload on non-STL types. Is there a reason to omiting these utilities?
4. Would a recursive XML node iterator have its place in cppwinrt, should there be such a contribution?

**Comment by KevinWelton** [comment]
Thanks for the question, Mathias. 

1) The IIterator returned from ChildNotes().First() is a WinRT type, not a C++ iterator. If we wanted to allow a range based for loop, the XmlDocument.ChildNodes() property would need to contain suitable begin() and end() methods for the for loop. 

The difference in type is also why the for_each code isn't working. The iterator you are playing with is a WinRT iterator that expects to be advanced via the member MoveNext() method, which returns a bool specifying if the iterator is still valid.

2) This is something the team should discuss. Thanks for bringing it to our attention.

3) This is also something we can look at overloading in the future. Thanks for the suggestion. For now, you can use my_h_string.c_str().

4) This isn't something we've discussed at this point.

**Comment by kennykerr** [comment]
Here's an example including a range-based for loop:

```C++
int main()
{
    initialize();

    using namespace Windows::Storage;
    using namespace Windows::Data::Xml::Dom;

    StorageFile file = StorageFile::GetFileFromPathAsync(L"c:\\temp\\doc.xml").get();

    XmlDocument doc = XmlDocument::LoadFromFileAsync(file).get();

    for (IXmlNode child : doc.ChildNodes())
    {
        printf("[%ls]\n", child.InnerText().c_str());
    }
}
```

**Comment by MathiasMagnus** [comment]
Superb, thanks for the tip. My mistake was that I trusted IntelliSense on its squiggly under 'doc', saying there is no suitable .begin() function found, which truly there isn't.

How does this work exactly? Neither XmlNodeList, neither anything that it is implicitly convertible to has a begin method. So why does this compile? (For the sake of understanding.)

**Comment by kennykerr** [comment]
That’s a good question. `ChildNodes` returns an `XmlNodeList`, whose default interface is `IXmlNodeList`. `IXmlNodeList` requires `IVectorView<IXmlNode>`. For the purposes of range-based for loops, the compiler treats the result of the `ChildNodes` method as an `IVectorView`. All of the generic interfaces (like `IVectorView`) in the `Windows::Foundation::Collections` namespace have suitable `begin` and `end` free functions available to the compiler via [ADL](http://en.cppreference.com/w/cpp/language/adl).

**Comment by MathiasMagnus** [comment]
One step closer to understanding 42. 🙂 Awesome library. Keep up the good work!

**Comment by Zingam** [comment]
@MathiasMagnus Don't trust the intellisense... I have wasted time and asked stupid questions because I trusted it! :)

**Comment by MathiasMagnus** [comment]
@Zingam If it weren't for IntelliSense, I wouldn't be using Visual Studio in the first place. MSVC in tandem with IntelliSense is the only reason for someone to put up with MSVCs lag of C++ conformance. We have been lead to believe that the reason why MSVC evolves so slowly is because it has to be kept feature par with IntelliSense.

Anyhow, without relying on IntelliSense, I'd immediately switch over to Visual Studio Code. Even simple things like Open Document don't work there without having to manually setup include dirs there. It is lightyears away from being as friendly as VS.
