### ISSUE TITLE
How to add protected methods returning non-Windows Runtime types to a C++/WinRT base class

### ISSUE THREAD

**Issue by ackh** [microsoft/cppwinrt#811]
Apologies if this is not the right place to ask such questions but I'm really stuck porting a C++/CX code base to C++/WinRT and can't find help anywhere. StackOverflow, [where I asked the same question](https://stackoverflow.com/q/65073839), didn't turn up anything useful and the C++/WinRT documentation that I could find does not help with my problem either.

I got the following C++/CX code that works as intended but would like to convert it to C++/WinRT code:

    namespace My.Custom.Stuff
    {
      [Windows::Foundation::Metadata::WebHostHidden]
      public ref class BaseClass : public Windows::UI::Xaml::Controls::SwapChainPanel
      {
      public:
        BaseClass();
        void PublicMethod();

      protected:
        static ::DirectX::XMFLOAT3 ProtectedMethod();
      };
    }

    namespace My.Custom.Stuff
    {
      [Windows::Foundation::Metadata::WebHostHidden]
      public ref class SubClass sealed : public BaseClass
      {
      public:
        SubClass();
        void UseProtectedMethod()
        {
          // Use the protected method that is provided by BaseClass
          ::DirectX::XMFLOAT3 value = ProtectedMethod()
        }
      };
    }

However, the problem that I encounter is as follows: `BaseClass` contains a protected method that returns a type that cannot be mapped to a corresponding Windows Runtime type. In C++/CX this is not a problem because `ProtectedMethod` is not mapped at all. If I use my Windows Runtime component `ProtectedMethod` is simply not exposed which is what I want.

However, that method should be a member of `BaseClass` because multiple other classes like `SubClass` use the method when implementing their public methods. I have come up with the following C++/WinRT MIDL code:

    namespace My.Custom.Stuff
    {
      unsealed runtimeclass BaseClass : Windows.UI.Xaml.Controls.SwapChainPanel
      {
        BaseClass();
        void PublicMethod();

        // This does not work
        protected DirectX.XMFLOAT3 RgbFromBrush(IInspectable brush);
      }
    }

    import "BaseClass.idl";

    namespace My.Custom.Stuff
    {
      runtimeclass SubClass : BaseClass
      {
        SubClass();
        void UseProtectedMethod();
      }
    }

The problem is that if I define `ProtectedMethod` that way it won't work because `::DirectX::XMFLOAT3` is no Windows Runtime type. If I use any other return type that protected method gets mapped. However, it should not be visible when using that Windows Runtime component and of course I should not have to change its return type.

I then tried to not list `ProtectedMethod` in the MIDL file and instead just add it to the generated header file of `BaseClass` as follows:

    namespace winrt::My::Custom::Stuff::implementation
    {
      struct BaseClass : BaseClassT<BaseClass>
      {
        BaseClass() = default;

      protected:
        static ::DirectX::XMFLOAT3 ProtectedMethod();
      };
    }

However, attempting to use `ProtectedMethod` in `SubClass` results in the following error:

    error C2039: 'ProtectedMethod': is not a member of 'winrt::My::Custom::Stuff::BaseClass'

Here's how I'm using it:

    #include "SubClass.g.h"

    namespace winrt::My::Custom::Stuff::implementation
    {
      struct SubClass : SubClassT<SubClass>
      {
        SubClass() = default;
        void UseProtectedMethod()
        {
          ::DirectX::XMFLOAT3 value = ProtectedMethod();
        }
      };
    }

    namespace winrt::My::Custom::Stuff::factory_implementation
    {
      struct SubClass : SubClassT<SubClass, implementation::SubClass>
      {
      };
    }

How can this be achieved using C++/WinRT?

**Comment by kennykerr** [comment]
@DefaultRyan want to chime in?

**Comment by DefaultRyan** [comment]
I'll pick up the thread over on stackoverflow.

**Comment by ackh** [comment]
Great, my problem is solved now. Thanks a lot @DefaultRyan and @kennykerr for your quick response and help!

I guess I'm going to kick out C++/CX soon :-)
