### ISSUE TITLE
2.0.201113.7 fails to generate headers for C++/CX references

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/cppwinrt#813]
In my project I reference a C++/CX runtime component (that I have under Universal Windows \ Extensions, as it is distributed as a VSIX).
While we're working on moving this component to C++/WinRT, we still need to consume the current version from a C++/WinRT project.
Now this seems to fail on version `2.0.201113.7` of the NuGet package, as the `Library.X.h` headers aren't generated.
I tried to downgrade to `2.0.201102.2` and everything works as expected.

**Comment by FrayxRulez** [comment]
To add some context, the headers fail to compile out of the box, as there's some contructors with an argument named `small`, that is defined as `char` in `rpcndr.h`. I brutally fixed the issue by `#define small small` in my precompiled header.
I don't think that this is the cause of the headers not being generated in newer versions, but still...

**Comment by kennykerr** [comment]
Macros are evil. 😉 

Unfortunately build issues are very problematic. There's an open PR where @jlaanstra is trying to fix some of them. Your best bet is to see whether that may help your issue. 

https://github.com/microsoft/cppwinrt/pull/796
