### ISSUE TITLE
Blank XAML page is not really blank

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#814]
Today the blank XAML page template adds some unwanted code like a stack panel with a button and an int32_t property called "MyProperty". MainPage could have this when the project template "Blank app" is created to teach users how to declare properties in MIDL 3 but for pages created afterwards, it's annoying since I need to remove those every time I add the page. Please remove it and only keep the sample for MainPage.

**Comment by kennykerr** [comment]
Feel free to contribute a PR that removes the unnecessary content.
