### ISSUE TITLE
Possible projection bug in AsyncActionCompletedHandler

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#815]
[AsyncAction.Completed](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncaction.completed?view=winrt-19041) is a delegate of type [AsyncActionCompletedHandler](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.asyncactioncompletedhandler?view=winrt-19041).
This delegate takes 2 params, the first one is a IAsyncAction (param named asyncInfo, which is confusing).
However cppwinrt seems to project this delegate as taking [IAsyncInfo](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IAsyncInfo?view=winrt-19041) instead

ref: https://github.com/MicrosoftDocs/winrt-api/pull/1900
CC @kennykerr

**Comment by kennykerr** [comment]
C++/WinRT defines it however it is defined in metadata, since the C++ definition for `AsyncActionCompletedHandler` is generated entirely from metadata. The metadata for this delegate says that it accepts an `IAsyncAction` followed by an `AsyncStatus` and that's exactly what shows up in the C++/WinRT projection.

**Comment by asklar** [comment]
ok I see what happened:
`AsyncActionCompletedHandler`'s first param is an `IAsyncAction`, this is projected correctly. The param name is `asyncInfo` which is a little misleading. Passing a lambda that takes `IAsyncInfo` instead of `IAsyncAction` works though, but this is because `IAsyncAction` is a subclass of `IAsyncInfo`:
> IAsyncAction inherits IAsyncInfo. Types that implement IAsyncAction also implement the interface members of IAsyncInfo:
https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncaction?view=winrt-19041#interface-inheritance
