### ISSUE TITLE
running cppwinrt inside powershell produces files named nul

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#817]
https://github.com/microsoft/cppwinrt/blob/36759dce3a8d02df954f420118135b5573624750/nuget/Microsoft.Windows.CppWinRT.props#L40-L43

running a command in powershell and redirecting to >nul actually creates a file named nul (which then becomes hard to access via non-PS programs)

**Comment by kennykerr** [comment]
What's the connection between powershell and this props file? I thought this was was processed by Visual Studio itself. Anyway, midlrt requires these null arguments.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
