### ISSUE TITLE
The warning C26800 is raised without a reason

### ISSUE THREAD

**Issue by nseveno** [microsoft/cppwinrt#819]
As suggested by IInspectable in [this StackOverflow question](https://stackoverflow.com/questions/65215135/what-should-i-do-for-warning-c26800), here is a problem with the C26800 code analysis rule.

I have a method in a C++/WinRT component. It produces the code analysis warning C26800, but the code seems to be good.

Here is the code for the method :
```
IAsyncOperation<ReproAnalysisWarning::Class> Class::LoadAsync(AudioGraph graph)
    {
        // the line below produces the warning
        CreateAudioDeviceOutputNodeResult result{ co_await graph.CreateDeviceOutputNodeAsync() };
        if (result.Status() != AudioDeviceNodeCreationStatus::Success)
        {
            throw hresult_error(E_FAIL);
        }

        winrt::com_ptr<Class> obj{ winrt::make_self<Class>(result.DeviceOutputNode()) };
        co_return *obj;
    }
```

Here is the warning :
`C:\Users\***\source\repos\ReproAnalysisWarning\Class.cpp(9): warning C26800: Utilisation d'un objet déplacé : ''graph'' (lifetime.1).`

Here is a minimal repro project :
[ReproAnalysisWarning.zip](https://github.com/microsoft/cppwinrt/files/5678198/ReproAnalysisWarning.zip)

**Comment by kennykerr** [comment]
I'm sorry to give you the runaround, but this looks like a compiler bug that I don't have any control over. The C++ compiler team accepts bug reports here:

https://developercommunity.visualstudio.com/spaces/62/index.html

If you simply share this same repro, they should be able to look into it. 

Regarding that last line, you can write it more simply as follows:

```C++
co_return winrt::make<Class>(result.DeviceOutputNode());
```

**Comment by nseveno** [comment]
Thanks @kennykerr for the answer.
I submitted a bug report to the C++ compiler team...
