### ISSUE TITLE
Support for IEquatable<T> Interface

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#82]
I tried "winrt/Windows.System.h", but no luck. Can you tell me where its located

Thank

**Comment by kennykerr** [comment]
[`System.IEquatable<T>`](https://msdn.microsoft.com/en-us/library/ms131187(v=vs.110).aspx) is a .NET interface, not a WinRT interface.

**Comment by JackDetrick** [comment]
Thanks
