### ISSUE TITLE
Generated winrt/base.h has 2 #pragma warning (disable : ....) statements that are not between warning push/pop

### ISSUE THREAD

**Issue by vbaderks** [microsoft/cppwinrt#826]
The generated winrt/base.h (2.0.201217.4) disables 2 warnings:

```
// Note: this is a workaround for a false-positive warning produced by the Visual C++ 15.9 compiler.
#pragma warning(disable : 5046)

// Note: this is a workaround for a false-positive warning produced by the Visual C++ 16.3 compiler.
#pragma warning(disable : 4268)
```

These #pragma are however not a between a #pragma warning(push) / #pragma warning(pop) construction, which means that these warnings will be also be disabled for all code after the #include <winrt/base.h>

Workaround: wrap #include <winrt/base.h> with push/pop, for example in the pch.h like:

```
#pragma warning(push)
#include <winrt/base.h>
#pragma warning(pop)

```

  
Note: warning 4946 and 5204 also need to be disabled when building with these warnings enabled as base.h will also generate these types of warning with Visual Studio 2019 16.9.0 Preview 2. My current include looks like:

```
#pragma warning(push)
#pragma warning(disable : 4946) // reinterpret_cast used between related classes
#pragma warning(disable : 5204) // class has virtual functions, but its trivial destructor is not virtual
#include <winrt/base.h>
#pragma warning(pop)

```

**Comment by kennykerr** [comment]
Sorry for the delay - I don't think I'll have the time to look into this - feel free to contribute a fix if this is a blocking issue.
