### ISSUE TITLE
Target CppWinRTClean cleans too broadly

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/cppwinrt#828]
The target
```
    <Target Name="CppWinRTClean">
        <ItemGroup>
            <_FilesToDelete Remove="@(_FilesToDelete)"/>
            <_FilesToDelete Include="$(GeneratedFilesDir)**"/>
            <_FilesToDelete Include="$(OutDir)*.winmd"/>
            <_FilesToDelete Include="$(IntDir)*.winmd"/>
            <_FilesToDelete Include="$(IntDir)*.idl"/>
            <_FilesToDelete Include="$(IntDir)*.rsp"/>
            <_FilesToDelete Include="$(CppWinRTMergedDir)**"/>
            <_FilesToDelete Include="$(CppWinRTUnmergedDir)**"/>
        </ItemGroup>
        <Delete Files="@(_FilesToDelete)"/>
    </Target>
```
in `Microsoft.Windows.CppWinRT.targets` cleans too broadly, IMHO.

It is not specifically forbidden to share the `$(OutDir)` folder between projects and we have done so. But in that case, however, the pattern `$(OutDir)*.winmd` not only cleans the merged `winmd` file of this project but also those of other projects.

That target should collect the names of the generated merged `winmd` file(s) and only delete these.

**Comment by kennykerr** [comment]
Can you describe what the problem is with the current approach?

**Comment by FrankHeimes** [comment]
> Can you describe what the problem is with the current approach?

The problem is that the line `<_FilesToDelete Include="$(OutDir)*.winmd"/>` may add files to the delete list that this project has not created itself.

The current approach assumes that the `$(OutDir)` folder is exclusively used by _this_ project and not by any other project.

IMHO replacing the line mentioned above with `<_FilesToDelete Include="$(CppWinRTProjectWinMD)"/>` should fix the problem.

If there are scenarios where multiple merged `winmd` files are created per project then these should be collected (by their names) and added individually to the delete list, as I mentioned above.

**Comment by kennykerr** [comment]
Sorry, I meant what is the negative consequence of this. I understand what you're saying but having a concrete problem may help clarify the importance of a fix and help shape the solution. For example, deleting the temporary build artifacts prevents incremental builds or forces a rebuild unnecessarily or breaks something else.

**Comment by FrankHeimes** [comment]
> Sorry, I meant what is the negative consequence of this

Bummer - I forgot to answer the most obvious question.

We have two dependend projects, A and B. Projects B consumes the `A.winmd` file created by project A. When cleaning project B, the file `A.winmd` is deleted, too. This renders project A out-of-date, too. So it is needlessly rebuilt.

And here, a second problem kicks in: Unfortunately, project A does not reliably detect that it's missing its `A.winmd` file ([reported here](https://github.com/microsoft/cppwinrt/issues/827)). This leads to subsequent MIDL compilation errors in project B, until project A is forcibly rebuild.

**Comment by kennykerr** [comment]
Perfect - thanks!
