### ISSUE TITLE
Consider adding plain COM interfaces that are related to WinRT interfaces to ABI 

### ISSUE THREAD

**Issue by jonitis** [Microsoft/cppwinrt#83]
Hello,

While pondering with cppwinrt I've started to look for best method to access IBuffer data without unnecessary data copying. It turned out there is plain IUnknown derived IBufferByteAccess interface that must be implemented by each WinRT IBuffer interface implementation. Including Robuffer.h causes the namespace ambiguity that you've already described in your blog post.

It would be great if cppwinrt would provide the definitions of interfaces that are related to WinRT runtime as part of the library itself. The problem is that COM interfaces do not have metadata and the Modern compiler can't auto-generate the code. Based on samples from base.h, I wrote something like this:

```
WINRT_EXPORT namespace winrt {

namespace ABI::Windows::Storage::Streams {

struct __declspec(uuid("905a0fef-bc53-11df-8c49-001e4fc686da")) __declspec(novtable) IBufferByteAccess : IUnknown
{
    virtual HRESULT __stdcall abi_Buffer(uint8_t** value) = 0;
};

}

namespace Windows::Storage::Streams {

struct BufferByteAccess : public IBuffer
{
    BufferByteAccess(std::nullptr_t = nullptr) noexcept {}
    
    BufferByteAccess(const IBuffer& buffer) : IBuffer(buffer)
    {
        InitBufferByteAccess();
    }

    BufferByteAccess(IBuffer&& buffer) : IBuffer(std::move(buffer))
    {
        InitBufferByteAccess();
    }

    uint8_t* data() noexcept
    {
        return m_bytes;
    }

    const uint8_t* data() const noexcept
    {
        return m_bytes;
    }

    size_t size() const noexcept
    {
        return Length();
    }

private:
    void InitBufferByteAccess()
    {
        auto byteAccess = try_as<ABI::Windows::Storage::Streams::IBufferByteAccess>();

        if (byteAccess) {
            check_hresult(byteAccess->abi_Buffer(put(m_bytes)));
        }
    }

    uint8_t* m_bytes = nullptr;
};

}

}
```

The caller would look like this:

```
    void TestBufferDataAccess(const IBuffer& buffer)
    {    
        BufferByteAccess bufferByteAccess(buffer);
        auto response = array_ref<uint8_t>(bufferByteAccess.data(), bufferByteAccess.data() + bufferByteAccess.size());

        printf("BufferByteAccess(): size %u\n", (unsigned)response.size());

        for (const auto& b : response) {
            printf("0x%02x ", b);
        }

        printf("\n");
    }
``` 
or this without extra addref/relese:

`            auto bufferResponse = BufferByteAccess(co_await card.GetAnswerToResetAsync());
`

Currently this code sits in my main program, but the declaration of ABI::Windows::Storage::Streams by the analogy of auto-generated headers would have to live in "winrt/internal/Windows.Storage.Streams.???.h" file. I still have not figured out the meaning of the digits in names of header files, except that larger digit is subset of headers with smaller digit. Maybe "*.com.h" suffix then?

Also using winrt::ABI::IBufferByteAccess interface alone would be awkward, since it returns only one pointer, but to access Length() ans Capacity() you would have to use original IBuffer. Would be great to combine functionality of IBuffer and IBufferByteAccess interfaces. Extending the IBuffer would be hard, since you need to add extra code to automatically generated code. And also storing yet another pointer within implementation class would probably be excessive for cases when one does not need the byte access to buffer.

I've just added wrapper class that extends the original IBuffer. In worst case it adds extra AddRef() / Release to the IBuffer that it wraps. In InitBufferByteAccess() get pointer to ABI::Windows::Storage::Streams::IBufferByteAccess, call its abi_Buffer() method and release it. I am not sure whether such wrapper class would also deserve to be part of library, but it can't live in base.h, since we want to include this functionality if programmer includes the "winrt/Windows.Storage.Streams.h" header file and uses "Windows::Storage::Streams" namespace. Again would be nice to have some convention/mechanism to combine autogenerated and manually written header files for each namespace.

Would love to hear back your thoughts on idea of adding WinRT related plain COM interfaces to cppwinrt. Would make the library more self-contained. OTOH I do not know how many more there are such IUnknown derived COM interfaces that may be useful by WinRT programmer.

**Comment by kennykerr** [comment]
This is a known limitation. We will provide built-in support for stream and buffer management in a future update.

Thanks for the feedback!

**Comment by jonitis** [comment]
Thanks!

**Comment by BrentRe** [comment]
We have a sample demonstrating how to use IBuffer et al but it looks like it didn't make it into the repo. We'll get it uploaded.

**Comment by KevinWelton** [comment]
The sample is now available under 10.0.14393.0\Samples\IBuffer.

**Comment by jonitis** [comment]
Thanks for publishing sample! The use of "com" namespace alias kinda resolves that I've tried to achieve, but with less code. Not as awkward as it initially seemed. Add more samples ;-)

**Comment by KevinWelton** [comment]
Glad to help :)

**Comment by jonitis** [comment]
BTW the use of robuffer.h from SDK 10.0.14393.0 with VS 2017 RC does not compile with /permissive- flag. Haven't checked whether 10.0.14393.795 uses new __declspec(uuid("905a0fef-bc53-11df-8c49-001e4fc686da")) syntax.

Without that strict mode the warning is produced:
```
1>c:\program files (x86)\windows kits\10\include\10.0.14393.0\winrt\robuffer.h(46,6): warning C4467: usage of ATL attributes is deprecated
1>[uuid(905a0fef-bc53-11df-8c49-001e4fc686da)]
```

Now I again want cppwinrt to be fully self-contained :)

**Comment by walbourn** [comment]
There are a number of ``/permissive-`` fixes needed in Windows headers. You can try out the Windows 10 Creators Update SDK which is available as a [preview](https://blogs.windows.com/buildingapps/2017/01/13/windows-10-sdk-preview-build-15003-released/).

**Comment by BrentRe** [comment]
A number of system headers are not yet compatible with the /permissive- flag. Work is ongoing to make them more compatible.

However, we will not be changing the C++/WinRT headers to duplicate all the information currently in system headers and become completely standalone. That's a recipe for issues down the line.
