### ISSUE TITLE
Non-void returning delegate generates bad lambda in projection for weak_ref overload

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#837]
If I have a non-void delegate like this:
```cs
// IDL
delegate Boolean MyDelegate();
```

The projected constructor for it that takes a `weak_ref` has a bad lambda:
```c++
template <typename O, typename M> MyDelegate::MyDelegate(weak_ref<O>&& object, M method) :
    MyDelegate([o = std::move(object), method](auto&&... args) { if (auto s = o.get()) { ((*s).*(method))(args...); } })
{
}
```

Notice there's no return statement there, unlike the other generated lambdas. Now I'm not 100% convinced there should be (because who knows what that value should be), but cppwinrt shouldn't be generating a lambda that causes error messages that are difficult for customers to debug.

So, either we should support this for non-void delegates (by returning some sort of "default value" if the `weak_ref` fails to resolve), or we should explicitly not support it (by explicitly deleting this constructor and/or a helpful static_assert message).

**Comment by kennykerr** [comment]
Probably simplest to remove the weak_ref constructor in such cases.

**Comment by kennykerr** [comment]
Feel free to contribute a fix if this is important to you.
