### ISSUE TITLE
UI support in classic desktop apps

### ISSUE THREAD

**Issue by michalo2882** [Microsoft/cppwinrt#84]
Hi,
Is it possible (or will it be) to create UI apps for classic Win32 subsystem?
Currently all samples using UI APIs are projects for UWP.

Regards,
Michael

**Comment by KevinWelton** [comment]
It's not possible to use WinRT UI in a Win32 app. And it's not something we can enable since the limiting factor is WinRT itself. So until fundamental support changes, this isn't an option.

**Comment by BrentRe** [comment]
And to expand on Kevin's response...

You can use C++/WinRT in a Win32 app - just not to call WinRT APIs for UI. The WinRT UI APIs require their use from an UWP app container. However, there are numerous WinRT APIs that can be called from either a UWP process or a Win32 process. E.g. WinRT Networking APIs and similar...

**Comment by walbourn** [comment]
Windows Runtime XAML UI is only supported for UWP applications. The XAML-based UI solution for Win32 classic desktop app is [Windows Presentation Foundation (WPF)](https://msdn.microsoft.com/en-us/library/aa663364.aspx) which is a .NET technology, not a Windows Runtime technology.

**Comment by michalo2882** [comment]
Thanks for explanation!
