### ISSUE TITLE
newbie question about overrideable function call

### ISSUE THREAD

**Issue by oldoldman** [microsoft/cppwinrt#840]
I'm simply deriving from the TextBoxT and expect the OnApplyTemplate get called, but it does not.
```c++
struct MyTextBox : TextBoxT<MyTextBox>
{
  void OnApplyTemplate()
  {}
};
```
In my understanding, ```OnApplyTemplate``` of ```IFrameworkElementOverrides``` is the same as ```OnLaunched``` of ```IApplicationOverrides``` and ```OnLaunched``` get called in the following code
```c++
struct App : ApplicationT<App>
{
  void OnLaunched(LaunchActivatedEventArgs const &)
  {}
};
```
How does this happen? Many thanks!!!

**Comment by kennykerr** [comment]
From the C++ perspective, this looks fine. It may be that Xaml requires a bit more setup for this to work. You may want to check in with the Xaml team. https://github.com/microsoft/microsoft-ui-xaml/
