### ISSUE TITLE
what triggers generation of module.g.cpp

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#846]
Even though I have *.idl files (using view model/idl template from VS), module.g.cpp does'nt get generated. Although each of the idl generate their respective headers and stub implementation.

**Comment by kennykerr** [comment]
You need to use `cppwinrt.exe`'s  `-component` flag.

**Comment by mediabuff** [comment]
Thank you. Added this flag to 'addional parameters ' in the cppwinrt property page. And it works.
