### ISSUE TITLE
Build optimization 

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#847]
The current model is to generate headers for framework and applications projections coupled. When you have lot of projects - this is waste effort, build time and resources. Plus u have to nuget cppwinrt in every project.

can the framework and app headers be separated and also built independently- as framework headers don’t change much.

additionally this has a benefit of sharing the headers across projects or even whole machine.

this will probably align with cswinrt as the projections are tied to a referenced library rather than the consuming app.

**Comment by kennykerr** [comment]
The headers only take a second or two to generate. The issue has to do with how long it takes to compile the headers. Today you can use [precompiled headers](https://docs.microsoft.com/en-us/cpp/build/reference/y-precompiled-headers?view=msvc-160) to avoid recompiling repeatedly. In the future you may be able to use [C++ modules](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-160) to for better effect.
