### ISSUE TITLE
Latest source does'nt compile.

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#848]
Downloaded and ran cppwinrt.sln.

```
1>pch.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt\winrt\impl\Windows.Foundation.0.h(983,26): error C2039: 'wait_for': is not a member of 'winrt::impl'
```

**Comment by mediabuff** [comment]
How do I disable 'windows kit' version of cppwinrt

**Comment by kennykerr** [comment]
The error indicates that you are including cppwinrt headers from the Windows SDK. Those do not get updated regularly. Please refer to the readme on [how to build cppwinrt](https://github.com/microsoft/cppwinrt#building-cwinrt).

**Comment by kennykerr** [comment]
This will project will look for the headers locally, but if you have not generated them then it will fall back and find them in the Windows SDK.
