### ISSUE TITLE
generation of base.h

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#849]
Under what conditions does 'base.h' not get generated ?

I had to force '-base'  option  in my cppwinrt compilation. What could be the cause

**Comment by kennykerr** [comment]
For historical reasons, this has a very specific behavior: 

https://github.com/microsoft/cppwinrt/blob/198a8270d16cead25edec4a63d8792b267539fd5/cppwinrt/main.cpp#L265
