### ISSUE TITLE
Is Decimal struct valid in C++/winRT?

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#85]
This is an issue for a store app conversion from C# to C++/winRT,

**Comment by BrentRe** [comment]
There is no pre-defined WinRT type equivalent to .NET's Decimal. As such, there are no existing WinRT APIs that accept/return a type equivalent to Decimal. And, this, no definition of Decimal in the C++/WinRT headers.

But you can define a C++ struct equivalent to Decimal and use it with C++/WinRT code. C++/WinRT is simply standard C++ after all.

You just need a struct that holds a 96-bit integer, a sign bit and the scale factor (5 more bits). As standard C++ does not interoperate with managed code, you don't necessarily need to get the bits in the identical locations as they are in .NET.

**Comment by JackDetrick** [comment]
Thanks
