### ISSUE TITLE
User control under sub folder- BlankUserControl.xaml.g.hpp not generated

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#850]
The header file that had 'InitializeComponenent' does'nt get generated if the user component is under a project subfolder. This works if the user component in the root folder.

**Comment by kennykerr** [comment]
There are certainly limitations in the way this works today, but it's not something we can easily change at this point as there are too many other tools that depend on it working just the way it does.

**Comment by mediabuff** [comment]
So, we expect all sources be in the project root directory, even for large projects ?

**Comment by kennykerr** [comment]
cppwinrt itself has no such requirements, but it sounds like it might be an issue for xaml. You may want to bring it up with the team here: https://github.com/Microsoft/microsoft-ui-xaml

**Comment by asklar** [comment]
@mediabuff this is a Duplicate of #731
