### ISSUE TITLE
how to pass com interface pointers across winrt interface

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#852]
The new idl 3.0 does'nt allow IUnknown or other com interafaces. I would like to pass around ID3D11Device interface as part of a winrt member function in a winrt api.

Both consumer and producer are c++ implementations.

**Comment by kennykerr** [comment]
You cannot refer to a non-WinRT type from a WinRT API. Generally, this problem is solved by using a COM interop interface. This interop interface is implemented by the WinRT class and callers can query for it explicitly. Various examples of this can be found in the Windows SDK.

**Comment by mediabuff** [comment]
Thank you. I was afraid of that :-)
