### ISSUE TITLE
Windows.UI.Core.Preview namespace not present in cppwinrt 200316.3?

### ISSUE THREAD

**Issue by jevansAN** [microsoft/cppwinrt#859]
Trying to implement the CloseRequested handler for UWP but the namespace doesn't seem to be available - is this still an option? Build is set to minimum 10.0.17134.0 and the winrt version is 200316.3 - as near as I can tell the UI.Core.Preview namespace should require only build 15063. Now I'm wondering if this capability is no longer around. As everything else is working fine I don't want to update winrt or VS 16.5.4 unless necessary.

**Comment by kennykerr** [comment]
C++/WinRT doesn't filter by version. Double check that the input set of winmd files contains the types you're looking for. Ignoring Velocity, nothing should prevent them from showing up like any other.

**Comment by jevansAN** [comment]
Thanks for the quick response! What I needed was to #include  <winrt/Windows.UI.Core.Preview.h> in my pch file. That took me past this bump...

**Comment by kennykerr** [comment]
Yes, includes are still necessary. 😉

**Comment by huangdaohui** [comment]
Same as Windows.UI.Core.AnimationMetrics namespace not present in cppwinrt 210714.1
