### ISSUE TITLE
VS2019 16.9 compile  error: implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines

### ISSUE THREAD

**Issue by Zingam** [microsoft/cppwinrt#866]
I have a UWP/cppwinrt project which I build with CMake. In the latest VS2019 Version 16.9.0 I am unable to compile:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\experimental\coroutine(37,1): fatal error C1189: #error:  The <experimental/coroutine> and <experimental/resumable> headers are only supported with /await and implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines. (compiling source file C:\Users\Application_UWP.cpp) 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\experimental\coroutine(37,1): fatal error C1189: #error:  The <experimental/coroutine> and <experimental/resumable> headers are only supported with /await and implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines. (compiling source file C:\Users\Application_Impl_UWP.cpp) 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\experimental\coroutine(37,1): fatal error C1189: #error:  The <experimental/coroutine> and <experimental/resumable> headers are only supported with /await and implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines. (compiling source file C:\Users\Application.cpp) 
```

**Comment by kennykerr** [comment]
You should only use `/await` if you're targeting C++17. If you're targeting later versions this flag is not required and will cause this error.

**Comment by Zingam** [comment]
I am targeting C++20. I don't use coroutines and I am unable to find /await in the generated project. I was expecting this to be fixed in 16.9 so I didn't complain earlier. If I generate a VS solution and install the Nuget manually I am able to compile but that's really inconvenient as I re-generate the VS solution often.

I think that cppwinrt in the Windows SDK is a supported option?

**Comment by kennykerr** [comment]
Oh, no if you're using cppwinrt from the Windows SDK then this isn't supported. Support for C++20 coroutines was added recently and hasn't made it into the Windows SDK.

**Comment by Zingam** [comment]
Do you mean cppwinrt gets updated only when Windows gets updated and it will eventually be updated?

**Comment by kennykerr** [comment]
C++/WinRT is regularly updated, but the version of cppwinrt in the Windows SDK is the version that was used to build that version of Windows. The trouble is that the Windows SDK is only released for certain major updates, so it can be many months before any improvements/fixes make there way into a public SDK. You're far better off [downloading cppwinrt.exe from here](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT).

**Comment by SpriteOvO** [comment]
Sorry to bother you guys, but I'm having the same problem.
@Zingam I would like to know how you can use a specific new version of winrt in CMake instead of winrt in the Windows SDK.

**Comment by sylveon** [comment]
.nupkg is a zip so you can just download and extract it from cmake or something

**Comment by SpriteOvO** [comment]
@sylveon Thanks for your quick reply! Now I can extract the `cppwinrt.exe` file.

But I am new to `cppwinrt`, and I have been searching for an hour and still haven't found a way to use that specific `cppwinrt.exe` in CMake to replace the one in the Windows SDK to build the project.

Are there any possible solutions other than replacing the binary file in the Windows SDK bin folder?

**Comment by Zingam** [comment]
You can generate the Visual Studio project file and open it in Visual Studio then you can add the Nuget via VS manually.
This is what I do.

**Comment by SpriteOvO** [comment]
@Zingam Unfortunately, I needed CI, so it is impossible to operate in Visual Studio, and I had to modify the code back to use the C++17 standard.

Anyway, thanks a lot for you guys help! :)

**Comment by Zingam** [comment]
It would have been nice if the `vcpkg` port https://github.com/microsoft/cppwinrt/issues/1 didn't look like that:
```
find_path(CPPWINRT_BASE_H
    NAMES winrt/base.h
    PATHS $ENV{INCLUDE}
)

if(NOT CPPWINRT_BASE_H)
    message(FATAL_ERROR "Unable to locate cppwinrt. Please install Windows SDK version 10.0.17134.0 or newer.")
endif()

SET(VCPKG_POLICY_EMPTY_PACKAGE enabled)
```

**Comment by Gavin-Williams** [comment]
What's the deal with this issue for people who aren't using either await or C++/WinRT - like in a legacy console app?

**Comment by SpriteOvO** [comment]
A workaround is mentioned here: https://github.com/microsoft/STL/pull/2132
If you are using C++20, specify `/await` to enable the legacy pre-C++20 coroutine, which will fix the error.

**Comment by Bruniya** [comment]
> Oh, no if you're using cppwinrt from the Windows SDK then this isn't supported. Support for C++20 coroutines was added recently and hasn't made it into the Windows SDK.

Amazing! It solved the problem that had been confusing me for two whole days. Using SDK 10.0.22 or something like that will avoid this issue.

**Comment by MrBeanCpp** [comment]
Update Windows SDK to 10.0.22000.0(with Visual Studio Installer) may help to solve the `cppwinrt` problem. https://github.com/SpriteOvO/AirPodsDesktop/issues/48#issuecomment-1733144738
