### ISSUE TITLE
Generated Add-AppDevPackage.ps1 wants an Add-AppDevPackage.psd1, but doesn't generate one.

### ISSUE THREAD

**Issue by erbrown481** [microsoft/cppwinrt#869]
When you create an app package for sideloading, the generated script expects a resource file to be created, but no resource file is created.

Repro Steps:
Open a c++/winrt project
Project/Publish/Create App Packages…
check Sideloading
Uncheck ‘Enable Automatic Updates’
Next
check ‘Yes, use the current certificate’
Next
Create

In the output directory, there are 3 files:
```
Add-AppDevPackage.ps1
<app>.appxbundle
<app>.cer
```

Go to test machine
copy over all files from output directory
Start powershell
`.\Add-AppDevPackage.ps1 -Path .<app>.appxbundle`

Expect:
App to be sideloaded

Actual:
Error message:
```
Import-LocalizedData : Cannot find the Windows PowerShell data file ‘Add-AppDevPackage.psd1’ in directory
‘Z:\Add-AppDevPackage.resources\en-US’, or in any parent culture directories.
At Z:\Add-AppDevPackage.ps1:55 char:1
Import-LocalizedData -BindingVariable UiStrings -BaseDirectory $Local …
  + CategoryInfo          : ObjectNotFound: (Z:\Add-AppDevPa...DevPackage.psd1:String) [Import-LocalizedData], PSInv
 alidOperationException
  + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

**Comment by asklar** [comment]
@erbrown481 cppwinrt doesn't create these scripts, that's done by the VS tooling. I see you filed an issue in the DevCom site first and you were wrongly pointed to here: https://developercommunity.visualstudio.com/t/Generated-Add-AppDevPackageps1-wants-an/1356666?space=8&entry=problem&q=add-appdevpackage

@MSLukeWest owns this script. Could you please help @erbrown481 and reopen the DevCom ticket?
