### ISSUE TITLE
[regression] Consuming C# component in C++ app results in non-compiling cppwinrt header

### ISSUE THREAD

**Issue by DragonBold** [microsoft/cppwinrt#871]
There problem with the generated source file in cppwinrt.exe

cppwinrt -input "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\CppUnitTestFramework.Universal\16.0\References\CommonConfiguration\neutral\ Microsoft.VisualStudio.TestPlatform.TestExecutor.WinRTCore.winmd" -reference local -output "Generated Files""

The generated source file contains <CLR> and cannot be compiled:

For instance
    template<> struct hash<winrt::Microsoft::VisualStudio::TestPlatform::TestExecutor::WinRTCore::<CLR>UnitTestClient> : winrt::impl::hash_base {};
 

Previous versions of cppwinrt.exe do not <CLR> and compile successfully.

**Comment by DragonBold** [comment]
generated source file
`
  "template<> struct hash<winrt::Microsoft::VisualStudio::TestPlatform::TestExecutor::WinRTCore::<CLR>UnitTestClient> : winrt::impl::hash_base {};
"
`

**Comment by asklar** [comment]
Seeing this too on a sample project; this seems pretty bad... @DragonBold which version of VS are you using? wondering if this might be a regression in VS 16.9 authoring of C# components.

**Simple repro project**: https://github.com/asklar/CLRImplRepro/

![image](https://user-images.githubusercontent.com/22989529/110753633-ac27dc80-81fb-11eb-90e7-3ac5d475c019.png)

**Comment by DragonBold** [comment]
The symptoms are the same.

I'm using Visual Studio 16.9.1.

I checked it here.

CppWinRT.2.0.210211.2　OK
CppWinRT.2.0.210225.3　NG

**Comment by DragonBold** [comment]
The symptoms are the same.

I'm using Visual Studio 16.9.1.
I checked it here.

CppWinRT.2.0.210211.2　OK
CppWinRT.2.0.210225.3　NG

**Comment by kennykerr** [comment]
@DefaultRyan this looks like its related to the winmd reader change.

**Comment by DefaultRyan** [comment]
> @DefaultRyan this looks like its related to the winmd reader change. If you're including non-WinRT types in the cache, then you need to tell cppwinrt to exclude them.

Taking a look at the repro project to confirm.

**Comment by DefaultRyan** [comment]
Confirmed that's the cause of the regression. Filed an issue on winmd and currently working on it. https://github.com/microsoft/winmd/issues/17

**Comment by DefaultRyan** [comment]
> Confirmed that's the cause of the regression. Filed an issue on winmd and currently working on it. [microsoft/winmd#17](https://github.com/microsoft/winmd/issues/17)

Have a PR out now - https://github.com/microsoft/winmd/pull/18
