### ISSUE TITLE
Error on x86 builds with Clang

### ISSUE THREAD

**Issue by arthurbiancarelli** [microsoft/cppwinrt#879]
Hello I'm encountering an issue while compiling with Clang targeting a x86 system

```
In file included from Generated Files\winrt/Windows.Foundation.h:5:
Generated Files\winrt/base.h(8299,9): error : no matching function for call to 'submit_threadpool_callback'
Generated Files\winrt/base.h(8222,17): message : candidate function not viable: no known conversion from '(lambda at Generated Files\winrt/base.h:8299:36)' to 'void (*)(void *, void *) __attribute__((stdcall))' for 1st argument
```

It looks suspiciously related to #496 and implementing a solution inspired from #511 I can successfully compile my project. 

However if I think I understand the problem (The Clang compiler lacks the Visual C++ support for lambdas with stdcall calling convention), I'm not familiar enough with the WinRT code base to understand the potential implications
I've attached the necessary modifications, I'll be happy to create a pull request if theses modifications make sense

[base_coroutine_threadpool.h.patch.txt](https://github.com/microsoft/cppwinrt/files/6116329/base_coroutine_threadpool.h.patch.txt)

**Comment by kennykerr** [comment]
Yes this regression was introduced https://github.com/microsoft/cppwinrt/pull/662 it seems. 

Feel free to contribute a PR - thanks!
