### ISSUE TITLE
C++/CX Interop Sample (for XAML)

### ISSUE THREAD

**Issue by l0calh05t** [Microsoft/cppwinrt#88]
As using actual XAML (not instantiating individual elements in code) is not currently supported, C++/CX or C# remain necessary for Blend-based GUI work. So it would be nice to have a sample where only the XAML/CodeBehind part uses C++/CX

**Comment by JackDetrick** [comment]
I was about to make a similar request.

**Comment by BrentRe** [comment]
The Migrating C++/CX Source Code doc contains examples of how to move back and forth from C++/CX hat types to C++/WinRT projected types. That should provide all the info that you need to interact with CX code. Let us know if it doesn't.

Note that it is relatively tedious to frequently convert back and forth from a hat type to a WinRT type. Typically, you'll have separate silos of code: one using CX types and another using C++/WinRT types. Then you only have to convert when crossing the boundary. As such an approach is very app specific, I'm not sure it makes sense to try and create a sample. Our choices for such silos may not match what you would choose to do.

Regardless though, the doc will show you how to do the conversions.

**Comment by l0calh05t** [comment]
Maybe I'm missing something, but that file only appears to describe how to translate existing C++/CX Code to cppwinrt, not how interop between both would look.

**Comment by MathiasMagnus** [comment]
I too do not quite understand what you would like to see. The closed source XAML compiler emits C++/CX no matter what. It will generate GUI logic based on the XAML file and provide you handler functions to implement with a specific name and signature.

From this point on, it is your responsibility to convert any C++/CX type in the event handler functions to C++/WinRT types and rely solely on these in the implementations of the events. Triggering UI logic from app code might be possible using C++/WinRT, but you definately have to include the compiler generated header file to gain access to the handler name.

The better question would be: are there plans to for the XAML compiler to be able to emit C++/WinRT code instead of C++/CX?

**Comment by Zingam** [comment]
@MathiasMagnus Now that's a great question!

**Comment by l0calh05t** [comment]
@MathiasMagnus while a proper XAML compiler would be nice, I doubt it will happen anytime soon. So for the time being C++/WinRT is not an serious option for GUI. So with a GUI implemented in C++/CX, how would I, for example, use an IAsyncOperationWithProgress that is implemented in C++/WinRT within that GUI? As I said, I am looking for a C++/CX - C++/WinRT interop example, NOT how to translate C++/CX to C++/WinRT.

**Comment by tim-weis** [comment]
@l0calh05t I believe the term *"interop"* doesn't quite hit it. When using C++/WinRT and C++/CX in the same project, you are crossing language boundaries (sort of), not platforms or execution environments (as you would in a mixed C++ and C++/CLI project, for example). Mixing C++/WinRT and C++/CX really boils down to translating between different syntaxes.

That is, once the *cppwinrt.exe* compiler becomes publicly available, and C++ types can be autogenerated from .winmd metadata. Until then you'd have to manually define C++ classes and build .winmd metadata for consumption by C++/CX. While possible, it's neither practical scalable. (The *cppwinrt.exe* compiler is planned to be released.)

@MathiasMagnus XAML support seems to be planned for C++/WinRT, as outlined in a (somewhat) recent [blog entry](https://moderncpp.com/2016/10/13/cppwinrt-available-on-github/) by Kenny Kerr:
> We’re now switching gears to focus on Xaml and component support among other things.

That's not giving away too much information on the features planned. I guess it's safe to assume, that - once done - it will allow writing a fully XAML-ized C++/WinRT application. Visual Studio integration would be great, but I could do without.

**Comment by l0calh05t** [comment]
@tim-weis What else would you call it? I'd consider pinvoke as a form of interop between C and C#, for example. So I take that for now, cppwinrt is simply not a feasible solution for GUI applications.

**Comment by tim-weis** [comment]
@l0calh05t P/Invoke *does* cross a platform boundary, namely from managed code, running on top of the Common Language Runtime (CLR), into native code. A lot of effort goes into marshaling parameters and return values between execution environments. In contrast, C++/CX and C++/WinRT are both essentially C++, sharing the same execution environment. Interface pointers can be freely exchanged between code written in either language. There is no more 'interop' involved than there is when passing a pointer from C code into a library with a C interface.

I do agree, though, that C++/WinRT is currently no match to any of the other programming languages targeting the UWP with respect to UI development. I have touched upon some of the reasons in my previous comment, but lack of C++/CX and C++/WinRT interop is not one of them.
