### ISSUE TITLE
[regression] Apps using DesktopWindowXamlSource start breaking in 2.0.201026.4 nuget

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#884]
Before 2.0.201026.4, a Win32 app could do
 ```cpp
#include <winrt/Windows.UI.Xaml.Hosting.h>
// ...
winrt::Windows::UI::Xaml::Hosting::DesktopWindowXamlSource dwxs{}
```

Beginning in 2.0.201026.4, apps will now get a 
`error C2039: 'DesktopWindowXamlSource': is not a member of 'winrt::Windows::UI::Xaml::Hosting'`

For UWP apps, they can reference the Desktop Extension SDK which contains the Windows.UI.Xaml.Hosting contract.
However, I'm not sure if Win32 apps are able to do that (which is the whole purpose of the hosting apis, i.e. to be used from win32 apps).

**Comment by asklar** [comment]
Workaround for anyone hitting this was to add the following to my win32 app project:

```xml
  <Target Name="AddHostingContract" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <HostingContractPath>$(WindowsSDK_MetadataPathVersioned)\Windows.UI.Xaml.Hosting.HostingContract\4.0.0.0\Windows.UI.Xaml.Hosting.HostingContract.winmd</HostingContractPath>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="$(HostingContractPath)">
        <IsWinMDFile>true</IsWinMDFile>
      </Reference>
    </ItemGroup>
  </Target>
```

**Comment by jlaanstra** [comment]
@asklar can you share a sample project where this worked? I'm happy to take a look.

**Comment by asklar** [comment]
Thanks - yes, here: https://github.com/microsoft/react-native-windows/tree/master/packages/playground/windows
playground-win32.sln is the one

**Comment by asklar** [comment]
@jlaanstra simplified repro:
-	Git clone https://github.com/asklar/Xaml-Islands-Samples.git
-	Git checkout repro
-	NativeXamlIslands.sln
-	Restore
-	Copy Ryan’s cppwinrt.exe that gets you past the first bug
o	Copy \\redmond\osg\teams\CORE\DEP\WinDev\asklar\bin\cppwinrt.exe E:\Xaml-Islands-Samples\packages\Microsoft.Windows.CppWinRT.191111.2\bin\
-	Rebuild and get this error:
4>E:\Xaml-Islands-Samples\Samples\Win32\SampleCppApp\XamlBridge.h(18,40): error C2039: 'DesktopWindowXamlSource': is not a member of 'winrt::Windows::UI::Xaml::Hosting'
4>E:\Xaml-Islands-Samples\obj\Win32\Debug\MyApp\Generated Files\winrt\Windows.UI.Xaml.Hosting.h(166): message : see declaration of 'winrt::Windows::UI::Xaml::Hosting'

**Comment by jlaanstra** [comment]
I am unable to repro with the above steps. Following up offline.

**Comment by jlaanstra** [comment]
This is not a C++/WinRT bug. What’s happening in the repro is that the include path is set to multiple Generated Files folder from multiple different projects, meaning that the same headers exist multiple times on the include path. This is unsupported.

-	SampleCppApp: This is a Win32 app and so we automatically include all the WinMDs from the platform, including extension SDKs.
-	MyApp: This is a UWP where by default no WinMDs from extension SDKs are included.

Because the include paths are mixed, the compiler picks the header from MyApp that doesn’t include the Desktop extension and therefore it can’t find the types. The fix for this is to sort out the include paths. A project should never include the Generated Files folder from a different project in its own include path.

**Comment by amtopel** [comment]
So then how are you supposed to use XAML islands if you can't include the generated files folder from a different project?  The example relies on that.

**Comment by sylveon** [comment]
Install the cppwinrt nuget in every project that needs to use cppwinrt

**Comment by HO-COOH** [comment]
I am running into the same issue. I am using the official sample project [here](https://github.com/microsoft/Xaml-Islands-Samples) , the `NativeXamlIsland.sln`. After uprgading the `cppwinrt` nuget from 
![image](https://github.com/microsoft/cppwinrt/assets/42881734/0f1a40ad-75a8-4db8-a369-525e1bcfdc5e)
 to `2.0.230706.1`, it no longer builds. Both project, the win32 main project and UWP control project obviously has `cppwinrt` nuget installed. Looking into the include directories of the **main Win32 project**, there is `$(AppIncludeDirectories)` which resolves to 2 folders which might be causing the issue.
![image](https://github.com/microsoft/cppwinrt/assets/42881734/78ab56a4-1376-4fe9-82a8-72b213e813e7)

The solution is you remove the unnecessary include in **main Win32 project**, like this
![image](https://github.com/microsoft/cppwinrt/assets/42881734/0bffe2a1-61f3-488c-9e7b-f2bbffe7605d)


If you got everything correct, the generated headers from your UWP project should be copied automatically to the Win32 output project.
![image](https://github.com/microsoft/cppwinrt/assets/42881734/92543616-fc0c-41de-aea5-2587a1c19daa)

You can try using [my modified (removed non C++ project) starting project here](https://github.com/HO-COOH/Xaml-Islands-Samples)

**Comment by sylveon** [comment]
The official docs and samples are pretty horrible. I've done my own setup instead of using their UWP app with a dummy exe hack (this should've never made it to docs) and cppwinrt hasn't ever presented an issue.

**Comment by HO-COOH** [comment]
@sylveon Can you share your setup?

**Comment by sylveon** [comment]
A runtime component project containing the XAML with a reference to it in my main desktop project.

**Comment by HO-COOH** [comment]
@sylveon Thanks, this is exponentially simpler than the official docs and I do get system xaml working. How to make WInUI2 library works then?

**Comment by sylveon** [comment]
It pretty much just works:tm: for me. Any specific issue you're hitting? We can take this offline (on Discord) if you want to, to avoid cluttering people's inboxes.

**Comment by asklar** [comment]
@HO-COOH  see https://github.com/asklar/xaml-islands
