### ISSUE TITLE
[regression] cppwinrt error: WinRT component written in C# UWP does not have a default interface

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#885]
`8>cppwinrt : error Type 'SampleLibraryCS.CircleViewManagerCS' does not have a default interface`

This started to happen with CppWinRT nuget package version **210225.3**. The previous version 210211.2 works fine.

```cs
    class CircleViewManagerCS : IViewManager, IViewManagerWithChildren
    {
...
```

I've tried applying the `Windows.Foundation.Metadata.Default` attribute but I'm not sure how to apply it to a particular interface in the context of the class, I haven't been able to figure out the syntax.

This could share a root cause with #871 
This is currently blocking adoption of new cppwinrt package in React Native for Windows.

Repro: https://github.com/asklar/react-native-windows/tree/cppwinrtUpdate/packages/sample-apps/windows

**Comment by kennykerr** [comment]
Duplicate of #871
