### ISSUE TITLE
C++/WinRT should exercise TestWinRT suite

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#887]
In light of a recent regression, it appears C++/WinRT could use more test coverage.  A big step in that direction would be to run the TestWinRT suite:
https://github.com/microsoft/TestWinRT

**Comment by kennykerr** [comment]
That would be great, although we'd need to add C# components to the test suite.

**Comment by asklar** [comment]
@kennykerr see https://github.com/microsoft/TestWinRT/issues/45 and https://github.com/microsoft/TestWinRT/issues/46

**Comment by asklar** [comment]
Also note that testwinrt as is is broken in several important ways:
- [TestWinRT will fail/crash when consumed from cppwinrt](https://github.com/microsoft/TestWinRT/issues/49)
- [TestWinRT CI does not actually run the test, and uses an old version of cppwinrt to compile](https://github.com/microsoft/TestWinRT/issues/48)
- [TestWinRT console project crashes at launch](https://github.com/microsoft/TestWinRT/issues/47)

**Comment by kennykerr** [comment]
> In light of a recent regression, it appears C++/WinRT could use more test coverage. A big step in that direction would be to run the TestWinRT suite

We don't have the resources to do this at the moment. Given that TestWinRT is written in C++/WinRT, a low-cost (and imperfect) way to do this would be to ensure that TestWinRT is regularly updated to the latest C++/WinRT nuget package.
