### ISSUE TITLE
Can't initialize array_view using initializer list for some runtimeclass types

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#890]
In some runtimeclass types, I get this compiler error when trying to initialize/pass array_view from an initializer list:
`'winrt::array_view<winrt::Develop::ShellView>::array_view(winrt::Develop::ShellView *,winrt::array_view<winrt::Develop::ShellView>::size_type) noexcept': cannot convert argument 1 from 'const _Elem *' to 'winrt::Develop::ShellView *'`

**Comment by kennykerr** [comment]
Can you share a minimal self-contained repro?

**Comment by oldnewthing** [comment]
This is by design. An initializer list is an array of `const` objects, but you are trying to create an `array_view<winrt::Develop::ShellView>` which is a view of mutable objects.

Change the `array_view<winrt::Develop::ShellView>` to `array_view<winrt::Develop::ShellView const>`.
