### ISSUE TITLE
Code generation fails when creating a component with a nested Windows namespaces

### ISSUE THREAD

**Issue by sharath2727** [microsoft/cppwinrt#892]
Description: Introducing a new namespace: Microsoft.Windows.<ComponentName> leads to compilation issues in ProjectReunion. Apparently, the compiler is trying to find ::Windows stuff inside Microsoft::Windows::*.

**Comment by DefaultRyan** [comment]
Problem understood. I'll try to carve out some time to fix this in the next couple days.
