### ISSUE TITLE
SetThreadpoolWaitEx and SetThreadpoolTimerEx are not available in Windows 7

### ISSUE THREAD

**Issue by ysc3839** [microsoft/cppwinrt#894]
IIRC C++/WinRT guarantee support Windows 7, but it uses `SetThreadpoolWaitEx` and `SetThreadpoolTimerEx`, which are available since Windows 8. Is it a bug?

https://github.com/microsoft/cppwinrt/blob/d61cb159be7b0a31ae8e82970aabedf9fcb2fda9/strings/base_coroutine_threadpool.h#L436-L443

**Comment by kennykerr** [comment]
Oops, @oldnewthing looks like your change dropped Windows 7 support. Sorry, I didn't notice this at the time. 

Keep in mind that Windows 7 support is experimental and (obviously) untested, but it makes sense to keep it running unless there's a compelling reason to retire that support.

**Comment by oldnewthing** [comment]
Ugh. let me see what threadpool stuff is available on win7.

**Comment by oldnewthing** [comment]
Hahahaha, SetThreadPoolTimer and SetThreadPoolTimer are exactly the same function! So I can just cut over to the non-Ex version.
