### ISSUE TITLE
Enhancement: provide build-time warnings for light-up APIs requiring TargetPlatformVersion 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#899]
Adobe and others have reported this.  There is a longstanding usability challenge with the TargetPlatformVersion/TargetPlatformMinVersion model, which was created with UWP to enable light-up scenarios.  The challenge is that it's easy to make unprotected calls (via ApiInformation) that will fail catastrophically when running on TargetPlatformMinVersion.  Of course, the obligation is on the developer to test down to that OS version.  But the compiler and/or libraries could help point to potential pitfalls.  

.NET 5 supports this kind of warning via the new TargetPlatformMoniker-based SupportedOSPlatform attribute:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-5.0

C++/WinRT doesn't have the luxury of being able to individually protect API calls and so suppress SupportedOSPlatform-generated warnings, as the C# compiler can.  But it might be possible to detect light-up API calls and generate a single TU-scope warning that can be manually suppressed.

**Comment by jlaanstra** [comment]
Could we add attributes for the api contract where apis were added and convince the static analysis team to generate warnings maybe?

**Comment by Scottj1s** [comment]
Yes, I'm thinking something like that too, similar to how C#/WinRT implements SupportedOSPlatform.

**Comment by kennykerr** [comment]
Feel free to contribute a solution. Unfortunately, we don't have the bandwidth to explore this at the moment.
