### ISSUE TITLE
UWP target Windows Store appxupload

### ISSUE THREAD

**Issue by VSChawathe** [Microsoft/cppwinrt#9]
1. `vcpkg install cppwinrt:x64-uwp cppwinrt:arm-uwp cppwinrt:x86-uwp` seems to triplicate headers. Will later releases refactor them?
2. https://github.com/Microsoft/cppwinrt/blob/master/Getting%20Started.md should cover applying something like https://msdn.microsoft.com/en-us/library/windows/desktop/hh446767(v=vs.85).aspx for making appxupload, specially for builds using alternate IDE like VSCode, for distributing through the Windows Store.

**Comment by BrentRe** [comment]
(1) While I know *of* vcpkg, I'm not familar with how it works. Ideally, you shouldn't get three copies of the headers when installing for three architectures. I would raise this as an issue in the vcpkg repository so they can figure out a solution.

(2) I'm not sure what you are asking here. The link you provide talks about MakeAppx.exe, which doesn't apply to source code such as cppwinrt. We also do not plan on distributing the source code via the Windows Store. This GitHub repository is our distribution vehicle. Happy to respond further if you can clarify the question.

**Comment by VSChawathe** [comment]
2. Using Visual Studio is an overkill considering XAML is unneeded. When building an app consuming C++/WinRT rather than C++/CX for (the app's, and definitely not the GitHub C++/WinRT source repository) distribution, is something like https://msdn.microsoft.com/en-us/library/hh561383.aspx needed prior to making package (assuming MakeAppx is the next step of the development cycle)?

**Comment by BrentRe** [comment]
Regardless of what library(ies) you use (C++/WinRT, Boost, etc.), when you build an application that you want to distribute via the Windows Store, you need to package the app appropriately for upload to the Windows Store.

Clearly, using Visual Studio makes this process lots easier as it has built-in functionality to do this packaging. But if you are not using Visual Studio, you would need to perform this packaging some other way (makefiles, batch scripts, etc.)

**Comment by VSChawathe** [comment]
For C++/CX, the Visual C++ compiler cl.exe required the /ZW switch when making appxupload. (bad example, as there might be whole lot of others, that Visual Studio keeps track of for us). Eventually C++/WinRT will get deeper IDE integration with Visual Studio with it's own UWP porject templates. In the meantime, should /ZW, as an example, be used with C++/WinRT as well, or was it for legacy C++/CX apps only?

**Comment by BrentRe** [comment]
That's up to you. You can use /ZW or not use /ZW when include the C++/WinRT library.

Cl.exe requires the /ZW switch to enable the Windows Runtime extensions (ref class, ref new, hats, etc.). The /ZW switch has nothing to do with the remainder of the build process. It's a C++ compiler-only switch.

**Comment by VSChawathe** [comment]
Wrong. TIL, leaving it gives error APPX0702 . Searching web led to [an unofficial explanation url](http://answers.flyppdevportal.com/categories/metro/nativecode.aspx?ID=ab265db2-d9de-492f-bd66-7af00e3a101e) tl;dr: Without /ZW, no .winmd making clean rebuild fail, i. e. console or desktop program using Store ready WinRT API, rather than actual package for deployment to devices is obtained.
