### ISSUE TITLE
IAsyncOperation<vector<int>> : error C2338: This generic interface has not been specialized.

### ISSUE THREAD

**Issue by jjhegedus** [Microsoft/cppwinrt#90]
I've simplified my code down to the following in my effort to determine the cause.  The code below still causes error C2338.  What is the problem here and how can it be resolved?  Do I need to create a new specialization of IAsyncOperation?

IAsyncOperation<std::vector<int>> TestIAsyncOperationWithVector()
{
    co_await 1ms;

    std::vector<int> vec;
    return vec;
}

This code compiles fine...
IAsyncOperation<int> TestIAsyncOperationWithInt()
{
    co_await 1ms;

    return 1;
}

**Comment by limefrogyank** [comment]
Aha! I know this one... you have to do something like this:
```
template <> struct __declspec(uuid("3a14233f-a037-4ac0-a0ad-c4bb0bbf0139")) __declspec(novtable) IAsyncOperation<std::vector<DirectX::XMFLOAT3>> : impl_IAsyncOperation<std::vector<DirectX::XMFLOAT3>> {};
	
template <> struct __declspec(uuid("3a14233f-a037-4ac0-a0ad-c4bb0bbf0138")) __declspec(novtable) AsyncOperationCompletedHandler<std::vector<DirectX::XMFLOAT3>> : impl_AsyncOperationCompletedHandler<std::vector<DirectX::XMFLOAT3>> {};
```

**Comment by KevinWelton** [comment]
Depending on what you're doing, it may be simpler to use a std::future.

If you want to use a winrt IAsync type, thre previous post is correct. You'll have to specialize the structs mentioned above. Something like this:

```
namespace winrt::ABI::Windows::Foundation {
    template <> struct __declspec(uuid("639E44FD-637C-45B0-ACC4-9AFF342CCA65")) __declspec(novtable) AsyncOperationCompletedHandler<std::vector<int>> : impl_AsyncOperationCompletedHandler<std::vector<int>> {};
    template <> struct __declspec(uuid("273B3484-18DA-4D03-AB02-CF2C3CDBCA01")) __declspec(novtable) IAsyncOperation<std::vector<int>> : impl_IAsyncOperation<std::vector<int>> {};
}
```

If you don't necessarily need the async action to be a WinRT type, you can go the futures route which will simply your code:

```
std::future<std::vector<int>> Sample()
{
    co_await 1ms;
    return std::vector<int>();
}
```

**Comment by BrentRe** [comment]
std::future or similar is the right way to do.

You cannot, in general, use IAsyncOperation with non-WinRT types, such as std::vector. The GUID for all WinRT parameterized interfaces, including IAsyncOperation, is deterministically calculated by MIDL and/or the RoGetParameterizedTypeInstanceIID function (which MIDL uses). And that function only operates on WinRT types. All code that needs the GUID of a parameterized interface calculates it via that function so the GUID you specify the template much match. The GUIDs for such types in our header files is produced by a call to that function.

Additionally, you cannot describe the IAsyncOperation<std::vector> in metadata or IDL for the same reason - std::vector is not a WinRT type. Therefore you will never be able to marshal the interface.

Granted, in some narrow use cases, you might get away with this. But it's an unsupported usage.

**Comment by jjhegedus** [comment]
Thanks all.  I was able to get it working with the suggestion from @limefrogyank with the following...

namespace winrt::ABI::Windows::Foundation
{
    template <> struct __declspec(uuid("3F2F76B5-7CF9-4535-8B91-EC7F74882B81")) __declspec(novtable) IAsyncOperation<std::vector<int>> : impl_IAsyncOperation<std::vector<int>> {};

    template <> struct __declspec(uuid("3F2F76B5-7CF9-4535-8B91-EC7F74882B81")) __declspec(novtable) AsyncOperationCompletedHandler<std::vector<int>> : impl_AsyncOperationCompletedHandler<std::vector<int>> {};
}

However, I was wondering how to determine what the "correct" guid would be.  I ended up just generating a new guid and it did work in my current use case.  I was a little uncomfortable though so I do think I will change it to use std::future.

@BrentRe would you be able to elaborate at all on the use cases that would be problematic.  At this point, I plan to use std:future, this is really just for my education.

**Comment by jjhegedus** [comment]
I was able to use std::future successfully as @KevinWelton suggested so I'm closing this issue.
