### ISSUE TITLE
Add starts_with and ends_with to hstring

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#907]
C++ 20's basic_string has starts_with and ends_with and since hstring's API is designed to look like a wstring, hstring should have these methods

**Comment by Jaiganeshkumaran** [comment]
Seems like wstring actually creates a std::wstring_view and calls it's ends_with and starts_with method respectively

**Comment by sylveon** [comment]
You can do similar with an hstring:
```cpp
winrt::hstring str;

if (std::wstring_view(str).starts_with(L"foo"))
{
    // Code
}
```

**Comment by kennykerr** [comment]
Feel free to contribute these additions - they can be quite handy.
