### ISSUE TITLE
Can't unbox boxed enum type as integral type

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#908]
**Gist**: https://gist.github.com/asklar/1d4345aa28aea565e0f313387a449515

The following code will crash
```cpp
auto ha = winrt::Windows::UI::Xaml::HorizontalAlignment::Right;
auto iinspectable = winrt::box_value(ha);
auto recoveredValue = winrt::unbox_value<int32_t>(iinspectable);
```
This happens regardless of the specific integral type that we unbox to.
It looks like enum values are not projected in a way that supports QI'ing them for `IReference<int32_t>` or similar. 
It would be useful to have this work out of the box.

**Comment by kennykerr** [comment]
The C++/WinRT boxing behavior for enums mimics .NET as this is required for Xaml to work. I'm reluctant to deviate from that pattern as that would put it at odds with C# and unnecessarily complicate boxing internals.

**Comment by asklar** [comment]
Would you consider a new method `winrt::get_enum_value` that doesn't change the behavior of as/try_as instead?

**Comment by sylveon** [comment]
You can test `IsNumbericScalar` from `IPropertyValue` and then call `GetInt32` or similar.

**Comment by asklar** [comment]
thanks @sylveon! that seems to do the trick!
