### ISSUE TITLE
cppwinrt generates an empty output folder

### ISSUE THREAD

**Issue by ZER0** [microsoft/cppwinrt#912]
I'm not sure what I'm doing wrong, I followed the steps described here:

https://github.com/microsoft/cppwinrt/issues/14#issuecomment-585260304

I basically runs `cppwinrt -in local -verbose`, and it creates a `winrt` folder with `impl` subfolder but that's it. Nothing inside both directories, no errors either.  Here the output:
```
 ver:   2.0.200203.5
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.AI.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.ApplicationModel.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Data.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Devices.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Foundation.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Gaming.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Globalization.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Graphics.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Management.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Media.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Networking.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Perception.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Security.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Services.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Storage.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.System.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.UI.Xaml.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.UI.winmd
 in:    C:\WINDOWS\SysNative\WinMetadata\Windows.Web.winmd
 out:   \
 time:  460ms
```

Maybe I'm missing some deps? But there is no errors… Why the .h files are not generated? Is there another way to obtain / create them?

**Comment by ZER0** [comment]
Ok, so apparently I need to add explicitly the `-output` argument as well. If I run:
```
cppwinrt -in local -verbose -output .
```

It creates the folder in the same place as before, but this time with all the files.

I think there is something wrong then when `output` is omitted, it doesn't work as expected.

**Comment by kennykerr** [comment]
Yes, I had noticed this a while back as well. The output option should default to "." but it was defaulting to "", which subsequently confused the path builder.
