### ISSUE TITLE
Error in Image Content Pipeline

### ISSUE THREAD

**Issue by jjhegedus** [Microsoft/cppwinrt#92]
Is it possible to use the Image Content Pipeline with ccpwinrt?

I have tried a number of tests, including just adding an image to the OCR sample, adding the build customization for the pipeline, setting the properties of the image to use the pipeline and re-building.  Even this simple test fails with the error below.

Error	MSB4184	The expression "[MSBuild]::MakeRelative(Debug\x64\, C:\Projects\Git\cppwinrt\10.0.14393.0\Samples\Ocr\Debug\x64\placeholder.dds)" cannot be evaluated. Invalid URI: The format of the URI could not be determined.	Ocr	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\VsGraphics\ImageContentTask.targets	27

**Comment by kennykerr** [comment]
I'm sorry but I don't now what the "Image Content Pipeline" is.

**Comment by jjhegedus** [comment]
Hi Kenny, thanks for responding.

The image content pipeline is part of tooling integrated with the Visual Studio build process for transforming content into formats that are more friendly for usage with DirectX.  In this case, what I was trying to do was to use the pipeline to convert from a .png to a .dds file format and package it into my app.

Here is a link to an article on msdn that describes it in more detail - https://msdn.microsoft.com/en-us/library/hh972446.aspx.

**Comment by walbourn** [comment]
The use of the content pipeline shouldn't have anything to do with C++/WinRT. It works fine with my C++/WinRT templates. It may be an issue with the sample projects.

**Comment by jjhegedus** [comment]
Are you referring to templates you have online?  
I'd like to compare if possible.

**Comment by jjhegedus** [comment]
Never mind, I see them under your directx-vs-templates.  I'll take a look and see if I can figure out what's different and causing the problem.  Thanks

**Comment by jjhegedus** [comment]
Chuck, I've confirmed that this works for me if I create a project from your templates.  So it isn't a problem with the set up of my machine.  I have yet to nail down exactly what is causing the problem.

**Comment by jjhegedus** [comment]
OK, I've found what appears to be the issue.  The Output Directory for the sample projects is set to "$(Configuration)\$(Platform)\".  If I select "<inherit from parent or project defaults>" it resets to "$(SolutionDir)$(Platform)\$(Configuration)\" and the image content pipeline runs as expected.

I haven't follow the whole chain of the build logic so I can't say exactly why.

Is this an important setting for some other functionality of cppwinrt and the associated projects or is it of no consequence to change it?

**Comment by jjhegedus** [comment]
I see this particular configuration wouldn't support multiple platform development but that if I change it to "$(SolutionDir)$(Configuration)\$(Platform)\"  it looks like it reproduces the results of the original but using the full path.

The relative path for the Output Directory looks like it was the problem for the Image Content Pipeline, something I'm sure I would have run into with the other pipelines as I move forward.

I also changed the Intermediate Directory from "$(Configuration)\$(Platform)\temp\" to "$(SolutionDir)$(Configuration)\$(Platform)\temp\" because it like it might have eventually caused a similar issue.

Does those sound like reasonable changes to make to the samples?

**Comment by walbourn** [comment]
You could just remove the elements ``<OutDir>`` and ``<IntDir>`` from the sample vcxproj entirely and let them default. That's what happens in my templates.

**Comment by jjhegedus** [comment]
Yes, that was actually my first solution, two comments above, reset to "inherit from parent or project defaults", unfortunately, I included the gt and lt symbols above causing the text not to display.  Sorry about that.  I'll update it to get the text showing.

The only difference in setting back to the default is that it switches the order of the folders from config->platform which is set in the cppwinrt samples to platform->config.  I don't expect that it would cause any issues but it had to be explicitly set so perhaps there was a reason.

**Comment by jjhegedus** [comment]
I guess I'll go ahead and close this issue.  Would you be able to accept a pull request with a couple of small updates to the project properties?  If so, which approach would you prefer, setting it back to the default, or setting it so "$(SolutionDir)$(Configuration)$(Platform)"?  I think this is a great initiative and I'd love to help in any way I can.
