### ISSUE TITLE
winrt::impl::error_ok and friends are duplicated in each translation unit

### ISSUE THREAD

**Issue by dmachaj** [microsoft/cppwinrt#921]
I was running a binary size analysis tool on our optimized binary and the "wasteful duplication" analysis flagged `winrt::impl::error_ok` and all of the other errors in that same block.  These are `constexpr` so they are in the readonly segment, as expected, but they are duplicated.  According to this tool they are 4 bytes each, duplicated 42 times, and add up to 168 bytes _each_.  That adds up to roughly 3KB of our final binary being copies of these error codes.

This can be fixed by changing `constexpr` to `inline constexpr`.  That syntax will result in them being de-duped to a single copy.  It requires C++17, but cppwinrt already requires that so it shouldn't be a problem.

**Comment by matbech** [comment]
@dmachaj I'm curious, what binary size analysis tool are you using?

**Comment by sylveon** [comment]
Shame, such a tool sounds really useful

**Comment by AlexBAV** [comment]
When I saw this issue, my first impulse was to ask the same question as @matbech.

But then I remembered Bruce Dawson (https://randomascii.wordpress.com/) was once referring to similar tool and after some googling I found that it is called `ShowGlobals` and is part of Google Chromium repository. You can clone and compile it.

As a hint, the following command will probably need to be executed (in elevated command prompt) before using it:

```
regsvr32 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\DIA SDK\bin\amd64\msdia140.dll"
```

The actual path to DIA DLL may differ.

**Comment by sylveon** [comment]
Seems like the tool is public now: https://www.microsoft.com/en-us/p/sizebench/9ndf4n1wg7d6

**Comment by kennykerr** [comment]
Yep!
