### ISSUE TITLE
What is the state of C++20 modules support in C++/WinRT?

### ISSUE THREAD

**Issue by pjmlp** [microsoft/cppwinrt#923]
I am having a go at porting a sample C++/WinRT application, while the cross platform C++ libraries are already compiling with the current VS 2019 C++20 modules support, I cannot find anywhere what the current state of C++/WinRT is, speciall how to integrate the code that gets generated from the IDL compiler.

Any official information available somewhere about the current support, or related roadmap?

**Comment by Jaiganeshkumaran** [comment]
There's a file named "winrt.ixx" for module support but I don't know whether that works or not.

**Comment by kennykerr** [comment]
Yes, there's experimental support for C++ modules via winrt.ixx - feel free to give that a try. Last time I checked there was some incompatibility with C++ modules and C++ coroutines that I wasn't sure how to fix.

**Comment by pjmlp** [comment]
What about the code that gets generated from customer IDL files for XAML applications?

Thanks for replying, so it seems pretty much WIP.

**Comment by kennykerr** [comment]
The `cppwinrt` tool generates headers from winmd files. IDL files are parsed by the `midlrt` tool and generates the winmd files. I haven't given much  thought to how it might work with Xaml applications.

**Comment by sylveon** [comment]
From a quick look there doesn't seem to be any module support for producers, only consumers.

And the `winrt.ixx` file is only for things in the `Windows.*` namespace, but that can probably be adjusted.

**Comment by pjmlp** [comment]
Given the feedback I assume XAML tooling in the context of C++20 modules for production delivery, is something that might be available long term, and most likely dependent on Project Reunion evolution regarding the role of C++/WinRT for XAML applications.

It also answered my question about the current state of module support, as such I am closing the issue. Thanks for the feedback.
