### ISSUE TITLE
FullTrustProcessLauncher is not a class or namespace name

### ISSUE THREAD

**Issue by EmmettTsai** [microsoft/cppwinrt#925]
From NuGet version: 2.0.201217.4, can not find class FullTrustProcessLauncher
and current last version still not work 2.0.210403.2

build error:
1>D:\Project\VS\WinRT\BlankApp1\BlankApp1\MainPage.cpp(16,9): error C2653: 'FullTrustProcessLauncher': is not a class or namespace name
1>D:\Project\VS\WinRT\BlankApp1\BlankApp1\MainPage.cpp(16,35): error C3861: 'LaunchFullTrustProcessForCurrentAppAsync': identifier not found
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(482,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.

but NuGet version 2.0.201215.2 is work fine.

Is FullTrustProcessLauncher class remove from cppwinrt?

My test step:
1. Create A Blank WinRT UWP Project, use default project settings
2. Add a Desktop Console Application Project
3. Add a Packaging App Project, and add both project into packaging Applications
4. Use FullTrustProcessLauncher api to launch Desktop Console Application
5. Switch NuGet version and rebuild and run Packaging App Project

**Comment by kennykerr** [comment]
I can't repro. C++/WinRT doesn't know anything about specific classes like `FullTrustProcessLauncher`. Instead it simply generates code based on type information found in .winmd metadata files. If types are missing, make sure you're referring to all of the necessary .winmd files and then make sure you include the necessary namespace headers. For example: 

`#include "winrt/Windows.ApplicationModel.h"`

**Comment by EmmettTsai** [comment]
Thank you @kennykerr , I am not add winmd reference, only include `"winrt/Windows.ApplicationModel.h"` , after add `Windows.winmd` and `Windows.ApplicationModel.FullTrustAppContract.winmd`, I can build and run success  at last version cppwinrt.
