### ISSUE TITLE
Allow non-agile delegates and IAsyncXxx for use from services

### ISSUE THREAD

**Issue by oldnewthing** [microsoft/cppwinrt#927]
Services operate inside a COM context, and objects cannot escape that context without going through a disconnectable proxy. This ensures that the service can respond to shutdown requests by disconnecting its outstanding objects (CoDisconnectContext). All C++/WinRT objects default to agile, but most of them permit opt-out via `non_agile`.

Known exceptions to this are the C++/WinRT implementations for delegates and IAsyncXxx, which are always agile.

(Non-agile delegates are useful in other contexts, like forcing event handlers to run on the UI thread.)

Another case is the built-in implementation of IErrorInfo (`error_info_fallback`), but this is unlikely to be a problem because it is used only when RoOriginateLanguageException is unavailable, so we can just say that C++/WinRT from services is not supported on Win7.

**Comment by kennykerr** [comment]
It might be simplest to add a `WINRT_NON_AGILE` macro to change the default for projects that need it.

**Comment by kennykerr** [comment]
Feel free to reopen if this is something you'd like to pursue.
