### ISSUE TITLE
License: Use of files generated by cppwinrt?

### ISSUE THREAD

**Issue by Echolon** [microsoft/cppwinrt#929]
Hello everyone,

I would like to ask how the license of cppwinrt applies to the files generated? Can we publish those under the same license? We would like to distribute those with the software we are creating.

One further point: I think that the explicitly-licensed files distributed with windows SDK are too old and have undesireable dependencies that the current version doesn't have. Any comments on this?

That would be really appreciated!

Kind regards

**Comment by kennykerr** [comment]
@BenJKuhn / @sotteson1 any thoughts? My impression is that the [MIT license](https://github.com/microsoft/cppwinrt/blob/master/LICENSE) applies to everything, but I'm not a lawyer.

**Comment by kennykerr** [comment]
I noticed the headers in the Windows SDK are also licensed under MIT so I would assume the same goes for these as they are ultimately the same header files just shipped in the SDK.
