### ISSUE TITLE
array_view constructor is too generous about accepting vector of derived classes

### ISSUE THREAD

**Issue by oldnewthing** [microsoft/cppwinrt#932]
```cpp
int main()
{
    auto vec = winrt::single_threaded_vector<winrt::Windows::Foundation::IInspectable>();
    vec.Append(winrt::box_value(1));

    // pick your poison
#if POISON==1
    winrt::Windows::Foundation::Uri v[1] = { nullptr };
#elif POISON==2
    std::vector<winrt::Windows::Foundation::Uri> v(1, { nullptr });
#elif POISON==3
    std::array<winrt::Windows::Foundation::Uri, 1> v = { nullptr };
#endif

    vec.GetMany(0, v);
    auto uri = v[0].AbsoluteCanonicalUri(); // crashes

}
```
This code compiles without any warnings or errors, but crashes.

The reason is that `GetMany` takes an `array_view<IInspectable>`, and it is legal to construct an `array_view<IInspectable>` from an `array_view<Uri>` thanks to these constructors:

```cpp
        template <typename C, size_type N>
        array_view(C(&value)[N]) noexcept :
            array_view(value, N)
        {}

        template <typename C>
        array_view(std::vector<C>& value) noexcept :
            array_view(data(value), static_cast<size_type>(value.size()))
        {
        }

        template <typename C, size_t N>
        array_view(std::array<C, N>& value) noexcept :
            array_view(value.data(), static_cast<size_type>(value.size()))
        {}
```

These constructors work because `C` is `Uri`, and `value` / `data(value)` / `value.date()` are `Uri*`, which is convertible to `IInspectable*` since `IInspectable` is a base class of `Uri`. (These constructors were probably written under the assumption the the `array_view` is being used for reading, not writing.)

`array_view<const T>` is contravariant in `T` under certain conditions; however, `array_view<T>` is read-write and should allow only exactly `T`.

```cpp
        // if T is non-const
        template <size_type N>
        array_view(value_type(&value)[N]) noexcept :
            array_view(value, N)
        {}

        array_view(std::vector<value_type>& value) noexcept :
            array_view(data(value), static_cast<size_type>(value.size()))
        {
        }

        template <size_t N>
        array_view(std::array<value_type, N>& value) noexcept :
            array_view(value.data(), static_cast<size_type>(value.size()))
        {}
```

The conditions under which you can treat `array_view<C>` as `array_view<const T>` are if

* `T` is a reference type, and
* `T` is a pointer-interconvertible base of `C`: `std::is_pointer_interconvertible_base_of_v<T, C>`.

Since C++/WinRT's minimum C++ version is C++17, we cannot use `std::is_pointer_interconvertible_base_of_v<T, C>`. However, we also know that Windows Runtime interfaces do not support multiple inheritance, so we can apply a more restrictive test that still covers the cases we care about:

* `T` is a reference type, and
* `T` is a base class of the default interface of `C`.

Conversely, `GetMany` or any other method that takes a `ref T[]` can be more accommodating of the types of `array_view`s it is given: Output `array_view`s are covariant in `T`. For output, C can be different from T, provided

* `T` is a reference type, and
* `C` is a base class of the default interface of `T`.

Expressing these rules via SFINAE in the `array_view` constructors and in the code generation of `ref T[]` parameters will require a good amount of template metaprogramming. (Maybe we need a `params::array_view`.)

**Comment by kennykerr** [comment]
More reason to move to C++20 and `std::span` - and get rid of `winrt::array_view`. 

I expect we'll move to C++20 once OS projects are able to select that language target. Until then, I don't think its worth tweaking `array_view` further.
