### ISSUE TITLE
Improve intellisense documentation experience for parity with C# and C++/CX

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#933]
Visual Studio's Intellisense has built-in support for parsing documentation from xML files. For C# and C++/CX, this lights up more or less automagically when it finds an XML next to a .NET dll or winmd, respectively. Also, the object browser shows this documentation when browsing .NET dlls and winmds (provided an appropriate XML is found in the same directory).

Here's the Object Browser showing the XML documentation (see highlighted text at lower right)
![image](https://user-images.githubusercontent.com/26174284/116735236-17439300-a9a3-11eb-9559-4f14c27ae82d.png)

Here's C++/CX showing the XML documentation in code
![image](https://user-images.githubusercontent.com/26174284/116735668-b6688a80-a9a3-11eb-865d-b2f2377948ce.png)

When it comes to C++/WinRT, there's less magic happening behind the scenes, which is lots of goodness. But we use cppwinrt to generate headers from the winmds, so the IDE isn't aware of the connection between the projected types and the winmd which spawned them. Because of this, it doesn't open the XML documentation.

Let's improve this tooling/experience gap.

Possible approaches:
- We could work with Visual Studio to see if their Intellisense model allows us to associate the projection with the winmd and/or XML docs.
  - I have no idea if this is plausible, let alone feasible, but this would be attractive if this ability exists.
  - One possible advantage if this works is that if localized XML files exist, the correct one will be automatically used by Intellisense.
- Enhance cppwinrt to read an XML file, extract the documentation, and insert it as [Intellisense-friendly comments](https://docs.microsoft.com/en-us/cpp/build/reference/xml-documentation-visual-cpp?view=msvc-160) in the projection headers.
  - The upshot of this is that we wouldn't be dependent on a Visual Studio feature that may not exist, and the documentation would be more self contained.
  - One downside is that because the documentation is directly inserted into the generated headers, it won't automatically localize. This can be partially worked around by pointing cppwinrt at the user's desired localized XML. For example, the Windows SDK doesn't ship with a "default" XML, but ships with several localized XMLs under subfolders (e.g. `References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\en\Windows.Foundation.FoundationContract.xml`. However, I'm not sure how to extract the current user's localization settings in MSBuild so it can be passed to the cppwinrt command line.

As an experiment for the second approach, I added some formatted comments to some generated projection headers, and ended up with the expected experience:
```c++
// In winrt\impl\Windows.Foundation.0.h ...

    template <typename D>
    struct consume_Windows_Foundation_IUriRuntimeClass
    {
        /// <summary>Gets a fully canonical RFC-compliant representation of the current URI.</summary>
        /// <returns>The canonical URI.</returns>
        [[nodiscard]] WINRT_IMPL_AUTO(hstring) AbsoluteUri() const;
...
    };
```
```c++
// In winrt\impl\Windows.Foundation.2.h ...

    /// <summary>Defines an object that represents a Uniform Resource Identifier (URI) value and parses it into components. The Uri object is used by many other Windows Runtime APIs that are not necessarily confined to web browser scenarios.</summary>
    struct __declspec(empty_bases) Uri : Windows::Foundation::IUriRuntimeClass,
        impl::require<Uri, Windows::Foundation::IUriRuntimeClassWithAbsoluteCanonicalUri, Windows::Foundation::IStringable>
    {
...
        /// <summary>Initializes a new Uri object from the specified Uniform Resource Identifier (URI) string. Initializing the Uri also parses the string and populates the Uri properties that represent Uniform Resource Identifier (URI) components.</summary>
        /// <param name="uri">The string from which the new Uri object is created.</param>
        explicit Uri(param::hstring const& uri);

        /// <summary>Initializes a new Uri by combining a base Uniform Resource Identifier (URI) and a relative Uniform Resource Identifier (URI). Initializing the Uri also parses the combined string and populates the Uri properties that represent Uniform Resource Identifier (URI) components.</summary>
        /// <param name="baseUri">The base Uniform Resource Identifier (URI).</param>
        /// <param name="relativeUri">The relative Uniform Resource Identifier (URI).</param>
        Uri(param::hstring const& baseUri, param::hstring const& relativeUri);
...
    };
```
(Hover over type with cursor)
![image](https://user-images.githubusercontent.com/26174284/116747522-e23f3c80-a9b2-11eb-89f0-eb333c1ab1d7.png)

(Autocomplete a member)
![image](https://user-images.githubusercontent.com/26174284/116747735-3813e480-a9b3-11eb-9c28-c389152e197b.png)

(Autocompleting params in a constructor)
![image](https://user-images.githubusercontent.com/26174284/116747945-81fcca80-a9b3-11eb-832f-e62bc7442bb1.png)

**Comment by sylveon** [comment]
I am definitely a fan of the second approach, because it also allows light up in other IDEs like VS Code, Qt Creator, CLion and etc.

**Comment by kennykerr** [comment]
@sylveon do the other IDEs support the same XML comment format?

**Comment by sylveon** [comment]
No, but Visual Studio<sup>1</sup> and all the IDEs I listed support [Doxygen](https://en.wikipedia.org/wiki/Doxygen) comments as an alternative. And even if XMLDoc is used, those IDEs can add support for this much more easily than needing to special case cppwinrt.

![image](https://user-images.githubusercontent.com/6440374/116749211-97cbb900-a9ce-11eb-9bf0-ea6570d912de.png)

1: https://devblogs.microsoft.com/cppblog/doxygen-and-xml-doc-comment-support/

**Comment by kennykerr** [comment]
Feel free to reopen if this is something you plan to work on.

**Comment by Psychlist1972** [comment]
@kennykerr @DefaultRyan Did anything ever happen in this space? Lack of auto doc generation is a real bummer for API work. I was hoping I could stick xml comments in the IDL, but I read the different issues here and found out that's a hard "no" right now.

**Comment by sylveon** [comment]
IDL has no support for XML docs at the moment. I was thinking of leveraging https://github.com/asklar/midl-langserv from @asklar at some point to generate a separate XMLdoc file from comments on the IDL (though my intent was to make these light up in C#, not C++, in which case this was the only thing needed. C++ light up would require cppwinrt codegen support)

**Comment by asklar** [comment]
at one point I did have the start of changes to MIDL to support outputting an xmldoc file, but sadly had to put it in the back burner. @jonwis / kenny perhaps we can work together to find someone who can take it over the finish line?

**Comment by JaiganeshKumaran** [comment]
@Psychlist1972 Using attributes in IDL is an option where you can then write a tool to reflect on the generated WinMD and create an XML comments file but localisation is harder with this and the size of the WinMD can get large.

**Comment by Psychlist1972** [comment]
@JaiganeshKumaran that's a good idea. I probably don't have time to write any sort of tool right now (unless it saves significant time immediately). But it would be good for there to be solutions which work for all the /WinRT projects (C++, CS, RS). Agreed on loc.

**Comment by Psychlist1972** [comment]
Another person had mentioned doxygen on my repo, but I dismissed it because I didn't think it worked with MIDL 3.0. However, I see it does understand IDL. Has anyone used it with C++/WinRT IDL files?

**Comment by sylveon** [comment]
The solution is xmldocs... But only C# and C++/CX support them. C++/WinRT has no kind of doc gen/consumption support.

**Comment by asklar** [comment]
another solution is to define your API in C# - where you can use XDC, and use CsWinMD (*) to produce the metadata and consume it from C++. 
To use cswinmd:
- create a C++ library project where your api implementation will live
- add a C# file to it, e.g. cppcomponent.cs, where you define the api
- in your C++ project:
```xml
<!-- import microsoft.windows.cswinmd.props and targets -->
  <ItemGroup>
    <CSharpCppComponent Include="CppComponent.cs" />
  </ItemGroup>
```

(*) we need to publish that nuget, it lives here: https://github.com/microsoft/CsWinRT/blob/master/nuget/Microsoft.Windows.CsWinMD.nuspec and the pipelines are set up but they are dependent on someone setting `_PublishCsWinMD` in the pipeline. @manodasanW could you run the pipeline with that so that we get it published to nuget.org?

**Comment by Psychlist1972** [comment]
@asklar definitely an interesting approach. But that ship has sailed here. All the API code here is C++/WinRT and the IDL is part of the C++/WinRT solutions. I did original prototypes in C# (where I'm more proficient anyway), but it had too many limitations for this. C++/WinRT has a ton of magic going on which requires the IDL in the project.

**Comment by asklar** [comment]
To be clear, you would still use C++/WinRT. This just gets rid of the MIDL compiler step. Instead of IDL, you define the interface in C#. The implementation in both cases stays the same, in C++/WinRT.
