### ISSUE TITLE
Visualizer should fall back to raw display of members

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/cppwinrt#938]
When the debug visualizer is unable to display a type, it instead presents:
"<Object uninitialized or information unavailable>"

In this case, it should also fall back to displaying the raw members (e.g., _ptr) of the type so that the developer at least has addresses to explore, etc.

**Comment by kennykerr** [comment]
Feel free to contribute a solution. Unfortunately, we don't have the bandwidth to explore this at the moment.
