### ISSUE TITLE
Why do I get BadContinuationParamType in this conversion?

### ISSUE THREAD

**Issue by johanlindfors** [Microsoft/cppwinrt#94]
Trying to convert an existing function that returns a Concurrency::task and I'd like to keep the method signature if possible. But after I've done the easy conversions as specified in the existing documents, I get a compilation error on the "return create_task(getFileTask)" line, claiming the following error:

no suitable user-defined conversion from "Concurrency::task<Concurrency::details::_BadContinuationParamType>" to "Concurrency::task<std::vector<byte, std::allocator<byte>>>"
 
Original method:

```
// Function that reads from a binary file asynchronously.
inline Concurrency::task<std::vector<byte>> ReadDataAsync(const std::wstring& filename)
{
	using namespace Windows::Storage;
	using namespace Concurrency;

	auto folder = Windows::ApplicationModel::Package::Current->InstalledLocation;
	auto getFileTask = folder->GetFileAsync(Platform::StringReference(filename.c_str()));
	
        return create_task(getFileTask)
		.then([] (StorageFile^ file)  {
		return FileIO::ReadBufferAsync(file);
	})
		.then([] (Streams::IBuffer^ fileBuffer) -> std::vector<byte>  {
		std::vector<byte> returnBuffer;
		returnBuffer.resize(fileBuffer->Length);
		Streams::DataReader::FromBuffer(fileBuffer)->ReadBytes(Platform::ArrayReference<byte>(returnBuffer.data(), fileBuffer->Length));
		return returnBuffer;
	});
}
```

Converted to winrt:

```
// Function that reads from a binary file asynchronously.
inline Concurrency::task<std::vector<byte>> ReadDataAsync(const std::wstring& filename)
{
	using namespace winrt::Windows::Storage;
	using namespace Concurrency;

	auto folder = winrt::Windows::ApplicationModel::Package::Current().InstalledLocation();
	auto getFileTask = folder.GetFileAsync(filename);

	return create_task(getFileTask)
		.then([](StorageFile const & file) {
		return FileIO::ReadBufferAsync(file);
	})
		.then([](Streams::IBuffer const & fileBuffer) -> std::vector<byte> {
		std::vector<byte> returnBuffer;
		returnBuffer.resize(fileBuffer.Length());
		Streams::DataReader::FromBuffer(fileBuffer).ReadBytes(winrt::array_ref<byte>(returnBuffer));
		return returnBuffer;
	});
}
```

What am I doing wrong?

**Comment by jjhegedus** [comment]
I haven't tried exactly the way you are doing it, continuing to use the ppl but I have had success with this using coroutines

`    inline std::future<std::vector<byte>> ReadDataAsync(const std::wstring& filename)
    {
        winrt::Windows::Storage::Streams::IBuffer fileBuffer = co_await winrt::Windows::Storage::PathIO::ReadBufferAsync(winrt::hstring_ref(filename.c_str()));

        std::vector<byte> returnBuffer;
        returnBuffer.resize(fileBuffer.Length());
        winrt::Windows::Storage::Streams::DataReader::FromBuffer(fileBuffer).ReadBytes(winrt::array_ref<byte>(returnBuffer));
        return returnBuffer;
    }`

**Comment by johanlindfors** [comment]
Thanks!

Inspired by your sample, this is the result which now works just fine, I'll leave the "continue to use PPL" to a later time...

```
inline std::future<std::vector<byte>> ReadDataAsync(const std::wstring& filename)
{
	auto folder = winrt::Windows::ApplicationModel::Package::Current().InstalledLocation();
	auto file = co_await folder.GetFileAsync(winrt::hstring_ref(filename.c_str()));
	IBuffer fileBuffer = co_await FileIO::ReadBufferAsync(file);
	std::vector<byte> returnBuffer;
	returnBuffer.resize(fileBuffer.Length());
	DataReader::FromBuffer(fileBuffer).ReadBytes(winrt::array_ref<byte>(returnBuffer));
	return returnBuffer;
}
```
