### ISSUE TITLE
IMemoryBufferReference should have a data method

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#944]
IBuffer has a data method in the C++/WinRT projected version but IMemoryBufferReference doesn't. I think IMemoryBufferReference should also have a data method so it will be easier to get the data than casting to IMemoryBufferByteAccess.

**Comment by kennykerr** [comment]
No objections - feel free to contribute a similar extension to what is currently provided for `IBuffer`.
