### ISSUE TITLE
Generated headers should use #pragma once in addition to header guard

### ISSUE THREAD

**Issue by DHowett** [microsoft/cppwinrt#945]
Headers that have a header guard are still processed in full by the preprocessor.

Since C++/WinRT doesn't use any tricks that require the header files to be multiply-included, it could emit a `#pragma once` at the beginning of each generated header.

This will allow the compiler (or preprocessor, as it were) to use at least one clever optimization:

A compiler that supports `#pragma once` could keep an inode cache of the files that have been included.
This would allow it to completely skip preprocessing the file to find the header guard at the point of `#include`

**Comment by MikeGitb** [comment]
> Headers that have a header guard are still processed in full by the preprocessor.

Just wondering: Have you actually verified that? My understanding is that most modern compilers actually automatically implement the described optimization when they see the classic header guard pattern even without `#pragma once`

**Comment by kennykerr** [comment]
Yes, I've never seen any numbers to show that this helps. I've only seen anecdotal evidence that this helps in some cases with some versions of some compilers. 

But its common practice. STL does this:

```C++
#pragma once
#ifndef _MAP_
#define _MAP_
.
.
.
#endif // _MAP_
```

While the MIDL-generated headers flip it around and add a second `ifdef` for good measure: 

```C++
#ifndef __windows2Eui2Ecomposition_h__
#define __windows2Eui2Ecomposition_h__
#ifndef __windows2Eui2Ecomposition_p_h__
#define __windows2Eui2Ecomposition_p_h__
#pragma once
.
.
.
#endif // __windows2Eui2Ecomposition_p_h__
#endif // __windows2Eui2Ecomposition_h__
```

Who knows why. 😊

**Comment by DHowett** [comment]
I've learned that I should likely assume that common legacy patterns have already been supremely optimized. I definitely came into this with no data to back me up. :smile:
