### ISSUE TITLE
warning C4459: declaration of 'last' hides global declaration

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#947]
In my preview build of VS I get the following warning when using /std:c++latest:

base.h(3546,1): warning C4459: declaration of 'last' hides global declaration
chrono(813,32): note: see declaration of 'std::chrono::last'
base.h(3546): note: while compiling class template member function 'winrt::array_view<const winrt::hstring>::array_view(const winrt::hstring *,const winrt::hstring *) noexcept'

**Comment by jlaanstra** [comment]
You can see the definition of last here: https://github.com/microsoft/STL/blob/68145cbc22f25fd9936a58d05b261c5c5767a38a/stl/inc/chrono#L813

**Comment by jlaanstra** [comment]
This happens when a cpp file includes base.h and also uses 

```
using namespace std::chrono
```

Which is often done for convenience in cpp files.

**Comment by kennykerr** [comment]
This doesn't repro on the non-preview version and I can't seem to get VS Preview installed correctly even after 17GB of program files... 

What line is `base.h(3546)` in your build? There are a few references to `last` in `base.h` as well as in some of the extensions for collections. 

The convention in C++/WinRT to avoid name collisions is to add `winrt_impl_xxx` to the front of a name. So you could replace `last` with `winrt_impl_last`.

**Comment by jlaanstra** [comment]
I believe this is coming with VS 2019 Update 10, which should soon reach non-preview status. I am running into this while testing VS2022.

Line 3546 has this:

```
        array_view(pointer first, pointer last) noexcept :
            m_data(first),
            m_size(static_cast<size_type>(last - first))
        {}
```

/cc @StephanTLavavej

**Comment by StephanTLavavej** [comment]
That's correct, `std::chrono::last` first appeared in [VS 2019 16.10 Preview 1](https://github.com/microsoft/STL/wiki/Changelog#vs-2019-1610-preview-1).

**Comment by kennykerr** [comment]
I cannot repro this with "Version 16.10.0 Preview 4.0".

**Comment by jlaanstra** [comment]
@kennykerr are you using /std:c++latest?

**Comment by kennykerr** [comment]
Yes.

**Comment by sylveon** [comment]
Can you provide a minimal repro?

**Comment by StephanTLavavej** [comment]
Note that VS 2019 16.10 was released for production use today. Also note that this shadow warning [is level 4](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4459?view=msvc-160) so the warning level option may be involved.
