### ISSUE TITLE
coroutine module support

### ISSUE THREAD

**Issue by Agrael1** [microsoft/cppwinrt#951]
Please add line exporting std::coroutine_traits for all coroutine types,
right now if any type is used inside a module with `import winrt;` coroutine traits tend to break up.

Proposal, at the generated header of Windows.Foundation.h
at line 3856 add macro WINRT_EXPORT
so it would look like WINRT_EXPORT namespace std

**Comment by sylveon** [comment]
I'd suggest adding WINRT_EXPORT to the template specializations directly instead of the whole namespace.

**Comment by kennykerr** [comment]
Have you tested that coroutine export+import works after this change? Last time I tried, I still ran into various compiler bugs. If you can get it to work, feel free to contribute a PR.

**Comment by Agrael1** [comment]
Yes, I did a manual export of those templates as the standard suggests, but I found out that the entirety of winrt.ixx is not working, I'm running latest preview:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.11.0 Preview 1.0

it compiles, but even smallest example is not working (just an empty project with removed pch)
and even if it compiles, then process looses the entry point for some reason

Further investigation is required

**Comment by kennykerr** [comment]
Feel free to reopen if you plan to work on this issue.
