### ISSUE TITLE
should we be checking HRESULT of IBufferByteAccess::Buffer()?

### ISSUE THREAD

**Issue by dlech** [microsoft/cppwinrt#957]
While implementing #956, I noticed that the return value of the call to `IBufferByteAccess::Buffer()` is not checked. Should we be checking this?

https://github.com/microsoft/cppwinrt/blob/f204e39d293c3c54dc1df65f05ed6a9c650ac6b1/cppwinrt/code_writers.h#L1305-L1310

**Comment by kennykerr** [comment]
The expectation is that if Buffer fails that a nullptr is returned. No other failure is expected.
