### ISSUE TITLE
Implementing an interface using winrt::implements doesn't seem to implement other required interfaces

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/cppwinrt#958]
Today implementing an interface using winrt::implements doesn't implement other required interfaces unless specified separately. Is this the intended behaviour?

**Comment by sylveon** [comment]
What's a require interface.

**Comment by kennykerr** [comment]
The WinRT metadata defines a required interface as one that must be implemented along with another. For example, IAsyncAction requires IAsyncInfo. Some languages project this as IAsyncAction inheriting IAsyncInfo but the underlying COM interfaces are unrelated. WinRT expects that an implementation of IAsyncAction can be queried (via QueryInterface) for an implementation of IAsyncInfo.

**Comment by kennykerr** [comment]
And to answer the original question, the implements class template doesn't automatically include required interfaces. It is not driven by metadata.

**Comment by JaiganeshKumaran** [comment]
Could you consider changing this behaviour? It becomes too verbose to specify every required interface and sometimes you forget to do it.
