### ISSUE TITLE
IAsyncOperation<TResult> breaks IntelliSense

### ISSUE THREAD

**Issue by vinderguy** [microsoft/cppwinrt#964]
# About the problem
I noticed that when you put either `co_await` or `co_return` in the body of `IAsyncOperation<TResult>`, the IntelliSense stops working completely within the file that contains the function. The syntax is no longer highlighted and no suggestions are given. Restarting Visual Studio or rebuilding the solution doesn't help. The only way to bring IntelliSense back to work is to remove all `co_await` and `co_return` keywords.

![image](https://user-images.githubusercontent.com/26736457/122923108-9b434700-d364-11eb-914c-a2fa4c315a3d.png)

# How to reproduce
1. Launch Visual Studio 2019 (the version I'm using - v16.10.2).
2. Create a **Windows Console Application (C++/WinRT)**.
3. Write a simple function, which return type is `IAsyncOperation<hstring>`. The `TResult` doesn't have to be ` hstring`.
4. Use either `co_await` or `co_return` within the function body.
5. Notice that the IntelliSense no longer works within the entire file until you manually remove all occurrences of `co_await` and `co_return` from that function.

The function I wrote:
```cpp
IAsyncOperation<hstring> SomeRandomOperation()
{
    HttpClient client;
    Uri uri{ L"https://example.com" };

    hstring result = co_await client.GetStringAsync(uri);

    // IntelliSense stops working just after typing the "co_await" keyword. 
    // The syntax is no longer highlighted and no suggestions are given.

    int32_t someRandomVariable = 123;

    return result;
}
```

# Software details
OS version:  **10.0.19043**
Visual Studio 2019 version: **16.10.2**
Extension version: **2.0.210505.3**
NuGet package version: **2.0.210621.3**

# Closing

I am not exactly sure if this is a **C++/WinRT** issue or if there is something wrong with my environment. Anyway, I tried everything from simply rebuilding the solution to reinstalling the entire Visual Studio. Any help would be greatly appreciated.

**Comment by vinderguy** [comment]
I've successfully reproduced the issue on a newly created virtual machine.

**Comment by kennykerr** [comment]
Thanks for the report, however the Visual Studio team requests that you use their feedback tool for issues with tooling:

https://developercommunity.visualstudio.com/search?space=62

**Comment by sylveon** [comment]
https://developercommunity.visualstudio.com/t/IntelliSense-stops-working-when-inside-a/1407261
