### ISSUE TITLE
Failure to generate headers for 10.0.19042.0

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/cppwinrt#967]
I'm attempting to generate some headers for the ~Project Reunion~ Windows App SDK, and I'm getting the following error:

> error: Could not read the Windows SDK's Platform.xml

For the following command line:

`cppwinrt -input . -output include -reference 10.0.19042.0`

If I specify the latest version via `-reference sdk` (which is `10.0.19042.0`) then this will work, as well as explicitly setting a previous version `-reference 10.0.18362.0`.

I've tried with cppwinrt versions: 

> C++/WinRT v2.0.190620.2

and

> C++/WinRT v2.0.210505.3

Which is the latest version available at the time of writing.

I've diffed the  `10.0.18362.0\Platform.xml` and `10.0.19042.0\Platform.xml` files, and can't see anything obviously broken. 

I've attached the `10.0.19042.0\Platform.xml` (as text file for upload purposes).
[Platform.txt](https://github.com/microsoft/cppwinrt/files/6725095/Platform.txt)

**Comment by sylveon** [comment]
There is no 19042 SDK version AFAIK, it's all 19041 still. Maybe that could be why?

**Comment by MarkIngramUK** [comment]
Boy do I feel stupid now. Thanks @sylveon . The issue has come from using CMake's `CMAKE_SYSTEM_VERSION` which is set to `10.0.19042`. I have no idea why it's set to that, and not `10.0.19041` ...
