### ISSUE TITLE
Should I bother converting Microsoft::WRL::ComPtr to winrt::com_ptr?

### ISSUE THREAD

**Issue by johanlindfors** [Microsoft/cppwinrt#97]
While working on a DirectX sample (available for test in PR: https://github.com/Microsoft/cppwinrt/pull/96) I stumbled upon this:

Should I at all be trying to convert the Microsoft::WRL::ComPtr fields to winrt::com_ptr? I have tried but haven't been able to convert the ".GetAddressOf()" or ".As(...)" and get the project to compile.

Maybe I shouldn't bother?

**Comment by walbourn** [comment]
If you want a pure C++/WinRT sample, then you should use ``winrt::com_ptr``. It's as you say not a trivial substitution, but they are equivalent. This avoids some quirks you'd encounter if you include both WRL and C++/WinRT headers in the same module--basically namespace resolution for ``Windows`` and ``Windows::Foundation`` namespaces need ``winrt::`` because WRL includes a few templates in those namespaces you can't avoid.

That said, you can stick with ``Microsoft::WRL::ComPtr`` and just deal with the quirks, although you can limit your include to just ``#include <wrl/client.h>``. Since I'm sharing code between C++/WiinRT, /ZW, and desktop I'm sticking with ``Microsoft::WRL::ComPtr`` in my [templates](https://github.com/walbourn/directx-vs-templates).

**Comment by johanlindfors** [comment]
I've managed to update most of the WRL::ComPtr references to winrt::com_ptr but I'm still struggling with some calls.

I have the following Cpp/CX code which defines the following with WRL:

main.h

Microsoft::WRL::ComPtr<ID3D11Buffer>		m_vertexBuffer;

This is then used a couple of times by the following calls:

HRESULT ID3D11Device::CreateBuffer(
  [in]            const D3D11_BUFFER_DESC      *pDesc,
  [in, optional]  const D3D11_SUBRESOURCE_DATA *pInitialData,
  [out, optional]       ID3D11Buffer           **ppBuffer
);

Calling code: m_deviceResources->GetD3DDevice()->CreateBuffer(
		&vertexBufferDesc,
		&vertexBufferData,
		&m_vertexBuffer
		)


void ID3D11DeviceContext::IASetVertexBuffers(
  [in]                 UINT                StartSlot,
  [in]                 UINT                NumBuffers,
  [in, optional]       ID3D11Buffer *const *ppVertexBuffers,
  [in, optional] const UINT                *pStrides,
  [in, optional] const UINT                *pOffsets
);

Calling code: context->IASetVertexBuffers(
		0,
		1,
		m_vertexBuffer.GetAddressOf(),
		&stride,
		&offset
		);

I've tried to naively convert this code to the following winrt calls:

```
winrt::com_ptr<ID3D11Buffer>		m_vertexBuffer;

m_deviceResources->GetD3DDevice()->CreateBuffer(
		&vertexBufferDesc,
		&vertexBufferData,
		winrt::get(m_vertexBuffer)
		);

...

context->IASetVertexBuffers(
		0,
		1,
		winrt::get(m_vertexBuffer),
		&stride,
		&offset
		);
```
But that doesn't work since the IASetVertexBuffers seems to expect an array of ID3D11Buffer.

What is the recommended/simple conversion for this use?

**Comment by tim-weis** [comment]
@johanlindfors I believe the `winrt::com_ptr` equivalent to `GetAddressOf()` is the free function template `put`. The following code snippet

    Calling code: context->IASetVertexBuffers( 0,
        1,
        m_vertexBuffer.GetAddressOf(),
        &stride,
        &offset );
can be replaced with

    Calling code: context->IASetVertexBuffers( 0,
        1,
        put( m_vertexBuffer ),
        &stride,
        &offset );
While WRL's member function `GetAddressOf()` describes what it does, C++/WinRT has decided to convey intent. As a matter of personal preference I do like the choice of C++/WinRT better.

I don't know how to convert the `As(...)` member, but issue #68 has information on that. Maybe this is helpful to you.

**Comment by johanlindfors** [comment]
Thanks @tim-weis but the compiler complains when replacing the .GetAddressOf with you suggestion with the following messages:

expression must be an lvalue or a function designator

**Comment by tim-weis** [comment]
@johanlindfors I'm sorry, I should have been more diligent and verified my suggestion. Taking the address of an rvalue expression that refers to a temporary cannot work. I'm not sure how to fix the code, other than using a crude workaround and go with a proper array, something like this:

    ID3D11Buffer* const buffer[] = { get( m_vertexBuffer ) };
    context->IASetVertexBuffers( 0,
        1,
        buffer,
        &stride,
        &offset );

**Comment by johanlindfors** [comment]
Awesome @kennykerr that works like a charm!

Keep up the great work, it looks great so far!
