### ISSUE TITLE
Compiling app with C++20 throws warnings in cppwinrt headers

### ISSUE THREAD

**Issue by asklar** [microsoft/cppwinrt#974]
`...\Generated Files\winrt\impl\Windows.UI.Xaml.Controls.0.h(16492,74): warning C4505: 'winrt::impl::consume_Windows_UI_Xaml_Controls_IContentControl<winrt::Windows::UI::Xaml::Controls::IContentControl>::Content': unreferenced local function has been removed`

We should do something to make sure a stock app compiles clean/without warnings.

**Comment by kennykerr** [comment]
It doesn't look like C++20 is yet a supported language:

![image](https://user-images.githubusercontent.com/9845234/124964080-6e826700-dfd5-11eb-9459-c53e6abbffdc.png)

Anyway, using "preview/latest" doesn't produce a warning when building the default "blank app" template.

**Comment by sylveon** [comment]
The switch will be there in 16.11 and 17.0.

**Comment by kennykerr** [comment]
Feel free to reopen if there is a repro or you plan to work on this.
