### ISSUE TITLE
Possible data races in weak_ref and implements

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/cppwinrt#975]
In this excerpt of `weak_ref::Resolve`,
```
if (m_strong.compare_exchange_weak(target, target + 1, std::memory_order_acquire, std::memory_order_relaxed))
{
    int32_t hr = m_object->QueryInterface(id, objectReference);
    m_strong.fetch_sub(1, std::memory_order_relaxed);
    return hr;
}
```
the refcount decrement is relaxed, presumably because the interface handed out by `QueryInterface` will do the actual release synchronization, further up the callstack. But if `QueryInterface` fails, this unsynchronized decrement could pose a problem. On top of that, if `m_object` gets released in the interim by another thread, we could be doing a relaxed decrement of the strong refcount to zero without running `m_object`’s destructor. Changing this decrement to `m_object->Release()` should fix both issues.

I’ve also noticed that `weak_ref::decrement_strong` and `implements::subtract_reference` are using release ordering, while `weak_ref::Release` is using relaxed ordering. But there is no corresponding acquire fence to ensure all accesses happen before deleting the object on a different thread. `weak_ref::Release` should be upgraded to release ordering, and an acquire fence should be placed before deleting objects in `weak_ref::Release` and `root_implements::NonDelegatingRelease`.

**Comment by kennykerr** [comment]
It doesn't seem to be an urgent issue and isn't known to be the source of any issues in practice. Feel free to contribute a fix, otherwise I'll probably close this issue if there's no further action taken.
