### ISSUE TITLE
Vsix not installing to vs2022 due to cyclic dependency error 

### ISSUE THREAD

**Issue by TheEndHunter** [microsoft/cppwinrt#984]
When I Attempted to run the vsix file from the marketplace for installing C++/WinRT to vs2022 I encountered an error(Log Attached Below) that says there is a cyclic dependency on   Microsoft.VisualStudio.ComponentGroup.UWP.VC --> Microsoft.VisualStudio.ComponentGroup.UWP.VC

The Log Contains the error.

[dd_VSIXInstaller_20210717150550_2370.log](https://github.com/microsoft/cppwinrt/files/6834820/dd_VSIXInstaller_20210717150550_2370.log)

I can provide more if needed just ask and ill try my best to get.

**Comment by raffaeler** [comment]
I also hot this problem today and I was going to open an issue.
I was wondering whether the VSIX is really compatible with VS17 or the manifest does not restrict the VS version correctly

**Comment by Link1J** [comment]
This is a Visual Studio 2022 issue, not a C++/WinRT issue. It has already been reported to the Visual Studio Team.
https://developercommunity.visualstudio.com/t/unable-to-update-from-preview-11-to-preview-20-a-c/1476321

**Comment by TheEndHunter** [comment]
Ok, thankyou for getting back, i shall close the issue then
