### ISSUE TITLE
How is the `-pch` command-line parameter supposed to be used?

### ISSUE THREAD

**Issue by syndek** [microsoft/cppwinrt#985]
I've been attempting to change the name of the precompiled header that C++/WinRT uses in my project through the 'Additional Parameters' option inside of the project properties, with no success.

When specifying the `-pch` parameter with an argument like so:
![image](https://user-images.githubusercontent.com/16063321/126052516-85d672ff-0c65-4280-8117-acabe0bf5cd5.png)

The build fails with the line `cppwinrt : error Option 'pch' accepts at most 1 value(s)` present in the build output.

I decided to look into this further and try to determine exactly what arguments `cppwinrt.exe` was receiving by investigating the contents of the `<project name>.vcxproj.cppwinrt_comp.rsp`, `<project name>.vcxproj.cppwinrt_plat.rsp`, and `<project name>.vcxproj.cppwinrt_ref.rsp` files generated inside of the `Debug` folder.

With no `-pch` parameter specified, the `<project name>.vcxproj.cppwinrt_comp.rsp` file includes the parameters `-name <project name> -pch <project name>.h`, suggesting that by default, the default name of the PCH file generated is simply the parent project's name. However, the help output for `cppwinrt.exe` seems to suggest that the default name is `pch.h`, and this is also what is used within the generated code.

This leaves me with the question: Have I interpreted the function of `-pch` correctly, and if so, is this behaviour I'm experiencing a bug or just misuse of the parameter?

**Comment by sylveon** [comment]
-pch is used when generating component templates

If you want to change the PCH of a cppwinrt project, you need to go in project properties and change it from "C/C++ > Precompiled Headers"

**Comment by syndek** [comment]
From what I can tell, files generated by `cppwinrt.exe` (i.e. everything under the `Generated Files` folder) don't respect this setting, and still try to use a file called `pch.h` which won't exist if your project is using a different name for the PCH file.

**Comment by sylveon** [comment]
Ah, I misread the source. (`-pch` only works with `-comp`, and `-comp` is described as "Generate component templates, and optional implementation")

The cppwinrt compiler gets passed the right `-pch` flag automatically by the IDE to match project settings, according to:
https://github.com/microsoft/cppwinrt/blob/c97862759284e786f8c4e1c11cd09d89bf90c553/nuget/Microsoft.Windows.CppWinRT.targets#L795-L808

So the additional argument that was added means there are two `-pch` directives, and manually writing that in a console does give the same error:
```
cppwinrt.exe -comp -ref sdk -pch "pch.h" -pch "test.h"
cppwinrt : error Option 'pch' accepts at most 1 value(s)
```

So updating the precompiled header location under Project Properties > C/C++ > Precompiled Headers and then rebuilding the project yields correct codegen (for example here `module.g.cpp`, with the PCH set to `test.h`):
![image](https://user-images.githubusercontent.com/6440374/126054730-69ed773e-724a-4b9b-80d1-617fca759891.png)

No need to manually pass arguments to cppwinrt :)

**Comment by syndek** [comment]
@sylveon Thanks, this makes a lot more sense. I didn't realise that `cppwinrt.exe` would respect the project's PCH name by default.

However, there's still one problem, and it's the same problem that originally led me to investigate using the `-pch` parameter. Some generated files (namely `XamlTypeInfo.Impl.g.cpp` and `XamlLibMetadataProvider.g.cpp`) are still trying to include `pch.h`, which for obvious reasons doesn't exist. As a result, the project won't compile.
![image](https://user-images.githubusercontent.com/16063321/126055722-56d7f788-55a9-4e5c-b867-561e3bdb2a69.png)

**Comment by sylveon** [comment]
Those aren't generated by cppwinrt, they are generated by the XAML compiler. It's a bug in their product and an issue should be opened in https://github.com/microsoft/microsoft-ui-xaml. 

I don't expect it to get fixed with the system XAML compiler however, as the system XAML compiler is in maintenance mode and all non-critical fixes get into the WinUI 3 XAML compiler instead.

**Comment by syndek** [comment]
Ah, okay then. My assumption was that all the files under `Generated Files` were generated by C++/WinRT. Thanks for clearing this up for me!
