### ISSUE TITLE
 error C2672: 'unbox_value_type': no matching overloaded function found

### ISSUE THREAD

**Issue by SergeyPachkov** [microsoft/cppwinrt#987]
I got this error when try to compile sample in VS2019 with cppWinRT 2.0.210722.2
from https://docs.microsoft.com/en-us/windows/win32/api/webauthenticationcoremanagerinterop/nn-webauthenticationcoremanagerinterop-iwebauthenticationcoremanagerinterop

`
using winrt::Windows::Security::Authentication::Web::Core::WebAuthenticationCoreManager;

{
     auto managerFactory = winrt::get_activation_factory<WebAuthenticationCoreManager>();
     winrt::com_ptr<IWebAuthenticationCoreManagerInterop> managerInterop{ managerFactory.as<IWebAuthenticationCoreManagerInterop>() };
}
`
error output is:
1>\x64\Debug\Generated Files\winrt\Windows.Foundation.h(3066,20): error C2672: 'unbox_value_type': no matching overloaded function found
1>\x64\Debug\Generated Files\winrt\base.h(2085): message : see reference to function template instantiation 'auto winrt::impl::as<To,winrt::impl::unknown_abi,0>(From *)' being compiled
1>        with
1>        [
1>            To=IWebAuthenticationCoreManagerInterop,
1>            From=winrt::impl::unknown_abi
1>        ]

**Comment by sylveon** [comment]
You need to include `<Unknwn.h>` before any cppwinrt header to enable classic COM support.
