### ISSUE TITLE
Error with StorageFile::GetFileFromPathAsync

### ISSUE THREAD

**Issue by JackDetrick** [Microsoft/cppwinrt#99]
I have this code:
auto _file = co_await StorageFile::GetFileFromPathAsync(L"FileDoubles.dbo"); 
where the file does  NOT yet exist.

In debug mode, when it returns it does not go to the next instruction instead it goes to the end of the method and seems to hang..

**Comment by kennykerr** [comment]
You can either wrap the `co_await` statement inside a try-block or call the `get()` method on the coroutine type, which will rethrow any exception thrown within the coroutine.

**Comment by JackDetrick** [comment]
I tried 'try catch (...)' with the same results. The  problem is that the StorageFile class doesn't provide any method to determine if a file exists.

**Comment by BrentRector** [comment]
You can use StorageFolder.TryGetItemAsync. But it requires starting from a folder, not a full path.

**Comment by JackDetrick** [comment]
Thanks...
