### ISSUE TITLE
Base classes using winrt::implements fail to compile with /std:c++20

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#990]
Attached project fails to compile:

1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6709,24): error C2672: 'to_abi': no matching overloaded function found (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6706): message : see reference to function template instantiation 'void *winrt::impl::interface_list<winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged>::find<T,Predicate>(const T *,const Predicate &) noexcept' being compiled
1>        with
1>        [
1>            T=winrt::BlankApp3::implementation::ViewModel,
1>            Predicate=winrt::impl::iid_finder
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6711): message : see reference to function template instantiation 'void *winrt::impl::interface_list<winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged>::find<T,Predicate>(const T *,const Predicate &) noexcept' being compiled
1>        with
1>        [
1>            T=winrt::BlankApp3::implementation::ViewModel,
1>            Predicate=winrt::impl::iid_finder
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6817): message : see reference to function template instantiation 'void *winrt::impl::interface_list<winrt::BlankApp3::ViewModel,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged>::find<T,winrt::impl::iid_finder>(const T *,const Predicate &) noexcept' being compiled
1>        with
1>        [
1>            T=winrt::BlankApp3::implementation::ViewModel,
1>            Predicate=winrt::impl::iid_finder
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6817): message : see reference to function template instantiation 'void *winrt::impl::interface_list<winrt::BlankApp3::ViewModel,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged>::find<T,winrt::impl::iid_finder>(const T *,const Predicate &) noexcept' being compiled
1>        with
1>        [
1>            T=winrt::BlankApp3::implementation::ViewModel,
1>            Predicate=winrt::impl::iid_finder
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(7844): message : see reference to function template instantiation 'winrt::impl::unknown_abi *winrt::impl::find_iid<D>(const T *,const winrt::guid &) noexcept' being compiled
1>        with
1>        [
1>            D=winrt::BlankApp3::implementation::ViewModel,
1>            T=winrt::BlankApp3::implementation::ViewModel
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(7844): message : while compiling class template member function 'void *winrt::implements<D,winrt::BlankApp3::ViewModel,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,winrt::BlankApp3::BindableBase>::find_interface(const winrt::guid &) noexcept const'
1>        with
1>        [
1>            D=winrt::BlankApp3::implementation::ViewModel
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\ViewModel.g.h(10): message : see reference to class template instantiation 'winrt::implements<D,winrt::BlankApp3::ViewModel,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,winrt::BlankApp3::BindableBase>' being compiled
1>        with
1>        [
1>            D=winrt::BlankApp3::implementation::ViewModel
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\ViewModel.h(10): message : see reference to class template instantiation 'winrt::BlankApp3::implementation::ViewModel_base<winrt::BlankApp3::implementation::ViewModel,winrt::BlankApp3::BindableBase>' being compiled (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6706,1): error C2784: 'abi<T,void>::type *winrt::to_abi(const winrt::impl::producer<D,I,void> *) noexcept': could not deduce template argument for 'const winrt::impl::producer<D,winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged,void> *' from 'const T *'
1>        with
1>        [
1>            T=winrt::BlankApp3::implementation::ViewModel
1>        ] (compiling source file ViewModel.cpp)
1>D:\Projects\BlankApp3\BlankApp3\Generated Files\winrt\base.h(6675): message : see declaration of 'winrt::to_abi' (compiling source file ViewModel.cpp)
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
1>Done building project "BlankApp3.vcxproj" -- FAILED.
[BlankApp3.zip](https://github.com/microsoft/cppwinrt/files/6888114/BlankApp3.zip)
[BlankApp3.zip](https://github.com/microsoft/cppwinrt/files/6888116/BlankApp3.zip)

**Comment by kennykerr** [comment]
Can you share a minimal repro? I can't open the attached project. 

I guess I may have to wait until the VSIX has been fixed. @DefaultRyan can we publish another version with your fix?

**Comment by DefaultRyan** [comment]
This doesn't have anything to do with the standalone VSIX. I think what's happening here is that the preview Component VSIX (included with VS preview) is referencing a nonexistent Nuget version. I was able to load the project by changing manually editing the versions in packages.config and the vcxproj.

When I changed them to reference cppwinrt 2.0.210722.2, and std:c++17, I'm getting a XamlCompiler error:
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(410,5): XamlCompiler error WMC0901: A type with a full name of 'BlankApp3.ViewModel' already exists in an included reference.

Which version of VIsual C++ are you using?

**Comment by jlaanstra** [comment]
That error seems odd as there are no other references in this project. I'm seeing this in VS2022.

**Comment by jlaanstra** [comment]
@DefaultRyan I can make the repro target a specific NuGet package if that helps?

**Comment by DefaultRyan** [comment]
I looked into it, and I'm not quite sure how this is working in C++17 mode. You have your base class, `BindableBase` that implements `INotifyPropertyChanged` as well as your derived class `ViewModel` that implements the same interface.

In C++20 mode, it's trying basically to convert `ViewModel*` to `winrt::impl::producer<D, INotifyPropertyChanged>*` for some `D`, and it rightly can't figure out what `D` should be, because both `ViewModel` and `BindableBase` would work.

I coded up a simplified repro https://godbolt.org/z/1GedqEKbx with both clang and msvc (2019), and clang also rejects this in C++17 mode. While it's *possible* that clang and VS2022 in C++20 mode are rejecting valid code, it's more likely that they are both correctly rejecting this code, and VS2022 in C++17 mode (and VS2019) are incorrect by allowing this to work and deducing `D` as `ViewModel`.

**Comment by jlaanstra** [comment]
If that's true, then how would I have a base class implement a WinRT interface?

**Comment by sylveon** [comment]
What I do is just implement the functions, without actually deriving from winrt::implements. When I inherit from that class in a Windows Runtime class, cppwinrt will correctly pick up the functions from the other base class.

**Comment by jlaanstra** [comment]
https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern CRTP works well for this. Updated BindableBase to be a template following this pattern resolved things.
