### ISSUE TITLE
guid parse errors can't be caught and handled at runtime

### ISSUE THREAD

**Issue by dfields-msft** [microsoft/cppwinrt#991]
The `winrt::guid` constructor that accepts a string calls `abort()` on failure instead of throwing an exception. This precludes the application from handling the error, e.g. to show a message to the user or fall back to default inputs. There is also no `try_parse()` function, so the `guid` parsing functionality of the library is limited to strings which are a priori known to be valid GUIDs.

**Comment by kennykerr** [comment]
Yes, these are constexpr constructors meant to be used with literals at compile time. If you want to do it at run time you can always use a function like `CLSIDFromString`.

**Comment by dfields-msft** [comment]
`CLSIDFromString` is quite clumsy and "un-modern" compared with the parsing constructor for `winrt::guid`. If the `abort()` were simply changed to a `throw`, it would be just as good for `constexpr` (perhaps better, since `abort()` itself isn't strictly `constexpr`), and also better suited for runtime use, which is available either way since `constexpr` functions are exposed for runtime use. What disadvantage is there to using `throw` instead?

**Comment by dfields-msft** [comment]
Yes, I've successfully used `throw` in `constexpr` with Clang and MSVC before, and the documentation suggests that this is normative (in that a `constexpr` branch which evaluates to a `throw` statement is malformed and will fail to compile, but that a constexpr function may contain a `throw` statement that is not evaluated for a given compile-time invocation without error). See:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-50
https://en.cppreference.com/w/cpp/language/constexpr
https://en.cppreference.com/w/cpp/language/constant_expression
