### ISSUE TITLE
Unclear error message if `winrt/Windows.Foundation.h` isn't included before awaiting an `IAsyncOperation`

### ISSUE THREAD

**Issue by sylveon** [microsoft/cppwinrt#996]
When building the following code
```cpp
#include <iostream>
#include <winrt/Windows.System.h>

winrt::fire_and_forget OpenUri(const winrt::Windows::Foundation::Uri &uri)
{
	bool opened;
	try
	{
		opened = co_await winrt::Windows::System::Launcher::LaunchUriAsync(uri);
	}
	catch (const winrt::hresult_error& err)
	{
		std::wcout << std::wstring_view(err.message());
	}

	// do something if opened is false
}
```

The error `error C2338: Not an awaitable type` is given, which is confusing because `LaunchUriAsync` returns an `IAsyncOperation<bool>`, which is indeed an awaitable type. This happens because the awaitable support machinery is in `<winrt/Windows.Foundation.h>`, which was never included. The solution is to include that header.

cppwinrt should try giving a better error in these cases (for example, `<winrt/Windows.Foundation.h> needs to be included to await IAsyncOperation`).

**Comment by kennykerr** [comment]
I'm not sure how cppwinrt as a library could do any better since the error comes from the compiler. Do you have a suggestion?

**Comment by sylveon** [comment]
Actually, the error comes from cppwinrt:
https://github.com/microsoft/cppwinrt/blob/464e59198c2046125d8ee5a8cc6ff1739097345f/strings/base_coroutine_threadpool.h#L239

I'm thinking we could forward-declare `IAsyncAction`, `IAsyncOperation<T>` and friends in this file, then if the case that contains this assert is hit, use an `if constexpr` to detect that it's an `IAsyncAction`/`IAsyncOperation<T>`/etc. and adjust the error message accordingly.

**Comment by kennykerr** [comment]
Ah, forgot about that... `get_awaiter` is some serious hackery to enable suspension point hooking, which is an extremely brittle feature requested by the OS team and, as far as I'm aware, to date unused. Gor tells me that the standard library will eventually make it redundant. I would be inclined to remove it in future but certainly not build on it.  If you can find a simple way to make that work I'm not apposed to it but there's just a lot of technical debt piled up here that really needs to be paid down first.
