### ISSUE TITLE
Rename or customize name of hresult_error?

### ISSUE THREAD

**Issue by damyanp** [microsoft/cppwinrt#997]
We're using cppwinrt in the implementation a DLL that's loaded inproc.  Various internal operations may fail in ways that result in an hresult_error exception being thrown and then caught by the DLL and handled as appropriate.

The issue is that users of our DLL would like to be able to set breakpoints for when hresult_errors might be thrown by their code, but ignore ones that would be thrown just by our module.

We could try and move away from using cppwinrt for these, but I was wondering if there's any customization point we could use.  One thing I considered was doing something like `#define hresult_error hresult_error_internal` before including any of the cppwinrt headers, but that does feel a bit icky.

**Comment by kennykerr** [comment]
Does "Just My Code" affect this behavior?

https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2019

I'm not sure whether it impacts how exceptions are handled though.

You're also free to throw your own exception types derived from `hresult_error` but if you're talking about the exceptions thrown by C++/WinRT you can, as a last resort, hook `winrt_throw_hresult_handler` and throw whatever you'd like. This is what is used by WIL internally.

**Comment by damyanp** [comment]
Ah, thank you - `winrt_throw_hresult_handler` is exactly what I'm looking for.  I think I need to refresh the version of cppwinrt I'm using, because it's not in that one :)

**Comment by damyanp** [comment]
@kennykerr - winrt_throw_hresult_handler is declared noexcept, which kind of makes it hard to throw my own type of exception from it.  Am I missing a trick?

**Comment by kennykerr** [comment]
Looks like an oversight. I don't actually use any of these hooks, which may be why this is noexcept. 😉 

https://github.com/microsoft/cppwinrt/blob/4ba22a67d7fb24d2ae0c0472d3cdaaeb4b013465/strings/base_extern.h#L2-L7

I suspect the linker just collapses the symbols so the replacement provided by WIL can throw and everything is fine.

They're all there regrettably to support some necessity in the OS and I'd rather folks not use them as it makes improving C++/WinRT down the road much harder. Anyway, let me know if that doesn't work if your replacement function pointer throws an exception.

**Comment by damyanp** [comment]
I think wil just uses it for logging the error rather than throwing a different exception.

**Comment by dmachaj** [comment]
That's right.  The WIL `winrt_throw_hresult` override is simply so that WIL's logging library can be aware of exceptions that cppwinrt is about to throw.  It isn't to have WIL throw anything.
