### ISSUE TITLE
winrt::resume_on_signal() does not timeout immediately for all negative inputs

### ISSUE THREAD

**Issue by matthewjones-microsoft** [microsoft/cppwinrt#998]
### SUMMARY

winrt::resume_on_signal() does not do an immediate timeout for all negative inputs. This does not match the documented behaviour.

For example:

```
// Expected: immediate timeout
// Observed: infinite timeout
co_await winrt::resume_on_signal(handle, TimeSpan::min());

// Expected: immediate timeout
// Observed: infinite timeout
co_await winrt::resume_on_signal(handle, -TimeSpan::max());
```

The code in winrt::resume_on_signal() that converts the timeout for use with SetThreadpoolWaitEx() is incorrect.

---

### DETAILS

The documentation for winrt::resume_on_signal() states that an immediate timeout occurs if a negative timeout is passed as a parameter. However, for many negative timeout values the current implementation behaves as if the timeout were infinite (not zero).

Notation: 
- **now** = immediate timeout
- **never** = infinite timeout
- **later** = finite timeout (relative time, some time span after _now_)
- **when** = absolute timeout (absolute time, independent of _now_)

The resume_on_signal() function uses the following curious conventions for the timeout parameter:
- **negative** = immediate timeout (now)
- **zero** = infinite timeout (never)
- **positive** =  finite timeout (later)

Internally this function calls SetThreadpoolWaitEx(), which uses the following _different_ curious conventions:
- **negative** = finite timeout (later)
- **zero** = immediate timeout (now)
- **positive** = absolute timeout (when)
- **null** = infinite timeout (never)

#### Correct Timeout Conversion

The correct way to convert the timeout from resume_on_signal() conventions to SetThreadpoolWaitEx() conventions is therefore:
-  **resume_on_signal -> SetThreadpoolWaitEx**
-  **now:** negative -> zero
-  **never:** zero -> null
-  **later:** positive -> negative

#### Current Timeout Conversion

However, the current resume_on_signal() implementation does this conversion:
-  **resume_on_signal -> SetThreadpoolWaitEx**
-  **now** negative -> <del>zero</del> positive (**when**)
-  **never** zero -> null
-  **later** positive -> negative

Note that when a negative timeout is specified (timeout _now_), the actual behaviour is an absolute timeout (timeout _when_). It is then interpreted as an absolute time (in 100ns clock periods since the Win32 FILETIME epoch, 1 January 1601).

In practice this means that timeouts closer to zero than -(2^56) work correctly, but timeouts further from zero than around -(2^57) work incorrectly. This is because 2^56 represents a FILETIME in the distant past (19th century), whereas 2^57 represents a FILETIME in the distant future (mid 21st century).

Depending on the current date/time and system clock, there is a particular bit representation somewhere between -(2^56) and -(2^57) where the current implementation switches from succeeding to failing. The exact value is the negative value of the current system clock measured in 100ns periods since 1601.

```
0xffffffff'ffffffff = -epsilon           succeeds
0xff000000'00000000 = -epsilon * 2^56    succeeds
0xfe000000'00000000 = -epsilon * 2^57    fails
0x80000000'00000001 = -TimeSpan::max()   fails
0x80000000'00000000 = TimeSpan::min()    fails

where epsilon = ++TimeSpan::zero()
```

_Most importantly, the most convenient timespans for specifying a negative value, namely TimeSpan::min() and -TimeSpan::max(), both behave incorrectly._

---

### POTENTIAL FIX

This issue can be fixed by changing the implementation await_suspend() in the function local struct resume_on_signal()::awaitable.

### Current Implementation:
```
int64_t relative_count = -m_timeout.count();
int64_t* file_time = relative_count != 0 ? &relative_count : nullptr;
```

### Fixed Implementation:
```
int64_t timeout = m_timeout.count();

int64_t now = 0;
int64_t later = -timeout;
int64_t* never = nullptr;

// Convert timeout from resume_on_signal() conventions to SetThreadpoolWaitEx() conventions.
int64_t* file_time =
    (timeout < 0) ? &now :
    (timeout > 0) ? &later :
    never;
```

The fixed implementation has been tested locally and winrt::resume_on_signal() appears to behave correctly for all negative inputs tested, including TimeSpan::min() and -TimeSpan::max() and various negated powers of two.

When using the current implementation, an infinite timeout (in practical terms) was observed for TimeSpan::min(), TimeSpan::max() and for values further from zero than -(2^57).

**Comment by kennykerr** [comment]
C++/WinRT is built on the Windows thread pool and a zero timeout isn’t supported by the thread pool. For that you can use `WaitForSingleObject`. I talked about that here:

https://docs.microsoft.com/en-us/archive/msdn-magazine/2011/november/windows-with-c-thread-pool-synchronization

**Comment by matthewjones-microsoft** [comment]
This issue has been discussed and resolved offline (thanks all).

Because the function does _not_ immediately timeout for all negative inputs, the documentation has now been updated to accurately reflect this. It no longer says that an immediate timeout occurs, and now says that behaviour is undefined.

https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/resume-on-signal

> _timeout An optional timeout value. If you pass a timeout of 0, that's treated as infinite. **Behavior is undefined if you pass a negative timeout.**_

The implementation has been left unchanged to avoid further development/testing costs and introducing backward compatibility issues.
